### ISSUE TITLE
flatMapLatest of Subject race condition? 

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#1001]
I haven't seen this issue yet, but I wanted to proactively make sure it wouldn't break my code.

If I have an Observable, that I am then `flatMapLatest`ing on, is it possible for me to miss some of the events from the Observable while my `flatMapLatest` is being recomputed?

So in this example:

```swift
let producers = Variable([producerOne])

producers.asObservable()
    .flatMapLatest { latestProducers -> Observable<String> in
        let strings = latestProducers
            .map { $0.asObservable() }

        return Observable.from(strings).merge()
    }
    .subscribe(onNext: { print($0) })

producerOne.onNext("1 -- A") // prints 1 -- A
producerTwo.onNext("1 -- B") // no output as expected

producerOne.onNext("2 -- A") // prints 2 -- A

producers.value.append(producerTwo) // LINE OF INTEREST 

producerTwo.onNext("1 -- B") // prints 1 -- B
```

Is it possible for either of my Observables (that potentially are on a different thread) to receive an event whist I'm not subscribed? During my `flatMapLatest` being called (when I call `producers.value.append(producerTwo) ` for example)? 
Since I've now disposed the subscription to my Observable of `[producerOne]`, and I have not yet subscribed to my Observable of `[producerOne, producerTwo]`?

**Comment by kzaher** [comment]
Hi @AndrewSB ,

yes, it's possible that some element won't be printed if certain threading conditions are met. I wouldn't call it lost because the system is behaving properly, but yep.

**Comment by AndrewSB** [comment]
That makes sense, yeah, the system is behaving properly.

Do you have any experience mitigating events that might not be subscribed to while flatMapLatest is being computed?

* Should I create a temporary event sink for my array of observables that is only active while the flatMapLatest is being recomputed, and then pull events off their once my flatMapLatest is done?
* Or instead not use flatMapLatest, but flatMap instead? and then add additional data to the element in a tuple (a counter for which iteration of flatMapLatest this is perhaps), and filter out all events that aren't from the latest counter?

**Comment by kzaher** [comment]
Hi @AndrewSB ,

I would suggest trying to redesign your problem, it seems to me that your current approach is too complicated. I'm sure there are probably simpler solutions.

Since this is not an issue per se, let's close this one. Maybe somebody in slack channel can help you brainstorm the solution.
