### ISSUE TITLE
Model a Future in RxSwift? Maybe with a shim off AsyncSubject?

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#1002]
Has anyone thought of using Futures with `Observable`s? 
Maybe by creating a new specialization of `SharedSeqeuence`? It seems very similar to what my not-very-elaborate understanding of [AsyncSubjects](http://reactivex.io/documentation/subject.html).

My main longing for something like this is to model my network or DB requests - it feels a heavy to have to `subscribe`, and then handle the `complete` event along with the `next` and `error` in my `switch`, where I'm assuming to only get one `.next` OR one `.error`. Usually my I just `break` out of the `complete` case.

Moreover, I usually have an implicit assumption that I'm only going to get an event once, and having that contract break from under me could cause subtle bugs that would be hard to catch (for example, doing something stateful in a view controller's subscribe function that I only expected to have called once).

Would I be better of just using a Future in this case? I could just create a new `flatMap` function on `Observable` that accepts a `Future`, and use another futures library. It doesn't feel as nice as something native, but I'd understand if it is out of scope for RxSwift

**Comment by kzaher** [comment]
Hi @AndrewSB ,

> Has anyone thought of using Futures with Observables?

Yes, it is kind of possible to model Futures with `SharedSequence`, but I would consider that more of an educational example :)

> My main longing for something like this is to model my network or DB requests - it feels a heavy to have to subscribe, and then handle the complete event along with the next and error in my switch, where I'm assuming to only get one .next OR one .error. Usually my I just break out of the complete case.

You don't have to, you can just write `.subscribe(onNext: { element in  })`. All events are optional.

> Would I be better of just using a Future in this case? I could just create a new flatMap function on Observable that accepts a Future, and use another futures library. It doesn't feel as nice as something native, but I'd understand if it is out of scope for RxSwift

Hm, why would you want to use futures here? What are the benefits?

**Comment by AndrewSB** [comment]
The reason I'd like to be able to use Futures is two-fold.

1. Futures are more approachable to people on my team who are new to Reactive programming, they feel very comfortable when there's a async event that is modeled with `Future<T>` instead of `Observable<T>`, even though the end result is almost exactly the same

2. More importantly, from a ideological standpoint I'd want to be represent a temporal computation that only returns one event.  [RxJS's documentation](https://github.com/Reactive-Extensions/RxJS/blob/aaebfe8962cfa06a6c80908d079928ba5b800c66/doc/readme.md) goes into the idea I bit. Copied here: 

<center>  	
<table>
   <th></th><th>Single return value</th><th>Mutiple return values</th>
   <tr>
      <td>Pull/Synchronous/Interactive</td>
      <td>Object</td>
      <td>Iterables (Array | Set | Map | Object)</td>
   </tr>
   <tr>
      <td>Push/Asynchronous/Reactive</td>
      <td>Promise</td>
      <td>Observable</td>
   </tr>
</table>
</center>

, as does kriskowal's [A General Theory of Reactivity](https://github.com/kriskowal/gtor) (which is where I first was exposed of the shortcoming) goes into great detail, his model of Spatial and Temporal (the table above) especially:

>  Rx conflates all reactive primitives into a single Observable type that can perform any role. Just as an array is an exemplar of an entire taxonomy of collections, promises, streams, and observables are merely representatives of their class of reactive primitives. As the common paraphrase of Einstein goes, everything should be made as simple as possible, but no simpler.

To me, it feels like not being able to express something that is an async single-return-value is akin to not being able to represent a sync sync single-return-value: i.e. no variables, only arrays. Every value you have would have to be wrapped in an array of count 1.

IMHO not being able to represent a Future, and limiting oneself to an async multiple-return-value adds incidental complexity & overhead on every Observable that only offers one event before completing.
 
At the call site, for example: a developer writing against an Observable<SomeAPIResponse> accepts an implicit contract that they're only going to get see `.next`, or `.error` before a `.complete`. Leading to brittle code (the code may break if drastic action was caused in the `.next`/`.error` subscription: presenting error alerts & mutating the navigation stack/showing a success state)

Not sure if this is something that should be represented directly through RxSwift, or if people should include their own Future implementation and write the machinery to get their Future to interop wth Rx (being cognizant of keeping size of RxSwift's binary ⬇️). 
This may just be an issue for me, as I'm using RxSwift to model my network API requests, which are being called from my view/business logic layer. RxJS is looking at this too though, but I think the README a linked to was a beta version, I'm not sure since I haven't used it

**Comment by fpillet** [comment]
@AndrewSB I don't think this would go into core, but could be a good case for implementation in a separate repository contributed to RxSwiftCommunity. You could easily start a RxFutures repository that relies on RxSwift for a very simple to write implementation of futures.

**Comment by AndrewSB** [comment]
@fpillet that sounds good, can I be added to RxSwiftCommunity?

Also, do you have any ideas on how I should implement one `.next` event? I saw three possibilities:
1. Automatically send a `.complete` once a `.next` is seen. This would be slightly hacky, and not symmetric with how the error state doesn't `.complete`, but would make it so the Observable is resolved, and can no longer accept future events
2. Modify the `.next` event to act like the `.error` event in this Futures subclass of `Observable` (or `SharedSequence`). I like this one the most, but I'm not sure how easy it is to implement
3. `rxFatalError` is an event is pushed into the RxFuture after an initial `.next`

**Comment by fpillet** [comment]
I added you to RxSwiftCommunity.

Solution 1 seems the most logical, since a Future is expected to emit a single item, right? In this respect, RxJava has `Single` which does exactly that (we do have it too). Your Future thing could simply be a wrapper around RxSwift's `single()` operator.

**Comment by AndrewSB** [comment]
@fpillet: that makes sense to me, thank you for the guidance!

**Comment by AndrewSB** [comment]
#1123 created `Single`, which supersedes this issue 😊
