### ISSUE TITLE
why ? 

### ISSUE THREAD

**Issue by CrazyCoderShi** [ReactiveX/RxSwift#1003]
```
    @IBOutlet weak var phoneNumber: UITextField!
    @IBOutlet weak var password: UITextField!
    override func viewDidLoad() {
        super.viewDidLoad()

        let viewModel = ViewModel(phoneNumberText: phoneNumber.rx.text.asDriver(),
                                  passwordText: password.rx.text.asDriver())
     }
```
When i decleared viewModel, get error: 'inout UITextField' does not conform to protocol 'ReactiveCompatible'
sorry for my bad English😱

**Comment by sergdort** [comment]
Hi, @CrazyCoderShi 
What is the type of `passwordText ` in your `ViewModel`?
Is it `Driver<String>` ?

**Comment by CrazyCoderShi** [comment]
@sergdort yes

**Comment by sergdort** [comment]
But the type of `rx.text` is `ControlProperty<String?>`
https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UITextView%2BRx.swift#L31

**Comment by sergdort** [comment]
I believe you need to do 
```
.map { $0 ?? "" } // Observable<String>
```

**Comment by kzaher** [comment]
There is also 

```
let viewModel = ViewModel(phoneNumberText: phoneNumber.rx.text.orEmpty.asDriver(),
                                  passwordText: password.rx.text.orEmpty.asDriver())
```

that has that `.map { $0 ?? "" }` internally.

**Comment by CrazyCoderShi** [comment]
Thx @kzaher, it works.

**Comment by xuech** [comment]
@kzaher, it works for me , haha ,nice!
