### ISSUE TITLE
can not see log printed out with PublishSubject

### ISSUE THREAD

**Issue by tranvutuan** [ReactiveX/RxSwift#1004]
I am experiencing with PublishSubject by following
```
// 1. Create a PublishSubject
let sequence = PublishSubject<Int>()
// 2. Using map to do some transformation
let a = sequenceOfInts.map { number -> Int in
            print("Mapping \(number)")
            return i * 2
        }
// 3. emits new element
sequence.on(.Next(1))

// 4. subcribe and get the new result
a.subscribeNext { x in print("--1--\(x)") }
 .addDisposableTo(disposeBag)
```

I'm not sure why printing statements are not shown on the console. Did I miss something in the middle

**Comment by dangthaison91** [comment]
@tranvutuan You need to subscribe Observable before it emits value.

**Comment by tranvutuan** [comment]
@dangthaison91:it works.One thing still bothers me: I'm thinking about rss feed service.it exists before we subscribe To the service.that means it already emits then we subscribe to it later on.that is why in my sample,i subscribe later on.

**Comment by dangthaison91** [comment]
You should use BehavourSubject or RelaySubject instead.

**Comment by tranvutuan** [comment]
make sense now,i will give it a try.thanks

**Comment by dangthaison91** [comment]
@tranvutuan Please close your issue if you don't have any question. For more question, you can join in RxSwift slack channel.
