### ISSUE TITLE
"Search Wikipedia" example generates unnecessary network traffic

### ISSUE THREAD

**Issue by Czajnikowski** [ReactiveX/RxSwift#1010]
**Short description of the issue**:

  When you launch `WikipediaSearchViewController` the app continuously generates network requests without any interaction from the user.

**Expected outcome**:

  Request should be started only when user changes a query in a search bar.

**What actually happens**:

  App generates constant network traffic (~ 20 kB/s) even when no query has been set in the search bar. In the console we can observe repeating logs like this:

```
...
curl -X GET 
"http://en.wikipedia.org/w/api.php?action=opensearch&search=" -i -v
Success (187ms): Status 200
curl -X GET 
"http://en.wikipedia.org/w/api.php?action=opensearch&search=" -i -v
Success (167ms): Status 200
curl -X GET 
"http://en.wikipedia.org/w/api.php?action=opensearch&search=" -i -v
Success (175ms): Status 200
...
```

**Self contained code example that reproduces the issue**:

  Not necessary

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  `581a7583c7be22bd908d2ade551fde5b74d97757`

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro (**for me**)
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 8.1 (8B62)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Pure Github repo

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Version 7.3.1 (7D1014))
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @Czajnikowski ,

I think this should be fixed now.
