### ISSUE TITLE
how to avoid capture wrong value 

### ISSUE THREAD

**Issue by xnxin** [ReactiveX/RxSwift#1013]
**Short description of the issue**:

capture the old value 

**Expected outcome**:

  _what you expect to happen goes here_

**What actually happens**:

  there is two viewcontrollers, when launch, i go homepage ,and check the user's password is right, others present login, when login dismiss, i'll generate a new disposeBag,so if change user, it will rebind Viewmodel to homeview.

**Self contained code example that reproduces the issue**:

```swift
 init() {
        //avoid relogin capture wrong value.
        let userpassowrd = Observable.just((keychain[.account]!, keychain[.password]!))
        
        login = userpassowrd.flatMapLatest {
            
            return API.default.rx
                .model(url: URLAddress.Login.login.rawValue,
                       method: .post,
                       params: ["account":$0.0, "loginPwd":$0.1])
        }.retry(3)
        .shareReplay(1)
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  Latest

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 8.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:

  - [x] I have a small code base

**Comment by fpillet** [comment]
Use `Observable.defer` to defer creating an observable (and capturing values) to when an actual subscriber wants to subscribe

**Comment by xnxin** [comment]
ok， did you mean like this:
```swift
        //avoid relogin capture wrong value.
        let accountAndPassword = Observable.deferred{
            Observable.just((keychain[.account]!, keychain[.password]!))
        }
        
        login = accountAndPassword.flatMapLatest {
            
            return API.default.rx
                .model(url: URLAddress.Login.login.rawValue,
                       method: .post,
                       params: ["account":$0.0, "loginPwd":$0.1])
        }.retry(3)
        .shareReplay(1)
```
it also not work , i can change my account, but the controller is there, i just give it new disposeBag, the viewmodel still same one, Does I need KVO the keychain value?? or there has others solution?

**Comment by fpillet** [comment]
Your problem is not clearly explained. Which old value is being captured? Is it `keychain[.account]` that you are changing after the first request?

**Comment by xnxin** [comment]
OK, if there is A in keychain, first in home page, the API.default.rx will get A as params, if i logout on home page, and i login on presented loginviewcontroller , the keychain's value is B, but API.default.rx still got A, not the B

**Comment by kzaher** [comment]
Hi @xnxin ,

I think we would need to understand context of this to answer this.

Conceptually:
* I think you would need to create your own service that has some observing mechanism hook (maybe `BehaviorSubject` that stores that information)
* Just read the information right before you need it if you have have some external trigger to execute your operation.

Hoping maybe somebody on Slack channel can help you to understand how to solve this, not sure this is an efficient way.
