### ISSUE TITLE
Subscription performance in reusable views?

### ISSUE THREAD

**Issue by shappeluft** [ReactiveX/RxSwift#1015]
I have a table view that contains a list of reasonably complex cells. Each cell has 2 text fields and 2 buttons and I hook them up to a view model via observable subscriptions (each row has it's own view model). I'm having a problem with scroll performance (it's noticeably laggy). If I comment out the setup with the view model, the scrolling performance is fine.

One solution that I've found works is subscribing to the input observables on a background thread but it feels like a code smell. Any thoughts on improving subscription performance in reusable views?

More details:

I have 4 input subscriptions in combination with `takeUntil(prepareForReuse)` to ensure no events are sent after the cell has been reused (which I assume brings it up to 8 input observable subscriptions). I have 3 output subscriptions to make the view respond to the view model behaviour.

**Comment by kzaher** [comment]
Hi @shappeluft,

I'm not sure can we help you with the information you've provided.

I doubt dozen of observable sequences per cell could cause this, but maybe there is something weird happening.

If you would be kind enough to fill out our issue template with necessary information I would be happy to take a look (especially the part with self contained code that reproduces the issue).

We can either reopen this if we get enough information to investigate or feel free to just open a new issue.
