### ISSUE TITLE
UserDefaults.rx.observe won't initialize URL values upon onNext

### ISSUE THREAD

**Issue by DivineDominion** [ReactiveX/RxSwift#1016]
**Short description of the issue**:

Observing `UserDefaults` URL keys does trigger an `onNext` update but always reports `nil`.

**Expected outcome**:

```
text: nil
url: nil
url: Optional(file:///first/path)
url: Optional(file:///second/path)
text: Optional("first")
text: Optional("second")
text: nil
url: nil
```

**What actually happens**:

```
text: nil
url: nil
url: nil
url: nil
text: Optional("first")
text: Optional("second")
text: nil
url: nil
```

**Self contained code example that reproduces the issue**:

```swift
import Cocoa
import RxSwift
import RxCocoa

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {

    let defaults = UserDefaults.standard
    let disposeBag = DisposeBag()

    func applicationDidFinishLaunching(_ aNotification: Notification) {

        defaults.rx.observe(String.self, "text")
            .subscribeOn(MainScheduler.instance)
            .subscribe(onNext: { print("text: \($0)") })
            .addDisposableTo(disposeBag)

        defaults.rx.observe(URL.self, "url")
            .subscribeOn(MainScheduler.instance)
            .subscribe(onNext: { print("url: \($0)") })
            .addDisposableTo(disposeBag)

        self.defaults.set(URL(fileURLWithPath: "/first/path"), forKey: "url")
        self.defaults.set(URL(fileURLWithPath: "/second/path"), forKey: "url")

        self.defaults.set("first", forKey: "text")
        self.defaults.set("second", forKey: "text")

        NSApp.terminate(self)
    }

    func applicationWillTerminate(_ notification: Notification) {
        defaults.removeObject(forKey: "text")
        defaults.removeObject(forKey: "url")
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.1 (latest Carthage build)

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 8.1 (8B62)
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by DivineDominion** [comment]
It's pretty hard to figure out which generic extension does what. Safest workaround I found:

```swift
defaults.rx
    .observe(String.self, "url", options: [.new], retainSelf: true)
    .map{ $0.flatMap { URL(fileURLWithPath: $0) } }
    .subscribeOn(MainScheduler.instance)
    .subscribe(onNext: { print("url: \($0)") })
    .addDisposableTo(disposeBag)
```

... where the `map` operation has to pick a specific `URL.init` variant. Could be `URL.init(string: $0)`, too.

**Comment by kzaher** [comment]
Hi @DivineDominion ,

I see `URL` implements `ReferenceConvertible`. Maybe we can use that to improve our kvo integrations.

**Comment by DivineDominion** [comment]
A basic generic extension without any added value would be this:

```swift
extension Reactive where Base: NSObject {
    public func observe<E>(_ type: E.Type, _ keyPath: String, options: NSKeyValueObservingOptions = [.new, .initial], retainSelf: Bool = true) -> Observable<E?> where E : ReferenceConvertible {

        return KVOObservable(object: base, keyPath: keyPath, options: options, retainTarget: retainSelf).asObservable()
    }
}
```

But I don't understand Rx internals (or maybe generics 🤔) enough just yet to determine where to go from here. `KVOObservable<Element>` casts to `Element` in `subscribe`. You cannot add another `subscribe` with just another generic specification (`Element : ReferenceConvertible`) because that would still clash. 

Also, you cannot cast to `ReferenceConvertible` because of the associated type:

```swift
// does not compile (KVOObservable.subscribe)
let value = value as? Element
if let ref = value as? ReferenceConvertible {
    observer.on(.next(ref))
} else {
    observer.on(.next(value))
}
```

So we end up with another type, right?

## WIP Types

In `NSObject+Rx`:

```swift
extension Reactive where Base: NSObject {
    public func observe<E>(_ type: E.Type, _ keyPath: String, options: NSKeyValueObservingOptions = [.new, .initial], retainSelf: Bool = true) -> Observable<E.ReferenceType?>
        where E : ReferenceConvertible {

        return KVOReferenceObservable<E>(object: base, keyPath: keyPath, options: options, retainTarget: retainSelf).asObservable()
    }
}

fileprivate class KVOReferenceObservable<Element>
    : ObservableType
    , KVOObservableProtocol
    where Element : ReferenceConvertible {
    typealias E = Element.ReferenceType?

    unowned var target: AnyObject
    var strongTarget: AnyObject?

    var keyPath: String
    var options: NSKeyValueObservingOptions
    var retainTarget: Bool

    init(object: AnyObject, keyPath: String, options: NSKeyValueObservingOptions, retainTarget: Bool) {
        self.target = object
        self.keyPath = keyPath
        self.options = options
        self.retainTarget = retainTarget
        if retainTarget {
            self.strongTarget = object
        }
    }

    func subscribe<O : ObserverType>(_ observer: O) -> Disposable where O.E == Element.ReferenceType? {
        let observer = KVOObserver(parent: self) { (value) in
            if value as? NSNull != nil {
                observer.on(.next(nil))
                return
            }
            let value = value as? Element.ReferenceType
            observer.on(.next(value))
        }
        
        return Disposables.create(with: observer.dispose)
    }
}
```

That works inasmuch as I can get to `.on(.next(value))` here. But when I stop execution, using lldb to cast `value` to NSURL or URL produces `nil` both times. `value as? String` still works.

* `(value as? String).map(URL.init)`:  
    error: ambiguous use of 'init'
* `(value as? String).map(NSURL.init)`  
    error: Couldn't lookup symbols:
      __TFCSo5NSURLCfT15fileURLWithPathSS_S_

¯\_(ツ)_/¯

**Comment by kzaher** [comment]
Hi @DivineDominion ,

I've investigated this issue. 

```
po UserDefaults.standard.object(forKey: "url") as! Data
▿ 248 bytes
  - count : 248
  ▿ pointer : 0x00007fc210501340
    - pointerValue : 140471474066240
```

I think this is somewhat special case. It looks like URL extension methods on UserDefaults are serializing it as `NSData`.

The workaround that you've found can be simplified into 

```
defaults.rx
    .observe(String.self, "url", options: [.new], retainSelf: true)
    .map{ _ in defaults.url(forKey: "url") }
```

You can even create your own extension for URL.

I've tested for this behavior in case of normal KVO being performed on an object.

```
class HasStrongProperty : NSObject {

    dynamic var url: URL = URL(string: "hello://there.com")!

}
```

... and it seems it works there.

I would be fine leaving this alone as it is since this is not a problem with KVO mechanism, but a sideffect of `UserDefaults` extensions serializing URL as Data for storage purposes.

Hope the workarounds will be sufficient.
