### ISSUE TITLE
limitation : ObserverType and ObservableType protocol use same associatedtype name

### ISSUE THREAD

**Issue by SimpleApp** [ReactiveX/RxSwift#1018]
Since both ObserverType and ObservableType protocol use the same associatedtype letter (aka E), one can not create a class that observes one type and emits another (data flows can be completely unrelated, so using "map" isn't an option).

**What actually happens**:

Swift doesn't allow to use of the protocol's name to characterize the associatedtype you're typealiasing, so there isn't a way to express this behavior at all.

**Self contained code example that reproduces the issue**:

```swift

import RxSwift
struct Commands{}
struct ModelUpdates{}

  class MyComponent : ObservableType, ObserverType{
    typealias ObserverType.E = Commands
    typealias ObservableType.E = ModelUpdates
}
```
doesn't compile.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

**Platform/Environment**

  - [ x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
 Latest
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @SimpleApp ,

I agree this is a nuisance. As far as I'm aware of this is language level limitation like you've noticed.

I've been bitten by this before when defining subjects. This is how we've worked around it there.

```
/// Represents an object that is both an observable sequence as well as an observer.
public protocol SubjectType : ObservableType {
    /// The type of the observer that represents this subject.
    ///
    /// Usually this type is type of subject itself, but it doesn't have to be.
    associatedtype SubjectObserverType : ObserverType

    /// Returns observer interface for subject.
    ///
    /// - returns: Observer interface for subject.
    func asObserver() -> SubjectObserverType
    
}
```

I'm not aware is there any more elegant solution out there.

It seems the me that are two basic approaches:
* name them the same and language has a built in way to solve naming collisions (that would be ideal)
* name them different by encoding part of protocol name into typealias (which is ugly if you ask me)

**Comment by SimpleApp** [comment]
Agree that improving the language is the only good solution to the problem. However, i don't think finding different names for the associated types of the two most protocol of the library is such a great problem, especially since you've already had the problem (i first thought i was doing something very wrong). Swift standard library tend to now use full names instead of just uppercased letters.

However, if you feel like voting for this issue in Swift, here's the jira link to it : 
https://bugs.swift.org/browse/SR-1616

**Comment by kzaher** [comment]
Hi @SimpleApp ,

I think we can improve those names in 4.0 to be full names. `Element` vs just `E`. 
I guess the problem still remains the same. 

I'm betting that those issues will be solved on language level in the future so it made more sense to me to make a couple use cases slightly more inconvenient then all cases.

Since you are the first person so far complaining about this, I'm satisfied with statistics :)

¯\\\_(ツ)\_/¯

**Comment by SimpleApp** [comment]
Indeed, changing the name but keeping it identical in both protocols won't solve the problem  :))

No worries i don't think it is indeed such a big problem, and i don't measure the true impact on the library anyway.

**Comment by kzaher** [comment]
I don't think we can do anything about this right now. We can reopen this for 4.0. Hoping this will be solved on compiler level until then.
