### ISSUE TITLE
bindto failed

### ISSUE THREAD

**Issue by aofeng2009** [ReactiveX/RxSwift#1019]
I update cell by following code, when cell's data loaded  cell looks like well at first time.but when I make some changed on property value of 'selected', the 'bindto' have no effect?  why?

```
MyController.swift:
func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    var model = xxxxxxxxx
   cell.setModel(model)
}

MyTableViewCell.swift:
var model = PublishSubject<MyClass>()
 func setModel(newModel: MyClass) {
        self.model.onNext(newModel)
    }
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        self.setup()
    }
    
    func setup() {
        model.map{$0.selected}.bindTo(selectButton.rx_selected).addDisposableTo(disposeBag)
}

```

**Comment by kzaher** [comment]
Hi @aofeng2009 ,

couple of remarks:

* It's not clear where is `disposeBag` located and when it's being cleared. If you are clearing it on `prepareForReuse`, you'll destroy binding.
* `PublishSubject` is usually not convenient to model state. `BehaviorSubject` is more appropriate.
* you can use `debug` operator to figure out what's happening. Something like:

```
 model.map{$0.selected}.debug("my tag").bindTo(selectButton.rx_selected).addDisposableTo(disposeBag)
```
