### ISSUE TITLE
Create an array versions of zip and combineLatest operator for rxswift 2.0

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#102]

**Comment by kzaher** [comment]
This is done.

**Comment by orkenstein** [comment]
@kzaher 
Why does it takes `resultSelector: Function to invoke whenever any of the sources produces an element.`?
I think it must be nillable.

**Comment by kzaher** [comment]
Hi @orkenstein ,

why?

**Comment by orkenstein** [comment]
What is the purpose of this function?  What if I just want to call `combineLatest` on array?
Am I missing something?

**Comment by kzaher** [comment]
Usually when you combine something, you want to define how to combine multiple items.

I think that we could potentially make `resultSelector = { $0 }` by default.

`combineLatest` is usually followed by a `map` IMHO, but I guess I don't see any harm in adding a default value, and I don't think that's a breaking change.

**Comment by orkenstein** [comment]
Agree. I can publish a PR.

25 февр. 2016 г., в 2:30, Krunoslav Zaher <notifications@github.com>
написал(а):

Usually when you combine something, you want to define how to combine
multiple items.

I think that we could potentially make resultSelector = { $0 } by default.

combineLatest is usually followed by a map IMHO, but I guess I don't see
any harm in adding a default value, and I don't think that's a breaking
change.

—
Reply to this email directly or view it on GitHub
<https://github.com/ReactiveX/RxSwift/issues/102#issuecomment-188514064>.
