### ISSUE TITLE
Please provide a binary download to cut down on compile time

### ISSUE THREAD

**Issue by bensarz** [ReactiveX/RxSwift#1020]
**Short description of the issue**:

Compiling RxSwift and all of its components takes a considerable amount of time.

**Expected outcome**:

Carthage allows for prebuilt framworks:
https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**What actually happens**:

No binary is provided for tags (like 3.0.1).
This causes each machine to have to compile RxSwift and its components.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.1

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.1 with Swift 3.0.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @bensarz and guys :),

I guess I could try adding Carthage prebuilt frameworks for latest version. 

The downside of that approach is that if latest version of Xcode isn't used unexpected errors could happen.

I'm willing to try.

If somebody has any knowledge how that works with multiple xcode versions, that would be great.

I would feel a lot more comfortable if we had an option to upload binaries per toolchain version.

$FRAMEWORK_NAME.$TOOLCHAIN_VERSION.framework.zip

If somebody can push this, that would be great :)

**Comment by kzaher** [comment]
![attached](https://cdn.meme.am/cache/instances/folder189/500x/73738189.jpg)

**Comment by bensarz** [comment]
Awesome! thanks for this!

**Comment by AndrewSB** [comment]
@kzaher I was pleasantly surprised to notice the zipped binary. Thank you for deciding to give it a shot!
