### ISSUE TITLE
 The button event response on the cell is duplicated.

### ISSUE THREAD

**Issue by Abel94** [ReactiveX/RxSwift#1021]
**Short description of the issue**:

Use rx.tap monitor button on the cell click event and found that there are multiple responses per click, and whether the reuse of the cell? How to avoid?

**Self contained code example that reproduces the issue**:

```swift
cell.agreeBtn.rx.tap.subscribe(onNext: {
      print("click")
})
.addDisposableTo(cell.disposeBag)
```

**Comment by ralfwow** [comment]
1. is this piece of code inside cellForRowIndex? if so, move it back to init of the tableview cell. i can't really explain better than saying this "tap action" is being subscribed once more every time the cell is recycled.

**Comment by dangthaison91** [comment]
Did you re-create `cell.disposeBag` whenever cell is reused?
https://github.com/ReactiveX/RxSwift/issues/437

**Comment by Abel94** [comment]
Thank you all. I think the use of the cell disposeBag to avoid this problem, but found no, the original is not implemented prepareForReuse to re-instantiate disposeBag. Very grateful @dangthaison91  #437
