### ISSUE TITLE
Race condition while using UITextView RxDelegateProxy + custom delegate

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#1024]
**Short description of the issue**:

I'm using a `UITextView`, on which I've set a custom delegate, and I'm also using the `textView.rx` delegate methods.
I've noticed a potential race condition while setting the delegate.

When I set a breakpoint, the race condition dissipates, and when I don't, the bug from the race condition is present. I recorded a demo. http://sendvid.com/tw9ex5ui

I first run the app without breakpoints set around my custom delegate assignment to show the bug  caused by the race condition
At **0:17**, I set a breakpoint on my custom delegate's method that I expect to fire when the text in the text view is edited
At **0:27**, the app builds and run in the bug is visible. I'm entering text in the textview, and the rx bindings are working (theres a binding from the `textView.rx.text` that updates the character count in the bottom right corner of the screen, and it is changing from 12 to 13, 13 to 14, etc. as I edit text), but my breakpoint in my custom `DismissOnReturnTextViewDelegate` is not hit)
Then at **0:33**, I set breakpoints sandwiching my `textView.delegate =` assignment, this for some reason removes the bug seen. I re-run the app
From **0:59 - 1:10**, you can see the breakpoints being hit
At **1:13** I enter text into the text field, you can see that my breakpoint in `DismissOnReturnTextViewDelegate` is being hit (i.e. **the custom delegate is functioning as expected**), and my the character count label in the bottom right is also being updated (see **1:16**) (i.e. **the `.rx` delegate is functioning as expected**).
I go on to highlight the `.rx` textView delegate code that updates the characterCount label @ **1:25**

**Expected outcome**:

Both my `.rx` delegate closures are fired, along with my custom delegate methods

**What actually happens**:

Sometimes only the `.rx` delegate methods are called, sometimes both the `.rx` delegate methods and custom delegate methods are called.

**Self contained code example that reproduces the issue**:

Video demo at http://sendvid.com/tw9ex5ui

https://github.com/AndrewSB/wrytr/blob/master/wrytr/Legacy/Views/Main/Reusable/ComposeViewController.swift

`.rx` delegate method used here: https://github.com/AndrewSB/wrytr/blob/0ef5354ee7cb1abede38c349b23d3a916b908d69/wrytr/Legacy/Views/Main/Reusable/ComposeViewController.swift#L43

`.delegate` set here: https://github.com/AndrewSB/wrytr/blob/0ef5354ee7cb1abede38c349b23d3a916b908d69/wrytr/Legacy/Views/Main/Reusable/ComposeViewController.swift#L68

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.1

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
8.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @AndrewSB ,

If you are using `rx` methods on `UITextView` and also want to use your own delegate you need to use `rx.setDelegate(yourDelegate).addDisposableTo(disposeBag)` for everything to work.

**Comment by AndrewSB** [comment]
@kzaher that makes complete sense. Is there somewhere I could have found that documentation?

**Comment by AndrewSB** [comment]
@kzaher `rx.setDelegate(yourDelegate).addDisposableTo(disposeBag)` isn't working for me. My `.rx` bindings are still working, but my delegate is never called. I see that my delegate gets initialized (and doesn't get `deinit`ed), but never see any messages...

**Comment by kzaher** [comment]
Hi @AndrewSB ,

I've tried to test your repo but I can't compile both master branch and `2e962d1946afe5fe2bc79262525c4757cf47ebca`.

I would assume that the delegate deallocates because it's being weakly retained like normal delegate, but couldn't confirm because couldn't compile the project.

On the other hand I've tested the delegate and it seems to work for me. Here is the commit.
https://github.com/ReactiveX/RxSwift/commit/81a0393f45ae74b3b505c9b2d76c85244f3e6f20

**Comment by kzaher** [comment]
If you have any ideas where to document this I'm open to suggestions.

**Comment by AndrewSB** [comment]
I'll work on getting the project buildable by EOD.

I'm not sure either, maybe around the same place RxDelegateProxy is
documented?

**Comment by AndrewSB** [comment]
@kzaher: I've put up some installation instructions over [here](https://github.com/AndrewSB/wrytr/blob/master/README.md#installation). Could you see if you can get running after following them?

Responding to 
> I would assume that the delegate deallocates because it's being weakly retained like normal delegate, but couldn't confirm because couldn't compile the project.

should I hold a strong reference to my custom delegate in my view controller then?

**Comment by kzaher** [comment]
@AndrewSB 

> should I hold a strong reference to my custom delegate in my view controller then?

Yes, you can keep a strong reference or use

```
rx.delegate.setForwardToDelegate(DismissOnReturnTextViewDelegate(), retainDelegate: true)
```

**Comment by AndrewSB** [comment]
https://github.com/AndrewSB/wrytr/commit/e6fd0c6b4e78f34b155f02052d681f458c5da1da contains your fix, thanks @kzaher!
