### ISSUE TITLE
How to cutom extension ObservableType with value binding Enum 

### ISSUE THREAD

**Issue by xnxin** [ReactiveX/RxSwift#1027]
**Short description of the issue**:

I want to catch all Error to avoid observable dispose, so I define a enum of Result, just like this
```swift
public enum Result<Value> {
    case value(Value)
    case error(Error)
}
```
And I define a extension to take vale when result has value ,just like this
```swift
public extension ObservableType where E == Result<Any> {
    
    public func value<T>() -> Observable<T> where T: Mappable {
        
        return self.flatMapLatest { result -> Observable<T> in
            
            switch result {
            case .value(let value):
                guard let obj = value as? T else {
                    return Observable.empty()
                }
                return Observable.just(obj)
            case .error:
                return Observable.empty()
            }
        }
    }
}
```

But when I use this extension, I got an error,
```swift
func test() {
        let intTest = Observable.just(Result.value(44))
        let intValue = mm.value()
    }
}
```
the error say `error: 'Result<Any>' is not convertible to 'Result<Int>'`
**Expected outcome**:

I want to user template to define the extension , not Any

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 8.1
```
**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @xnxin ,

this is more of a Swift question. Please take a look at how `XXXConvertible` protocols are used in similar scenarios.

You'll need to write something like

```
protocol ResultConvertible {
    associatedtype Value
    associatedtype Error

    var result: Result<ResultValue, ResultError>
}

public extension ObservableType where E: ResultConvertible {
    public func value<T>() -> Observable<Result<E.Value, E.Error>> {
        ....
    } 
}
```
