### ISSUE TITLE
Buggy Schedulers

### ISSUE THREAD

**Issue by FGoessler** [ReactiveX/RxSwift#1032]
**Short description of the issue**:

It looks like that schedulers are either broken or the documentation about them is out of date. (Or I just get the docs wrong xD)

The [documentation](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Schedulers.md) states:
> In case subscribeOn isn't explicitly specified, the subscribe method will be called on the same thread/scheduler on which subscribe(onNext:) or subscribe is called.

However if I try this dummy example (executing this code on the main thread):
``` swift
let disposeBag = DisposeBag()
let obs = Observable<Int>.create({ obs in
    obs.onNext(1)
    DispatchQueue.global(qos: .background).async {
        obs.onNext(2)
    }
    return Disposables.create()
})
obs.subscribe(onNext: {
    print("\($0) delivered on main thread: \(Thread.current.isMainThread)")
})
.addDisposableTo(disposeBag)
```

**Expected outcome**:

```
1 delivered on main thread: true
2 delivered on main thread: true
```
(Because subscribe is executed on the main thread which would cause everything to be delivered on the main thread even if it was produced on a background thread.)

**What actually happens**:

```
1 on main thread: true
2 on main thread: false
```

**Variation**

Even if I add an `subscribeOn(MainScheduler.instance)` I get the same output. Only adding a `observeOn(MainScheduler.instance)` operator leads to the correct results.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [x] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [x] yes (which ones) [7.3.1, 8.0, 8.1, 8.2]
  - [ ] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by fpillet** [comment]
Two things:

1. `subscribeOn` guarantees that you **subscribe** to an observable on a given scheduler. Only `observeOn` will guarantee which scheduler the events actually get **delivered** on.
2. Main **queue** may _not always_ be equivalent to main **thread**. This is a subtle distinction, but in your case it won't make a difference.

To summarize, there is no bug here. What you are seeing is normal, expected behavior. To guarantee event delivery on main queue, always use `observeOn`, or a `Driver`.

**Comment by fpillet** [comment]
Just to make things crystal clear, yes you read the docs wrong. The `subscribeOn` documentation clearly states that it guarantees which scheduler is current when the observable is subscribed to. What happens next (i.e. observable hoping queues to deliver its events somewhere else) is not in the permiter of `subscribeOn`.

**Comment by FGoessler** [comment]
Ah ok - thanks a lot for the clarification! 

Just to get it totally clear:

The use of `subscribeOn` is NOT that the callbacks that you pass into `subscribe(...)` are called on the specified scheduler, but that the "observable creation" happens on that scheduler. So if I create my observable via `Observable.create { ... }` the block passed there is executed on that thread. Correct?

**Comment by fpillet** [comment]
Yes, correct.

**Comment by kzaher** [comment]
I've just added that clarification to the docs to remove any ambiguities.

**Comment by FGoessler** [comment]
Awesome! Thank you so much! 👍
