### ISSUE TITLE
Allow BehaviorSubject without initial value

### ISSUE THREAD

**Issue by hannesstruss** [ReactiveX/RxSwift#1038]
In some cases it is convenient to initialize an empty BehaviorSubject without an initial value.

**Comment by kzaher** [comment]
Hi @hannesstruss ,

then you want `ReplaySubject.create` ....

**Comment by hannesstruss** [comment]
Indeed. Thanks!

**Comment by menehune23** [comment]
Don't forget to set the buffer size to 1 if you want exactly a `BehaviorSubject` minus the initial value piece.
