### ISSUE TITLE
Request: First operator

### ISSUE THREAD

**Issue by Oyashirox** [ReactiveX/RxSwift#1043]
Hi,

I'm currently trying to do a simple Observable that downloads a file, and reports true if it completes, or false if it was cancelled. Here's what I currently have:

```swift
private func showCancellableDownload(url: String, filepath: String) -> Observable<Bool> {
        // Cancel emits if the cancel button is tapped
        let cancel = view.showLoading(title: "Downloading...", message: "")
            .subscribeOn(MainScheduler.instance)
            .shareReplay(1)
            .map { false }
        
        let download = downloadManager
            .download(url: url, filepath: filepath)
            .takeUntil(cancel)
            .subscribeOn(ConcurrentDispatchQueueScheduler(qos: .userInitiated))
            .observeOn(MainScheduler.instance)
            .do(
                onNext: { self.view.showLoadingProgress(percent: $0.percent) },
                onError: { _ in self.view.hideLoading() },
                onCompleted: { self.view.hideLoading() }
            )
            .toCompletable()
            .map { true }
        
        return Observable
            .of(cancel, download)
            .merge()
    }
```
I have something similar with RxJava, but there `TakeUntil`reports an error that let me identify that the download was cancelled, and I can map a different value.

I tried to adapt in RxSwift by using the  merge operator as you can see above. My problem is now that I only want the first result of the merge. `Single` won't work because there will be more than one element for sure (When cancel is tapped, it will return false, then the download observable will stop and return true). I looked for a `First` operator that would return the first value then unsubscribe, but it does not seems to exist ? I would create it as I did for `toCompletable` (Emits when previous observable completes) but I don't know how I can achieve this properly (by unsubscribing right after the first element).

EDIT:
I did this, it works but I'm not sure it is fondamentally correct ?
```swift
extension ObservableType {
    
    func first() -> Observable<Self.E> {
        return Observable.create { observer in
            let subscription = self.subscribe { e in
                switch e {
                case .next(let value):
                    observer.on(.next(value))
                    observer.on(.completed)
                case .error(let error):
                    observer.on(.error(error))
                case .completed:
                    observer.on(.completed)
                }
            }
            
            return subscription
        }
    }
}
```

**Comment by sergdort** [comment]
@Oyashirox Isn't `take(1)` what you need?

**Comment by Oyashirox** [comment]
Well, I don't know why but I completely missed that. I'll try as soon as I can, but that's probably it.
