### ISSUE TITLE
 Ambiguous reference to member ‘tableView’

### ISSUE THREAD

**Issue by Bashta** [ReactiveX/RxSwift#1050]
**Short description of the issue**:

Getting compile time error on main view controller. Ambiguous reference to member ‘tableView’

**Expected outcome**:

Project should build properly

**What actually happens**:

Project fails to build

**Self contained code example that reproduces the issue**:

```swift  
import Moya
import Moya_ModelMapper
import UIKit
import RxOptional
import RxCocoa
import RxSwift

final class PostTableViewController: UITableViewController {
    
    //MARK: - Properties
    let disposeBag = DisposeBag()
    
    var provider: RxMoyaProvider<HubChatEndpoint>!
    var postViewModel: PostViewModel!
    
    //MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        print(self.tableView)
        self.view.backgroundColor = .white
    }
}

private extension PostTableViewController {
    //MARK: -
    func setupRx() {
        provider =  RxMoyaProvider<HubChatEndpoint>()
        postViewModel = PostViewModel(provider: provider)
        
        postViewModel.fetchPosts().bindTo(tableView.rx.items(cellIdentifier: "Cell")) {
            (index, viewModel: PostViewModel, cell) in
            cell.textLabel?.text = repository.name
            cell.detailTextLabel?.text = repository.url
            }
            .addDisposableTo(disposeBag)
    }
}

import Foundation
import Moya
import Mapper
import Moya_ModelMapper
import RxOptional
import RxSwift

struct PostViewModel {
    
    let provider: RxMoyaProvider<HubChatEndpoint>

    internal func fetchPosts() -> Observable<[Post]?> {
        return self.provider.request(HubChatEndpoint.Post)
            .mapArrayOptional(type: Post.self)
            .debug()
    }
}

struct Post: Mappable {
    
    let rawContent: String
    let avatarUrl: String?
    let username: String
    let imagesUrl: Array<String>?
    
    init(map: Mapper) throws {
        try rawContent = map.from("")
        try username = map.from("")
        avatarUrl = map.optionalFrom("")
        imagesUrl = map.optionalFrom("")
    }
}

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Using RxSwift (3.0.1)

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 8.2.1 (8C1002)
```

**Installation method**:
  - [ x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @Bashta ,

I think you need to use `internal func fetchPosts() -> Observable<[Post]>`.

**Comment by Bashta** [comment]
```Swift
postViewModel.fetchPosts().bindTo(tableView.rx.items(cellIdentifier: "Cell")) {
            (index, viewModel: PostViewModel, cell) in
            cell.textLabel?.text = repository.name
            cell.detailTextLabel?.text = repository.url
            }
            .addDisposableTo(disposeBag)
```
The actual problem was this method. Removed the `(index, viewModel: PostViewModel, cell)` and replaced with `row, element, cell`(Shame on me for copy pasting). After that it builded correctly. The compiler error was misleading and took  me a bit off-guard. (Closing the issue hoping no one will ever read this fail 🤞)
