### ISSUE TITLE
RxTests in Gitlab CI makes errors

### ISSUE THREAD

**Issue by svyatoslav-reshetnikov** [ReactiveX/RxSwift#1052]
**Short description of the issue**:

I'm trying to test my project with RxSwift using Gitlab CI with this code line from my .gitlab-ci.yml
```go
xcodebuild test -workspace ProjectName.xcworkspace -scheme ProjectName -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
```
but it makes few errors:

[x] /path_to_project/Pods/RxTests/RxTests/HotObservable.swift:26:29: use of undeclared type 'Bag'
private var _observers: Bag<AnyObserver<Element>>

[x] /path_to_project/Pods/RxTests/RxTests/HotObservable.swift:29:22: use of unresolved identifier 'Bag'
 _observers = Bag()

In Xcode, this project builds successfully and runs on tester's devices from iPhone 4s to iPhone 7. I don't understand the cause of this error - your library or Gitlab CI. I hope you'll help me.

**Expected outcome**:

I expect that my project tests successfully through Gitlab CI.

**What actually happens**:

Actually, Gitlab CI makes errors when it trying to test my project. See .gitlab-ci.yml file below

**Self contained code example that reproduces the issue**:

```go
  stages:
  - build

build_project:
  stage: build
  script:
    - rm -rf Pods;rm -rf ProjectName.xcworkspace;rm -rf ProjectName.xcodeproj/project.xcworkspace
    - pod install
    - xcodebuild clean -workspace ProjectName.xcworkspace -scheme ProjectName | xcpretty
    - xcodebuild test -workspace ProjectName.xcworkspace -scheme ProjectName -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
  tags:
    - tag1
    - tag2
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Using RxCocoa (3.0.1)
Using RxSwift (3.0.1)
Using RxTests (3.0.0-beta.2)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [x] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 8.2.1 (8C1002)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi,

Please use RxTest ~> 3.0.

**Comment by kzaher** [comment]
Other than that, I have no idea what's wrong.

**Comment by svyatoslav-reshetnikov** [comment]
@kzaher thanks! RxTest ~> 3.0 solved my problem.
