### ISSUE TITLE
Observable.throttle does not send event on specified scheduler.

### ISSUE THREAD

**Issue by D-Wang** [ReactiveX/RxSwift#1061]
**Short description of the issue**:

Observable.throttle does not send event on specified scheduler.

**Expected outcome**:

Observable.observeOn(schedulerB).throttle(1, schedulerA) will send all events on schedulerA

**What actually happens**:

Some event will be sent on schedulerB. It depends on whether the event has been hold before sent. If event was throttled, it will be sent on schedulerA, else it will be sent on schedulerB (original scheduler).

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Comment by kzaher** [comment]
Hi @D-Wang ,

throttle operator is just using a scheduler. There aren't any guarantees that all events will be delivered on that scheduler.

If you need for all events to arrive on scheduler A, then you need to do
```
Observable.observeOn(schedulerB).throttle(1, schedulerA).observeOn(schedulerA)
```

I think that maybe docs are little vague.
```
Scheduler to run the throttle timers and send events on.
```

Probably `and send events on` events part is confusing. I'll remove it from the docs.

**Comment by kzaher** [comment]
I've updated the docs, it should be more clear now.
