### ISSUE TITLE
Failed expectationForPredicate causes issues with RxBlocking

### ISSUE THREAD

**Issue by DarkOxygen** [ReactiveX/RxSwift#1062]
**Short description of the issue**:

It appears that a failed `expectationForPredicate` in a test case causes RxBlocking to enter an error state that persists for all subsequent tests in the suite. We have observed this in our UI tests, with a small example test file provided below that demonstrates the issue. Essentially, any network request made with `.toBlocking()` automatically fails, even though the request is made and the response successfully delivered (the latter verified using Charles Proxy).

**Expected outcome**:

A failed `expectationForPredicate` in a test case will not have any side-effects on RxBlocking functions anywhere else in the test suite.

**What actually happens**:

A failed `expectationForPredicate` causes any network request made with `.toBlocking()` to immediately fail, even though both the request and response are successful.

**Self contained code example that reproduces the issue**:
[ExpectationsBreakRxBlockingSomehowUITests.swift.zip](https://github.com/ReactiveX/RxSwift/files/685723/ExpectationsBreakRxBlockingSomehowUITests.swift.zip)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
```
2.6.0
```
**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
```
7.3.1
```
**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by kzaher** [comment]
Hi @DarkOxygen ,

I've tried to investigate this.

Copied your code [here](https://github.com/ReactiveX/RxSwift/commit/6e8c143fa1df7e6d7e6024f76428a258511d128a).

It's based on top of 2.6.1 release. Just unit test `RxExample-iOSUITests` scheme.

I don't think I can repro the issue you are suggesting. Maybe there is something else in your environment, or maybe I'm doing something wrong.

In any case, I need more info on this.

**Comment by kzaher** [comment]
I think we can close this for now. I've tried to repro this with existing informations, but failed.
