### ISSUE TITLE
swift package generate-xcodeproj seems to be broken

### ISSUE THREAD

**Issue by Lukas-Stuehrk** [ReactiveX/RxSwift#1066]
**Short description of the issue**:

I cannot install RxSwift as the dependency of a macOS application when the dependencies are installed via the Swift package manager.

However, I am  unsure if installing via the Swift package manager is supported or not since it is not listed in the installation methods. But there's a `Package.swift` file so I thought it is supported.

**Expected outcome**:

Building the app should work.

**What actually happens**:

There are some compile errors while building the app:
```
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:92:12: error: '__forwardToDelegate' is unavailable
    return __forwardToDelegate;
           ^
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:14:15: note: declaration uses __weak, but ARC is disabled
    id __weak __forwardToDelegate;
              ^
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:96:5: error: '__forwardToDelegate' is unavailable
    __forwardToDelegate = forwardToDelegate;
    ^
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:14:15: note: declaration uses __weak, but ARC is disabled
    id __weak __forwardToDelegate;
              ^
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:151:1: warning: method possibly missing a [super dealloc] call [-Wobjc-missing-super-calls]
}
^
/tmp/example/Packages/RxSwift-3.1.0/Sources/RxCocoaRuntime/_RXDelegateProxy.m:14:15: error: cannot create __weak reference in file using manual reference counting
    id __weak __forwardToDelegate;
```

**Self contained code example that reproduces the issue**:

I have a minimal example where the issue is reproducible at https://github.com/Lukas-Stuehrk/rxswift-macos-example

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

All 3.x.x versions

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

Xcode version Version 8.2.1 (8C1002)

Apple Swift Package Manager - Swift 3.0.2 (swiftpm-11750)

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @Lukas-Stuehrk ,

I'm not sure I can repro this.

<img width="1102" alt="screen shot 2017-01-10 at 20 20 42" src="https://cloud.githubusercontent.com/assets/1641148/21821054/5d51b136-d772-11e6-89c6-a64ab85815fa.png">

**Comment by Lukas-Stuehrk** [comment]
@kzaher Okay, interesting. When I build the package on the command line via `swift build` it works perfectly fine. However, when I create the Xcode project via `swift package generate-xcodeproj` and then run it in Xcode, it fails.
<img width="431" alt="xcode build" src="https://cloud.githubusercontent.com/assets/245433/21823342/e8cf1f52-d77a-11e6-95ce-94058e924ddd.png">

**Comment by kzaher** [comment]
Anyone has any idea how to turn arc by default with SPM and generate-xcodeproj?

I have no idea.

<img width="868" alt="screen shot 2017-01-11 at 21 43 05" src="https://cloud.githubusercontent.com/assets/1641148/21865570/fb20d9da-d846-11e6-9171-1cbbfd3d038f.png">

**Comment by sora0077** [comment]
`swift package generate-xcodeproj --xcconfig-overrides spm.xcconfig` works successfully.

```spm.xcconfig
// spm.xcconfig
CLANG_ENABLE_OBJC_ARC = YES
```

> http://stackoverflow.com/a/40254974

**Comment by kzaher** [comment]
Thnx @sora0077 ,

this is great. Is there any way we can pack this into this repository so user doesn't need to add this manually?

**Comment by sora0077** [comment]
Hi @kzaher 
I send pull request https://github.com/apple/swift-package-manager/pull/902 about `CLANG_ENABLE_OBJC_ARC `, and it merged!

**Comment by kzaher** [comment]
Nice :)
