### ISSUE TITLE
Rx.playground uses CPU constantly

### ISSUE THREAD

**Issue by MihaiDamian** [ReactiveX/RxSwift#1068]
**Short description of the issue**:

Certain pages in the playground (Working_with_Subjects for example) use the CPU at full load, even after all statements were executed.

**Expected outcome**:

CPU usage should go down after all statements are executed.

**What actually happens**:

Open Activity Monitor and check the CPU usage for Xcode. Open the Working_with_Subjects page. The output from the examples is printed in a few seconds in the Debug Area. The CPU usage remains around 100% and Xcode responsiveness is severely affected.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift commit 49148d57c19c629ccb0f4afec656ccb035bf41ef

**Platform/Environment**

  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

8.2.1

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X] yes (7.3.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @MihaiDamian ,

why do you think this is problem with this library and not Xcode?

**Comment by MihaiDamian** [comment]
It's possible that Xcode is at fault here, however the playground is unusable in the current state and this is a problem for library users.

**Comment by kzaher** [comment]
Can anyone repro this?

It seems to be working ok for me.

**Comment by sergdort** [comment]
Yeah, for it works fine as well 36% at max during run

**Comment by MihaiDamian** [comment]
I did a bit of debugging. The issue is not caused by code at all but by markdown rendering. It seems Xcode has a problem rendering sufficiently complex blocks of markdown as soon as you hit a specific number of such blocks in the same playground file. From my tests going from 5 to 6 identical blocks of markdown will cause CPU usage to spike from ~4% CPU to ~70%. 

Will open a radar ticket for this.

**Comment by kzaher** [comment]
@MihaiDamian Ok great. 👍 

Since it seems this is xcode issue, let's close this issue in this repo.
