### ISSUE TITLE
Extra argument in call with `tableView.rx.items' error

### ISSUE THREAD

**Issue by saru2020** [ReactiveX/RxSwift#1071]
Hello,
i can't understand, this are good, but rx_itemsWithCellIdentifier is deprecated on swift3.0

    var cars: Variable<[CarViewModel]> = Variable((UIApplication.shared.delegate as! AppDelegate).cars)
    let disposeBag = DisposeBag()
        
    override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.estimatedRowHeight = 80
    
        self.cars.asObservable()
        .bindTo(tableView.rx_itemsWithCellIdentifier("CarCell", cellType: CarTableViewCell.self)) { (a,b,c) in

        }
    }
After changes,
    var cars: Variable<[CarViewModel]> = Variable((UIApplication.shared.delegate as! AppDelegate).cars)
    let disposeBag = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.estimatedRowHeight = 80
    
        self.cars.asObservable().bindTo(self.tableView.rx.items("CarCell", cellType: CarTableViewCell.self)) { (index, carViewModel: CarViewModel, cell) in
            cell.carViewModel = carViewModel
            }.addDisposableTo(disposeBag)
    }
i had extra argument in callwith `tableView.rx.items("CarCell", cellType: CarTableViewCell.self)``
Can you help me please

**Comment by kzaher** [comment]
Hi @saru2020 ,

maybe `cellIdentifier` is missing.
```
let items = Observable.just([
             "First Item",
             "Second Item",
             "Third Item"
         ])

         items
             .bindTo(tableView.rx.items(cellIdentifier: "Cell", cellType: UITableViewCell.self)) { (row, element, cell) in
                cell.textLabel?.text = "\(element) @ row \(row)"
             }
             .addDisposableTo(disposeBag)
```

**Comment by kzaher** [comment]
There are examples in method comments.
