### ISSUE TITLE
Variable with value semantics

### ISSUE THREAD

**Issue by scottrhoyt** [ReactiveX/RxSwift#1073]
I do my best to avoid `Variable`s altogether, but I am in the process of migrating an older codebase and have found some instances where they have been quite useful in an intermediate refactor. Still, as mentioned here, I'm not keen on exposing the `Variable`s in an interface because of how they break immutability. I thought I would toss out the idea of an `ImmutableVariable` that maintains the qualities of a `Variable` (including emitting complete when deallocated), yet is able to have value semantics. Here's my--hacky--idea for it. Inspiration [here](https://www.cocoawithlove.com/blog/2016/03/27/on-delete.html). I was wondering what others thought.

```swift
private final class OnDelete {
    var block: () -> Void
    public init(_ c: @escaping () -> Void) {
        block = c
    }
    deinit {
        block()
    }
}

/// ImmutableVariable is a wrapper for `BehaviorSubject` with value semantics.
///
/// Unlike `BehaviorSubject` it can't terminate with error, and when variable is deallocated
/// it will complete it's observable sequence (`asObservable`).
public struct ImmutableVariable<Element> {

    public typealias E = Element

    private let _subject: BehaviorSubject<Element>

    private var _lock = SpinLock()

    // state
    private var _value: E

    // deleted
    private let _onDelete: OnDelete

    /// Gets or sets current value of variable.
    ///
    /// Whenever a new value is set, all the observers are notified of the change.
    ///
    /// Even if the newly set value is same as the old value, observers are still notified for change.
    public var value: E {
        get {
            _lock.lock(); defer { _lock.unlock() }
            return _value
        }
        set(newValue) {
            _lock.lock()
            _value = newValue
            _lock.unlock()

            _subject.on(.next(newValue))
        }
    }

    /// Initializes variable with initial value.
    ///
    /// - parameter value: Initial variable value.
    public init(_ value: Element) {
        _value = value
        _subject = BehaviorSubject(value: value)
        _onDelete = OnDelete({ [_subject] in _subject.onCompleted() })
    }
    
    /// - returns: Canonical interface for push style sequence
    public func asObservable() -> Observable<E> {
        return _subject
    }
}
```

A compiler error when trying to do this:

```swift
let variable = ImmutableVariable(1)
variable.value = 2
```

This would allow people to expose an `ImmutableVariable` in an interface without fear of unwanted mutation:

```swift
struct MyStruct {
  private(set) var variable = ImmutableVariable(1)
}
```

**Comment by scottrhoyt** [comment]
Ah, I think I discovered the flaw in my plan:

```swift
let a: ImmutableVariable<Int>? = ImmutableVariable(1)
let b = a
a = nil
// no completed emitted
```

**Comment by kzaher** [comment]
Hi @scottrhoyt ,

I see what you tried to do there, but I don't think this could work. If you need read only view of variable you can just use `Observable` or `Driver`.

**Comment by scottrhoyt** [comment]
Thanks for looking at it @kzaher. Indeed I am migrating to a pure observer pattern. However the codebase I am refactoring is quite large and in this particular instance, relies on synchronously reading a value from a global setting. In reality this global setting is set by a failable asynchronous operation, which has been a source of bugs for the rest of the app. End state, I would like it to be a pure `Observable` however having access to `Variable.value` in an intermediate state would help break up the refactor. Since this is a temporary solution, `Variable` will work for me, I was just thinking about this along the way. :)
