### ISSUE TITLE
[RxExamples] GitHubSignup breaks if interactive "back" is aborted

### ISSUE THREAD

**Issue by radex** [ReactiveX/RxSwift#1076]
**Short description of the issue**:

  In the "GitHub signup" example, start swiping from the left edge to the right (the "back" gesture), but lift the finger before the threshold to abort it

**Expected outcome**:

  The example keeps working

**What actually happens**:

  All of the bindings from view model to views are disposed, and the UI is no longer responsive.

* * *

The root of the problem is that the dispose bag is cleaned on `willMove(toParentViewController:)`. This works perfectly fine if you tap the Back button or do the whole edge-swipe gesture. But because iOS triggers it when edge-swipe has _begun_, if you abort it, the UI stays disconnected.

Not sure what is the *right* solution here. Should we connect the bag disposal to a different event (when we know that the back operation is committed), or should UI bindings be extracted from `viewDidLoad` so that they can be re-established in case of an edge-swipe abort?

**Comment by kzaher** [comment]
Hi @radex ,

These examples were hacked together with best intentions, but live you've noticed, they are pretty rough.

I think we can just remove entire `override func willMove(toParentViewController parent: UIViewController?) {` and let the dispose bag dispose everything.

**Comment by radex** [comment]
I haven't fully considered the consequences that the comment above `willMove(toParentViewController...)` talks about…

If you think there's no danger, I'll submit a PR removing this.

**Comment by kzaher** [comment]
I think the simplest thing is to rely on `disposeBag` to clean up subscription.

That code was written long time ago. UIKit has changed since then.

**Comment by radex** [comment]
Got it, #1086 then.
