### ISSUE TITLE
UICollectionViewCell gets draggable when elements are binded via rx.items(dataSource:)

### ISSUE THREAD

**Issue by ishkawa** [ReactiveX/RxSwift#1081]
**Short description of the issue**:

UICollectionViewCell gets draggable when elements are binded via `rx.items(dataSource:)`, even if the delegate does not have implementation of `collectionView(_:canMoveItemAtIndexPath:)`.

**Expected outcome**:

UICollectionViewCell is not draggable by default.

**What actually happens**:

UICollectionViewCell is draggable by default.

**Self contained code example that reproduces the issue**:

```swift
import UIKit
import RxSwift
import RxCocoa

class Cell: UICollectionViewCell {
    @IBOutlet weak var label: UILabel!
}

class ViewController: UICollectionViewController {
    private let dataSource = DataSource()
    private let disposeBag = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let values = Array(1...100)

        Observable
            .just(values)
            .bindTo(collectionView!.rx.items(dataSource: dataSource))
            .addDisposableTo(disposeBag)
    }

    class DataSource: NSObject, UICollectionViewDataSource, RxCollectionViewDataSourceType {
        typealias Element = [Int]

        var values = [Int]()

        func collectionView(_ collectionView: UICollectionView, observedEvent: Event<Element>) {
            if case .next(let element) = observedEvent {
                values = element
                collectionView.reloadData()
            }
        }

        func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
            return values.count
        }

        func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath) as! Cell
            cell.label.text = String(indexPath.row)

            return cell
        }
    }
}
```

Entire project is available [here](https://github.com/ishkawa/sandbox/tree/master/RxCocoaReorderIssue). Run `carthage bootstrap` and open `RxCocoaReorderIssue/Demo.xcodeproj` to reproduce the issue.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.1.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.2.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (8.2.1 and 7.3.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @ishkawa,

I think you can temporarily use `self.installsStandardGestureForInteractiveMovement = false` to solve this issue.

Long term solution would require modifying `RxCollectionViewDataSourceProxy` to use something like 

https://github.com/ReactiveX/RxSwift/issues/907
https://github.com/ReactiveX/RxSwift/commit/c005b1a775a6691e2b00b03b987a8c20379e3f0a

It would probably make sense to make `CachedCommitForRowAt` more generic.

Do you maybe have time to help out with this?

**Comment by ishkawa** [comment]
Yes, I'll try to fix this issue.

**Comment by kzaher** [comment]
HI @ishkawa ,

I think #1087 is related to this issue also. It looks like it might be worth solving this in delegate proxy layer.
