### ISSUE TITLE
Multiple Buttons Single Action

### ISSUE THREAD

**Issue by Rico9260** [ReactiveX/RxSwift#1088]
how can i handle action of multiple button by combining them in RxSwift?

**Comment by sergdort** [comment]
Hi, @Rico9260 

Just merge them into one sequence e.g:
```
let o = Observable.of(button1.rx.tap, button2.rx.tap).merge()
```

**Comment by Rico9260** [comment]
i need to access the tag of button inside the subscribe call

**Comment by sergdort** [comment]
```
let tag1 = button1.rx.tap.map { [unowned self]  _ in return self.button1.tag}
let tag2 = button2.rx.tap.map { [unowned self]  _ in return self.button2.tag}
let tags = Observable.of(tag1, tag2).merge 
```

**Comment by sergdort** [comment]
I think we can close this one 😀

**Comment by santhoshs5** [comment]
I have five buttons in VC and four buttons maintains isSelected property 
if either of the four button's isSelected is true I need to show the fifth button
otherwise i Need to hide it.

How can I achieve this ?
