### ISSUE TITLE
Implement concatMap operator

### ISSUE THREAD

**Issue by brendanarnold** [ReactiveX/RxSwift#1093]
**Short description of the issue**:

No concatMap operator for serializing streams of streams - see [React docs for concatMap](http://reactivex.io/documentation/operators/flatmap.html). This coupled with the fact that there is no non-element repeat (i.e. an overload for repeat that resubscribes on completion) means that looping an observable in RxSwift is tricky - see this [Stackoverflow question for details](http://stackoverflow.com/questions/42115976/how-do-i-sequentially-loop-an-observable-in-rxswift)

**Expected outcome**:

There should be a way to serialize streams of streams when each stream completes

**What actually happens**:

Have not been able to figure out a way to do the above

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.1.0

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  
**Xcode version**:

```
8.1
```

**Comment by kzaher** [comment]
Hi @brendanarnold ,

Its kind of silly, but Swift doesn't have infinite sequence :) So you first need to create yours first.

```
struct InfiniteSequence<E> : Sequence {
    typealias Element = E
    typealias Iterator = AnyIterator<E>
    
    private let _repeatedValue: E
    
    init(repeatedValue: E) {
        _repeatedValue = repeatedValue
    }
    
    func makeIterator() -> Iterator {
        let repeatedValue = _repeatedValue
        return AnyIterator {
            return repeatedValue
        }
    }
}
```

... and then

```
InfiniteSequence(repeatedValue: Observable.just("Repeat me until end of time")
       .map { _ in "Really?" })
      .concat()
```

**Comment by kzaher** [comment]
... because RxSwift doesn't have back pressure.

**Comment by brendanarnold** [comment]
So RxSwift not having back pressure is a design decision? If so is there any more info on this decision? 

I think I understand the implications in implementing `concatMap` in that you would have to cache the 'queued' observables which could be tricky but for `repeat` the implementation is relatively straightforward since the above `InfiniteSequence` snippet is already in the source code and is used for the retry operator. In fact `repeat` is almost the same as `retry` in that it can also potentially loop forever.

**Comment by tomahh** [comment]
Oops, didn't see this issue before and answered over on stackoverflow. But wouldn't `Observable.repeatElement(polling).concat()` solve the issue? Or maybe there's something I'm missing... 🤔

**Comment by kzaher** [comment]
@tomahh without backpressure repeat element will just produce elements like crazy until you run out of memory.

@brendanarnold majority of Rx implementations actually don't have backpressure.

It adds additional level of complexity and slowdowns for limited set of use cases. A big part of them could be written so they don't require backpressure at all.

Swift also doesn't have native concurrency model, etc.

RxJava 2.0 has now split types with and without backpressure. (Observable vs Flowable).

**Comment by brendanarnold** [comment]
Hi @kzaher, I tried your example but `InfiniteSequence` is not an observable and so does not have the `.concat()` method.

Using `Observable.from` on the infinite sequence freezes the app, presumably because it is trying to complete the infinite series?

**Comment by kzaher** [comment]
Hi @brendanarnold,

We've moved concat operator to a static method, my bad.

```
_ = Observable.concat(InfiniteSequence(repeatedValue: Observable.just("Repeat me until end of time")
    .map { _ in "Really?" }))
    .subscribe(onNext: { next in
        print(next)
    })
```

The reason why it "freezes" is because this will just pump elements indefinitely and print them out.

If you want it to back off a bit :)

```
_ = Observable.concat(InfiniteSequence(repeatedValue: Observable.just("Repeat me until end of time")
    .map { _ in "Really?" }.delay(1.0, scheduler: MainScheduler.instance)))
    .subscribe(onNext: { next in
        print(next)
    })
```

I'm still not sure what are you exactly trying to accomplish :)

**Comment by nxtstep** [comment]
Hi @brendanarnold, @kzaher,

I've ran into this issue as well. I've 'created' my own implmentation of `concatMap()` derived from existing RxSwift operators: 

```
extension ObservableType {

    /**
    Projects each element of an observable sequence to an observable sequence and concatenates the resulting observable sequences into one observable sequence.

    - seealso: [concat operator on reactivex.io](http://reactivex.io/documentation/operators/concat.html)

    - returns: An observable sequence that contains the elements of each observed inner sequence, in sequential order.
    */
    public func concatMap<O: ObservableConvertibleType>(_ selector: @escaping (E) throws -> O) -> Observable<O.E> {
        return self.asObservable().map(selector).concat()
    }
}
```

I'm more than happy to create a PR for this to get it in the main repo.

**Comment by groue** [comment]
I, too, need `concatMap`.

But I'm not sure I understand: is @nxtstep's suggestion above a correct implementation for `concatMap`, considering the previous comments?

**Comment by kzaher** [comment]
It's correct, but we'll try to do a more optimized solution.
