### ISSUE TITLE
is onDispose part of Reactive Programming?

### ISSUE THREAD

**Issue by rendion** [ReactiveX/RxSwift#1095]
The docs seem to say that Variable.asObservable to be safe calls onComplete when the variable is "deinit"-ed.

But when you explicity call dispose on the disposable, onComplete is not called, onDispose is.

If onDipose is some sort of paralell to deinit for a subscription, shouldnt deinit for a Variable() and dispose for the disposable do one or the other?  If onDispose is the correct teardown for all subscriptions, then why do it differently for Variable()s or vice versa (just call onComplete)

Sorry the slack account thing didnt work.  This is a general question and Im not sure it applies outside of swift or if its a general Reactive issue.

**Comment by rendion** [comment]
My general concern is that if rxswift is adding subscription states then it probably shouldnt be because subscription states observers would turn into a switch statement not a completed or didnt which is a nice and tidy idiom for rx.

**Comment by kzaher** [comment]
Hi @rendion ,

Thnx for reporting the slack link malfunction. That was a major f...u... :( 

Producer sends to consumer -> next, completed, error
Consumer subscribes to producer to receive those messages, but can dispose the subscription to express its intent to not receive any more messages.

Communication channel is disposed when either producer sends completed or error, or consumer disposed -> onDispose is called in those cases. It's just a convenience.

https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md

**Comment by rendion** [comment]
I see so dispose is orthogonal to the stream itself, and if theres any cleanup logic needed then I need to know that it can be disposed that way.  But in the case of Variable() deinit, (and the disposeBag) strategy it seems onComplete and onDispose will both be called.  I get what your saying, subtle difference between stream ending and disposing the subscription.
