### ISSUE TITLE
Autoloading Github Repositories 

### ISSUE THREAD

**Issue by vjujjavarapu** [ReactiveX/RxSwift#1105]
Where is the code located for https://github.com/ReactiveX/RxSwift/issues/170 now?

**Comment by SeRG1k17** [comment]
[My example](https://github.com/SeRG1k17/rxtest)

**Comment by vjujjavarapu** [comment]
I ran the project, saw random files from other tutorials code/files. and when i type swift or infant anything i dont see nothing.

**Comment by kzaher** [comment]
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/GitHubSearchRepositories/GitHubSearchRepositoriesViewController.swift
