### ISSUE TITLE
Propagate runtime error to the subscriber

### ISSUE THREAD

**Issue by linktohack** [ReactiveX/RxSwift#1106]
Hello I have asked the question in the Slack channel but it seems to be debatable...

**Short description of the issue**:

Let us say I have a silly snippet:

```swift
        dropboxButton.rx.tap.flatMap { _ -> Observable<Any> in
//            Observable.error("Pretend to throw Error")
//            throw "Error"
            let x: Int? = nil
            return Observable.just(x! + 1)
        }.subscribe(onNext: {
            print("Dropbox result: \($0)")
        }, onError: {
            print("Dropbox Error: \($0)")
        }).addDisposableTo(bag)
```

**Expected outcome**:

I expect the runtime error propagated to `onError` with that print a message like: `Dropbox Error: fatal error: unexpectedly found nil while unwrapping an Optional value`

**What actually happens**:

The app crashes with following error: `fatal error: unexpectedly found nil while unwrapping an Optional value`.

If I `throw` or return an `Observable.error`, the error is successful propagated to `onError`

**Motivation**

The following snippet in RxJava (Kotlin) propagates successfully the `RuntimeError` `null pointer exception` to `onError` function and print the stack trace without crashing the program

```kotlin
        RxView.clicks(fab).flatMap {
            val x: Int? = null
            Observable.just<Int>(x!! + 1)
        }.subscribe({
            Snackbar.make(fab, "Replace with your own action $it", Snackbar.LENGTH_LONG)
                    .setAction("Action", null).show()
        }, { it -> it.printStackTrace() })```
``` 

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 8
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @linktohack ,

Swift works in a totally different way. There is difference between error and exception.

Like you have whitenessed, it has its downsides.

There are awful hacks that would allow us to change this behavior, but they would cause memory leaks etc.

**Comment by linktohack** [comment]
Thanks @kzaher, please close the issue, hope it will serve if someone looking for the same idea...
