### ISSUE TITLE
Variable is not an open class

### ISSUE THREAD

**Issue by tgyhlsb** [ReactiveX/RxSwift#1112]
**Short description of the issue**:

I want to add a `reset()` method to my variables, it will set the `value` to the one provided on init. But I can't do this because `Variable` is not open.

**Expected outcome**:

```swift
open class Variable<Element>
```

**Self contained code example that reproduces the issue**:

```swift
open class VariableExtended<Element>: Variable<Element> {
    
    private let defaultValue: Element
    
    override init(_ value: Element) {
        self.defaultValue = value
        super.init(value)
    }
    
    public func reset() {
        self.value = self.defaultValue
    }

}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 3.0.0

**Comment by kzaher** [comment]
Hi @tgyhlsb ,

`Variable` is just a simple wrapper around `BehaviorSubject`. It doesn't contain any logic at all.

Could you just create your wrapper if you want this behavior?

**Comment by tgyhlsb** [comment]
Hi @kzaher 

This is what I ended up doing. But as small as it is, I'd find it nice if I could reuse it.
This issue can be closed if you don't plan to change this ;)

**Comment by kzaher** [comment]
Lets try to keep this repo as simple as possible :)
