### ISSUE TITLE
RxTableViewSectionedAnimatedDataSource

### ISSUE THREAD

**Issue by lu469814** [ReactiveX/RxSwift#1115]
I want to use AnimatedDataSource Extract data from Core Data，and bind tableview

**This is my ViewController**
`      
            
           let animatedDataSource = RxTableViewSectionedAnimatedDataSource<AnimatableSectionModel<String, TimeModel>>()     

        editTableView.isEditing = true

        let dataSource = animatedDataSource
        
        dataSource.configureCell = { _, tableView, indexPath, model in
            
            let cell = tableView.dequeueReusableCell(withIdentifier: Constant.timeEditCellIdentifier, for: indexPath) as! TimeEditTableViewCell
            
            cell.model = model
            
            return cell
        }
        
        dataSource.canEditRowAtIndexPath = { _ in return true }
        
        APP_DELEGATE.managedObjectContext.rx.entities(TimeModel.self, sortDescriptors: nil)
            .map { model in
                [AnimatableSectionModel(model: "Section 1", items: model)]
            }
            .bindTo(editTableView.rx.items(dataSource: animatedDataSource))
            .addDisposableTo(disposeBag)
        
        editTableView.rx.itemDeleted.map { [unowned self] indexPath -> TimeModel in
            return try self.editTableView.rx.model(at: indexPath)
            }
            .subscribe(onNext: { (model) in
                do {
                    try APP_DELEGATE.managedObjectContext.rx.delete(model)
                } catch {
                    logMessage("fail-reason:\(error)")
                }
            })
            .addDisposableTo(disposeBag)

`

**This is my model**

      ` struct TimeModel {

    var time: String
    var identifier: String
    var selectDay: String
    var switchState: String
    var timePlace: String

}
 `

`
     func == (lhs: TimeModel, rhs: TimeModel) -> Bool {
         return lhs.identity == rhs.identity
       }`

     extension TimeModel: Equatable { }

     extension TimeModel: IdentifiableType {
    
             typealias Identity = String
    
          var identity: Identity { return identifier }
    
     }
`

   

> `extension TimeModel: IdentifiableType {
    
    typealias Identity = String
    
    var identity: Identity { return identifier }
    
}

extension TimeModel: Persistable {
    
    typealias T = NSManagedObject
    
    static var entityName: String {
        return "TimeModel"
    }
    
    static var primaryAttributeName: String {
        return "identifier"
    }
    
    init(entity: T) {
        
        time = entity.value(forKey: "time") as! String
        timePlace = entity.value(forKey: "timePlace") as! String
        selectDay = entity.value(forKey: "selectDay") as! String
        identifier = entity.value(forKey: "identifier") as! String
        switchState = entity.value(forKey: "switchState") as! String
        
    }
    
    func update(_ entity: T) {
        
        entity.setValue(time, forKey: "time")
        entity.setValue(timePlace, forKey: "timePlace")
        entity.setValue(selectDay, forKey: "selectDay")
        entity.setValue(identity, forKey: "identifier")
        entity.setValue(switchState, forKey: "switchState")
        
        do {
            try entity.managedObjectContext?.save()
        } catch let e {
            logMessage("\(e)")
        }
    }
    
}
`

The first question is, cell.model = model
When i set the cell value to collapse

The second question is that this page is not updated when other pages are modified CoreData

Teach me how to use AnimatedDataSource, very grateful

**Comment by kzaher** [comment]
Hi @lu469814 ,

I'm having a bit of trouble understanding your exact issue. I'm assuming part of the issue is that animated data source isn't updating your cell on change.

```swift
func == (lhs: TimeModel, rhs: TimeModel) -> Bool { return lhs.identity == rhs.identity }
```

This is wrong. You need to compare all members by value for updates to work.

```swift
func == (lhs: TimeModel, rhs: TimeModel) -> Bool { 
     return lhs.time == rhs.time && lhs.identifier == rhs.identifier && .....
}
```

**Comment by lu469814** [comment]
I already change return lhs.identity == rhs.identity into return lhs.time == rhs.time && lhs.identifier == rhs.identifier && ..... （all members by value）

But still no effect

I try to change RxTableViewSectionedAnimatedDataSource into RxTableViewSectionedReloadDataSource So there is no problem 

But I want to delete the Cell when there is animation

I have confirmed that the database has been modified on the next page

But when the current page is returned, the data on the Cell is not updated

I have all the code on the above, I tried to use ReloadDataSource is no problem, I do not know if I use AnimatedDataSource incorrectly

Thank you for your help

**Comment by DianQK** [comment]
You can see this demo https://github.com/ReXSwift/ReX-Todo-Demo, it workes well.
And you can add `debug` before `bindTo(editTableView.rx.items(dataSource: animatedDataSource))` to make sure that you get data for Core Data.

But If `RxTableViewSectionedReloadDataSource` work well, I think you should check out protocol `IdentifiableType`.

**Comment by lu469814** [comment]
@DianQK 

When the model is added to the database on the next page, the current page executes 

APP_DELEGATE.managedObjectContext.rx.entities (TimeModel.self, predicate: nil, sortDescriptors: nil) .map {model in
             LogMessage ("\ (model) \ n")
             [AnimatableSectionModel (model: "Section 1", items: model)]
         } .bindTo (editTableView.rx.items (dataSource: animatedDataSource))
             .addDisposableTo (disposeBag)

Here is the correct data after I add the model

 check out protocol IdentifiableType. ？

`   
    extension TimeModel: IdentifiableType {

    typealias Identity = String

    var identity: Identity { return identifier }
    
     }  `

`struct TimeModel {

    var time: String
    var identifier: String
    var selectDay: String
    var switchState: String
    var timePlace: String

}`

Is there any problem here?

**Comment by DianQK** [comment]
Update RxDataSources version from 1.0.2 to 1.0.3, maybe this can fix.

For more, see https://github.com/RxSwiftCommunity/RxDataSources/issues/84

**Comment by lu469814** [comment]
Thank DianQK for helping me solve the problem，Thanks kzaher to help me。
