### ISSUE TITLE
Use of Locks vs GCD queues

### ISSUE THREAD

**Issue by CalvHobbes** [ReactiveX/RxSwift#1117]
I've noticed that there are several places in the code where you use locks (jncluding RecursiveLocks), as opposed to say, other techniques involving GCD etc (if those techniques are even applicable in your framework): 
1) https://www.mikeash.com/pyblog/friday-qa-2015-02-06-locks-thread-safety-and-swift.html
2) https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/ThreadSafety/ThreadSafety.html

I'm new to Swift/Objective-C so just curious to know if the reason you use locks/recursive locks is because that was the most optimal way to do it, for the specific requirements of the framework. Or....do you have any further optimizations in mind? The reason I ask is because the docs seem to suggest that using locks has a high cost associated with it....since the kernel is involved etc.

Thanks!

**Comment by kzaher** [comment]
Hi @CalvHobbes ,

In places where we need reentrant locks, we use `NSRecursiveLock`. 
In places where we only need to pass messages, we use atomic operations.

I'm not sure what exact places are you referring to?

According to my benchmarks Swift overhead has way more impact on runtime performance than locks. 

I believe that removing locks entirely would make this library only 0-25% more performant, depending on the particular use cases.

**Comment by CalvHobbes** [comment]
Hi @kzaher , thank you for your response. I was, indeed, referring to the RecursiveLocks primarily (there's only one other place you use a SpinLock), but it looks like you've done all possible due diligence there. Didn't understand the part about Swift overhead having more impact. For academic interest, is there a benchmark test or article etc. you could point me to?

**Comment by CalvHobbes** [comment]
@kzaher  I found this: https://www.cocoawithlove.com/blog/2016/06/02/threads-and-mutexes.html. I think I'm starting to understand what you were saying about Swift overhead :)
