### ISSUE TITLE
Building a auto reloading view controller

### ISSUE THREAD

**Issue by vjujjavarapu** [ReactiveX/RxSwift#1124]
Hi, 

I want to contribute and build a project probably in the RxExample folder, so that without the searchBar or the tableview bottom reaching trigger an autoreload kind of behavior everything viewWillAppear. The only way i have done is setting the tableview.datasource = nil and binding tableview with the viewmodel again which seems to be not the best way to deal with this problem.

**Comment by kzaher** [comment]
Hi @vjujjavarapu ,

We'll try to improve some of the examples soon. I'm not sure what are you asking? 

You want to reload the results on viewWillAppear?

**Comment by vjujjavarapu** [comment]
I apologize for the confusing question, I have done it in my own style, However, I do like to contribute to  RxSwift by writing an example with the auto reloading concept idea, In GitHubRepos example, search bar's text is being observed to fire off the network request instead building an auto fetching the data without a search bar in a way.  I was trying to ask the question at the same time, I would like to contribute to the examples in RxSwift.

**Comment by kzaher** [comment]
Hi @vjujjavarapu ,

We've refactored that example a bit lately. It now doesn't depend on a search bar. Hope it makes it more extensible now.

**Comment by vjujjavarapu** [comment]
Hi @kzaher , I cannot thank you enough for this. You are the best. I would love to contribute in any which way by creating more and more examples to the RxExample. or if you have any example which you would like to implement but got no time, Let me know.
