### ISSUE TITLE
Prevent multiple api calls

### ISSUE THREAD

**Issue by jasin755** [ReactiveX/RxSwift#1127]
How Can I prevent multiple long api calls (e.g. user tap the button several times) without saving state (e.g. saving state to "isLoading" property)

I am solving this problem for Stack and a good solution is on RxJava:

```
getClicksEvents()
.take(1)
.flatMap(aVoid -> getRequestObservable())
.repeat()
.retry()
.subscribe( result -> //do your thing );
```

but RxSwift hasn't implemented `repeat` method.

Is there an alternative solution?

**Comment by kzaher** [comment]
Hi @jasin755 ,

there is `flatMapFirst`, so you can do:

```
getClicksEvents()
.flatMapFirst(aVoid -> getRequestObservable())
.retry()
.subscribe( result -> //do your thing );
```

**Comment by jasin755** [comment]
Nice! That's it! Thanks :)
