### ISSUE TITLE
Feature request: rxanimate

### ISSUE THREAD

**Issue by lolohouse** [ReactiveX/RxSwift#1128]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://rxswift-slack.herokuapp.com/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

 Example for animate

**Expected outcome**:

  add for idea animating for rx
  add file extension 
  in a future, binding for rx.transform to facility, por example.

 example actuality for my extension: 
self.googleMaps.rx.selectedMarker
            .map { self.boolConverter.to(not: $0) }
            .bindNext(animateBounce: 0.5) { val in
                let value = CGFloat(val ? 0.2 : 1.0)
                let animate = CGAffineTransform(scaleX: value, y: value)
                    .concatenating(CGAffineTransform(translationX: 0, y: val ? 100 : 0))
                self.buttonShare.transform = animate
                self.buttonHowGet.transform = animate
            }.addDisposableTo(disposeBag)

explication example:
 for control googlemaps when select-marketPoint to converter to true/false to bindNextAnimate (show or hide buttons, for transform) to adddisposable.

Simple no?

The extension is: 

extension ObservableType {
    
    public func bindNext(animateBounce duration: TimeInterval, delay: TimeInterval = 0, damping: CGFloat = 0.4, velocity: CGFloat = 0.5, options: UIViewAnimationOptions = [], onNext: @escaping (Self.E) -> Swift.Void) -> Disposable {
        return self.bindNext { val in
            UIView.animate(withDuration: duration, delay: delay, usingSpringWithDamping: damping, initialSpringVelocity: velocity, options: options, animations: {
                onNext(val)
            }, completion: nil)
        }
    }
    
    public func bindNext(animate duration: TimeInterval, delay: TimeInterval = 0, options: UIViewAnimationOptions = [], onNext: @escaping (Self.E) -> Swift.Void) -> Disposable {
        return self.bindNext { val in
            UIView.animate(withDuration: duration, delay: delay, options: options, animations: {
                onNext(val)
            }, completion: nil)
        }
    }
}

**What actually happens**:

  _what actually happens goes here_

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by jamiepinkham** [comment]
Hi @lolohouse!

I'm having a hard time figuring out what you're asking for here. I think the template is obscuring what you'd like to do.

**Comment by kzaher** [comment]
Hi @lolohouse ,

I think I can understand how this could be useful, but I don't think we should maintain it in this repo.
