### ISSUE TITLE
Completeable is misspelled. 

### ISSUE THREAD

**Issue by hzsweers** [ReactiveX/RxSwift#1134]
**Short description of the issue**:

  The new `Completeable` class is misspelled. RxJava's is `Completable`.

**Expected outcome**:

  It should be `Completable` if we want to match RxJava.

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting, but an active contributor to RxJava

**Comment by kzaher** [comment]
Hi @hzsweers ,

Thnx for reporting this. We've already been informed. I'll create a patch release tonight.

**Comment by hzsweers** [comment]
Thanks!

**Comment by kzaher** [comment]
Hi @hzsweers ,

I've pushed changes to [develop](https://github.com/ReactiveX/RxSwift/commits/develop) branch.

Do you maybe see anywhere some other mistypes or anomalies before I start pre release tests?

**Comment by hzsweers** [comment]
Only other thing that comes to mind is that RxJava 2 follows the reactive streams nomenclature of saying `onComplete` rather than `onCompleted`. That's probably out of scope for this though since Observable uses it as well. Might be worth making new operators abide by it though?

**Comment by kzaher** [comment]
Yeah, let's focus on the obvious for now :)

**Comment by hzsweers** [comment]
:+1:
