### ISSUE TITLE
Turning off `isUserInteractionEnabled` in `UITextField`'s `rx.text` subscription block reverted the last input when in Japanese (and maybe other languages)

### ISSUE THREAD

**Issue by jaclync** [ReactiveX/RxSwift#1137]
**Short description of the issue**:

Setting `isUserInteractionEnabled` to `false` in `UITextField`'s `rx.text` subscription block caused the last input to be reverted in text field's text when in Japanese (and maybe other languages with radicals).

**Expected outcome**:

Text field's text stays the same after setting `isUserInteractionEnabled` to `false` in `rx.text` subscription block.

**What actually happens**:

In Japanese, characters can be typed with Japanese or Romanji keyboard in iOS. In either case, the last input (a [Dakuten](https://en.wikipedia.org/wiki/Dakuten), a radical, or a character) would be reverted after setting `isUserInteractionEnabled` to `false` in `rx.text` subscription block.

**Self contained code example that reproduces the issue**:

```swift
let textField = UITextField()
textField.rx.text.orEmpty
  .subscribe(onNext: { text in
    if text == "たべます" {
      textField.isUserInteractionEnabled = false
    }
  })
  .addDisposableTo(disposeBag)
```

In [this example project](https://github.com/jaclync/RxTextFieldTest) I made, typing "tabemasu" in Japanese Romanji keyboard (ta=た, be=べ, ma=ま, su=す) triggered `textField.isUserInteractionEnabled = false`. However, the last character "u" was reverted and thus the text field was left with "たべまs" instead of "たべます".

The part of stack trace that resulted in this revert (possibly related to internal keyboard autocorrection?):
```
#32	0x0000000104132b61 in ControlTarget.eventHandler(UIControl!) -> () at /RxTextFieldTest/Pods/RxCocoa/RxCocoa/Common/ControlTarget.swift:75
#33	0x0000000104132bca in @objc ControlTarget.eventHandler(UIControl!) -> () ()
#34	0x00000001050878bc in -[UIApplication sendAction:to:from:forEvent:] ()
#35	0x000000010520dc38 in -[UIControl sendAction:to:forEvent:] ()
#36	0x000000010520df51 in -[UIControl _sendActionsForEvents:withEvent:] ()
#37	0x0000000105ba66a1 in -[UITextField fieldEditorDidChange:] ()
#38	0x0000000105bb4a53 in -[UITextInputController _sendDelegateChangeNotificationsForText:selection:] ()
#39	0x0000000105bbc892 in -[UITextInputController setMarkedText:selectedRange:] ()
#40	0x0000000105217a0c in -[UIFieldEditor setMarkedText:selectedRange:] ()
#41	0x0000000105baa752 in -[UITextField setMarkedText:selectedRange:] ()
#42	0x0000000105699911 in -[UIResponder(UITextInput_Internal) _setMarkedText:selectedRange:] ()
#43	0x000000010535c400 in -[UIKeyboardImpl acceptWord:firstDelete:forInput:] ()
#44	0x000000010535a623 in -[UIKeyboardImpl acceptCandidate:forInput:] ()
#45	0x000000010535a946 in -[UIKeyboardImpl acceptCandidate:forInput:executionContext:] ()
#46	0x0000000105bd636b in -[UIKeyboardTaskQueue continueExecutionOnMainThread] ()
#47	0x0000000105bd6789 in -[UIKeyboardTaskQueue performTaskOnMainThread:waitUntilDone:] ()
#48	0x000000010535a869 in -[UIKeyboardImpl acceptCurrentCandidateForInput:] ()
#49	0x00000001053596c8 in -[UIKeyboardImpl acceptAutocorrection] ()
#50	0x000000010534749b in -[UIKeyboardImpl setDelegate:force:] ()
#51	0x0000000105767dde in -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] ()
#52	0x000000010529d765 in -[UIResponder _finishResignFirstResponder] ()
#53	0x0000000105b97a0e in -[UITextField _finishResignFirstResponder] ()
#54	0x000000010529d899 in -[UIResponder resignFirstResponder] ()
#55	0x0000000105b978dd in -[UITextField resignFirstResponder] ()
#56	0x000000010511bfe3 in -[UIView setUserInteractionEnabled:] ()
#57	0x00000001040654c6 in ViewController.(viewDidLoad() -> ()).(closure #1) at /RxTextFieldTest/RxTextFieldTest/ViewController.swift:39
```

My workaround for this issue was to turn off `isUserInteractionEnabled` in a `DispatchQueue.main.async` block in subscription block.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.3.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.2.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Comment by kzaher** [comment]
Hi @jaclync ,

why do you think this is a RxCocoa bug and that changing `isUserInteractionEnabled` is supported in UIKit synchronously when text changes?

**Comment by ddengler** [comment]
ran into the same(?) issue:

```
    results
      .map { $0.username }
      .drive(usernameTextField.rx.text)
      .disposed(by: disposeBag)

    results
      .map { !$0.loading }
      .drive(usernameTextField.rx.isEnabled)
      .disposed(by: disposeBag)
```

While this is properly executed the change event on usernameTextField.rx.text does not seem to be triggered. Have not investigated this any further. Just wanted to let you know. Will post any other findings.
