### ISSUE TITLE
Can't use TestableObservable as Observable in RxTest

### ISSUE THREAD

**Issue by adamsmaka** [ReactiveX/RxSwift#1139]
**Short description of the issue**:

I'm trying to test my Rx code and I have a lot of problems with it, when it comes to test Arrays. There is a lot of examples how to do that with Bool or Int, but what with Observable<[MyStruct]> ? 

**Expected outcome**:

I want to test my code which convert Obseravable<[MyStruct1]> to Observable<[MyStruct2]>. 

**What actually happens**:

I use TestScheduler to create TestableObseravable<[MyStruct1]> but when I send it to the converter it says:
Cannot convert value of type 'TestableObservable<[MyStruct1]>' (aka 'TestableObservable<Array<MyStruct1>>') to expected argument type 'Observable<[MyStruct1]>' (aka 'Obseravable<Array<MyStruct1>>')

**Self contained code example that reproduces the issue**:

In my TestsModule

```
    func testSectionsObservable() {
        
        let task1 = TaskData(name: "Some Task 1", startDate: dateFormatter.date(from: "3/13/17 11:00:00")!)
        let task2 = TaskData(name: "Some Task 2", startDate: dateFormatter.date(from: "3/14/17 12:00:00")!)
        let task3 = TaskData(name: "Some Task 3", startDate: dateFormatter.date(from: "3/15/17 13:00:00")!)
        
        let newTasksArrays = self.scheduler.createColdObservable([
            next(100, []),
            next(200, [task1, task2]),
            next(300, [task1, task2, task3])
            ])
        
        let closedSectionsVariable = Variable<[Int]>([])
        
        let results = scheduler.createObserver([Day].self)
        
        let sectionsCreator = SectionsCreator(tasks: newTasksArrays, closedSections: closedSectionsVariable.asObservable())
        
        self.scheduler.scheduleAt(0) {
            sectionsCreator.days.subscribe(results).addDisposableTo(self.disposeBag)
        }
        
        
        scheduler.start()
        
        let expected = [
            next(100, [Day]()),
            next(200, [Day(weekday:task1.weekday),Day(weekday:task2.weekday)]),
            next(300, [Day(weekday:task1.weekday),Day(weekday:task2.weekday),Day(weekday:task3.weekday)])
        ]
        
        for (i,expect) in expected.enumerated() {
            XCTAssertEqual(results.events[i].value.element!, expect.value.element!)
        }
        
        // Compare actual to expected.
        XCTAssertEqual(results.events.count, expected.count)
    }
```

In My App

```
struct SectionsCreator {
    
    let days: Observable<[Day]> // <- this is what we are testing!!!!!!!!
    
    init(tasks: Observable<[TaskData]>, closedSections: Observable<[Int]>) {
        
        self.days =
            Observable
                .combineLatest(tasks, closedSections) { tasks, closedWeekdays -> [Int: [TaskData]] in
                    
                    var dictionary: [Int: [TaskData]] = [:]
                    for task in tasks {
                        let weekday = task.weekday
                        if dictionary[weekday] != nil {
                            if !closedWeekdays.contains(weekday) {
                                dictionary[weekday]!.append(task)
                                if task.subtasks.count > 0 {
                                }
                            } else {
                                dictionary[weekday] = []
                            }
                        } else {
                            dictionary[weekday] = []
                            if !closedWeekdays.contains(weekday) {
                                dictionary[weekday] = [task]
                            }
                            
                        }
                    }
                    return dictionary
                }
                .debug()
                .map({ dictionary -> [Day] in
                    var days = [Day]()
                    
                    days = dictionary.map({
                        var day = Day(weekday: $0.key)
                        day.items = $0.value.map({ SectionItem.TaskItem($0) })
                        return day
                    }).sorted(by: { lhs, rhs in
                        lhs.weekday < rhs.weekday
                    })
                    
                    return days
                })
    }
    
}
```

**Platform/Environment**

  - [* ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ * ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.2.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ * ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [*] I have a small code base
  - [ ] I have a significant code base

**Comment by adamsmaka** [comment]
And second problem is as you can see above, that I cant make assert like this:
`XCTAssertEqual(results.events, expected)`

**Comment by dpassage** [comment]
For the first problem: `TestableObservable` implements `ObserverType`, but it's not itself a subclass of `Observable`. Adding `.asObservable()` to it in your test code should resolve the problem.

For the second problem, the `XCTAssertEqual` implementations added by `RxTest` only work if the values are `Equatable`. And even if you make `Day` equatable, arrays of things which are `Equatable` are not (yet) themselves `Equatable`.

For situations like that, I'll use `mapWithIndex` or even `zip` on the result `Observable` to check that the data is correct manually; mapping to `true` if it is or `false` if it isn't. Then your `expected` can be stuff like `next(100, true)`, etc.
