### ISSUE TITLE
UI Freeze on subscribe()

### ISSUE THREAD

**Issue by rz-robsn** [ReactiveX/RxSwift#1141]
**Short description of the issue**:

  Hey there, I have met at my work what seems to be a bug on this library. I have a collection view where each cell subscribes to an observable when they come into view. 
The problem occurs after I swipe through the items for a few seconds: I notice a UI freeze when the collection view is about bring an item onscreen. Pausing execution at that moment reveals that the programs blocks in the `subscribe()` method call in the `collectionView(_:cellForRowAtIndexPath:)` delegate implementation, stack trace shown below. 

<img width="1280" alt="screen shot 2017-03-16 at 11 36 53 pm" src="https://cloud.githubusercontent.com/assets/968239/24068314/1dc7f60a-0b62-11e7-8d46-145120a6d8f0.png">

Note: this problem seems awfully similar to [this one](https://github.com/ReactiveX/RxSwift/issues/497), but It does not look like I'm doing anything wrong in my Observable chain.

**Expected outcome**:

No UI freeze, the observable that the cell subscribes to is doing its work on a background dispatch queue, then the result of that work is sent to the main thread via the `observeOn` operator. If the lengthy operation is made on a background thread and the result is then dispatched to the main thread, the UI should never be blocked, right ?

**What actually happens**:

As said in the description, a UI freeze. Notice though that the code I made available through this issue does not exactly reproduce the one I experienced in my real project at work. In our app the UI froze but never unfroze no matter how long we waited, while in the provided code sample the UI freezes for just a few seconds then goes back to normal. If we find a fix for the code sample issue, I'm going to try it out on our actual app to see if it resolves that bug as well.

**Self contained code example that reproduces the issue**:

gist [here](https://gist.github.com/rz-robsn/f815c17dfa601f5c2307b1e1685f2661)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.2.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.2.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

That's it. Thank you in advance !

**Comment by kzaher** [comment]
Hi @rz-robsn ,

you were missing `subscribeOn` after `shareReplay(1)`:

```
 Observable.just(Data(), scheduler: ConcurrentDispatchQueueScheduler(qos: .default))
                    .delay(2, scheduler: ConcurrentDispatchQueueScheduler(qos: .default))
                    .shareReplay(1)
                    .subscribeOn(ConcurrentDispatchQueueScheduler(qos: .default)) // <---
                    .take(1)
```

If there is already a cached element in `shareReplay` it will dispatch it immediately on which ever scheduler one is using (in this case `MainScheduler.instance`). `subscribeOn` would ensure that initial element being emitted and processed on background scheduler.

**Comment by rz-robsn** [comment]
Hey @kzaher, thank you for finding my issue, the fix also work on our app project as well !!! 

I have 2 follow up questions / comments : 

- Could you tell me exactly how does the ReplaySubject determines the scheduler on which the item will be emitted if the item is cached already ? I did not find any mention of that behaviour in the `shareReplay()` or the ReplaySubject documentation.
- To be honest, I expected `shareReplay()` to dispatch the cached item on the same scheduler the source observable is subscribed on. I would find any other behaviour counterintuitive. Could you explain the rationale behind why `shareReplay()` works the way it does ?
