### ISSUE TITLE
Unable to compile after pod install

### ISSUE THREAD

**Issue by switchawk** [ReactiveX/RxSwift#1142]
**Short description of the issue**:
After pod installing for this project for the first time, it seems I'm unable to compile. I have both iOS and macOS targets on this project. It seems the macOS project _does_ compile and the iOS project does _not_.

**What actually happens**:
It seems there is a compilation error as follows: On the file `TextInput.swift` the error is `Value of type 'Reactive<Base>'has no member 'text'`.

I've post a stackoverflow question here: http://stackoverflow.com/questions/42695105/error-compiling-with-rxswift

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
RxSwift 3.2.0

**Platform/Environment**

  - [X ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X ] easy, 100% repro

**Xcode version**:

```
8.2.1
```

**Installation method**:
  - [X] CocoaPods

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X ] just starting

**Comment by kzaher** [comment]
Hi,

sorry, can't repro this.

Pod version:  1.2.0
Xcode: Version 8.2.1 (8C1002)

[CocoaPodiOS.zip](https://github.com/ReactiveX/RxSwift/files/852273/CocoaPodiOS.zip)

Unless I get more information on this, or somebody else can repro this, there isn't anything I can do here.

**Comment by switchawk** [comment]
Any idea what’s the meaning of this error?

**Comment by kzaher** [comment]
I know what it means, but don't know what causes it.

**Comment by switchawk** [comment]
What does it mean? Maybe it’ll point me to the right direction.

**Comment by kzaher** [comment]
Well it means that compiler either can't find `text` property, it's type isn't correct, or something else.

**Comment by switchawk** [comment]
It seems to compile if changed to `self.textInput.text`

**Comment by switchawk** [comment]
I've managed to reproduce this issue in a slimmed down project. You'll need to do `pod install`.

[Example.zip](https://github.com/ReactiveX/RxSwift/files/852762/Example.zip)

**Comment by switchawk** [comment]
Well, placing `RxCocoa` before `RxSwift` in the Podfile seems to have fixed the issue. Didn't know order matters there.

**Comment by goulkreek** [comment]
Hi

  I have this issue under Xcode 9.
  I have tried your suggestions, but still have the issue.
  Maybe RxSwift may change the call to `self.textInput.text` ?
Thx
