### ISSUE TITLE
A crash involving DelegateProxyType.proxyForObject, the main queue, and the main thread.

### ISSUE THREAD

**Issue by groue** [ReactiveX/RxSwift#1151]
**Short description of the issue**:

`DelegateProxyType.proxyForObject` insists on running on the main queue, when the main thread is possibly much enough.

**Expected outcome**:

One can call, for example, `locationManager.rx.didEnterRegion` from within a block executed synchronously from the main thread, without any fatal error:

```swift
// on the main thread
mySerialQueue.sync {
    // should work
    locationManager.rx.didEnterRegion....
}
```

**What actually happens**:

A crash:

```swift
// on the main thread
mySerialQueue.sync {
    // fatal error: Executing on background thread. Please use `MainScheduler.instance.schedule` to schedule work on main thread.
    locationManager.rx.didEnterRegion....
}
```

Note that the error message is wrong: we're *not* executing on a background thread.

The crash comes from `MainScheduler.ensureExecutingOnScheduler()`, on [this line](https://github.com/ReactiveX/RxSwift/blob/09c4b19c48c77435eddc8443f3aaa30e7be7ff66/RxCocoa/Common/DelegateProxyType.swift#L156).

This is delicate, because we're not talking about which thread should an observable run, or on which thread should the results be consumed, or on which thread a subscription should be created. We're talking about the thread in which *the observable itself is created*. A very uncommon problem, I'm sure, and I'm too noob to even know about the work around I should use.

Now, creating the observable on the main queue is *not the expected solution* to this problem, for this would be a workaround, not a solution: `DispatchQueue.async` is an opportunity for the subscription to miss values. The goal is really to create the observable, and subscribe, *right away from the main thread* (in a queue that is not the main queue).

No: if I'm right thinking that `DelegateProxyType.proxyForObject` only uses `MainScheduler.ensureExecutingOnScheduler()` to serialize modifications to the delegate, then an assertion for `Thread.isMainThread` would be enough. And this issue would be avoided.

Thoughts?

**Self contained code example that reproduces the issue**:

I tried my best to describe the problem above. And the issue is more a question about a crash, than the crash itself.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.3

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% report
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.2.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X] yes (irrelevant)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by sergdort** [comment]
I'm assuming that originally `DelegateProxyType` was designed for UIKit

And I feel like there was conversation regarding this with @kzaher . 
Since that method is not thread safe, this assertion ensure developer that he is doing something wrong

**Comment by groue** [comment]
> I'm assuming that originally DelegateProxyType was designed for UIKit

Yes.

> Since that method is not thread safe, this assertion notify developer that he is doing something wrong

In this case, it's wrong telling the developer he's wrong.

But it can't provide a reliable check without false positive: it's impossible to assert that "this piece of code is serialized with the main thread". You can be 1. on the main thread but not on the main queue, 2. on the main queue but not on the main thread, and 3. not on the main queue and not on the main thread but still serialized with the main thread. So many cases, and many of them can't be asserted.

Closing this issue as unsolvable. Thanks for your time, @sergdort (and @fpillet).
