### ISSUE TITLE
Xcode 8.3 Swift 3.1 carthage build error. 

### ISSUE THREAD

**Issue by medisean** [ReactiveX/RxSwift#1156]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://rxswift-slack.herokuapp.com/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

 Can't build in Xcode 8.3 with carthage.

**Expected outcome**:

Build success.

**What actually happens**:

Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1.

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

master

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] Carthage

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] I have a small code base

**Comment by FengDeng** [comment]
You need `carthage build` again.

**Comment by FengDeng** [comment]
Please check your RxSwift.framework headers .You can find words // Generated by Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38).
If not ,rebuild!

**Comment by medisean** [comment]
![2017-03-28 6 17 47](https://cloud.githubusercontent.com/assets/6093631/24400400/e3d07d94-13e2-11e7-9b77-249254cf45b0.png)

**Comment by medisean** [comment]
I wrote a demo and added only RxSwift and the same error occurred.

**Comment by FengDeng** [comment]
Are you check your framework's header? If it build with swift 3.0.2,please remove it and rebuild with swift 3.1.

**Comment by FengDeng** [comment]
File at path:Carthage/Build/iOS/RxSwift.framework/Headers/RxSwift-Swift.h
Check first word,you can know it's build with which swift version.

**Comment by jtilleyj** [comment]
You need to update carthage to 20.1. That did it for me.

From release notes (20.0)
Pre-built Swift binaries will only be used if they were built with the same version of the Swift compiler (#1755)

**Comment by medisean** [comment]
That works! Thank you! @jtilleyj
