### ISSUE TITLE
Add ThreadScheduler

### ISSUE THREAD

**Issue by biboran** [ReactiveX/RxSwift#1160]
**Short description of the issue**:

 `Realm` can be queried only from one thread where it was created. Since neither `OperationQueue` not `DispatchQueue` guarantee that work will be executed on any consistent thread, I found no way to use imbedded schedulers to work on the `Realm` entity within an Rx monad.

**Suggestion**

It would be great if it was possible to instantiate a scheduler that will perform work on a particular thread like so:
```swift
let thread = Thread()
let realmScheduler = ThreadScheduler(thread: thread)
```

**P.S. my research**

What I was able to do for now is:

```swift
final class ThreadWithRunLoopScheduler: ImmediateSchedulerType {
  
  private let thread: ThreadWithRunLoop
  
  init(thread: ThreadWithRunLoop) {
    self.thread = thread
  }
  
  func schedule<StateType>(_ state: StateType, action: @escaping (StateType) -> Disposable) -> Disposable {
    let disposable = SingleAssignmentDisposable()
    
    thread.runLoop.perform {
      disposable.setDisposable(action(state))
    }
    
    return disposable
  }
  
}

final class ThreadWithRunLoop: Thread {
  
  var runLoop: RunLoop!
  
  override func main() {
    runLoop = RunLoop.current
    runLoop.add(Port(), forMode: .commonModes)
    runLoop.run()
  }
  
}

let thread = ThreadWithRunLoop()
thread.start()

let scheduler = ThreadWithRunLoopScheduler(thread: thread)

Observable
  .just()
  .observeOn(scheduler)
  .do(onNext: { print(Thread.current == thread) })
  .subscribe()
```

but I have no idea how such scheduler will behave in different scenarios.

**Comment by kzaher** [comment]
Hi @biboran ,

I'm not sure I understand the original issue.

> Realm can be queried only from one thread where it was created.

In case of mutations I'm assuming that one should create a realm, perform mutations in transaction and then dispose that realm.

In case of observing, I'm assuming one should have one Realm that serves main thread / dispatch queue. I believe MainScheduler.instance should be sufficient.

@icanzilb should know better.

I believe that manually managing threads in *OS is not an optimal solution.

**Comment by icanzilb** [comment]
I also don't fully understand what the issue at hand is. @biboran can you elaborate more? In my experience Realm allows reads and writes from any thread (or process).

**Comment by biboran** [comment]
Let's say I have a component `RealmStringService` that looks as follows:
```swift
class RealmStringService {
  
  let realm: Realm
  let backgroundScheduler: SchedulerType
  
  init(scheduler: SchedulerType, realm: Realm) {
    self.realm = realm
    self.backgroundScheduler = scheduler
  }
  
  func getStringsFromRealm() -> Observable<[String]> {
    return
      Observable
        .just()
        .observeOn(backgroundScheduler)
        .map{ [unowned self] in
          return self.realm.objects(RealmString.self).map{ $0.string }
        }
        .observeOn(MainScheduler.instance)
  }
}
```

If for some reason I have a lot of `RealmString` objects in my `Realm` I would need to query it on some background thread. However, I also want my `realm` property to be easily injectable, so that I could write unit tests for `RealmStringService`.

Here is a sample project I set up with a playground in it: https://github.com/biboran/RealmSchedulerIssue/

@icanzilb Realm does allow reads and writes from a thread where it was instantiated. Could you please take a look at the sample project I set up. Also here is a reference from realm.io - `Sharing Realm instances across threads is not supported` ( https://realm.io/docs/swift/latest/#using-a-realm-across-threads )

Thanks it advance!

**Comment by sergdort** [comment]
I would agree that sometimes you need thread with run look
For example `Realm`'s notifications only works in threads with runloop 

But the thing is that it quite easy to implement. For example I did it like [this](https://github.com/sergdort/CleanArchitectureRxSwift/blob/master/RealmPlatform/Utility/RxUnits/RunLoopThreadScheduler.swift#L4), not sure if it's correct thought :) But it works

**Comment by kzaher** [comment]
Hi guys,

So there are multiple issues here.

I don't know much about Realm, but this seems like a wrong usage to me for this particular task.

This is example from https://realm.io/docs/swift/latest/#using-a-realm-across-threads

```
DispatchQueue(label: "background").async {
  let realm = try! Realm()
  guard let person = realm.resolve(personRef) else {
    return // person was deleted
  }
  try! realm.write {
    person.name = "Jane Doe"
  }
}
```

In the context of RxSwift, this would be something like

```
func getStringsFromRealm() -> Observable<[String]> {
    return
      Observable
        .deferred {
            let realm = try! Realm()
             return self.realm.objects(RealmString.self).map{ $0.string }
        }
        .subscribeOn(somebackgroundScheduler)
}
```

I'm assuming there are cases when one needs to have a long living realm object, but in those cases one could create a scheduler like @biboran and @sergdort are suggesting.

I think it's great we have links to how to create schedulers that run on specific thread, but this would create additional maintenance burden that I don't think we should take in this repo.

**Comment by icanzilb** [comment]
@biboran I'd suggest for you to use Realm as described in the docs (and as Krunoslav suggests above). As I said earlier you can read and write from any thread; unless you lock yourself into a single thread like in your code sample by injecting a realm instance into your class. I don't see any benefit of doing this, only drawbacks

**Comment by biboran** [comment]
Ok, thanks for the discussion! I'll revise my work and think of a better way to inject realm instances.
