### ISSUE TITLE
Mark Observable as open not public 

### ISSUE THREAD

**Issue by wassimseif** [ReactiveX/RxSwift#1163]
**Short description of the issue**:
I'm trying to create an [RxRelay](https://github.com/JakeWharton/RxRelay) for Swift. It's should be like a Broadcaster ( Mediator Design Pattern) but with Reactive base

  _description here_
When i try to write the class `Relay`
```
class Relay<T : ObserverType>: Observable<T>
```
i get an error 
```
Cannot inherit from non-open class 'Observable<T>' outside of its defining module
```
Since in Swift 3 , In order to subclass a class if should be marked as `open`

**Platform/Environment**

  - [ x] iOS
  - [ x] macOS
  - [ x] tvOS
  - [ x] watchOS
  - [ x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.2.1
```

**Comment by sergdort** [comment]
I think  `ObservableConvertibleType` should be enough, isn't it?

**Comment by wassimseif** [comment]
What about the `ObserverType` ?

**Comment by sergdort** [comment]
Yeah, sure. I mean that I think you don't need to inherit from `Observable`

**Comment by sergdort** [comment]
But the thing is that if you conform to `ObserverType` you would need to implement `on(event: Event<T>)` right? But from my understanding you don't want to have this `API`, right?

**Comment by wassimseif** [comment]
I don't know if you're familiar with RxRelay. it's like an event bus, but with Rx implementation. For Example,I have a singleton RxRelay with Location as a type. In some view i subscribe to this `observable` and in some other controllers, i send events to it

**Comment by sergdort** [comment]
From the that library that you've sent it's basically subject without the ability to call onComplete or onError

**Comment by sergdort** [comment]
Which is basically something like this

```
final class PublishRelay<T>: ObservableConvertibleType {
    private let subject = PublishSubject<T>()
    
    func accept(_ element: T) {
        subject.onNext(element)
    }
    
    func asObservable() -> Observable<T> {
        return subject.asObservable()
    }
}
```

Or I missing something?

**Comment by wassimseif** [comment]
According to your code , This is what i got 

```
let userNameRelay  = PublishRelay<String>()
        userNameRelay.accept("Hello")
        
        userNameRelay.asObservable().subscribe { (event ) in
            print(event.element)
        }
        
        userNameRelay.accept("World")
```

Is there a way to NOT write `asObservable` when i want to subscribe

**Comment by wassimseif** [comment]
I created this wrapper. what do you think about ?
```
func subsribe(On on :  ((T) -> Void)?  ){
        subject.asObservable().subscribe(onNext: on)
 }
    
```
So the class becomes 
```
final class PublishRelay<T>: ObservableConvertibleType {
    
    private let subject : PublishSubject<T>
    
    init(){
        subject = PublishSubject<T>()
    }
    
    func subsribe(On on :  ((T) -> Void)?  ){
        subject.asObservable().subscribe(onNext: on)
    }
    
    func accept(_ element: T) {
        subject.onNext(element)
    }
    
    func asObservable() -> Observable<T> {
        return subject.asObservable()
    }
}
```

**Comment by sergdort** [comment]
The only problem that I see so far is the you don't return `Disposable` from the `subsribe` which is important because it will remove subscriber from the subject when you don't want to receive notifications anymore

**Comment by kzaher** [comment]
Hi guys,

@sergdort 👍 for 
```
final class PublishRelay<T>: ObservableConvertibleType {
    private let subject = PublishSubject<T>()
    
    func accept(_ element: T) {
        subject.onNext(element)
    }
    
    func asObservable() -> Observable<T> {
        return subject.asObservable()
    }
}
```

I think this is similar to https://github.com/ReactiveX/RxSwift/pull/1116

I think we could rename `Publisher` -> `Relay` and `EventHub` to `Publisher`.

We could also alias `Variable` = `BehaviorRelay`.

I'm still brainstorming about naming those things.

**Comment by wassimseif** [comment]
@kzaher What do you think is a good implementation of what @sergdort said about returning `Disposables` ?

**Comment by kzaher** [comment]
I think that everything @sergdort said is right, and solution he proposed is the simplest one. Is there some problem with the solution @sergdort proposed?

**Comment by wassimseif** [comment]
@kzaher In this implementation, we can't un-subscribe from the observable

**Comment by sergdort** [comment]
@wassimseif  I think if you return `Disposable` from the `subscribe` then you should be able to do this
