### ISSUE TITLE
Can not get the .old value when observed value changed

### ISSUE THREAD

**Issue by yooomark** [ReactiveX/RxSwift#1164]
**Short description of the issue**:

```swift
rx.observe(SomeType.self, "someVar", options: .old)
       .subscribe(onNext: { object in
           print("\(object)")
       })
```

**Expected outcome**:

  get the old value when `someVar` changed

**What actually happens**:

  always print  `nil`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.3.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 8.3 (8E162)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by Killectro** [comment]
+1 for this, I've encountered this issue as well in a production app and had to work around it. I would love to see a fix for it.

The issue is that in the KVO code, the options being returned are always the `.new` ones. The arguments passed into the RxSwift KVO method are ignored.

**Comment by kzaher** [comment]
Hi guys,

I think unit tests should be working:

```
KVOObservableTests.test_New
KVOObservableTests.test_New_And_Initial
```

> The issue is that in the KVO code, the options being returned are always the .new ones. The arguments passed into the RxSwift KVO method are ignored.

@Killectro why do you think options are ignored?

The reason why we don't support old is because:
* we wanted to have a simple return type `Observable<T>` vs KVO dictionary
* the purpose of the API was to be able to include initial value or not
* One can easily always build a generic operator that returns a tuple of current an previous value:

```swift
extension ObservableType {
    func currentAndPrevious() -> Observable<(current: E, previous: E?)> {
        return self.multicast({ () -> PublishSubject<E> in PublishSubject<E>() }) { (values: Observable<E>) -> Observable<(current: E, previous: E?)> in
            let pastValues = values.asObservable().map { previous -> E? in previous }.startWith(nil)
            return Observable.zip(values.asObservable(), pastValues) { (current, previous) in
                return (current: current, previous: previous)
            }
        }
    }
}

Observable.of(0, 1, 2, 3, 4).currentAndPrevious().subscribe {
    print($0)
}
```

I think we need to document this better.

**Comment by kzaher** [comment]
We can make this API better in 4.0.
