### ISSUE TITLE
Are you planning to release RxSwift.framework.zip?

### ISSUE THREAD

**Issue by shindyu** [ReactiveX/RxSwift#1173]
Hi.
We are using RxSwift. Thank you very much.

I have one question.
Are you planning to release RxSwift.framework.zip?
With that, the time for carthage update is shortened, I am very happy.

**Comment by kzaher** [comment]
Hi,

we had it, but we are investigating Swift compiler 3.1  issues at the moment.

https://github.com/ReactiveX/RxSwift/issues/1171

**Comment by shindyu** [comment]
Thank you very much!
