### ISSUE TITLE
BehaviorSubject questions

### ISSUE THREAD

**Issue by joshuawright11** [ReactiveX/RxSwift#1182]
So I've been using the `BehaviorSubject` classes a lot recently, and I've come across the issue that when using an Rx function on it (flatMap, concat, etc) the return type is an Observable, not a BehaviorSubject. 

I also don't understand why the `value` method throws. Wouldn't it be more Swifty to return an optional? Kind of a pain to `try? subject` every time. I'm probably missing some fundamental about BehaviorSubjects by asking this.  

These issues came up while I was trying to find a type of Observable that would allow access to the last value without subscribing, in addition to being able to be subscribed to. I first tried using `Variable` but was not able to apply rx functions to it. I then tried `BehaviorSubject` but ran into the issues mentioned above. 

So far I've just been using two different variables, one an Observable<Element> and one of type Element, the second being updated on every onNext of the first. Is there a cleaner way to do this?

Thanks! Your library is awesome btw.

**Comment by scotteg** [comment]
Use `Varianle` and call `asObservable()` on it when you want to access its underlying `BehaviorSubject` observable. You can then access the most recent value without subscribing via `value` or subscribe to it as any other observable sequence.

**Comment by joshuawright11** [comment]
Yes, but then it is no longer a Variable so I can't access the value.

**Comment by scotteg** [comment]
It's one or the other. You're either working with it as a value or as an observable, in which case you're working with next event elements to access the underlying value being emitted. If you want to post some of your code I'll see if I can help further.

**Comment by joshuawright11** [comment]
But that seems to be what a BehaviorSubject does, no? The `value()` method returns the most recent value. And again, I would use a BehaviorSubject but applying various rx operators to it makes the return type an Observable, not a BehaviorSubject. 

Here's my reason for asking:

I have a central network accessor class that has an array, `users`. Since that array could updated on a network call, I would like to update all the classes that use it, therefore I made it an observable.

Lets say I would also like to be able to access the `users`'s value for tableView data sources (I could use the included binding methods, but for the example lets say I don't want to) okay, so I'll turn this `users` `Observable` into a `BehaviorSubject` so the value can be accessed with the `value()` method. 

But now, lets say I have a tableView that is only supposed to show the users who are a female. When I do `let femaleUsers = users.flatMap({ $0.gender == .female })` the return type is an `Observable`, not a `BehaviorSubject` (even though `BehaviorSubject` is a type of `Observable`). This means that I can no longer easily get the current value of `femaleUsers` and I can't use `subscribe` for `UITableViewDataSource` methods such as `numberOfRowsInSection` since it requires an immediate return value.

**Comment by scotteg** [comment]
If I understand you correctly, you shouldn't be relying on the underlying observable type within an operator or handler. As I said, use `Variable` if you want to access the latest value of an observable without subscribing to it, and call `asObservable()` on it in order to subscribe to it. Within a chain of operators such as `map` you are working with emitted elements and return an `Observable` to the next operator in the chain (or to `subscribe`), not the original original observable type. I'm not sure I can help you any further unless you share the actual code you're working with.

**Comment by joshuawright11** [comment]
Thanks for the resHopefully this makes it more clear what I'm asking

```
class NetworkAccess {
    
    // So every class can access the same, current list of users
    static var users: Variable<[User]> = Variable<[User]>([])
    
    //...
    
    func loadUsers() {
        api.fetchUsers().subscribe(onNext: { fetchedUsers in
            self.users.value = fetchedUsers
        })
    }
}

class Example: UIViewController {
    
    func showAllUsers() {
        let allUsers = NetworkAccess.users
        let allUsersVC = UsersTableView(usersToShow: allUsers)
        present(allUsersVC, animated: true, completion: nil)
    }
    
    func showFemaleUsers() {
        
        
        // Here is where the issue is I want to apple rx operators to this but cant without 
        // turning it back into an observable.
        //
        // If I do `NetworkAccess.users.asObservable().flatMap { ... that would sucessfully apply the
        // filter, but then the return value would be an observable (the `value` could no longer be 
        // accessed for the `UsersTableView` UITableViewDataSource methods).
        //
        // Any way to accomplish the filtering of a Variable while still being able to subscribe to and
        // get the last value without a subscription?
        //
        // v v v v v v v v v v v v v v v v v v v v v v v v v v v v v
        let femaleUsers = NetworkAccess.users.flatMap { users in
            return users.filter { $0.gender == .female }
        }
        // ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
        //
        //
        
        let femaleUsersVC = UsersTableView(usersToShow: femaleUsers)
        present(femaleUsersVC, animated: true, completion: nil)
    }
    
}

class UsersTableView: UITableViewController {

    var usersToShow: Variable<[User]>
    
    init(usersToShow: Variable<[User]>) {
        self.usersToShow = usersToShow
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        usersToShow.asObservable().subscribe(onNext: { _ in
            self.tableView.reloadData()
        }).addDisposableTo(disposeBag)
        
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return usersToShow.value.count
    }
    
    // ... more UITableViewDataSource/Delegate methods
    
}
```

**Comment by joshuawright11** [comment]
Nevermind, I think I should just go about filtering/transforming the Variables in a different way.

**Comment by ksoftllc** [comment]
Interested in how you'd do this now that Variable is being deprecated. Any thoughts?

**Comment by freak4pc** [comment]
`variable.value` getter == `relay.value` getter
`variable.value = value` == `relay.accept(value)`
