### ISSUE TITLE
PrimitiveSequence debug methods missing (Enhancement Request)

### ISSUE THREAD

**Issue by mwoollard** [ReactiveX/RxSwift#1183]
**Short description of the issue**:

```
Completable.empty().debug()
Single<Int>.just(1).debug()
Maybe<Int>.just(1).debug()
```
All give `xxx has no member 'debug'` compiler error since debug feature hasn't been implemented for PrimitiveSequence types. 

**Expected outcome**:

I'd expect to be able to use .debug() on PrimitiveSequence types.

**What actually happens**:

Compiler error

**Self contained code example that reproduces the issue**:

See above

**Platform/Environment**

Effects all

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% reproducible

**Xcode version**:

```
8.3
```
If it is agree this is desirable I'm happy to contribute a PR to implement.

**Comment by kzaher** [comment]
Hi @mwoollard ,

that operator is already in our codebase, we just need to ship it.

**Comment by mwoollard** [comment]
OK great !
