### ISSUE TITLE
Crash in RxExample iOS app when closing API wrappers example

### ISSUE THREAD

**Issue by MaximeLM** [ReactiveX/RxSwift#1186]
**Short description of the issue**:

The RxExample iOS app crashes when closing the "API wrappers" example

**Expected outcome**:

The app should continue working

**What actually happens**:

The app crashes with an assertion failure:

*assertion failed: Resources weren't cleaned properly, 98 remained, 84 expected: file /Users/<...>/RxSwift-3.4.0/RxExample/RxExample/ViewController.swift, line 94*

**Steps to reproduce**:

- Start the RxExample-iOS app
- Tap the "API wrappers" cell
- Wait a few seconds
- Tap "Rx Examples" to go back

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.4.0 - https://github.com/ReactiveX/RxSwift/releases/tag/3.4.0

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 8.3 (8E162)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [X] Manual

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @MaximeLM ,

could you please try with Xcode 8.3.1?

**Comment by MaximeLM** [comment]
Hi @kzaher ,

Still crashing with Xcode 8.3.1. 

I noticed that by removing the line 164 of RxExample/RxExample/Examples/APIWrappers/APIWrappersViewController.swift, the app no longer crashes.
`
_ = textView.rx.textInput <-> textViewValue
`

**Comment by kzaher** [comment]
Hm....

Anybody else can repro this? 

What device you are using? And configuration?

**Comment by MaximeLM** [comment]
iPhone 6, iOS 10.3.1, plugged on MacBook pro 2016 13'', macOS Sierra 10.12.4, Xcode 8.3.1

**Comment by kzaher** [comment]
It should work ok now. Thnx
