### ISSUE TITLE
Project with -all_load flag can't compile

### ISSUE THREAD

**Issue by Alak** [ReactiveX/RxSwift#1188]
**Short description of the issue**:

I've an issue with the recent version of RxSwift 
in my app I use  XCode's Other Linker Flags: `-all_load`
iIt was working perfectly in RxSwift 3.1.0 but now with RxSwift 3.4.0
I can't build anymore: `ld: framework not found XCTest for architecture arm64`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _3.4.0_

**Platform/Environment**

  - [*] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [* ] easy, 100% repro

**Xcode version**:

```
8.3.1
```

**Installation method**:
  - [*] Carthage

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [*] yes (8.2 and 8.3.1)

**Level of RxSwift knowledge**:
  - [*] I have a significant code base

**Comment by kzaher** [comment]
Hi @Alak ,

are you shipping RxTest library?

**Comment by Alak** [comment]
No, I'm doing more test to find since when it's not working

**Comment by kzaher** [comment]
Hi @Alak ,

any news on this? Did you find any issue with the library?

**Comment by Alak** [comment]
Hey @kzaher so after a day of testing, the problem come from the recent carthage update and the way we are statically linking the third party libraries. So nothing linked to RxSwift.

Thanks for your time.
