### ISSUE TITLE
Implement mergeDelayError operator

### ISSUE THREAD

**Issue by Ded77** [ReactiveX/RxSwift#1191]
**Short description of the issue**:

No mergeDelayError operator.

> merge-delay-error is like merge, but will emit all items from all of the merged Observables even if one or more of those Observables terminates with an onError notification while emissions are still pending.
cf. [http://reactivex.io/documentation/operators/merge.html](url)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.4.0

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @Ded77 ,

could you please provide some context for this? This looks like a really specific operator to me.

**Comment by Ded77** [comment]
Hi @kzaher,

My use case is quite simple :
I need to retrieve data from the network. This data is then cached.
When I make the same call again, I first return the cached data if it exists, then the data from the network.

```swift
func fetchData() -> Observable<Data> {
  return Observable
    .of(cachedData, fetchDataOnNetwork)
    .merge()
}
```

In most of the cases, the fetching of cached data is faster than those of the network, so I can display the cached data then the network data (or possibly a network error).

But in some cases (with the iPhone in Airplane mode for example), the network error is sent before the cached data, so I will never be able to show the cached data (the sequence terminates with an error).

So I need to delay the network error to first display the cached data : this is the meaning of the `mergeDelayError` operator.

The corrected code could be : 
```swift
func fetchData() -> Observable<Data> {
  return Observable
    .of(cachedData, fetchDataOnNetwork)
    .mergeDelayError()
}
```

Thank you 😊

**Comment by kzaher** [comment]
Is there some reason why you aren't using `concat` for this behavior? It seems to be that you really want concat.

Even if `mergeDelayError` operator existed, there are no guarantees that the end result wouldn't be cached data.

**Comment by Ded77** [comment]
You are right, `concat` perfectly fullfil my need.
Thanks again !

**Comment by bimusiek** [comment]
Hey, I think it would still be quite useful. 

I am using `concat` now, however, if there is an error in the middle of all observables then it does not even trigger next ones. It quits and returns an error. 

I would love to get behavior where all observables are triggered and then I get an error at the end.

**Comment by AAverin** [comment]
Coming from RxJava/RxKotlin, was surprised to not see `mergeDelayError` operator. Pretty common thing there. Description can be found here:
http://reactivex.io/documentation/operators/merge.html
Main idea is to let all merged observables run and deal with error later:
```
mergeDelayError behaves much like merge. The exception is when one of the Observables being merged terminates with an onError notification. If this happens with merge, the merged Observable will immediately issue an onError notification and terminate. mergeDelayError, on the other hand, will hold off on reporting the error until it has given any other non-error-producing Observables that it is merging a chance to finish emitting their items, and it will emit those itself, and will only terminate with an onError notification when all of the other merged Observables have finished.
```

**Comment by TomasLinhart** [comment]
I also would like to see this operator in RxSwift. It exists in RxJS and RxJava, and it is useful in cases where you want to execute the array of observables, and you don't care if they succeed.

One of the examples could be syncing images in the background. If some images are not sent it shouldn't prevent other images from sending. The failed can try to be sent next time.

**Comment by JakeSc** [comment]
Reopened this issue here: https://github.com/ReactiveX/RxSwift/issues/1652.
