### ISSUE TITLE
Add elements() & errors() method on materialize operator

### ISSUE THREAD

**Issue by frederik-jacques** [ReactiveX/RxSwift#1193]
**Short description of the issue**:

The `materialize` operator was added in RxSwift 3.4 (previously this was available in the RxSwiftExt library), but 2 convenience methods where not ported to the RxSwift repo:

1. `elements()`
2. `errors()`

I don't know if this was a made decision, or if this was just forgotten.

**Expected outcome**:

The `elements()` and `errors()` convenience methods are available.

**What actually happens**:

You have to manually filter, check the type of the event and then map it to the correct type.

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 8.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by fpillet** [comment]
We're re-adding them to RxSwiftExt for now (if the decision is made to move them to core, I'll remove them again from RxSwiftExt). PR has been merged, please wait a bit for the release or point to repo HEAD to get them.

**Comment by kzaher** [comment]
Hi guys,

> I don't know if this was a made decision, or if this was just forgotten.

I would rather not include `elements()` and `errors()` for now inside the main repo :)

**Comment by fpillet** [comment]
I have released a new version of RxSwiftExt with these operators. Adam provided the implementation today.

**Comment by frederik-jacques** [comment]
@fpillet I just updated RxSwiftExt, but it doesn't recognize the methods?

I also just created an empty project with RxSwift/RxSwiftExt pods and tried the following code, but it says elements() and errors() does not exist.

`
import RxSwift
import RxSwiftExt

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let o = Observable<String>.just("hello").materialize().share()
        
        let b = o.elements() // ERROR: Value of type 'Observable<Event<String>> has no member elements'
        
        return true
    }

`

Am I missing something?

**Comment by i-schuetz** [comment]
Just curious, what's the reasoning to not include `elements()` and `errors()` in the main repo? Too much "convenience"? Bad practice? Is there a recommendation to what to use instead?

**Comment by freak4pc** [comment]
Hey Ivan :) 
It's hard knowing the considerations of 3-4 years in the past but I think the main thing is that we avoid as much as possible to add very "simple" code inside RxSwift. 

When I say simple, I basically mean "something anyone could write up really quickly". Which is why we also don't provide Binders for some simple things, since it's very easy to create yourself.

`errors()` and `elements()` are basically one-liner operators, so they're not really worth adding to Core: 

```swift
public extension ObservableType where Element: EventConvertible {
    func elements() -> Observable<Element.Element> {
        compactMap { $0.event.element }
    }

    func errors() -> Observable<Swift.Error> {
        compactMap { $0.event.error }
    }
}
```

**Comment by i-schuetz** [comment]
Ah, thanks for the explanation! 😁
