### ISSUE TITLE
Question about ConcurrentDispatchQueueScheduler

### ISSUE THREAD

**Issue by haritowa** [ReactiveX/RxSwift#1198]
Hello, I can't understand [this](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/ConcurrentDispatchQueueScheduler.swift#L37) method's use case. On a glance - it should wrap global concurrent queue, but, as far as I can see - it [creates](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/ConcurrentDispatchQueueScheduler.swift#L38-L43) new queue each time it is invoked. [There is version](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/SerialDispatchQueueScheduler.swift#L80-L82) of this method for SerialDispatchQueue(and it seems to work properly). 

> In addition to the serial main queue, the system also creates a number of global concurrent dispatch queues. You can access the global concurrent queue that best matches a specified quality of service (QoS) using the global(attributes:) type method.

From documentation, global queues are concurrent, so it should be safe to use them in ConcurrentScheduler(at least as a [target](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/ConcurrentDispatchQueueScheduler.swift#L42) for internal queue). Maybe I miss something, can you please help me?

**Comment by sergdort** [comment]
The idea of having `ConcurrentScheduler ` is to provide abstraction on concurrent queues.
Even though `Global` queues are concurrent for some use cases users might want to have specific queue to be responsible for doing some work e.g image processing, parsing data and so on

The reason why `ConcurrentScheduler ` creates new queue each time is that consumer need to keep reference to the `scheduler` and pass it in `observeOn` or `subscribeOn`

For example 

````swift
final class SomeService {
    let scheduler: ConcurrentScheduler

    func someMethod() -> Observable<Something> {
        return getSomething().observeOn(scheduler)
    }
}
````

**Comment by haritowa** [comment]
@sergdort Sorry, i didn't get you. If you want to create `ConcurrentScheduler` with custom queue, you always can use this [init](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/ConcurrentDispatchQueueScheduler.swift#L29). On the other side, method i mentioned in question was 
> for scheduler that wraps one of the global concurrent dispatch queues

as method comment says. But it just "convenience" init, which creates queue with requested QoS for each created scheduler(i.e. if you create two ConcurrentScheduler with same QoS, it will create two queues, instead of use global queue two times). I'm a little confused, case this method for SerialQueueScheduler use global queue, as it comment says, but create new for ConcurrentScheduler.

**Comment by haritowa** [comment]
Oh, I see, sorry
> All custom dispatch queues have the concept of a target queue. In essence, a custom dispatch queue doesn't actually execute any work, but passes work to its target queue for execution. Normally the target queue of a custom queue is the default-priority global queue.

But I'm still wondering, why not using .global? For label?

**Comment by kzaher** [comment]
Hi guys,

I think the reason why there was an initialization vs using existing global dispatch queue was that we could label it with some custom rx description. 

Serial dispatch queue scheduler had internal serial dispatch queue name labelled rx.*. That being said, I'm not sure where those names actually useful to anyone, so we might just use one of the global ones.
