### ISSUE TITLE
Can I user this library on both iOS 7, 8 and 9 ?

### ISSUE THREAD

**Issue by FangYiXiong** [ReactiveX/RxSwift#120]

**Comment by kzaher** [comment]
Hi @FangYiXiong,

I believe you should, yep :)

**Comment by bontoJR** [comment]
I can confirm that RxSwift works perfectly with iOS 7, the only problem is that it cannot be used with CocoaPods, but it should be imported as external project. I am currently using it as git submodule.

I will close this issue, if you have any other question please don't hesitate to ask. :+1:
