### ISSUE TITLE
Is there a way to suppress `Recursive call` error in Debug scheme in some certain code?

### ISSUE THREAD

**Issue by owenzhao** [ReactiveX/RxSwift#1201]
*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

 I encounter "Warning: Recursive call or synchronization error!" on my intended code.

**Expected outcome**:

  The code won't recurse endlessly.

**What actually happens**:

 I got the fatal error message in Debug mode. 

**Self contained code example that reproduces the issue**:

```swift
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let center = NotificationCenter.default
    let noti = Notification(name: MyNotificationName)
    let v = Variable(0)
    
    v.asObservable()
        .subscribe(onNext:{ _ in
            center.post(noti)
        })
        .disposed(by: disposeBag)

    center.rx.notification(MyNotificationName)
        .asObservable()
        .subscribe(onNext: { [unowned self] _ in
            print(v.value)
            if v.value == 10 {
                self.disposeBag = DisposeBag()
            }
            else {
                v.value += 1 // cause the issue
            }
        })
        .disposed(by: disposeBag)
    
    v.value = 1
}

let MyNotificationName = Notification.Name.init(rawValue: "My Notification Name")
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift (3.3.1), RxCocoa (3.3.1)

**Platform/Environment**

  - [*] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [*] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 8.3.1 (8E1000a)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [*] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [*] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @owenzhao ,

Like you've noticed, this will only appear in DEBUG build to warn you that you've created a cyclic data dependency.

If you are ok with that cyclic dependency, you can do
```
center.rx.notification(MyNotificationName)
        .observeOn(MainScheduler.asyncInstance)
        ....
```

Although, my suggestion would be to make that code simpler ;)

**Comment by owenzhao** [comment]
@kzaher , thank you. You answer is what I exactly want. I am doing something with `EventKit`'s `EKEventStoreChanged` notification, which leads the error.
