### ISSUE TITLE
 Use of unresolved identifier 'Materialize' RXSwift Compiler error

### ISSUE THREAD

**Issue by akjesto** [ReactiveX/RxSwift#1203]
**Short description of the issue:**

 Use of unresolved identifier 'Materialize'
 Use of unresolved identifier 'Dematerialize'
These issue Happened in **Observable+Single.swift**

**Self contained code example that reproduces the issue:**

```
 extension ObservableType {
     public func materialize() -> Observable<Event<E>> {
        return Materialize(source: self.asObservable())
    }
}

extension ObservableType where E: EventConvertible {
       public func dematerialize() -> Observable<E.ElementType> {
        return Dematerialize(source: self.asObservable())
    }
}

```
**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.4.0

Platform/Environment

- [x]  iOS
- [ ]  macOS
- [ ]  tvOS
- [ ]  watchOS
- [ ]  playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

- [x]  easy, 100% repro
- [ ]  sometimes, 10%-100%
- [ ]  hard, 2% - 10%
- [ ]  extremely hard, %0 - 2%

**Xcode version:**
8.2.1

Installation method:

- [x] CocoaPods
- [ ]  Carthage
- [ ]  Git submodules

**I have multiple versions of Xcode installed:**

- [x]  yes (8.2.1,7.2,7.3.1,8.0)
- [ ]  no

Level of RxSwift knowledge:
(this is so we can understand your level of knowledge
and formulate the response in an appropriate manner)

- [x]  just starting
- [ ]  I have a small code base
- [ ]  I have a significant code base

**Comment by kzaher** [comment]
Hi @akjesto , 

could you please fill out issue template? I need more information.

**Comment by akjesto** [comment]
Hi @kzaher ,
I updated the issue.Please check it

**Comment by kzaher** [comment]
Hi @akjesto ,

could you maybe create and empty project with Podfile and see it it happens there? This looks like it's maybe some CocoaPods issue.

**Comment by kzaher** [comment]
Hi @akjesto ,

I've just realized that you were using Xcode 8.2.1. 

Apple has deprecated Swift 3.0 so the 3.4.0 release only supports Swift 3.1+, otherwise we need to add another dimension to our matrix. 

This probably wouldn't be much useful anyway since Swift 3.1 is backwards compatible, so don't see any reason why not just use latest Xcode version.
