### ISSUE TITLE
Observable.combineLatest with an empty collection does not complete.

### ISSUE THREAD

**Issue by scottrhoyt** [ReactiveX/RxSwift#1205]
**Short description of the issue**:

  `Observable.combineLatest(Collection)` with an empty `Collection` does not complete.

**Expected outcome**:

  The `Observable` completes immediately.

**What actually happens**:

  The `Observable` does not complete.

**Self contained code example that reproduces the issue**:

```swift
let disposeBag = DisposeBag()

Observable.combineLatest([Observable<String>]()) { $0 }
    .subscribe(onCompleted: { print("completed!") })
    .addDisposableTo(disposeBag)

// never prints "completed!"
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (8.3.1, 8.2.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @scottrhoyt ,

yeah, I think we need to improve that behavior. I'm still not sure what is the best way to handle this. Completing the sequence seems the most probably candidate.

Were you using this to wait for aggregate network requests? What was the use case?

**Comment by scottrhoyt** [comment]
@kzaher similar. 

My use case is waiting for an aggregation of local queries (in this case, querying a user's contacts). I filter some data (an array) before mapping it to an array of observables that I combine into an observable of an array. The completion of this combined observable has a side effect of stopping a loading indicator. I noticed that when the filtering process produced an empty array, the resulting combined observable would never complete and my loading indicator would never stop.

It was fairly simple to workaround by mapping to an empty observable when the data set is empty, but the behavior was counterintuitive to me.

**Comment by kzaher** [comment]
@scottrhoyt yeah, agreed. We'll fix this somehow.

**Comment by kzaher** [comment]
We have the same problem with zip operator. Combine latest is more straightforward to solve, but we'll figure something out. I would like to investigate first how other implementations are behaving in these cases.

**Comment by PatrickSCLin** [comment]
I occurred this situation when I use zip , hope it will fix soon

**Comment by scottrhoyt** [comment]
Thanks @kzaher. Let me know if you need any additional feedback.

**Comment by kzaher** [comment]
Fix for this is pushed in develop branch. We'll release this in a couple of days.

**Comment by xrnd** [comment]
I tried to use Observable.empty() in Zip operator. The completion block wouldn't execute in that case. I tried a sort of hack 
`Observable<Response>.empty().ifEmpty(default: Response(statusCode: 0,data: Data.cs_emptyValue()))`
My expected value of Observable is Response. (Maya Response object) I gave it empty data and status code 0 with Observable type <Response>. Yes ! it worked. 
Zip is the solution with dynamic observable call creation.

**Comment by norcisa-andy** [comment]
I run into this issue while testing view models using RxCocoa. In my case I have something like 

`let search = Variable("")`
`search.flatMapLatest { query -> Observable<Result> in `
`   guard !query.isEmpty else {`
`                    return .empty()`
 `               }`
   `             return ... //Some observable `
