### ISSUE TITLE
Disable button until network request returns

### ISSUE THREAD

**Issue by jayesh15111988** [ReactiveX/RxSwift#1209]
I have seen this feature in ReactiveCocoa where tapping a button invokes a network request. While request is in progress, the button is inactive and it prevents user from tapping it multiple times thereby avoiding any unwanted side effects. Does RxSwift offer similar functionality? I went through documentation, but could not find a hint on how to do it.

**Comment by sergdort** [comment]
Hi, @jayesh15111988 there is examples in the RxSwift repo.
I think the one you're interested is [this](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/GitHubSignup/UsingVanillaObservables/GitHubSignupViewController1.swift#L46)

**Comment by jayesh15111988** [comment]
@sergdort I thought of that earlier. So we have to do it manually based on the viewModel state? Is that a good practice as far as RxSwift standards are concerned?

**Comment by kzaher** [comment]
@jayesh15111988 we don't have any official standards regarding this because this is in higher layer of abstraction that this repo is concerned, but I don't see a problem with the proposed solution.

The way UI is blocked during async operations is usually highly customizable.
