### ISSUE TITLE
Is there a way to check when a tableview is about to insert a cell, or delete a cell?

### ISSUE THREAD

**Issue by rslim087g** [ReactiveX/RxSwift#1210]
So I'm binding an observable Chat to a tableView through animated data source 
     
          let dataSource = RxTableViewSectionedAnimatedDataSource<Section>()
                  Chats.asObservable()
               .bind(to: tableView.rx.items(dataSource: dataSource))
                  .addDisposableTo(disposeBag)
        
        dataSource.configureCell = { dataSource, tableView, indexPath, item in
            
            let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") ?? UITableViewCell(style: .default, reuseIdentifier: "Cell")
            cell.textLabel?.text = item.lastMessageText
            return cell
        }

Then to check if a cell is going to be inserted or not, i wrote this 

        tableView.rx.itemInserted.subscribe(onNext: { (index) in
            print("insert")
        }).addDisposableTo(disposeBag)
        
itemInserted never gets fired! I was wondering what i'm doing wrong, or if someone has a working example of itemInserted!

**Comment by tomokitakahashi** [comment]
Hi , @rslim087g ✋ 
Maybe , I think `rx.itemInserted` called when you used `tableView.insertRows`. 
If you append new data to `Chats`, not called it
I recommend using `Chats.asObservable().distinctUntilChanged()` !
Sorry if I made a mistake.
There seems to be more ideas...

**Comment by kzaher** [comment]
Hi guys,

`rx.itemInserted` is called when user requires adding a cell in the ui. It's a wrapper for UITableView delegate method. This is by design as far as I can tell.
