### ISSUE TITLE
Why is do not called after subscribing

### ISSUE THREAD

**Issue by onmyway133** [ReactiveX/RxSwift#1212]
Hi, I have `a` which is `subscribed` via `Observable.of`, it is a bit indirect, but why the `do` block does not get called?

The scenario is I have a long chain (like `a`, `b`, `c`, `d`, `e`, ...) and I want to `do` in some `Observable` in the middle of the chain
 
```swift
let a = PublishSubject<Int>()
let b = PublishSubject<Int>()
let c = PublishSubject<Int>()

a.bindTo(b)
b.bindTo(c)

c.subscribe(onNext: {
  print($0) // called
})

a.do(onNext: {
  print($0) // not called 🤔
})

Observable.of(a).merge().subscribe(onNext: {
  print($0) // called
})

a.onNext(1)
a.onNext(2)
```

**Comment by sergdort** [comment]
Hi, @onmyway133! `Do` like other operators wont do anything until you subscribe.

**Comment by onmyway133** [comment]
@sergdort Hi, thanks for your quick reply. Here I subscribe to `a` indirectly, via `c` and `Observable.of`. How can I hook up to `a` event? I want to perform some side effect when `a` works in the chain

**Comment by sergdort** [comment]
You can do:

```swift
let d = a.do(onNext: {
  print($0)
})
Observable.of(b, c, d).merge().subscribe(onNext: {
  print($0) // called
})
```

**Comment by kzaher** [comment]
```
a.do(onNext: {
  print($0) // not called 🤔
}) <-- result is observable sequence that is discarded
```

@sergdort provided the "correct" code

**Comment by onmyway133** [comment]
@sergdort @kzaher thanks, I think I get it
