### ISSUE TITLE
setDelegate(self) not working. tableView viewForHeaderInSection does not get triggered.

### ISSUE THREAD

**Issue by rslim087g** [ReactiveX/RxSwift#1214]
Apparently, to use tableView delegate methods, I'm supposed to set the tableview.rx delegate to self

This is not working unfortunately. ViewforHeaderInSection never gets called. This is the code that I wrote for it: 

    func setUpTableBinding() {
                
        let dataSource = RxTableViewSectionedAnimatedDataSource<Section>()

        dataSource.configureCell = { ds, tv, ip, item in
            let cell = tv.dequeueReusableCell(withIdentifier: "cell", for: ip)  as! MessagesViewControllerCell
            cell.label.text = item.lastMessageText
            return cell
        }
        
        tableView.rx.setDelegate(self)
            .addDisposableTo(disposeBag)
       
        Chats.asObservable()
            .bind(to: tableView.rx.items(dataSource: dataSource))            
            .addDisposableTo(disposeBag)   
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
    let headerView = UIView(frame: CGRect(x: 0, y: 0, width: tableView.bounds.size.width, height: 20))
    headerView.backgroundColor = UIColor.red
    return headerView
    }

**Comment by kzaher** [comment]
Hi @rslim087g ,

I've tested this and it works. Just try adding 

```
func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let headerView = UIView(frame: CGRect(x: 0, y: 0, width: tableView.bounds.size.width, height: 20))
        headerView.backgroundColor = UIColor.red
        return headerView
    }
```

to the bottom of `SimpleTableViewExampleSectionedViewController` in this repo, and check out for yourself.

Maybe there is something weird happening with ` Chats.asObservable()`. Don't know.

**Comment by SheldonWangRJT** [comment]
I am seeing this happens on my project as well. I am using 3.6.1 and language is Swift 4, Xcode version is Version 9.2 (9C40b). Anybody seeing this again?
