### ISSUE TITLE
DZNEmptyDataSet not compatible with tableview binding. Was anyone able to make it work?

### ISSUE THREAD

**Issue by rslim087g** [ReactiveX/RxSwift#1219]
I'm trying to set up an empty dataset with DZNEmptyDataSet while my tableview is bound to a  variable  
                 let Chats = Variable([Section]()). 

      Chats.asObservable()

            .bind(to: tableView.rx.items(dataSource: dataSource))

The problem is, even when Chats is empty, the empty dataSet for the tableview doesn't show. If i remove the bind function, it shows. I was wondering if anyone was able to make the two coexist?

**Comment by kzaher** [comment]
Hi @rslim087g ,

I think you'll maybe need to conform `dataSource` to `DZNEmptyDataSetSource, DZNEmptyDataSetDelegate` or use 
```
    self.tableView.emptyDataSetSource = self;
    self.tableView.emptyDataSetDelegate = self;
```

Try extending `RxTableViewDataSourceProxy` with `DZNEmptyDataSetSource, DZNEmptyDataSetDelegate`.

Maybe setting 
```
    self.tableView.emptyDataSetSource = self.tableView.rx.dataSource;
    self.tableView.emptyDataSetDelegate = self.tableView.rx.dataSource;
```

have no idea.

This doesn't seem like an issue with this repository, so closing it here. Maybe something will respond to you and help you.

**Comment by JustinM1** [comment]
I had an issue with DZNEmptyDataSource, I had to subclass the AnimatedDataSource. Here is a snippet for anyone who may find it useful. 

    final class MyRxTableViewSectionedAnimatedDataSource<S: AnimatableSectionModelType>: RxTableViewSectionedAnimatedDataSource<S> {

    private var currentItemsCount = 0

    var isEmpty: Bool {
       return currentItemsCount == 0
    }

    override func tableView(_ tableView: UITableView, observedEvent: Event<[S]>) {
        super.tableView(tableView, observedEvent: observedEvent)
        switch observedEvent {
        case let .next(events):
            guard let lastEvent = events.last else { return }
            currentItemsCount = lastEvent.items.count
        default: break
        }
      }
    }

Then return the dataSource.isEmpty property in DZNEmptyDataSetDelegate

    func emptyDataSetShouldDisplay(_ scrollView: UIScrollView!) -> Bool {
        return dataSource.isEmpty
    }

[https://stackoverflow.com/questions/43625287/dznemptydataset-not-compatible-with-tableview-binding-in-rxswift-was-anyone-abl/45929436#45929436](url)
