### ISSUE TITLE
Adding RxSwift to Swift Source Compatibility Test Suite

### ISSUE THREAD

**Issue by sunflash** [ReactiveX/RxSwift#1220]
I really like using RxSwift in daily basis.
It's probably a good idea, to add RxSwift to "Swift Source Compatibility Test Suite".
[https://swift.org/blog/swift-source-compatibility-test-suite](https://swift.org/blog/swift-source-compatibility-test-suite)
[https://swift.org/source-compatibility/#current-list-of-projects](https://swift.org/source-compatibility/#current-list-of-projects)
ReactiveSwift, ReactiveCocoa, RxDataSources is already includes in the list. 😃

**Comment by kzaher** [comment]
Hi @sunflash ,

thnx for reporting this, I'll try to add it there. I have no idea how RxDataSources ended up there and and RxSwift didn't.

**Comment by jamiepinkham** [comment]
Pull request to Swift Source Compatibility Suite: https://github.com/apple/swift-source-compat-suite/pull/29

**Comment by jamiepinkham** [comment]
This has been merged.
