### ISSUE TITLE
Unexpected merge behaviour

### ISSUE THREAD

**Issue by palcalde** [ReactiveX/RxSwift#1221]
**Short description of the issue**:
The operator merge in RX Swift Completes if I try to merge A and B observable and A completes synchronously, it doesn't even subscribes to B.

**Expected outcome**:
I would expect merge to not complete until A and B (both) complete. In this scenario A completes synchronously but since B doesn't, I expect the merge result observable to not complete. 

I've confirmed that in RXKotlin(https://www.google.es/search?q=rx+kotlin&oq=rx+kotlin&aqs=chrome..69i57j0l5.1369j0j7&sourceid=chrome&ie=UTF-8) works as expected, in the example I've provided merge([a,b]) and merge([b,a]) both output the same result.

**What actually happens**:
As seen in the oficial documentation (http://www.introtorx.com/Content/v1.0.10621.0/12_CombiningSequences.html#Merge) merge should only complete once all the inner observables complete. 

When I merge two observables A and B with with the RX Swift operator, if A and B are asynchronous then the behaviour works as expected. However, if A completes synchronously (meaning that completes on the subscribe action synchronously, like Observable.empty()) the merged observable Completes and Disposes before doing the subscription to B.  

**Self contained code example that reproduces the issue**:

```
let a = Observable<Int>.empty()
let b = Observable<Int>.interval(1.0, scheduler: MainScheduler.asyncInstance).asObservable()

//Doesn't work, onDisposed gets called and nothing gets printed
Observable.merge([a,b]).subscribe(onNext: { i in
    print(i)
}, onError: { _ in
    print("error")
}, onCompleted: { 
    print("completed")
}, onDisposed: {
    print("disposed")

//works, prints 1,2,3,4.. even tho A subscription is disposed
Observable.merge([b,a]).subscribe(onNext: { i in
    print(i)
}, onError: { _ in
    print("error")
}, onCompleted: {
    print("completed")
}, onDisposed: {
    print("disposed")
})
```
 

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
3.2

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3
```

**Comment by kzaher** [comment]
Hi @palcalde ,

I think I know where is the problem. We'll fix this.

**Comment by palcalde** [comment]
Thanks!, let me know if you need anything else.

**Comment by kzaher** [comment]
Fix for this is pushed in `develop` branch. We'll release this in a couple of days.
