### ISSUE TITLE
binding value to tableview

### ISSUE THREAD

**Issue by croccio** [ReactiveX/RxSwift#123]
how can i binding array to tableview? the example is with section, i want only one section, but i don't know how to replace allUsers  without combineLatest, because i've only one section and one array

    let allUsers = combineLatest(favoriteUsers, users) { favoriteUsers, users in
            return [
                SectionModel(model: "Favorite Users", items: favoriteUsers),
                SectionModel(model: "Normal Users", items: users)
            ]
        }

**Comment by kzaher** [comment]
Hi @croccio ,

I think you can just use `Variable([
            SectionModel(model: "Favorite Users", items: [])
])`

hope that helps :)

**Comment by croccio** [comment]
thank you, i've solved :)
