### ISSUE TITLE
UIButton + DisposeBag in UIBarButtonItem = memory leak

### ISSUE THREAD

**Issue by Arnoymous** [ReactiveX/RxSwift#1230]
I have a subclass of UIButton with a DisposeBag and rx subscribes, when I add it in to a UIViewController I have no problems with the disposeBag but when i add it in a 
`self.navigationItem.rightBarButtonItem = UIBarButtonItem(customView: MY_BUTTON)`
the disposeBag in my button don't dispose :(

to fix it i had to remove the rightBarButtonItem in deinit:
```
deinit {
        self.navigationItem.rightBarButtonItem = nil
    }
```

**Comment by kzaher** [comment]
Hi @Arnoymous ,

please fill in issue template, can't understand what are you reporting exactly.

**Comment by Arnoymous** [comment]
In fact it's a iOS bug, not RxSwift sorry.
UIBarButtonItem dont deinit when the NavController deinit and the barButtonItem is set on its rootController
