### ISSUE TITLE
How to trigger and cancel network request

### ISSUE THREAD

**Issue by onmyway133** [ReactiveX/RxSwift#1233]
Hi, I think this is a common problem. In ViewController, we usually do network request in `viewWillAppear` and cancel it in `viewWillDisappear`, but I want the whole sequence to start again in `viewWillAppear`, continue like that until `ViewController` is dismissed What should be the `rx` way of doing it?

I tried

```swift
rx.viewWillAppear
      .takeUntil(rx.viewWillDisappear)
      .retry()
      .bindTo(viewModel.input.fetch)
      .disposed(by: bag)
```

but it does not work, the sequence is stopped at the first `viewWillDisappear` and never `retry` again. My idea is to start and stop a sequence based on some events (in this case view appearance), and retry it again

**Comment by tottakai** [comment]
Hi,

we just have have another disposeBag, which is named after the lifecycle method, f.ex. `viewWillAppearDisposeBag`. In the `viewWillDisappear`, we just reassign a new DisposeBag instance to `viewWillAppearDisposeBag`, which will dispose everything in that bag.

**Comment by kzaher** [comment]
Like @tottakai suggested,

I would just use a `disposeBag` and assign new instance on `viewWillDisappear ` which will clear all subscriptions.
