### ISSUE TITLE
Error: Build failed in latest pod version

### ISSUE THREAD

**Issue by Nik20112** [ReactiveX/RxSwift#1239]
**Short description of the issue**:
I have Xcode 8.3.2 and installed latest version of RxSwift but facing the build error issue like below:
'Use of undeclared type of RecursiveLock'
'SubscribeSafe' is inaccessible due to file private protection level
Build error issue in Lock, Amb and AddRef.swift file
> pod 'RxSwift'
**Expected outcome**:
Build Succeed
Why this build error occurred even I updated the all latest version of Xcode and RxSwift Pod?

**What actually happens**:
Don't know the issue when just build and error occurred.

**Self contained code example that reproduces the issue**:

```swift 
//Lock.Swift file
  protocol Lock {
    func lock()
    func unlock()
}

// https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20151214/000321.html
typealias SpinLock = RecursiveLock

extension RecursiveLock : Lock {
    @inline(__always)
    final func performLocked(_ action: () -> Void) {
        lock(); defer { unlock() }
        action()
    }

    @inline(__always)
    final func calculateLocked<T>(_ action: () -> T) -> T {
        lock(); defer { unlock() }
        return action()
    }

    @inline(__always)
    final func calculateLockedOrFail<T>(_ action: () throws -> T) throws -> T {
        lock(); defer { unlock() }
        let result = try action()
        return result
    }
}
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.4.1 latest one

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
Xcode version 8.3.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting

**Comment by kzaher** [comment]
Hi @Nik20112 ,

Sincerely I have no idea :)

<img width="1005" alt="screen shot 2017-05-06 at 17 40 20" src="https://cloud.githubusercontent.com/assets/1641148/25773735/2e0dbcbe-3283-11e7-9518-d32e46ad0647.png">

The file in question is a symbolic link to `../../Platform/RecursiveLock.swift` because we are reusing some files internally in different libraries.

I would suggest running `git clone https://github.com/ReactiveX/RxSwift.git` and trying to run unit tests for `RxSwift-iOS` target.

Maybe that will give you some hints.

**Comment by Nik20112** [comment]
Hi,
Thanks. So there is no way to resolve this in latest version of pod. How can we use this in my project [git clone https://github.com/ReactiveX/RxSwift.git](url)?

**Comment by kzaher** [comment]
> So there is no way to resolve this in latest version of pod.

I'm trying to figure out what is wrong with your setup. CocoaPods integration works in general.
If you provide me with the info I've requested we've might figure out what is wrong :)

If you don't provide it, then yes, there is nothing I can do here.
