### ISSUE TITLE
Weird behavior of startWith().shareReplay(1)

### ISSUE THREAD

**Issue by devxoul** [ReactiveX/RxSwift#1241]
**Short description of the issue**:

The behavior of the code below is different from RxJS. Is this intended or a bug? 🤔

JSFiddle: https://jsfiddle.net/devxoul/f0kj9sc2/5/

**Expected outcome**:

```
state1 -> ...
state2 -> subscribed
state2 -> Event next(2)
state2 -> isDisposed
```

**What actually happens**:

```
state1 -> ...
state2 -> subscribed
state2 -> Event next(2)
state2 -> Event next(0) // I don't want this value
state2 -> isDisposed
```

**Self contained code example that reproduces the issue**:

```swift
let action = PublishSubject<Void>()
let state = action
  .scan(0) { state, _ in state + 1 } // +1 when action emits value
  .startWith(0)
  .shareReplay(1)

// state1
let disposable1 = state.debug("state1").subscribe()
action.onNext() // state: 1
action.onNext() // state: 2
disposable1.dispose()

// state2
state.debug("state2").subscribe().dispose()
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

commit 102424379fb8d6c69b33b95c67504679042f44cc from `master`

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 8.3.2 (8E2002)
```

**Comment by kzaher** [comment]
Hi @devxoul ,

As far as I can tell, they are behaving the same. I think you've forgot to dispose the subscription in RxJs.

https://jsfiddle.net/8bf4mkec/1/

```
2017-05-07 20:04:42.099: state1 -> subscribed
2017-05-07 20:04:42.100: state1 -> Event next(0)
2017-05-07 20:04:42.102: state1 -> Event next(1)
2017-05-07 20:04:42.103: state1 -> Event next(2)
2017-05-07 20:04:42.104: state1 -> isDisposed
2017-05-07 20:04:42.104: state2 -> subscribed
2017-05-07 20:04:42.104: state2 -> Event next(2)
2017-05-07 20:04:42.104: state2 -> Event next(0)
2017-05-07 20:04:42.104: state2 -> isDisposed
```

```
state1 -> Event next(0)
state1 -> Event next(1)
state1 -> Event next(2)
state2 -> Event next(2)
state2 -> Event next(0)
```

**Comment by devxoul** [comment]
@kzaher, 😱 Thanks for pointing it out!
