### ISSUE TITLE
Using RxSwift, RxCocoa, RxDataSource as my framework pod dependency, Creating issue.

### ISSUE THREAD

**Issue by Bala-iOS** [ReactiveX/RxSwift#1243]
## Adding RxSwift as dependency in PodSpec not worked
 Am created a FrameWork in Swift 3 and I used RxSwift, RxCocoa, RxDataSource for that. Now am created podespec for my FrameWork and added RxSwift, RxCocoa, RxDataSource as a dependency.

  _When I drag and drop manually all are working fine_

If I try to integrate my FrameWork using Pod its Integrated and Builded properly. And first Screen of my framework worked fine. Whenever RxSwift or RxDataSource code Executed its throw Signal SIGABRT error. And Sometime its throw the [this](https://github.com/ReactiveX/RxSwift/issues/675) issue. I also tried with giving my `tableView.dataSource = nil` and `tableView.dataSource = nil` before `bindTo` or use `rx_setDataSource`, But it won't work 

**This is my PodSpec code**:

`Pod::Spec.new do |s|
s.name             = "MySDK"
s.version          = "0.1.0"
s.summary          = "My framework Summary"
s.license          = { :type => "MIT", :text=> <<-LICENSE
MIT License
}
s.homepage         = "https://www.mysdk.com/home"
s.author           = { “Me” => “me@me.com” }
s.source           = { :git => "https://git.com/mysdk.git", :tag => s.version }
s.platform         = :ios, '9.0'
s.requires_arc     = true

s.source_files     = "iOS/**/*.{swift}"
s.public_header_files = "iOS/MySDK.framework/Headers/MySDK-Swift.h,native/MySDK.framework/Headers/MySDK.h"
s.preserve_paths   = "iOS/MySDK.framework"
s.vendored_frameworks = "iOS/MySDK.framework"

s.frameworks       = 'UIKit'
s.dependency 'RxSwift',    '3.0'
s.dependency 'RxCocoa',    '3.0'
s.dependency 'RxDataSources', '1.0'
end`

**RxSwift/RxCocoa/Rx`Blocking/RxTest version/commit**

  _Latest Version_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
  8.3.2
```

**Comment by kzaher** [comment]
Hi @Bala-iOS ,

Did you try creating an empty test project with 

```
# Podfile
use_frameworks!

target 'YOUR_TARGET_NAME' do
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'YOUR_TESTING_TARGET' do
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end
```

and check does it work then?

**Comment by Bala-iOS** [comment]
@kzaher 

I tried your method by:

Mentioned the below code in my `Podspec` dependency
`s.dependency 'RxSwift', '~> 3.0'
s.dependency 'RxCocoa', '~> 3.0'
s.dependency 'RxDataSources', '~> 1.0'`

And added the below code in my test project `Podfile`
`target 'DemoFrameWorkTests' do
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end`

But it won't fix. The same problem occurred. 

If I manually drag and drop `RxSwift, RxCocoa, RxDataSource` its working fine. But, when I go with `Podspec` it not working

I have attached the error screen shot below.
<img width="881" alt="screen shot 2017-05-10 at 11 42 24 am" src="https://cloud.githubusercontent.com/assets/25056948/25885545/a30baa9e-3576-11e7-90fd-c89dc5965d69.png">

**Comment by kzaher** [comment]
Hi @Bala-iOS ,

Have you tried this on an empty project? If so, can you upload that empty project zip that doesn't work?

**Comment by Bala-iOS** [comment]
Please find the test project attachment below.

[DemoFrameWork.zip](https://github.com/ReactiveX/RxSwift/files/989880/DemoFrameWork.zip)

**Comment by Bala-iOS** [comment]
@kzaher 
Any update ...

**Comment by Bala-iOS** [comment]
Hi @kzaher ,

Am try to fix this, unfortunately the same issue repeated every time. Am looking for your valuable Comment. Kindly do the needful help.

Thanks.

**Comment by kzaher** [comment]
Hi @Bala-iOS ,

this is not an RxSwift issue as far as I can tell.

<img width="1178" alt="screen shot 2017-05-15 at 22 21 52" src="https://cloud.githubusercontent.com/assets/1641148/26062283/fb9e609e-39bc-11e7-94be-56c322fe24c5.png">

Xcode Version 8.3.2 (8E2002)

There is something wrong with your environment. I unfortunately can't produce it. Try deleting your derived data or reinstalling Xcode.

Sorry. Maybe somebody else can repro this and help you.

**Comment by ccaceres-watchman** [comment]
Did you find a solution for this problem?
