### ISSUE TITLE
Command failed due to signal: Abort trap 6

### ISSUE THREAD

**Issue by anmolmalhotra** [ReactiveX/RxSwift#1244]
:warning: Constantly getting the above error on my Xcode on installing RxSwift through CocoaPods. :warning: 

Steps:
1) Created Project and initiated Pods.
2) Added RxSwift and RxCocoa through PodFile and pod install.
3) Opens RxSwift.xcworkspace; imports RxSwift and RxCocoa and rebuilds the project.
4) This error comes. No way to remove this. Spinning my head since 4 hrs on Google.

**Short description of the issue**:

  Swift Compiler Error on importing RsSwift.

**Expected outcome**:

  No compiler error and I want to learn RsSwift so badly but this thing is not letting me doing that.

**What actually happens**:

  Command failed due to signal: Abort trap 6

**Self contained code example that reproduces the issue**:

```swift
  import UIKit
  import RxCocoa
  import RxSwift

  class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()  
    }
 }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.2.0

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
  8.3.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting

**Comment by kzaher** [comment]
Hi @anmolmalhotra ,

Did you try creating an empty test project with 

```
# Podfile
use_frameworks!

target 'YOUR_TARGET_NAME' do
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'YOUR_TESTING_TARGET' do
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end
```

and check does it work then?

**Comment by anmolmalhotra** [comment]
Thanks for the reply @kzaher. Yes I have tried creating new project 3 times with the same lines you wrote above already and it is not working.
@dpaschich on Slack suggested me that 3.2.0 is not going to work on Xcode 8.3 and above. So I just now tried running pod update to update to version 3.4.1 and see if this will work.

You guys should install 3.4.1 by default I think. I just wasted 3-4 hrs. :(

**Comment by kzaher** [comment]
Hi @anmolmalhotra ,

I'm not sure I understand your situation. The pod file I've pasted from README.md with installation instructions 

```
# Podfile
use_frameworks!

target 'YOUR_TARGET_NAME' do
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'YOUR_TESTING_TARGET' do
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end
```

... should install 3.4.1 version.

**Comment by anmolmalhotra** [comment]
Updated to 3.4.1 and I am still getting that error. Don't know whats wrong.
<img width="1019" alt="screen shot 2017-05-09 at 11 42 29 pm" src="https://cloud.githubusercontent.com/assets/16324934/25865675/47c5ef9c-3511-11e7-91c6-384845c0505c.png">

**Comment by kzaher** [comment]
I would suggest cleaning Xcode derived data.

**Comment by anmolmalhotra** [comment]
Trying

**Comment by anmolmalhotra** [comment]
Tried. Still getting the same error. ☹️

**Comment by anmolmalhotra** [comment]
Now getting this. Whole project code has gone white and showing this on top.
<img width="779" alt="screen shot 2017-05-09 at 11 55 18 pm" src="https://cloud.githubusercontent.com/assets/16324934/25866138/0fb8878e-3513-11e7-936d-8f05b6ae3b08.png">

**Comment by anmolmalhotra** [comment]
@kzaher found the bug. It was not building because the library name and my project name were clashing. Both were same. Tried with another name and it worked. Don't know if this really creates the issue. Weird. Thanks for your help though! :) Happy coding!

**Comment by wbxiaowangzi** [comment]
@anmolmalhotra  What is your specific name repetition?Is the class name repetition inside the garage?I also met the same problem, I quote three libraries have a same class called manager. The swift is the reason?
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/12706376/27780142-de2952d6-5ff9-11e7-8ba9-a6dc5f3b853c.png">
