### ISSUE TITLE
Value of type 'Variable<classname>' has no member 'next'

### ISSUE THREAD

**Issue by FangYiXiong** [ReactiveX/RxSwift#125]
I got a lot of this error when migrating my RxSwift related code from 1.x to swift 2.0.
```
Value of type 'Variable<classname>' has no member 'next'
```
I read the document [Migration from RxSwift 1.9 to RxSwift 2.0 version](https://github.com/ReactiveX/RxSwift/blob/rxswift-2.0/Documentation/Migration.md). Didn't see anything about this 'next' function name change info. Did I miss something?

**Comment by kzaher** [comment]
Hi @FangYiXiong , it's now `sendNext`. We didn't write all changes, just the most notable ones.

Hope this helps.

**Comment by bontoJR** [comment]
This problem seems to be solved, I can close this :)
