### ISSUE TITLE
SharedSequence should have an ObserveOn Scheduler and a SubscribeOn Scheduler

### ISSUE THREAD

**Issue by brentleyjones** [ReactiveX/RxSwift#1252]
**Short description of the issue**:

`Driver` (because of `SharedSequence`) uses the same scheduler for subscription and for observing, when it should use different ones for each.

Take the following statement:

```swift
Driver.just("View Controller Title").drive(navigationItem.rx.title).addDisposable(to: disposeBag)
```

**Expected outcome**:

The `navigationItem.title` should be set immediately, regardless if there are events queued in `MainScheduler.instance` (i.e. it should use `ConcurrentMainScheduler.instance` for subscription).

**What actually happens**:

If there are events queued in `MainScheduler.instance`, then the above won't set the `navigationItem.title` during the same run loop. This can cause issues with display, since in this example it will mean when the view controller is pushed on a navigation controller the title won't appear until the animation is complete.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 3.4.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by brentleyjones** [comment]
I have a patch that provides this functionality, if you want me to open a PR.

**Comment by TheAdamBorek** [comment]
Hey @brentleyjones,
yesterday we were talking about this issue with @kzaher on RxSwift's slack and we have a solution. Today I want to create a PR with the fix ;)

**Comment by kzaher** [comment]
We've done some changes to the way we are ensuring delivering events on the main scheduler and it seems they work pretty good for now. I'm not sure I see any advantage of us adding this for now.

If we find some advantage of adding this, we can reopen this issue.
