### ISSUE TITLE
Use correct Semantic Versioning

### ISSUE THREAD

**Issue by orta** [ReactiveX/RxSwift#126]
A [SemVer version](http://semver.org) should always include a patch so [2.0-alpha1](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift.podspec#L3) isn't strictly compliant.

**Comment by kzaher** [comment]
Hi, so if I now do 2.0.0-alpha.2 for next release, do we expect some issues?

**Comment by orta** [comment]
We added support for dealing with those kinds of transitions in 0.38.2 https://github.com/CocoaPods/Core/commit/74f8fdcfd840a332fa8aee46112e26ea6a6090c8 - so yes, mostly, for people who have updated their CP. The website will definitely deal with it.

**Comment by kzaher** [comment]
That will be dealt in 2.0.0-alpha.2 together with more proper inline documentation :)

**Comment by kzaher** [comment]
This should be done :)
