### ISSUE TITLE
framework not found RxCocoa for architecture x86_64 in Xcode8.3.2

### ISSUE THREAD

**Issue by longshihua** [ReactiveX/RxSwift#1263]
**Short description of the issue**:

I upgrade my Xcode to 8.3.2. I run my app which works well. When I run my unit test. I got the error "framework not found RxCocoa for architecture x86_64"

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NewAPP' do
    pod 'Alamofire',  '~> 4.4'
    pod 'SnapKit',    '~> 3.2.0'
    pod 'SwiftyJSON'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxOptional'
    pod 'Moya/RxSwift'
    pod 'Moya-ModelMapper/RxSwift', '~> 4.1.0'
    pod 'Then', '~> 2.1'
    pod 'RxDataSources', '~> 1.0'
    pod 'ObjectMapper'
    pod 'RxAlamofire/RxCocoa'
end

target 'NewAPPTests' do
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end

**Platform/Environment**

  iOS

**Xcode version**:

```
  Xcode 8.3.2
```

**Installation method**:
 CocoaPods

**I have multiple versions of Xcode installed**:
 no

**Comment by kzaher** [comment]
Hi @longshihua ,

This is what I get when I try to use your Podfile.

```
[05/20 15:35:51]  kzaher  Krunoslavs-MacBook-Pro  ~  Projects  RxIntegrations  Share  NewAPP  master  26✔  2✎  ❓  $  pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Moya-ModelMapper/RxSwift (> 4.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Moya-ModelMapper/RxSwift (> 4.1.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

You were also missing 
```
pod 'RxSwift', '> 3.0'
pod 'RxCocoa', '> 3.0'
```

inside `target 'NewAPPTests' do`

This is the Podfile that works for me.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NewAPP' do
    pod 'Alamofire', '> 4.4'
    pod 'SwiftyJSON'
    pod 'RxSwift', '> 3.0'
    pod 'RxCocoa', '> 3.0'
    pod 'RxOptional'
    pod 'Moya/RxSwift'
    pod 'Then', '> 2.1'
    pod 'RxDataSources', '~> 1.0'
    pod 'ObjectMapper'
    pod 'RxAlamofire/RxCocoa'
end

target 'NewAPPTests' do
    pod 'RxSwift', '> 3.0'
    pod 'RxCocoa', '> 3.0'
    pod 'RxBlocking', '> 3.0'
    pod 'RxTest', '> 3.0'
end
```

This doesn't look like RxSwift issue to me.
