### ISSUE TITLE
Create my own operators

### ISSUE THREAD

**Issue by gorozco58** [ReactiveX/RxSwift#1267]
**Short description of the issue**:

Hello guys I am trying to create a new operator this is pretty easy I just want to ignore nil elements in a sequence then I have something like this:

**What actually happens**:

```swift
import Foundation
import RxSwift

public protocol OptionalType {
    associatedtype Wrapped
    var optional: Wrapped? { get }
}

extension Optional: OptionalType {
    public var optional: Wrapped? { return self }
}

public extension ObservableType where E: OptionalType {
    public func ignoreNil() -> Observable<E.Wrapped> {
        return flatMap { value in
            value.optional.map { .just($0) } ?? Observable<E.Wrapped>.empty()
        }
    }
}
```
**Expected outcome**:

but I was looking for RxSwift operators implementation and I noticed that you use `Producer` class to do the implementation. I want to do something similar to you but I can't use that class because it doesn't have `public` accessor.  So can't I use the producer class in order to do my own implementation ?

```swift
class Producer<Element> : Observable<Element>
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift version 3.4.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @gorozco58 ,

You can just use `Observable.create`. You don't need `Producer`.
https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#custom-operators

**Comment by gorozco58** [comment]
thank you so much @kzaher

**Comment by groue** [comment]
I came to this issue after looking for a way to define a *custom observable type*, with specific operators. It is because of those custom operators that the type-erased `Observable` isn't a good fit.

I agree this is not exactly the topic of this issue. However, should anyone else wonder how to deal with the fact that `Producer` is not public, as I did, and stumble upon this issue, here is a technique inspired by @kzaher's answer above.

1. Define your custom observable as `ObservableType`

    This allows your observable to be used just like all other observables.

2. Implement `asObservable()` with `Observable.create`

    Implementing this method avoids the default implementation which would create yet another `Observable` instance.

    Using `Observable.create` is just the vetted way to create an observable.

3. Freely add your custom operators

    This was the main goal, after all :-)

With such a setup, RxSwift is able to perform all its regular and subtle concurrency checks, and I believe this gives an observable which is a good citizen.

Sample code:

```swift
struct MyObservable: ObservableType { // A class is ok as well
    typealias Element = ...
    
    func subscribe<Observer>(_ observer: Observer) -> Disposable
        where Observer: ObserverType, Self.Element == Observer.Element
    {
        asObservable().subscribe(observer)
    }
    
    func asObservable() -> Observable<Element> {
        Observable.create { ... }
    }
    
    func myOperator(...) -> Self {
        ...
    }
}
```
