### ISSUE TITLE
Feature Request: Wrapper of ReplaySubject like Variable

### ISSUE THREAD

**Issue by tarunon** [ReactiveX/RxSwift#1268]
I need `ReplaySubject` wrapper like `Variable`. I felt we need this wrapper because `Variable` is required initial value.

## Motivation
- `Variable<E?>` is not good way to avoid set initial value. `Variable<E?>` publish `nil` first, we need filter it and maybe it's a little bit annoying. And somebody can set `nil` again, but we need `nil` only when initialize `Variable`. In my opinion, it's better that if compiler prevent set `nil` again.
- `ReplaySubject<E>` is better, but I hope to get more useful features like a `Variable`. 
- It will be helpful when we make `UIView` or `UIViewController` subclass using Nib/Storyboard.

I am using this feature on our code base, and we name it `LazyVariable`.

**Comment by sergdort** [comment]
To be honest I'm don't like that `Variable` is in the main repo at all :)
I've seen so many times people abuse it :) 
Also there are several ways to ensure you have latest value on subscription by using `Driver`, `shareReplay`, `withLatestFrom` ...

So I would not want these feature to in the main repo :)

**Comment by kzaher** [comment]
Hi guys,

yeah, I agree with @sergdort , if it's not core functionality, not a declarative concept, not consistent with other rx implementations and can be easily accomplished by using public interface, it's probably not a good idea to include it in this repo.

Sorry @tarunon . We have already too much code to maintain :)

**Comment by kzaher** [comment]
@tarunon I think that with time we will probably move it somewhere else. 

Right now moving it would probably cause too much confusion, and we have a lot of things to polish. 

I'm also hoping that with time there will maybe exist some cross library concept equivalent to BehaviorSubject but with far less exotic name.

And Swift 4.0 is coming :)

**Comment by tarunon** [comment]
@kzaher Sure! Thank you explaining ~
