### ISSUE TITLE
[RFC] Rx Debugging Tool

### ISSUE THREAD

**Issue by jeremiegirault** [ReactiveX/RxSwift#1274]
**Rationale**

I have been thinking about debugging Reactive Streams for a long time.
When I started Reactive development I had a lot of troubles debugging through the stacktrace. Indeed a stack trace is a "spatial" snapshot of the current state of the code. It does not capture values over time. It does not capture Observable stream structure through operators. Debugging through streams with current tools, actually designed to inspect the state of an app, is a pain. 
However I have the conviction that it is possible to capture the content of data over time and the structure of the streams and display / replay them to find bugs or issues.

**Proposition**

Functional streams have a great intrinsic property: they have an equivalent visual language. Visual languages a great for us to understand how things behave.
I stole 2 illustrations on google image to illustrate it :
![img1](https://cloud.githubusercontent.com/assets/1162682/26531492/78ea1fd4-43ea-11e7-95a8-280f81e1a896.png)
![img2](https://cloud.githubusercontent.com/assets/1162682/26531493/7b5df060-43ea-11e7-9277-e479dd9962af.png)
sources: https://imve.informatik.uni-hamburg.de/projects/VisualAFRP / https://lavag.org/topic/17804-functional-dataflow-programming-with-labview/

This visual language can represent the abstract structure of an Observable composed of combined operators. 
If the Observable is hot, or when a cold Observable is subscribed it "instantiates" a graph of this kind which can be represented visually. 
- Every node in the graph is an "instance" of a subscription with it's operator name.
- Values could be displayed moving over time in the edges/links of the graph with a smart enough algorithm.

Through instrumentation of a pseudo-rx framework I managed to extract the data needed to be displayed in such a debugging tool. Therefore I think it's possible to build such a tool using a combination of
- client (rx library) instrumentation
- a debugging server (I used node) to rebuild the graph state over time.
- a debugging client (I made a small d3 web client) to display and allow interaction with the graph.

A simple slider would allow to replay all values over time in a very fine granularity (instrumentation queue ordering granularity actually).
This basic feature would allow to visualize streams and data and also potential memory leaks. (non-disposed subscriptions would stay on screen over time)

About more advanced features it would be possible and great to :
- search and find values in time: first / last / next / previous occurrence
- name streams and/or operators and filter visually or by name
- drill-down inside custom operators up to "native" operators 
- export/imports reports to replay
- inject stream data from debugging server inside client via the socket and client instrumentation. (it would be great when sharing replays and/or testing values inside streams) 
- programatically analyze reports to find bugs (I'm sure we can find some patterns of errors and I ran some streams data through machine learning in the past and it allowed me to find issues in my code)

**Expected help**

- Feedback, confrontations of ideas (is this pain of debugging share by other RxSwifters?)
- Features the tool should / could have
- UI/UX of the tool (I have a vision about how some features can look like but opinions are welcome)
- Architecture / Design of the tool
- Support of RxSwift community / People interested to work on this side-project with me

It's a complicated topic and I don't have a lot of time but the most important thing to not give up on this project for me would be to have some follow-up with the community.

**Work done**

I could only dedicate a few hours of spare time to this side-project but managed to do this :

- Hacking a solution to extract relevant data through instrumentation : https://github.com/jeremiegirault/RxGraph ⚠️ ugly code ⚠️ 
- Demo gif of what I managed to do for the following code :
```
func test() {
    let x = Observable<Int>.of(1,2,3).map { 3*$0 }
        .flatMap { (val: Int) -> Observable<String> in
        if val % 2 == 0 { return .of("even") }
        else { return .of("odd") }
    }
    x.test("abc")
    print("\(ProcessingGraph.shared.describe())")
}

test()

print("---")
print("\(ProcessingGraph.shared.describe())")
```
![rxvisu](https://cloud.githubusercontent.com/assets/1162682/26531423/250efd5e-43e9-11e7-840c-b7c754749609.gif)

**Comment by kzaher** [comment]
Hi @jeremiegirault ,

this is an interesting experiment :)

I've checked your implementation, and it seems that you are passing some additional metadata through sink chain.

I've talked about this with @fpillet , he had some similar ideas. Maybe you can investigate this when you find time.

It's not clear to me how this could be adapted in the main repo without a lot of changes. 

If there is a small set of changes we can do to support this, that is something we can consider, but it's not clear to me what those changes would be.

**Comment by jeremiegirault** [comment]
Actually IIRC, in my (functional) implementation I only need to pass metadata through `flatMap` which is the core operation on `Observable`. Others operators could be derived from this one.

In RxSwift implementation I'm not sure but I think that each "base" operator have a kind of "own" framework-internal sink. This would be the way the metadata would go through. I would need more information to know if there is a generic "sink" part where the metadata could be passed without touching all operators custom sink. This would allow an easier implementation.

Anyone here knowing more about RxSwift sinks up to help me about how to instrument the framework ? :)

**Comment by kzaher** [comment]
Hi @jeremiegirault ,

I don't think we unfortunately have some generic way to pass metadata except by using reflection.
As far as I can tell that's the only way to implement something like this.

**Comment by kzaher** [comment]
I guess this looks a bit stale and we already have a bunch of other work.

Right now we don't have anything library level that would help with more easier debugging. I'll try to think about how can we improve status quo while I'll be investigating changes for RxSwift 4.0 version.

**Comment by luolong** [comment]
There is an existing project called [RxFiddle] (on [Github]) that tries to present a higher level visualisation on top of of some instrumentation. The prototype seems to be working reasonably well on TypeScript/ECMAScript target platform and there are initiatives for making it work on Java using compile time code generation. It would be awesome to be able to debug and visualize RxSwift streams as well with this tool...

[RxFiddle]: https://rxfiddle.net/
[Github]: https://github.com/hermanbanken/RxFiddle
