### ISSUE TITLE
Can not use RxSwift.Resources.total with Carthage

### ISSUE THREAD

**Issue by nahung89** [ReactiveX/RxSwift#1277]
**Short description of the issue**:
I'm using Carthage to manage 3rd libraries. For now, there is no way to run debug with `RxSwift.Resources.total`.

**Expected outcome**:
Use `RxSwift.Resources.total` normally

**What actually happens**:
in terminal: 
```
carthage build --configuration Debug (or)
carthage bootstrap RxSwift --configuration Debug
*** Downloading RxSwift.framework binary at "David.1"
```
In XCode:
```
Error: Module 'RxSwift' has no member named 'Resources'
```

**Self contained code example that reproduces the issue**:

```swift
  _ = Observable<Int>.interval(1, scheduler: MainScheduler.instance)
            .subscribe(onNext: { _ in
                print("Resource count \(RxSwift.Resources.total)")
            })
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
N/A

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.3.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @nahung89 ,

`carthage update --no-use-binaries --configuration Debug RxSwift`

**Comment by tungfam** [comment]
Hi,

Do you know if it's possible to revert the command `carthage update --no-use-binaries --configuration Debug RxSwift`? If yes could you please kindly share how to do it?

Thank you!

**Comment by tungfam** [comment]
Hi,

Do you know if it's possible to revert the command: 
`carthage update --no-use-binaries --configuration Debug RxSwift` ? 

If yes could you please kindly share how to do it @kzaher ?

Thank you!
