### ISSUE TITLE
RxExample-iOS Project: Build Fail RandomUserAPI.swift -> Line 9 -> No Such Module RxSwift

### ISSUE THREAD

**Issue by mark-jTribe** [ReactiveX/RxSwift#128]
Fresh checkout, any ideas?  Using XCode 7 Beta 6

**Comment by mark-jTribe** [comment]
I'm a dummy, had to build RxExample-iOS-no-module by switching build scheme.  FYI for other people I guess :)

**Comment by mark-jTribe** [comment]
Actually I can build RxExample-iOS-no-module but not RxExample-iOS.  And when building no module I can't do anything in the simulator which of course makes sense because I assume it doesn't include the RxSwift module

**Comment by kzaher** [comment]
Hi @mark-jTribe,

I think the most probable problem is that you didn't open Rx.xcworkspace but example project itself.

Try opening Rx.xcworkspace and building from there.

Hope this helps.

**Comment by bontoJR** [comment]
No extra input about this, so I can consider this closed.

If someone is experiencing a similar problem (I had it today), please consider the following approach before reporting it here, it solved the problem for me: http://stackoverflow.com/a/26842602/253315
