### ISSUE TITLE
PublishSubject and Driver

### ISSUE THREAD

**Issue by onmyway133** [ReactiveX/RxSwift#1284]
Hi, I'm trying to merge 2 `PublishSubject` as `Driver`

```swift
let bag = DisposeBag()

let s1 = PublishSubject<Int>()
let s2 = PublishSubject<Int>()

let d1 = s1.asDriver(onErrorJustReturn: 0)
let d2 = s2.asDriver(onErrorJustReturn: 0)

let m = Driver.of(d1, d2).merge()

var results = [Int]()

// Need to trigger IMPORTANT  !!!!!!
d2.drive().addDisposableTo(bag)

m.drive(onNext: {
  results.append($0)
}).disposed(by: bag)

s1.onNext(11)
s2.onNext(21)
s1.onNext(12)
s2.onNext(22)

wait(for: 0.1)

XCTAssertEqual(results, [11, 21, 12, 22])
```

It works if I have the trigger 

```swift
d2.drive().addDisposableTo(bag)
```

But without it, `results` is just `[11, 12]`.  If I change the order in `merge` to `let m = Driver.of(d2, d1).merge()`, then I need to trigger `d1.drive().addDisposableTo(bag)`. It seems I always need to trigger the last `Driver` in `merge`

Why is that? I may miss something, please help

**Comment by onmyway133** [comment]
I just see on this https://github.com/ReactiveX/RxSwift/issues/579 that there is `Driver.merge()`, so it is better than `Driver.of().merge()`?

**Comment by gmoalvarez** [comment]
Please ask these types of questions on the RxSwift Slack channel
https://rxswift-slack.herokuapp.com
There are a lot great people over there helping each other out with RxSwift.

**Comment by kzaher** [comment]
This is more of a Slack channel question, and not issue with the project.

**Comment by onmyway133** [comment]
@gmoalvarez @kzaher Hi, I personally think that these are more about how to use the project. And the great thing is that it has more visibility, so that other people can search and get answers. On slack, you can answer 1 or 2 people, but you can't always do that if the next one ask the same question

Actually I asked many questions on that Slack channel, and no one answered me 😢

**Comment by sunshinejr** [comment]
Thank you!
Spark by Readdle
