### ISSUE TITLE
Subscription continues emitting elements after being disposed

### ISSUE THREAD

**Issue by rlaguilar** [ReactiveX/RxSwift#1285]
**Short description of the issue**:

I have a subscription to an observable that continues emitting elements after I cancel the subscription.

**Expected outcome**:

After I cancel the subscription the previous observable should stop emitting elements.

**What actually happens**:

The previous subscription still emits a few elements after it has been unsubscribed from. This issue happens from time to time.

**Self contained code example that reproduces the issue**:

Well, I can't provide a sample code here, but I can give a [link to a gist](https://gist.github.com/rlaguilar/ca6840d3ea85dad733d0901b18e1be20) containing the two source files involved in the bug.

The reported error occurs in the line 91 of the `MazeViewController.swift` file.

It should be valid to note that the view controller is never deallocated, neither does the `MazeView` instance, so retain cycles should not be a problem.

Anyway, if you want a full functional project with the issue, I can send the project to you privately, but I can't post it online.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 3.5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [x] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 8.3.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @rlaguilar ,

Could you please help us and provide us with something that is short, self contained, explains expected output and it's difference from current output?

**Comment by kzaher** [comment]
Feel free to reopen the issue once you make those changes.
