### ISSUE TITLE
Please tell me what's wrong with my code?

### ISSUE THREAD

**Issue by dander521** [ReactiveX/RxSwift#1292]
![dingtalk20170614112622](https://user-images.githubusercontent.com/15241138/27114229-b2ce3f16-50f4-11e7-860f-ede0ef4d444a.png)

**Comment by dander521** [comment]
I 
![dingtalk20170614113006](https://user-images.githubusercontent.com/15241138/27114247-d7a5806a-50f4-11e7-9fad-6d3e7c57cc61.png)

I have a model like this , when i user it in viewController , i meet that problem,

**Comment by DianQK** [comment]
change to `usernameTF.rx.text.orEmpty.asDriver()`.

it look like `usernameTF.rx.text.orEmpty` is `Driver<String?>`

**Comment by dander521** [comment]
It does not work  ~O~

**Comment by sergdort** [comment]
Hi, @dander521 
Did you change both `userNameTF` and `passwordTF` as @DianQK suggested?

**Comment by dander521** [comment]
of course I change both userNameTF and passwordTF with orEmpty

**Comment by gmoalvarez** [comment]
I think this question would be more appropriate in the RxSwift Slack channel.
https://rxswift-slack.herokuapp.com

There is an active group of people helping each other out over there.

**Comment by kzaher** [comment]
I'm hoping nice people in Slack will be able to help you, this doesn't look like an issue with project itself.

**Comment by dander521** [comment]
how to join Slack ,can u invite me to join it? thank u
