### ISSUE TITLE
RxSwift framework imports UIKit.

### ISSUE THREAD

**Issue by r-mckay** [ReactiveX/RxSwift#1298]
Hello,

I'm creating this issue not knowing if it is a truly one or if the behaviour I'll describe is intended. But it's definitely a question that I wanted to ask.

The context is this one: I have a project following the MVVM pattern. I'd like to have ViewModels that do not depend on UIKit, because they need to be View-independant. 
However, when importing RxSwift in them, I noticed that UIKit was imported as well: RxSwift apparently imports UIKit.
I use CocoaPods and its frameworks.
I took a deeper look at the RxSwift source code and didn't find occurrences of UIKit. I wanted to ask you if this import was intended and if yes why. If it's not, I'd be glad to help.

Thank you very much for your answers!

**Short description of the issue**:

RxSwift imports UIKit.

**Expected outcome**:

To not import UIKit.

**What actually happens**:

 UIKit is imported with RxSwift.

**Self contained code example that reproduces the issue**:

```swift
import RxSwift
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 3.5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is it to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.3
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @r-mckay ,

RxSwift doesn't depend on UIKit.

> I took a deeper look at the RxSwift source code and didn't find occurrences of UIKit. I wanted to ask you if this import was intended and if yes why. If it's not, I'd be glad to help.

If you can help, that would be great.

**Comment by r-mckay** [comment]
Hi @kzaher,

> If you can help, that would be great.

Yes sure, I'd be glad to. I'll open a PR as soon as I have something. Thank you.

**Comment by kzaher** [comment]
@r-mckay looks like you've discovered this is CocoaPods issue. Closing this here then.

**Comment by r-mckay** [comment]
Hello @kzaher,
yes it seems so, thank you for closing this.
