### ISSUE TITLE
filename same name.

### ISSUE THREAD

**Issue by Jinxiansen** [ReactiveX/RxSwift#1301]
Each time you use the **pod update**, the screenshot will appear, the file name is repeated.

Podfile content : 
```
 pod 'RxSwift', '~> 3.0'
 pod 'RxCocoa', '~> 3.0'
```

<img width="841" alt="12" src="https://user-images.githubusercontent.com/16829428/27268527-b3067f56-54e2-11e7-9d2b-0692aa87e9d8.png">
<img width="1073" alt="s3" src="https://user-images.githubusercontent.com/16829428/27268545-ceea3d34-54e2-11e7-8dda-b7b925e4de9e.png">

**Comment by kzaher** [comment]
Hi @Jinxiansen ,

it seems to me that it should work. Here is a project where it works for me.

[CocoaPodiOS.zip](https://github.com/ReactiveX/RxSwift/files/1084241/CocoaPodiOS.zip)

```
cocoapods 1.2.1
```

**Comment by Jinxiansen** [comment]
@kzaher  Does not appear to be written in Swift, the latest version ? 🙂
<img width="862" alt="3" src="https://user-images.githubusercontent.com/16829428/27275729-567d2d88-550b-11e7-9f2b-6ffca997cdce.png">

**Comment by Jinxiansen** [comment]
<img width="456" alt="4" src="https://user-images.githubusercontent.com/16829428/27275850-c4bd1c86-550b-11e7-8f4f-630e37f84ba1.png">

**This is my Swift version information.**

**Comment by Jinxiansen** [comment]
When i commented out
 ```
pod 'RxSwift', '~> 3.0'
pod 'RxCocoa', '~> 3.0'
```, 
the use of **pod update**, and then cancel the note, the use of **pod update**, this time will not appear above the same name and other errors can be used in the project, but at this time, when I Add other libraries through the pod, and then use **pod update**, it will prompt filename / same name and other errors.

Why is this ？

**Comment by kzaher** [comment]
Hi @Jinxiansen ,

I don't understand. Does the project I've sent work for you?

When you create an empty project and use the Podfile I've sent, does it work for you?

What CocoaPods version are you using?

If it works with that minimal pod file for you, and doesn't for some other pod why do you think this is a bug with RxSwift and not CocoaPods?

> the use of pod update, and then cancel the note, the use of pod update, this time will not appear above the same name and other errors can be used in the project, but at this time, when I Add other libraries through the pod, and then use pod update, it will prompt filename / same name and other errors.

This doesn't provide me with anything useful I can investigate.
