### ISSUE TITLE
RxSwift+Moya,refresh failed?

### ISSUE THREAD

**Issue by longshihua** [ReactiveX/RxSwift#1304]
**Short description of the issue**:

I'm newer to RxSwift. I want to refresh the tableview to show new data.The first request that I can get the data. but when I pull down the tableview, the request didn't finished. I have no ideas about this? 

**Expected outcome**:

I can refresh my tableview

**What actually happens**:

 when I pull down the tableview, the request didn't finished

**Self contained code example that reproduces the issue**:

```swift
 
class RecommendViewController: UIViewController {
    
    lazy var tableView = DefaultManager.createTableView(HomeImageCell.self, 
                                                        HomeImageCell.idenfitier)
    let disposeBag = DisposeBag()
    lazy var viewModel = HomeViewModel()
    lazy var dataSource: [HomeListDetailModel] = []

    override func viewDidLoad() {
        super.viewDidLoad()
        viewModel.fetchRecommendList("answer_feed",0)
        setupTableView()
        configureRefresh()
        bindDataToTableView()
    }
        
    func setupTableView() {
        view.addSubview(tableView)
        tableView.snp.makeConstraints { (make) in
            make.edges.equalTo(0)
        }
        tableView.estimatedHeight(200)
    }
    
    func bindDataToTableView() {
        viewModel.recommend
            .observeOn(MainScheduler.instance)
            .do(onNext: { [unowned self] model in
                print("endAllRefresh")
                self.endAllRefresh()
            }, onError: { (error) in
                self.endAllRefresh()
                print("error = \(error)")
            })
            .map { [unowned self] model in
                return self.handleData(model)
            }.bind(to: tableView.rx.items(cellIdentifier: HomeImageCell.idenfitier , cellType: HomeImageCell.self )) { index, model, cell in
                cell.updateCell(data: model)
            }.disposed(by: disposeBag)
    }
    
    func configureRefresh() {
        tableView.mj_header = MJRefreshNormalHeader(refreshingBlock: { [unowned self] in
            let model = self.dataSource[0]
            self.viewModel.fetchRecommendList("answer_feed",model.behot_time)
         
        })
        tableView.mj_footer = MJRefreshAutoNormalFooter(refreshingBlock: { [unowned self] in
            let model = self.dataSource[self.dataSource.count - 1]
            self.viewModel.fetchRecommendList("answer_feed",model.behot_time)
        })
    }
    
    func endAllRefresh() {
        self.tableView.mj_header.endRefreshing()
        self.tableView.mj_footer.endRefreshing()
    }
    
    func handleData(_ model: HomeListModel) -> [HomeListDetailModel] {
        guard let data = model.detailData else {
            return dataSource
        }
        self.dataSource = data
        return data
    }

}

My ViewModel

protocol HomeProtocol {
    func fetchRecommendList(_ category: String, _ behot_time: Int) 
}

class HomeViewModel: HomeProtocol  {
    lazy var provider = HTTPServiceProvider.shared
    var recommend: Observable<HomeListModel>!

    init() {}

    init(_ provider: RxMoyaProvider<MultiTarget>) {
       self.provider = provider
    }

    func fetchRecommendList(_ category: String, _ behot_time: Int) {
        recommend = provider.request(MultiTarget(HomeAPI.homeList(category: category,behot_time: behot_time)))
        .debug()
        .mapObject(HomeListModel.self)
    } 
 }

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift3.5.0

**Platform/Environment**

iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - easy, 100% repro

**Xcode version**:

```
  Xcode 9.0beta
```

**Installation method**:
  -  CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  -  no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - I have a small code base

**Comment by sergdort** [comment]
Hi,

**Comment by sergdort** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
all who are interested in development of this project and watching it are being spammed by irrelevant information.
those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.
Thank you for understanding.
