### ISSUE TITLE
Reactive UIPickerView

### ISSUE THREAD

**Issue by MrAsterisco** [ReactiveX/RxSwift#1305]
**Short description of the issue**:

  The UIPickerView RX extension is limited and doesn't allow binding of the UIPickerView data source.

**Expected outcome**:

  I would expect to have RX extensions to use the UIPickerView just like I'm used with UITableViews.

**What actually happens**:

 The RX extension only provides an `itemSelected` property which, of course, doesn't work alone (because, there is no way to bind an array of items to the picker).

**Self contained code example that reproduces the issue**:

I would expect something like:

```swift
viewModel.items
 .bind(to: pickerView.rx.items) { row, element in
    // return the display name of the element	
 }
 .disposed(by: self.disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.3
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @MrAsterisco ,

I think it would be theoretically possible, but I would need to investigate that a bit.

**Comment by kzaher** [comment]
Hi @MrAsterisco ,

I think I now remember this one. It wasn't clear how should data model look like. It seems to me that each component could have it's own type, so it's not clear how should generic method that supports multiple components look like.

It also seems that there are 3 ways how one could implement view factory.

```
    // these methods return either a plain NSString, a NSAttributedString, or a view (e.g UILabel) to display the row for the component.
    // for the view versions, we cache any hidden and thus unused views and pass them back for reuse. 
    // If you return back a different object, the old one will be released. the view will be centered in the row rect  
    @available(iOS 2.0, *)
    optional public func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String?

    @available(iOS 6.0, *)
    optional public func pickerView(_ pickerView: UIPickerView, attributedTitleForRow row: Int, forComponent component: Int) -> NSAttributedString? // attributed title is favored if both methods are implemented

    @available(iOS 2.0, *)
    optional public func pickerView(_ pickerView: UIPickerView, viewForRow row: Int, forComponent component: Int, reusing view: UIView?) -> UIView
```

I think different factories could be handled with different extensions, like:
```
viewModel.items
 .bind(to: pickerView.rx.itemTitles) { row, element in
    // return the display name of the element	
 }
 .disposed(by: self.disposeBag)

viewModel.items
 .bind(to: pickerView.rx.itemAttributedTitles) { row, element in
    // return the display name of the element	
 }
 .disposed(by: self.disposeBag)

viewModel.items
 .bind(to: pickerView.rx.items) { row, element in
    // return the display name of the element	
 }
 .disposed(by: self.disposeBag)
```

... but I'm not sure how should sequence elements look like..

**Comment by MrAsterisco** [comment]
I think, but that's totally my own opinion, that it would be nice to support all the three cases, but with separated sequences. I've been working on a iOS for a while and I've never used the ability of the UIPickerView to support different kind of rows: actually, I didn't even know that it was possible.

Even the example in the [iOS Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/) doesn't mention this ability. As a matter of fact, it clearly states:

> Use predictable and logically ordered values. Many values in a picker may be hidden when the scrollable lists are stationary. It's best when people can predict what these values are, such as with a list of alphabetized countries, so they can move through the lists quickly.

How can this rule be followed with different layouts of each row? And, moreover, does anyone know an example of a UIPickerView with items with various layouts?

**Comment by kzaher** [comment]
Hi @MrAsterisco ,

It's not an issue if each row has it's own layout.

`UIPickerViewDataSource` is an adapter interface. The problem is in different components. e.g.

```
let components: [[String]]
```

or 

```
struct Data {
     let component1: [String]
     let component2: [Int]
}
let components: Data
```

I don't see an elegant way to cover all of these cases in a uniform way.

**Comment by kzaher** [comment]
Actually, now that I've said this, we can just allow data to be any type and just pass Int component and row component in lambda.

I'll try to create some prototype for this.

**Comment by MrAsterisco** [comment]
Hello @kzaher,

I'm sorry, I misunderstood your first message.

Well, I still think that as a first implementation it would already be good enough to support a single component.
Hence, the sequence to provide would be something like:

`let elements: [String]`

Most of the times, this is what you want to do with UIPickerViews. What do you think?

**Comment by sergdort** [comment]
Hi, guys! 

@kzaher I feel like we can use the same `SectionModelType` as we are using for `RxDataSources` because essentially `UIPickerView` is a view that has sections and rows, right? Or I missing something 

The only problem that I see so far is that we probably will need to implement 3 concrete adapters based on how user want to customise rows

**Comment by MrAsterisco** [comment]
Hi @sergdort,

As a matter of fact, you're right. A `UIPickerView` is just a `UITableView` drawn differently, their data sources are almost identical (except for the 3 adapters).

I still think that a simpler approach, with just one component, should be taken in consideration, though.

**Comment by kzaher** [comment]
@sergdort 
I think that `UIPickerView` is a bit different than `UI{Table,Collection}View`.

The reason why we had `SectionModelType` and `AnimatedSectionModelType` in RxDataSources was because of animations and editing.

If we don't have animations and editing then we don't need any kind of structured data since user is doing all of the customizations.

@MrAsterisco 
I would need to try to create a prototype for this. It seems to me that it would be easier to implement this inside RxDataSources project first vs main repo.
Having one array would probably enable us to implement number of components and number of rows for component automatically.

The weird thing is that number of components and number of rows per component is on `dataSource`, but `titleForRow`/`attributedTitleForRow`/`viewForRow` are on `delegate`. I am a bit confused why is this the case. This is not consistent with `UI{Table,Collection}View` as far as I can tell.

**Comment by sergdort** [comment]
Hi guys!

Please take a look on proposal PR [here](https://github.com/RxSwiftCommunity/RxDataSources/pull/140)

**Comment by kzaher** [comment]
Hi @sergdort ,

I've left my comments on that PR. Looks pretty good.
