### ISSUE TITLE
collectionview not showing any items

### ISSUE THREAD

**Issue by sseen** [ReactiveX/RxSwift#1314]
**Short description of the issue**:

  collectionview not showing any items

**Expected outcome**:

```swift 
func items<S: Sequence, Cell: UICollectionViewCell, O : ObservableType>
        (cellIdentifier: String, cellType: Cell.Type = Cell.self)
```
function executed and items show

```
// print log 
Resource count 215
false
(0.0, 0.0, 50.0, 50.0)
false
(61.0, 0.0, 50.0, 50.0)
false
(122.0, 0.0, 50.0, 50.0)
false
(183.5, 0.0, 50.0, 50.0)
false
(244.5, 0.0, 50.0, 50.0)
```
**What actually happens**:

 ```swift
func items<S: Sequence, Cell: UICollectionViewCell, O : ObservableType>
        (cellIdentifier: String, cellType: Cell.Type = Cell.self)
```
function executed , but  items not show
```
// print log
Resource count 215
false
(0.0, 0.0, 50.0, 50.0)
false
(61.0, 0.0, 50.0, 50.0)
false
(122.0, 0.0, 50.0, 50.0)
false
(183.5, 0.0, 50.0, 50.0)
false
(244.5, 0.0, 50.0, 50.0)
```
**Self contained code example that reproduces the issue**:

```swift
import UIKit
import RxSwift
import RxCocoa

struct CommonUnit {
    let marginItem = 20
    let navPlusStatus:CGFloat = 64
    let animationTime:TimeInterval = 0.33
    let delayTime:TimeInterval = 0
    let bannerHeight:CGFloat = 120
    let navbar_change_point = 50
    let cellReuse = "cell0"
    let headerReuse = "headerView"
    
    let color = UIColor(colorLiteralRed: 0/255.0, green: 175/255.0, blue: 240/255.0, alpha: 1)
}

class SimpleCollectionViewController: UIViewController {
    
    var mainCollection:UICollectionView!
    let commonUse = CommonUnit()
    var screenWidth:CGFloat!
    var screenHeight:CGFloat!
    var disposeBag: DisposeBag?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let disposeBag = DisposeBag()
        
        screenWidth = self.view.frame.width
        screenHeight = self.view.frame.height
        
        let layout = UICollectionViewFlowLayout()
        layout.headerReferenceSize = CGSize(width: screenWidth, height:commonUse.bannerHeight)
        mainCollection = UICollectionView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: commonUse.bannerHeight * 2), collectionViewLayout: layout)
        mainCollection.contentInset = UIEdgeInsetsMake(0, 0, 0, 0)
        mainCollection.backgroundColor = UIColor.white
        mainCollection.register(NumberCell.self, forCellWithReuseIdentifier: commonUse.cellReuse)
        
        
        self.view.addSubview(mainCollection)
        
        let items = Observable.just(
            (0..<5).map{"\($0)"}
        )
        
        items
            .bind(to: mainCollection.rx.items(cellIdentifier: commonUse.cellReuse, cellType: NumberCell.self)) { (row, element, cell) in
                cell.value?.text = "\(row)"
                cell.backgroundColor = UIColor.darkGray
                print(cell.isHidden)
            }
            .disposed(by: disposeBag)
        

    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
}

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  rxswift 3.5
  rxcocoa 3.5

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 8.3.3
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (xcode 9 beta)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Could you create a sample project that reproduces the issue? Your provided sample is not "Self contained" as it depends on many types you're not exposing here (CommonUnit , the cell itself, etc)

**Comment by sseen** [comment]
@freak4pc thanks u reply, I just updated the code, includes everything.

**Comment by freak4pc** [comment]
@sseen Before even going further, just realized you are init'ing disposeBag inside your viewDidLoad, which means it would be disposed immediately, which would explain your issue.

Could you move your dispose bag to the Class scope ? 
 
e.g.

```
private let disposeBag = DisposeBag()

override func viewDidLoad() { 
... 
}
```

**Comment by sseen** [comment]
@freak4pc Amazing! u save my life, thanks!

**Comment by pavankumar-n-46** [comment]
> @sseen Before even going further, just realized you are init'ing disposeBag inside your viewDidLoad, which means it would be disposed immediately, which would explain your issue.
> 
> Could you move your Dispose Bag to the Class' scope ?
> 
> e.g.
> 
> ```
> private let disposeBag = DisposeBag()
> 
> override func viewDidLoad() { 
> ... 
> }
> ```

@freak4pc  you saved my life too!! thanks
