### ISSUE TITLE
Performing side effects

### ISSUE THREAD

**Issue by marlowcharite** [ReactiveX/RxSwift#132]
Is there a way to perform an intermediary action upon an observable. For instance I want to be able to do:

``` swift
    func getTracks(queryParams: [String: AnyObject]) -> Observable<[Track]> {
        
        return GET("tracks.php", parameters: queryParams)
            .map { return JSONSerializer.convertJSONToTracks($0) }
            .sideEffect {
                // persist the tracks to database
        }

    }
```
and still have the tracks be returned in an observable

**Comment by ikesyo** [comment]
There are [`doOn()` operators](https://github.com/ReactiveX/RxSwift/blob/c4ea7b4bb23d0ae6160c762267fabff08d51f8d7/RxSwift/Observables/Observable%2BSingle.swift#L64-L98).

**Comment by marlowcharite** [comment]
@ikesyo thanks. I just came across this while looking through the documentation... I don't know how I missed it upon the first look through
