### ISSUE TITLE
Throttle don't reset window

### ISSUE THREAD

**Issue by oxape** [ReactiveX/RxSwift#1328]
I learn ReactiveX about [Time-shifted sequences](http://www.introtorx.com/Content/v1.0.10621.0/13_TimeShiftedSequences.html#Throttle)

Unlike Sample though, Throttle's period is a sliding window. Each time Throttle receives a value, the window is reset. Only once the period of time has elapsed will the last value be propagated.Sequences that produce values at a constant rate (like Interval or Timer) either would have all of their values suppressed if they produced values faster than the throttle period, or all of their values would be propagated if they produced values slower than the throttle period. 

But I find throttle operator don't reset window.
My test code
 ```
Observable<Int>
        .interval(1, scheduler: MainScheduler.instance)
        .map({ interval in
            return "interval"
        })
        .throttle(5, scheduler: MainScheduler.instance)
        .subscribe({ event in
            print(event)
        }).addDisposableTo(disposeBag) 
```
In theory i will never receive next event. but i can receive events every five seconds.

I am trying to modify the source code. But I can't understand parameter latest, anyone can help me?
parameter latest: Should latest element received in a dueTime wide time window since last element emission be emitted.
```
public func throttle(_ dueTime: RxTimeInterval, latest: Bool = true, scheduler: SchedulerType)
```

**Comment by kzaher** [comment]
Hi @oxape ,

Rx.NET messed up throttle and debounce as far as I can tell. That caused some confusion with all implementations. Rx.NET throttle = debounce operator.

**Comment by oxape** [comment]
I find definition of debounce.
Debounce — only emit an item from an Observable <strong>if a particular timespan has passed without it emitting another item</strong>. Behavior does not conform to definition of debounce.
is it possible to throttle follow the above definition, if can I want try.
