### ISSUE TITLE
Improve on-boarding for new users. RxCocoa quick-start/cheat sheet docs required.

### ISSUE THREAD

**Issue by tcldr** [ReactiveX/RxSwift#1335]
**Short description of the issue**:

It's not immediately obvious from the documentation how you might get an observable of UIViewController lifecycle events such as `viewDidLoad`, `viewDidAppear`, etc. with RxCocoa. This is a really simple task that one would expect to be supported, but from the initial docs might assume it isn't.

Asking on the slack channel didn't immediately gain results, and it seemed there may be no way at all! The person I spoke to was equally quizzical about it. Only through an (outdated) gist I found by searching the web did I find what I was looking for, `sentMessage(_ selector:)`.

**Expected outcome**:

Going through the documentation I would hope to see an example on grabbing these basic lifecycle events, or more generally, wrapping existing cocoa classes as one of the first steps. That would make onboarding to RxSwift/RxCocoa a much smoother process and help get more people using the framework.

**What actually happens**:

My own journey was to realise that RxCocoa was the Cocoa specific Rx extensions. Navigate to the RxCocoa directory. See no README. Explore the source code. See that the UIViewController extension appeared to be very sparse. Imagine that the desired functionality was missing. Think about (re)implementing myself. Think about abandoning framework wondering what other obvious functionality is missing. etc.

**Solution**

I notice there is no README.md in the RxCocoa directory currently. Maybe it would be a good idea to place it here? Referencing it from the main Readme. Otherwise someone may scan the source code, make the wrong assumption, get disappointed and leave.

The main RxSwift documentation is great. It's a really good overview. I think it needs the addition of explaining the separation between the RxSwift and RxCocoa projects, and a link to a README in the the RxCocoa dir which goes over the basics. Maybe the introduction of `sentMessage(_ selector:)` should be in one of the earlier steps.

I hope this is useful. Thanks.

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
https://github.com/ReactiveX/RxSwift/pull/1256

**Comment by tcldr** [comment]
Hi @kzaher, thanks for your note. That's exactly the kind of thing I was after. Might be worth dropping a pointer in the README under a RxCocoa section? Would defo help retain new users I think. It took me a while to figure out if this could be done succinctly at all.

**Comment by kzaher** [comment]
@tcldr the reason why we haven't advocated this functionality is because it depends on objc dynamic properties.

Apple tooling and App store policies are every day stricter about runtime modifications you can do in your code so it's not irrational to be very careful about using objc dynamic features.

I would rather users are aware that they are using some dynamic API when they are. 

I wouldn't consider this something new users need to know, in fact, I would rather if people would use this feature infrequently for their own sake because of the reasons explained.

I guess that will cost us some popularity probably in the short run, but I'm fine with that.
