### ISSUE TITLE
custom collectionviewflowlayout get crash

### ISSUE THREAD

**Issue by sseen** [ReactiveX/RxSwift#1339]
**Short description of the issue**:
when I custom collectionviewflowlayout the project throws the crashed like

 >*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x610000030340> {length = 2, path = 0 - 1}'

Finally I find the trick to void this, but I still want to know why crash happened.

**Expected outcome**:

  collection view show

**What actually happens**:

  crashed

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x610000030340> {length = 2, path = 0 - 1}'

**Self contained code example that reproduces the issue**:
and I created a [project here](https://github.com/sseen/RxswiftCollectionDataSourceIssueDemo)

```swift
// 
// crashed code 
//
import UIKit

class RDHomeCollectionFlowLayout: UICollectionViewFlowLayout {
    
    var datas:[NumberSection] = [NumberSection]()
    
    override var collectionViewContentSize:CGSize {
        
        let contentWidth = self.collectionView?.bounds.size.width
        let contentHeight = RD.CustomCollection.DayHeaderHeight * 2// (HeightPerHour * HoursPerDay)
        let contentSize = CGSize(width: contentWidth!, height: contentHeight)

        
        return contentSize
    }

    
    override func shouldInvalidateLayout(forBoundsChange newBounds: CGRect) -> Bool {
        return true
    }
    
    override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        var layoutAttributes = [UICollectionViewLayoutAttributes]()

        // Cells
        let visiableIndexPaths = self.indexPathsOfItemsInRect(rect)
        for indexPath:IndexPath in visiableIndexPaths {
            let  attributes = self.layoutAttributesForItem(at: indexPath)
            layoutAttributes.append(attributes!)
        }
        
        
        print("\(layoutAttributes.count)")
        
        return layoutAttributes
    }
    
    func indexPathsOfItemsInRect(_ rect:CGRect) -> [IndexPath] {
        var indexPaths = [IndexPath]()
        if datas.count > 0 {
            for index in datas[0].items {
                let a_index = IndexPath(item: index, section: 0)
                indexPaths.append(a_index)
            }
        }
        
        return indexPaths
    }
    
    
    override func layoutAttributesForItem(at indexPath: IndexPath) -> UICollectionViewLayoutAttributes? {
        let attributes = UICollectionViewLayoutAttributes(forCellWith: indexPath)
        attributes.frame = CGRect(x: (self.itemWidth() + 1 ) * (CGFloat)(indexPath.item) ,
                                  y: RD.CustomCollection.HourHeaderWidth * (CGFloat)(indexPath.item % 4),
                                  width: self.itemWidth(),
                                  height: RD.CustomCollection.HourHeaderWidth)
        
        return attributes
    }
    
    func itemWidth() -> CGFloat {
        let items:CGFloat = 4
        let width = ( K.ViewSize.SCREEN_WIDTH - (items - 1) ) / items
        return width
    }
}
```

```swift
//
// fixed crash code 
//
import UIKit

class RDHomeCollectionFlowLayout: UICollectionViewFlowLayout {
    
    var datas:[NumberSection] = [NumberSection]()
    
    override var collectionViewContentSize:CGSize {
        
        let contentWidth = self.collectionView?.bounds.size.width
        let contentHeight = RD.CustomCollection.DayHeaderHeight * 2// (HeightPerHour * HoursPerDay)
        let contentSize = CGSize(width: contentWidth!, height: contentHeight)

        
        return contentSize
    }

    
    override func shouldInvalidateLayout(forBoundsChange newBounds: CGRect) -> Bool {
        return true
    }
    
    override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        var layoutAttributes = [UICollectionViewLayoutAttributes]()

        // Cells
        let attributesArray = super.layoutAttributesForElements(in: rect);
        guard self.collectionView != nil else {return attributesArray;}
        for attributes in attributesArray ?? [] {
            
            attributes.frame = CGRect(x: (self.itemWidth() + 1 ) * (CGFloat)(attributes.indexPath.item) ,
                                      y: RD.CustomCollection.HourHeaderWidth * (CGFloat)(attributes.indexPath.item % 4),
                                      width: self.itemWidth(),
                                      height: RD.CustomCollection.HourHeaderWidth)
            
            layoutAttributes.append(attributes)
        }
        
        
        print("\(layoutAttributes.count)")
        
        return layoutAttributes
    }
    
    func itemWidth() -> CGFloat {
        let items:CGFloat = 4
        let width = ( K.ViewSize.SCREEN_WIDTH - (items - 1) ) / items
        return width
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 8.3.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode 9 beta)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @sseen ,

I don't think this is RxSwift issue. You are using synchronous initial data in layout while data source still didn't have a chance to be bound with sequence elements.

You can get latest value of items from data source by using `cvReloadDataSource.sectionModels` or using `subscript` on `cvReloadDataSource` in case you want access to individual section or item.

Hope that will help you, but we can't spend time on this since this isn't an issue with library.

**Comment by sseen** [comment]
@kzaher thanks for your reply, I think I know where it was wrong.
