### ISSUE TITLE
`andThen` operator with Single trait disposes immediately after Completable emits completed event

### ISSUE THREAD

**Issue by lizhiquan** [ReactiveX/RxSwift#1347]
**Short description of the issue**:

  `andThen` operator with Single trait disposes immediately after Completable emits completed event.

**Expected outcome**:

  Single should run normally until it emits its own event.

**What actually happens**:

  Single disposes after Completable emit completed event.

**Self contained code example that reproduces the issue**:

```swift
func api() -> Single<[String: AnyObject]> {
    return Single.create { (observer) -> Disposable in
        let url = URL(string: "https://api.github.com/users/phucnm")!
        let task = URLSession.shared.dataTask(with: url, completionHandler: { (data, response, error) in
            do {
                if let data = data {
                    let dict = try JSONSerialization.jsonObject(with: data, options: []) as! [String: AnyObject]
                    observer(.success(dict))
                    print(dict.debugDescription)
                }
            } catch {
                observer(.error(error))
                print(error.localizedDescription)
            }
        })
        task.resume()
        return Disposables.create {
            task.cancel()
        }
    }
}

_ = Completable.empty()
  .andThen(api().debug("api"))
  .debug("result")
  .subscribe()
```
Result:
```
2017-07-20 11:56:11.936: result -> subscribed
2017-07-20 11:56:11.938: api -> subscribed
2017-07-20 11:56:11.943: api -> isDisposed
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _3.6.0_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.3.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @lizhiquan ,

I've made a fix for those issues. Could you please verify #1348 PR solves your issue?

**Comment by lizhiquan** [comment]
Hi @kzaher ,
The issue is solved.

Thanks, @kzaher. 😀

**Comment by kzaher** [comment]
I'm hoping to release a patch release for this and #1344 today.
