### ISSUE TITLE
TableView sometimes glitches after a data change in the Variable that it's bound to

### ISSUE THREAD

**Issue by Meeks91** [ReactiveX/RxSwift#1363]
**Short description of the issue**:

The tableView that my variable is bound to sometimes jumps/glitches when a data change occurs as a result of me clicking on one of the buttons in one of the tableView's cells. **Note:** the glitch only starts occurring after row 4.

**Expected outcome**:

The data should change in the variable that tableView is bound to and then the tableView should update and it's UI should reflect the updated data without glitching. 

**What actually happens**:

The data updates properly but the tableView jumps when it updates the data. This only happens sometimes though. 

**Self contained code example that reproduces the issue**:

**Note:** I've already mentioned this but just to be clear -> the glitch only starts occurring after row 4. 

```swift
    //This in the ViewController
private let variable = Variable<[MyDataClass]>([])

//This is how the tableView is bound to the variable
variable.asObservable()
        .bind(to: questionnaireTableView.rx.items)
        { (tableView, row, dataForRow) in

            //generate the cell identifier for this type of data
            let cellIdentifier = self.generateCellIdentifierForThisTypeOf(data: dataForRow)

            //create the cell
            let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: IndexPath(row: row, section: 0)) as! QuestionnaireCell
            
            //set the text data
            cell.label.text = dataForRow.textData
            
            //set the background colour to reflect the data's value
            cell.button?.backgroundColor = dataForRow.booleanVariable == true ? UIColor.customColourOne : UIColor.customColourTwo

            //assign the onTapListener
            self.addRxTapListenerTo(button: cell.button, in: cell, row: row, data: dataForRow)

            //configures the layout of the specified question
            cell.configureLayoutFor(question: question)

            return cell
        }
        .addDisposableTo(disposeBag)


func addRxTapListenerTo(button: UIButton, in cell: QuestionnaireCell, row: Int, data: MyDataClass){

        //add the onTap listener
        button.rx.tap.asObservable().bind {

                    //send the tap to the presenter
                    self.presenter.onButtonTapped(data: data, index: row)
                }
                .addDisposableTo(cell.disposeBag)
}

//This is in the presenter

/* called from the view when a button is selected. It updates the data stored
   at the given index in the our arrayOfDataObjects and then notifies the view
   that the data has been updated */
func onButtonTapped(data: MyDataClass, index: Int){

    updateDataSourceWith(data: data, at: index)

    viewDelegate.onDataUpdata(data:  MyDataSingleton.shared.arrayOfDataObject)
}

//updates the QuestionnaireData with the specified selectedAnswer at the given index
func updateDataSourceWith(data: MyDataClass, at index: Int){

    MyDataSingleton.shared.arrayOfDataObjects[index] = data
}

//This is back in the viewController

/* updates the variable which the tableView is bound to */
func updateViewWith(data: [MyDataClass]){
    
    questionnareDataVariable.value = data
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

'~> 3.0'

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] sometimes, 10%-100%

**Xcode version**:

8.3.2

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  - [x] no

**Level of RxSwift knowledge**:

 - [x] I have a basic understanding of it.

**Comment by Meeks91** [comment]
To fix the issue you have to assign a new instance of DisposeBag to the cell's disposeBag variable when prepareForReuse() is called:

class CustomCell: UITableViewCell{

var disposeBag = DisposeBag() 


override func prepareForReuse() {
        super.prepareForReuse()

        disposeBag = DisposeBag() 
    }
}

**Comment by kzaher** [comment]
Hi @Meeks91 ,

I don't think we can figure out from your example what is happening because it's not self contained. I'm glad you've found what worked for you.
