### ISSUE TITLE
GeolocationService.instance.unsafeMutableAddressor

### ISSUE THREAD

**Issue by 1cookspe** [ReactiveX/RxSwift#1370]
**Short description of the issue**:

In the "GeolocationService.swift" file, located at "https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Services/GeolocationService.swift", the iOS app crashes with a SIGABRT error (Thread 1: signal SIGABRT). The specific line that this occurs is line 17, at "static let instance = GeolocationService()". 

More specifically, it returns an exception of "GeolocationService.instance.unsafeMutableAddressor". Any ideas on why this may be?

**Expected outcome**:

I expect this to occur without error, allowing me to manage the user's location.

**What actually happens**:

An exception of "GeolocationService.instance.unsafeMutableAddressor" is returned, and a SIGABRT error is triggered on the below code. 

**Self contained code example that reproduces the issue**:

```swift
static let instance = GeolocationService()
  
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [x] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.3
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode 8.3.3, Xcode-Beta)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @1cookspe ,

I can't repro this on master  branch. Why are you using 3.0 tag?

**Comment by 1cookspe** [comment]
Thanks for your response! I'm using 3.0 for the 3.0 version of RxSwift.

**Comment by freak4pc** [comment]
Please install the newest version of RxSwift. You're using a very old one.

**Comment by 1cookspe** [comment]
Thanks for the advice! How should I install the newest version of RxSwift? Should I run `pod install`

**Comment by freak4pc** [comment]
@1cookspe Make sure your Podfile is correct and do a `pod update`. 

I'm closing this right now as it's not an issue with RxSwift or RxCocoa, but more of a Cocoapods issue. If you have any more questions, feel free to join our Slack channel!
