### ISSUE TITLE
CurrentThreadScheduler does not conform to SchedulerType

### ISSUE THREAD

**Issue by eliasbagley** [ReactiveX/RxSwift#1377]
Hey,
I'm trying to inject my schedulers so I can replace them during my tests. I'm pretty sure the scheduler I want to use for my tests is `CurrentThreadScheduler.instance`, but this conforms to `ImmediateSchedulerType`, not `SchedulerType`. This is possible to do in RxJava with a trampoline scheduler, but I don't know how to achieve this same behavior.

**Comment by kzaher** [comment]
Hi @eliasbagley ,

Maybe you want `RxTest.TestScheduler`?
