### ISSUE TITLE
Help me add support for MFMailComposeViewController

### ISSUE THREAD

**Issue by nmdias** [ReactiveX/RxSwift#1378]
Hi,

Please help me add support for `MFMailComposeViewController`. I want this for my App, and I would very much like to add it to RxCocoa, once I get it to work.

I'm attempting to extend **RxCocoa to support the `MFMailComposeViewController`**. However, I believe that my subscription is getting disposed before I get to do anything and I don't know why. Yet!  I'm also unable to get the delegate to work properly. But I'm not sure if this is the origin of my issue...

Here's where I'm at:

I created an `RxMailComposerDelegateProxy`. 

> Notice the use of the `mailComposeDelegate` property and not the `delegate` from a `UINavigationControllerDelegate`.

```swift
/// For more information take a look at `DelegateProxyType`.
public class RxMailComposerDelegateProxy
    : DelegateProxy
    , MFMailComposeViewControllerDelegate
    , DelegateProxyType {
    
    /// For more information take a look at `DelegateProxyType`.
    public class func currentDelegateFor(_ object: AnyObject) -> AnyObject? {
        let mailComposer: MFMailComposeViewController = castOrFatalError(object)
        return mailComposer.mailComposeDelegate
    }
    
    /// For more information take a look at `DelegateProxyType`.
    public class func setCurrentDelegate(_ delegate: AnyObject?, toObject object: AnyObject) {
        let mailComposer: MFMailComposeViewController = castOrFatalError(object)
        mailComposer.mailComposeDelegate = castOptionalOrFatalError(delegate)
    }
    
    // MARK: Delegate proxy methods
    
    #if os(iOS)
    /// For more information take a look at `DelegateProxyType`.
    public override class func createProxyForObject(_ object: AnyObject) -> AnyObject {
        let mailComposer: MFMailComposeViewController = castOrFatalError(object)
        return mailComposer.createRxDelegateProxy()
    }
    #endif
    
}
```

Then I extended `Reactive` for a Base of type `MFMailComposeViewController` with that proxy:

```swift
extension Reactive where Base: MFMailComposeViewController {
    
    /// Reactive wrapper for `delegate`.
    ///
    /// For more information take a look at `DelegateProxyType` protocol documentation.
    public var mailComposeDelegate: DelegateProxy {
        return RxMailcomposerDelegateProxy(parentObject: base)
    }
  
}
```

And the `mailComposeDelegate` method `didFinishWith`:

```swift
extension Reactive where Base: MFMailComposeViewController {
    
    /// Reactive wrapper for `delegate` message.
    public var didFinishWith: Observable<(MFMailComposeResult, NSError?)> {
        return mailComposeDelegate.methodInvoked(#selector(MFMailComposeViewControllerDelegate.mailComposeController(_:didFinishWith:error:)))
            .map { result -> (MFMailComposeResult, NSError?) in
                let composeResult = try castOrThrow(MFMailComposeResult.self, result[1])
                let error = try castOptionalOrThrow(NSError.self, result[2])
                return (composeResult, error)
        }
    }
    
}
```

Next, on the actual app, I'm creating an `Observable<MFMailComposeViewController>`:

```swift

enum MFMailComposeError: CustomNSError {
    case cantSendEmail
    static let domain = "Custom MFMailCompose error"
    var errorCode: Int { return -9999 }
    var errorUserInfo: [String : Any] {
        return [
            NSLocalizedDescriptionKey: "Device cannot send email.",
            NSLocalizedFailureReasonErrorKey: "The device doesn't have an email account setup.",
            NSLocalizedRecoverySuggestionErrorKey: "Setup an email accound on the device."
        ]
    }
}

extension Reactive where Base: MFMailComposeViewController {
    
    static func create(
        with parentViewController: UIViewController?,
        animated: Bool = true,
        configure: @escaping (MFMailComposeViewController) throws -> () = { x in })
        -> Observable<MFMailComposeViewController>
    {
        return Observable.create({ [weak parentViewController] observer -> Disposable in
            
            if !MFMailComposeViewController.canSendMail() {
                observer.on(.error(MFMailComposeError.cantSendEmail))
                return Disposables.create()
            }
            
            let mailComposer = MFMailComposeViewController()
            
            let dismissDisposable = mailComposer.rx.didFinishWith.debug().subscribe(onCompleted: { [weak mailComposer] in
                guard let mailComposer = mailComposer else {
                    return
                }
                dismissViewController(mailComposer, animated: animated)
            })
            
            do {
                try configure(mailComposer)
            } catch let error {
                observer.on(.error(error))
                return Disposables.create()
            }
            
            guard let parentViewController = parentViewController else {
                observer.on(.completed)
                return Disposables.create()
            }
            
            parentViewController.present(mailComposer, animated: animated)
            observer.on(.next(mailComposer))
            
            return Disposables.create(dismissDisposable, Disposables.create {
                dismissViewController(mailComposer, animated: animated)
            })
            
        })
        
    }
    
}
```

This code takes inspiration from the existing UIImagePickerController [example](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/ImagePicker/UIImagePickerController%2BRxCreate.swift)

Now, on my view controller, I create the said `observer`, `flatMap` into the `didFinishWith` delegate and `subscribe`.

```swift
MFMailComposeViewController.rx.create(with: self) { (mailComposer) in
        mailComposer.setToRecipients(["example@mail.com"])
        mailComposer.setMessageBody("Message body", isHTML: false)
    }
    .debug()
    .flatMap { $0.rx.didFinishWith }
    .subscribe(onNext: {(result: MFMailComposeResult, error: NSError?) in

    }, onError: { (error) in

    }, onCompleted: {
        
    }, onDisposed: {
        
    }).disposed(by: disposeBag)
```

I'm not sure what's wrong here. The composer is presented, but then the`didFinishWith` is never called when I attempt to send or cancel the email.

Here's my output:

```
2017-08-13 00:20:30.505: SettingsViewController.swift:100 (viewDidLoad()) -> subscribed
2017-08-13 00:20:30.533: Reactive + MFMailComposeViewController.swift:126 (create(with:animated:configure:)) -> subscribed
2017-08-13 00:20:30.534: Reactive + MFMailComposeViewController.swift:126 (create(with:animated:configure:)) -> Event completed
2017-08-13 00:20:30.534: Reactive + MFMailComposeViewController.swift:126 (create(with:animated:configure:)) -> isDisposed
2017-08-13 00:20:30.535: SettingsViewController.swift:100 (viewDidLoad()) -> Event next(<MFMailComposeViewController: 0x12a082200>)

```

Note: This is all on happening on a device, as the simulator won't work for the mail composer.

I'm fairly new to all things Rx, so the issue might be my lack of understanding of RxSwift/RxCocoa. If someone could have a quick look at my code. Thanks!

**Comment by freak4pc** [comment]
Hey @nmdias 
First of all I want to start off by my personal opinion - I don't think a RX wrapper for MFMailComposerViewController is in the scope of RxCocoa since it's not a "Core" component. It's not a common component so it is better to have as a separate library or even just a personal implementation of whoever uses it. 

Also this is a lot of code so I won't have time to actually check implementation ATM. If possible, could you wrap this up in a testable & runnable project ? I'll try to assist.

**Comment by nmdias** [comment]
Hi @freak4pc. Because it's a view controller I assumed it would fall into RxCocoa. I now understand that it doesn't. Thank you for your insight.

I'm still looking forward to the idea of contributing to RxSwift. Maybe as an Example, similar to the existing Image Picker examples? Or as you suggested an external library. Maybe both.

Anyways:

I created a repo with RxSwift already pre-compiled showing my issue:

https://github.com/nmdias/RxMailComposer

Thank you

**Comment by freak4pc** [comment]
@nmdias RxCocoa's scope is more around the "basics" that **every app needs** and not the more specific components that **some apps need**. The intent is to leave RxCocoa as thing as possible ATM which is also why even some of the core components like UIButton and UITextField don't have _all_ properties, but just the most popular ones. 

UIImagePickerController is also a very specific use case and not something I would generalize as part of RxCocoa (there is already a library in RxSwiftCommunity that does that).

I'll try to take a look at your repo as well :)

**Comment by freak4pc** [comment]
Hey @nmdias 
Would you mind creating this as an issue in your own repository ? 

I'm closing this one and asking since this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
It would be better to ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

I'm asking this because:

- we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
- all who are interested in development of this project and watching it are being spammed by irrelevant information.
- those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding. 😄

**Comment by RustamKhisamov** [comment]
Hi @nmdias 
Did you find the solution?

**Comment by RustamKhisamov** [comment]
I found the issue. Should be this:
`public var mailComposeDelegate: DelegateProxy<MFMailComposeViewController, MFMailComposeViewControllerDelegate> {
        return RxMailComposerDelegateProxy.proxy(for: base)
    }`
instead:
` public var mailComposeDelegate: DelegateProxy {
        return RxMailcomposerDelegateProxy(parentObject: base)
    }`

My working code:
`
func dismissViewController(_ viewController: UIViewController, animated: Bool) {
    if viewController.isBeingDismissed || viewController.isBeingPresented {
        DispatchQueue.main.async {
            dismissViewController(viewController, animated: animated)
        }
        
        return
    }
    
    if viewController.presentingViewController != nil {
        viewController.dismiss(animated: animated, completion: nil)
    }
}

enum MFMailComposeError: CustomNSError {
    case cantSendEmail
    static let domain = "Custom MFMailCompose error"
    var errorCode: Int { return -9999 }
    var errorUserInfo: [String: Any] {
        return [
            NSLocalizedDescriptionKey: "Device cannot send email.",
            NSLocalizedFailureReasonErrorKey: "The device doesn't have an email account setup.",
            NSLocalizedRecoverySuggestionErrorKey: "Setup an email accound on the device."
        ]
    }
}

extension Reactive where Base: MFMailComposeViewController {
    static func create(
        with parentViewController: UIViewController?,
        animated: Bool = true,
        configure: @escaping (MFMailComposeViewController) throws -> Void = { x in })
        -> Observable<MFMailComposeViewController> {
        return Observable.create({ [weak parentViewController] observer in
            
            if !MFMailComposeViewController.canSendMail() {
                observer.on(.error(MFMailComposeError.cantSendEmail))
                return Disposables.create()
            }
            
            let mailComposer = MFMailComposeViewController()
            
            let dismissDisposable = mailComposer.rx
                .didFinishWith
                .subscribe(onCompleted: { [weak mailComposer] in
                    guard let mailComposer = mailComposer else {
                        return
                    }
                    dismissViewController(mailComposer, animated: animated)
                })
            
            do {
                try configure(mailComposer)
            } catch let error {
                observer.on(.error(error))
                return Disposables.create()
            }
            
            guard let parentViewController = parentViewController else {
                observer.on(.completed)
                return Disposables.create()
            }
            
            parentViewController.present(mailComposer, animated: animated)
            observer.on(.next(mailComposer))
            
            return Disposables.create(dismissDisposable, Disposables.create {
                dismissViewController(mailComposer, animated: animated)
            })
        })
    }
    
    public var mailComposeDelegate: DelegateProxy<MFMailComposeViewController, MFMailComposeViewControllerDelegate> {
        return RxMailComposerDelegateProxy.proxy(for: base)
    }

    public var didFinishWith: Observable<(MFMailComposeResult, NSError?)> {
        return mailComposeDelegate
            .methodInvoked(#selector(MFMailComposeViewControllerDelegate.mailComposeController(_:didFinishWith:error:)))
            .map { result in
                let composeResult = try castOrThrow(MFMailComposeResult.self, result[1])
                let error = try castOptionalOrThrow(NSError.self, result[2])
                return (composeResult, error)
        }
    }
}

private func castOrThrow<T>(_ resultType: T.Type, _ object: Any) throws -> T {
    
    guard let returnValue = object as? T else {
        throw RxCocoaError.castingError(object: object, targetType: resultType)
    }
    
    return returnValue
}

private func castOptionalOrThrow<T>(_ resultType: T.Type, _ object: Any) throws -> T? {
    
    if NSNull().isEqual(object) {
        return nil
    }
    
    guard let returnValue = object as? T else {
        throw RxCocoaError.castingError(object: object, targetType: resultType)
    }
    
    return returnValue
}
`

and the proxy:
`public class RxMailComposerDelegateProxy: DelegateProxy<MFMailComposeViewController, MFMailComposeViewControllerDelegate>,
    MFMailComposeViewControllerDelegate, DelegateProxyType, UINavigationControllerDelegate {

    public weak private(set) var mailController: MFMailComposeViewController?
    
    public init(mailController: ParentObject) {
        self.mailController = mailController
        super.init(parentObject: mailController, delegateProxy: RxMailComposerDelegateProxy.self)
    }
    
    public static func registerKnownImplementations() {
        self.register { RxMailComposerDelegateProxy(mailController: $0) }
    }
    
    public static func currentDelegate(for object: MFMailComposeViewController) -> MFMailComposeViewControllerDelegate? {
        let mailComposer: MFMailComposeViewController = castOrFatalError(object)
        return mailComposer.mailComposeDelegate
    }
    
    public static func setCurrentDelegate(_ delegate: MFMailComposeViewControllerDelegate?, to object: MFMailComposeViewController) {
        let mailComposer: MFMailComposeViewController = castOrFatalError(object)
        mailComposer.mailComposeDelegate = castOptionalOrFatalError(delegate)
    }
}

private func castOrFatalError<T>(_ value: Any!) -> T {
    let maybeResult: T? = value as? T
    guard let result = maybeResult else {
        rxFatalError("Failure converting from \(value) to \(T.self)")
    }
    
    return result
}

private func castOptionalOrFatalError<T>(_ value: AnyObject?) -> T? {
    if value == nil {
        return nil
    }
    let v: T = castOrFatalError(value)
    return v
}

private func rxFatalError(_ lastMessage: String) -> Never {
    // The temptation to comment this line is great, but please don't, it's for your own good. The choice is yours.
    fatalError(lastMessage)
}`

**Comment by freak4pc** [comment]
Hi @RustamKhisamov,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
