### ISSUE TITLE
Unrecognized selector for UITapGestureRecognizer

### ISSUE THREAD

**Issue by devAlikhani** [ReactiveX/RxSwift#1382]
I want add `UITapGestureRecognizer` to main View in `viewDidLoad`, but when i use gesture app is terminating with this error :

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TtGC7RxCocoa13GestureTargetCSo22UITapGestureRecognizer eventHandler:]: unrecognized selector sent to instance 0x600000446bd0'`

```
let tapGest = UITapGestureRecognizer()
    tapGest.rx.event.subscribe(onNext: {[weak self] _ in
        self?.view.endEditing(true)
    }).disposed(by: disposeBag)
    view.addGestureRecognizer(tapGest)
```

RxSwift version : 4.0.0-alpha.0

**Comment by kzaher** [comment]
Hi @devAlikhani ,

I've pushed a fix with this to `swift4.0` branch. .1 version will be out soon.
