### ISSUE TITLE
UIDatePicker .countDownTimer | rx.countDownDuration

### ISSUE THREAD

**Issue by adamsmaka** [ReactiveX/RxSwift#1391]
**Short description of the issue**:

UIDatePicker with mode .countDownTimer skips elements.
It always skips first pick, then works, but sometimes also skip something later.

**Expected outcome**:

to receive onNext TimeInterval from first roll of UIDatePicker

**What actually happens**:

I receive onNext from second pick. Exactly like I'd have .skip(1), but I don't.

**Self contained code example that reproduces the issue**:

```
    lazy var countDownPicker: UIDatePicker = {
        let picker = UIDatePicker()
        picker.datePickerMode = .countDownTimer
        return picker
    }()

    func setupPickers() {
        countDownPicker.rx
            .countDownDuration
            .debug()
            .subscribe(onNext: { [weak self] time in
                // do sth
            })
            .disposed(by: bag)
    }
```
  

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
```
3.4.1 (I don't know why "pod update RxSwift" does nothing :( I can't update to newer one)
```
**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
8.3.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @adamsmaka ,
I would suggest checking your dependencies first. One of them probably has hardcoded 3.4.1.

Are you sure that changes being skipped are caused by user input. We skip programatic changes.

**Comment by ramonvic** [comment]
Same error here, always skip first change.

**Comment by adamsmaka** [comment]
yes, i'm using picker itself, not programatically

**Comment by kzaher** [comment]
@adamsmaka it looks like this behavior could be connected with https://stackoverflow.com/questions/28295013/uidate-picker-valuechanged-does-not-update-the-first-spin-but-does-every-spin-a as @ramonvic explained.

@adamsmaka  if there is any reason to believe that there is some other issue with this library we can reopen this issue, otherwise don't know what to investigate and how to validate this issue is closed.
