### ISSUE TITLE
rx.deallocated extension not appearing on my view controller

### ISSUE THREAD

**Issue by cbowns** [ReactiveX/RxSwift#1397]
**Short description of the issue**:

I can't use `self.rx.deallocated`, per the RxSwift intro docs recommendation on deallocating a subscriber when its parent object deinits ([the docs](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#take-until))

When I try the docs' recommendation:

```
sequence
    .takeUntil(self.rx.deallocated)
    .subscribe {
        print($0)
    }
```

As:

```
let deallocSignal = self.rx.deallocated
```

 I get a compilation error:

```
/Users/cbowns/Development/RxTest/RxTest/RxTest/ViewController.swift:17:34: Value of type 'Reactive<ViewController>' has no member 'deallocated'
```

**Expected outcome**:

`self.rx.deallocated` is defined, per the Reactive protocol's extension in NSObject+Rx.swift:

```
// Dealloc
extension Reactive where Base: AnyObject {
    
    /**
    Observable sequence of object deallocated events.
    
    After object is deallocated one `()` element will be produced and sequence will immediately complete.
    
    - returns: Observable sequence of object deallocated events.
    */
    public var deallocated: Observable<Void> {

…
```

**What actually happens**:

A compilation error.

**Self contained code example that reproduces the issue**:

Attached is a zip of a greenfield project which uses Carthage to compile RxSwift 3.6.1. In the RxTest.workspace, I have RxTest set to embed and link the RxSwift iOS framework.

[RxTest.zip](https://github.com/ReactiveX/RxSwift/files/1278677/RxTest.zip)

Note that self.rx.base is defined:

<img width="599" alt="screenshot 2017-09-05 12 41 03" src="https://user-images.githubusercontent.com/474/30080175-7fa1a9b4-9237-11e7-997c-43946cc75eb5.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
└─❱❱❱ xcodebuild -version   
Xcode 8.3.3
Build version 8E3004b
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

I'm new to RxSwift but have shipped two production apps with ReactiveCocoa 1.x.

**Comment by devxoul** [comment]
Could you import `RxCocoa` and try again?

**Comment by cbowns** [comment]
Yeah, that fixes it. Lemme make a PR for a readme update.

**Comment by cbowns** [comment]
Yeah, that fixes it… but why? It doesn't seem like it should, given where that extension is defined.

**Comment by cbowns** [comment]
For example, I just copied and pasted a bit of the NSObject+Rx.swift's AnyObject extensions into my file, and everything is fine (fine being "it built"):

```
import UIKit
import RxSwift

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // This builds now.
        let deallocSignal = self.rx.deallocated

        // This does build:
        let objectBase = self.rx.base
    }
}

// Pull in some NSObject+Rx extensions:

fileprivate var deallocatedSubjectTriggerContext: UInt8 = 0
fileprivate var deallocatedSubjectContext: UInt8 = 0

fileprivate final class DeallocObservable {
    let _subject = ReplaySubject<Void>.create(bufferSize:1)

    init() {
    }

    deinit {
        _subject.on(.next(()))
        _subject.on(.completed)
    }
}

// MARK: AnyObject + Reactive

extension Reactive where Base: AnyObject {
    func synchronized<T>( _ action: () -> T) -> T {
        objc_sync_enter(self.base)
        let result = action()
        objc_sync_exit(self.base)
        return result
    }
}

// Dealloc
extension Reactive where Base: AnyObject {

    /**
     Observable sequence of object deallocated events.

     After object is deallocated one `()` element will be produced and sequence will immediately complete.

     - returns: Observable sequence of object deallocated events.
     */
    public var deallocated: Observable<Void> {
        return synchronized {
            if let deallocObservable = objc_getAssociatedObject(base, &deallocatedSubjectContext) as? DeallocObservable {
                return deallocObservable._subject
            }

            let deallocObservable = DeallocObservable()

            objc_setAssociatedObject(base, &deallocatedSubjectContext, deallocObservable, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
            return deallocObservable._subject
        }
    }
}
```

**Comment by devxoul** [comment]
`rx.deallocated` is declared in NSObject, not AnyObject.

**Comment by cbowns** [comment]
Right right, but it's an extension on AnyObject

**Comment by devxoul** [comment]
Actually it's declared on the protocol named `Reactive` rather than `AnyObject`.

**Comment by cbowns** [comment]
ok, yes. "it's an extension on Reactive for classes which inherit from AnyObject". It's not constrained to NSObject, it's for AnyObject.

My real question is, can this be moved into RxSwift from RxCocoa?

**Comment by devxoul** [comment]
I think it is not possible. `rx.deallocated` requires some runtime Objective-C trick (associated object) but we are trying to keep RxSwift a pure Swift implementation without any dependency of Objective-C types.

**Comment by cbowns** [comment]
gotcha, ok. I'll submit a PR to change the docs.
