### ISSUE TITLE
NSControl value changes can only have one observer

### ISSUE THREAD

**Issue by fpillet** [ReactiveX/RxSwift#1398]
**Short description of the issue**:

`NSControl` on macOS can only have one observer receiving value changes due to the internal implementation of `value<C,T>` in `NSControl+Rx.swift`

A corollary to this issue is that if we try to expose different types when `value` changes, we get a crash due to the internal implementation of `value<C,T>`. Read on.

**Expected outcome**:

Multiple observers should work, and the output type of the observable should not cause a crash.

**Discussion**:

This issue surfaced when I implemented `NSPopUpButton+Rx` on macOS, which exposes the selected item in different forms (a `String`, an item index `Int`, a `NSMenuItem`...). Internally, all implementations piggyback on `rx.value`, which uncovered two major issues:

* macOS controls have only one target/action. Due to the internal implementation of `NSControl.rx.value<C,T>(...)` which uses `Observable.create`, every time a new observer subscribes to the value its `ControlTarget` overrides the one of the previous observer, effectively muting its observable.
* another issue is that the `lazyInstanceObservable` created used a closure with a generic type matching the output observable's type. This effectively prevented multiple types from being produced from `NSControl.rx.value`, producing a crash in the type downcast inside `lazyInstanceObservable`

The solution is required two changes:
* first make value change observance generic by using a single `Void` observable type. The real type is output with a `map` calling the provided getter
* second, share the resulting observable (with `replay: 1, scope: .forever` strategy) to guarantee that new observers don't shut previous ones and get the latest value.

This issue comes with a PR that both demonstrates and solves the problem, in the context on macOS.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

See PR #1399 for implementation

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Comment by kzaher** [comment]
I've cherry picked and applied commits to 4.0 branch and develop. We'll probably do a another 3.6.2 patch release because of this one.
