### ISSUE TITLE
RxTableViewSectionedReloadDataSource doesn't work with self sizing cells

### ISSUE THREAD

**Issue by iOSDevFin** [ReactiveX/RxSwift#1400]
Hi there,

I've noticed a crash on 'bindTo' when using a RxTableViewSectionedReloadDataSource when the following properties are set:

		tableView.estimatedRowHeight = 50
		tableView.rowHeight = UITableViewAutomaticDimension

These properties are needed in order to make sure that the cells are self sizing. However, it looks like the delegate of the tableview is running earlier than usual and is using an empty datasource... That's kind of weird. 

Binding:

		viewModel.marketOverview.asObservable()
			.bindTo(tableView.rx.items(dataSource: dataSource))
			.addDisposableTo(disposeBag)

Notice:

It's working fine when I remove the property estimatedRowHeight... working everything as expected..

Latest RXSwift
Latest RXDataSources

Does anyone have an idea how to solve this issue?

Many thanks

**Comment by freak4pc** [comment]
Hey @Maik987 
I have several VCs setting these properties with RxDataSources and with no issues so I assume its not the library's issue in this case

**Comment by Maik987** [comment]
@freak4pc Hi there, do you have any sample code that's working for me?

**Comment by Maik987** [comment]
@freak4pc hehe :) I mean a sample application

**Comment by freak4pc** [comment]
@Maik987 It's not realistic to ask of people to write sample applications for you :) If you need help you need to provide a reproducible sample project that doesn't work and then we can try and assist

**Comment by Maik987** [comment]
Anyway. I've written down the issue in detail. Looking forward to some other answers. Thank you so far.

**Comment by freak4pc** [comment]
I believe I was trying to help you here, but your issue is not detailed... You have an issue that is only specific to your app and not the library, but you are not sharing any specific code or reproducible sample. I don't think anyone would be able to assist easily otherwise... 

If you can take a few minutes to make a clean sample project that I can run locally I'd love to help out.

**Comment by Maik987** [comment]
Please find attached a sample application that crashes. 

Comment out the estimatedRowHeight and it's working
[SampleRXDataSourceWithSelfSizing.zip](https://github.com/ReactiveX/RxSwift/files/1280457/SampleRXDataSourceWithSelfSizing.zip)

**Comment by Maik987** [comment]
Please find attached an "updated" version of the sample crash application

**Comment out the estimatedRowHeight and it's working**

[SampleRXDataSourceWithSelfSizing.zip](https://github.com/ReactiveX/RxSwift/files/1280490/SampleRXDataSourceWithSelfSizing.zip)
