### ISSUE TITLE
Type 'inout UITableView' does not conform to protocol 'ReactiveCompatible'

### ISSUE THREAD

**Issue by 1cookspe** [ReactiveX/RxSwift#1401]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://rxswift-slack.herokuapp.com/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

We keep receiving an error saying that our UITableView does not conform to protocol 'ReactiveCompatible'

**Expected outcome**:

The code should run smoothly.

**What actually happens**:

We receive an error of "Type 'inout UITableView' does not conform to protocol 'ReactiveCompatible'"
![screen shot 2017-09-07 at 3 43 22 pm](https://user-images.githubusercontent.com/8737691/30181926-fc961804-93e2-11e7-8e4e-c53349a9bcfd.png)

**Self contained code example that reproduces the issue**:

```swift
  searchViewModel
            .sectionItems?
            .do(onCompleted:  { _ in
                SVProgressHUD.dismiss()
            })
            .bind(tableView.rx.items(dataSource: searchViewModel.dataSource))
            .addDisposableTo(rx_disposeBag)
  
// The error is in the second to last line
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [x] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.3.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kayorl** [comment]
i met the same problem,  how did you solve?
