### ISSUE TITLE
onCompleted not called

### ISSUE THREAD

**Issue by arjunnaha** [ReactiveX/RxSwift#1403]
**Short description of the issue**:

onCompleted subscribe not called in the view controller. At the moment the view model calls the login function and the view controller subscribes to the view model - this doesn't call the onCompleted block in the view controller. However, when the login function is called directly from the view controller, it works, leading me to believe that something is up with the view model.

**Expected outcome**:

`onCompleted` method on subscribe called when `observer.onCompleted()` is called on the Observable.

**What actually happens**:

`onCompleted` never called despite `.debug()` stating 'Event completed'. However, when an error occurs, `onError` _is_ called.

**Self contained code example that reproduces the issue**:

Auth Provider:
```swift
func login(username: String, password: String) -> Observable<Void> {
        return Observable.create { observer in
            provider.rx.request(.auth)
                .filter(statusCode: 200)
                .mapJSON()
                .subscribe(
                onSuccess: { json in
                    observer.onCompleted()
                }, onError: { error in
                    observer.onError(error)
                })
                .disposed(by: disposeBag)
         }
    }
```
View Model: 
```swift
        let authManager = AuthManager()
        let usernameAndPassword = Observable.combineLatest(input.username, input.password) { (username: $0, password: $1) }

       authStatus = input.didPressButton
            .withLatestFrom(usernameAndPassword)
            .flatMapLatest { pair in
                return authManager.login(username: pair.username, password: pair.password)
            }
```
View Controller:
```swift
        let viewModel = LoginViewModel(
            input: (
                username: loginUsernameField.rx.text.orEmpty.asObservable(),
                password: loginPasswordField.rx.text.orEmpty.asObservable()
            )
        )
        
        viewModel.authStatus
            .debug("VC")
            .subscribe(
                onNext: {
                    print("next")
            },
                onError: { error in
                    print("error")
            },
                onCompleted: {
                    print("completed")
            },
                onDisposed: {
                    print("disposed")
            })
           .addDisposableTo(disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 9.0 beta 5
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @arjunnaha ,

I'm not sure this is self contained example (I can run it and replicate the behavior). The only thing I can suggest is to do this
```
func login(username: String, password: String) -> Observable<Void> {
            return provider.rx.request(.auth)
                .filter(statusCode: 200)
                .mapJSON()
                .asObservable()
    }
```
and never use dispose bags inside a function that returns and observable sequence.

If you can provide some self contained example then we can investigate where is the potential issue.

**Comment by arjunnaha** [comment]
After quite a lot of debugging, I found I could fix this by adding the `take` operator to my view model. I'm using this quite blindly, unaware of what this is doing...

```swift
        let authManager = AuthManager()
        let usernameAndPassword = Observable.combineLatest(input.username, input.password) { (username: $0, password: $1) }

       authStatus = input.didPressButton
            .take(1)
            .withLatestFrom(usernameAndPassword)
            .flatMapLatest { pair in
                return authManager.login(username: pair.username, password: pair.password)
            }
```

**Comment by kzaher** [comment]
Hi @arjunnaha ,

If you can provide some **self contained example** (something we can run), and explain what is the exact problem then we can investigate where is the potential issue.

**Comment by arjunnaha** [comment]
Hi @kzaher,

Find below a self contained example, that you should be able to run:

**View Controller**
```swift
import UIKit
import RxSwift
import RxCocoa

class LoginViewController: UIViewController {

    let disposeBag = DisposeBag()

    // MARK: Interface Builder - Setup IB with two text field and a button
    @IBOutlet weak var loginUsernameField: UITextField!
    @IBOutlet weak var loginPasswordField: UITextField!
    @IBOutlet weak var loginButton: UIButton!

    override func viewDidLoad() {
        
        let viewModel = LoginViewModel(
            input: (
                username: loginUsernameField.rx.text.orEmpty.asObservable(),
                password: loginPasswordField.rx.text.orEmpty.asObservable(),
                didPressButton: loginButton.rx.tap.asObservable()
            )
        )
        
           viewModel.authStatus
            .debug("VC")
            .subscribe(onNext: {
                     print("Next")
            }, onError: { error in
                    print("Error")
            }, onCompleted: {
                    print("Completed")
            }, onDisposed: {
                   print("Disposed")
            })
            .addDisposableTo(disposeBag)
    }
    
}

```

**View Model**
```swift
import Foundation
import RxSwift
import RxCocoa

class LoginViewModel {
    
    // Outputs
    let authStatus: Observable<Void>
    
    init(input: (
        username: Observable<String>,
        password: Observable<String>,
        didPressButton: Observable<Void>
        )) {
        
        let authManager = AuthManager()
        let fakeAuthService = FakeAuthService()
        
        let usernameAndPassword = Observable.combineLatest(input.username, input.password) { (username: $0, password: $1) }
        

        authStatus = input.didPressButton
            .debug("VM")
            //.take(1)
            .withLatestFrom(usernameAndPassword)
            .flatMapLatest { pair in
                return fakeAuthService.login(username: pair.username, password: pair.password)
            }
        
    }
}


class FakeAuthService {
    func login(username: String, password: String) -> Observable<Void> {
        return Observable.create { observer in
            if(username == "test" && password == "test") {
                observer.onCompleted()
            } else {
                let error = NSError(domain:"test", code:1, userInfo:nil)
                observer.onError(error)
            }
             return Disposables.create()
        }
    }
}
```

If I don't have the line `.take(1)` in the View Model, then in the View Controller, none of the on statements will occur and therefore none of the prints happen. The only on block that works without the `.take(1)` line, is `onError`.

**Comment by kzaher** [comment]
Hi @arjunnaha ,

the reason why "Completed" won't be called without `take(1)` is because `authStatus` isn't completed while `didPressButton` doesn't complete. Please check what is exactly `flatMapLatest` and how it works.
