### ISSUE TITLE
NSTextFieldDelegate's controlTextDidChange() is called regardless of whether it is implemented

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveX/RxSwift#1405]
https://github.com/ReactiveX/RxSwift/blob/60d1d887a2c0a3477154f484f72c3773e0fa3168/RxCocoa/macOS/NSTextField%2BRx.swift#L39-L44

This is an optional method, and as such should probably be:

```swift
public override func controlTextDidChange(_ notification: Notification) {
    let textField: NSTextField = castOrFatalError(notification.object)
    let nextValue = textField.stringValue
    self.textSubject.on(.next(nextValue))
    _forwardToDelegate?.controlTextDidChange?(notification)
}
```

Otherwise, if this method is called on a class that does not implement `controlTextDidChange(…)`, an exception is thrown: `unrecognized selector sent to instance`

**Comment by kzaher** [comment]
Thnx for reporting.
