### ISSUE TITLE
[Feature Request]  simplify DelegateProxy implementation

### ISSUE THREAD

**Issue by beeth0ven** [ReactiveX/RxSwift#1415]
*Short description of missing functionality*:

Hallo! I think we don't need to provide  `currentDelegate` and `setCurrentDelegate` function for `DelegateProxy`  subclass when it's `ParentObject` is `Delegated` by default.

*The reason why I need this functionality*:

We can remove the `currentDelegate` and `setCurrentDelegate` function to simplify implementation.

```swift
open class RxSearchBarDelegateProxy
    : DelegateProxy<UISearchBar, UISearchBarDelegate>
    , DelegateProxyType 
    , UISearchBarDelegate {

    ...

    open class func currentDelegate(for object: ParentObject) -> UISearchBarDelegate? {
        return object.delegate
    }

    open class func setCurrentDelegate(_ delegate: UISearchBarDelegate?, to object: ParentObject) {
        object.delegate = delegate
    }
}
```

*Short code example of how you would like to use the API*:

just let `ParentObject` confirm to  protocol  `Delegated`.

```swift
open class RxSearchBarDelegateProxy
    : DelegateProxy<UISearchBar, UISearchBarDelegate>
    , DelegateProxyType 
    , UISearchBarDelegate {

    ...

//    open class func currentDelegate(for object: ParentObject) -> UISearchBarDelegate? {
//        return object.delegate
//    }
//
//    open class func setCurrentDelegate(_ delegate: UISearchBarDelegate?, to object: ParentObject) {
//        object.delegate = delegate
//    }
}
    
extension UISearchBar: Delegated {
    public typealias Delegate = UISearchBarDelegate
}
```

*Code I have right now*:

We can solve the problem by provide default implementation for function `currentDelegate ` and `setCurrentDelegate` if  `ParentObject` is `Delegated `.

```swift
public protocol Delegated: AnyObject {
    associatedtype Delegate: AnyObject
    var delegate: Delegate? { get set }
}

extension DelegateProxyType where ParentObject: Delegated, ParentObject.Delegate == Delegate {
    
    public static func currentDelegate(for object: ParentObject) -> Delegate? {
        return object.delegate
    }
    
    public static func setCurrentDelegate(_ delegate: Delegate?, to object: ParentObject) {
        object.delegate = delegate
    }
}
```

**RxCocoa version**

 4.0.0-beta.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
  Xcode 9.0
```

**Comment by sergdort** [comment]
I feel like it was implemented in #1379

**Comment by beeth0ven** [comment]
Hi @sergdort! Thank your for reply! And thank you for sharing article about RxSwift again!  Er, #1379 is a great PF. It helps us to avoid using force casting when implement DelegateProxy subclasses. My suggestion is an extension to the PF. This helps us to  avoid implementation of `currentDelegate` and `setCurrentDelegate` if possible in DelegateProxy subclass .

**Comment by tarunon** [comment]
Hi there, 

> I feel like it was implemented in #1379

Actually, I could not work for this issue in #1379.

We use `currentDelegate` and `setCurrentDelegate` in `reset` function.
https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Common/DelegateProxy.swift#L249-L265
If my understanding is correct, it mean`DelegateProxy` should have abstract method that `currentDelegate` and `setCurrentDelegate` for `reset` implementation, so we cannot override it in protocol extension. 

If future swift support [Generalized existentials](https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md#generalized-existentials), we will move `currentDelegate` and `setCurrentDelegate` in `DelegateProxyType` and omit many them implementations.

**Comment by beeth0ven** [comment]
Hi @tarunon, Thank you for optimizing `DelegateProxy`.

Sorry. I did not explain this suggestion clearly, it's my fault.

Because I found some rules for the `Delegated` object:

```swift
class UIScrollView: ... {
    var delegate: UIScrollViewDelegate? { get set }
}

class UISearchBar: ... {
    var delegate: UISearchBarDelegate? { get set }
}

class UISearchController: ... {
    var delegate: UISearchControllerDelegate? { get set }
}

...

```

The rule is a protocol `Delegated `: 

```swift
public protocol Delegated: AnyObject {
    associatedtype Delegate: AnyObject
    var delegate: Delegate? { get set }
}
```

So we can let them confirm to the protocol:

```swift
extension UIScrollView: Delegated {
    public typealias Delegate = UIScrollViewDelegate
}

extension UISearchBar: Delegated {
    public typealias Delegate = UISearchBarDelegate
}

extension UISearchController: Delegated {
    public typealias Delegate = UISearchControllerDelegate
}

...
```

Currently the `DelegateProxy`'s `currentDelegate` and `setCurrentDelegate` function is just the `delegate`'s `get` and `set`:

```swift
open class RxScrollViewDelegateProxy
    : DelegateProxy<UIScrollView, UIScrollViewDelegate>
    , DelegateProxyType ... {

   ...

    open class func setCurrentDelegate(_ delegate: UIScrollViewDelegate?, to object: ParentObject) {
        object.delegate = delegate
    }

    open class func currentDelegate(for object: ParentObject) -> UIScrollViewDelegate? {
        return object.delegate
    }
}

open class RxSearchBarDelegateProxy
    : DelegateProxy<UISearchBar, UISearchBarDelegate>
    , DelegateProxyType ...  {

    ...
    
    open class func currentDelegate(for object: ParentObject) -> UISearchBarDelegate? {
        return object.delegate
    }

    open class func setCurrentDelegate(_ delegate: UISearchBarDelegate?, to object: ParentObject) {
        object.delegate = delegate
    }
}


open class RxSearchControllerDelegateProxy
    : DelegateProxy<UISearchController, UISearchControllerDelegate>
    , DelegateProxyType ... {

    ...

    open class func setCurrentDelegate(_ delegate: UISearchControllerDelegate?, to object: ParentObject) {
        object.delegate = delegate
    }
    
    open class func currentDelegate(for object: ParentObject) -> UISearchControllerDelegate? {
        return object.delegate
    }
}

...
```

So we can optimizing it using protocol extension:

```swift
open class RxScrollViewDelegateProxy
    : DelegateProxy<UIScrollView, UIScrollViewDelegate>
    , DelegateProxyType ... {

   ...
}

open class RxSearchBarDelegateProxy
    : DelegateProxy<UISearchBar, UISearchBarDelegate>
    , DelegateProxyType ...  {

    ...
}


open class RxSearchControllerDelegateProxy
    : DelegateProxy<UISearchController, UISearchControllerDelegate>
    , DelegateProxyType ... {

    ...
}

extension DelegateProxyType where ParentObject: Delegated, ParentObject.Delegate == Delegate {
    
    public static func currentDelegate(for object: ParentObject) -> Delegate? {
        return object.delegate
    }
    
    public static func setCurrentDelegate(_ delegate: Delegate?, to object: ParentObject) {
        object.delegate = delegate
    }
}

...
```

For some special `Delegate` like `UITableViewDataSource` you can still use the original plan:

```swift
open class RxTableViewDataSourceProxy
    : DelegateProxy<UITableView, UITableViewDataSource>
    , DelegateProxyType  ...  {

    ...

    open class func setCurrentDelegate(_ delegate: UITableViewDataSource?, to object: ParentObject) {
        object.dataSource = delegate
    }

    open class func currentDelegate(for object: ParentObject) -> UITableViewDataSource? {
        return object.dataSource
    }
   ...
}
```

If you want to override `currentDelegate` and `setCurrentDelegate ` provide by the protocol extension, you can implement them in `DelegateProxy` subclasses:

```swift

open class RxScrollViewDelegateProxy
    : DelegateProxy<UIScrollView, UIScrollViewDelegate>
    , DelegateProxyType ... {

   ...

    open class func setCurrentDelegate(_ delegate: UIScrollViewDelegate?, to object: ParentObject) {
        object.delegate = delegate
    }

    open class func currentDelegate(for object: ParentObject) -> UIScrollViewDelegate? {
        return object.delegate
    }
}
```

**Comment by tarunon** [comment]
@beeth0ven I'm sorry maybe my explaining was not clearly, plz let me explain again.
There are reasons of cannot implement `currentDelegate` and `setCurrentDelegate` in protocol extension.

1. Cannot cast `DelegateProxy` object to `DelegateProxyType`.
Because `DelegateProxyType` has associatedtype, and swift4 does not support [Generalized existentials](https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md#generalized-existentials).

2. `DelegateProxy` is required abstract methods `currentDelegate` and `setCurrentDelegate`.
There are `reset` method, it uses `currentDelegate` and `setCurrentDelegate`, 
https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Common/DelegateProxy.swift#L249-L265
and we cannot cast `DelegateProxy` to `DelegateProxyType`.

3. Cannot override class method in protocol extension.
Please check this gist, https://gist.github.com/tarunon/d8a6ac7f6b761d342094b0c37384a40b
`DelegateProxy` have abstract `currentDelegate` and `setCurrentDelegate`, and we cannot override them in protocol extension, it mean we must override `currentDelegate` and `setCurrentDelegate` in each DelegateProxy implementations.

**Comment by tarunon** [comment]
I may came up with a good way, I can make new PR if I succeed.
But I think we need more discussions.

**Comment by beeth0ven** [comment]
@tarunon  Thanks for your detailed explanation! 

Yeah. I mean we don't need to cast` DelegateProxy` to `DelegateProxyType `  as  `4.0.0-beta.0` brunch shows:

https://github.com/ReactiveX/RxSwift/blob/rxswift4.0-swift4.0/RxCocoa/Common/DelegateProxy.swift#L221-L230

Because  we get `currentDelegate` and `setCurrentDelegate` function  from `DelegateProxy.init`:

https://github.com/ReactiveX/RxSwift/blob/rxswift4.0-swift4.0/RxCocoa/Common/DelegateProxy.swift#L37-L48

There we can get the function provide by the protocol  `DelegateProxyType`, So when we register known implementations:

https://github.com/ReactiveX/RxSwift/blob/rxswift4.0-swift4.0/RxCocoa/iOS/Proxies/RxScrollViewDelegateProxy.swift#L32-L37

The `currentDelegate` and `setCurrentDelegate` function provided by protocol extension has been inject to `DelegateProxy` if the `ParentObject` is `Delegated`.

I'm glad to see your next PR 🙂.

**Comment by beeth0ven** [comment]
Hi @tarunon I see your PR. That's awesome!

I think protocol extension method can be override by children:

![2017-09-21 3 54 37](https://user-images.githubusercontent.com/5554127/30684813-4430cf76-9ee5-11e7-860e-eeb83d96ecf6.png)

As [The Swift Programming Language](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html#//apple_ref/doc/uid/TP40014097-CH25-ID267) said:

>You can use protocol extensions to provide a default implementation to any method or computed property requirement of that protocol. If a conforming type provides its own implementation of a required method or property, that implementation will be used instead of the one provided by the extension.

So don't worry! we can override `currentDelegate` and `setCurrentDelegate`.

**Comment by tarunon** [comment]
@beeth0ven I just worry that [this problem](https://bugs.swift.org/browse/SR-103) that I've reported. 
I omitted every implementations from DelegateProxy, so now, I cannot override these methods in subclasses.

**Comment by kzaher** [comment]
Hi,

@tarunon I've improved delegate proxies in 4.0/beta.0 a bit so that technically what @beeth0ven is suggesting is possible because delegate setters and getters aren't being overriding isn't 

> Hallo! I think we don't need to provide currentDelegate and setCurrentDelegate function for DelegateProxy subclass when it's ParentObject is Delegated by default.

@beeth0ven Is `Delegated` some Cocoa protocol, because I don't see it. Are you proposing that we add another protocol to RxCocoa? Doing that would be problematic because that approach would limit us to single delegate per delegate owner.

**Comment by beeth0ven** [comment]
Hi @kzaher. 

En, the `Delegated` protocol is'n available in Cocoa. Yeah, I'm proposing we can add it to RxCocoa.

For most `Delegate` like: 
* `UIScrollViewDelegate`
* `UISearchBarDelegate`
* `UINavigationControllerDelegate`
* `UIPickerViewDelegate`
* `CLLocationManagerDelegate`
* ...

We can provide default implementation for `DelegateProxyType` where the `ParentObject` is `Delegated`.

For some special **"Delegate"** which has been standardized like:
* `UITableViewDataSource`
* `UICollectionViewDataSource`
* `UIPickerViewDataSource`
*  ...

We can add another protocol for example: `HasDataSource` as the PR #1417 shows.

If the **"Delegate"** is Non-standardized we can still use original plan.

---

For example if the `TableView` has three **"Delegate"**:

```swift
class TableView: .. {
    var delegate: TableViewDelegate? { get set }
    var dataSource: TableViewDataSource? { get set }
    var customDelegate: CustomTableViewDelegate? { get set }
}
```

We can let `TableView` confirm to `Delegated` and `HasDataSource` protocol:

```swift
extension TableView: Delegated {
    public typealias Delegate = TableViewDelegate
}

extension TableView: HasDataSource {
    public typealias DataSource = TableViewDataSource
}
``` 

Those TableView `DelegateProxy` subclasses will inherit the corresponding method from protocol extension:

```swift
// inherit setCurrentDelegate and currentDelegate function form DelegateProxyType where the ParentObject is Delegated
open class RxTableViewDelegateProxy
    : DelegateProxy<TableView, TableViewDelegate>
    , DelegateProxyType 
    , TableViewDelegate {
    ...
}

// inherit setCurrentDelegate and currentDelegate function form DelegateProxyType where the ParentObject is HasDataSource
open class RxTableViewDataSourceProxy
    : DelegateProxy<TableView, TableViewDataSource >
    , DelegateProxyType 
    , TableViewDataSource {
    ...
}
```

For Non-standardized **"Delegate"** we can still use original plan:

```swift
// Can't inherit setCurrentDelegate and currentDelegate function form DelegateProxyType so we must provide them.
open class RxCustomTableViewDelegate Proxy
    : DelegateProxy<TableView, CustomTableViewDelegate>
    , DelegateProxyType 
    , TableViewDataSource {

     open class func setCurrentDelegate(_ delegate: CustomTableViewDelegate?, to object: ParentObject) {
        object.customDelegate = delegate
    }

    open class func currentDelegate(for object: ParentObject) -> CustomTableViewDelegate? {
        return object.customDelegate
    }
    ...
}
```

**Comment by kzaher** [comment]
We've merge the PR.

**Comment by beeth0ven** [comment]
Thanks @kzaher @tarunon.
