### ISSUE TITLE
ObservableType.subscribe(...) #if DEBUG causing problems with pre-compiled frameworks

### ISSUE THREAD

**Issue by asutula** [ReactiveX/RxSwift#1416]
**Short description of the issue**:

I build a distribute a pre-compiled Swift framework that depends on RxSwift. That framework uses the `ObservableType.subscribe(...)` function, of which there are two versions wrapped in a `#if DEBUG #else #endif` (see the [RxSwift source here](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/ObservableType%2BExtensions.swift#L24)). My framework is built using the Release configuration, so the compiled binary is expecting the release version of the `ObservableType.subscribe(...)` function from RxSwift. 

When using my framework in a project that builds other dependencies from source code (Cocoapods, for example), and running a Debug build, there is a runtime crash that happens when my framework calls `ObservableType.subscribe(...)` because it is the Debug version of `ObservableType.subscribe(...)` that is compiled and that doesn't match with the Release version my pre-compiled binary Framework is looking for.

If I use pre-compiled versions of RxSwift (using Carthage, or manually downloading a release from Github), the problem goes away because there is now just the Release version of `ObservableType.subscribe(...)` and it is consistent with what my framework was compiled with.

I see that the two different versions of the `ObservableType.subscribe(...)` function have existed since last summer, and this didn't seem to be a problem with older versions of Cocoapods (Cocoapods 1.2.0 was the last one that didn't seem associated with this issue). I'm not sure if this is strictly and issue with RxSwift, or strictly an issue with Cocoapods, or somewhere in between, but the underlying issue is clear.

**Expected outcome**:

 I expect my pre-compiled framework to be able to call `ObservableType.subscribe(...)` for both Debug and Release builds.

**What actually happens**:

There is a runtime crash where `ObservableType.subscribe(...)` is not found for Debug builds:
```
dyld: lazy symbol binding failed: Symbol not found: __TIFE7RxSwiftPS_14ObservableType9subscribeFT6onNextGSqFwx1ET__7onErrorGSqFPs5Error_T__11onCompletedGSqFT_T__10onDisposedGSqFT_T___PS_10Disposable_A1_
Referenced from: /Users/aaron/Library/Developer/CoreSimulator/Devices/335F6B8A-0CBC-406D-9559-5718D4910F5A/data/Containers/Bundle/Application/7B0C8A9A-44E6-4EE1-A3E6-87BFF84273BA/DeLaCasa.app/Frameworks/Set.framework/Set
Expected in: /Users/aaron/Library/Developer/CoreSimulator/Devices/335F6B8A-0CBC-406D-9559-5718D4910F5A/data/Containers/Bundle/Application/7B0C8A9A-44E6-4EE1-A3E6-87BFF84273BA/DeLaCasa.app/Frameworks/RxSwift.framework/RxSwift
```

**Self contained code example that reproduces the issue**:

1. Clone this project that depends on my pre-compiled framework and RxSwift: [https://gitlab.com/weareset/DeLaCasa.git](https://gitlab.com/weareset/DeLaCasa.git)
2. Check out the `feature-update-pods` branch.
3. Open the workspace.
4. Change the team id to a team of yours.
5. Run the app (in Debug by default), see the crash.
6. Edit the scheme and change Run to use Release.
7. Run the app and see it work.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version 8.3.3
```

**Installation method**:
  - [x] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @asutula,

It seems to me that you are doing dependency management in an invalid way.

You can't mix Carthage and CocoaPods dependencies safely.

Consider this case:
* Carthage could for some reason pick RxSwift 3.6.2 and compile your library against that version
* you would include your library that depends on some RxSwift 3.6.2 APIs
* then CocoaPods dependency resolution could pick 3.5.0 that lacks those APIs and you would still get a missing API linker crash

Unless CocoaPods and Carthage specify they are compatible, you can't mix two different independent dependency resolution algorithms and expect everything to work.

I would suggest that if you are using them in the same project then make sure dependencies are completely separate.

**Comment by asutula** [comment]
Thanks for the reply @kzaher. That's not the case. I'm not mixing Carthage and Cocoapods. I was just pointing out that the issue I'm describing is only when someone uses Cocoapods to build a project that depends on my framework. If they instead use Carthage or any other way of linking pre-compiled frameworks to their project, it's fine.

Just to clarity the main points with my issue:

- I maintain a framework called SetSDK. I can't distribute it's source code, so I distribute it already compiled.
- SetSDK depends on RxSwift
- When I build my framework for distribution, I do a Release build, which compiles against one version of `ObservableType.subscribe(...)` (the one without the file, function, and line number parameters)
- I use Cocoapods to distribute my already-compiled framework
- The SetSDK podspec specifies the dependency on the correct version of RxSwift
- When someone integrates SetSDK into their project using Cocoapods and then performs a Debug build (by Running the app from Xcode, for example), there is a runtime crash because it's now the Debug version of `ObservableType.subscribe(...)` (with the file, function, and line number parameters) that was compiled from RxSwift (because of the #if DEBUG #else code in RxSwift I mentioned), but the SetSDK was compiled as Release using the other version of `ObservableType.subscribe(...)` and is calling that version which now doesn't exist.
- If the person integrating SetSDK using Cocoapods performs a Release build, things work fine because the version of `ObservableType.subscribe(...)` is consistent between what was used when compiling SetSDK and when compiling the app and RxSwift after integrating SetSDK using Cocoapods.

**Comment by kzaher** [comment]
Hi @asutula ,

could you please explain how does this conceptually differ from my previous response?

I was trying to construct an example that demonstrates that what you are describing isn't an issue with `subscribe` method being different in release and debug configurations, but a more general problem of using dependency managers in an unsupported way.

If you want to hack your problem this way you can always create your own subscribeXXX convenience method inside your library that is configuration independent, but I wouldn't recommend doing it that way because the real issue that you have is using two different dependency managers and two separate code resolution logics that could break in any number of ways. 

This "problem" you have reported is just a tip of the iceberg.

**Comment by asutula** [comment]
What I'm taking from this is that distributing a binary framework with dependencies is a bad idea, especially when those dependencies are resolved and compiled in a dynamic way. I agree with that. We can close this issue.

**Comment by Vladlex** [comment]
I'm sorry, but I think the problem is deeper.

Logically, it's ok to have different implementation for methods, but it's not ok when you declare two methods with different signatures for different schemes, but which only looks like the same method when typing it using SwiftRx framework.

It's better to leave a full-list argument signature (with `file`, `line` and so on) without `#if debug` checks, but separate implementation to debug and non-debug parts and just don't use debug-needed arguments in non-debug part.

IMHO.

**Comment by asutula** [comment]
Nice, I like that.
