### ISSUE TITLE
Wrong description for Variable in Docs

### ISSUE THREAD

**Issue by dakeshi** [ReactiveX/RxSwift#1426]
I think that [the description about `Variable`](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#variables) could make confusion. 

> so variable can never terminate or fail.

It should be `never terminate with errors` to make clear. Refer to [source code comments](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Subjects/Variable.swift#L11)

**Comment by kzaher** [comment]
Hi @dakeshi ,

thnx for reporting, should be ok now.
