### ISSUE TITLE
use addDisposableTo method can not make a warning

### ISSUE THREAD

**Issue by dakeshi** [ReactiveX/RxSwift#1427]
**Short description of the issue**:
When I search some tutorials about RxSwift, I find out so many sample codes still use deprecated `addDisposableTo` method instead of `disposed(by:)`. I think that the main reason is a missing warning message.

Deprecated `addDisposableTo` method can not make a warning during a build time. To show a warning and avoid an old method, it need to comment out in `Deprecated.swift`.

>     /// **@available(\*, deprecated, message="use disposed(by:) instead")** 

Um. it is not the correct statement. It should be:

>  @available(*, deprecated, message: "use disposed(by:) instead") 

**Expected outcome**:

show a warning to avoid to use deprecated method 

**What actually happens**:

no warning.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.0
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @dakeshi ,

Thnx for reporting this. We haven't been able to deprecate this for 3.x release, but we've deprecated it now in 4.x.
