### ISSUE TITLE
Can public of functions?

### ISSUE THREAD

**Issue by KyoheiG3** [ReactiveX/RxSwift#143]
Hi,

I want to use the following function.
```
func rx_createDelegateProxy() -> RxScrollViewDelegateProxy {
    return RxScrollViewDelegateProxy(parentObject: self)
}
```
https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UIScrollView%2BRx.swift#L22-L24

Do you have plans to publish?

**Comment by kzaher** [comment]
Hi @KyoheiG3 ,

you are correct, this was an oversight on my end. 

It should be public to enable delegate/dataSource extending.

**Comment by KyoheiG3** [comment]
Expect a awesome correction :)

**Comment by kzaher** [comment]
I am looking at the code,

I think I'll need to expose some other things also :)

**Comment by KyoheiG3** [comment]
I think at least subclasses of `DelegateProxy` is necessary likely.

**Comment by kzaher** [comment]
This was just released. Please let me know if we need to reopen it or if there are some additional problems.

**Comment by KyoheiG3** [comment]
Thanks you. awesome framework!!
