### ISSUE TITLE
RxMotion.sharedInstance.motion cyclic issue

### ISSUE THREAD

**Issue by grinder81** [ReactiveX/RxSwift#1434]
**Short description of the issue**:

`RxMotion.sharedInstance.motion` seems have a cyclic issue.

**Expected outcome**:
  `RxMotion.sharedInstance.motion
.observeOn(MainScheduler.instance)
.subscribe(onNext: { motion in
print(motion)
})
.addDisposableTo(rx.disposeBag)`
This code should just work and print motion data.

**What actually happens**:
Getting this:
 :warning: Synchronization anomaly was detected. :warning:
  > Debugging: To debug this issue you can set a breakpoint in Rx.swift:113 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
   This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: Two different unsynchronized threads are trying to send some event simultaneously.
    This is undefined behavior because the ordering of the effects caused by these events is nondeterministic and depends on the
    operating system thread scheduler. This will result in a random behavior of your program.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
   or by synchronizing sequence events in some other way.

**Self contained code example that reproduces the issue**:

```
RxMotion.sharedInstance.motion
.observeOn(MainScheduler.instance)
.subscribe(onNext: { motion in
  print(motion)
})
.addDisposableTo(rx.disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.x latest 

**Platform/Environment**

  -  iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - easy, 100% repro

**Xcode version**:

```
  Version 9.0 (9A235)
```

**Installation method**:
  - CocoaPods
  
**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  -  yes (7,8 and 9)

**Comment by kzaher** [comment]
Hi @grinder81 ,

I think this is a wrong repo to report this. This repo doesn't contain any types named `RxMotion`.
