### ISSUE TITLE
.ignoreElements() Change return type

### ISSUE THREAD

**Issue by gorozco58** [ReactiveX/RxSwift#1436]
**Description**:

I am trying to use `.ignoreElements()` method due to I have a method returning a `Observable<Type>`and I wanna transform this into `Completable` trait but `.ignoreElements()` return  `RxSwift.Observable<Self.E>`. 

**Expected outcome**:

I have been looking for another Rx implementations and this method return `Completable`.
I think this make sense because I just want `onComplete` or `onError` event .

**What actually happens**:

The method is currently returning `RxSwift.Observable<Self.E>`. 

**Java Implementation**:

This is the Java implementation.

```java
/**
     * Ignores all items emitted by the source ObservableSource and only calls {@code onComplete} or {@code onError}.
     * <p>
     * <img width="640" height="305" src="https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/ignoreElements.2.png" alt="">
     * <dl>
     *  <dt><b>Scheduler:</b></dt>
     *  <dd>{@code ignoreElements} does not operate by default on a particular {@link Scheduler}.</dd>
     * </dl>
     *
     * @return the new Completable instance
     * @see <a href="http://reactivex.io/documentation/operators/ignoreelements.html">ReactiveX operators documentation: IgnoreElements</a>
     */
    @CheckReturnValue
    @SchedulerSupport(SchedulerSupport.NONE)
    public final Completable ignoreElements() {
        return RxJavaPlugins.onAssembly(new ObservableIgnoreElementsCompletable<T>(this));
    }
```

**Comment by kzaher** [comment]
Hi @gorozco58 ,

yes, I think we can change the return type now.

**Comment by kzaher** [comment]
This should be fixed now.
