### ISSUE TITLE
Slack signup token issue

### ISSUE THREAD

**Issue by slangley** [ReactiveX/RxSwift#144]
I was trying to sign up to the Slack channel, but I'm getting the message below about 'Missing admin scope: The token you...'

This was after entering email address and pressing Get My Invite on rxswift.slack.com (I removed my address before taking the screenshot)

Sorry if this is the wrong place to post, but didn't know where else to let you guys know.

<img width="418" alt="screenshot 2015-09-19 15 26 44" src="https://cloud.githubusercontent.com/assets/153313/9977838/46c1763a-5ee3-11e5-8b54-f1f14e57311e.png">

**Comment by kzaher** [comment]
@slangley thnx for reporting this :+1:. I have no idea why this is happening :)

Maybe @bontoJR knows more. I'll also take a look.

**Comment by bontoJR** [comment]
It seems to be a problem on Slack side. The token is valid, but the API returns an error, I reported to Slack, let's see.

**Comment by bontoJR** [comment]
Thanks for reporting, solved!

The problem is that API tokens to invite people can't be anymore created by the channel's owner, but they only work with users with admin privileges.
