### ISSUE TITLE
Application is crashing when I tried to integrate Rx with Carthage

### ISSUE THREAD

**Issue by rohitnewscorp** [ReactiveX/RxSwift#1453]
**Short description of the issue**:

When I integrated the RxSwift framework with the Carthage I am not able to run the app and App is getting crashed and giving me logs 

dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/rsharma6/Library/Developer/CoreSimulator/Devices/E2E9C69F-BF78-4271-88EA-FA9CC1E76EAF/data/Containers/Bundle/Application/E567E38D-F3DC-4699-A611-968B6DAF5127/CarthageDemo.app/CarthageDemo
  Reason: image not found

**Expected outcome**:

 It should work fine as It is smooth with the pods 

**What actually happens**:

 I integrate Rxswift framework with the carthage It is giving me the issue 

dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/rsharma6/Library/Developer/CoreSimulator/Devices/E2E9C69F-BF78-4271-88EA-FA9CC1E76EAF/data/Containers/Bundle/Application/E567E38D-F3DC-4699-A611-968B6DAF5127/CarthageDemo.app/CarthageDemo
  Reason: image not found

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:
9.0
```
  Xcode version goes here
```
**Installation method**:
  - [ ] Carthage

**I have multiple versions of Xcode installed**:
  - [ ] no

**Level of RxSwift knowledge**:
  - [ ] just starting

**Comment by tarunon** [comment]
Don't you forgot `carthage copy-framewroks`?

**Comment by rohitnewscorp** [comment]
@tarunon  I have already copy frame work!!

**Comment by tarunon** [comment]
Sorry It was my misunderstanding see `Reason: image not found`
I never see `.framework/RxSwift` while using RxSwift and carthage, If my understanding is collect, `@rpath/RxSwift.framework/RxSwift` is ok.

I can see this error message when I forgot `carthage copy-frameworks` .
```sh
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/tarunon/Library/Developer/CoreSimulator/Devices/9FBFAB61-84A8-427D-9C7D-7006301E7110/data/Containers/Bundle/Application/5F9BA77D-6AF4-4FC7-AD6F-9EAA22D09E8E/Test.app/Test
  Reason: image not found
```

**Comment by kzaher** [comment]
Have no idea about this one, and can't repro it.

¯\\\_(ツ)\_/¯
