### ISSUE TITLE
UITextField can not observe when setting text to UITextField

### ISSUE THREAD

**Issue by nguyentuanvu90** [ReactiveX/RxSwift#1462]
[titleTextField.rx.text.subscribe(onNext: { text in
            self.validateTitleLabel.text = String(text?.characters.count ?? 0) + LocalizedString.titleCount.string
        }).disposed(by: disposeBag)](url)

titleTextField.text = "Vunt"
when I set text doesn't call to subscribe

**Comment by dangthaison91** [comment]
@nguyentuanvu90 It is expected behavior to avoid reentrancy. You can set text manual so you can control logic too.
