### ISSUE TITLE
Application is crashing with RxSwift4 + Cocoapods

### ISSUE THREAD

**Issue by orakaro** [ReactiveX/RxSwift#1463]
**Short description of the issue**:

Cocoapods installed RxSwift/RxCocoa crash on every ViewController by [DataSource is already set error](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Common/DelegateProxyType.swift#L206).

**Expected outcome**:
Application should run without crash

**What actually happens**:
We have a fairy large project using RxSwift till version 2.x. Recently I tried to switch from Carthage to Cocoapods and realize that every viewController crashed with above error. DataSource is *not* set in either Storyboard or code before binding. 

I am unsure this is related to #675 or not.

I created a fresh new project which easily reproducing this problem (see below). The weird thing is, same code works if RxSwift is integrated with Carthage

**Self contained code example that reproduces the issue**:
https://github.com/orakaro/Experiment (Xcode9/Swift4/RxSwift4)
  
**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.0.0

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
9.0.1
```

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @orakaro ,

<img width="791" alt="screen shot 2017-10-20 at 10 02 38" src="https://user-images.githubusercontent.com/1641148/31810913-dc8328ba-b57d-11e7-865f-07bd4c200221.png">

I have no idea what is `Optional(<_UIFilteredDataSource: 0x60400005eb40>)`.

Carthage is probably not crashing because it's using Release build that has assert lines ignored.

**Comment by orakaro** [comment]
@kzaher Your are right! Changing the RxSwift/RxCocoa Optimization level did the trick 👍 
<img width="1224" alt="screen shot 2017-10-20 at 17 29 35" src="https://user-images.githubusercontent.com/479796/31811927-49547bcc-b5bc-11e7-8257-d372f9fd59d5.png">

But I still have no idea where is that `_UIFilteredDataSource ` come from 😓

**Comment by REKURDennis** [comment]
The DataSource of the tableView of a UITableViewController is the TableViewController by default. Setting the dataSource explicitly to nil solves your problem without changing the optimisation level.

Btw.: On my machine Xcode crashes entirely and I don't see the "Datasource is already set" error.

`override func viewDidLoad() {
        tableView.dataSource = nil
        let upstreamData: Driver<[Int]> = Driver.of([1,2,3,4,5,6,7,8,9])
        
        // Following code is need for Cocoapods
        // tableView.dataSource = nil
        upstreamData
            .drive(tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
        
        super.viewDidLoad()
    }`
