### ISSUE TITLE
Documentation on cocoadocs.org

### ISSUE THREAD

**Issue by dev4dev** [ReactiveX/RxSwift#1471]
Hello, I'm not sure that here is the right place to address this issue, but maybe somebody will help.

I like to use Dash app for searching documentation, it allows you to install docs for pods. Unfortunately the latest usable version of RxSwift docs was for 3.5.0 version http://cocoadocs.org/docsets/RxSwift/3.5.0/.

4.0.0 is stripped down to nothing http://cocoadocs.org/docsets/RxSwift/4.0.0/, like some leftovers.
Can it be fixed somehow?

Thanks.

**Comment by kzaher** [comment]
Hi,
I think they depend on jazzy. Have no idea what's the plan to support 4.0 and are cocoadocs maintained anymore.

**Comment by LanceFu** [comment]
Like @dev4dev already mentioned, I am using Dash as well and was searching for documentation for RxSwift 4.0.0. Can we expect one at some point? If so, when?

**Comment by kzaher** [comment]
@LanceFu https://github.com/CocoaPods/cocoadocs.org/issues/549

https://github.com/CocoaPods/cocoadocs.org/issues/549#issuecomment-339954839

**Comment by kzaher** [comment]
Since this is not something on our end, I'm closing this issue.

**Comment by zvonicek** [comment]
@dev4dev @LanceFu 
I managed to build RxSwift 4.1.2 docs with Jazzy and published it to Dash, so you can get it there.

![snimek obrazovky 2018-05-09 v 8 50 42](https://user-images.githubusercontent.com/1540564/39827889-9838cd88-53b9-11e8-9131-52b7dd37a8bb.png)

**Comment by dev4dev** [comment]
@zvonicek hey, that's great idea, thanks!

**Comment by vietstone** [comment]
it's nice @zvonicek Thank you

**Comment by scalbatty** [comment]
This is great!

Is there any way we can keep the docs up to date? 
I've tried running Jazzy after the config update script and had very mixed results. Maybe the docs on the https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/RxSwift page could be enriched with the actual command or a script that generates the new docs?

Thanks!
