### ISSUE TITLE
Crash when convert Double to Int

### ISSUE THREAD

**Issue by dangthaison91** [ReactiveX/RxSwift#1472]
**Short description of the issue**:

**Expected outcome**:

**What actually happens**:

Stacktrace point to: `DispatchQueueConfiguration.swift`

```
interval	TimeInterval	30875491.331709981
fatal error: Double value cannot be converted to Int because the result would be greater than Int.max

DispatchQueueConfiguration.swift - Line 21: return DispatchTimeInterval.milliseconds(Int(interval * 1000.0))
```
```swift
 var shouldExpireBefore: TimeInterval { //... }
 var willExpireAt: TimeInterval {
        return expiryDate?.timeIntervalSinceNow ?? 0
    }
    
    var expiresSoon: Observable<Void> {
        let expiresSoonAt = willExpireAt - shouldExpireBefore
        
        guard expiresSoonAt > 0 else {
            return .just(()) // fire now if it expiresSoonAlready
        }
        
        return Observable<Int>.timer(expiresSoonAt, scheduler: MainScheduler.instance).map { _ in }
    }
  ```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 9.0
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by minuscorp** [comment]
I think this is just an issue that you're excceding Int value, which depending of the device's architecture, it can be of 32 or 64 bit length. You can use a safe version of the crashing line using `Int.init(exactly:)` and either `round` or `floor` to avoid losing the conversion due to the decimal part of the numer.

```swift
return Observable<Int>.timer((Int(exactly: floor(expiresSoonAt)) ?? Int.max), scheduler: MainScheduler.instance).map { _ in }
```

**Comment by dangthaison91** [comment]
@minuscorp Thanks, but it didn't work. I have to workaround with: `let interval = min(Int.max/1000, expiresSoonAt)`

**Comment by kzaher** [comment]
We can add versions that take `DispatchTimeInterval`, so that should solve these kinds of issues.

**Comment by kzaher** [comment]
This should not be even theoretically possible. We've refactored schedulers in 5.0 to take dispatch interval directly.
