### ISSUE TITLE
Xcode 9 with Swift 4 "Extra argument in call"

### ISSUE THREAD

**Issue by DennisMostajo** [ReactiveX/RxSwift#1473]
I was using XCode 8.3 with swift 3.1 and I updated to Xcode 9 with swift 4, now in some classes when I use RXSwift, I have this error compiler logs:
```
class petViewModel {
    var lastPetID: Int = 0
    var refreshing = Variable<Bool>(false)
    var vaccines: Results<vaccines>? = nil
    let error = Variable<(Int,String)>(0,"") // Extra argument in call
    let changes = Variable<([Int], [Int], [Int])>([Int](), [Int](), [Int]())  // Extra argument in call
    var firstLoad = Variable<Bool>(false)

    // and more code bla bla bla

}
```
using RXSwift what is the best way to implement it? before was compiling me without any problem, any help, please?

I did tried:
```
let change1 = Variable<[Int]>([Int]())
let change2 = Variable<[Int]>([Int]())
let change3 = Variable<[Int]>([Int]())

let changes = Observable.combineLatest(change1.asObservable(), change2.asObservable(), change3.asObservable())
```
but now is show me a compiler error: "Cannot use instance member 'change1' within property initializer; property initializers run before 'self' is available"

**Comment by biboran** [comment]
@DennisMostajo the issue is that swift 4.0 currently [doesn't support](https://medium.com/xebia/breaking-changes-in-swift-4-cc90b63b5f87) tuple transformations. 

Your `Variable` is not compiling because you declared it as a tuple and pass it as a variadic parameter. Just wrap it into a tuple:
```swift
let changes = Variable<([Int], [Int], [Int])>(
  ( // <-- this is a tuple you are missing
    [Int](), 
    [Int](), 
    [Int]()
  ) // <-- this is a tuple you are missing
)
```

as for your `combineLatest` your have to wrap the argument into a collection (using a literal for example)

```swift
Observable.combineLatest([
  change1.asObservable(), 
  change2.asObservable(), 
  change3.asObservable()
])
```

**Comment by DennisMostajo** [comment]
thank you very much for your answer @biboran , I could update the syntax, issue resolved, your kung fu is the best!! \o/
