### ISSUE TITLE
CocoaPods podspec validation fails after updating pod to RxSwift 4.0.0

### ISSUE THREAD

**Issue by pixeldock** [ReactiveX/RxSwift#1474]
**Short description of the issue**:

  After updating my pod to RxSwift 4.0.0 the podspec validation fails with a warning.

**Expected outcome**:

 Podspec validation should pass without warning.

**What actually happens**:

 After running `pod lib lint` the validation fails with the following output:

```
Validating podspec
 -> RxAppState (0.4.0)
    - WARN  | xcodebuild:  RxSwift/RxSwift/SwiftSupport/SwiftSupport.swift:25:18: warning: overlapping accesses to 'self', but modification requires exclusive access; consider calling MutableCollection.swapAt(_:_:)
    - NOTE  | xcodebuild:  RxSwift/RxSwift/SwiftSupport/SwiftSupport.swift:25:28: note: conflicting access is here
```

**Self contained code example that reproduces the issue**:

You can checkout my pod's current master at https://github.com/pixeldock/RxAppState

Run `pod lib lint` to reproduce the issue.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 RxSwift release version 4.0.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  9.0.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (9.0.1 and 9.1.0 beta)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi,
https://github.com/pixeldock/RxAppState/blob/master/.swift-version should be 4.0

**Comment by pixeldock** [comment]
Thanks a lot!
