### ISSUE TITLE
very weird wrong error (swift bug?)

### ISSUE THREAD

**Issue by pvinis** [ReactiveX/RxSwift#1477]
**Short description of the issue**:

  there is a weird error happening in this code. when i try to multiply an `Int` and a `CGFloat` and assign it to a `CGFloat`, i get an error that the binary operator `*` is not working there. that is a correct error. but when i do the same as the first line in a `subscribe` `onNext:` block, then instead of that error, i get a `extraneous argument onNext`.
  correct error
<img width="940" alt="correct-error" src="https://user-images.githubusercontent.com/100233/32131845-91b9ef08-bbb8-11e7-9021-4fff5f2ea043.png">
  wrong error
<img width="925" alt="wrong-error" src="https://user-images.githubusercontent.com/100233/32131848-a055b3ee-bbb8-11e7-8cc9-70ed2534d269.png">

**Expected outcome**:

  i should be getting the same operator `*` error, whether its the first line in the block or not.

**What actually happens**:

  i get a different error, one thats not related to the actual error.

**Self contained code example that reproduces the issue**:

```swift
  let i: Int = 3
  let f: CGFloat = 4.0
  var o: CGFloat
  Observable.just("test")
    .subscribe(onNext: { s in
      o = i * f
    })
    .disposed(by: DisposeBag())
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.0.0

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  9.0.1 (9A1004)
```

**Installation method**:
  - [ ] CocoaPods
  - [X] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @pvinis ,

This is compile time error `o = i * f` because Swift doesn't support automatic type conversions and so is this `var o: CGFloat` since compiler can't prove `o` is initialized in scope.

The weird error you are seeing is just a consequence of first error, so this is Swift compiler inconvenience. Yes, we've hit this often and it's irritating. 

¯\\\_(ツ)\_/¯

**Comment by pvinis** [comment]
i have reported it here https://bugs.swift.org/browse/SR-6246

**Comment by carlosypunto** [comment]
@pvinis, it should be: `o = CGFloat(i) * f` and there isn't error, as well Kruno told you

**Comment by pvinis** [comment]
well yes I understand that. it's still a swift bug. so I kept this issue closed and I just linked the issue over there for future reference and for anyone interested.

**Comment by garritfra** [comment]
Old issue, but [this](https://stackoverflow.com/a/48303519/9046809) thread solved it for me. basically you have add the `onError:` closure, and the compiler will point out the correct error message.
```swift
  let i: Int = 3
  let f: CGFloat = 4.0
  var o: CGFloat
  Observable.just("test")
    .subscribe(
      onNext: { s in o = i * f },
      onError: nil
    ).disposed(by: DisposeBag())
```
