### ISSUE TITLE
Problem with RxSwift in Framework

### ISSUE THREAD

**Issue by encisek** [ReactiveX/RxSwift#1479]
Hi!
I build framework, first new projekt when i test my application - all be ok.
Next step i try build in SDK (framework) packade and add this to my projekt and...
There is a problem... set scheme on build - OK, when I try set scheme on release my SDK crash on: 
onDisposed: {}).addDisposableTo(disposeBag)

I dont know why my projekt test its ok, but when i try add it to SDK in release is CRASH ;/

Maybe someone had a similar problem.
RxSwift 3.6.1 - on SDK, project test and application when i add package SDK.

Thanks for help! :)

Edit: 
When setting up a SDK project configuration on debug - it only works on debug configuration (when release is crash related to RxSwift) when the project is setup as release and throws into the package it works only at release configuration (on debug is crash associated with RxSwift).
I want to build one package which will support release and debug.

**Comment by kzaher** [comment]
Hi @encisek ,

I have a bit of problem understanding your correct issue. It might be related with different subscription call signatures for debug and release versions.

We've changed that in 4.0 so you might check out that version instead.

**Comment by encisek** [comment]
Update RxSwift to 4.0 and configuration change in the project has fixed the problem. 
Thanks ;)
