### ISSUE TITLE
RxBlocking & RxTest does't work well with PublishSubject

### ISSUE THREAD

**Issue by huy-le** [ReactiveX/RxSwift#1480]
**Short description of the issue**:

  I'd like to test a PublishSubject to know how many events it published. However, the RxBlocking & RxTest doesn't help. It always returns nil.

**Expected outcome**:

  result.count > 0

**What actually happens**:

  result.count == 0

**Self contained code example that reproduces the issue**:

```swift
    func testPublishSubject() {
        let subject = PublishSubject<String>()
        subject.onNext("Abc")
        subject.onCompleted()
        do {
            let result = try subject.toBlocking().toArray()
            XCTAssert(result.count == 1)
        } catch {
            // Ignore
        }
    }

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  XCode 9.0
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by biboran** [comment]
I think that is expected because `PublishSubject` doesn't replay events. I don't think you can test `PublishSubject` with RxBlocking directly. You can see how it's tested [here](https://github.com/ReactiveX/RxSwift/blob/0b66f666ba6955a51cba1ad530311b030fa4db9c/Tests/RxSwiftTests/Observable%2BSubscriptionTest.swift).

**Comment by huy-le** [comment]
@biboran Thanks, I thought that it behaves same.
