### ISSUE TITLE
xcode9.1 code completion

### ISSUE THREAD

**Issue by jacknathan** [ReactiveX/RxSwift#1482]
my xcode version is 9.1 when i input "let valid = mobileView.textField.rx.text.", i cannot receive any code completion suggestion?

**Comment by kzaher** [comment]
Hi @jacknathan ,

oh damn it. I think compiler team messed up something.

If you do `mobileView.textField.rx.text.asDriver()` or `mobileView.textField.rx.text.asObservable()` or `mobileView.textField.rx.text.map { $0 }` it works fine.

If you have time it would be great to report this to compiler team. 

I have some more pressing issues I need to tackle first, so I doubt I'll have time to investigate this one soon.

**Comment by kzaher** [comment]
Especially since this bug isn't ours :(

**Comment by carlosypunto** [comment]
in case it helps. This is happening only with components with ControlProperty<AnOptionalType>, that is: ControlProperty<String?> and ControlProperty<NSAttributedString?>. And in my case it happens with and without the assignment

**Comment by mheras** [comment]
Hi! Any update on this? It's really unpleasant to code without IDE completion. This also happens with AppCode.

If this is an issue from the Apple's compiler team, could anyone please share the link so we can see how it is progressing?

Thank you.

**Comment by kzaher** [comment]
Hi guys,

I don't know why Xcode autocomplete is flaky, the temporary solution is quite simple **just add `asObservable` or `asDriver`**.

`mobileView.textField.rx.text.asObservable()`

**Comment by kchlebus** [comment]
Hi,
that issue still occurs on Xcode 10. Adding `asObservable` or `asDriver` helps as you wrote, but it's not ideal solution... I've noticed that it working correctly when I integrate RxCocoa using Carthage, not CocoaPods. So maybe it's related to CocoaPods then?

**Comment by piin** [comment]
I have this issue in Xcode 10.1, any updates?

**Comment by freak4pc** [comment]
I don't think it's anything related to the codebase as much as it is related to Xcode and Swift. We can't really spend project time correcting Apple's issues unfortunately :) 

They've made a stress tester for Swift and I've filed a few radars related to it but these things take a long time, I wouldn't count it being resolved anytime soon.

**Comment by RaoulNL** [comment]
Sure takes a long time... since the issuer started this issue in November 2017...

**Comment by JadianZheng** [comment]
Oops, still not wok at Xcode 13

**Comment by freak4pc** [comment]
@JadianZheng no reason to bump a 2.5 years old issue.

My answer still stands, auto-complete is related to Apple and not RxSwift specifically :)
