### ISSUE TITLE
[Feature Request] : Buffer without TimeSpan

### ISSUE THREAD

**Issue by celian-m** [ReactiveX/RxSwift#1484]
As seen in [RxMarbles](http://rxmarbles.com/#bufferCount) and [ReactiveX](http://reactivex.io/documentation/operators/buffer.html), the `buffer` operator should be callable without the timeSpan.

**Comment by kzaher** [comment]
Hi @celian-m ,

do you have any use case for this, or are you just saying this for consistency sake? There is an infinite amount of possible operators, and we need to just ship most useful subset.

**Comment by kzaher** [comment]
No reply.

**Comment by nilehmann** [comment]
@kzaher, I found a use case for this. I want to process all `CNContact`, but I'd like to do it in chunks. If I had a buffer operator like the one described here I could just use `enumerateContacts` (wrapped in an observable) and then buffer contacts to process them in batch. In general, I think this could be used anytime you have a large (but finite) set of objects and an api exposing a way to iterate over those objects (and report when the iteration is completed).
