### ISSUE TITLE
Add support for static library frameworks

### ISSUE THREAD

**Issue by piercifani** [ReactiveX/RxSwift#1485]
**Short description of the issue**:

I want to build RxSwift with the `static_framework` flag when using Cocoapods 1.4.0 beta in order to have a faster launch time

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones) 8.3.3 and 9.1
  - [ ] no

**Comment by kzaher** [comment]
Hi @piercifani ,

any hints or PRs that describe what we need to do to support this in backwards compatible way?

**Comment by piercifani** [comment]
Just so you know, I'm using RxSwift to try out this feature on Cocoapods, you can follow the thread [here](https://github.com/CocoaPods/CocoaPods/issues/7213)

**Comment by kzaher** [comment]
@piercifani appreciate the help.

**Comment by sergdort** [comment]
Seems like Cocoapods added support for [static frameworks](https://github.com/CocoaPods/Core/pull/386) and in order to support this we just need to put [`"static_framework": true`](https://github.com/CocoaPods/Specs/search?p=12&q=static_framework&type=&utf8=✓) in the podspec.
Will try to find some time tomorrow to look into it

**Comment by sergdort** [comment]
So, I've managed to make it work locally for `RxSwift`, `RxBlocking` and `RxTest`. But it does not work for `RxCocoa` because it contains some `ObjC` files, not sure what is the issue TBH ¯\_(ツ)_/¯

**Comment by sergdort** [comment]
I think it should work out of the box right now with CocoaPods 1.5.0 http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by kzaher** [comment]
Ok, let's close this then.
