### ISSUE TITLE
bind to publish subject question

### ISSUE THREAD

**Issue by makleso6** [ReactiveX/RxSwift#1487]
**Short description of the issue**:
    after new bind UIButton.rx.tap to model PublishSubject<Void> does not execute subscribe on block

**Expected outcome**:
    execution of block 
```swift
     .subscribe(onNext: { (_) in
            print(section)
      })
```

**What actually happens**:

   nothing happens 🙄
**Self contained code example that reproduces the issue**:

```swift
class RxHeaderViewContainer: NSObject {
    var subject: PublishSubject<Void> = PublishSubject<Void>()
}

class RxHeaderView: UIView, ModelTransfer {
    @IBOutlet weak var actionButton: UIButton!
    var disposeBag = DisposeBag()
    func update(with model: RxHeaderViewContainer) {
        disposeBag = DisposeBag()
        actionButton.rx.tap.bind(to: model.subject).disposed(by: disposeBag)
    }
}

//in presenter
let container = RxHeaderViewContainer()
        container.subject.asObserver().subscribe(onNext: { (_) in
            print(section)
            // nothing goes here with first model
        }).disposed(by: disposeBag)
        view.storage.manager.memoryStorage.setSectionHeaderModel(container, forSection: section)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.0.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% [repo](https://github.com/makleso6/RxTableView)
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
 
```
  9.0.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @makleso6 ,

This is not self contained example as far as I can tell.

`view.storage.manager.memoryStorage.setSectionHeaderModel(container, forSection: section)`.

Please specify which API do you suspect failing and how we can repro this?

**Comment by makleso6** [comment]
@kzaher I using DTTableViewManager for configure UITableView
in [example](https://github.com/makleso6/RxTableView/blob/master/RxTableCell/RxPresenter.swift) demonstrate issue

**Comment by kzaher** [comment]
Hi @makleso6 ,

we unfortunately can't debug code. I've taken a peek and there are too many questions. You aren't using dispose bags in idiomatic way, etc.

If you are suspecting a bug with some particular API, the bug report needs to explain what API is behaving unexpected and what is the expected behavior.

I suggest using `debug` operator gain a more detailed understanding what sequences are sending.

If somebody has time to investigate this, then great, otherwise closing this one until we have a more precise report.
