### ISSUE TITLE
swift 3.2

### ISSUE THREAD

**Issue by shiratsu** [ReactiveX/RxSwift#1489]
**Short description of the issue**:

I would like to use this library on Xcode9.1 with swift 3.2.
However i was not able to build this library.

**Expected outcome**:

this library wasn't build for swift 3.2.
It's for swift 3.1
Even if i use latest version.

**What actually happens**:

same with expected

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 latest release,Mortred

**Platform/Environment**

  - [○ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [○ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [○] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [○] yes (which ones)
  - [ ] no
But i replaced Xcode 8.3 again.

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [○] I have a small code base
  - [○] I have a significant code base

**Comment by kzaher** [comment]
Hi @shiratsu ,

As far as I can tell we don't need to support Swift 3.2 for you to use this library. Just follow the [README.md](https://github.com/ReactiveX/RxSwift#carthage) instructions and it should work.

**Comment by shiratsu** [comment]
OK,sure.I will try.

**Comment by shiratsu** [comment]
I could resolve it.
Thank you!
