### ISSUE TITLE
A crash get into RxSwift on DelegateProxy.

### ISSUE THREAD

**Issue by ufosky** [ReactiveX/RxSwift#1492]
![image](https://user-images.githubusercontent.com/801838/32769399-b010a18a-c956-11e7-9f28-10214011f95f.png)

I get some crash reports from my app, the stack trace is like the image above. These report devices are all Jailbroken.
**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @ufosky ,

are you familiar with `HookLocationManagerClass`? I have no idea what that is.

Can you repro this?

I think we've removed that assert in `master`, so in next release it shouldn't crash.

**Comment by yusufoos** [comment]
I've had the same crash with the 4.0 Release using UIScrollViewDelegate.

It crashes here:

`func castOptionalOrFatalError<T>(_ value: Any?) -> T? {
    if value == nil {
        return nil
    }
    let v: T = castOrFatalError(value)
    return v
}`

How can we try the latest release and see if master fixes it?

**Comment by ufosky** [comment]
I think the HookLocationManagerDelegate is a magic create by jailbreak system.

**Comment by kzaher** [comment]
Hi @ufosky ,

if you can't repro this in normal cases, I would like to close this since there isn't anything we can do there except for changes we've already done.
