### ISSUE TITLE
Infinite recursion in `SerialDisposable.disposable` getter.

### ISSUE THREAD

**Issue by serges147** [ReactiveX/RxSwift#1494]
**Short description of the issue**:

An attempt to use `SerialDisposable.disposable` cause inline recursion.

**Expected outcome**:

Just nested disposable will be returned.

**What actually happens**:

The getter never completes. Program crashes.

**Self contained code example that reproduces the issue**:

```swift
import RxSwift

print("hello!")

let sd = SerialDisposable()

// the problematic getter is invoked
let _ = sd.disposable

print("never happens")
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 9.1
```
**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @serges147 ,

thnx for the fix. I wouldn't recommend using that getter though because once you read the disposable value it becomes stale.
