### ISSUE TITLE
Xcode 9.1 crashed when push to an UICollectionviewController whoes items are set by RXSwift

### ISSUE THREAD

**Issue by aio-ani** [ReactiveX/RxSwift#1499]
**Short description of the issue**:

when I push the UICollectionViewController from another viewcontroller,the Xcode just crashed ,not the app,but the xcode. The UICollectionViewController is in related with a xib in Main.storyboard. Attachment is here [files.zip](https://github.com/ReactiveX/RxSwift/files/1495401/files.zip)

**Expected outcome**:

  I need it to be loaded normally.

**What actually happens**:

The Xcode just crashed ,have no problems to be loged.

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running


import Foundation
import RxCocoa
import RxSwift

class ForumVC : UICollectionViewController{
    
    let collectData = [(bg:"h_video",img:"h_video",title:"title1"),
                       (bg:"h_video",img:"h_video",title:"title2"),
                       (bg:"h_video",img:"h_video",title:"title3"),
                       (bg:"h_video",img:"h_video",title:"title4")]
    let disposeBag = DisposeBag()
    override func viewDidLoad() {
        super.viewDidLoad()
//        collectConfig()
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        collectConfig()
    }
    func collectConfig(){
        let items = Observable.just(self.collectData)
        items.asObservable().bind(to: collectionView!.rx.items(cellIdentifier: "ForumCell", cellType: UICollectionViewCell.self)){ row, element, cell in
            let bgV = cell.viewWithTag(10) as! UIImageView
            let imgV = cell.viewWithTag(11) as! UIImageView
            let titleLb = cell.viewWithTag(12) as! UILabel
            bgV.image = UIImage.init(named: element.bg)
            imgV.image = UIImage.init(named: element.img)
            titleLb.text = element.title
        }.disposed(by: disposeBag)
        collectionView!.rx.setDelegate(self).disposed(by: disposeBag)
//        Observable.just(self.collectData)
//        .asDriver(onErrorJustReturn: [])
//            .drive(self.collectionView!.rx.items(cellIdentifier: "ForumCell", cellType: UICollectionViewCell.self)){ (row,element,cell) in
////                let bgV = cell.viewWithTag(10) as! UIImageView
////                let imgV = cell.viewWithTag(11) as! UIImageView
////                let titleLb = cell.viewWithTag(12) as! UILabel
////                bgV.image = UIImage.init(named: element.bg)
////                imgV.image = UIImage.init(named: element.img)
////                titleLb.text = element.title
//        }.disposed(by: disposeBag)
//        self.collectionView!.rx.setDelegate(self).disposed(by: disposeBag)
    }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let width = collectionView.bounds.width
        let cellWidth = floor((width - 3*15) / 2) // compute your cell width
        return CGSize(width: cellWidth, height: 80)
    }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        return 15
    }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 15
    }
}


```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 9.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @aio-ani ,

why do you think this is a problem with this library and not Xcode?

**Comment by aio-ani** [comment]
@kzaher at the first glance,i think it's more like xcode 's bug,so I have changed my mind to search for another way to solve the problem.thanks very much for your replay.
