### ISSUE TITLE
line 32 Duplicate item error and crash

### ISSUE THREAD

**Issue by vitali36** [ReactiveX/RxSwift#1505]
Hello! I have a problem with updating tableview after getting new data. Problem with Diff. Error.duplicateItem and getting rxDebugFatalError into RxTableViewSectionedAnimatedDataSource class. How can I fix it?

**Comment by kzaher** [comment]
Hi @vitali36 ,

this is not a proper repo to report this. You are probably using `RxDataSource` repo.

It says you have two items with same id inside the data source, which isn't supported.

`id` means unique identifier.

**Comment by vitali36** [comment]
@kzaher thanks a lot!
