### ISSUE TITLE
carthage update with swift 4.0.3

### ISSUE THREAD

**Issue by PH9** [ReactiveX/RxSwift#1521]
after i use `carthage update --platform iOS`

it shown 

```
*** Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
```

**Comment by kzaher** [comment]
Hi @PH9 ,

yes, we'll release 4.0.1 soon and publish new binary.

**Comment by avanes5555** [comment]
"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)."

**Comment by freak4pc** [comment]
This isn't related to this ~2 year old thread :)
