### ISSUE TITLE
Remove RxTests Pod Spec (since its now named RxTest)

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1522]
Following several times this was asked in the RxSwift slack channel, there are two RxTest related Cocoapods: [RxTest](https://cocoapods.org/pods/RxTest) and [RxTests](https://cocoapods.org/pods/RxTests). The former is actually the correct one, and this change was made in [this commit](https://github.com/ReactiveX/RxSwift/commit/3ef88cd4053a749530757c3255b8feeb7d2e1ea5#diff-8b7784190977920d0e43139f298e0d03).

![rxtest](https://user-images.githubusercontent.com/605076/33805735-394fda0a-ddc6-11e7-9827-9bc1f08a6a14.jpg)

My thought is the old Podspec should be removed completely to cause this confusion for developers. The only downside to this is that developers using RxSwift 2.x will have to point their Podfile directly to the repo, since the old version of the repo (RxTests) will be unavailable.

I believe this is a worthwhile sacrifice, that benefits the 99% while providing minimal discomfort for the people who still use 2.x (which is two major versions backwards). 

This issue has been opened mainly to get community feedback so we can decide if removing RxTest is something that makes sense to others as well.

**Comment by LightD** [comment]
Yeah I've seen this. I am planning to start a major refactoring phase and porting everything to RxSwift. Anyone integrating RxSwift will have the usually "taken for granted" comfort and less confusion. 
You'll have way more open issues about this problem, than you would have about the unavailability of RxTests pod not being available.

If there's a vote, I'll vote for removal of RxTests pod.

**Comment by kzaher** [comment]
Hi @freak4pc ,

good thing you've posted it here so we can discuss this in public.

Pro:
* Causing less confusion on Cocoapods web site.

Con:
* It's equivalent to deleting a tag. We'll break previously working pods for 2.x users. I'm not even sure can you submit Swift 2.x apps to app store, but they will break if we do this and this could cause an avalanche of issues.

At this moment I personally think that Cons outweigh the Pros, but if there will be some significant momentum for removal of old pod, then we can consider doing that.

The best solution IMHO would be if CocoaPods supported some feature that enables us to specify that the name of the pod has changed, without actually breaking the existing pods. Maybe @orta knows more about this?

**Comment by freak4pc** [comment]
I personally prefer a few tickets on RxTests backward compatibility than a TON of ticket on people installing RxTests instead of RxTest (this has already been asked about 10 times in the past two weeks on slack ... ) 

I just think we need to concentrate on the present and future. Maintaining backwards compatibility is important, but we're not really taking it away. Pointing a Podfile straight to the repo doesn't seem like a big deal to me (heck, if you're still maintaining a Swift 2.x app, you have worst problems in life for sure 😂 )

**Comment by kzaher** [comment]
@freak4pc have the people been asking because they are both visible on cocoapods portal or is there some other reason?

If the problem is visibility on cocoapods portal, maybe we can remove it just from the portal?

**Comment by freak4pc** [comment]
@kzaher I guess because
1. It was named RxTests for a very long time
2. People instinctively put it in their Podfile and it works, so they don't think there's anything wrong with it until they try and actually work with it

I still stand on the thought removing it completely and asking people with old versions to direct to the repository, the best. 

This method doesn't interferer with the main crowd of developers, and only requires minimal involvement for people who are still maintaining 2.x versions.

**Comment by kzaher** [comment]
Hi @freak4pc ,

I've tried running `pod trunk delete`

```
[03/08 23:15:06]  kzaher  Krunoslavs-MacBook-Pro  ~  Projects  kreddit  kreddit  react  2⬆  4✎  ❓  $  pod trunk delete RxTests
Ignoring io-console-0.4.6 because its extensions are not built.  Try: gem pristine io-console --version 0.4.6
[!] Please specify a version.

Usage:

    $ pod trunk delete NAME VERSION

      WARNING: It is generally considered bad behavior to remove versions of a Pod
      that others are depending on! Please consider using the deprecate command
      instead.

      Deletes the specified pod version from trunk and the master specs repo. Once
      deleted, this version can never be pushed again.

Options:

    --silent    Show nothing
    --verbose   Show more debugging information
    --no-ansi   Show output without ANSI codes
    --help      Show help banner of specified command
```

I would agree with their advice.

Since this is still a pain point, I've deprecated `RxTests` in favor of `RxTest` with this command.

`pod trunk deprecate RxTests --in-favor-of=RxTest`

<img width="1171" alt="screen shot 2018-03-08 at 23 18 09" src="https://user-images.githubusercontent.com/1641148/37179757-006e4c52-2327-11e8-9692-b2b0e3c14300.png">

I was hoping this warning would be bigger :( Maybe we should ask cocoapods team to improve that warning. 

I'm hoping this is enough to resolve this issue.

**Comment by freak4pc** [comment]
I didn't even know about `pod trunk deprecate` - As far as I'm concerned that's perfect! 

Thanks :)
