### ISSUE TITLE
`Resources.total` warning: UITextField is leaking in iOS 11.2 (not a bug with RxSwift)

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#1526]
It looks like iOS 11.2 broke UITextField. It never gets deallocated.

```
final class UITextFieldSubclass: UITextField { deinit { print("never called")  } }
let textField = UITextFieldSubclass(frame: .zero)
```

If you are using `Resources.total` that's where the problem is.

**Comment by VanHoutte1337** [comment]
Finally I found my answer! It was going crazy after using: 
`loginTextField.rx.text
            .orEmpty
            .bind(to: viewModel.login)
            .disposed(by: disposeBag)`

When I would print my Resources.total, it kept adding 3 resources. Let's hope this gets fixed soon.

**Comment by freak4pc** [comment]
Confirming this is still happening on 11.2.1.

**Comment by anymuse** [comment]
11.2.2 too. Drives me crazy~
