### ISSUE TITLE
UITextfield retain cycle for Throttle, but not Debounce

### ISSUE THREAD

**Issue by andrewrt** [ReactiveX/RxSwift#1530]
**Short description of the issue**:
Throttle causes retain cycle whereas Debounce does not for the raywenderlich RxSwift tutorial (when modified to use weak/unowned self).
I am new to RxSwift - so might be missing something very fundamental - please let me know if so.

**Expected outcome**:
Throttle and Debounce handle ARC in roughly the same way - where if you are sure to make use of [unowned self] or [weak self] in observables and dispose properly.

**What actually happens**:
Throttle has retain cycle, Debounce does not.

**Self contained code example that reproduces the issue**:

```swift
// Pulled from the raywenderlich Chocotastic project's BillingInfoViewController.swift class - validating input from UITextFields. Code updated for Credit Card validation map calls to use [unowned self]:

  private func setupTextChangeHandling() {
    let creditCardValid = creditCardNumberTextField
      .rx
      .text //1
//      .debounce(0.1, scheduler: MainScheduler.instance) // use this instead of throttle for no retain cycle
      .throttle(0.1, scheduler: MainScheduler.instance) //2
      .map { [unowned self ] in
        self.validate(cardText: $0!)
    } //3
    
    creditCardValid
      .subscribe(onNext: { [unowned self ] in
        self.creditCardNumberTextField.valid = $0
      }) //4.count
      .disposed(by: disposeBag) //5
    }

  
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Chocotastic' do
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
```

**Platform/Environment**

  - [* ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [* ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  9.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ * ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [* ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ * ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @andrewrt ,

RW code is faulty and causes retain cycles because of referencing `self` inside closures. This isn't a bug with this library.

**Comment by andrewrt** [comment]
Hi kzaher, I was under the impression that by updating said code to use [unowned self] as I have in the code snippet, that the problems should be solved (and it is so long as I use debounce, but not throttle)?

**Comment by kzaher** [comment]
@andrewrt You can' test this using UITextField because of 
https://github.com/ReactiveX/RxSwift/issues/1526

**Comment by kzaher** [comment]
Actually you should, but we have resource leak tests and it looks like they are working

```
#if TRACE_RESOURCES
        func testThrottleLatestReleasesResourcesOnComplete() {
            let scheduler = TestScheduler(initialClock: 0)
            _ = Observable<Int>.just(1).throttle(0.0, latest: true, scheduler: scheduler).subscribe()
            scheduler.start()
        }

        func testThrottleLatestReleasesResourcesOnError() {
            let scheduler = TestScheduler(initialClock: 0)
            _ = Observable<Int>.error(testError).throttle(0.0, latest: true, scheduler: scheduler).subscribe()
            scheduler.start()
        }
    #endif
```

**Comment by andrewrt** [comment]
OK, thanks!
