### ISSUE TITLE
Extend global Hook to Traits

### ISSUE THREAD

**Issue by lucas34** [ReactiveX/RxSwift#1532]
Hi,

Currently in RxSwift 4.0.0, the global Hook handle is only called for ObservableType.

The documentation for "Hook" is "/// Error handler called in case onError handler wasn't provided.".
But when I implement the following code 

```
Hooks.defaultErrorHandler = { callback, error in
    print("handled")
}

_ = Observable<String>.error(ApiError.unexpected).subscribe() // print
 _ = Single<String>.error(ApiError.unexpected).subscribe()
 _ = Maybe<String>.error(ApiError.unexpected).subscribe()
 _ = Completable.error(ApiError.unexpected).subscribe()
```

None of the observers implements onError. However, the Hook will only get called for the Observable. Why not forwarding error for Single, Maybe and Completable to Hook ? Otherwise, I think you should update the documentation for Hook to make it more explicit.

To workaround this I'm doing sequence.asObservable().subscribe()

**Comment by kzaher** [comment]
Hi @lucas34 ,

yes, we should also add `Hooks.defaultErrorHandler` to `Single`, `Maybe`, `Completable`.
