### ISSUE TITLE
[RxCocoa.RxCollectionViewDelegateProxy leftMarginForCollectionView:layout:]: unrecognized selector sent to instance 0x1c02da7f0

### ISSUE THREAD

**Issue by lanjing99** [ReactiveX/RxSwift#1536]
**What actually happens**:

where shows keyboard, then crash

frame #0: 0x00000001825444f0 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x000000018330b828 CoreFoundation`-[NSObject(NSObject) doesNotRecognizeSelector:] + 140
    frame #2: 0x0000000183303d10 CoreFoundation`___forwarding___ + 1380
    frame #3: 0x00000001831e8ecc CoreFoundation`_CF_forwarding_prep_0 + 92
    frame #4: 0x000000018d0d9dac UIKit`-[UIKeyboardCandidateBarLayout prepareLayout] + 476
    frame #5: 0x000000018c83adb4 UIKit`-[UICollectionViewData _prepareToLoadData] + 160
    frame #6: 0x000000018c83a3cc UIKit`-[UICollectionViewData validateLayoutInRect:] + 104
    frame #7: 0x000000018c839d80 UIKit`-[UICollectionView layoutSubviews] + 260
    frame #8: 0x000000018c7dcf00 UIKit`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1276
    frame #9: 0x0000000187341998 QuartzCore`-[CALayer layoutSublayers] + 184
    frame #10: 0x0000000187345b20 QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 332
    frame #11: 0x000000018c7f1ccc UIKit`-[UIView(Hierarchy) layoutBelowIfNeeded] + 548
    frame #12: 0x000000018d399dd0 UIKit`-[UIInputSetHostView layoutIfNeeded] + 108
    frame #13: 0x000000018d0aebf0 UIKit`-[_UIRemoteKeyboards ignoreLayoutNotifications:] + 48
    frame #14: 0x000000018d3aa5f4 UIKit`__43-[UIInputWindowController setInputViewSet:]_block_invoke + 124
    frame #15: 0x000000018c7eda14 UIKit`+[UIView(Animation) performWithoutAnimation:] + 104
    frame #16: 0x000000018d3aa30c UIKit`-[UIInputWindowController setInputViewSet:] + 744
    frame #17: 0x000000018d3a226c UIKit`-[UIInputWindowController performOperations:withAnimationStyle:] + 56
    frame #18: 0x000000018c893fa4 UIKit`-[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1660
    frame #19: 0x000000018c805a7c UIKit`-[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 2472
    frame #20: 0x000000018c8050a4 UIKit`-[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 80
    frame #21: 0x000000018d042e10 UIKit`-[UIWebBrowserView _reloadInputViewsAfterPotentialFocusRedirect] + 60
    frame #22: 0x000000018d042c9c UIKit`-[UIWebBrowserView _endAllowingFocusRedirects] + 48
    frame #23: 0x0000000103d7528c libdispatch.dylib`_dispatch_client_callout + 16
    frame #24: 0x0000000103d87c38 libdispatch.dylib`_dispatch_sync_thread_bound_invoke + 124
    frame #25: 0x0000000103d7528c libdispatch.dylib`_dispatch_client_callout + 16
    frame #26: 0x0000000103d79ea0 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1196
    frame #27: 0x00000001832a6544 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #28: 0x00000001832a4120 CoreFoundation`__CFRunLoopRun + 2012
    frame #29: 0x00000001831c3e58 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #30: 0x0000000185070f84 GraphicsServices`GSEventRunModal + 100
    frame #31: 0x000000018c84367c UIKit`UIApplicationMain + 236
  * frame #32: 0x0000000100f2f92c loan`main at AppDelegate.swift:38
    frame #33: 0x0000000182ce056c libdyld.dylib`start + 4

  - [ ] iOS 11.2

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:
9.2
```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting

**Comment by lanjing99** [comment]
crashed after loading a Web page, before show keyboard.

**Comment by kzaher** [comment]
Hi @lanjing99 ,

I'm not sure I understand how to repro this?

**Comment by sssssunying** [comment]
what's wrong?
