### ISSUE TITLE
Unable to compile RxCocoa 4.1.0

### ISSUE THREAD

**Issue by lucas34** [ReactiveX/RxSwift#1544]
I'm not able to compile after updating to RxSwift and RxCocoa 4.1.0
Clean build relaunch etc didn't help.

```
DelegateProxy
Error:(213, 59) ambiguous use of 'map'
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
```
RxCocoa 4.1.0
RxSwift 4.1.0
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 9.1
```

**Swift Version**:
```
3.2
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Comment by kzaher** [comment]
Hi @lucas34,

Does https://github.com/ReactiveX/RxSwift/pull/1539 solve the issue for you?

**Comment by lucas34** [comment]
Yes it does solve the issue

**Comment by lucas34** [comment]
It seems to only affect you if you are using Swift version<4 (3.2 for sure).
Can you consider merging #1539 and having a 4.1.1 release as compile bug fix ?

**Comment by kzaher** [comment]
@lucas34 yes, I'll do that.
