### ISSUE TITLE
Reactive UIPickerview not showing values

### ISSUE THREAD

**Issue by SahebRoy92** [ReactiveX/RxSwift#1545]
**UIPickerView created programatically now showing any data.**

I have tried the following snipped as this was taken from the example project of RxSwift directly, but no matter what I do no data is showing. I even debugged the number of rows in the picker, right after the bind call and its having value, but as soon as the bind call gets finished no data is showing.

Code : 

      var pickerView : UIPickerView = {
        let lzypickerView = UIPickerView(frame: CGRect(x: 0, y: 40, width: UIScreen.main.bounds.size.width, height: 190))
             return lzypickerView
       }()

    func openPicker(){
    let disposeBag = DisposeBag()
        
             Observable.just(["1","2","3"])
               .bind(to: pickerView.rx.itemTitles) { _, item in
                     return "\(item)"
                 }
                 .disposed(by: disposeBag)
              print("Finished -- ")
    }

Outcome : 

<img width="388" alt="screen shot 2018-01-09 at 12 04 43 pm" src="https://user-images.githubusercontent.com/13575978/34707936-54bd8242-f536-11e7-8531-c215e07c3719.png">

**DEBUG**
Breakpoint before print : Number of components in UIPickerView is showing as 1
Breakpoint after print : Number of components in UIPickerview is showing as 0

**Hack/ Solution**

Removed call to disposeBag and the pickerview is operating as normal.
**Now I dont know if this is an issue or not as dispose bag calls are supposed to be used in every Reactive bind.**

<img width="551" alt="screen shot 2018-01-09 at 12 07 27 pm" src="https://user-images.githubusercontent.com/13575978/34707854-d1ec3c14-f535-11e7-824c-2ec0b2351629.png">
<img width="386" alt="screen shot 2018-01-09 at 12 08 03 pm" src="https://user-images.githubusercontent.com/13575978/34707948-5ebdab96-f536-11e7-8b52-121954895c14.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
Latest - 

**Platform/Environment**
  - iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - easy, 100% reproducible

**Xcode version**:
9.0

**Installation method**:
  - CocoaPods
 

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  -  no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  -  just starting

**Comment by kzaher** [comment]
Hi @SahebRoy92 ,

please consult readme and example app on how to use dispose bags properly.

**Comment by gmarson** [comment]
you must declare disposeBag outside your function
