### ISSUE TITLE
UIBarButtonItem does not react to tap events if initialized in map closure

### ISSUE THREAD

**Issue by seasox** [ReactiveX/RxSwift#1549]
**Short description of the issue**:
Instances of `UIBarButtonItem` do not signal on tap events if they were created in a map closure. 

**Expected outcome**:
Console prints "tap" after tap on navigation bar button and label text gets updated, regardless of where `UIBarButtonItem` was initialized (inside or outside of map closure).

**What actually happens**:
Tapping `UIBarButtonItem` instances which were created in a map closure does not result in a signal on`rx.tap`.

**Self contained code example that reproduces the issue**:
See https://github.com/seasox/BarButtonLost

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
This problem appears in both RxSwift/RxCocoa 4.1.0 and 4.1.1

**Platform/Environment**
  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
Version 9.2 (9C40b)

**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [X] I have a small code base
  - [ ] I have a significant code base

**Comment by seasox** [comment]
Snapshot of demonstration project repository:

[BarButtonLost-master.zip](https://github.com/ReactiveX/RxSwift/files/1626692/BarButtonLost-master.zip)

**Comment by kzaher** [comment]
Hi @seasox ,

you are misunderstanding how Rx and `Driver` work. You ideally want `Driver` to be non terminating to avoid these kinds of issues.

`buttons` are a finite `Driver`, it generates a single element and the sequence immediately completes.

When you are subscribing to `index` and `barButtons` in view controller you are creating two separate batches of buttons and using one to subscribe to UI and batch you are collecting events from.

You can solve this easily by preventing `barButtons` from terminating `barButtons = Driver.merge(Driver.just(theOnlyValueYouWant), Driver.never())`.
