### ISSUE TITLE
Common `Bindable` protocol for any type that has `bind(to:`) sort of method

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1550]
This issue is a discussion and not an actual "Issue", per-se

Right now there is no good way to target all types that are Bindable - this includes Subjects, Relays and also in general there is no way to group Relays together. 

I noticed this problem in RxTestExt where we're forced to have separate definitions for `BehaviorRelay` and `PublishRelay`, for example: 

https://github.com/RxSwiftCommunity/RxTestExt/pull/15/files#diff-a4d1020eede0cd46ebf602cf4481baafR13

Would be really cool if we could have just a single method that applies to all `Bindable` types. 

Would love community feedback :)

**Comment by freak4pc** [comment]
The thought is something like

```swift
protocol Bindable {
    func bind(to: Bindable)
}

extension PublishSubject: Bindable { ... } // In RxSwift
extension PublishRelay: Bindable { ... } // In RxCocoa
```

**Comment by mosamer** [comment]
This would not solve it I think. May be something like
```swift
protocol Bindable {
   associatedtype E
}
extension ObserverType: Bindable {}

extension ObservableType {
   public func bind<B: Bindable>(to bindable: B) -> Disposable where B.E == E {
        ...
    }
}
```

**Comment by freak4pc** [comment]
@mosamer I already removed my comment as I realized I was thinking backwards about it :)

**Comment by kzaher** [comment]
Hi @mosamer @freak4pc  ,

I've posted my comments to https://github.com/ReactiveX/RxSwift/pull/1551.

**Comment by freak4pc** [comment]
Closing this in favor of the PR discussion
