### ISSUE TITLE
How to change the datasource method "canMoveItemAt" in collectionView

### ISSUE THREAD

**Issue by lyluoyuan** [ReactiveX/RxSwift#1553]
When used collectionView with  RxSwift, I found that the datasource method "canMoveItemAt" is set false in latest version. How should I change it true?

**Comment by IgorBulyga** [comment]
Hi @lyluoyuan, dataSource has the closure property `open var canMoveItemAtIndexPath: ((CollectionViewSectionedDataSource<S>, IndexPath) -> Bool)?`, where you can define custom behaviour.
