### ISSUE TITLE
re execute observable in Observable.zip

### ISSUE THREAD

**Issue by krmao** [ReactiveX/RxSwift#1560]
![image](https://user-images.githubusercontent.com/7344437/35725183-64cd9c72-083b-11e8-81fe-9728ea260bb5.png)
![image](https://user-images.githubusercontent.com/7344437/35725186-67df3358-083b-11e8-810e-544ba2f2dd9a.png)

why red line ( coupon and storeselect ) print more than once?

**Comment by beeth0ven** [comment]
Hi @krmao 

I'm not sure what happened here, but the following code works as expect to me:

![2](https://user-images.githubusercontent.com/5554127/35730213-2f8b2cd0-084c-11e8-979c-8754b2d266e4.png)

I can't reproduce it, is there something i'm missing?

**Comment by krmao** [comment]
@kzaher hi 

### this problem never happen again .
