### ISSUE TITLE
Unpredictable runtime behaviour

### ISSUE THREAD

**Issue by Chupik** [ReactiveX/RxSwift#1561]
**Short description of the issue**:

  Application crashes or freezes while disposing UITableViewController resources. Reproducible only on iOS 10.x.

**Expected outcome**:

  Application does not crash after popping back to the previous viewController.

**What actually happens**:

  Application crashes or tries to reload all invisible cells while disposing UITableViewController resources.
https://github.com/ReactiveX/RxSwift/blob/e479d0029db0575e03e3c092e1c9724b9410eab7/RxCocoa/Common/DelegateProxyType.swift#L340
<img width="676" alt="2018-02-04 15 06 54" src="https://user-images.githubusercontent.com/2719055/35778425-2972f5f6-09cf-11e8-9201-72dd873b1138.png">

<img width="455" alt="2018-02-04 17 22 38" src="https://user-images.githubusercontent.com/2719055/35778510-12d98106-09d0-11e8-915f-5ffda902c36d.png">

**Self contained code example that reproduces the issue**:

   https://github.com/Chupik/DisposableCrashExample

   If you want to reproduce the application freezes, move the line 
```swift
tableView.rx.setDelegate(self).disposed(by: disposeBag)
```
 to the end of the "viewDidLoad".

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift 4.1.1, RxCocoa 4.1.1
  RxSwift 4.0.0, RxCocoa 4.0.0

**Platform/Environment**

  - [x] iOS Simulator 10.2, 10.3
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode Version 9.2 (9C40b)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @Chupik ,

Why do you think this is an `Rx{Swift,Cocoa}` bug and not UIKit bug?

**Comment by Chupik** [comment]
Hi, @kzaher 
Maybe this is an UIKit bug. But everything works fine if I do not use delegate customization.

**Comment by kzaher** [comment]
Hi @Chupik ,

yeah, sorry man. As far as I can tell this is an UIKit quirk/defect. I wish we could make all of these quirks go away, but unfortunately I don't think this is plausible.

¯\\\_(ツ)\_/¯

**Comment by Pulichev** [comment]
I know that this is kinda old thread, but in my case helped next:
in VC:

`deinit {
        tableView?.dataSource = nil
        tableView?.delegate = nil
        disposeBag = DisposeBag()
    }`
