### ISSUE TITLE
Add another `deferred` for `PrimitiveTypes` with `ElementType` factory instead of `PrimitiveSequence`

### ISSUE THREAD

**Issue by williamhjcho** [ReactiveX/RxSwift#1562]
# Short description

Add another `deferred` for `PrimitiveTypes` with `ElementType` factory instead of `PrimitiveSequence` factory

## Proposition

`Single.deferredElement(() throws -> ElementType)) -> Single<ElementType>`
`Maybe.deferredElement(() throws -> ElementType?)) -> Maybe<ElementType>`
`Completable.deferredElement(() throws -> Void)) -> Completable`

Where the factory closures simply return 

- some value (`Single` and `Maybe`) 
- or not (`Maybe` and `Completable`)

Then adjust to it's `PrimitiveSequence` accordingly (`just` or `empty`).

The factory also can `throw` to allow the sequence to send an `error` instead.

## Observations

This is not an improvement/addition of core concepts, rather it's more of a "wrapper" on top of current `PrimitiveSequence.deferred`

`RxJava` already has this implemented: `fromCallable` but from the name alone it's not much to be inferred.
`deferredElement` is just something I came up with at the moment of need, but it's still debatable, especially on `Completable`

The implementation is fairly [simple enough](https://github.com/ReactiveX/RxSwift/compare/master...william-wc:add-deferred-from-values?expand=1)
(I didn't open the PR yet since the guidelines asked to open an issue first when proposing adding things to the API)

**Comment by kzaher** [comment]
Hi @williamhjcho ,

I would say that this is an easy to build extension. I can understand why you might have a need for this extension, but I would like to not include it for the time being.

I would like to keep library as small and orthogonal as possible, and keep traits in sync with observable sequence version.

Hope this makes sense.

**Comment by williamhjcho** [comment]
It seemed small and self-conscious enough for it to be a part of the core `API`

But it makes sense to keep orthogonality. 
Adding it as an extension is also fairly trivial to whoever needs it.

(I'll keep my `fork` open to whoever needs it in the future)
