### ISSUE TITLE
onDispose callback scheduler?

### ISSUE THREAD

**Issue by kustra** [ReactiveX/RxSwift#1564]
**Short description of the issue**:

I cannot find any documentation on which scheduler is used to execute onDispose callbacks in RxSwift. [I created a playground](https://github.com/kustra/RxPlaygrounds/blob/master/Schedulers.playground/Contents.swift) to experiment with it, but still I don't seem to grasp the logic behind it.

Consider this code:
```
Observable.just(0)
    .debugThread("A")
    .subscribeOn(namedScheduler("subscribeOn-1"))
    .debugThread("B")
    .subscribeOn(namedScheduler("subscribeOn-2"))
    .debugThread("C")
    .observeOn(namedScheduler("observeOn-1"))
    .debugThread("D")
    .subscribeOn(namedScheduler("subscribeOn-3"))
    .debugThread("E")
    .subscribeOn(namedScheduler("subscribeOn-4"))
    .debugThread("F")
    .observeOn(namedScheduler("observeOn-2"))
    .debugThread("G")
    .subscribe()
```

The `debugThread` operations are for debugging schedulers of Rx callbacks. See the playground for implementation details.

**Expected outcome**:

Any consistent, predictable behaviour regarding the scheduler choices for executing onDispose calls. 

**What actually happens**:

These are the schedulers used for executing onDispose on the various point in the chain:
```
 A       onDispose      subscribeOn-1
 B       onDispose      subscribeOn-2
 C       onDispose      subscribeOn-1
 D       onDispose      subscribeOn-3
 E       onDispose      subscribeOn-4
 F       onDispose      observeOn-1
 G       onDispose      observeOn-2
```

**Self contained code example that reproduces the issue**:

https://github.com/kustra/RxPlaygrounds
Clone the repo, open RxPlaygrounds.xcworkspace in Xcode, build it once, then open Schedulers.playground in the Project navigator.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
PODS:
  - RxCocoa (4.1.1):
    - RxSwift (~> 4.0)
  - RxOptional (3.3.0):
    - RxCocoa (~> 4.0)
    - RxSwift (~> 4.0)
  - RxSwift (4.1.1)
```

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] playgrounds

I'm fairly sure that this behaviour is platform-independent. I did try it with the macOS build of RxSwift playgrounds, too, with similar results.

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 9.2 (9C40b)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

As I mentioned earlier, I could also reproduce the issue with RxSwift Playgrounds.

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by kustra** [comment]
At the least, this is a documentation issue. A behaviour of RxSwift that is not specified anywhere.
