### ISSUE TITLE
Why doesn't RxSwift support macOS 10.9?

### ISSUE THREAD

**Issue by toadzky** [ReactiveX/RxSwift#1566]
I have a macOS app that I'm rebuilding in swift and I wanted to use RxSwift. I actually got a bunch of stuff done on top of RxSwift before I realized that it only supports back to 10.10. I cloned the repo, changed the deployment target for macOS to 10.9 and it builds fine.

Is there a specific reason 10.9 isn't supported or was it just an oversight when creating the project?

**Comment by kzaher** [comment]
Hi @toadzky ,

We don't have any special requirements as far as I can tell. If Swift compiler works on that platform, so should RxSwift.

At the moment I can't recall any other requirements or known issues. Feel free to make a PR.

**Comment by toadzky** [comment]
@freak4pc thanks for jumping on that. i was planning to do it tonight when i had some time, but you have saved me the effort

**Comment by tomaszbak-binar** [comment]
@kzaher Change mentioned here started to be a problem in Cocoapods after merging https://github.com/ReactiveX/RxSwift/pull/2144 

Parts using `WKWebView` have annotations for macOS 10.10, but if a project generated by Cocoapods has the deployment target set to 10.9 (and by default it uses a value from the Podspec), the compilation will fail.

Until you'll fix deployment target value in the podspec I will use following hook to quick-fix the issue:
```ruby
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == "RxCocoa"
          config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
      end
    end
  end
end
```

**Comment by freak4pc** [comment]
What exactly fails in the compilation?

**Comment by freak4pc** [comment]
I just made a dummy object with a 10.9 Deployment Target and RxSwift 5.1.1 and it builds with no issues. Happy to try and help if you provide more details.

![image](https://user-images.githubusercontent.com/605076/77649236-2bcc8500-6f72-11ea-9340-38a1b4415361.png)

**Comment by tomaszbak-binar** [comment]
RxCocoa compilation fails with 18 errors, to be exact. The errors point to different WebKit types and methods, but they all report the same issue:
```
.../Pods/RxCocoa/RxCocoa/iOS/Proxies/RxWKNavigationDelegateProxy.swift:16:21: 'WKWebView' is only available in macOS 10.10 or newer
```

My main project has the deployment target set to 10.12, but I don't think it should change anything. As mentioned above, errors go away if I manually bump target for the generated project.

**Comment by freak4pc** [comment]
Again, as you said, there is an availability clause on that piece for 10.10 and up, so it shouldn't be an issue. Is there any chance you could send me that empty generated project you mentioned so I can inspect it?

**Comment by tomaszbak-binar** [comment]
I tried to reproduce it on a fresh project with a similar setup to mine and there was no issue for me too. This made me go back to my project and nuke Cocoapods. After a fresh install the issue no longer occurs, so it was probably related to Pods or Xcode internal caching. Sorry for taking your time 😅

**Comment by freak4pc** [comment]
All good :) glad it works for you.
