### ISSUE TITLE
Failure converting from Optional(<RXSwiftTableReloadViewController: 0x7fc9eec4eb60>) to UIScrollViewDelegate

### ISSUE THREAD

**Issue by LakshmanaSwamy** [ReactiveX/RxSwift#1587]
Failure converting from Optional(<RXSwiftTableReloadViewController: 0x7fc9eec4eb60>) to UIScrollViewDelegate
This is my code whats wrong with that

import UIKit
import RxSwift
import RxCocoa

struct Person{
    let name : String
    let age : Int
}

class RXSwiftTableReloadViewController: UIViewController {
    @IBOutlet weak var aTableView: UITableView!
    let personArr = [Person(name: "satish",age: 30),Person(name: "naresh",age: 28),Person(name: "lokesh",age: 40),Person(name: "nani",age: 25),Person(name: "hari",age: 30)
    ]
    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()
        let nib = UINib(nibName: "SettingTableViewCell", bundle: nil)
        aTableView.register(nib, forCellReuseIdentifier: "SettingTableViewCell")
        print(personArr)
        let objectArr : Observable<[Person]> = Observable.just(personArr)
        
        objectArr.bind(to: aTableView.rx.items(cellIdentifier:"SettingTableViewCell")){
            _,person, cell in
            if let cellToUse = cell as? SettingTableViewCell {
                print(person.name)
            }
        }.disposed(by:disposeBag)
       
    }
}

**Comment by undeadhd** [comment]
i have this problem too

```swift
let cities = Observable.of(["Lisbon", "Copenhagen", "London", "Madrid", "Vienna"])
        cities.asObservable().bind(to: tableView.rx.items(cellIdentifier: "cell")) { _, element, cell in
            cell.textLabel?.text = element
}
```

**Comment by kzaher** [comment]
Hi @LakshmanaSwamy ,

Please fill out issue template.

**Comment by andreaferrando** [comment]
You forgot to set your ViewController as implementing the UITableViewDelegate, just add:
`class RXSwiftTableReloadViewController: UIViewController, UITableViewDelegate`

**Comment by dtsos** [comment]
Can Anyone solve this problem?

**Comment by LakshmanaSwamy** [comment]
yes Andrea gave  the solutions

Thanks
Lakshman

**Comment by jamielesouef** [comment]
Removing the delegate and datasource in my starboard fixed this or me 👍

**Comment by LakshmanaSwamy** [comment]
Fixed
