### ISSUE TITLE
Parallel refresh requests of OAuth access token.

### ISSUE THREAD

**Issue by vin7974** [ReactiveX/RxSwift#1588]
The problem is when the access token expires and multiple requests happen at the same time some of them fail.

Parallel requests can be triggered by different parts of the app. For example, when the app is navigated to new view controller multiple requests are sent to the server and a list of events is downloaded.

What would be the best way to make sure that no second refresh token request is made while the first is still running? (Synchronous refresh token method)

I'm using RxSwift and RxAlamofire.

public func _request(_ method: Alamofire.HTTPMethod, url: URLConvertible, parameters: [String : Any]? , encoding: ParameterEncoding, headers: [String : String]? ,isSecondTryAfterAuth: Bool = false) -> RxSwift.Observable<(HTTPURLResponse, Any)>{
        print(self)
        return RxAlamofire
            .requestJSON(method, url,parameters: parameters, encoding:JSONEncoding.default, headers:headers)
            .flatMap({(HTTPURLResponse, json) -> Observable<(HTTPURLResponse, Any)> in
                
                if(HTTPURLResponse.statusCode == 401){
                    print("\n\n\n ********* 1 ***********")
                    if (isSecondTryAfterAuth || self == nil){
                        NotificationCenter.default.post(name: Notification.Name("logout"), object: nil)
                        return Observable.error(APIError.invalidCredentials)
                    }
                      
                        return (self.refreshToken(headers)
                            .flatMapLatest({ (RefreshTokenResponse) -> Observable<(HTTPURLResponse, Any)> in
                                AuthManager.setSessionToken(RefreshTokenResponse.token)
                                print("\n\n\n ********* 2 ***********")

                                guard let authenticationBlock = self.authenticationBlock else {
                                    throw APIError.missingAuthenticationBlock
                                }

                                return Observable.create { observer in
                                    authenticationBlock {
                                        print("\n\n\n ********* 3 ***********")

                                        let token = AuthManager.getSessionToken()
                                        if( token != nil && !(token!.isEmpty)){

                                            self.headers["Authorization"] = "Bearer \(token!)"
                                           
                                        }
                                        self._request(method, url:url, parameters: parameters,encoding:encoding,headers: self.headers, isSecondTryAfterAuth: true)
                                            .subscribe { event in
                                                observer.on(event)
                                                print("\n\n\n ********* 4 ***********")

                                            }.addDisposableTo((self.disposeBag))
                                    }
                                    return Disposables.create()
                                }
                            }))
                }else {
                   // defer{self.lock.unlock()}
                    return Observable.just(HTTPURLResponse, json)
                }
            })
    }
    
    func refreshToken(_ headers: [String : String]?) -> Observable<RefreshTokenResponse>{
        print("\n\n\n ********* 5 ************\n\n\n")
        
        let absolutePath = "\(baseURL)/refresh-token"
        return RxAlamofire
            .requestJSON(.post, absolutePath, encoding: JSONEncoding.default,headers: headers)
            .debug()
            .map({ (response,json) -> RefreshTokenResponse in
                return Mapper<RefreshTokenResponse>().map(JSONObject: json)!
                print("\n\n\n ********* 6 ***********")
      })
    }
}

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
