### ISSUE TITLE
the throttle info link is wrong?

### ISSUE THREAD

**Issue by FuYouFang** [ReactiveX/RxSwift#1591]
in http://reactivex.io/documentation/operators.html#filtering page，the `throttle` operator link `debounce` document.

why? They are same, or something wrong?

**Comment by kzaher** [comment]
@FuYouFang There isn't any info on `throttle` operator in reactivex.io documentation. `Debounce` is the closest as far as I can tell.

There was a historic mixup and original .NET `throttle` behavior was actually RxJava `debounce`.

Is there some some other link that you think should be there?

**Comment by FuYouFang** [comment]
I find one difference,

```
Observable.of(1,2,3,4,5)
        .concat(Observable.never())
        .debounce(dueTime, scheduler: MainScheduler.instance)
        .subscribe(onNext: {print($0)})
        .addDisposableTo(disposeBag)
```
wait `dueTime` seconds print `5`.

```
Observable.of(1,2,3,4,5)
    .concat(Observable.never())
    .throttle(dueTime, scheduler: MainScheduler.instance)
    .subscribe(onNext: {print($0)})
    .addDisposableTo(disposeBag)
```
print `1` immediately, wait `dueTime` seconds print `5`.

**Comment by kzaher** [comment]
@FuYouFang In RxSwift there is difference in behavior between `throttle` and `debounce`. Was that the question?

**Comment by FuYouFang** [comment]
@kzaher Yes.

**Comment by 1397v** [comment]
Well I think the real problem here is that there is no definition for `throttle` in the RxSwift documentation because when you click on throttle at http://reactivex.io/documentation/operators.html it takes you to the definition of [debounce](http://reactivex.io/documentation/operators/debounce.html). 
The thing is that this is **wrong** on RxSwift, and it should be documented somewhere. There is just an annotation on the table for RxSwift saying "TBD".

**Comment by kzaher** [comment]
@1397v you are welcome to create PR to https://github.com/ReactiveX/reactivex.github.io that fixes this, and after that to RxSwift.

**Comment by 1397v** [comment]
@kzaher I'm not talking about the framework itself, there is no problem about it, I'm talking about the **docs**. Just having some explanation that shows how `throttle` differs from `debounce` in the RxSwift framework would be so nice and people wouldn't lose so much time looking for tutorials on the Internet.

**Comment by 1397v** [comment]
@kzaher Done! [Added description for throttle in RxSwift #367](https://github.com/ReactiveX/reactivex.github.io/pull/367)
