### ISSUE TITLE
`unowned self` can lead to crash even if subscription lives as long as `self` does

### ISSUE THREAD

**Issue by gobetti** [ReactiveX/RxSwift#1593]
Hi! I just want to be sure whether this can be considered a bug or if it's a result from a non-idiomatic use of the framework (in which case suggestions to improve are absolutely welcome!). Thanks 😄 

**Short description of the issue**:

It is possible that a subscription has its subscribe block executed after the class instance has already deallocated, even if that subscription is held by that instance's DisposeBag. In other words, using `unowned self` is not entirely safe.

**Expected outcome**:

All the subscriptions controlled by a DisposeBag should be disposed by the DisposeBag's deallocation event before allowing any of its subscriptions to handle events other than `onDisposed`.

**What actually happens**:

Apparently, the DisposeBag disposes its Disposables individually, allowing events to be handled by the still alive subscriptions in between disposals.

**Self contained code example that reproduces the issue**:

```swift
class ModalPage {
  private let disposeBag = DisposeBag()
  
  init() {
    Observable<Void>.never()
      .subscribe(onDisposed: {
        print("disposed 1")
        // this will set a new value to the variable, causing a new `next` event to trigger:
        Singleton.shared.variable.value = true
      }).disposed(by: disposeBag)
    
    Singleton.shared.variable.asObservable()
      .subscribe(onNext: { [unowned self] in // self should still exist here thanks to the disposeBag
        print("setting")
        self.useBool($0) // crashes because an event on `variable` is triggered before this is disposed, and after self has been deallocated
        }, onDisposed: {
          print("disposed 2") // a crash occurs before this has the chance to be called
          // this will set a new value to the variable, causing a new `next` event to trigger:
          Singleton.shared.variable.value = true
      }).disposed(by: disposeBag)
  }
  
  func useBool(_ boolean: Bool) {
    print("\(boolean)")
  }
}

class Singleton {
  static let shared = Singleton()
  let variable = Variable(false)
}

var modalPage: ModalPage? = ModalPage()
_ = Observable<Int>.timer(1.0, scheduler: MainScheduler.instance).subscribe(onNext: { _ in
  print("timer")
  modalPage = nil
})
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

tag 3.6.1

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [?] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.2
```

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @gobetti ,

>It is possible that a subscription has its subscribe block executed after the class instance has already deallocated, even if that subscription is held by that instance's DisposeBag. In other words, using unowned self is not entirely safe.

This is described on top of getting started doc.

https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#disposing

> Apparently, the DisposeBag disposes its Disposables individually, allowing events to be handled by the still alive subscriptions in between disposals.

Yes, this is by design.

**Dispose logic should never perform anything except disposing, like sending elements**. The code will execute properly, but semantically it causes undefined behavior.

**Comment by Nominalista** [comment]
Is this the reason why 'weak self' should be used instead of 'unowned self'?

**Comment by gobetti** [comment]
@Nominalista according to Apple's documentation:
> use an unowned reference when the other instance has the same lifetime or a longer lifetime.

Source: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html

However according to @kzaher:
> you should never use `unowned`.

Source: https://github.com/RxSwiftCommunity/RxDataSources/issues/169

Our project is huge and we use `unowned self` all over when in a subscription chain clearly held by self's DisposeBag, and using this procedure we don't have any crashes related to that during the 6 months we've been in the App Store - the first one motivated the creation of this issue. However I agree with @kzaher that the example I pasted could have been written in a different way and still avoided the issue. In this case specifically, instead of using `onDispose` to trigger an event, I used `rx.deallocated` (and kept unowned instead of weak).

**Comment by hanl001** [comment]
@kzaher 

> Hi @gobetti ,
> 
> > It is possible that a subscription has its subscribe block executed after the class instance has already deallocated, even if that subscription is held by that instance's DisposeBag. In other words, using unowned self is not entirely safe.
> 
> This is described on top of getting started doc.
> 
> https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#disposing
> 
> > Apparently, the DisposeBag disposes its Disposables individually, allowing events to be handled by the still alive subscriptions in between disposals.
> 
> Yes, this is by design.
> 
> **Dispose logic should never perform anything except disposing, like sending elements**. The code will execute properly, but semantically it causes undefined behavior.

According to this, why is unowned also used in RxSwift(TimerOneOffSink) and RxGesture(TouchDownGestureRecognizer)

**Comment by freak4pc** [comment]
There is very little value bumping a thread from 3 years ago, no one probably remembers much at this point :)
