### ISSUE TITLE
SychronizationErrorMessages misspelling

### ISSUE THREAD

**Issue by FuYouFang** [ReactiveX/RxSwift#1594]
in `Rx.swift` file,  I found a misspelling( `SychronizationErrorMessages`), `Sychronization` should be `Synchronization`(missing `n`).

**Comment by FuYouFang** [comment]
in `Disposable` file, `Respresents` should be `Represents`.

**Comment by kzaher** [comment]
Hi @FuYouFang ,

thnx for reports. I've made the changes. Feel free to open PR if you see some defects like this in future.
