### ISSUE TITLE
CurrentThreadScheduler.swift is incompatible with Swift 4.1

### ISSUE THREAD

**Issue by alanzeino** [ReactiveX/RxSwift#1598]
Luckily, this is the only visible warning out of using master with Swift 4.1. I'll put up a PR for this.

```
RxSwift/RxSwift/Schedulers/CurrentThreadScheduler.swift:54:17: warning: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
            key.deallocate(capacity: 1)
                ^
```

**Comment by freak4pc** [comment]
The main project itself seems to have a few more warnings around 4.1, but library-wise this seems like the only issue. It's pretty much just removing the `capacity:` piece I imagine ?

**Comment by kzaher** [comment]
I think we can close this.
