### ISSUE TITLE
Suggestion how to watch for update location in MVVM 

### ISSUE THREAD

**Issue by suprie** [ReactiveX/RxSwift#160]
Hi, 

so i have a viewModel .
```
    var currentLocation: Variable<CLLocation>?;
```
Somewhere in init 
```
   LocationManager.rx_didUpdateLocations.map { locations in 
      self.currentLocation.value = locations.first
  }
```
And in my view controller : 

```
viewModel?.currentLocation?.subscribeNext { x in
            print(x)
            // do something with the location updated
        }
```

But now, the print(x) is never called. Do you have any suggestion on how to watch the location update?
Or any suggestion with the MVVM and CLLocationManager?

**Comment by carlosypunto** [comment]
In iOS >= 8 there needs to be `NSLocationAlwaysUsageDescription` or `NSLocationWhenInUseUsageDescription` key in `Info.plist` with a message to be displayed in the prompt.

**Comment by suprie** [comment]
Hi carlos, 

I already did that, the location is updated, but the event is not sent. I cannot figured it why. 

If i use 
``` 
locationManager.rx_didUpdateLocations.subscibeNext { locations in 
   print(locations.first)
}
```

it will print the location. But i want to separate between ViewController and the location update, i thought that the best place is in the view model, so ViewController only need to know when the location is updated.

**Comment by kzaher** [comment]
Hi @suprie ,

This should work :)
```
var currentLocation: Variable<CLLocation> = LocationManager.rx_didUpdateLocations.map { locations in 
      return locations.first
  }
```

Why you need to do it this way is described here https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md

Hope this helps :)

**Comment by bontoJR** [comment]
I have this code in a project I am working on and it works:

```
let filteredLocation = DefaultLocationManager.rx_didUpdateLocations
            .map() { locations in
                return locations.filter() { loc in
                    return loc.horizontalAccuracy < 20
                }.first
        }
```

(The `horizontalAccuracy` is necessary to skip the first values that might be completely out of order.)

**Comment by suprie** [comment]
Hi @kzaher , 

I've tried your code, and it error now "cannot convert value of type Observable<CLLocation?> to specified type 'Variable<CLLocation>'

Whats wrong? Anyway i'm reading the getting started now

**Comment by kzaher** [comment]
@suprie , oh sry,

I should have said 

```
let currentLocation = LocationManager.rx_didUpdateLocations.map { locations in 
      return locations.first
  }
```

or @bontoJR 's snippet.

**Comment by kzaher** [comment]
I think this should be fixed, let me know if there are any issues with this :)

**Comment by MobanMichael** [comment]
> Hi,
> 
> so i have a viewModel .
> 
> ```
>     var currentLocation: Variable<CLLocation>?;
> ```
> Somewhere in init
> 
> ```
>    LocationManager.rx_didUpdateLocations.map { locations in 
>       self.currentLocation.value = locations.first
>   }
> ```
> And in my view controller :
> 
> ```
> viewModel?.currentLocation?.subscribeNext { x in
>             print(x)
>             // do something with the location updated
>         }
> ```
> But now, the print(x) is never called. Do you have any suggestion on how to watch the location update?
> Or any suggestion with the MVVM and CLLocationManager?

In this case Are you creating your view model as singleton?
