### ISSUE TITLE
TestScheduler not working for testing AVSpeechSynthesizer

### ISSUE THREAD

**Issue by ivanmkc** [ReactiveX/RxSwift#1600]
**Short description of the issue**:
I want to test the AVSpeechSynthesizer such that I can determine when the AVSpeechSynthesizerDelegate functions fire once I call synthesizer.play. For example:

```swift
func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, willSpeakRangeOfSpeechString characterRange: NSRange, utterance: AVSpeechUtterance)
```
However, the test runs as expected and completes before the callbacks have a chance to fire. How do I block until they do, and what is the general philosophy behind timing with TestScheduler for code where you can't control the scheduling?

**Expected outcome**:

The callbacks fire immediately and register a recorded event on my TestScheduler.

**What actually happens**:

The callbacks fire after the TestScheduler finishes testing.

**Self contained code example that reproduces the issue**:

```swift
//Narrator should pause (i.e. play state is paused) when triggered
//Also: Narrator should resume playing from the same spot when triggered
func testShouldPauseWhenTriggered() {
        SharingScheduler.mock(scheduler: testScheduler) {
            //Start playback
            let playPauseTrigger = testScheduler.createHotObservable([
                Recorded.next(200, ()),
                Recorded.next(220, ()),
                Recorded.next(230, ())
                ])
            
            playPauseTrigger.bind(to: narrator.playPauseTrigger).disposed(by: disposeBag)
            
            let expected = [Recorded.next(0, PlayState.Stopped),
                            Recorded.next(200, .Playing),
                            Recorded.next(220, .Paused),
                            Recorded.next(230, .Playing)]
            
            let playStateRecorded = testScheduler.record(narrator.playState)
            
            //Start
            testScheduler.start()
            
            XCTAssertEqual(playStateRecorded.events, expected)
            
            //TODO: Narrator should resume playing from the same spot when triggered
        }
    }
```

```swift
extension Narrator: AVSpeechSynthesizerDelegate
{
    func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didStart utterance: AVSpeechUtterance) {
        self.playStateSubject.value = .Playing
    }
    
    func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didPause utterance: AVSpeechUtterance) {
        self.playStateSubject.value = .Paused
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
```
RxSwift (4.1.2)
RxTest (4.1.2)
```

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

It's more a question than a request for a fix.

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x ] I have a significant code base

**Comment by kzaher** [comment]
Hi @ivanmkc ,

> However, the test runs as expected and completes before the callbacks have a chance to fire. How do I block until they do, and what is the general philosophy behind timing with TestScheduler for code where you can't control the scheduling?

This is not a RxSwift issue. Google dependency injection.

This doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
