### ISSUE TITLE
It looks like GithubSearchRepository is not working at all?

### ISSUE THREAD

**Issue by hengsokvisal** [ReactiveX/RxSwift#1603]
**Short description of the issue**:

#It looks like GithubSearchRepository is not working at all?

**Expected outcome**:

I was expect when I type something in the searchbox, it will give back repositories as a result.

**What actually happens**:

When I type something in the search box , it show nothing beside a blank tableview as a result.

**Platform/Environment**

  - [ yes] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
 9.2
```

**Installation method**:
  - [yes] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [yes] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [yes] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @hengsokvisal ,

I think it should work now. I've pushed a fix for this.
