### ISSUE TITLE
 I can't compile it when I use Carthage

### ISSUE THREAD

**Issue by MorningStarJ** [ReactiveX/RxSwift#1608]
add 'github "ReactiveX/RxSwift" ~> 4.0' to Cartfile
then 'carthage update'

 the temrinal said
*** Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."

my carthage version: 0.29.0

**Comment by marols** [comment]
I'm experiencing the same issue.

(Xcode 9.3, Swift 4.1, Carthage 0.29.0)

**Comment by soleo** [comment]
Used `carthage update --platform iOS --no-use-binaries` to work arround

**Comment by MorningStarJ** [comment]
@soleo That will checking out `RxSwift at "4.0.0-rc.0"` if i use `carthage update RxSwift --platform iOS --no-use-binaries`

**Comment by kzaher** [comment]
Hi @MorningStarJ ,

The command @soleo provided 
`carthage update RxSwift --platform iOS --no-use-binaries`
should work as far as I can tell. If it doesn't, then this is Carthage issue, and this is not a proper repo.

We'll publish new version with new binary soon.

**Comment by marols** [comment]
@kzaher Does this mean that the real problem is the binary needs to be recompiled with a newer version of Swift?

**Comment by kzaher** [comment]
yes

**Comment by marols** [comment]
Okay, thanks
