### ISSUE TITLE
Ditch iOS7 support?

### ISSUE THREAD

**Issue by orta** [ReactiveX/RxSwift#161]
I don't know how many implementation details this changes, but it might be worth cutting off 7.0 support in the README and in the framework now that 9.0 is out.

**Comment by kzaher** [comment]
Hi @orta,

I've been thinking about this. 

I don't know, so far iOS 7 isn't causing much pain points for us, but I would need to investigate this more.

The thing I'm most worried about is actually how Swift compiler behaves on iOS 7 :), we've had some issues there.

I'm also curious how many people are planning to use Rx on iOS7, so if you are, you can let me know here :)

**Comment by bontoJR** [comment]
I'm with @orta to drop support :)

**Comment by dtartaglia** [comment]
I'm thinking that the library should be able to support iOS 7 in that if the programmer is targeting iOS 7 in his Xcode 7 project, he should have any problems. That way the programmer is using the latest Xcode tools and Swift compiler so @kzaher's issues are taken care of, but if the programmer still needs to deploy on iOS 7 devices he can. As long as nobody is having to put huge work-arounds into the code, I don't see a problem.

That's my 2p.

**Comment by croccio** [comment]
please, no drop ios7 support

**Comment by tomahh** [comment]
iOS7 is still a big thing amongst our app's userbase. We import rxswift manually, but it's a blessing to be able to do so.

So, yeah, please don't drop support if can do so.

**Comment by bontoJR** [comment]
Ok, I think that's enough, let's keep iOS 7 supported with project import :)
I don't see any specific issue with that, most of the things we are using in RxSwift are iOS 4.0+.

I think also in RxCocoa with the new `@availability` annotation shouldn't be too hard, isn't it @kzaher?

**Comment by kzaher** [comment]
I think that most problems are related with Swift compiler :)

If Swift compiler can generate correct assembler for iOS 7 then it shouldn't be a bug problem, otherwise ... argh :(

And yes, it has failed to do so in some instances in past :(

**Comment by bontoJR** [comment]
Closing this, iOS 7 will stay supported as long as there are no excessive problems while compiling.

**Comment by yury** [comment]
Thanks
