### ISSUE TITLE
Ambiguous use of distinctUntilChanged() on Observables with optional values

### ISSUE THREAD

**Issue by Nailer** [ReactiveX/RxSwift#1611]
**Short description of the issue**:

Calling the distinctUntilChanged() method on any observable sequence with an optional value will cause a compiler error complaining about ambiguous methods.

**Expected outcome**:

That the code compiles.

**What actually happens**:

Code does not compile, and yields error:
Ambiguous use of 'distinctUntilChanged()'

**Self contained code example that reproduces the issue**:

```swift
       let stringObservable: Observable<String?> = Observable<String?>.from(optional: nil)
        stringObservable.distinctUntilChanged()
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 4.1.2

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 9.3 release version
```

**Comment by Nailer** [comment]
Current workaround is to use:
`.distinctUntilChanged({ $0 == $1 })`

Proposed fix in RxSwift:
Delete distinctUntilChanged() definition from Driver+Optional.swift and Observable+Optional.swift

**Comment by kzaher** [comment]
@Nailer we don't have `Driver+Optional.swift and Observable+Optional.swift` files here.

**Comment by vzsg** [comment]
Those seem to be part of [RxOptional](https://github.com/RxSwiftCommunity/RxOptional/blob/master/Source/Observable%2BOptional.swift), not RxSwift after all. And it was fixed, but not tagged.

**Comment by Nailer** [comment]
My mistake! I didn't check this before submitting.

**Comment by Nailer** [comment]
Closing the issue since it's fixed in RxOptional
