### ISSUE TITLE
rx.observe

### ISSUE THREAD

**Issue by appbanana** [ReactiveX/RxSwift#1617]
_ = self.rx.observe(String.self, "testStr").subscribe(onNext: {[weak self] (value) in
            DLog(message: self)
        })     
When I detect a change in the properties of an object, I find that it causes a memory leak, how can I solve this problem.

        _ = self.rx.observe(String.self, "testStr").subscribe(onNext: {[weak self] (value) in
            DLog(message: self)
            
        }).dispose()
If I add the method of  dispose() , it can only detect the initial value. The properties of an object can be not detected when it changes again.

how can I solve this problem?

**Comment by kzaher** [comment]
This is by design,

`observeWeakly` doesn't retain.
