### ISSUE TITLE
Chaining operations with RxSwift

### ISSUE THREAD

**Issue by tosbaha** [ReactiveX/RxSwift#1620]
**Short description of the issue**:
I tried to ask same question on StackOverflow and slack channel but I didn't get a response. I am sorry if this is not the right place.

I want to chain following operations

- createUserandVerify
  - Create Anonymous User (user)
  - Verify User -> verifiedUser
  - If verification successful return verifiedUser else return user
- Get stuff with coredata `getStuff`
  - If stuff.count > 0 Upload stuff with user credentials `uploadStuff`
- Finally report the result of all operations

I wrote createUserandVerify as below. I wonder how should I write `uploadStuff` in reactive way. Upload function depends on user credentials. Therefore It must only run after `createUserandVerify`. I know I could just check count of array inside `uploadStuff` and return empty but I wonder the best practices. I tried to use `withLatestFrom` but it immediately runs the `uploadStuff`.

**Expected outcome**:

 Chaining operations based on previous output

**What actually happens**:

 I am looking for best practices

**Self contained code example that reproduces the issue**:

```swift
func createUserandVerify() -> Single<User> {
    return Service.sharedInstance.generateAnonUser()
        .flatMap{ user in
            if Service.sharedInstance.isOldRegisteredUser {
                print("It is old user")
                // We need to verify the receipt
                return  Service.sharedInstance.verifyReceipt()
                    .flatMap { verifiedUser in
                        print("Returning Verified new user [Verification Success]")
                        return Single.just((verifiedUser))

                    }.catchError{ error ->Single<User> in
                        print("Returning firstly created user [Verification Failed]")
                        print("Error Type: \(error)")
                        return Single.just(user)

                }
            } else {
                //Normal anonymous old user
                print("Returning firstly created user [Anonymous]")
                return Single.just(user)
            }
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 9.3 (9E145)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by tosbaha** [comment]
I asked at Stackoverflow and Slack. I am once again deeply sorry for spamming the issues.
