### ISSUE TITLE
`take(_ duration:scheduler:)` and `take(_ count:)` usage ambiguity

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1625]
There is a great confusion between `take(_ duration:scheduler:)` and `take(_ count:)` in the sense they both don't require a label for the first argument.

### take(_ duration:scheduler:) : 
https://github.com/ReactiveX/RxSwift/blob/f1e215a3fe1303568e415095cb00a6ca2a27b706/RxSwift/Observables/Take.swift#L41

### take(_ count:) :

https://github.com/ReactiveX/RxSwift/blob/f1e215a3fe1303568e415095cb00a6ca2a27b706/RxSwift/Observables/Take.swift#L19

I would suggest dropping the `_` from the duration variation, making it `take(duration:scheduler:)` to get rid of the ambiguity. 

This was noticed when @irace asked a question with an example that uses both of them in the same sequence, with code similar to this: 

```swift
observable
  .take(5)
  .take(8, scheduler: MainScheduler.instance)
```

There is no real way to know what the latter does. The "count" one makes sense to be label-less.

This can be done via either
1. Soft deprecating in a minor patch
2. Hard deprecating in next major
3. A combination of both (stepped deprecation)

Let me know your thoughts.

**Comment by freak4pc** [comment]
Hey, thanks for your answer @kzaher :)

#1472 seems like a different issue involving switching everything to `DispatchTimeInterval` (which should also be minor, i don't mind doing it) 

But I think this specific PR will only be about:

1. Creating the new signature
2. Soft-deprecating and moving to `Deprecated.swift`: Do you prefer using DeprecationWarner like Variable, or just go for a `@availble` deprecation clause for a warning, since its a relatively minor change?

**Comment by kzaher** [comment]
Hi @freak4pc ,

It's maybe a separate issue, but it affects interface of this particular method, doesn't it?

**Comment by freak4pc** [comment]
Hey @kzaher :)

I agree, but you wrote: 
> but that is part of a more global change.

I'll take care of this PR. 

Regarding deprecation, do you want to go with a runtime warning of a build-time warning (e.g. `@available`) ? I think the latter makes more sense given its such a lesser-used method and very small fix.

**Comment by freak4pc** [comment]
A PR for this is up: #1658

**Comment by freak4pc** [comment]
PS Regarding `DispatchTimeInterval` - this would be a _much_ more wide-spread and low-level change (as it also possibly affects Schedulers and almost every "timed" aspect of Rx), so It should definitely be part of a different PR while taking into consideration retaining existing behavior.

**Comment by freak4pc** [comment]
We still haevn't fixed this ambiguity. Shouldn't we resolve the ambiguity even without using DispatchTimeInterval for schedulers?

**Comment by kzaher** [comment]
We need to expose DispatchTimeInterval first. 

We aren’t going to have 2 deprecations for the same API.

**Comment by freak4pc** [comment]
Basically I understand - buy don't you feel like DispatchTimeInterval will only be part of RxSwift 5 at this point? I'm not super excited to block any good API additions just because of a change that might happen in a few months (even if its part of RxSwift 4, it will take a long time to get to as its a fundamental change)

**Comment by freak4pc** [comment]
@kzaher I might do this as well for RxSwift 5 after you tackle the DispatchTimeInterval thing

**Comment by kzaher** [comment]
There is no more ambiguity.

Now it it's 
```
observable
  .take(5)
  .take(.milliseconds(8), scheduler: MainScheduler.instance)
```

I'm not sure is this still a problem. Feel free to reopen this if you see something problematic.

**Comment by freak4pc** [comment]
There's no type ambiguity, but I still thing we should disambiguate the signature. 

Either making the first variation `take(count:)` or the second one either `take(duration:)` or `take(for duration:)`. 

Even though the types are different, I don't feel it's enough to understand what it does.

**Comment by fpillet** [comment]
I side with @freak4pc on this one. Historically, `take(_ count:)` is fine and "standard" as it exists in RxJava. I would add a named parameter like `take(during:)` (I feel that `during` is better than `duration` but it's a minor point).

**Comment by kzaher** [comment]
I think we shouldn't discuss about particular operators, but about policies how to name operators.

We can argue about how to name particular operators for ages, but unless there is consistency across the operators I think we will probably cause more harm than good.

The downside of the current naming is that somebody could accidentally mistake it with count version. 
I'm not sure this is possible since it takes a scheduler like all temporal operators.

Why would we put label here and not on `throttle`, `timer`, `debounce`, `delay`, `delaySubscription`, `skip`, `timeout`, ....

The only ones we have label on are `buffer` and `window` because they have both temporal and numeric parameters.
