### ISSUE TITLE
Example for UITabBar+Rx

### ISSUE THREAD

**Issue by AshleyDeng** [ReactiveX/RxSwift#1627]
**Short description of the issue**:

Wanted make UITabBarController reactive. Example is to subscribe the `tabBar(_:didSelect:)` event from UITabBarDelegate.

**Expected outcome**:

Able to run the code and print info.

**What actually happens**:

XCode throws exception: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Changing the delegate of a tab bar managed by a tab bar controller is not allowed.'`

**Self contained code example that reproduces the issue**:

```swift
class MyTabBarController: UITabBarController {
  private let disposeBag = DisposeBag()
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    tabBar.rx.didSelectItem
      .subscribe(onNext: { tab in
        print(tab)
      })
      .disposed(by: disposeBag)
  }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift -> 4.1.2
RxCocoa -> 4.1.2

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
A tab bar controller already manages its own delegate. Can you use a simple `UITabBar` instead or just use `UITabBarController+Rx`, e.g. `rx.didSelect` ?
