### ISSUE TITLE
Instrument Leaks work nothing

### ISSUE THREAD

**Issue by Caolongs** [ReactiveX/RxSwift#1631]
**Short description of the issue**:

  Instrument Leaks work nothing...

Download this [Example](https://github.com/ReactiveX/RxSwift) , `command+i` -> `leaks` ,and just end, do not  monitor 

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**RxSwift version**:

```
4.1.2
```
**Xcode version**:

```
Version 9.3 
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @Caolongs ,

I believe this is Xcode issue. Don't think we can do anything about this in this repo. Sorry. Please report this issue to Apple.

¯\\\_(ツ)\_/¯
