### ISSUE TITLE
Can't run `swift test` on Linux

### ISSUE THREAD

**Issue by felix91gr** [ReactiveX/RxSwift#1637]
**Short description of the issue**:

Can't run SPM's `swift test` command on Linux

**Expected outcome**:

Tests to be run with a summary at the end.

**What actually happens**:

Got this output:

`error: no tests found; create a target in the 'Tests' directory`

**Self contained code example that reproduces the issue**:

```bash
git clone https://github.com/ReactiveX/RxSwift rxSwift
cd rxSwift
git checkout 4.1.2
swift test
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Release `4.1.2`

**Platform/Environment**
  
Linux (Ubuntu 16.04). I'd test it in a Mac as well, if I had one :sweat_smile: 

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**~Xcode~ Swift toolchain version**:

Swift 4.1, release for Ubuntu 16.04

**Installation method**:

None of the above

**I have multiple versions of Xcode installed**:

  - N/A

**Level of RxSwift knowledge**:
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @felix91gr ,

Please take a look at our CI about how to run unit tests on Linux. We can't support classical `swift test` because of Swift package manager limited functionality regarding tests.

**Comment by kzaher** [comment]
Hi @felix91gr ,

yes, I believe that to run the tests on Linux or Unix you should perform `./scripts/all-tests.sh Unix`.

**Comment by felix91gr** [comment]
Thank you!

I think that's all I had to ask. 

If I may add something else: does this appear in the docs somewhere? Because I didn't find it when I was looking for it. 

It's probably somewhere and I should've `grep`'d it 🤔. But if it isn't, then should it appear somewhere? At least so that other users like me don't have to ask about how to test RxSwift.

**Comment by kzaher** [comment]
Hi @felix91gr ,

Our CI file represents the documentation as far as I can tell since anyone merging anything into this repo will need to fight with CI.

Even if you just run `./scripts/all-tests.sh` without any parameters it will still work.

This will probably create some frustrations, yes, but I'm not convinced that documenting this somewhere else in this repo will improve the situation.

**Comment by felix91gr** [comment]
I was thinking that for people who want to check that everything works in
their machines by running the tests, having it noted somewhere would be
very nice :)
