### ISSUE TITLE
Crash when running with Xcode 9.3's default Release configuration

### ISSUE THREAD

**Issue by macdrevx** [ReactiveX/RxSwift#1640]
**Short description of the issue**:

A simple Rx snippet crashes when compiled with Xcode 9.3's default Release configuration.

**Expected outcome**:

Shouldn't crash

**What actually happens**:

Results in a crash

**Self contained code example that reproduces the issue**:

```swift
let subject = PublishSubject<Int>()
_ = Observable.just(1)
    .do(onNext: subject.onNext)
    .subscribe()
```

Here's a sample project that's already configured to use the Release build configuration for the Run action: [Crasher.zip](https://github.com/ReactiveX/RxSwift/files/1968218/Crasher.zip)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.1.2

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 9.3 (9E145)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by macdrevx** [comment]
Cross-posted here: https://bugs.swift.org/browse/SR-7585

**Comment by freak4pc** [comment]
See https://github.com/ReactiveX/RxSwift/issues/1555#issuecomment-379916369

**Comment by macdrevx** [comment]
@freak4pc perfect. Thank you.
