### ISSUE TITLE
playground does not work in swift 4

### ISSUE THREAD

**Issue by SNThunderbolt** [ReactiveX/RxSwift#1643]
<img width="2054" alt="screen shot 2018-05-06 at 9 56 30 am" src="https://user-images.githubusercontent.com/11421870/39670159-cc6d98de-5113-11e8-9670-7c8ab875b4a7.png">
hi
I'm trying to use rx.playground. I built the rxSwift-macOS successfully
but when I go to rx playground the debug area shows nothing! I tried using TryYourself.playground still
 nothing, I commented out everything and just printed "hi" but nothing seems to work.
could anyone help me please?

I'm using Xcode 9.3 and macOS HighSierra.

**Comment by kzaher** [comment]
Hi @SNThunderbolt ,

please file issue template.
