### ISSUE TITLE
Crash: SingleAssignmentDisposable does not implement methodSignatureForSelector

### ISSUE THREAD

**Issue by gobetti** [ReactiveX/RxSwift#1647]
**Short description of the issue**:

  There is a specific scenario in our application where a crash occurs with the following message:
```
*** NSForwarding: warning: object 0x7fc0d6868ba0 of class 'RxSwift.SingleAssignmentDisposable' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[RxSwift.SingleAssignmentDisposable runInContext:]
```
Do you have any idea what it could be, or how can I obtain further helpful data for investigation?

**Self contained code example that reproduces the issue**:
Unknown

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
3.6.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
(Not checking anything since I don't have a self-contained code)

**Xcode version**:

```
  9.3
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @gobetti ,

sorry, this doesn't looks like and RxSwift issue. It doesn't provide any steps to reproduce this and this library doesn't use `runInContext` selector.
