### ISSUE TITLE
New binary release for Carthage

### ISSUE THREAD

**Issue by marbetschar** [ReactiveX/RxSwift#1655]
Seeing the following output when using Carthage:

```
*** Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
```

got the following lines in my Cartfile:

```
github "RxSwiftCommunity/RxRealm" ~> 0.7
github "RxSwiftCommunity/RxDataSources" ~> 3.0
```

Would be great to have a new binary release compiled with Swift 4.1.

**Comment by kzaher** [comment]
Hi @marbetschar ,

As far as I can tell new Xcode releases that contain Swift 4.1 compiler have been too unstable for production use. We are waiting for some production ready Swift compiler version.

For more info, please take a look at https://github.com/ReactiveX/RxSwift/issues/1555

**Comment by karimkhamwani** [comment]
same issue.

**Comment by kzaher** [comment]
This is kind of the same as #1668, so let's track this there.
