### ISSUE TITLE
BehaviorRelay<Void> does not get onNext() event

### ISSUE THREAD

**Issue by bdolewski** [ReactiveX/RxSwift#1656]
**Short description of the issue**:
Hi everyone,
I'm using `var closed: BehaviorRelay<Void>` in my view-model to notify coordinator/flow from upper layer that view is "closed" (some MVVM architecture). I need that var just to notify some other class that there is `onNext()` event, I don't care about element that this event carries on.

However if put code like this:
`
    func closeTapped() {
        outputs.closed.accept(()) // <-- THIS
    }
`

then I don't receive any `onNext()` events. I need to use `var closed: BehaviorRelay<Bool>` and put `true` or `false` in `accept()`.

I'm 95% sure that I'm doing something wrong and there are better solution for this (`Completable`?)
Maybe 5% that it's a bug.

**Expected outcome**:

I get `onNext()`

**What actually happens**:

No `onNext()` element

**Self contained code example that reproduces the issue**:
I'm writing this from my memory, sorry about any syntax errors:

```
    let closed = BehaviorRelay<Void>.init(value: ())
    let bag = DisposeBag()
    _ = closed
        .asObservable()
        .subscribe(onNext: {
            print("onNext")
        })
        .disposed(by: bag)
    
    closed.accept(())
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

We're using gitsubmodule in our project.
HEAD: 3e848781c7756accced855a6317a4c2ff5e8588b Release 4.1.2

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 9.3.1 (9E501)
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [x ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @bdolewski ,

you are using local disposeBag, please take a look at how they are used in example project.
