### ISSUE TITLE
Playground execution failed for error: Couldn't lookup symbols

### ISSUE THREAD

**Issue by seanLee** [ReactiveX/RxSwift#1660]
**Short description of the issue**:

I am watching a course about RxSwift.Few days ago I run the code well in Playground.But this period I do the same thing,console print this:
```
Playground execution failed:

error: Couldn't lookup symbols:
  __T07RxSwift14ObservableTypePAAE2ofAA0C0Cy1EQzGSayAHGd_AA018ImmediateSchedulerD0_p9schedulertFZ
  __T07RxSwift10ObservableCMa
  __T07RxSwift14ObservableTypePAAE4fromAA0C0Cy1EQzGSayAHG_AA018ImmediateSchedulerD0_p9schedulertFZfA0_
  __T07RxSwift14ObservableTypePAAE4justAA0C0Cy1EQzGAHFZ
  __T07RxSwift10ObservableCyxGAA0C4TypeAAlWa
  __T07RxSwift14ObservableTypePAAE2ofAA0C0Cy1EQzGSayAHGd_AA018ImmediateSchedulerD0_p9schedulertFZfA0_
  __T07RxSwift14ObservableTypePAAE4fromAA0C0Cy1EQzGSayAHG_AA018ImmediateSchedulerD0_p9schedulertFZ

```
that is the pofile:
```
platform :ios, '11.0'

target 'RxSwiftPlayground' do
  use_frameworks!
  
  # Pods for RxSwiftPlayground
  pod 'RxSwift', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end

```
I have some ideas that may Xcode made this issues
**Self contained code example that reproduces the issue**:

```swift
  I can't even define a const value.
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
 Both Xcode9.3 and Xcode9.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] I have a significant code base

**Comment by warrenrentlytics** [comment]
I was trying to work through a Ray Wenderlich book and all of us are were having similar errors. Try this for the Podfile instead:

```
platform :ios, '11.0'

target 'RxSwiftPlayground' do
  use_frameworks!
  
  # Pods for RxSwiftPlayground
  pod 'RxSwift', '~> 4.0'
end

post_install do |installer|
    
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
```

Reinstall the pods and open the new workspace. Xcode error out initially but eventually the Playground ran.

Found that answer at https://forums.raywenderlich.com/t/playground-does-not-execute-on-first-chapter/41341/27 .

**Comment by seanLee** [comment]
@warrenrentlytics me too.And I found that if I downgrade my cocoapods version, the message was gone.I will try ur solution.Thank you so much.

**Comment by Gerald-Alpha** [comment]
The method described by @GABHISEKBUNTY works well for Xcode 9.3.

**Comment by tedgonzalez** [comment]
The method described by @GABHISEKBUNTY works well for Xcode 9.4.1.

**Comment by maheshm255** [comment]
The method described by @GABHISEKBUNTY  works well  using Xcode 9.4.

**Comment by freak4pc** [comment]
Hey all :) I appreciate your reporting, but its enough to +1 the author's comment instead of repeating the comments here. Thanks !

**Comment by chrisco314** [comment]
The posted solution of resetting CONFIGURATION_BUILD_DIR didn't work for me due to other libraries that it broke (Apollo), but this appears to be related to a bug introduced in cocoapods 1.5.0.  My solution was to roll back to cocoapods 1.4.0, and that worked.

**Comment by kmaciejczyk** [comment]
The method described by @GABHISEKBUNTY  works for Xcode 10.1. Thanks.

**Comment by Yoges-hatched** [comment]
The method described by @GABHISEKBUNTY works for Xcode 11.3.1 
Thanks.

**Comment by ayemereodia2** [comment]
Delete your PodFolder, open a path to your project and run "pod install"
