### ISSUE TITLE
New Carthage Binary for Xcode 9.4

### ISSUE THREAD

**Issue by eridbardhaj** [ReactiveX/RxSwift#1668]
Currently the Swift version with **Xcode 9.4** was updated to **4.1.2** therefore we cannot use it with **Xcode 9.4**, as it will produce the following error:

> Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).

It would be really nice to have an update on this

**Comment by kzaher** [comment]
Hi @eridbardhaj ,

I've just moved to Switzerland last Saturday, so I'm still trying to catch a breath. I'm hoping that in a couple of days things will start to return to normal, but right now they are a complete mess.

I'll try to cut a new release in the next couple of days and try to start processing PRs, but right now I'm too exhausted and need some sleep.

The bottom line is that I have this in queue, but it will unfortunately take a bit more time.
