### ISSUE TITLE
withLatestFrom up to 3 other observables

### ISSUE THREAD

**Issue by amlcurran** [ReactiveX/RxSwift#1672]
**Short description of the issue**:

We're currently implementing an app across Android and iOS and are making large effort to keep the codebases aligned.

In RxJava, the [`withLatestFrom`](http://reactivex.io/documentation/operators/combinelatest.html) function takes up to [three other observables](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#withLatestFrom-io.reactivex.ObservableSource-io.reactivex.ObservableSource-io.reactivex.ObservableSource-io.reactivex.functions.Function4-) to combine with. However, RxSwift [only accepts one other](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Observables/WithLatestFrom.swift). This mismatch in APIs results in a mismatch of our code.

Would this be considered as an addition to the RxSwift API? I would be happy to implement it.

**Expected outcome**:

I can use `withLatestFrom(..)` with up to three additional observables

**What actually happens**:

I can only use `withLatestFrom(..)` with one more observable

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by sergdort** [comment]
Hi, @amlcurran !

I feel like you can achieve this by adding extension e.g

```swift
extension Observable {
    func withLatesFrom<T, U, R>(other1: Observable<T>, other2: Observable<U>, selector: (T, U) -> R) -> Observable<R> {
        return Observable.zip(self.withLatestFrom(other1), self.withLatestFrom(other2), selector)
    } 
}
```

Not sure if it worth to add this overload to the library tho :)

**Comment by kzaher** [comment]
I agree with @sergdort , but I would suggest using this form

```swift
func withLatesFrom<T, U, R>(other1: Observable<T>, other2: Observable<U>, selector: @escaping (E, T, U) -> R) -> Observable<R> {
        return self.withLatestFrom(Observable<Any>.combineLatest(
            other1,
            other2
        )) { x, y in selector(x, y.0, y.1) }
    }
```
