### ISSUE TITLE
What's the operator to complete once any Completable completes?

### ISSUE THREAD

**Issue by gobetti** [ReactiveX/RxSwift#1674]
**Short description of the issue**:

I was looking for a way to have a sequence to complete when any of the specified Completables complete. That looked similar to the logic of "having a sequence to trigger `next` whenever any of the specified Observables do so" (aka `merge`) so I thought `Completable.merge` would do that, but actually it completes only once all Completables have completed.

Thinking further, on one hand that makes sense because `Observable.merge` will also complete only once all of its Observables have completed; on the other hand, there used to be `Completable.zip` but apparently it was replaced by `Completable.merge` (with a chance of adding `zip` back someday according to #1245), and `Completable.zip` sounds more immediate as an operator to complete once all Completables have completed.

**Expected outcome**:

- `Completable.zip` completes when _all_ of the Completables do so, and `Completable.merge` completes when _any_ of the Completables do so
- Or keep things as they are and introduce another operator (unless already existent) that completes when any of Completables do so

**What actually happens**:

- `Completable.merge` completes only once all Completables have completed
- RxSwift 3.x: `Completable.zip` completes only once all Completables have completed, RxSwift 4.x: there's no `Completable.zip`
- Missing (?) operator that completes once any of the specified Completables complete

**Self contained code example that reproduces the issue**:

```swift
Completable.merge(.empty(), .never()).debug().subscribe()
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.6.1 and 4.2.0

**Xcode version**:

```
  9.3.1
```

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @gobetti ,

we can add alias `zip` = `merge` in RxSwift 5.0. We first need to clean up zip.

**Comment by gobetti** [comment]
That's ok @kzaher, thanks for rocket fast answer! Do we have another operator that accomplishes what I expected from `Completable.merge`?

**Comment by kzaher** [comment]
If it emits and elements, then yes, we have `amb`, but it won't work for completable in its current form. We could add `amb` to `Single` though if it doesn't already exist.

**Comment by gobetti** [comment]
I can work on adding it Completable! This completes fine:
```swift
Observable.amb([
  Completable.empty().asObservable(),
  Completable.never().asObservable()
])
```

**Comment by vandadnp** [comment]
Here is an extension on `Completable` to add the `amb` operator:

```swift
extension PrimitiveSequence where Trait == CompletableTrait, Element == Swift.Never {
    /**
     Propagates the completable that reacts first.
     
     - Parameter sources: array of completables
     - Returns: A completable that surfaces any of the given completables, whichever reacted first.
     */
    static func amb(_ sources: [Completable]) -> Completable {
        return Observable.amb(sources.map { $0.asObservable() }).makeCompletable()
    }
}
```

Hope it helps somebody

**Comment by kzaher** [comment]
I've been thinking about this, and I think it makes sense to only support `amb` if you want this behavior.
