### ISSUE TITLE
Add asObserver() on Variable

### ISSUE THREAD

**Issue by PhilippeCuvillier** [ReactiveX/RxSwift#1686]
*Short description of missing functionality*:

Would it be interesting to have a `asObserver()` method on `Variable`?

*Short code example of how you would like to use the API*:

```swift
protocol ControllerType {
    var input: AnyObserver<Int>  { get }
}

struct Controller {
    public let input: AnyObserver<Int>

    private let variable = Variable<Int>(0)

    init() {
        input = variable.asObserver()
    }
}

let inputData: Observable<Int> = /* ... */
let controller: ControllerType = Controller()

let disposeBag = DisposeBag()
inputData
    .bind(to: controller.input)
    .disposed(by: disposeBag)
```

*The reason why I need this functionality*:

This would allow implementing an `AnyObserver`  interface (_e.g._ in the `ControllerType` protocol above) with a `Variable` instead of a `Subject`.

*Code I have right now*:

Would the following implementation be enough?

```swift
extension Variable {
    public func asObserver() -> AnyObserver<E> {
        return AnyObserver { event in
            if let newValue = event.element {
                self.value = newValue
            }
        }
    }
}
```

Or maybe with some error handling like `bind(to:)`:

```swift
extension Variable {
    public func asObserver() -> AnyObserver<E> {
        return AnyObserver { event in
            switch event {
            case let .next(element):
                self.value = element
            case let .error(error):
                let error = "Binding error to variable: \(error)"
            #if DEBUG
                rxFatalError(error)
            #else
                print(error)
            #endif
            case .completed:
                break
            }
        }
    }
}
```

(Sorry if this feature request duplicates an existing one)

**Comment by kzaher** [comment]
Hi @PhilippeCuvillier ,

I understand why you would want something like that. If we add generic errors in future, we can consider doing this.

I don't like to have many 
```
            #if DEBUG
                rxFatalError(error)
            #else
                print(error)
            #endif
```

in code. So far we've added only most useful bindings.

Hope it makes sense.

Let's defer this.

**Comment by PhilippeCuvillier** [comment]
Hi, thank you very much for your answer.
I get the point with avoiding constructions that involves fatalError()-like calls.

By the way, may I ask you why Relays do not have such asObserver() operators?
