### ISSUE TITLE
I am getting this error in angular6 when I did upgrade from to angular6.

### ISSUE THREAD

**Issue by Mujeeb017** [ReactiveX/RxSwift#1688]
Property 'shareReplay' does not exist on type 'Observable<Object>'.

**Comment by sergdort** [comment]
`angular6`?

**Comment by Mujeeb017** [comment]
yes in angular6?

**Comment by sergdort** [comment]
Isn't it JS library?

**Comment by kzaher** [comment]
Hi @Mujeeb017 ,

you should ask the question here https://github.com/ReactiveX/rxjs/issues. This is Swift repo.
