### ISSUE TITLE
GitHubSearchRepositories Example not paginating

### ISSUE THREAD

**Issue by nmdias** [ReactiveX/RxSwift#1689]
**Short description of the issue**:

 GitHubSearchRepositories Example not Paginating

**Expected outcome**:

  Fetching next page when `isNearBottomEdge` returns true

**What actually happens**:

  No Pagination occurs

**Self contained code example that reproduces the issue**:

The iOS Example of `GitHubSearchRepositories` in RxSwift [Zürich](https://github.com/ReactiveX/RxSwift/releases/tag/4.2.0) version, built with Xcode Version 9.4.1 (9F2000)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.4.1
```

**I have multiple versions of Xcode installed**:
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Oh shoot,

I've failed to implement equality operator when I didn't even need to implement it :/ Pushed fix to develop, should be ok now.
