### ISSUE TITLE
`Observable<String?>.combineLatest(oX.withLatestFrom(o2), o1) { $0 ?? $1 }` always returns `$0` after first event on `oX`. Why?

### ISSUE THREAD

**Issue by Sajjon** [ReactiveX/RxSwift#1691]
[I asked for help on Slack, yesterday, no reply](https://rxswift.slack.com/files/U7WHU2TT9/FBNTN6R2T/read_email_from_service__enable_input_from_uitextfield__being_able_to_restore_to_account_email.swift)

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

I have a view where I ask the user for her email address in a UITextField. I prefill the field with
an email address associated with her `user account`, fetched by some `AccountService`. 
this service returns an Optional String. If the text field is prefilled with an email from her account
it should always be possible for the user to type in some other email. And also clear the field using 
the native clear button in the TextField. To complicate things I have also added a right button to the
UITextField, called `resetToEmailFromAccountButton`, when pressed the textfield should revert back
to the email address from the account (if any).
My code below is a bit simplified version of my real code, but it captures the most important parts. 
My problem: When having pressed `resetToEmailFromAccountButton` once, I can no longer change the 
email by entering another one - the signal always uses the email from the account (service).
I have tried using Driver<String?> as much as possible but changed to Observables here, Driver
did not work either. If I understood it correctly, when working with Views, as I do below
(mostly, except the Account Service), it is preferred to use `Driver`?

**Expected outcome**:
I expect `resetToEmailFromAccountButton` button tap to only reset email once, and then when I type characters in the UITextField, those should be used. 

**What actually happens**:

After having pressed the `resetToEmailFromAccountButton` button once, forever the Observable `email` only emits the email fetched from Account service.

**Self contained code example that reproduces the issue**:

```swift
import RxCocoa

// ########### SOMEWHERE IN A VIEW/VIEWCONTROLLER ########### 
// Views
let emailTextField: UITextField
let resetToEmailFromAccountButton: UIButton
emailTextField.leftView = resetToEmailFromAccountButton
emailTextField.clearButtonMode = .always // should be possible to clear

// OBSERVABLES FROM VIEWS
let emailControlProperty: ControlProperty<String?> = emailTextField.rx.text
let resetToEmailFromAccount: Observable<Void> = resetToEmailFromAccountButton.rx.tap

// API/SERVICE OBSERVALBE
// getAccount() -> Observable<Account> // `Account` has property `email: String?`
let emailFromAccountService: Observable<String?> = accountService.getAccount().map { $0.email }

// ########### RX LOGIC ########### 
let emailFromTextField: Observable<String?> = emailControlProperty.asObservable()
 						.skip(1) // starts with `""` (empty string event) - WHY? This is unwanted. Skip it.
 						.startWith(nil) // we want to start with `nil`

let emailFromAccountServiceManuallyRequested: Observable<String?> = resetToEmailFromAccount.withLatestFrom(emailFromAccountService) { _, fromAccount in
	return fromAccount
}
.startWith(nil) // If I dont use `startWith(nil)` here, the TextField doesn't get populated with email from Service...? Why? 


// !!!!! HELP NEEDED !!!!!
// The observable below stops working when user has pressed button `resetToEmailFromAccountButton` once, 
// then this observable ALWAYS returns element from Observable `emailFromAccountServiceManuallyRequested`
// I think I am missing some operation/command that makes 
// `emailFromAccountServiceManuallyRequested` when use in `combineLatest` below, only emit events
// After having a "new" button tap.
// What am I missing?
let email = Observable<String?>.combineLatest(
    emailFromAccountServiceManuallyRequested,
    emailFromTextField,
    emailFromAccountService
) { (restoredFromAccount: String?, fromField: String?, fallbackToAccountEmail: String?) in
	return restoredFromAccount ?? // PRIO 1: Always set email to the one fetched from account service (IF ANY), since the user activly chose this (button tap)
			fromField ?? // PRIO 2: Email input in textfield by user has prio over email from account
			fallbackToAccountEmail // PRIO 3: Initial value if present - read email from account (service).
}


// ########### UPDATE VIEW ########### 
let emailDriver: Driver<String?> = email.asDriver()

emailDriver.drive(emailControlProperty)
			.disposed(by: someBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
`Podfile.lock`:
  - RxCocoa (4.1.2):
    - RxSwift (~> 4.0)
  - RxSwift (4.1.2)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
```
9.4.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (10.0 beta2)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @Sajjon ,

Please try Slack. Unfortunately this is not a support channel. It is possible that nobody will have time to answer you on Slack channel, but that doesn't change the fact that this channel is only for reporting issues.

Sorry
