### ISSUE TITLE
_isStopped == 1 before .error, .completed events are received in AnonymousObservableSink

### ISSUE THREAD

**Issue by artemiusmk** [ReactiveX/RxSwift#1703]
**Short description of the issue**:

  no subscribe's callbacks are called

**Expected outcome**:

  onNext, onCompleted or onError are called

**What actually happens**:

  https://stackoverflow.com/questions/51439213/can-swift-init-returns-previously-created-object

**Self contained code example that reproduces the issue**:

 I debugged and found that when I call func with Observable.create second time and more in AnonymousObservableSink class _isStopped var == 1 before .error, .completed events are received. Inside Observable.create I use Starscream to get data via the websocket

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.2.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
  9.4.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @artemiusmk ,

The problem you are describing is too vague. It seems to me that you have some problem with Starscream.

If this is some problem with this repo, please provide **self contained** example that reproduces the issue.
