### ISSUE TITLE
NavigationBar animation breaked when using tableView items binding

### ISSUE THREAD

**Issue by TopalSergey** [ReactiveX/RxSwift#1705]
**Short description of the issue**:

Navigation bar transition animation is breaked when I use navigation bar with large titles and rx bindings for tableView. Please see gif below.
To reproduce, It's need to use storyboard: UINavigationController -> VC1 -> VC2 (with table). And when you goes from VC1 to VC2, animation is breaked.

**Expected outcome**:

Navigation bar animation should work as when using normal UITableViewDataSource.

**What actually happens**:

![ezgif-4-ac63b54dc6](https://user-images.githubusercontent.com/11177122/43048810-2bacb342-8df6-11e8-926d-55fe1eb4db57.gif)

**Self contained code example that reproduces the issue**:

```swift
// VC should be instantiated from storyboard
import RxSwift
import RxCocoa
import UIKit

class TableViewController: UIViewController {

    @IBOutlet private weak var tableView: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
        Observable<[Int]>.just([1, 2, 3, 4])
            .bind(to: tableView.rx.items(cellIdentifier: "Cell", cellType: UITableViewCell.self)) { (row, element, cell) in
                cell.textLabel?.text = "\(element)"
            }
    }

}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.2.0

**Platform/Environment**

  - [ *] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [* ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.4.1 (9F2000)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [* ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ *] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [* ] I have a small code base
  - [ ] I have a significant code base

**Comment by TopalSergey** [comment]
The issue is caused by calling UIView.layoutIfNeeded() from DelegateProxyType.subscribeProxyDataSource(ofObject:dataSource:retainDataSource:binding:):

`                // this is needed to flush any delayed old state (https://github.com/RxSwiftCommunity/RxDataSources/pull/75)
                object.layoutIfNeeded()
`

**Comment by kzaher** [comment]
Hi @TopalSergey ,

can't repro it https://github.com/ReactiveX/RxSwift/tree/anomaly/1705

Please make a PR to https://github.com/ReactiveX/RxSwift/tree/anomaly/1705 that reproduces the case.

**Comment by TopalSergey** [comment]
Add example to reproduce navigation bar animation anomaly #1706

**Comment by TopalSergey** [comment]
Hi, I've made PR #1706.
To reproduce please select item 'Anomaly 1705' under 'Table/Collection view examples' section.

**Comment by freak4pc** [comment]
@TopalSergey Closing this for now, let's keep the discussion going in your PR. Feel free to bump a comment there to get some attention for it :) Thanks !
