### ISSUE TITLE
Adding numbers example crash 

### ISSUE THREAD

**Issue by CivelXu** [ReactiveX/RxSwift#1710]
**Short description of the issue**:

At NumbersViewController , change the UITextField input ;
when NumbersViewController pop will crash sometimes 
at this line code

```  
assert(Resources.total <= numberOfResourcesThatShouldRemain, "Resources weren't cleaned properly, \(Resources.total) remained, \(numberOfResourcesThatShouldRemain) expected")
```

**Comment by kzaher** [comment]
Maybe ios cleans resources with a small delay in some cases. If this was a leak it should be more consistent IMHO.

**Comment by freak4pc** [comment]
Closing this as it is relatively old. Feel free to reopen if you have additional questions. 

As kruno mentioned - if it's intermittent it might be related to some debug optimizations / resources cleanups etc. If you can reproduce the issue in a more consistent way, I'd love to take a look. 

Thanks!
