### ISSUE TITLE
UIKeyboard resigns on ".subscribe (onNext: {[weak self] text" - Bug?

### ISSUE THREAD

**Issue by veer-suthar** [ReactiveX/RxSwift#1717]
I am trying to get text of textfield on DONE button press, but when I write onSubscribe(onNext, it resigns keyboard?
I don't want to resign keyboard, until response comes back from server as I want - its use case of promo code and until its valid -  

         textfield_promo.rx.controlEvent(.editingDidEndOnExit)
         .withLatestFrom(textfield_promo.rx.text.orEmpty)
         .subscribe (onNext: {[weak self] text in
         
         }).disposed(by: rxBag)

Why it resigns keyboard?

When I only write 

        textfield_promo.rx.controlEvent(.editingDidEndOnExit)
            .withLatestFrom(textfield_promo.rx.text.orEmpty)
Its fine, but in this, I am unable to get text 

  - [* ] iOS

  - [*] easy, 100% repro

Version 9.4.1 (9F2000)

  - [*] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [*] just starting

**Comment by freak4pc** [comment]
Hey, as explained to you over at the slack group, this isn't a bug with RxSwift/RxCocoa itself.
