### ISSUE TITLE
Slack onboarding fails

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#1727]
Hi guys,

our Slack onboarding on heroku is failing. http://slack.rxswift.org/

Does @freak4pc or @bontoJR own rxswift.org or that heroku server? 

I have no idea who owns it 😆 .

**Comment by freak4pc** [comment]
@bontoJR owns it but I have access - will take a look :)

**Comment by freak4pc** [comment]
Was worth it to see you open an Issue in your own repo 😂

**Comment by freak4pc** [comment]
@kzaher It seems fine here - could've been a temporary downtime. Could you look again? 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/605076/44542999-07b21d80-a717-11e8-9e69-7e72777ca2bd.png">

**Comment by bontoJR** [comment]
Working fine for me as well, maybe a temporary Heroku downtime?

**Comment by kzaher** [comment]
Oh cool, I’ll close it them. It was reported to me.

**Comment by kzaher** [comment]
Looks like heroku failed again http://slack.rxswift.org/ 😕

**Comment by kzaher** [comment]
That was @bontoJR

**Comment by bontoJR** [comment]
So I tried multiple things, restart the dyno, refresh the app, new deploy, etc... with no luck, it looks like the whole setup is broken and on the free level I don't have any support, I recommend to recreate this.

So I am going to start from scratch, assign a new dyno to that web app and add also ppl with rights to edit it, please le me know the emails I should add.

**Comment by freak4pc** [comment]
Hey @bontoJR - Maybe just add community@rxswift.org, easier to add more people onto that e-mail list when needed. 

Thanks for your work on this :)

**Comment by bontoJR** [comment]
But an account on heroku with that email is then requires and now Heroku enforces 2FA which makes the whole login process for multiple ppl a little bit more difficult... I would prefer to add personal accounts :)

**Comment by freak4pc** [comment]
In that case I'd appreciate adding me :] 
nickname at gmail dot com

**Comment by freak4pc** [comment]
@bontoJR Any update here?

**Comment by freak4pc** [comment]
**NOTE:** If you got here without a way to join slack, please email community@rxswift.org and I'll add you :) Sorry for the issue!

**Comment by freak4pc** [comment]
Deployed this, seems to work well: 
https://rxslack.herokuapp.com

I'm gonna forward the subdomain to it.

**Comment by freak4pc** [comment]
I've deployed a different onboarding page for now, seems to work fine. 
Same domain @ http://slack.rxswift.org.
