### ISSUE TITLE
Suggestion: BehaviorRelay Readonly Trait

### ISSUE THREAD

**Issue by c0diq** [ReactiveX/RxSwift#1734]
**Short description of the issue**:

We often use a BehaviorRelay to represent a ViewModel output as it has the property to never error or complete. However, this has the negative side effect of a exposing a way  for injecting new values using the `accept` method, violating the encapsulation rule.

**Expected outcome**:

Create a read-only version of BehaviorRelay or a BehaviorRelay operator that `erases` the accept method so one cannot do `observable.subscribe(onNext: relay.accept)`.

**What actually happens**:

It is possible to modify a view model output value outside of the view model.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.2.0

**Platform/Environment**

  - [X] iOS
  - [X] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.4.1
```

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by freak4pc** [comment]
@c0diq I'm confused as to why you'd use a Relay or Subject as an output - usually those are more fitting for inputs. 

Outputs that don't error out would usually be Driver or Signal - depending on the sharing strategy you're looking for. 

In any way - Relays are a concept arriving from RxJava (they have their own RxRelay after which our own Relays are modeled) - so: 

1. It will not be beneficial or platform agnostic to make another unit that has a different trait. 
2. It seems to me you are misusing Relays based on the context and information you're sharing. 

Anything beyond that is probably beyond the scope of a GitHub issue - as those are reserved only for actual issues with the project itself, and not as much for "how do I do xxxx". Those sort of questions are better aimed at our slack channel @ https://slack.rxswift.org .

I'm going to be closing this for now given everything - but if you feel there's more discussion needed or this is a valid issue, let me know and we can reopen. 

Shai.

**Comment by freak4pc** [comment]
The better methodology would be having your BehaviorRelay private and expose its `asObservable()` in a `public` way. 

In general, the usage of `Variable` (and `BehaviorRelay` in the way you suggest) is very imperative. It's totally OK if its used for bridging an already-imperative concept/object, for example; but if you're actually modelling your app via local caching with relays, that might not be the best choice, overall.
