### ISSUE TITLE
combineLatest can be declared using variadic parameters with Swift 2.0

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#174]
2015-09-16
Updated the Variadic Parameters section, now that variadic parameters can be declared in any position in a function’s parameter list.

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459

**Comment by ikesyo** [comment]
Each observables has a different generic parameter, so variadic parameters can not be used, I think.

**Comment by kzaher** [comment]
Yeah, I'm also not sure what is the suggestion :)

There are two versions of `combineLatest`. 

* one with different types of arguments -> goes up to 8 arguments
* one with collection of observables of same type

```
extension CollectionType where Generator.Element : ObservableType {
    
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.
    
    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    public func combineLatest<R>(resultSelector: [Generator.Element.E] throws -> R) -> Observable<R> {
        return CombineLatestCollectionType(sources: self, resultSelector: resultSelector)
    }
}
```

@frogcjn could you help us understand your suggestion better? :)

I think the second version is equivalent to variadic arguments?

**Comment by kzaher** [comment]
We also have the same versions for `zip` operator :)

**Comment by kzaher** [comment]
This was probably a misunderstanding, closing this one for now.
