### ISSUE TITLE
Extra argument 'onError' in call when using Single

### ISSUE THREAD

**Issue by satishreddyg** [ReactiveX/RxSwift#1745]
**Short description of the issue**:

I was trying to access a method in a singleton class to get the json data back in Single<T> and when I subscribe to it, I am getting an error as, " Extra argument 'onError' in call"

**Expected outcome**:

 I should be able to get error closure work

**What actually happens**:

  its not building the project

**Self contained code example that reproduces the issue**:

```swift
class NetworkClient: Network {
    static let shared = PMNetworkClient()
    private override init() {}
    
    func getJSON<T: Codable >(forRequest urlRequest: URLRequest) -> Single<T> {
        return Single<T>.create(subscribe: { observer -> Disposable in
            //make the call
            let task = URLSession.shared.dataTask(with: urlRequest) { (data, HTTPResponse, error) in
                guard error == nil else {
                    observer(.error(SmartSearchError.responseError))
                    return
                }
                guard let response = HTTPResponse as? HTTPURLResponse, response.statusCode == 200 || response.statusCode == 201 else {
                    observer(.error(SmartSearchError.statusCodeNotSuccessful))
                    return
                }
                guard let validData = data else {
                    observer(.error(SmartSearchError.noResponseData))
                    return
                }
                do {
                    let jsonDict = try JSONDecoder().decode(T.self, from: validData)
                    observer(.success(jsonDict))
                } catch let caughtError {
                    observer(.error(caughtError))
                }
            }
            task.resume()
            return Disposables.create()
        })
    }
}

networkClient.getJSON(forRequest: request)
                .subscribe(onSuccess: { (results: [[String: Any]]) in
                    print(results)
                }, onError: { (error: Error) in //this is where the error occurs
                    print("error is: \(error.localizedDescription)")
                })
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.3.0/4.3.0

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
  Xcode 10.0
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [** ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ **] yes (Xcode 8.3 and Xcode 10.0)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ **] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by dtartaglia** [comment]
The compiler can't infer the return type for `getJSON`. This isn't an RxSwift issue. It's a language issue.

This compiles and works:

    let result: Single<MyCodableType> = networkClient.getJSON(forRequest: request)
        let disposable = result
            .subscribe(onSuccess: { value in
                print(value)
            }, onError: { error in
                print(error)
            })

**Comment by satishreddyg** [comment]
got it. Changes made and its working, thanks a lot.
