### ISSUE TITLE
Carthage build RxSwift >= 4.3.1 should be built with Swift 4.2

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1750]
Using Carthage with a pre-build archive will not be able to use the archive for projects with Xcode 10 and Swift 4.2: 

```
*** Downloading RxSwift.framework binary at "Zürich"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."
Falling back to building from the source
```

I think that, since version 4.3.1 and above are post Xcode 10 GM, the archive should be with Swift 4.2, leaving users of Swift 4.1 to build from source.

Any thoughts welcome.

**Comment by kzaher** [comment]
That’s not 4.3.0 that you are using currently. 

https://github.com/ReactiveX/RxSwift/releases/tag/4.3.0

**Comment by freak4pc** [comment]
Ugh. totally my bad, sorry !
