### ISSUE TITLE
RxCocoa Swift 4.2 for macOS

### ISSUE THREAD

**Issue by mariohahn** [ReactiveX/RxSwift#1751]
For macOS there are still some issues with Swift 4.2 

- Deprecated File
- NSTextField+Rx

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Using RxCocoa (4.3.1)

**Platform/Environment**

  - [x ] macOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro

**Xcode version**:

```
Xcode 10
```

**Installation method**:
  - [x ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x ] I have a significant code base

**Comment by freak4pc** [comment]
@mariohahn Without any details we obviously can't do anything :)

**Comment by mariohahn** [comment]
It's not build for macOS: 

Deprecated.swift
<img width="1065" alt="bildschirmfoto 2018-09-25 um 12 43 38" src="https://user-images.githubusercontent.com/915933/46009749-bf44a180-c0c0-11e8-9a67-d36e0fb2c1d9.png">

NSTextField+Rx.swift
<img width="1044" alt="bildschirmfoto 2018-09-25 um 12 43 48" src="https://user-images.githubusercontent.com/915933/46009778-cf5c8100-c0c0-11e8-8737-b7d427b2170e.png">

**Comment by freak4pc** [comment]
You're definitely not on the latest version. Look in your `Podfile.lock`, are you on 4.3.1 ? 

My mac app builds, and also the code looks different in the two cases you mentioned.

**Comment by mariohahn** [comment]
hmm, after `pod deintegrate` and `pod install`it worked, maybe it was a caching issue. Thanks (:
