### ISSUE TITLE
Swift Complier Error for RxCocoa for Swift 4.2

### ISSUE THREAD

**Issue by sEmoto-JIEM** [ReactiveX/RxSwift#1754]
*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

  Swift Complier Error for RxCocoa

**Expected outcome**:

  I can import RxCocoa to my class and build my app.

**What actually happens**:

  When importing RxCocoa to my class, error that Could not build Objective-C module 'RxCocoa' has occurred. For Swift 4.2, UIKit components have been renamed.

**Self contained code example that reproduces the issue**:

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift: 4.2.0
  RxCocoa: 4.2.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [x] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version 10.0
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Please us 4.3.1 release/
