### ISSUE TITLE
Swizzle UITableView  @selector(setDelegate:) method, and set

### ISSUE THREAD

**Issue by Zuoweixiang** [ReactiveX/RxSwift#1755]
**Short description of the issue**:

 i have swizzle UITableView's @(setDelegate:) method , and set my  NSProxy  object  instead.  

it seems that  Rx  do not want people use NSProxy to forward message?

**Expected outcome**:

 I hope that , UITableView Delegate Method will be forward to my NSProxy object,then do something I want. then my NSProxy forward message to RxDelagateProxy. 
**What actually happens**:

 crashed in DEBUG ,and can't work fine.
**Self contained code example that reproduces the issue**:

```swift
void sa_setDelegate(id obj ,SEL sel, id delegate){
    SEL swizzileSel = sel_getUid("sa_setDelegate:");
    SADelegateProxy *delegateProxy = nil;
    if (delegate != nil) {
        delegateProxy = [obj sensorsAnalyticsDelegateProxy];
        if (delegateProxy == nil) {
            if ([obj isKindOfClass:UITableView.class]) {
                delegateProxy = [SADelegateProxy proxyWithTableViewDelegate:delegate];
            }else if ([obj isKindOfClass:UICollectionView.class]){
                delegateProxy = [SADelegateProxy proxyWithCollectionViewDelegate:delegate];
            }
        }else {
            if (delegate == delegateProxy.target) {
                return;
            }
            [delegateProxy setTarget:delegate];
            return;
        }
    }
    [(NSObject *)obj setSensorsAnalyticsDelegateProxy:delegateProxy];
    ((void (*)(id, SEL,id))objc_msgSend)(obj,swizzileSel,delegateProxy);
}
@implementation NSObject (SensorsAnalyticsDelegateProxy)

-(void)setSensorsAnalyticsDelegateProxy:(SADelegateProxy *)SensorsAnalyticsDelegateProxy{
    objc_setAssociatedObject(self, @selector(setSensorsAnalyticsDelegateProxy:), SensorsAnalyticsDelegateProxy, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
-(SADelegateProxy *)sensorsAnalyticsDelegateProxy{
    return objc_getAssociatedObject(self, @selector(setSensorsAnalyticsDelegateProxy:));
}

@end

@implementation UITableView (SensorsAnalyticsDelegateProxy)
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{

        SEL origSel_ = sel_getUid("setDelegate:");
        SEL swizzileSel = sel_getUid("sa_setDelegate:");
        Method origMethod = class_getInstanceMethod(self, origSel_);
        const char* type = method_getTypeEncoding(origMethod);
        class_addMethod(self, swizzileSel, (IMP)sa_setDelegate, type);
        Method swizzleMethod = class_getInstanceMethod(self, swizzileSel);
        IMP origIMP = method_getImplementation(origMethod);
        IMP swizzleIMP = method_getImplementation(swizzleMethod);
        method_setImplementation(origMethod, swizzleIMP);
        method_setImplementation(swizzleMethod, origIMP);
    });
}

@end
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [1 ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [1 ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
```
10.0
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [1 ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [1 ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [1 ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey @Zuoweixiang - This doesn't seem related to RxSwift or Rx at all. Unfortunately. since we're all volunteers spending our free time working on this library and supporting it, we have to prioritize only issues relating to bugs/issues with the framework itself, and not "How do I do xxx?" kind of questions. 

For those sort of questions, you might be better off to check out our slack channel: https://slack.rxswift.org . 

Good luck, and thanks for your understanding.
Shai,.
