### ISSUE TITLE
Error while creating ImagePicker

### ISSUE THREAD

**Issue by anirudhamahale** [ReactiveX/RxSwift#1757]
**Short description of the issue**:

  I wanted to implement Image Picker so I copied code from the example app https://github.com/ReactiveX/RxSwift/tree/master/RxExample/RxExample/Examples/ImagePicker

**What actually happens**:

createWithParent(:) method from UIImagePickerController+RxCreate.swift file gives error `Value of type 'Reactive<UIImagePickerController>' has no member 'didCancel'` while creating dismissDisposable.

When I trie to get didFinishPickingMediaWithInfo from ImagePickerController.swift gives error `Value of type 'Reactive<(UIImagePickerController)>' has no member 'didFinishPickingMediaWithInfo'` for .flatMap { $0.rx.didFinishPickingMediaWithInfo }

**Self contained code example that reproduces the issue**:

```swift

let imagePicker = UIImagePickerController()
            let dismissDisposable = imagePicker.rx
                .didCancel
                .subscribe(onNext: { [weak imagePicker] _ in
                    guard let imagePicker = imagePicker else {
                        return
                    }
                    dismissViewController(imagePicker, animated: animated)
                })

openCameraButton.rx.tap
            .flatMapLatest { [weak self] _ in
            return UIImagePickerController.rx.createWithParent(self) { picker in
                picker.sourceType = .camera
                picker.allowsEditing = false
                }
                .flatMap { $0.rx.didFinishPickingMediaWithInfo }
                .take(1)
            }
            .map { info in
                return info[UIImagePickerControllerOriginalImage] as? UIImage
            }
            .bind(to: imageView.rx.image)
            .disposed(by: disposeBag)
 
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 10
  Swift 4.2
  RxSwift 4.3.1
  RxCocoa 4.3.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

Here are the screenshots of the issues
![screenshot 2018-10-01 at 9 08 36 pm](https://user-images.githubusercontent.com/16848003/46301383-cd645780-c5c3-11e8-8127-cfa914c34397.png)
![screenshot 2018-10-01 at 9 08 20 pm](https://user-images.githubusercontent.com/16848003/46301391-d48b6580-c5c3-11e8-83b3-a8d3610e264e.png)

**Comment by kzaher** [comment]
We don't ship these extensions as a part of official release as far as I can tell.
