### ISSUE TITLE
DelegateProxy.currentDelegate

### ISSUE THREAD

**Issue by RazeeHJ** [ReactiveX/RxSwift#1758]
I get this error:

assert(proxy === DelegateProxy.currentDelegate(for: object), "Proxy changed from the time it was first set.

Original: (proxy)

Existing: (String(describing: DelegateProxy.currentDelegate(for: object)))")
I have two observables that handles two different xib storyboard on different states but once one of them has been loaded And the second should be binded I receive the error above, I have tried to use the self.tableView.delegate = nil & self.tableView.dataSource = nil but yet it causes this on the .bind(to:) function. My problem is I don't know how to handle it before this error:

Assertion failed: Proxy changed from the time it was first set.
Original:

.asObservable().bind(to:(tableView?.rx.items(cellIdentifier: 
      aTableViewCell.Identifier, cellType: HaTableViewCell.self))!

    func initTableView() {

    // pull to refresh
    aViewModel
        .isLoading
        .asObservable()
        .subscribe({ (loading) in
            if loading.element == false { 
            } else {
                self.tableView!.delegate = self // loads a shimmering view
                self.tableView!.dataSource = self
            }
        })
        .disposed(by: disposeBag)

         Tableview.delegate = nil
         Tableview.dataSource= nil

         // when I’ve the data it crashes
       aViewModel
        .datas
        .asObservable()
        .bind(to:(tableView?.rx.items(cellIdentifier: aTableViewCell.Identifier, cellType: HaTableViewCell.self))!) { (index, element, cell) in
         // when the data is fired load this tableview cell
        }.disposed(by: disposeBag)
        }

**Comment by hanl001** [comment]
Hi，has this problem been solved?

**Comment by freak4pc** [comment]
You shouldn't do both a manual delegate / data source and a reactive one. Decide on a single method and use that - switching the delegates manually this way can cause unexpected issues and crashes. 

This isn't a bug, but a programmer error, so I'll be closing this. 
If you need any additional, code-specific help, please check out our slack channel @ https://slack.rxswift.org. 

Thanks.

**Comment by hanl001** [comment]
i just update Rx from 4.1 to 4.3,  and not do both a manual delegate / data source and a reactive one. when versation 4.1 is was worked, so sad....

**Comment by kzaher** [comment]
There is `setDelegate` method on `rx.proxy` that enables manual delegate setting.

**Comment by hanl001** [comment]
@freak4pc in this specific code, you are right, thanks!!!
 But in my case, I don't know where it is wrong. Clearing the cache is useless, however when I 
 `checkout to old branch --> clear cache --> build  --> checkout to new branch --> clear cache --> build` ,  all build are ok.

**Comment by freak4pc** [comment]
Hey @hanl001 - You might've been doing something wrong that just happened to work before :) It's hared to say. 

I suggest opening a new issue for your specific problem - but make sure it has an actual reproducible project or we won't be able to do much unfortunately. 

Thanks!
