### ISSUE TITLE
Xcode 10 carthage build error

### ISSUE THREAD

**Issue by intoxicated** [ReactiveX/RxSwift#1759]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://slack.rxswift.org/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

Unable to build with carthage with 4.3.1

**Expected outcome**:

build with carthage command

**What actually happens**:

Build system information
error: Cycle inside RxCocoa-iOS; building could produce unreliable results.
Cycle details:
→ Target 'RxCocoa-iOS': CodeSign /Users/R3alFr3e/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/RxSwift/4.3.1/Build/Products/Release-iphonesimulator/RxCocoa.framework
○ Target 'RxCocoa-iOS' has a command with output '/Users/R3alFr3e/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/RxSwift/4.3.1/Build/Products/Release-iphonesimulator/RxCocoa.framework/RxCocoa'
○ Target 'RxCocoa-iOS' has link command with output '/Users/R3alFr3e/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/RxSwift/4.3.1/Build/Intermediates.noindex/Rx.build/Release-iphonesimulator/RxCocoa-iOS.build/Objects-normal/x86_64/RxCocoa'
○ Target 'RxCocoa-iOS' has a command with output '/Users/R3alFr3e/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/RxSwift/4.3.1/Build/Products/Release-iphonesimulator/RxCocoa.framework/RxCocoa'

** BUILD FAILED **

**Self contained code example that reproduces the issue**:

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  xcode 10
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by lengocduy** [comment]
I have the same issue previously. After I upgraded carthage version(0.31.0) "brew upgrade carthage" the issue has gone. In GuideLine of RxSwift, The Tested with carthage version: 0.26.2.

**Comment by kzaher** [comment]
I've tested this with `0.30.1` and it does build. It looks like it was just stale Carthage version. If the issue persists, please provide more details.
