### ISSUE TITLE
Bug!!!  build error about Type inference

### ISSUE THREAD

**Issue by nizenyang** [ReactiveX/RxSwift#1762]
first problem
![image](https://user-images.githubusercontent.com/8390188/46743440-a56ba700-ccdb-11e8-8a47-3b77e2f7a9ed.png)
![image](https://user-images.githubusercontent.com/8390188/46743451-ab618800-ccdb-11e8-83dd-a7eeb6a2a00c.png)

second  problem
![image](https://user-images.githubusercontent.com/8390188/46743539-e499f800-ccdb-11e8-8161-44bddc1346a0.png)

like picture
why show this error

searchV.sBar.textField  Type is UITextField
but build error

how can I solve this problem???

**Comment by freak4pc** [comment]
Hey @nizenyang - This seems to be a Swift type inference issue, unrelated to RxSwift. unfortunately we can't provide support for these sort of issues as they're not actually related to the library or its functionality. 

FWIW I just wrote a similar code piece with an internal UITextField exposed with a lazy var and it worked just fine for me. I'm not entirely sure what you have inside your custom component but it would not be feasible to provide code-level support here IMHO. 

Good luck!
Shai.
