### ISSUE TITLE
Collect Operator

### ISSUE THREAD

**Issue by mbalex99** [ReactiveX/RxSwift#177]
Can we add a `collect` operator or something?

    var userIds = ["1234", "12564", "49873", "29837598"];

    userIds.asObservable
	    .flatMap{ rx_getCreditCardToken($0)}
	    .collect()
	    .flatMap { (tokens: [TokenData]) -> TransactionResult in 
	        return rx_bulkCharge(tokens, 12.00)
	    }
	    .subscribeNext{ transactionResult
	        print(transactionResult)
	    }

This is available by the reduce operator, however it's rather verbose.

**Comment by kzaher** [comment]
Yeah, we can add `toArray` extension or something :)

**Comment by mbalex99** [comment]
Yes that would be awesome.

**Comment by mbalex99** [comment]
Maybe toArray isn't the best method name. It kind of implied T not Observable<T> 
What about `reduceToArray` since that's what it's really doing.

**Comment by kzaher** [comment]
I think there is a `toArray()` operator in Rx :), but yeah, we'll probably add something like that :)

**Comment by bontoJR** [comment]
Solved with #202
