### ISSUE TITLE
Can't compile RxCocoa with DISABLE_SWIZZLING flag

### ISSUE THREAD

**Issue by vasiliiIvanovOmnigon** [ReactiveX/RxSwift#1770]
**Short description of the issue**:

Can't compile RxCocoa with DISABLE_SWIZZLING flag

**Expected outcome**:

RxCocoa should be compilable with DISABLE_SWIZZLING flag

**What actually happens**:

RxCocoa build with DISABLE_SWIZZLING flag fails with error:
```
RxCocoa/RxCocoa/Foundation/NSObject+Rx.swift:350:119: error: value of type 'KeyValueObservingOptions' has no member 'nsOptions'
        super.init(target: parent.target, retainTarget: parent.retainTarget, keyPath: parent.keyPath, options: parent.options.nsOptions, callback: callback)
```

Seems like `nsOptions` is defined for case without `DISABLE_SWIZZLING`, so it can't be found otherwise.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxCocoa: d62846ca96495d862fa4c59ea7d87e5031d7340e
RxSwift: fd680d75283beb5e2559486f3c0ff852f0d35334

I know that this version is pretty old, but I can see the same code in current revision (commit 0df62b4d562f8620d4b795b18e4adf0b631527a1).

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 9.4.1 (9F2000)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by punty** [comment]
I have this PR that should fix this https://github.com/ReactiveX/RxSwift/pull/1779

**Comment by kzaher** [comment]
This should be fixed now.
