### ISSUE TITLE
[Question] How to avoid "Reentrancy anomaly was detected"?

### ISSUE THREAD

**Issue by Maxikq** [ReactiveX/RxSwift#1775]
**Short description of the issue**:

As an exercise I'm trying to transform my Bluetooth code into RxSwift, however I'm currently struggling with it. In my case I want to have a method `pair` which returns `Observable<PairingState>` to inform about progress. 

I receive Bluetooth events via delegate and broadcast them through `BehaviourSubject<BluetoothEvent>`

I want to react on each BluetoothEvent and perform some action if necessary plus emit event to `Observable<PairingState>` to inform about the progress.

**What actually happens**:

Now I'm struggling with performing actions on events, because they also may emit another event. So this cases causes often `Reentrancy anomaly was detected.` issue.

How should I properly implement it?

**Self contained code example that reproduces the issue**:

Here is my example:

```swift
//
//  BluetoothPairingService.swift
//  BluetoothDemo
//
//  Created by Wojciech Kulik on 21/07/2018.
//  Copyright © 2018 Wojciech Kulik. All rights reserved.
//

import Foundation
import CoreBluetooth
import RxSwift

enum PairingState {
    case none
    case scanStarted
    case deviceFound
    case pairing
    case paired
}

enum PairingError: Error {
    case deviceNotFound
    case timeOut
    case bluetoothOff
    case disconnected
}

class PairingFlow: FlowController {
    
    private let timeout = 15.0

    // MARK: 1. Pairing steps
    
    func pair() -> Observable<PairingState> {
        self.bluetoothSerivce?.startScan()

        return self.bluetoothSubject
            .debug()
            .do(onNext: { [weak self] state in
                    switch state {
                    case .discoveredPeripheral:
                        try self?.connect() // <- may emit onNext or onError - reentry
                    case .readyToWrite:
                        self?.bluetoothSerivce?.getSettings()
                    default: return
                    }
                }, onError: { [weak self] _ in
                    self?.cancel()  // <- may emit onNext or onError - reentry
                }, onCompleted: { [weak self] in
                    self?.cancel()  // <- may emit onNext or onError - reentry
            })
            .timeout(timeout, scheduler: MainScheduler.instance)
            .map { state in
                switch state {
                case .scanStarted:
                    return .scanStarted
                case .discoveredPeripheral:
                    return .deviceFound
                case .connected(_):
                    return .pairing
                case .received(_):
                    return .paired
                case .disconnected(let failure):
                    if failure { throw PairingError.disconnected }
                    return .none
                default:
                    return .none
                }
            }
            .filter { $0 != PairingState.none }
    }
    
    private func connect() throws {
        self.bluetoothSerivce?.stopScan()
        
        guard self.bluetoothSerivce?.centralManager.state == .poweredOn else {
            throw PairingError.bluetoothOff
        }
        guard let peripheral = self.bluetoothSerivce?.peripheral else {
            throw PairingError.deviceNotFound
        }
        
        self.bluetoothSerivce?.centralManager.connect(peripheral)
    }
    
    private func cancel() {
        self.bluetoothSerivce?.disconnect()
    }
}

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by Maxikq** [comment]
http://rxswift-slack.herokuapp.com/ doesn't work, where I can ask a question?

**Comment by freak4pc** [comment]
@Maxikq Please DM me your email on twitter (or write it here) and I can Invite you to slack. Seems like our Heroku gateway is down at the moment.

**Comment by Maxikq** [comment]
Thank you, please invite me using this mail: max1414pl@gmail.com

**Comment by freak4pc** [comment]
You should have an invite.

**Comment by DhbStudy** [comment]
> You should have an invite.

Hello, the same problem about the  dependence loop. I can't join the http://rxswift-slack.herokuapp.com/. Can you help me? 
Here is my email: dhbstudy@hotmail.com

**Comment by freak4pc** [comment]
Please try http://slack.rxswift.org

**Comment by DhbStudy** [comment]
@freak4pc

Hello, the same problem about the dependence loop. I can't enter the [http://rxswift-slack.herokuapp.com/](http://rxswift-slack.herokuapp.com/). Can you help me?
Here is my email: dhbstudy@hotmail.com

**Comment by DhbStudy** [comment]
@freak4pc

Hello, the same problem about the dependence loop. I can't enter the [http://rxswift-slack.herokuapp.com/](http://rxswift-slack.herokuapp.com/). Can you help me?
Here is my email: dhbstudy@hotmail.com
