### ISSUE TITLE
error with Xcode 10.1

### ISSUE THREAD

**Issue by VisualEcho** [ReactiveX/RxSwift#1789]
**Short description of the issue**:

I have updated my Xcode to 12.1 yesterday. And when I rebuild my project after install pods today, I got several errors in RxCocoa.

**Expected outcome**:

**What actually happens**:

**Self contained code example that reproduces the issue**:

```swift
//ControlTarget.swift
//line 17, 32, 36
typealias ControlEvents = UIKit.UIControlEvents // error: 'UIControlEvents' has been renamed to 'UIControl.Event'
let controlEvents: UIControlEvents // error: 'UIControlEvents' has been renamed to 'UIControl.Event'
init(control: Control, controlEvents: UIControlEvents, callback: @escaping Callback)  // error: 'UIControlEvents' has been renamed to 'UIControl.Event'

//Deprecated.swift
//line 358
transition.timingFunction = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseInEaseOut) // error: 'kCAMediaTimingFunctionEaseInEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeInEaseOut'

//line 359
transition.type = transitionType //error: Cannot assign value of type 'String' to type 'CATransitionType'. Replace 'transitionType' with 'CATransitionType(rawValue: transitionType)'

//NSTextStorage+Rx.swift
//line 23
public var didProcessEditingRangeChangeInLength: Observable<(editedMask:NSTextStorageEditActions, editedRange:NSRange, delta:Int)> // error: 'NSTextStorageEditActions' has been renamed to 'NSTextStorage.EditActions'

//line 27
let editedMask = NSTextStorageEditActions(rawValue: try castOrThrow(UInt.self, a[1]) ) // error: 'NSTextStorageEditActions' has been renamed to 'NSTextStorage.EditActions'

//UITableView+Rx.swift

//line 234
return UITableViewCellEditingStyle(rawValue: (try castOrThrow(NSNumber.self, a[1])).intValue) == .insert // error: 'UITableViewCellEditingStyle' has been renamed to 'UITableViewCell.EditingStyle'

//line 249
return UITableViewCellEditingStyle(rawValue: (try castOrThrow(NSNumber.self, a[1])).intValue) == .delete  // error: 'UITableViewCellEditingStyle' has been renamed to 'UITableViewCell.EditingStyle'

//UIButton+Rx.swift

//line 48, 55, 62, 79
public func title(for controlState: UIControlState = []) -> Binder<String?> // error: 'UIControlState' has been renamed to 'UIControl.State'
public func image(for controlState: UIControlState = []) -> Binder<UIImage?> // error: 'UIControlState' has been renamed to 'UIControl.State'
public func backgroundImage(for controlState: UIControlState = []) // error: 'UIControlState' has been renamed to 'UIControl.State'
public func attributedTitle(for controlState: UIControlState = []) -> Binder<NSAttributedString?>  // error: 'UIControlState' has been renamed to 'UIControl.State'

//UIControl+Rx.swift
//line 33, 60, 90

public func controlEvent(_ controlEvents: UIControlEvents) -> ControlEvent<()> // error: 'UIControlEvents' has been renamed to 'UIControl.Event'
editingEvents: UIControlEvents  // error: 'UIControlEvents' has been renamed to 'UIControl.Event'
editingEvents: UIControlEvents = [.allEditingEvents, .valueChanged]  // error: 'UIControlEvents' has been renamed to 'UIControl.Event'
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.2.0

**Platform/Environment**

  - [*] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [*] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

10.1
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [*] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
You're probably either targeting the wrong version of RxSwift or the wrong version of Swift in Xcode for your project. 

I'm on Xcode 10.1 with iOS 12.1 with no compilation issues. Do you have a project to reproduce?

**Comment by VisualEcho** [comment]
> You're probably either targeting the wrong version of RxSwift or the wrong version of Swift in Xcode for your project.
> 
> I'm on Xcode 10.1 with iOS 12.1 with no compilation issues. Do you have a project to reproduce?

What's about your Swift version? I find out my project auto change the version of Swift to 4.2. Maybe  that's why I get the errors

**Comment by freak4pc** [comment]
4.2 as well. Please provide a fresh project reproducing this, otherwise we'll have to close unfortunately as this repo is only about solving issues with the framework itself, and not individual problems in people's projects (that would be better for our Slack channel).

**Comment by VisualEcho** [comment]
I tried in a fresh project. I do nothing but import RxSwift. When I build the project, as u see.
<img width="1183" alt="wx20181101-173118 2x" src="https://user-images.githubusercontent.com/5999906/47843909-06c6f780-ddfc-11e8-92c3-fb4ed179cc0e.png">

**Comment by freak4pc** [comment]
As I mentioned - please *attach* the project. Otherwise there's nothing for us to look at :)

**Comment by VisualEcho** [comment]
[TestRxType.zip](https://github.com/ReactiveX/RxSwift/files/2537933/TestRxType.zip)
OK, I upload the project.

**Comment by freak4pc** [comment]
Look at your `Podfile.lock` - you are using RxSwift 4.2.0. 
Please do a full `pod repo update` and `pod update`: 
![image](https://user-images.githubusercontent.com/605076/47844336-d155e600-ddca-11e8-9d16-b2c425fc6389.png)

**Comment by VisualEcho** [comment]
I tried this way, but it didn't work.
Now I updated all the frameworks, the version are
<img width="447" alt="image" src="https://user-images.githubusercontent.com/5999906/47888409-5569a580-de7f-11e8-93df-517d45e3fe95.png">
It works now.
Thank u all the same.
