### ISSUE TITLE
Slack is down

### ISSUE THREAD

**Issue by JonasVautherin** [ReactiveX/RxSwift#1790]
The RxSwift slack seems to be down: http://rxswift-slack.herokuapp.com/ says "Application Error".

**Comment by freak4pc** [comment]
It's being tracked in #1727

**Comment by JonasVautherin** [comment]
Thanks, I hadn't seen it. Is there a way to bypass this and get access to the slack in another way?

**Comment by freak4pc** [comment]
Yup, for now you can just tell me your email (here or send me an email to community@rxswift.org).
