### ISSUE TITLE
RxSwift Slack sign-ups are down

### ISSUE THREAD

**Issue by bogo** [ReactiveX/RxSwift#1791]
**Short description of the issue**:

The [Heroku instance](http://slack.rxswift.org/) that the RxSwift sign-ups are running on is failing.

**Expected outcome**:

A user can register for the RxSwift Slack.

**What actually happens**:

A Heroku application error appears.

**Self contained code example that reproduces the issue**:

n/a

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

n/a

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds
  - [x] Web

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

n/a

**Comment by freak4pc** [comment]
Tracked in #1727

**Comment by freak4pc** [comment]
See #
