### ISSUE TITLE
carthage update tries to build tvOS schemes for OS X

### ISSUE THREAD

**Issue by torstenlehmann** [ReactiveX/RxSwift#180]
Environment:
- Xcode 7.0.1 (7A1001) (maybe the problem?)
- OS X 10.10.5

In 2.0.0-alpha.4 when running `carthage update --platform mac` I get the following error:

```
xcodebuild: error: Failed to build workspace Rx with scheme RxBlocking-tvOS.
	Reason: The run destination My Mac is not valid for Running the scheme 'RxBlocking-tvOS'.
```

The reason for this is that I have no matching tvOS device and Xcode defaults to `My Mac`.

A temporary fix:

1. Run `carthage update`. An error will occur while it tries to build a tvOS scheme.
2. Open `PROJECT/Carthage/Checkouts/RxSwift/Rx.xcworkspace`.
3. Next to the stop button click the Pop-Up Button and select `Manage schemes…`.
4. Deselect `Autocreate schemes`. Remove all non tvOS (and maybe watchOS) schemes. I removed tvOS, watchOS and iOS schemes.
5. Run `carthage build`.

**Comment by kzaher** [comment]
@torstenlehmann I've used Xcode 7.1 beta when testing integrations :)

People have been asking me about tvos and watchos support a lot :) There are just so many combinations of integrations and platforms right now that it's hard to cover every combination :)

@torstenlehmann Thnx for workaround steps, and reporting this.

For the next alpha I'll remove tvos shared schemes from normal releases if xcode 7.1 won't be released, and add them for carthage in separate branch :(

**Comment by torstenlehmann** [comment]
@kzaher Ok. So the problem will disappear if Xcode 7.1 is released.

There is no other way in Xcode to tell a scheme to have no fallback platform? I don't know any.

**Comment by kzaher** [comment]
Yeah, I doubt it has :) I think that osx is the `else` fallback, which is a bug on it's own :)

**Comment by torstenlehmann** [comment]
:)

**Comment by kzaher** [comment]
I've unshared schemes for tvOS and tried it and it seems to me that Carthage builds this correctly now :)

I'll probably need to create a separate branch for tvos again :( Oh well ...

This should be closed.
