### ISSUE TITLE
UIScrollview delegate didn't call

### ISSUE THREAD

**Issue by miku1958** [ReactiveX/RxSwift#1806]
**Short description of the issue**:
I make a scrollview delegate method like didEndDragging as a observer, but if I did set a value in subscribe close ,it won't call, like:
```
   _ = scrollview.rx.didEndDragging.asObservable().subscribe { [weak self] _ in//if I delete this _, it won't callback

        }
```

**Expected outcome**:

  it should callback normally 

**What actually happens**:

  didn't callback

**Self contained code example that reproduces the issue**:

```swift
    _ = scrollview.rx.didEndDragging.asObservable().subscribe { [weak self] in
            //do something
        }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxCocoa 4.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  10.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @miku1958 ,

I'm not sure I understand the issue.

This code prints values for me:
```swift
 _ = textView.rx.didEndDragging.subscribe {
            print($0)
        }
```

**Comment by kzaher** [comment]
Have no idea what to do here. Closing.
