### ISSUE TITLE
A combination of groupBy, scan and subscribe causes a leak

### ISSUE THREAD

**Issue by mkko** [ReactiveX/RxSwift#1844]
**Short description of the issue**:

It seems that there is a possible reference loop with a combination of operators and subscriptions. This is possible when using

- `groupBy` to split observable into individual ones,
- `scan` to combine these inner observables into an array
- and finally `subscribe` to the individual observables (i.e. basically the keys of `groupBy`).

I was using this combination to group a stream of mixed updates by their identifier and handle these updates within the instance itself. I'm not sure if this was the best way, but it seemed to be the most simple one. Basically I'm doing the following. The arrays are actually observables, but I'm not sure how to visualize them.

```swift
[("a", 1), ("b", 1), ("a", 2), ("b", 2), ("a", 3), ("b", 3), ...] -> [Update(key: "a", updates: [1, 2, 3, ...]), Update(key: "b", updates: [1, 2, 3, ...]), ...]
```

However, using the sample code below keeps the updates coming even when the observable is disposed. Digging into this it seems that the loop is from the following:

- `ScanSink<E, O>._accumulate` holds the last value, even when disposed.
- These `Update` instances are not deallocated, even though not referenced by anything else.
- These `Update` instances keep the subscriptions alive.

At first this seemed simply dangerous/harmful use of Rx. However, I would still expect that when disposed, the observable chain wouldn't hold references anymore. In the code I expected that these instances would be deallocated and their dispose bags would handle the disposing.

Also, if leaving `groupBy` out (or `scan` for that matter), the code stops as expected. I'd expect it to behave the same way as without 

Simply clearing the `_accumulate` variable in the `ScanSink` makes it stop as well when disposed.

I'm not sure though if emptying `_accumulate` would be the fix. I think the question is how `groupBy´ should behave, as it is essentially an observable of observables and I would expect that the lifecycle of inner and outer observables are not dependent on each other.

**Self contained code example that reproduces the issue**:

I've created [a sample project](https://github.com/mkko/RxSwiftGroupByScanReferenceLoop) that reproduces this issue. Here's the gist of it: 

```swift
// Create a couple of grouped observables.
Observable<Int>
    .interval(1, scheduler: MainScheduler.instance)
    .groupBy(keySelector: { $0 % 3 })
    .scan([], accumulator: { (acc, g) in
        acc + [Update(key: g.key, updates: g.asObservable())]
    })
    .debug("Main")
    .subscribe()
    .disposed(by: disposeBag)

// Make it stop after five seconds.
Observable<Int>
    .interval(5, scheduler: MainScheduler.instance)
    .subscribe(onNext: { _ in
        print("Disposing...")
        self.disposeBag = DisposeBag()
    })
    .disposed(by: disposeBag)
```

And `Update` is:

```swift
class Update {
    private let disposeBag = DisposeBag()

    init(key: Int, updates: Observable<Int>) {
        updates
            .debug("Update(key: \(key))")
            .subscribe()
            .disposed(by: disposeBag)
    }
}
``` 

For reference, this works just fine:

```swift
let timer = Observable<Int>.interval(1, scheduler: MainScheduler.instance)
timer.scan([], accumulator: { (acc, i) in
        acc + [Update(key: i, updates: timer)]
    })
    .subscribe()
    .disposed(by: disposeBag)
```

**Expected outcome**:

Expected output should be something like:

```
Main -> subscribed
Update(key: 0) -> subscribed
Main -> Event next([])
Update(key: 0) -> Event next(0)
Update(key: 1) -> subscribed
Main -> Event next([RxSwiftMemLeak.Update])
Update(key: 1) -> Event next(1)
Update(key: 2) -> subscribed
Main -> Event next([RxSwiftMemLeak.Update, RxSwiftMemLeak.Update])
Update(key: 2) -> Event next(2)
Update(key: 0) -> Event next(3)
Update(key: 1) -> Event next(4)
RxSwiftMemLeak[66370:2780463] Disposing...
Main -> isDisposed
Update(key: 0) -> isDisposed
Update(key: 1) -> isDisposed
Update(key: 2) -> isDisposed
```

**What actually happens**:

```
Main -> subscribed
Update(key: 0) -> subscribed
Main -> Event next([])
Update(key: 0) -> Event next(0)
Update(key: 1) -> subscribed
Main -> Event next([RxSwiftMemLeak.Update])
Update(key: 1) -> Event next(1)
Update(key: 2) -> subscribed
Main -> Event next([RxSwiftMemLeak.Update, RxSwiftMemLeak.Update])
Update(key: 2) -> Event next(2)
Update(key: 0) -> Event next(3)
Update(key: 1) -> Event next(4)
RxSwiftMemLeak[66739:2791547] Disposing...
Main -> isDisposed
Update(key: 2) -> Event next(5)
Update(key: 0) -> Event next(6)
Update(key: 1) -> Event next(7)
Update(key: 2) -> Event next(8)
Update(key: 0) -> Event next(9)
Update(key: 1) -> Event next(10)
Update(key: 2) -> Event next(11)
...and so on
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
- RxCocoa (4.4.0):
- RxSwift (4.4.0):
```

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
 10.1 (10B61)
```

**Comment by kzaher** [comment]
Hi @mkko ,

you can't do this.

```swift
.scan([], accumulator: { (acc, g) in
        acc + [Update(key: g.key, updates: g.asObservable())]
    })
```

```swift
class Update {
    private let disposeBag = DisposeBag()

    init(key: Int, updates: Observable<Int>) {
        updates
            .debug("Update(key: \(key))")
            .subscribe()
            .disposed(by: disposeBag)
    }
}
```

You've created a reference cycle that is independent of Rx. 

`scan` references accumulator which subscribes to group by sink, which probably references `scan` sink.

To avoid these kinds of leaks **do not send references types as sequence elements or parts of sequence elements**. **Only use value types as sequence elements**.

**Comment by mkko** [comment]
Thanks for your reply.

The issue here is that `scan` references the accumulator which does reference the `groupBy` sink (or the subjects created there), but even when disposed, `scan` doesn't release the reference and keeps the subscriptions alive. My initial expectation was that `scan` would release the resources when disposed which lead me to this issue.

If compared to the sample that didn't introduce this issue:

```swift
let timer = Observable<Int>.interval(1, scheduler: MainScheduler.instance)
timer.scan([], accumulator: { (acc, i) in
        acc + [Update(key: i, updates: timer)]
    })
    .subscribe()
    .disposed(by: disposeBag)
```

I expected the behavior in both cases to be coherent, but apparently this is not the case? They both depend on the same observable.

I understand this is not normal use case and I was able to work around it just by basically replacing `groupBy` in `scan`. I also understand that using reference types is not recommended with Rx. However, I don't think there's another way when dealing with map annotations in iOS and `NSObject` instances. Maybe Rx was not the right tool for my use case.

I would just hope to make Rx safer to use. Especially in regards of memory, since these kinds of issues can be really tricky to see. In this case the fix would be simply make `scan` release its resources on dispose.

**Comment by kzaher** [comment]
@mkko If you aren’t sending value types in sequences, better to not use it because almost nobody will be able to analyze your code. Including you after a month.

I can’t advise how to model problem and should you use rx. Maybe yes, maybe no.

**Comment by mkko** [comment]
Thanks. I've been struggling with this reference type topic since the beginning of my Rx use. Usually the requirement is from the UI which pretty much enforces the use of reference types (eg. MKAnnotation).

I'm curious, is there any safe use of Rx with reference types? I've been learning this the hard way and I believe it would be valuable to advice the use somewhere in the docs. The use of pure functions kind of implies this though, but simple-minded readers such as me might not take the hint.

**Comment by mkko** [comment]
The idea of bridging sounds convenient, but I'm not sure how to accomplish this. I take you don't mean similar bridging to what is done between `NSString` and `String`, are you? With annotations, the single instance has to remain the same, so only way I can think of is to have some sort of cache/registry/container of existing instances. Is this the kind of bridging you mean, @freak4pc?

**Comment by freak4pc** [comment]
No, I actually just meant recreating new ones - do they have to remain the same? Another option is trying to create some sort of a dictionary between value-typed keys vs. reference-type values

**Comment by mkko** [comment]
Yeah, I believe they do, if you want to animate additions, move and possibly in general avoid any kind of flickering. I was thinking similar mapping too, the only challenge I find is invalidating old unused instances but I already had an idea of reusing the annotations from the map itself.

I'll need dig into this, maybe there's a way to introduce another kind of property in `MKMapView` that you can bind struct-based types to and this binding would handle the mapping/bridging for you.

Thanks!
