### ISSUE TITLE
Possible bug in multicast regarding completions.

### ISSUE THREAD

**Issue by danielt1263** [ReactiveX/RxSwift#1848]
**Short description of the issue**:

It seems that the `replay()` operator isn't replaying to later subscribers if the underlying observable completes.

**Expected outcome**:

I expect the following output:

	output 1 -> subscribed
	output 1 -> Event next(1)
	output 1 -> Event completed
	output 2 -> subscribed
	output 2 -> Event next(1)
	output 2 -> Event completed
  
**What actually happens**:

The second observable (output 2) is subscribed to, but never emits a value or completes. Note that if you comment out the `onCompleted()` call, *both* subscriptions will output the `next(1)` event.

**Self contained code example that reproduces the issue**:

```swift
    let subject = PublishSubject<Int>()
    let replay = subject.replay(1024)
    replay.connect()
    replay.debug("output 1").subscribe()

    subject.onNext(1)
    subject.onCompleted()

    replay.debug("output 2").subscribe()
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift - 4.3.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  10.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by dtartaglia** [comment]
The following test exhibits the bug. Putting this test in the current test suite (from the master branch) will expose the bug.

```swift
	func testReplayCount_CompleteTwoSubscribers() {
		let scheduler = TestScheduler(initialClock: 0)

		let xs = scheduler.createColdObservable([
			.next(10, 5),
			.next(20, 9),
			.next(30, 11),
			.next(40, 20),
			.next(50, 22),
			.next(60, 23),
			.next(70, 24),
			.next(80, 25),
			.completed(90)
			])

		var ys: ConnectableObservable<Int>! = nil
		var subscription1: Disposable! = nil
		var subscription2: Disposable! = nil
		var connection: Disposable! = nil
		let res1 = scheduler.createObserver(Int.self)
		let res2 = scheduler.createObserver(Int.self)

		scheduler.scheduleAt(Defaults.created) { ys = xs.replay(3) }
		scheduler.scheduleAt(450, action: { subscription1 = ys.subscribe(res1) })
		scheduler.scheduleAt(550, action: { subscription2 = ys.subscribe(res2) })
		scheduler.scheduleAt(Defaults.disposed) { subscription1.dispose() }
		scheduler.scheduleAt(Defaults.disposed) { subscription2.dispose() }

		scheduler.scheduleAt(400) { connection = ys.connect() }
		scheduler.scheduleAt(600) { connection.dispose() }

		scheduler.start()

		XCTAssertEqual(res1.events, [
			.next(450, 9),
			.next(450, 11),
			.next(450, 20),
			.next(450, 22),
			.next(460, 23),
			.next(470, 24),
			.next(480, 25),
			.completed(490),
			])

		XCTAssertEqual(res2.events, [
			.next(450, 9),
			.next(450, 11),
			.next(450, 20),
			.next(450, 22),
			.next(460, 23),
			.next(470, 24),
			.next(480, 25),
			.completed(490),
			])
	}
```

**Comment by freak4pc** [comment]
I'm closing every issue older than 6 months. If this is still an issue for you, please comment and I can reopen :) Thanks !
