### ISSUE TITLE
Button tap event is not fired

### ISSUE THREAD

**Issue by MasterHiei** [ReactiveX/RxSwift#1850]
**Short description of the issue**:

  - What happened

    I used the Throttle operator like below to avoid tap event getting fired repeatedly. Then rx_tap event is not working anymore.

```swift
    myBtn.rx.tap
        .throttle(0.5, latest: false, scheduler: MainScheduler.instance)
        .subscribe() // <- some code in here
        .disposed(by: self.disposeBag)
```

  - What I did

1. tap a button(used Throttle operator).
2. change device time to 1(or more) min ago immediately and quickly(App work in background).
3. back to app and tap the same button immediately and quickly.

  - Android(RxKotlin) have the same issue.

:cry:
Does have any idea about this? or other way to avoid tap event gets fired multiple times.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 ```
  RxSwift 4.4.0
  RxCocoa 4.4.0
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [x] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 10.1 (10B61)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by dtartaglia** [comment]
All timers shut down while the app is in the background. Therefore the time your app spent in the background doesn't count against the throttle time. Also, timers don't use clock time to determine their status so changing the device's clock is irrelevant.

**Comment by MasterHiei** [comment]
Yes...Thanks for your comment.
But I have not idea what happened there. :dizzy_face:That's weird.

**Comment by freak4pc** [comment]
Hey - I'm sorry but this isn't a bug. I think Daniel's comment clears up how this works. Closing for now, but if you have additional questions related to framework issues, you can comment here. If you just need help, our slack might be a better option.
