### ISSUE TITLE
onSubscribed closure in do(onNext: ...) gets called after the subscription is disposed

### ISSUE THREAD

**Issue by ioninks** [ReactiveX/RxSwift#1851]
**Short description of the issue**:

`onSubscribed` closure in `do(onNext: ...)` gets called after the subscription is disposed if the observable is created with `just(...)` function. 

**Self contained code example that reproduces the issue**:

```swift
let disposeBag = DisposeBag()

let observable = Observable<Int>.just(1)

observable
    .do(onNext: { value in
        print("do on next: \(value)")
    }, onCompleted: {
        print("do on completed")
    }, onSubscribe: {
        print("do on subscribe")
    }, onSubscribed: {
        print("do on subscribed <-")
    }, onDispose: {
        print("do on dispose")
    })
    .subscribe(
        onNext: { value in
            print("subscribe on next: \(value)")
    },
        onCompleted: {
            print("subscribe on completed")
    },
        onDisposed: {
            print("subscribe on disposed")
    })
    .disposed(by: disposeBag)
```

**What actually happens**:

This is what gets printed in the console:

```
do on subscribe
do on next: 1
subscribe on next: 1
do on completed
subscribe on completed
subscribe on disposed
do on subscribed <-
do on dispose
```

**Expected outcome**:

If I replace `Observable<Int>.just(1)` with `Observable<Int>.of(1)` the output becomes closer to what is expected:

```
do on subscribe
do on subscribed <-
do on next: 1
subscribe on next: 1
do on completed
subscribe on completed
subscribe on disposed
do on dispose
```

P.S. Is it designed this way so `onCompleted` closure in `do(onNext: ...)` gets called before `onCompleted` in `subscribe(onNext: ...)` but `onDispose` closure in `do(onNext: ...` is called after `onDisposed` in `subscribe(onNext: ...)` ? 

**RxSwift version**

4.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.0, 10.1 (different machines)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @ioninks,

This is just a consequence of calling callbacks and hooks after callbacks have been called. 

If I understand there are two complaints here.
Complaint 1: `do on subscribed <-` is called after sink/subscription has been disposed. I can understand why this might be confusing and I think there might be a simple fix. We just check is the sink unsubscribed, and if so, we just don't call `onSubscribed`.

Complaint 2: `do on subscribed <-` is called at wrong time.
The suggested order
```
do on subscribe
do on subscribed <-
do on next: 1
subscribe on next: 1
do on completed
subscribe on completed
subscribe on disposed
do on dispose
```
doesn't make much sense to me. 
You are suggesting that `do on subscribe` and `do on subscribed <-` are indistinguishable from each other. There is no benefit of having this API at all IMHO. The `onSubscribed` closure is situated exactly where it names suggests it to be. The behavior you are experiencing is a consequence of that. You have an expectation that is based on some invalid assumptions on how this library works.

**Comment by ioninks** [comment]
Hi, @kzaher,
Thank you very much for a clarification. I guess we can close this issue.
