### ISSUE TITLE
Throttled events are sent on a different scheduler

### ISSUE THREAD

**Issue by T1T4N** [ReactiveX/RxSwift#1857]
**Short description of the issue**:

When using the `throttle` operator, events that aren't throttled are executed on the specified scheduler, but event that are throttled execute on a different scheduler, the one specified in the operator.

I am aware of [this previous issue](https://github.com/ReactiveX/RxSwift/issues/1061) which was closed (as well as [this commit](https://github.com/ReactiveX/RxSwift/commit/e474a4476c9312a9c99f87a3d583d8c30bd04c44)), but I still think it is a valid standing issue.

At the very least, if this is the intended behavior, the documentation for `Throttle` should be updated to specify exactly what happens to the __throttled__ events.

**Expected outcome**:

All events, regardless of throttled or not, should be executed on the specified scheduler using `observeOn` (or the default), and not on the scheduler specified:
> [to run the throttle timers on.](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Observables/Throttle.swift#L22)

**What actually happens**:

Throttled events are executed on a different scheduler.

**Self contained code example that reproduces the issue**:

```swift
func currentQueueLabel() -> String {
    let name = __dispatch_queue_get_label(nil)
    return String(cString: name, encoding: .utf8) ?? "unknown"
}

let bag = DisposeBag()
let opQueue = DispatchQueue(label: "OpQueue")
let timeoutQueue = DispatchQueue(label: "TimeoutQueue")
let opScheduler = SerialDispatchQueueScheduler(queue: opQueue, internalSerialQueueName: "OpQueue")
let timeoutScheduler = SerialDispatchQueueScheduler(queue: timeoutQueue, internalSerialQueueName: "TimeoutQueue")

Observable<Int>.create { observer in
    observer.onNext(1)
    observer.onNext(2)
    sleep(5)
    observer.onNext(3)
    return Disposables.create()
}
.observeOn(opScheduler)
.do(onNext: { print("DO BEFORE THROTTLE: \($0) on: \(currentQueueLabel())") } )
.throttle(2, scheduler: timeoutScheduler)
.do(onNext: { print("DO AFTER THROTTLE: \($0) on: \(currentQueueLabel())") } )
.subscribe(onNext: { print("OnNext: \($0) on: \(currentQueueLabel())")})
.disposed(by: bag)
```

**Current output of code sample**
```
DO BEFORE THROTTLE: 1 on: OpQueue
DO AFTER THROTTLE: 1 on: OpQueue
OnNext: 1 on: OpQueue

DO BEFORE THROTTLE: 2 on: OpQueue
DO AFTER THROTTLE: 2 on: TimeoutQueue
OnNext: 2 on: TimeoutQueue

DO BEFORE THROTTLE: 3 on: OpQueue
DO AFTER THROTTLE: 3 on: OpQueue
OnNext: 3 on: OpQueue
```

**Expected output of code sample**
```
DO BEFORE THROTTLE: 1 on: OpQueue
DO AFTER THROTTLE: 1 on: OpQueue
OnNext: 1 on: OpQueue

DO BEFORE THROTTLE: 2 on: OpQueue
DO AFTER THROTTLE: 2 on: OpQueue
OnNext: 2 on: OpQueue

DO BEFORE THROTTLE: 3 on: OpQueue
DO AFTER THROTTLE: 3 on: OpQueue
OnNext: 3 on: OpQueue
```

**Current workaround**

The quick workaround for this issue is to perform an `observeOn` after the `throttle` operator.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

latest (4.4.0)

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 10.1
Build version 10B61
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @T1T4N,

> All events, regardless of throttled or not, should be executed on the specified scheduler using observeOn (or the default), and not on the scheduler specified:

As far as I'm aware of we don't specify this behavior anywhere. I'm not sure what made you think this is true. 

I'm fine with accepting a PR clarifying this behavior in the documentation, because I can understand why this might be confusing, but other than doing that I don't think this is a bug.

As far as I'm aware of that assumption is not documented anywhere, there is not a single unit test testing this behavior and other implementations behave in similar fashion.
