### ISSUE TITLE
Try NOT to use force unwrapping "optional!"

### ISSUE THREAD

**Issue by AshleyDeng** [ReactiveX/RxSwift#1861]
**Short description of the issue**:

Been having crashes in RxCocoa as it uses force unwrapping on an optional variable.

**Expected outcome**:

Should not crash / use force unwrapping.

**What actually happens**:

Uses force unwrapping and crashes.

**Self contained code example that reproduces the issue**:

In RxCollectionViewReactiveArrayDataSource.swift

```swift
var itemModels: [Element]? = nil
...
override func _collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        return cellFactory(collectionView, indexPath.item, itemModels![indexPath.item])
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxCocoa 4.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.1 (10B61)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @AshleyDeng ,

Can you provide steps to repro the issue? Just writing

> Should not crash / use force unwrapping.

isn't productive.

What action are you proposing for that piece of code? As far as I can tell there is not much difference between using `!` and manually calling `fatalError`.

**Comment by kzaher** [comment]
Not sure is there an alternative.
