### ISSUE TITLE
flat Map does no emit the onCompleted event

### ISSUE THREAD

**Issue by dvertovsek** [ReactiveX/RxSwift#1864]
**Short description of the issue**:

Observable inside the `flatMap` does not emit the `onCompleted` event onto the subscriber.

**Expected outcome**:

Observable inside the `flatMap` should emit the `onCompleted` event

**What actually happens**:

The `onCompleted` does not get called

**Self contained code example that reproduces the issue**:

```swift
let disposeBag = DisposeBag()
func getObs() -> Observable<[String]> {
    return Observable<Int>.create { observer in
        observer.onNext(0)

        return Disposables.create()
        }
        .flatMap { num -> Observable<[String]> in
            return .empty()
    }
}
getObs().subscribe { event in
    print(event) // Nothing gets printed here
}.disposed(by: disposeBag)
```
or
```
let disposeBag = DisposeBag()

func getObs() -> Observable<[String]> {
    return Observable<Int>.create { observer in
        observer.onNext(0)

        return Disposables.create()
        }
        .flatMap { num -> Observable<[String]> in
            return Observable.create { observer in
                observer.onCompleted

                return Disposables.create()
            }
    }
}
getObs().subscribe { event in
    print(event) // Nothing gets printed here
    }.disposed(by: disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.0

**Platform/Environment**

  - `[ X ] iOS`
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - `[ X  ] easy, 100% repro`
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**: 

```
Version 10.1 (10B61)
```

**Installation method**:
  -` [ X  ] CocoaPods`
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - `[ X ] no`

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - `[  X ] I have a significant code base`

**Comment by kzaher** [comment]
This is by design.
```
let disposeBag = DisposeBag()
func getObs() -> Observable<[String]> {
    return Observable<Int>.create { observer in
        observer.onNext(0)
        observer.onCompleted() // <-- missing

        return Disposables.create()
        }
        .flatMap { num -> Observable<[String]> in
            return .empty()
    }
}
getObs().subscribe { event in
    print(event) // Nothing gets printed here
}.disposed(by: disposeBag)
```

**Comment by LaCost765** [comment]
@dvertovsek Faced with the same issue, did you find solution?
