### ISSUE TITLE
Auto loading help

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#187]
Hey, guys I'm just playing with the library, trying to create my own Autoloading tableView.
So I just did like in the example, but when error occurs it just dispose loading.

So I was able to do kind of like this, by recursively call this function again. 
But I feel that there is more elegant way do do this

```swift
   private func startLoad() {
      let nextPageTriger =  self.tableView
         .rx_contentOffset
         .flatMap { (offset) in
            Pagination.shouldLoadNextBatch(offset, table: self.tableView)
               ? just()
               : empty()
      }
      
      Marvel.heroList(self.heroViewModels.value.count,loadNextBatch: nextPageTriger)
         .map { (heroes) -> [HeroListViewModel] in
            return heroes.map(HeroListViewModel.init)
         }
         .subscribe(next:
            { (heroes) -> Void in
               self.heroViewModels.value.appendContentsOf(heroes)
            }, error: { (err) -> Void in
               print(err)
               self.startLoad()
            }, disposed: { _ in
               print("disposed")
         })
         .addDisposableTo(self.disp)
   }
```

**Comment by kzaher** [comment]
Hi @sergdort ,

there is `catchError*` and `retry*` families of operators. Was that what you were looking for?

**Comment by sergdort** [comment]
Hi @kzaher ,

So I was able to refactor this way

```swift

   private func recursiveLoad() -> Observable<[HeroListViewModel]> {
      let nextPageTriger = tableView
         .rx_contentOffset
         .flatMap { (offset) in
            Pagination.shouldLoadNextBatch(offset, table: self.tableView)
               ? just()
               : empty()
      }
      return Marvel.heroList(heroViewModels.value.count,loadNextBatch: nextPageTriger)
         .map(HeroListViewModel.transform)
         .catchError { err in
            print(err)
            return self.recursiveLoad()
         }
   }

// And using it like this

      recursiveLoad()
         .subscribeNext({ (heroes) -> Void in
            self.heroViewModels.value.appendContentsOf(heroes)
         })
         .addDisposableTo(disp)

```

Sure this is bad practice, because it's leads to infinite number of calls if error constantly occurs (and user trying to scroll to bottom)
But when I try to use retry* operators its start loading from the beginning of first recursive call again
For example if I have asking for 20, 40 .. got error it will ask again with offset of 20
I guess I'm expecting wrong from the normal behavior.
Then I think it would be great to have feature which would allow to *retry some number of times with new Observable (like we have with catchError )

**Comment by kzaher** [comment]
Hi @sergdort ,

I'm assuming you want to `retry` a couple of times for each batch in case it fails.

I've moved the retry operator in example app to make more sense

https://github.com/ReactiveX/RxSwift/blob/develop/RxExample/RxExample/Examples/AutoLoading/GitHubSearchRepositoriesViewController.swift#L99

Now that code does a couple of retries for each batch before failing :)

I think we'll do an example alone that demonstrates different retry logics. There is quite a lot of choices here :)

* you can retry finite number of times
* retry finite number of times then wait for network reachability to change
* do an exponential backoff until upper bound and then retry at that max interval
* on failure report that it failed, but wait until some condition to retry
* others :)

We'll do an example in RxExample just for that, but need to finish up some other things first :)

I would suggest taking a look at position of retry operator [here](https://github.com/ReactiveX/RxSwift/blob/develop/RxExample/RxExample/Examples/AutoLoading/GitHubSearchRepositoriesViewController.swift#L99) and see if it makes more sense in the example now. It should try to reload batch where an error occurred, and not go from the start.

**Comment by sergdort** [comment]
Hmm. I think this will just retry if there is an error during the first call. Am right?
And should It retry if there is a connection error? Because now it doesn't

**Comment by kzaher** [comment]
This should retry every batch request 2 more times. On third failure the failure is being propagated.

It doesn't retry now if there is an error on connectivity level?

**Comment by sergdort** [comment]
I've tested on my device (RxExample), and when I'm searching something it pops the results, and then when I turn off wifi and start scrolling its prints error in the console and removes all items from the tableView.

I thought .catchErrorJustReturn operator has higher priority on *retry but when I've removed it, the app just prints error and does'n restarts the connection

**Comment by kzaher** [comment]
Hi @sergdort ,

that is something I would expect from that code :)

[This catchErrorJustReturn](https://github.com/ReactiveX/RxSwift/blob/develop/RxExample/RxExample/Examples/AutoLoading/GitHubSearchRepositoriesViewController.swift#L235)  says what should do when there is nothing more we can do here, what is the value we should send :)

I think you are talking about retries when reachability changes.
We will be adding examples of how to do more elaborate recoveries (including that) in upcoming releases :)

**Comment by sergdort** [comment]
Oh, I see ;)
Thank you very much! And please feel free to close this issue if you want.
Will wait  for the next release :)

**Comment by kzaher** [comment]
I think it's ok to leave it here as a reminder what I need to add to next releases until we actually do this :)

**Comment by kzaher** [comment]
We've added those network reachable retries in example app, so this should be addressed there.

We can open new issue if necessary.

**Comment by sergdort** [comment]
Hi, @kzaher thanks, will take a look on exapmle :+1:
