### ISSUE TITLE
Feature Request: delaySubscription(closure)

### ISSUE THREAD

**Issue by beachcitiessoftware** [ReactiveX/RxSwift#1872]
I would like to see this functionality (http://reactivex.io/RxJava/javadoc/rx/Observable.html#delaySubscription-rx.functions.Func0-) implemented in RxSwift.  

- OR - 

Is there another way to accomplish this functionality already?

**Comment by kzaher** [comment]
Something like `Observable.defer { }.delaySubscription(scheduler)`.

**Comment by beachcitiessoftware** [comment]
Hm, that doesn't seem to be quite the same.

**Comment by kzaher** [comment]
Reading the docs again, that might be just `trigger.flatMapLatest { _ in source }`. I'm unsure why they have an operator for that. Never used it. Anyway, we don't have explicit operator like that.
