### ISSUE TITLE
Usage of `share(replay:scope:)` with a high replay count results in large memory footprint.

### ISSUE THREAD

**Issue by BrianSemiglia** [ReactiveX/RxSwift#1873]
**Short description of the issue**:

  Usage of `share(replay:scope:)` with a high replay count results in large memory footprint.

**Expected outcome**:

  Usage of `share(replay:scope:)` with a high replay count would result in a memory footprint proportional to the event count not the replay count.

**What actually happens**:

  In this case, usage of `share(replay:scope:)` with a high replay count results in a memory footprint of about 15GB.

**Self contained code example that reproduces the issue**:

```swift
  Observable.just("foo").share(replay: 999999999, scope: .forever)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  4.4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce?**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  10.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
And how’s does your memory look if you have an array with the same 999999999 elements ?

**Comment by freak4pc** [comment]
Hey @BrianSemiglia - 

Basically the way `share(replay:scope:)` works is that it allocated a `ReplaySubject` with the provided buffer size:

https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Subjects/ReplaySubject.swift#L238

It internally uses a `ContiguousArray` which stores all of its elements in a contiguous memory region, which I guess is the reason it automatically reserves that capacity upfront, so the memory access is more efficient. 

https://github.com/ReactiveX/RxSwift/blob/master/Platform/DataStructures/Queue.swift#L36

I'm not sure if this is necessarily a fix worth doing, or maybe its worth creating a specialized version for really high replay that don't reserve the memory capacity up front. Do you have a real use case where this kind of replay is actually used, or this is a theoretical memory issue?

**Comment by BrianSemiglia** [comment]
I'm looking to replay all events of an observable. I would opt for `.replayAll` but it doesn't offer auto connect.

**Comment by freak4pc** [comment]
Maybe @kzaher can offers some thoughts.

**Comment by kzaher** [comment]
Hi guys,

I think that @BrianSemiglia probably wants.
```swift
self.multicast(makeSubject: { ReplaySubject.createUnbounded() }).refCount()
```

**Comment by BrianSemiglia** [comment]
```.multicast(makeSubject: { ReplaySubject.createUnbounded() }).refCount()``` seems to only replay the next events of an observable that hasn't completed yet. ```.share(replay: 1, scope: .forever)``` replays the next, error, and completion events and is closer to the behavior that I'm hoping for. Is there any configuration that allows for that?

**Comment by freak4pc** [comment]
Based on the original implementation, I imagine you're looking for 
`self.multicast(ReplaySubject.createUnbounded()).refCount()`

**Comment by BrianSemiglia** [comment]
Hey, it worked! Memory's looking good too. Thanks for all your help! I used it to implement this: https://github.com/BrianSemiglia/RxCacheMap
