### ISSUE TITLE
DispatchQueue.isMain not returning as expected

### ISSUE THREAD

**Issue by ryu1006** [ReactiveX/RxSwift#1874]
**Short description of the issue**:

  During XCUITests and scrolling a longer list of cells with a `rx.contentOffset` observable set in `awakeFromNib`, the DispatchQueue.isMain is returning false, causing a rxFatalError to be thrown when it actually is running on the main thread. The logic to check if the DispatchQueue is on the main thread seems incorrect.

![image](https://user-images.githubusercontent.com/5336143/52661326-caf9fe80-2ecf-11e9-86a5-800a827bfdcb.png)

![stacktrace](https://user-images.githubusercontent.com/5336143/52661318-c59cb400-2ecf-11e9-821f-9eaef6e6a9ef.png)

**Expected outcome**:

  DispatchQueue.isMain returns true.

**What actually happens**:

  DispatchQueue.isMain returns false.

**Self contained code example that reproduces the issue**:

```
class OffersTests: XCTestCase {
    func testOfferHide() {
        let tableView = Offers.offerTableView
        while !tableView.cells.element(boundBy: 12).isHittable {
            tableView.swipeUp()
        } 
        tableView.cells.element(boundBy: 12).swipeLeft()
    }
}

class TileTableViewCell: UITableViewCell {
    @IBOutlet fileprivate var scrollView: UIScrollView!

override public func awakeFromNib() {
        super.awakeFromNib()
        self.setupObservables()
    }

 fileprivate func setupObservables() {
        self.scrollView.rx.contentOffset
            .flatMap({ [weak self] offset -> Observable<Bool> in
                guard let weakSelf = self else {
                    return Observable.empty()
                }
                let progress = offset.x
                return Observable.just(progress > 200)
            })
            .subscribe(onNext: { [weak self] enabled in
                self?.isUserInteractionEnabled = enabled
            })
            .addDisposableTo(rx.disposeBag)
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift 4.3.1

**Platform/Environment**

  - [X] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro

**Xcode version**:

```
Version 10.1 (10B61)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [X] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] I have a significant code base

**Comment by ryuloblaws** [comment]
May be related to this person's findings: http://tom.lokhorst.eu/2018/02/leaky-abstractions-in-swift-with-dispatchqueue

**Comment by kzaher** [comment]
Hi @ryu1006 ,

unfortunately I'm not sure it's so simple.

I think that there are two concepts. Main thread and main dispatch queue.

I think that the main thread pumps the main dispatch queue. That would mean that the main thread could serve other purposes.

I think there were issues with some versions of iOS that were checking is something being executed on main dispatch queue and not is the main thread executing the code.

I'm not sure when did I encounter these cases.

I think that it would maybe be better to add another internal method called `ensureRunningOnMainThread()` and use that for assertions inside `DelegateProxy` and not change the `ensureExecutingOnScheduler`.

It seems to me that the `ensureExecutingOnScheduler` is working correctly since you aren't performing the work on the main dispatch queue.

**Comment by ryuloblaws** [comment]
Sounds good, I will create a PR for that situation.

**Comment by grinder81** [comment]
I think it's not only `DelegateProxy` there is more place where we will need that fix. Basically, any UI code execution must be in the main thread not in main DQ. We are working on it and will share a full update soon.

**Comment by freak4pc** [comment]
Was this resolved in #1882, I guess?

**Comment by kzaher** [comment]
It seems like it was. If it wasn't, somebody will report. @ryu1006 open both this issue and this PR and said `Addressing issue: #1874`.

**Comment by ryu1006** [comment]
This was responded.
