### ISSUE TITLE
first and firstOrError operators lost

### ISSUE THREAD

**Issue by potemkinaleksey** [ReactiveX/RxSwift#1875]
Hello!

At this commit: https://github.com/ReactiveX/RxSwift/commit/d4a30201a9bfa2e1d53d7f4a15f2c4a6c7b54e53 first and firstOrError operators was added. 
But then at this commit: https://github.com/ReactiveX/RxSwift/commit/95af87af0a30da05d37df7576e84175116d93004 they were lost.

It seems like it was by accident when merging, because there is still FirstSink class.

Can we get them back? Maybe i can do cherry pick and make a pull request?

**Comment by kzaher** [comment]
Hi @potemkinaleksey ,

yeah, we can do that.

**Comment by freak4pc** [comment]
Closing this to keep discussion running in #1886.
