### ISSUE TITLE
TimeInterval: Cannot invoke 'throttle' with argument list of type '(Double, ImmediateSchedulerType)'

### ISSUE THREAD

**Issue by gregpardo** [ReactiveX/RxSwift#188]
I'm using the latest develop branch. I'm basically using the throttle example in the getting started and I get the error above. Obviously it's saying I'm sending the wrong type but I can't seem to figure out how to use TimeInterval

**Comment by bontoJR** [comment]
Can you post a code example?

**Comment by gregpardo** [comment]
It's working now after I changed some other code. I think my observable type was the culprit
