### ISSUE TITLE
Cannot return assign Signal of subProtocol

### ISSUE THREAD

**Issue by agiokas** [ReactiveX/RxSwift#1883]
If I have two protocols , A , and B:A, and function expects an Observable<A> I cannot assign a Observable<B> to it.

**Expected outcome**:

I should be able to use sub-protocols

**What actually happens**:

Cannot assign value of type 'Observable<B>' to type 'Observable<A>?'

```swift
  code goes here
  
import UIKit
import RxSwift
import RxCocoa

protocol A { }

protocol B:A {}

class SomeConformingToB : B {}

class SomeClass {
    var property:Observable<A>?
    var property2:Array<A>?
}

class AnotherClass {
    
    init() {
        let observable = Observable<B>.just(SomeConformingToB())
        let someClassInstance = SomeClass()
        
        someClassInstance.property = observable /// Problem is on this line
        
        let ar = [SomeConformingToB(), SomeConformingToB()]
        someClassInstance.property2 = ar
    }
    
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift" == 4.4.0

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 10.1 (10B61)
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @agiokas ,

This is a question about swift language support for covariance and contravariance of the generic arguments.

This question is orthogonal with the current library implementation details. Please forward this to the swift compiler/lang team at Apple.
