### ISSUE TITLE
.switchLatest() does not retain Observables

### ISSUE THREAD

**Issue by agiokas** [ReactiveX/RxSwift#1890]
**Short description of the issue**:

.switchLatest() does not retain Observables

**Expected outcome**:

  switchLatest should retain the Observables which created in the closure before

**What actually happens**:

Observable is deallocated

**Self contained code example that reproduces the issue**:

```swift

import UIKit
import RxCocoa
import RxSwift

class ViewController: UIViewController {

    let disposeBag = DisposeBag()
    weak var observable1:BehaviorSubject<Int>?
    var number = 1
    override func viewDidLoad() {
        super.viewDidLoad()
        someNum().bind(to: self.rx.someNumber).disposed(by: disposeBag)
        observable1?.onNext(2)
        observable1?.onNext(3)
        observable1?.onNext(4)
    }

    func someNum() -> Observable<Int> {
        let v = BehaviorSubject<Int>(value: 1)
        self.observable1 = v
        return Observable.just(v).switchLatest()
    }
}

extension Reactive where Base: ViewController {
    fileprivate var someNumber: Binder<Int>{
        return Binder(base){ (vc, newNum) in
            print("--- newNum ",newNum)
            vc.number = newNum
        }
    }
}  

```

```swift
import UIKit
import RxCocoa
import RxSwift

class ViewController: UIViewController {

    let disposeBag = DisposeBag()
    let mainObservable = BehaviorSubject<Bool>(value: true)
    weak var observable1:BehaviorSubject<Int>?
    weak var observable2:BehaviorSubject<Int>?
    var number = 1
    override func viewDidLoad() {
        super.viewDidLoad()
        someNum().bind(to: self.rx.someNumber).disposed(by: disposeBag)
        observable1?.onNext(2)
        observable1?.onNext(3)
        observable1?.onNext(4)
        mainObservable.onNext(false)
        observable2?.onNext(12)
        observable2?.onNext(13)
        observable2?.onNext(14)
    }

    func someNum() -> Observable<Int> {
        return mainObservable.map({ [weak self](value) -> Observable<Int> in
            if value {
                if self?.observable1 == nil {
                    let v = BehaviorSubject<Int>(value: 1)
                    self?.observable1 = v
                    return v
                } else {
                    return (self?.observable1)!
                }
            } else {
                if self?.observable2 == nil {
                    let v = BehaviorSubject<Int>(value: 10)
                    self?.observable2 = v
                    return v
                } else {
                    return (self?.observable2)!
                }
            }
        }).switchLatest()
    }
}

extension Reactive where Base: ViewController {
    fileprivate var someNumber: Binder<Int>{
        return Binder(base){ (vc, newNum) in
            print("--- newNum ",newNum)
            vc.number = newNum
        }
    }
}


```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.4.0

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)  10.1  and 10.2 beta 3
  - [] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
I'm not sure this is a bug in RxSwift, really. What gave you the impression any operators is supposed to retain weak references this way ?

**Comment by agiokas** [comment]
My point was not that they are weak references.

Replace the 
```swift
        return Observable.just(v).switchLatest()
```

with 

```swift
        return Observable.just(observableWhichFiresMultipleTimes()).switchLatest()

func observableWhichFiresMultipleTimes() -> Observable()

```

and you will have the same effect

**Comment by agiokas** [comment]
A similar example

I would expect that an observable which is create inside the map would me retained by the switchLatest.

How should I handle such situations?

``swift
    weak var weakSubj:BehaviorSubject<NSNumber>?
    func testMemoryAllocationOfToObservable() {
        let disposeBag = DisposeBag()
        let observable = Observable.just(true).map({ [weak self](value) -> Observable<NSNumber> in
            let v = BehaviorSubject<NSNumber>(value: NSNumber(value: 0))
            self?.weakSubj = v
            return v
        }).switchLatest()

        let observer = TestObserver(observable, disposeBag: disposeBag)
        weakSubj?.onNext(NSNumber(value: 1))
        weakSubj?.onNext(NSNumber(value: 2))
        weakSubj?.onNext(NSNumber(value: 3))
        weakSubj?.onNext(NSNumber(value: 4))

        XCTAssertEqual(observer.values, [0,1,2,3,4])
    }
``

**Comment by agiokas** [comment]
I just noted that TestObserver is my own Class so here is another example

```swift
    func testRetain_of_toObservable() {
        var disposeBag:DisposeBag? = DisposeBag()
        weak var weakSubj:BehaviorSubject<Int>?
        var observable:Observable<Int>? = Observable.just(true).map({(value) -> Observable<Int> in
            let subject = BehaviorSubject<Int>(value: 0)
            weakSubj = subject
            return subject
        }).switchLatest()
        
        let expectation = XCTestExpectation(description: "value 0 expected")
        let expectation2 = XCTestExpectation(description: "value 10 expected")
        let expectation3 = XCTestExpectation(description: "value 20 expected")
        let expectation4 = XCTestExpectation(description: "value 30 expected")
        observable!.subscribe(onNext: { (value) in
            if value == 0 {
                expectation.fulfill()
            } else  if value == 10 {
                expectation2.fulfill()
            } else if value == 20 {
                expectation3.fulfill()
            } else if value == 30 {
                expectation4.fulfill()
            }
        }).disposed(by: disposeBag!)
        weakSubj?.onNext(10)
        weakSubj?.onNext(20)
        weakSubj?.onNext(30)
        wait(for: [expectation, expectation2, expectation3, expectation4], timeout: 0.5)
        disposeBag = nil
        observable = nil
        XCTAssertNil(weakSubj) // subject should be released
    }
```

I also noticed that the retaining of the mapped value would only be correct if it is NOT an Observable

**Comment by kzaher** [comment]
@agiokas 

Could you please summarize **what particular API** do you think is failing and **why** do you think it is failing?

I see a lot of code and to be honest don't understand what are you trying to prove.

**Comment by agiokas** [comment]
@kzaher 

I think the problem is in the switchLatest() of the Switch, 
when nextElementArrived(element: E) is called the element is not retained.

What I want to do is to create an Observable inside of a .map and that Observable should be retained by the .switchLatest()

**Comment by kzaher** [comment]
@agiokas You haven't provided any rationale why you would think we are guaranteeing this. We are only retaining references the minimal time we need. If you want to retain something for a longer time, you are responsible for retaining it.

I'm really sorry, but this doesn't look like an issue with this project.
