### ISSUE TITLE
PublishSubject, BehaviorSubject does not close when it subscribes to the completed event.

### ISSUE THREAD

**Issue by magi82** [ReactiveX/RxSwift#1901]
**Short description of the issue**:

Hi. I have a question and I raise it.

When subscribing to a stream published to a PublishSubject or BehaviorSubject, it knows that the subscription will terminate when it receives a completed event.

But in the middle as Observable with no onCompleted event with flatMap
If you change it to just again, the subject will not be closed nor will it be completed.

**Expected outcome**:

```
(output()) -> subscribed
(output()) -> Event next(1)
(output()) -> Event next(3)
(output()) -> Event completed
(output()) -> isDisposed
```

**What actually happens**:

```
(output()) -> subscribed
(output()) -> Event next(1)
(output()) -> Event next(3)
(output()) -> Event next(4)
```

**Self contained code example that reproduces the issue**:

```swift
let subject: PublishSubject<String> = PublishSubject()
subject
    .debug()
    .subscribe()
    .disposed(by: disposeBag)
        
subject.onNext("1")
        
Observable<String>.just("2")
    .flatMap { value -> Observable<String> in
        Observable<String>.create { observer in
            observer.onNext(value)
            return Disposables.create()
        }
    }
    .flatMap { _ in Observable<String>.just("3") }
    .bind(to: subject)
    .disposed(by: disposeBag)
    
    subject.onNext("4")
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  10.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
This is by design. You are not firing `onCompleted`. 

```swift
observer.onNext(value)
observer.onCompleted()
return Disposables.create()
```

**Comment by magi82** [comment]
@kzaher 

I did not enter onCompleted to reproduce the bug.
The important point is that the just operator must be completed,
It does not complete after using the just operator in flatMap.

```swift
 .flatMap { _ in Observable<String>.just("3") }
```

**Comment by kciter** [comment]
As I know `just` operator is firing `onComplete` when subscribed, but it didn’t.

**Comment by serges147** [comment]
I think the key word here is `bind` - it (by design) doesn't forward `.completed` (and under debug issues fatal error for `.error`-s).

**Comment by GeekTree0101** [comment]
```swift
Observable<String>.create { observer in
            observer.onNext(value)
            return Disposables.create()
        }
```
Observable.create return **NopDisposable** (Creates a disposable that does nothing on disposal.) 
(NopDisposable.swift line 29)
```swift
extension Disposables {
    /**
     Creates a disposable that does nothing on disposal.
     */
    static public func create() -> Disposable {
        return NopDisposable.noOp
    }
}

```

Producer.swift line 18
```sh
 po sinkAndSubscription
▿ 2 elements
  ▿ sink : <AnonymousObservableSink<MergeSinkIter<String, Observable<String>, MergeSink<String, Observable<String>, PublishSubject<String>>>>: 0x6000020fd380>
  - subscription : RxSwift.(unknown context at 0x102b0f770).NopDisposable() // <-- HERO
```

Therefore, If you wanna see **expected outcome** , AnonymousObservable needs fire onCompleted for expected outcome.
