### ISSUE TITLE
DelegateProxy does not deal with generics

### ISSUE THREAD

**Issue by fb55** [ReactiveX/RxSwift#1906]
**Short description of the issue**:

RxStarscream has a [generic implementation](https://github.com/RxSwiftCommunity/RxStarscream/blob/be2a7f91291c7252fe537fec983a96c3c1a92365/Source/RxStarscream.swift#L18) of a `DelegateProxy`. Due to the way `DelegateProxy` works, it only calls `registerKnownImplementations()` for the first observed instance of the generic, breaking all following implementations.

**Expected outcome**:

`DelegateProxy` should call `registerKnownImplementations()` for all variants of a generic.

**What actually happens**:

Execution fails, unless you call `registerKnownImplementations()` explicitly.

**Self contained code example that reproduces the issue**:

Using RxStarscream, as this is where the issue was observed:

```swift
import Starscream
import RxStarscream

// Dummy implementation of WebSocketClient protocol
class WebSocketMock: NSObject, WebSocketClient {
    override init() {
        // Possible workaround for bug
        // RxWebSocketDelegateProxy<WebSocketMock>.registerKnownImplementations()
    }

    weak var delegate: WebSocketDelegate?
    weak var pongDelegate: WebSocketPongDelegate?
    var disableSSLCertValidation: Bool = false
    var overrideTrustHostname: Bool = false
    var desiredTrustHostname: String?
    var sslClientCertificate: SSLClientCertificate?
    var security: SSLTrustValidator?
    var enabledSSLCipherSuites: [SSLCipherSuite]?

    var isConnected= false

    func connect() { }
    func disconnect(forceTimeout _: TimeInterval?, closeCode _: UInt16) { }
    func write(string _: String, completion _: (() -> Void)?) { }
    func write(data _: Data, completion _: (() -> Void)?) { }
    func write(ping _: Data, completion _: (() -> Void)?) { }
    func write(pong _: Data, completion _: (() -> Void)?) { }
}

WebSocket(url: URL(string: "wss://echo.websocket.org")!).rx.connected.bind { print("Connected real: \($0)") }
WebSocketMock().rx.connected.bind { print("Connected mock: \($0)") } // errors
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

`4.4.2`

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
10.2
```

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] I have a significant code base

**Comment by kzaher** [comment]
> DelegateProxy should call registerKnownImplementations() for all variants of a generic.

How?

**Comment by fb55** [comment]
The issue seems to be that RxCocoa only checks whether it has already seen the `Delegate` (not the `ParentObject` variant) before calling `registerKnownImplementations()`. The `Delegate` stays the same here and might even be the same for other Rx wrappers, given that RxStarscream uses `NSObjectProtocol` as the delegate type.

Given that `ParentObject` already has a requirement to extend `AnyObject`, would there be an issue with including it inside the `identifier` implementation?

**Comment by kzaher** [comment]
Commit or PR?

I'm unsure what is your suggestion.

**Comment by kzaher** [comment]
No response.
