### ISSUE TITLE
Can't build Carthage with RxSwift in Swift 5, Xcode 10.2

### ISSUE THREAD

**Issue by codepgq** [ReactiveX/RxSwift#1910]
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/panguoquan/Desktop/项目部分/OSChina/CDNLights/CDNLights/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcworkspace -scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/panguoquan/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l8/zc8808q119d82s3ybqhfhrqh0000gn/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/panguoquan/Desktop/项目部分/OSChina/CDNLights/CDNLights/Carthage/Checkouts/ReactiveSwift)

/Users/panguoquan/Desktop/项目部分/OSChina/CDNLights/CDNLights/Carthage/Checkouts/ReactiveSwift/Sources/Scheduler.swift:187:18: error: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'DispatchSourceTimerWrapper' to 'Hashable' by implementing 'hash(into:)' instead
        fileprivate var hashValue: Int {
                        ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(4 failures)

**Comment by kzaher** [comment]
Appreciate the humor, but April 1rst was yesterday 😆 .

This made me laugh though 😆
