### ISSUE TITLE
Error on archive submission: Bundle contains disallowed file 'Frameworks'

### ISSUE THREAD

**Issue by aexmachina** [ReactiveX/RxSwift#192]
When I install RxSwift using Carthage I get the following error when I submit the archive to the app store:

```
The bundle at 'foobar.app/Frameworks/RxSwift.framework' contains disallowed file 'Frameworks'
The bundle at 'foobar.app/Frameworks/RxCocoa.framework' contains disallowed file 'Frameworks'
The bundle at 'foobar.app/Frameworks/RxBlocking.framework' contains disallowed file 'Frameworks'
```

I can see that there is indeed a Frameworks directory created for each of these packages (but not for any of the other Carthage packages that we're using).

```sh
$ find Carthage -name Frameworks | xargs ls
Carthage/Build/iOS/RxBlocking.framework/Frameworks:
libswiftCore.dylib		libswiftDarwin.dylib		libswiftFoundation.dylib
libswiftCoreGraphics.dylib	libswiftDispatch.dylib		libswiftObjectiveC.dylib

Carthage/Build/iOS/RxCocoa.framework/Frameworks:
libswiftCore.dylib		libswiftCoreLocation.dylib	libswiftFoundation.dylib
libswiftCoreGraphics.dylib	libswiftDarwin.dylib		libswiftObjectiveC.dylib
libswiftCoreImage.dylib		libswiftDispatch.dylib		libswiftUIKit.dylib

Carthage/Build/iOS/RxSwift.framework/Frameworks:
libswiftCore.dylib		libswiftDarwin.dylib		libswiftFoundation.dylib
libswiftCoreGraphics.dylib	libswiftDispatch.dylib		libswiftObjectiveC.dylib
```

If I remove these directories then the archive submission is successful.

**Comment by kzaher** [comment]
Hi @aexmachina ,

Which version are you using?

Latest 2.0.0-alpha.4  version
https://github.com/ReactiveX/RxSwift/tree/2.0.0-alpha.4

should be fix it.

**Comment by aexmachina** [comment]
Yes, I'm using `github "ReactiveX/RxSwift" "2.0.0-alpha.4"`

**Comment by aexmachina** [comment]
For anyone else with this problem the workaround is to use a Run Script Build Phase to `rm -rf Carthage/Build/*/*/Frameworks` before the _Copy Carthage Frameworks_ step.

**Comment by kzaher** [comment]
I think there is a possibility that Carthage just overwrites files, which means you would have a union of old and new files.

There is also a possibility that Xcode cache is maybe wrong.

I've tried to build fresh version for myself right now and don't see Frameworks dir.

Could you please try to run

```
clean xcode derived data
rm -rf Carthage
carthage update
```

**Comment by aexmachina** [comment]
I've done that and I'm still getting those files. I'm using Carthage 0.9.3. Here's the output:

```sh
~/d/W/nxgen-ios (beta-deployment) $ ./bin/execute.sh clean
*** clean: Deleted all DerivedData for nxgen-ios
~/d/W/nxgen-ios (beta-deployment) $ rm -rf Carthage
~/d/W/nxgen-ios (beta-deployment) $ carthage update --platform iOS
*** Cloning Nimble
*** Cloning Quick
*** Cloning OHHTTPStubs
*** Cloning SwiftyJSON
*** Cloning RxSwift
*** Downloading Nimble.framework binary at "Nimble v2.0.0"
*** Downloading OHHTTPStubs.framework binary at "Swift Helpers & Xcode 7"
*** Checking out RxSwift at "2.0.0-alpha.4"
*** Checking out SwiftyJSON at "2.3.0"
*** Downloading Quick.framework binary at "v0.6.0"
*** xcodebuild output can be found in /var/folders/nm/3dhqnm9x5s5dvj818qrr4yzc0000gq/T/carthage-xcodebuild.dJy1dx.log
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
~/d/W/nxgen-ios (beta-deployment) $ ls Carthage/Build/*/*/Frameworks
Carthage/Build/iOS/RxBlocking.framework/Frameworks:
libswiftCore.dylib         libswiftDarwin.dylib       libswiftFoundation.dylib
libswiftCoreGraphics.dylib libswiftDispatch.dylib     libswiftObjectiveC.dylib

Carthage/Build/iOS/RxCocoa.framework/Frameworks:
libswiftCore.dylib         libswiftCoreLocation.dylib libswiftFoundation.dylib
libswiftCoreGraphics.dylib libswiftDarwin.dylib       libswiftObjectiveC.dylib
libswiftCoreImage.dylib    libswiftDispatch.dylib     libswiftUIKit.dylib

Carthage/Build/iOS/RxSwift.framework/Frameworks:
libswiftCore.dylib         libswiftDarwin.dylib       libswiftFoundation.dylib
libswiftCoreGraphics.dylib libswiftDispatch.dylib     libswiftObjectiveC.dylib

**Comment by kzaher** [comment]
Hm,
I've tried with both 
Xcode 7.1 (7B60)
Xcode 7.0.1 (7A1001)

So that means there is still something out there that we are doing differently ...

Could you maybe create an empty folder, add this 

Cartfile
```
git "https://github.com/ReactiveX/RxSwift" "2.0.0-alpha.4"
```

and run

```
carthage update --platform iOS
```

I'm curios will it make those Frameworks folder again.

It looks like it might be also worth doing

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

<img width="782" alt="screen shot 2015-10-14 at 13 24 15" src="https://cloud.githubusercontent.com/assets/1641148/10482240/f3a3e2ec-7276-11e5-8dba-8fbcb5fb7500.png">

**Comment by kzaher** [comment]
No new informations about this one so closing this one for now.

If somebody has similar issues, we can reopen this one.

**Comment by aexmachina** [comment]
Yes fair enough. It doesn't happen in a new project for me either. Workaround is working fine for me.
