### ISSUE TITLE
tvOS: Add additions for 9.0 focused items

### ISSUE THREAD

**Issue by gregpardo** [ReactiveX/RxSwift#193]
Example for UICollectionView focus I made. For some reason ControlType wasn't working but this is the basic idea. 

```Swift
extension UICollectionView {
    
    /**
     Reactive wrapper for `delegate` message `collectionView:didUpdateFocusInContext:withAnimationCoordinator:`.
     */
    public var rx_nextFocusUpdated: Observable<NSIndexPath> {
        let source = rx_delegate.observe("collectionView:didUpdateFocusInContext:withAnimationCoordinator:")
            .map { a -> NSIndexPath in
                let context = a[1] as! UICollectionViewFocusUpdateContext
                return context.nextFocusedIndexPath! as NSIndexPath
        }
        
        return source
    }
}
```

**Comment by gregpardo** [comment]
Hmm it looks like the .nextFocusedIndexPath value can actually be nil. It throws an error when the whole collectionview loses focus

**Comment by kzaher** [comment]
Hi @gregpardo ,

I would like to include those extensions in some form :)

Could you make a PR to `develop` branch so we can collaborate on this. 

If you have some idea of a cool small example project we can run on tvos, we can also discuss that :)

**Comment by gregpardo** [comment]
Updated to allow for nil values and opened pull request. 

https://github.com/ReactiveX/RxSwift/pull/197

Let me know your thoughts
