### ISSUE TITLE
_lock' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by waploaj** [ReactiveX/RxSwift#1934]
**Short description of the issue**:

  After pod installing for the first time,  I'm unable to compile and am stuck on DisposeBag.swift this func i get error 
```

 /// Convenience function allows an array of disposables to be gathered for disposal.
    public func insert(_ disposables: [Disposable]) {
        self._lock.lock(); defer { self._lock.unlock() }   __>error says _lock' is inaccessible due to 'private' protection level
        if self._isDisposed {
            disposables.forEach { $0.dispose() }
        } else {
            self._disposables += disposables
        }
    }
```

**Expected outcome**:

  _what you expect to happen goes here_

**What actually happens**:

  _what actually happens goes here_

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [ 1] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ 1] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
i have try with xcode 10, xcode 9

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ 1] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ 1] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ 1] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Which version of RxSwift are you using? It looks like an old version, I'm not seeing any locks in DispatchQueueConfiguration: https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/Internal/DispatchQueueConfiguration.swift

The code you mention seems to come from DisposeBag but it's still not the latest version: https://github.com/ReactiveX/RxSwift/blob/65efb404c80fe1b23108c8fbb57d05b615e21c93/RxSwift/Disposables/DisposeBag.swift#L51

**Comment by waploaj** [comment]
@freak4pc am using version 4.0 and sorry for clarification its in disposebag.swift. and am having another issue in 
1. schedule(deadline:repeating: leeway) is unavailable on (on DispatchQueueConfiguration.swift line 47)
```
let timer = DispatchSource.makeTimerSource(queue: self.queue)
        timer.schedule(deadline: deadline, leeway: self.leeway) on this line 47 error schedule(deadline:repeating:leeway:)' is unavailable

```

**Comment by freak4pc** [comment]
Could you try a newer version of RxSwift? e.g. 4.4.2 or 4.5 ?

**Comment by waploaj** [comment]
is it compatible with swift 3.x

**Comment by freak4pc** [comment]
I believe up to 4.2.0 or 4.3.0 still supports Swift 3, but it's best to just experiment ;)

**Comment by waploaj** [comment]
Am still getting the same error. Am try to understand what its the cause can you please assist  me if you don't mind?  can i share the repo with you

**Comment by seanadkinson** [comment]
Not sure if its related, but I'm seeing `EXC_BAD_ACCESS` on a similar line:

```
func register(synchronizationErrorMessage: SynchronizationErrorMessages) {
            self._lock.lock(); defer { self._lock.unlock() }  // <-- Throwing EXC_BAD_ACCESS
            ...
}
```

Just upgraded to Xcode 10.2, and I'm using RxSwift `4.5.0`.

**Comment by freak4pc** [comment]
That seems unrelated. do you have some code around this we could look at ? @kzaher

**Comment by waploaj** [comment]
> That seems unrelated. do you have some code around this we could look at ? @kzaher

yes

**Comment by edmond-c** [comment]
Also on `4.5.0`. Changing the Swift Language Version to `4.2` fixed it:
![image](https://user-images.githubusercontent.com/48694605/56621664-9189f180-65ea-11e9-8a5c-ed953c022c35.png)

**Comment by kzaher** [comment]
I think this was a problem because we didn't have a specific version in podspec. This should go away with 5.0.

**Comment by freak4pc** [comment]
Should be OK with 5.0. If this is still an issue please open a new Issue with updated information.
