### ISSUE TITLE
The link about Swift 3.x branch in readMe.md is invalid

### ISSUE THREAD

**Issue by beforeold** [ReactiveX/RxSwift#1941]
**Short description of the issue**:

  when i clicked the link about Swift 3.x link in the readme.md，the browser show the 404 page

**Expected outcome**:

  lead me to the right page or remove the link if not availiable

**What actually happens**:

  show the 404 page

**Self contained code example that reproduces the issue**:

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ √] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
We won’t support Swift 3 soon since Swift 5 is already coming out. I think the latest supporting versions is 4.3.0

**Comment by beforeold** [comment]
> We won’t support Swift 3 soon since Swift 5 is already coming out. I think the latest supporting versions is 4.3.0
Cool, so the readme file will be upated someday, just let you know. I am going to close this issue.

**Comment by freak4pc** [comment]
The readme file in the develop branch should be updated. Thank you!
