### ISSUE TITLE
UITableViewCell Delete

### ISSUE THREAD

**Issue by kai120897660** [ReactiveX/RxSwift#1955]
I tap UItableViewCell delete when I use UITableView. We get error:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (15) must be equal to the number of rows contained in that section before the update (15), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

I aready reaload dataSourece, I write the code like this :
![image](https://user-images.githubusercontent.com/16075552/56780161-cd060500-6810-11e9-9c41-3f179af3388f.png)
![image](https://user-images.githubusercontent.com/16075552/56780179-e0b16b80-6810-11e9-98aa-5ce165636d3b.png)
Can you tell me what to do?

**Comment by freak4pc** [comment]
Hey, you're not supposed to delete rows directly - you should delete the model from the data source itself (e.g. emit a new set of models). 

This isn't a bug in RxSwift at all, if you have usage questions, please open a StackOverflow Question or refer to our Slack channel.

Thanks!
