### ISSUE TITLE
Adding skipLast to the core lib

### ISSUE THREAD

**Issue by DivineDominion** [ReactiveX/RxSwift#1957]
I was looking for an implementation of `skipLast(n)` that would only begin emitting events after `n` events have passed. Turns out it isn't part of the core. It's part of the ReactiveX docs, though:

Is this something you'd want to add? If not, I'd open a PR for e.g. `RxSwiftExt`.

## Reference Material 

- http://reactivex.io/documentation/operators/skiplast.html
- http://introtorx.com/Content/v1.0.10621.0/05_Filtering.html#SkipLastTakeLast 

Here's an example implementation of the operator:

```swift
extension Observable {
    func skipLast(_ count: Int = 1) -> Observable<Element> {
        let cacheSize = count + 1
        return self
            .scan([]) { (cache, next) -> [Element] in
                Array(cache.appending(next).takeLast(cacheSize))
            }
            .filter { $0.count >= cacheSize }
            .map { $0.first! }
    }
}

extension Collection {
    func takeLast(_ k: Int) -> DropFirstSequence<Self> {
        if self.count > k {
            return self.dropFirst(self.count - k)
        } else {
            return self.dropFirst(0)
        }
    }
}

extension Array {
    public func appending(_ newElement: Element) -> Array<Element> {
        var result = self
        result.append(newElement)
        return result
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift v4.5.0

**Comment by freak4pc** [comment]
I personally like the idea (the implementation will need to be different and use the actual stream elements [Sink] and not operator composition). If Kruno approves:)

**Comment by kzaher** [comment]
@DivineDominion  @freak4pc I'm not sure I understand why do you think we should include this?

**Comment by DivineDominion** [comment]
I ask here and not on RxSwiftExt because it's part of the core ReactiveX docs. What are you asking for? Like, is there a "what's included in the core" test this could pass or fail?

**Comment by MortyMerr** [comment]
@kzaher I thought this repo is trying to be sync with ReactiveX interface. If something is there - it should be added to RxSwift, because a potential user will expect to find this operator here. What do you think?

**Comment by kzaher** [comment]
@MortyMerr

> I thought this repo is trying to be sync with ReactiveX interface. If something is there - it should be added to RxSwift, because a potential user will expect to find this operator here. What do you think?

You have got this half right.

**We are trying to be in sync with their terminology, interfaces and concepts and apply them to Swift.** I don't want to learn 100 different terminologies that describe stateful systems.

What that statement doesn't imply is that some implementation added some operator all others should do the same. That idea is wrong on both practical side and game theory side.

I think that most implementations contain the most common and useful operators, but not all implementations contain all operators. That's simply impossible. **The set of possible operators is not finite**.

It is not sufficient to say that some other maintainer of some Rx library has added some operator and that's a good reason why we should bloat this codebase. That would mean that somebody can slip some useless operator to some maintainer I have no idea about and that I would be forced to maintain it. That means that the barrier to add new code is extremely low, which means that the size of the library will blow up with time. I'm not saying that all project have consistent policies but since I'm not maintainer of other project I don't have any interest in their policies.

The only approach that's viable IMHO is designing a small number of highly configurable operators.

**Comment by MortyMerr** [comment]
@kzaher I meant not all Rx repos, but only only ReactiveX official spec. But I get your point, thank you.
Just to outline: do you think `skipLast` is useless operator? Should this issue be closed? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kzaher** [comment]
> I meant not all Rx repos, but only only ReactiveX official spec

There is no official spec. There is a web page (glossary), but not an official spec. 
Glossary != Spec

https://github.com/ReactiveX/reactivex.github.io

You can make PRs to that web page in the same way you can do a PR to some repo.

> do you think skipLast is useless operator? Should this issue be closed?

I guess I try to keep open minded and who ever wants us to merge something is welcome to provide me with reasons why he wants this to be merged.

Usually people provide, I've seen this operator on ReactiveX. If that is the only reason, then I would by default say no.

Something needs to be extremely useful to a lot of people for it to be merged. This is a large codebase as it is and deprecating/pulling stuff out is a tiresome process that will just annoy people using that functionality.

**Comment by DivineDominion** [comment]
Sounds legit. Do you want this issue to stay open for others to vote in favor/chime in, or does it makes more sense to close the issue and leave this as a google-able place for future discussion?

I'm fine with this becoming part of RxSwiftExt just as well. Don't know how you folks write apps without this operator, but maybe I'm just weird in my operator setup ;)

**Comment by AlexisQapa** [comment]
While on the implementation side the "last" naming seems fine on the user side shouldn't it be skipFirst ? I might have missed something but I read it as skip the first n elements

**Comment by MortyMerr** [comment]
@AlexisQapa there is already `skip` which skips first n elements. This issue is about the operator, which allows skipping n last elements

**Comment by AlexisQapa** [comment]
Yeah I thought so. Sorry ^^

**Comment by MortyMerr** [comment]
@DivineDominion could u please provide an example in which this operator is very useful? Maybe, more people would be interested in it that :)

**Comment by DivineDominion** [comment]
I use it in my app to fix a timing issue at the moment, when me knowing that I need to save metadata is tied to the source of metadata having _changed_. That's why I want to rewind by 1 event.

----

**Use case:** When the user changes the  currently disp[layed note, store the latest scroll offset as file metadata for later restoration.

**Sequence**

- Changing the displayed note also changes the scroll offset (e.g. when the new note is shorter than the last)
- Use the value _before_ the change to the new note instead

```swift
let savingScrollOffset: Observable<Void> = Observable.of(noteChange, beginIdling).merge()
savingScrollOffset
    .withLatestFrom(noteScrollOffset.skipLast())  // ViewModel is already using the new values
    .distinctUntilChanged()
    .subscribe(_saveNoteScrollOffset)
    .disposed(by: disposeBag)
```

**Comment by freak4pc** [comment]
I'm closing every issue older than 6 months. If this is still an issue for you, please comment and I can reopen :) Thanks !
