### ISSUE TITLE
 Is the 5.0.0 tag changed?

### ISSUE THREAD

**Issue by hllGitHub** [ReactiveX/RxSwift#1961]
**Short description of the issue**:

``` sh
   git fetch --tags
``` 
It failed.

```
From https://github.com/ReactiveX/RxSwift
 * branch              HEAD       -> FETCH_HEAD
 ! [rejected]          5.0.0      -> 5.0.0  (would clobber existing tag)
```

Is the 5.0.0 tag changed?

**Expected outcome**:

  Hope can `get fetch --tags`. 

**What actually happens**:

```
From https://github.com/ReactiveX/RxSwift
 * branch              HEAD       -> FETCH_HEAD
 ! [rejected]          5.0.0      -> 5.0.0  (would clobber existing tag)
```
**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

10.2

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment**:
I guess you modified the remote tag (5.0.0). And I can run `git fetch --tags` successfully after deleting local repo and git clone again. If my guess is correct, hope you can keep tags and don't change it often. Thanks!

**Comment by freak4pc** [comment]
I don't believe we've changed these tags, this repo is actually very strict in this regard. Anyways I believe you can add `--force` to make sure you have the latest.

**Comment by freak4pc** [comment]
Since I don’t see a technical issue to solve here, I’m closing this for now. Feel free to leave additional comments if you feel this wasn’t resolved.

**Comment by hllGitHub** [comment]
My current repo was pulled yesterday. The output of `git show 5.0.0` as follows:
``` sh
$git show  5.0.0
commit 3fba536bcea3a4ebe3c7b5c542a7c658a0c4200c (tag: 5.0.0)
Author: Michele Volpato <mvolpato@users.noreply.github.com>
Date:   Sun Apr 28 13:25:30 2019 +0200

    Fix wrong deprecated message

diff --git a/RxSwift/Traits/PrimitiveSequence.swift b/RxSwift/Traits/PrimitiveSequence.swift
index 9e4cf320..57f2f75f 100644
--- a/RxSwift/Traits/PrimitiveSequence.swift
+++ b/RxSwift/Traits/PrimitiveSequence.swift
@@ -26,7 +26,7 @@ public protocol PrimitiveSequenceType {
     @available(*, deprecated, message: "Use `Trait` instead.")
     typealias TraitType = Trait

-    @available(*, deprecated, message: "Use `Trait` instead.")
+    @available(*, deprecated, message: "Use `Element` instead.")
     typealias ElementType = Element

     // Converts `self` to primitive sequence.
```
Current commit is c6c0c540109678b96639c25e9c0ebe4a6d7a69a9 for tag 5.0.0.

**Comment by freak4pc** [comment]
It's not something we commonly do, but seems like it was done for that release yesterday and you got caught right in that 1 hour when you pulled the tag. Anyways the --force pull option I mentioned should resolve it.
