### ISSUE TITLE
Lacking RxAtomic in Latest Releast (5.0.1)

### ISSUE THREAD

**Issue by krystlemaelabio** [ReactiveX/RxSwift#1964]
Can we use RxAtomic instead from 4.5.0?

**Comment by freak4pc** [comment]
No. RxAtomic is deprecated since it created a ton of thread sanitizing issues. RxSwift [uses `NSLock` instead](https://github.com/ReactiveX/RxSwift/blob/master/Platform/AtomicInt.swift#L12) now.
