### ISSUE TITLE
Library RxCocoa cannot find 

### ISSUE THREAD

**Issue by MarcSteven** [ReactiveX/RxSwift#1965]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://slack.rxswift.org/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:The library RxCocoa cannot find 

  _description here_

**Expected outcome**:
I hope it can find and then compile successfully

  _what you expect to happen goes here_
compiler successfully

**What actually happens**:
Cannot find the library

  _what actually happens goes here_

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
Xcode the latest version
```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ 1] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by mironal** [comment]
I got a similar problem.

```
dyld: Library not loaded: @rpath/RxRelay.framework/RxRelay
  Referenced from: /Users/***/Library/Developer/Xcode/DerivedData/***/Build/Products/***/Model.framework/Model
  Reason: image not found
```

**Comment by MarcSteven** [comment]
It's a issue since RxSwift 4.4 later ,because I never met this issue before 4.4.
I tried to find the solutions and then cannot solve it .

**Comment by krystlemaelabio** [comment]
Similar problem. RxRelay referenced RxCocoa but image not found. Runtime error. Please fix ASAP.

Used latest build 5.0.1.

Thanks.

**Comment by freak4pc** [comment]
RxRelay doesn’t reference RxCocoa. Please provide a reproducible sample project.

**Comment by MarcSteven** [comment]
I had solved this issue ,the solution as below:
Enter into **Build Phase** and then click the **Link Binary with Libraries**
Remove **LRxSwift.a and LRxCocoa.a**
And then it works!

**Comment by krystlemaelabio** [comment]
Sorry I meant RxCocoa is referenced by RxRelay but RxCocoa image not found, runtime error. Can you release official build with this resolved? Thanks.

**Comment by freak4pc** [comment]
This isn’t a problem with the library - you probably have some linking issue like the person above.

If you have a reproducible project I can take a look.

**Comment by freak4pc** [comment]
And again - RxRelay does **not** reference RxCocoa.

**Comment by Nabeatsu** [comment]
I created [a reproducible sample project](https://github.com/Nabeatsu/RxCocoaCannotFindSample) .
this repository reproduce this issue in the initial commit.
Next commit resolve this issue. the solution is to enter into Build Phase and then click the Link Binary with Libraries and delete RxSwift.framework and RxCocoa.framework.

**Comment by freak4pc** [comment]
Well, that "reproduction" is a problem with your own project. It does not relate to this library at all to my understanding.

**Comment by reimondhill** [comment]
Well ... I am Having the same issue here ... Maybe it is obvious but i can't see it ...

**Comment by reimondhill** [comment]
Adding RxRelax solves the issue

**Comment by freak4pc** [comment]
FYI - If you're using Carthage this makes sense. RxRelay is new, if you're using RxCocoa you'll want to drop it in after doing a `carthage update`. 

If your issue doesn't relate to this specifically, please open a new issue with information.
