### ISSUE TITLE
RxCocoa image not found

### ISSUE THREAD

**Issue by krystlemaelabio** [ReactiveX/RxSwift#1967]
RxCocoa is referenced by RxRelay but RxCocoa image not found, runtime error. Can you release official build with this resolved? Thanks.

Expected: No runtime errors related to Rx components.

**Comment by ashok1089** [comment]
I am trying to refactor Variable to Behavior Relay with RxSwift 5.0.1 and running into below runtime error:

dyld: Library not loaded: @rpath/RxRelay.framework/RxRelay
  Referenced from: 
  Reason: image not found

**Comment by MortyMerr** [comment]
Delete derived data & clean & rebuild should help

**Comment by ashok1089** [comment]
Tried already did not work out. thanks though

**Comment by freak4pc** [comment]
Hey @ashok1089 - based on your error, you're using Carthage. 
Make sure you dragged the built binary (RxRelay.framework) to your project, as it's not part of RxCocoa directly, it's a separate framework (as the error message states).

**Comment by wfs498121294** [comment]
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa
  Referenced from: /var/containers/Bundle/Application/A76FECA0-B597-4153-9BAF-E857A1624CD2/RxExample-iOS.app/RxExample-iOS
  Reason: image not found

**Comment by freak4pc** [comment]
Locking. If anyways has any other issues, please open a new issue.
