### ISSUE TITLE
Up to date API docs

### ISSUE THREAD

**Issue by bbqsrc** [ReactiveX/RxSwift#1969]
http://cocoadocs.org/docsets/RxSwift/4.0.0/ does not even have `Observable` for some reason.

However, http://cocoadocs.org/docsets/RxSwift/3.5.0 did.

Can this be fixed?

**Comment by freak4pc** [comment]
I'm not too sure where CocoaDocs takes these docs from at all. @kzaher thoughts?

**Comment by kzaher** [comment]
This should be generated from a podspec as far as I can tell.

**Comment by freak4pc** [comment]
Doesn't seem like CocoaDocs is maintained at all. @bbqsrc 

![image](https://user-images.githubusercontent.com/605076/57459535-1aa45800-727c-11e9-98ad-184ab55c7a28.png)

**Comment by bbqsrc** [comment]
Do you publish the API documentation anywhere else? It is the first (and seemingly only) result in Google for rxswift api docs.

**Comment by freak4pc** [comment]
I don't think there's official API docs but you can generate the API using jazzy (there's a `jazzy.yml` in the main folder): https://github.com/realm/jazzy

Also you can just browser through the source files and the **Documentation** folder.

**Comment by kzaher** [comment]
I don't know what to do here. Cocoadocs was maintaining the docs.

We have inline docs and reactivex.io.

**Comment by freak4pc** [comment]
Hey @bbqsrc & @kzaher 
I've uploaded the Jazzy docs to https://docs.rxswift.org/ for everyone to enjoy. 

I'm hoping to open a PR soon to make the process of keeping these updated more streamlined.
