### ISSUE TITLE
RxTest: TestScheduler fails when created as a static library

### ISSUE THREAD

**Issue by mauricekraus** [ReactiveX/RxSwift#1980]
**Short description of the issue**:
I installed RxTest, RxBlocking, RxSwift and RxCocoa 5 over Cocoapods as static libraries (i.e. without "use_frameworks"). The project itself works fine, everything compiles well even in a larger project, but if I switch to the test target and instantiate a ```let scheduler = TestScheduler(initialClock: 0)```, the test will fail.

**Expected outcome**:
That the test will succeed.

**What actually happens**:
32 Errors were found by Xcode.

> Undefined symbols for architecture x86_64:
  "protocol descriptor for RxSwift.VirtualTimeConverterType", referenced from:
      protocol conformance descriptor for RxTest.TestSchedulerVirtualTimeConverter : RxSwift.VirtualTimeConverterType in RxTest in libRxTest.a(TestSchedulerVirtualTimeConverter.o)
  "RxSwift.VirtualTimeScheduler.(_running in _260D0E4B3CF48EA56DEBEF4C56AB21A1).getter : Swift.Bool", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_running in _260D0E4B3CF48EA56DEBEF4C56AB21A1).setter : Swift.Bool", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_running in _260D0E4B3CF48EA56DEBEF4C56AB21A1).modify : Swift.Bool", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_clock in _260D0E4B3CF48EA56DEBEF4C56AB21A1).getter : A.VirtualTimeUnit", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_schedulerQueue in _260D0E4B3CF48EA56DEBEF4C56AB21A1).setter : RxSwift.PriorityQueue<RxSwift.VirtualSchedulerItem<A.VirtualTimeUnit>>", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.scheduleRelative<A>(_: A1, dueTime: Dispatch.DispatchTimeInterval, action: (A1) -> RxSwift.Disposable) -> RxSwift.Disposable", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_schedulerQueue in _260D0E4B3CF48EA56DEBEF4C56AB21A1).modify : RxSwift.PriorityQueue<RxSwift.VirtualSchedulerItem<A.VirtualTimeUnit>>", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_converter in _260D0E4B3CF48EA56DEBEF4C56AB21A1).setter : A", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_converter in _260D0E4B3CF48EA56DEBEF4C56AB21A1).modify : A", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_nextId in _260D0E4B3CF48EA56DEBEF4C56AB21A1).getter : Swift.Int", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_nextId in _260D0E4B3CF48EA56DEBEF4C56AB21A1).setter : Swift.Int", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.stop() -> ()", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "method descriptor for RxSwift.VirtualTimeScheduler.__allocating_init(initialClock: A.VirtualTimeUnit, converter: A) -> RxSwift.VirtualTimeScheduler<A>", referenced from:
      method descriptor for RxTest.TestScheduler.start<A>(() -> RxSwift.Observable<A>) -> RxTest.TestableObserver<A> in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_nextId in _260D0E4B3CF48EA56DEBEF4C56AB21A1).modify : Swift.Int", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.clock.getter : A.VirtualTimeUnit", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.schedule<A>(_: A1, action: (A1) -> RxSwift.Disposable) -> RxSwift.Disposable", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.scheduleRelativeVirtual<A>(_: A1, dueTime: A.VirtualTimeIntervalUnit, action: (A1) -> RxSwift.Disposable) -> RxSwift.Disposable", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_clock in _260D0E4B3CF48EA56DEBEF4C56AB21A1).setter : A.VirtualTimeUnit", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.start() -> ()", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "method descriptor for RxSwift.VirtualTimeScheduler.adjustScheduledTime(A.VirtualTimeUnit) -> A.VirtualTimeUnit", referenced from:
      method descriptor for RxTest.TestScheduler.start<A>(() -> RxSwift.Observable<A>) -> RxTest.TestableObserver<A> in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.advanceTo(A.VirtualTimeUnit) -> ()", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.now.getter : Foundation.Date", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.sleep(A.VirtualTimeIntervalUnit) -> ()", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_clock in _260D0E4B3CF48EA56DEBEF4C56AB21A1).modify : A.VirtualTimeUnit", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.init(initialClock: A.VirtualTimeUnit, converter: A) -> RxSwift.VirtualTimeScheduler<A>", referenced from:
      RxTest.TestScheduler.init(initialClock: Swift.Int, resolution: Swift.Double, simulateProcessingDelay: Swift.Bool) -> RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.scheduleAbsoluteVirtual<A>(_: A1, time: A.VirtualTimeUnit, action: (A1) -> RxSwift.Disposable) -> RxSwift.Disposable", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_converter in _260D0E4B3CF48EA56DEBEF4C56AB21A1).getter : A", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.(_schedulerQueue in _260D0E4B3CF48EA56DEBEF4C56AB21A1).getter : RxSwift.PriorityQueue<RxSwift.VirtualSchedulerItem<A.VirtualTimeUnit>>", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.findNext() -> RxSwift.VirtualSchedulerItem<A.VirtualTimeUnit>?", referenced from:
      type metadata for RxTest.TestScheduler in libRxTest.a(TestScheduler.o)
  "nominal type descriptor for RxSwift.VirtualTimeScheduler", referenced from:
      method descriptor for RxTest.TestScheduler.start<A>(() -> RxSwift.Observable<A>) -> RxTest.TestableObserver<A> in libRxTest.a(TestScheduler.o)
  "RxSwift.VirtualTimeScheduler.deinit", referenced from:
      RxTest.TestScheduler.deinit in libRxTest.a(TestScheduler.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

**Self contained code example that reproduces the issue**:

To reproduce the issue:
1. create a fresh project
2. Inititalize Cocoapods with the Podfile
```ruby
#use_frameworks!

target 'TestProject' do  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
 
  target 'TestProjectTests' do
      inherit! :search_paths
      # Pods for testing
      pod 'RxBlocking', '~> 5'
      pod 'RxTest', '~> 5'
  end
end
```
3. In your test target run the following test case

```swift
import XCTest
import RxSwift
import RxTest

@testable import TestProject

class TestProjectTests: XCTestCase {

    override func setUp() {
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }

    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func testExample() {
        let scheduler = TestScheduler(initialClock: 0)
        // Use XCTAssert and related functions to verify your tests produce the correct results.
    }

    func testPerformanceExample() {
        // This is an example of a performance test case.
        self.measure {
            // Put the code you want to measure the time of here.
        }
    }

}
```

4. When you remove the # from the use_frameworks the test should not fail anymore.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.0

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.2.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [X] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Yep, Swift compiler bug. Sorry, nothing we can do here.

**Comment by yoonhg84** [comment]
I also experienced the same problem. 
Try the following:

```
// TestProjectTests Build Settings
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/RxSwift"
OTHER_LDFLAGS = $(inherited) -l"RxSwift"
```

**Comment by iwheelbuy** [comment]
try this way:

```
def pods_main
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
end

def pods_test
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
end

target 'TestProject' do
    pods_main
end

target 'TestProjectTests' do
    pods_main
    pods_test
end
```
