### ISSUE TITLE
Add compactMap to sharedSequence, Single and Maybe

### ISSUE THREAD

**Issue by gringoireDM** [ReactiveX/RxSwift#1983]
Now that we have `compactMap` operator for `ObservableType` in the RxSwift core, i believe it would be useful to have the same operator for `SharedSequence`, `Single` and `Maybe`, like it's done for other operators like `map`, `filter` and so on.

A possible implementation is given in the PR #1978

**Comment by acecilia** [comment]
And also for Driver please :)

**Comment by kzaher** [comment]
We've merged your proposal.
