### ISSUE TITLE
Module 'RxSwift' was created for incompatible target x86_64-apple-macosx10.9: 

### ISSUE THREAD

**Issue by Nilesh-Jha-14** [ReactiveX/RxSwift#1984]
Module 'RxSwift' was created for incompatible target x86_64-apple-macosx10.9:

**Comment by freak4pc** [comment]
If you don't provide any more details we'll unfortunately have to close this issue.

**Comment by Nilesh-Jha-14** [comment]
So My project is working Fine on one System having Xcode 9.4.1 ... I installed Xcode 10.2  and xcode 9.4.1 in another system... When I run the project in new System after updating Carthage.. Its giving this error

**Comment by freak4pc** [comment]
If you want support for Xcode 10.2 you'll need RxSwift 5.

**Comment by Nilesh-Jha-14** [comment]
So Now I am using Xcode 10.2 and RXSwift 5.0.1 which is being downloaded automatically .. Now I am getting this error.

Could not find module 'RxSwift' for architecture 'x86_64'; found: i386, armv7k, arm, arm64_32

**Comment by freak4pc** [comment]
Hey, I have a clean project where there are no issues. If you can create a project with a reproduction of the issue, I can take a look.

**Comment by kzaher** [comment]
This seems stale.
