### ISSUE TITLE
Unable to build RxCocoa using xcodebuild

### ISSUE THREAD

**Issue by iwheelbuy** [ReactiveX/RxSwift#1985]
**Short description of the issue**:

Unable to build a project with *xcodebuild* when *OTHER_SWIFT_FLAGS = -Xfrontend -debug-time-function-bodies* is used.

**Expected outcome**:
```
** BUILD SUCCEEDED **
```

**What actually happens**:

```
0.06ms	/Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/Common/ControlTarget.swift:27:9	getter selector
/Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/Common/DelegateProxy.swift:90:43: error: use of undeclared type 'Selector'
        open func sentMessage(_ selector: Selector) -> Observable<[Any]> {

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/Common/DelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/Foundation/NSObject+Rx.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/Common/RxCocoaObjCRuntimeError+Extensions.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxCollectionViewDataSourcePrefetchingProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxCollectionViewDataSourceProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxNavigationControllerDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxPickerViewDataSourceProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxPickerViewDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxScrollViewDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxSearchBarDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxSearchControllerDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxTabBarControllerDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxTabBarDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxTableViewDataSourcePrefetchingProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxTableViewDataSourceProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxTextStorageDelegateProxy.swift
	CompileSwift normal x86_64 /Users/iwheelbuy/Desktop/Nice/Pods/RxCocoa/RxCocoa/iOS/Proxies/RxWebViewDelegateProxy.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(18 failures)
```

**Self contained code example that reproduces the issue**:

Created a [blank project](https://github.com/ReactiveX/RxSwift/files/3206646/Nice.zip), added Podfile with RxSwift, installed pods.

```
xcodebuild -workspace Nice.xcworkspace -scheme Nice -sdk iphonesimulator -arch x86_64 -configuration Debug clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies"
```
I also tried `-UseModernBuildSystem=NO`

This command used to work 6-12 months ago.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
platform :ios, '10.0'

inhibit_all_warnings!
use_modular_headers!

def pod__Rx
    pod 'RxCocoa', '5.0.0'
    pod 'RxDataSources', '4.0.1'
    pod 'RxGesture', '3.0.0'
    pod 'RxOptional', '4.0.0'
    pod 'RxSwift', '5.0.0'
end

target 'Nice' do
    pod__Rx
end
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 10.2
Build version 10E125
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
I don't have Xcode 10.2, does it work with 10.2.1 for you?

Anybody can repro this?

I've tried and works for me.

```
pod --version
```
1.7.0.beta.3

[C.zip](https://github.com/ReactiveX/RxSwift/files/3233862/C.zip)

**Comment by iwheelbuy** [comment]
Thank you for your response. Will try using 10.2.1 on another machine.

**Comment by iwheelbuy** [comment]
I've checked your project on three different machines with various Xcode and Cocoapods versions and with no success. It still fails with the output listed in _What actually happens_

**Comment by kzaher** [comment]
Oh,

I've looked into this. This is nothing on our end. You can't just override flags in that way because you are messing with CocoaPods magic.

You need to add the `-Xfrontend -debug-time-function-bodies` to the `OTHER_SWIFT_FLAGS` in the project build settings manually.
