### ISSUE TITLE
v4.5.0 binary seems to be incompatible with Xcode 10.1 (swift 4.2.1)

### ISSUE THREAD

**Issue by hiroshi** [ReactiveX/RxSwift#1993]
> :warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://slack.rxswift.org/) first. :warning: 

Hi, the url must be https://rxswift.slack.com/, slack.rxswift.org is a dead domain.
And the slack workspace seems to require invitation. right?
<a href="https://gyazo.com/7ab517f8489cbc9a848425035b4c04a5"><img src="https://i.gyazo.com/7ab517f8489cbc9a848425035b4c04a5.png" alt="Image from Gyazo" width="320"/></a>

**Short description of the issue**:
I'm trying to migrate a swift 3 project that uses RxSwift v3.4.0 to be able to built with Xcode 10.2. I need to migrate it to swift 4.x with Xcode 10.1 (Xcode 10.2 don't support migration from swift 3).

I see this.
https://github.com/ReactiveX/RxSwift/releases/tag/5.0.0
> If you're using Xcode 10.1 and below, please use RxSwift 4.5.

So, I changed Cartfile to:
```
github "ReactiveX/RxSwift" "4.5.0"
```

but it say:
`Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1).`

<a href="https://gyazo.com/61a09898713ec5de14680694e2689192"><img src="https://i.gyazo.com/61a09898713ec5de14680694e2689192.png" alt="Image from Gyazo" width="796"/></a>

**Expected outcome**:

It works with Xcode 10.1.

**What actually happens**:

```
$ carthage bootstrap --platform iOS --cache-builds
...
*** Downloading RxSwift.framework binary at "[4,5]"
***  Skipped installing RxSwift.framework binary due to the error:                                             
        "Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."                                        

    Falling back to building from the source
...
```

**Self contained code example that reproduces the issue**:
Download 
```
github "ReactiveX/RxSwift" "4.5.0"
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

v4.5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
$ xcodebuild -version 
Xcode 10.1
Build version 10B61
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

10.2.1 (/Applicatoins/Xcode.app)
10.1 ( I chose it with `xcode-select -s` before `carthage bootstrap`)

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base
  - [x] just started to migrate old codebase (swift3.0) to be able to be built with Xcode 10.2....

**Comment by kzaher** [comment]
I've tried http://slack.rxswift.org/ and it seems to be working for me. That's the invite link.
https://rxswift.slack.com/ is the slack domain after you get invite from http://slack.rxswift.org.

I'm not sure what's the problem here. We can only have one binary uploaded compatible with a single Xcode version. The binaries are just a convenience. The fallback to building seems to be working according to your description.

**Comment by freak4pc** [comment]
Hey @kzaher @hiroshi - the rxswift.org domain was down for a couple of days due to renewal issues, we solved it since.

**Comment by hiroshi** [comment]
> Hey @kzaher @hiroshi - the rxswift.org domain was down for a couple of days due to renewal issues, we solved it since.

Ah, I can reach the domain now. Thanks!

**Comment by hiroshi** [comment]
Hey @kzaher,

The link to slack workspace is not the subject of the issue! I'm sorry for reporting multiple topics in an issue though.

The subject is
> v4.5.0 binary seems to be incompatible with Xcode 10.1 (swift 4.2.1)

Was it resolved?

**Comment by freak4pc** [comment]
He answered I believe: 

> I'm not sure what's the problem here. We can only have one binary uploaded compatible with a single Xcode version. The binaries are just a convenience. The fallback to building seems to be working according to your description.

**Comment by hiroshi** [comment]
Sorry, I didn't understand the point until now.
