### ISSUE TITLE
TestScheduler start method never returns in some cases

### ISSUE THREAD

**Issue by c0diq** [ReactiveX/RxSwift#1997]
**Short description of the issue**:

  `TestScheduler.start()` never returns when an infinite observable using that scheduler is not subscribed within the start action block.

**Expected outcome**:

  `TestScheduler.start()` should not block.

**What actually happens**:

  Whenever an infinite observable using the test scheduler is subscribed outside of the start action, the `TestScheduler.start` method never returns if the observable never completes.

**Self contained code example that reproduces the issue**:

Here's an example of code where "finished" never gets printed
```swift
    let disposeBag = DisposeBag()
    let scheduler = TestScheduler(initialClock: 0)

    let infinite = Observable<Int>.interval(.seconds(1), scheduler: scheduler)

    infinite
        .subscribe()
        .disposed(by: disposeBag)

    print("started")
    _ = scheduler.start()
    print("finished")
```

Moving subscription inside the `start` action or forcing the `infinite` to complete after a while makes it work.
 
```swift
    let disposeBag = DisposeBag()
    let scheduler = TestScheduler(initialClock: 0)

    let infinite = Observable<Int>.interval(.seconds(1), scheduler: scheduler)

    _ = scheduler.start { infinite }
    print("finished")
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  5.0.1

**Platform/Environment**

  - [X] iOS
  - [X] macOS
  - [X] tvOS
  - [X] watchOS
  - [X] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.2.1
```

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by matvdg** [comment]
I have the same issue, it broke all my unit tests...

**Comment by kzaher** [comment]
Hi, guys,

I'm not sure what is your expectation, but as far as I can tell this is by design.

Doing this:
```
let disposeBag = DisposeBag()
    let scheduler = TestScheduler(initialClock: 0)

    let infinite = Observable<Int>.interval(.seconds(1), scheduler: scheduler)

    infinite
        .subscribe()
        .disposed(by: disposeBag)

    print("started")
    _ = scheduler.start()
    print("finished")
```
means simulate until there are items to be used. And there will always be items since 

`let infinite = Observable<Int>.interval(.seconds(1), scheduler: scheduler)`

doesn't ever complete.

```
_ = scheduler.start { infinite }
```
Means, 
```
public func start<Element>(_ create: @escaping () -> Observable<Element>) -> TestableObserver<Element> {
        return self.start(created: Defaults.created, subscribed: Defaults.subscribed, disposed: Defaults.disposed, create: create)
    }
```
Subscribe to the returned observable and dispose at 100 units (`Defaults.disposed`). So this is a finite simulation.

**Comment by c0diq** [comment]
Ah you are right. The problem started happening for me because the `zip` behavior changed. It used to complete as soon as one source completed. Now it doesn't and that causes the infinite problem. 

This example used to work prior to RxSwift 5.

```
    let disposeBag = DisposeBag()
    let scheduler = TestScheduler(initialClock: 0)

    let observable = Observable.zip(
        Observable<Int>.from([1, 2, 4]),  
        Observable<Int>.interval(.seconds(1), scheduler: scheduler)
    )
    .map { $0.0 }

    observable
        .subscribe()
        .disposed(by: disposeBag)

    print("started")
    _ = scheduler.start()
    print("finished")
```
I understand now. Thanks for checking into it.
