### ISSUE TITLE
What do you think about Apple new Combine?

### ISSUE THREAD

**Issue by BohdanCube** [ReactiveX/RxSwift#2001]
What do you think about Apple [new framework](https://developer.apple.com/documentation/combine?changes=latest_minor)?

Will you use it in some way in RxSwift or did they done partial copy of your functionalities in their own "new" framework?

I have a mixed feeling about this...

**Comment by freak4pc** [comment]
#1999

**Comment by BohdanCube** [comment]
> #1999

Thx
