### ISSUE TITLE
RxCocoa causes UIWebView link errors on UIKitForMac

### ISSUE THREAD

**Issue by noahsark769** [ReactiveX/RxSwift#2004]
**Short description of the issue**:

  When building projects for UIKitForMac (Apple's new Project Catalyst environment), RxCocoa fails to link because it expects `UIWebView` to be available. I created a sample project which demonstrates the issue at [NGRxCocoaUIKitForMacLinkingIssue](https://github.com/noahsark769/NGRxCocoaUIKitForMacLinkingIssue).

I think the solution here will probably be as simple as adding `#if !targetEnvironment(UIKitForMac)` around the parts of the codebase that expect UIWebView to be exposed by UIKit.

**Expected outcome**:

  The project should link when built for UIKitForMac

**What actually happens**:

  The project fails to link

**Self contained code example that reproduces the issue**:

   No code needed, since just including the RxCocoa cocoapod in the project reproduces the issue

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  Tested with 5.0.0, though I suspect this is an issue with all versions

**Platform/Environment**
UIKitForMac

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
  11.0 beta (11M336w)
```

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (11.0 and 10.2.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Seems there's a PR tracking this - #2002

**Comment by mariohahn** [comment]
+1

**Comment by noahsark769** [comment]
Looks like that PR was closed. Any word on another one being open yet? I could possibly look into this, but I probably won't have time for a while.

**Comment by iamDecode** [comment]
PR https://github.com/ReactiveX/RxSwift/pull/2012 fixes this and was merged into the develop branch. The API for Catalyst isn't stable so I do not expect this to land in a release before Xcode 11 stable is released. For the time being you can use the develop branch.

**Comment by freak4pc** [comment]
@iamDecode is right here. Feel free to target develop and well make a proper release once GM it out. Closing this for the time being.

**Comment by noahsark769** [comment]
Awesome, thanks for the work here!

**Comment by adozenlines** [comment]
The use of UIWebView in RxCocoa is still an issue. Apple is actively flagging app with UIWebView usage with a December 2020 deadline to resolve the issue.

**Comment by freak4pc** [comment]
UIWebView isn't used in RxSwift for months now. Make sure you're on the latest version.

**Comment by adozenlines** [comment]
No, but it's in RxCocoa and I cannot find RxCocoa anywhere in Github to make my post.

**Comment by adozenlines** [comment]
In my pod file, I'm not specifying a specific version when I do a pod update but when I search for the class it shows up in RxCocoa.

**Comment by freak4pc** [comment]
I imagine your podspec isn't updated. Look in your `Podfile.lock` what version is there, and run `pod repo update` before your `pod update`

**Comment by adozenlines** [comment]
Thanks, will do.

**Comment by adozenlines** [comment]
Did the pod repo update but it is stuck at 4.5.0

**Comment by freak4pc** [comment]
This isn't a proper issue to get help for this. I imagine something is locked in your setup, RxSwift is on 5.1.1, you will need to do some migration as well I imagine. 

I suggest coming to our Slack. http://slack.rxswift.org

**Comment by adozenlines** [comment]
Looks like Braid/Rx has a dependency on RxCocoa & RxSwift ~> 4.4.0.

**Comment by freak4pc** [comment]
That's very old :)

**Comment by adozenlines** [comment]
So I had to fork the Braid/Rx repo and edit the spec file to move onto 5.1.1. to resolve my issue
