### ISSUE TITLE
build ipa failed

### ISSUE THREAD

**Issue by codepgq** [ReactiveX/RxSwift#2009]
![image](https://user-images.githubusercontent.com/20208598/59397336-d77b5e80-8dbe-11e9-8e91-af70030b87e4.png)

[IDEDistribution.standard.log](https://github.com/ReactiveX/RxSwift/files/3283758/IDEDistribution.standard.log)
[IDEDistribution.verbose.log](https://github.com/ReactiveX/RxSwift/files/3283759/IDEDistribution.verbose.log)
[IDEDistributionPipeline.log](https://github.com/ReactiveX/RxSwift/files/3283760/IDEDistributionPipeline.log)

**Comment by freak4pc** [comment]
Hey, many of the community members release production versions with RxSwift 5 so this is probably a problem with your configuration and not the library. If you need extra assistance, slack might be a better placed for that http://slack.rxswift.org
