### ISSUE TITLE
Crash on access of MainScheduler.sharedInstance: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by gregpardo** [ReactiveX/RxSwift#201]
Edit: Using 2.0.0-beta

Not sure whats going on here but I was getting a crash on MainScheduler.sharedInstance. I put a simple line in my app delegate before any other code is loaded that was

```Swift
print(MainScheduler.sharedInstance)
```

It crashes in the init constructor of MainSchedule here with an EXC_BAD_ACCESS

```Swift
private init() {
    _mainQueue = dispatch_get_main_queue()
    super.init(serialQueue: _mainQueue)  <--- HERE
}
```

So it looks to me like the _mainQueue is not initialized because it has an instance_type of 0x0 in the debugger.

**Comment by kzaher** [comment]
Hi @gregpardo ,

This is a head scratcher :)

Hm .... between previous release and this one, we've changed

```Swift
private init() {
        super.init(serialQueue: dispatch_get_main_queue())
    }
```

to 

```Swift
    private let _mainQueue: dispatch_queue_t

    private init() {
        _mainQueue = dispatch_get_main_queue()
        super.init(serialQueue: _mainQueue)
    }
```

Can you tell me did the previous alpha.4 version work and testing environment?
* Xcode
* Integration method
* OS
* Device
 
Can you also please tell me what is the result of doing only

```Swift
print(dispatch_get_main_queue())
```

**Comment by yury** [comment]
I have created test project - https://github.com/yury/rx-issue-201
@gregpardo, can you try it? Do you get same error in it?

I put two prints - in app delegate and ViewController#viewDidLoad

**Comment by benjamincombes** [comment]
I had the same issue, with the master branch, using Xcode 7.1 beta 2 ; but updating to Xcode 7.1 beta 3 solved the issue for me.

**Comment by gregpardo** [comment]
I'll have to check my Xcode version when I get back home as per @benjamincombes's suggestion. Will keep you all updated.

**Comment by gregpardo** [comment]
Can confirm upgrading to the new 7.1 release solved the issue as well as a few other couple weird bugs I was having. I'm cool with closing this.
