### ISSUE TITLE
Move FATAL_SYNCHRONIZATION to Hooks enum

### ISSUE THREAD

**Issue by MortyMerr** [ReactiveX/RxSwift#2013]
I can see only one usage of `FATAL_SYNCHRONIZATION` compiler flag. It is not so easy to add/delete compiler flags via Cocoapods, I would prefer to have simple bool flag.
I suggest moving it to Hooks enum, where all other debug settings placed. Consistency of settings also will be improved.  And refactor `synchronizationError` like this:
```swift
        private func synchronizationError(_ message: String) {
            if Hooks.isFatalSynhronization {
                rxFatalError(message)
            } else {
                print(message)
            }
        }
```
What do you think?

**Comment by freak4pc** [comment]
It sounds interesting but I think it breaks the public interface, so it would be tricky to entirely rename it.

**Comment by MortyMerr** [comment]
I can’t find any mentions of that flag in docs. So, it looks like a hidden feature. 
I understand your concern about public interface. But simple bool flag instead of compiler flag is easier to use. Moreover this approach is already used in `Hooks` for another debugging feature. 
Is it possible to have both options for now? What do you think? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
We can _technically_ have both. But I'm not sure it should be this easy to turn this off, as it's a precaution, not really a "feature" like recording an error stack

**Comment by freak4pc** [comment]
I'm closing every issue older than 6 months. If this is still an issue for you, please comment and I can reopen :) Thanks !
