### ISSUE TITLE
RxJava: `lastOrError` in RxSwift?

### ISSUE THREAD

**Issue by Sajjon** [ReactiveX/RxSwift#2016]
**Short description of the issue**:

How can I get the same behaviour as RxJava's [`lastOrError`](https://github.com/ReactiveX/RxJava/wiki/Filtering-Observables#lastorerror)?

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
RxSwift version: `4.4.2`

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
Version 10.2.1 (10E1001)
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by isaac-weisberg** [comment]
I believe that RxSwift doesn't provide an implementation for this operator out of the box.

The closest it gets is to use the `takeLast(_:)` operator. Here, it will not convert a successfully completed observable into an erroneous one and will emit 0+ times.

You can however use the `toArray` operator and implement your erroneous state out of the resulting array and the number of elements you expected in it.

**Comment by freak4pc** [comment]
@Sajjon you can easily implement this using `materialize()` IMO.

**Comment by freak4pc** [comment]
@Sajjon I haven't tested this but I believe this should work:

```swift
extension Observable {
    func lastOrError(_ error: Swift.Error) -> Observable<Element> {
        takeLast(1).ifEmpty(switchTo: .error(error))
    }
}
```
