### ISSUE TITLE
Compiling RxSwift raises 'incompatible with weak references' error

### ISSUE THREAD

**Issue by aqjune** [ReactiveX/RxSwift#2017]
**Short description of the issue**:

Compiling RxSwift with Swift Development Snapshot 2019-06-20 Toolchain raises `'NSTextView' is incompatible with 'weak' references` error.

**Expected outcome**:

Should compile without errors

**What actually happens**:

Compilation error with the message above appears at RxCocoa/macOS/NSTextView+Rx.swift :

```
    /// Typed parent object.
    public weak private(set) var textView: NSTextView?
```

**Self contained code example that reproduces the issue**:

Build `RxCocoa` target.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift commit id 70b8a33c5c3f4c3b15ebf10b638d2b15cfafb814

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 11.0 beta 2 (11M337o)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones: Version 10.2.1 (10E1001) )
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
@aqjune Does it compile on the latest public Swift? If yes, that might be a compiler bug to file and not one in RxSwift.

**Comment by freak4pc** [comment]
It builds with no compile issues for me on Xcode 11b2 with the Swift version bundled with it. As I mentioned, we don't deal with development snapshot because they're buggy and not representing Swift or RxSwift itself. Closing for now but let me know if there's any thing else :)
