### ISSUE TITLE
The SharedSequence initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by acecilia** [ReactiveX/RxSwift#2024]
I am implementing a struct wrapper around `BehaviorRelay`. I called it `MutatingBehaviorRelay`. The main difference is that the access control level used to declare a `MutatingBehaviorRelay` is associated with the mutability of the underlying `BehaviorRelay` (yes, for MVVM).

I came this far:

```swift
import RxCocoa
import RxRelay
import RxSwift

/// `MutatingBehaviorRelay` is a wrapper for `BehaviorRelay`.
///
/// The main difference is that the access control level used to declare a `MutatingBehaviorRelay`
/// is associated with the mutability of the underlying `BehaviorRelay`
public struct MutatingBehaviorRelay<Element>: ObservableType {
    private let behaviourRelay: BehaviorRelay<Element>

    /// Accepts `event` and emits it to subscribers
    public mutating func accept(_ event: Element) {
        behaviourRelay.accept(event)
    }

    /// Current value of behavior subject
    public var value: Element {
        return behaviourRelay.value
    }

    /// Initializes behavior relay with initial value.
    public init(value: Element) {
        behaviourRelay = BehaviorRelay(value: value)
    }

    /// Subscribes observer
    public func subscribe<Observer>(
        _ observer: Observer
        ) -> Disposable where Element == Observer.Element, Observer: ObserverType {
        return behaviourRelay.subscribe(observer)
    }

    /// - returns: Canonical interface for push style sequence
    public func asObservable() -> RxSwift.Observable<Element> {
        return behaviourRelay.asObservable()
    }
}

/// An extension providing `Driver` related functions
extension MutatingBehaviorRelay {
    /// Converts `MutatingBehaviorRelay` to `Driver`.
    ///
    /// - returns: Observable sequence.
    public func asDriver() -> Driver<Element> {
        let source = self.behaviourRelay.asObservable()
            .observeOn(DriverSharingStrategy.scheduler)
        return SharedSequence(source) // Error: 'SharedSequence<SharingStrategy, Element>' initializer is inaccessible due to 'internal' protection level
    }
}
```

I found a problem when converting the `MutatingBehaviorRelay` to a `Driver`. I want to keep the underlying `behaviorRelay` private (I can not do `return behaviourRelay.driver()`), so I followed the implementation in [here](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Traits/Driver/BehaviorRelay+Driver.swift). The problem is that the initializer of `SharedSequence` is internal, so the code does not compile.

What is the proper way to work around this? Make the initializer public? Follow a different approach?

Thanks,
Andres

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.1

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 10.2.1 (10E1001)
```

**Installation method**:
  - [ ] CocoaPods
  - [X] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [X] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey @acecilia - I think that there was some discussion around this around here and there was some preference not to expose this sort of internal initializer because it only serves a very small percentage of the "population". I'm not entirely sure of the full reasoning as it was a long time ago, but we can re-open for discussion with @kzaher and others.

PS I don't think the name of your object is necessarily correct. the object isn't mutable per-se because it doesn't have "a value", it has a stream of values going through it.

**Comment by acecilia** [comment]
@freak4pc thanks for your answer. Yes, I am not 100% happy with the name yet, it was the first thing that came to my mind when putting it down ;P. If you have a better idea for it let me know!

**Comment by freak4pc** [comment]
Second downside of a `var` based object is that you could replace *the entire* relay, breaking any ongoing subscribers. Just seems like a lot of holes using it this way (IMO). Mutability has dangerous paths that require more thinking and API Design.

**Comment by acecilia** [comment]
You are 100% right. That is another downside of this approach that I am not happy with. Still thinking about how to do this. Declaring the relay as `private(set) var` will limit the possibilities of replacing the entire relay, but does not solve the problem completely.

My goal with this is to do something that has been already discussed in RxSwift before: 
- Provide an `accept()` method that can only be reached from inside the class owning the `BehaviorRelay`.
- Make sure that the relay can not be replaced (what you are commenting).
- Do all this without boilerplate code, preferably with a one line declaration.

Seems like coming to a solution that satisfies those three points is not that easy.

**Comment by freak4pc** [comment]
I think this would be outside the scope of RxSwift unfortunately. I suggest moving this discussion to our Slack, since it's not really something wrong with the library itself. Closing this for now but let me know if you feel this should be reopened.

**Comment by acecilia** [comment]
If you think that the internal protection level in the `SharedSequence` init is ok, then its fine to close it. Thanks!
