### ISSUE TITLE
Fatal error: Binding error to behavior relay: objectDeleted: file

### ISSUE THREAD

**Issue by mukeshlokare** [ReactiveX/RxSwift#2025]
I am facing issue on,
Xcode 10.2.1
macOS Mojave 10.14 .5

Fatal error: Binding error to behavior relay: objectDeleted: file /Users/webwerks/Desktop/Monster/iOS/monstar_mukesh/project_name/Pods/RxCocoa/RxCocoa/Common/Observable+Bind.swift, line 90
2019-07-04 15:42:33.074374+0530 target_name[2731:1953909] Fatal error: Binding error to behavior relay: objectDeleted: file

*Note*
For macOS High Sierra 10.13.6
Xcode 10.1
There was not any issue & crash on existing code.
![Screenshot 2019-07-04 at 3 55 24 PM](https://user-images.githubusercontent.com/29204561/60659933-39862b80-9e74-11e9-9daa-99f5c5a152c9.png)

**Comment by freak4pc** [comment]
Please follow the issue template and provide additional code (preferably, reproducible). Otherwise we won't be able top help as this doesn't seem like an issue inside RxSwift.

**Comment by mukeshlokare** [comment]
Hey, Thanks for reply Can I connect you on skype. I can't share the source code.

**Comment by freak4pc** [comment]
No, sorry, we don't provide private tech support for people :)

If this is an issue with the framework itself that you can reproduce, please open a new issue with code. If you have a specific issue with your own code base, it's better to use Slack or other support channels (http://slack.rxswift.org).

**Comment by mukeshlokare** [comment]
What I suspect is,

```
private func logoutAction() -> CocoaAction {
    return CocoaAction { [weak self] in
      guard let `self` = self else { return .empty() }
      
      let subject = PublishSubject<Void>()
      
      func changeRootView() {
        let authScene = AuthScene.signin(coordinator: self.sceneCoordinator)
        self.sceneCoordinator.transition(to: authScene, type: .root(animationType: .present))
          .asObservable()
          .mapTo(())
          .bind(to: subject)
          .disposed(by: self.disposeBag)
      }
      
      self.logoutRequestAction.execute(())
        .subscribe { changeRootView() }
        .disposed(by: self.disposeBag)
      
      subject
        .subscribe{
          APITokenManager.shared.removeToken()
          RealmDBManager.shared.deleteAllData()
          OneSignalManager.shared.unsubscribe()
        }
        .disposed(by: self.disposeBag)
      
      return subject
    }
  }
```

& Following change has fixed my issue,

```

private func logoutAction() -> CocoaAction {
    return CocoaAction { [weak self] in
      guard let `self` = self else { return .empty() }
      
      let subject = PublishSubject<Void>()
      
      func changeRootView() {
        let authScene = AuthScene.signin(coordinator: self.sceneCoordinator)
        self.sceneCoordinator.transition(to: authScene, type: .root(animationType: .present))
          .asObservable()
          .mapTo(())
          .bind(to: subject)
          .disposed(by: self.disposeBag)
      }
      
      self.logoutRequestAction.execute(())
        .subscribe { changeRootView() }
        .disposed(by: self.disposeBag)
      
      subject
        .subscribe( onNext: { _ in
          APITokenManager.shared.removeToken()
          RealmDBManager.shared.deleteAllData()
          OneSignalManager.shared.unsubscribe()
        })
        .disposed(by: self.disposeBag)
      
      return subject
    }
  }
```

Thanks for suggestion 👍
