### ISSUE TITLE
I got a similar problem.

### ISSUE THREAD

**Issue by BoxDengJZ** [ReactiveX/RxSwift#2029]
I got a similar problem.

```
dyld: Library not loaded: @rpath/RxRelay.framework/RxRelay
  Referenced from: /Users/***/Library/Developer/Xcode/DerivedData/***/Build/Products/***/Model.framework/Model
  Reason: image not found
```

_Originally posted by @mironal in https://github.com/ReactiveX/RxSwift/issues/1965#issuecomment-489894192_

**Comment by freak4pc** [comment]
Please look at the other comments there, you're probably not importing RxRelay - It's now a separate dependency and you'll need it to use RxCocoa.
