### ISSUE TITLE
DelegateProxy bug

### ISSUE THREAD

**Issue by DanboDuan** [ReactiveX/RxSwift#2035]
**Short description of the issue**:

There is a bug in RxCocoa when UIScrollView's delegate is swizzled

**Expected outcome**:

  UIScrollView.rx.delegate or   UIScrollView.rx.setDelegate should work

**What actually happens**:
 if I hook the delegate, the RxCocoa works wrong

**Self contained code example that reproduces the issue**:

The `BDWebViewDecorator` is subclass of NSProxy to decorate the delegate.

```Objective-C
// sample codes, not all, the Decorator will forward all methods calling except bd_isCollectionViewTrackerDecorator  to the target
@implementation BDCollectionViewDelegateDecorator

- (BOOL)respondsToSelector:(SEL)aSelector {
    if (aSelector == @selector(bd_isCollectionViewTrackerDecorator)) {
        return YES;
    }

    return [self.target respondsToSelector:aSelector];
}

@end

// setXXXDelegate: and setDelegate: are swizzled
- (void)setXXXDelegate:(id)delegate {
    if (delegate == nil) {
        [self setXXXDelegate:delegate];
    }
    // once is ok
    if ([delegate respondsToSelector:@selector(bd_isCollectionViewTrackerDecorator)]) {
         [self setXXXDelegate:delegate]; 
         return;
    }
    BDWebViewDecorator *proxy = [[BDWebViewDecorator alloc] initWithTarget:delegate];
    [self setXXXDelegate:proxy];
    //  setWebViewDelegate first then hold proxy
    self.bd_TrackerDecorator = proxy;
}
```

RxCocoa works wrong here

```Swift
public static func proxy(for object: ParentObject) -> Self {
        let maybeProxy = self.assignedProxy(for: object)
        let proxy: AnyObject
        if let existingProxy = maybeProxy {
            proxy = existingProxy
        } else {
            proxy = castOrFatalError(self.createProxy(for: object))
            self.assignProxy(proxy, toObject: object)
            assert(self.assignedProxy(for: object) === proxy)
        }
        let currentDelegate = self._currentDelegate(for: object)
        let delegateProxy: Self = castOrFatalError(proxy)

        if currentDelegate !== delegateProxy {
            delegateProxy._setForwardToDelegate(currentDelegate, retainDelegate: false)
            assert(delegateProxy._forwardToDelegate() === currentDelegate)
            self._setCurrentDelegate(proxy, to: object)
            assert(self._currentDelegate(for: object) === proxy)
            assert(delegateProxy._forwardToDelegate() === currentDelegate)
        }

        return delegateProxy
    }
```

1. first `assert(self._currentDelegate(for: object) === proxy)` is not always True

The self._currentDelegate(for: object) should be the decorator, it will work fine

2. second, the setDelegate will call proxy() once and then delegate will call another time

this will cause delegateProxy's forwardToDelegate points to the decorator. 

the decorator's target is the delegateProxy which leads to bad loop of delegateProxy's responds method calling decorator's respondsToSelector method, and  decorator's respondsToSelector method calling delegateProxy's responds method.

**Comment by DanboDuan** [comment]
sample project here https://github.com/DanboDuan/SwiftDemo

**Comment by freak4pc** [comment]
I'm closing every issue older than 6 months. If this is still an issue for you, please comment and I can reopen :) Thanks !
