### ISSUE TITLE
SharingScheduler.mock(scheduler:action:) does not work

### ISSUE THREAD

**Issue by sochalewski** [ReactiveX/RxSwift#2040]
**Short description of the issue**:

`SharingScheduler.mock(scheduler:action:)` does not override scheduler to a given, mock scheduler.

**Expected outcome**:

Observables that use main schedulers are testable with `TestScheduler` and `SharingScheduler.mock(scheduler:action:)`.

**What actually happens**:

`TestableObserver` does not record events.

**Self contained code example that reproduces the issue**:

```swift
// A class with an example of observable that uses main scheduler to work.
class Rx {
    private(set) lazy var observable: Observable<Int> = {
        return Observable<Int>
            .interval(.milliseconds(50), scheduler: MainScheduler.instance)
            .takeWhile { $0 <= 100 }
    }()
}

// A class test.
class RxTestSharingSchedulerMockTests: XCTestCase {

    private var sut: Rx!
    private var testScheduler: TestScheduler!
    private var disposeBag: DisposeBag!

    override func setUp() {
        sut = Rx()
        testScheduler = TestScheduler(initialClock: 0)
        disposeBag = DisposeBag()
    }

    override func tearDown() {
        sut = nil
        testScheduler = nil
        disposeBag = nil
    }

    // This does not work and does not record elements.
    func testRxTestSharingSchedulerMock() {
        SharingScheduler.mock(scheduler: testScheduler) {
            let observer = testScheduler.createObserver(Int.self)
            sut.observable.bind(to: observer).disposed(by: disposeBag)

            testScheduler.start()
            testScheduler.advanceTo(10000)

            XCTAssertEqual(observer.events.compactMap { $0.value.element }, (0...100).compactMap { $0 }) // events is empty
        }
    }

    // This does work and values contains consecutive numbers.
    func testRxTestBlocking() {
        let values = try! sut.observable.take(10).toBlocking().toArray()
        XCTAssertEqual(values, (0...9).compactMap { $0 })
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.2.1 and 10.3
```

**Installation method**:
  - [x] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

It does not work with Carthage, but I've created a sample clear project to check it out with CocoaPods and it does not work too.

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
SharingScheduler is for testing SharedSequences such as Driver and Signal - I don’t see you using any of these here.

**Comment by sochalewski** [comment]
You're right, I overlooked this. Thank you for your assistance!
