### ISSUE TITLE
Couldn't IRGen expression, no additional error

### ISSUE THREAD

**Issue by anamarta86** [ReactiveX/RxSwift#2046]
With 5.0.1 version when use `po` on debug console I get this error `Couldn't IRGen expression, no additional error`. On 5.0.0 this doesn't happen.

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

10.3

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ x] yes (9.3.1 and 10.3)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey there. Seems to me this is a bug for the Swift/Debug Tooling team and not this project. I’d open a reproducible sample on https://bugs.swift.org. 

With Carthage, 5.0.0 is a static library and 5.0.1 is a dynamic library. There’s no other difference (for SPM and CocoaPods there should be no difference).

**Comment by anamarta86** [comment]
thanks for your help
