### ISSUE TITLE
flatMap: Cannot convert return expression of type 'Observable<_.Element>' to return type 'Observable<String>'

### ISSUE THREAD

**Issue by g-enius** [ReactiveX/RxSwift#2047]
**Short description of the issue**:

 Swift  Compiler will complain if I leave return type implicitly inferred. But it works fine for map.

**Expected outcome**:

flapMap should be compiled same as map if return type is empty.

**What actually happens**:

Doesn't compile

**Self contained code example that reproduces the issue**:

```swift
      var test: Observable<String> {
        let a = Observable.from([1, 2, 3])
        return a.flatMap { _ in   //Cannot convert return expression of type 'Observable<_.Element>' to return type 'Observable<String>'
            print("")
            return Observable.just("")
        }
    }

However, it works if:
1) I change it to map or
2) add the return type explicitly.
3) only return one line of code (by deleting print(""))

**Comment by freak4pc** [comment]
Hey, please file a bug with the Swift Compiler team (https://bugs.rxswift.org). This isn’t related to RxSwift itself.
