### ISSUE TITLE
RxCocoa 5.0.1 not available via Cocoapods

### ISSUE THREAD

**Issue by netbe** [ReactiveX/RxSwift#2049]
**Short description of the issue**:

5.0.1 version is not available in Cocoapods.

**Expected outcome**:

Should be able to install via Cocoapods

**What actually happens**:

```
 pod install --repo-update
[!] CocoaPods could not find compatible versions for pod "RxCocoa":
  In Podfile:
    RxCocoa (= 5.0.1)

None of your spec sources contain a spec satisfying the dependency: `RxCocoa (= 5.0.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**Comment by freak4pc** [comment]
5.0.1 solves a Carthage-specific issue.

5.0.0 and 5.0.1 are identical as far as CocoaPods, SPM and Submodule integrations are concerned.
