### ISSUE TITLE
Cocoapods 5.0.1 release

### ISSUE THREAD

**Issue by gringoireDM** [ReactiveX/RxSwift#2052]
Not really an issue, but I see that the version 5.0.1 is not yet released to cocoapods. Any ETA on when this is going to be released? Thank you so much for your work

**Comment by freak4pc** [comment]
5.0.1 is a Carthage only release. There are no code changes between 5.0.0 and 5.0.1.

**Comment by gringoireDM** [comment]
I'm sorry. I believed that 5.0.1 was adding https://github.com/ReactiveX/RxSwift/pull/1978

**Comment by freak4pc** [comment]
Fair point, we should probably release a 5.1.0 with some additions soon, let's wait a bit to see if we can accumulate any other PRs/changes.
