### ISSUE TITLE
CombineLatest don't take the latest values after retry

### ISSUE THREAD

**Issue by g-enius** [ReactiveX/RxSwift#2053]
**Short description of the issue**:

CombineLatest/Zip/WithLatestFrom don't take the latest values after retry. I have to add the below commented out extra logics to make it dynamically calculated which looks very bizarre.

**Expected outcome**:
After retry, I would expect all the income observables will be re-calculated.
 

**What actually happens**:

The values of the input observables are cached. After re-subscribed, func foo still emits old value rather than re-calculating it.

**Self contained code example that reproduces the issue**:

```swift
func foo() -> Observable<Double> {
    return Observable.just(Date.timeIntervalSinceReferenceDate).debug()
//        .flatMap{ _ in
//            //can't just return Observable.just($0), as it will always return cached value
//            return Observable.just(Date.timeIntervalSinceReferenceDate)
//        }.debug()
}

let subject = PublishSubject<String>()
let disposeBag = DisposeBag()

Observable.combineLatest(subject, foo()) { return ($0, $1) }
    .retry(2)
    .subscribe(onNext: { print($0, $1) })
    .disposed(by: disposeBag)

enum errorEnum: Error {
    case unknow
}

subject.onError(errorEnum.unknow)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift 5.0

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%

**Xcode version**:

```
  10.3
```

**Comment by g-enius** [comment]
To be more clearly,
The current workaround is:
func foo() -> Observable<Double> {
    return Observable.just(Date.timeIntervalSinceReferenceDate).debug()
        .flatMap{ _ in
            //can't just return Observable.just($0), as it will always return cached value
            return Observable.just(Date.timeIntervalSinceReferenceDate)
        }.debug()
}

**Comment by kzaher** [comment]
> The values of the input observables are cached. After re-subscribed, func foo still emits old value rather than re-calculating it.

The code is behaving exactly like as designed.

Observable.just means always return this value. It doesn't matter that `Date.timeIntervalSinceReferenceDate` depends on time. `Just` operator can't know this fact.

If you want for the `Observable.just` value to be calculated on subscription use `deferred`.

```swift
   Observable.deferred { Observable.just(Date.timeIntervalSinceReferenceDate) }
```

**Comment by g-enius** [comment]
Thanks, @kzaher for your prompt reply and providing a working solution.

I was thinking it was because of CombineLatest, as when I simply subscribed Observable.just multiple times, like below codes. It did return the latest values. Thus, I believed it would work the same if it got re-subscribes after retry, but it turned out not. So I blamed CombineLatest which cached the old value.

```swift
func foo() -> Observable<Double> {
    return Observable.just(Date.timeIntervalSinceReferenceDate).debug()
}

let disposeBag = DisposeBag()

foo().subscribe(onNext: { print($0)}).disposed(by: disposeBag)
foo().subscribe(onNext: { print($0)}).disposed(by: disposeBag)
