### ISSUE TITLE
Is there any plan on supporting that transformations on PublishRelay/BehaviourRelay return also PublishRelay/BehaviourRelay?

### ISSUE THREAD

**Issue by acecilia** [ReactiveX/RxSwift#2058]
Hello:

**Short description of the issue**:

When transforming `PublishRelay`/`BehaviourRelay` the return type is `Observable` instead of `PublishRelay`/`BehaviourRelay`.

In the following code:

```swift
struct State {
    let property1: Int
    let property2: String
}
let publishRelay = PublishRelay<State>()
let mappedPublishRelay = publishRelay.map { $0.property1 }
```

**Expectation:** 

`mappedPublishRelay` is of type `PublishRelay<Int>`

**Reality:** 

`mappedPublishRelay` is of type `Observable<Int>`
  
**Precedents**:

When transforming a `Driver`, the returning type is also `Driver`, and not `Observable`.
When transforming a `Signal`, the returning type is also `Signal`, and not `Observable`.

**Discussion**:

Is there any plan on supporting that transformations on `PublishRelay`/`BehaviourRelay` return also `PublishRelay`/`BehaviourRelay`?

Some related issues:
- https://github.com/ReactiveX/RxSwift/issues/1182
- https://github.com/ReactiveX/RxSwift/issues/1272

Thanks!

**Comment by acecilia** [comment]
@freak4pc @kzaher your feedback/thoughts will be very much appreciated :)

**Comment by freak4pc** [comment]
Unlikely. A subject isn’t comparable to a SharedSequence (Driver/Signal).

If you look at Combine, for example, using operators on a subject also yields a Publisher and not another Subject.
