### ISSUE TITLE
FR: Scan into for SharedSequence / Driver

### ISSUE THREAD

**Issue by AlexisQapa** [ReactiveX/RxSwift#2059]
**Short description of the issue**:

The is no scan operator with into parameter for SharedSequence / Driver.
There was an issue / discussion to add it Observable here: https://github.com/ReactiveX/RxSwift/issues/1667 and it was accepted.
Is there a reason it is not available for SharedSequence ?

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
5.0.1

**Platform/Environment**
  - [X] iOS

**Xcode version**:

```
10.2 / 11 beta 7
```

**Installation method**:
  - [X] Carthage
  - [X] SPM

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X] yes 10.2 / 11 beta 7

**Level of RxSwift knowledge**:
  - [X] I have a significant code base

**Comment by freak4pc** [comment]
Hey Alexis - I'm not sure this operator makes much sense for these types. In general many Observable operators don't necessarily make sense in the contexts of other traits.

SharedSequence would be the piece you usually expose to the consumer at the end of a chain, not something you typically further manipulate in the way you describe here above. 

My personal instinct is that it's not a significant enough use-case to add to the code-base.

**Comment by AlexisQapa** [comment]
I often have ControlEvents combining into drivers and this kind of operator avoid converting to observable then converting back to driver losing the "can't fail" trait thought I understand your position.
