### ISSUE TITLE
CFBundleVersion must be only three period-separated integers

### ISSUE THREAD

**Issue by seboslaw** [ReactiveX/RxSwift#206]
Could not submit with 2.0.0-beta1 and XCode 7.1 because of this issue: http://stackoverflow.com/questions/25418798/cfbundleversion-must-be-a-period-separated-list-of-at-most-three-non-negative-in

**Comment by orta** [comment]
I'd recommend running something like this: https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150139578

This will probably end up getting fixed upsteam in tools. Though I guess for frameworks the bundle ID would have to be the int only versions.

**Comment by jerolimov** [comment]
Here is my Podfile `post_install` hack (based on @orta's comment in https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150139578, thanks for that!) which just removes the beta suffix:

```ruby
post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        original_version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        changed_version = original_version[/(\d+\.){1,2}(\d+)?/]
        unless original_version == changed_version
            puts "Fix version of Pod #{target}: #{original_version} => #{changed_version}"
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{changed_version}" "Pods/Target Support Files/#{target}/Info.plist"`
        end
    end
end
```

**Comment by kzaher** [comment]
2.0.0 version has been released :)
