### ISSUE TITLE
Xcode 11 + SPM: "No such module 'RxSwift'"

### ISSUE THREAD

**Issue by RamblinWreck77** [ReactiveX/RxSwift#2063]
Steps to reproduce:

-Make new project w/view controller

-Add https://github.com/ReactiveX/RxSwift/ via File/Swift Packages/Add Package Dependency

-add import RxSwift to view controller

-Build will fail with "no such module"

Things I've tried:

✅ Clean build/nuke derived data

✅ RxSwift is included in Frameworks, Libraries, and Embedded Content for the specified target

I could just be a moron and be missing something obvious, but I thought I'd share here in case anyone else runs into this issue!

**Comment by RamblinWreck77** [comment]
Relevant thread seemingly having similar issues:

https://forums.developer.apple.com/thread/119327

**Comment by RamblinWreck77** [comment]
Oh wow, it appears SwiftPM has hard coded "Release/Debug" configuration names?! What?!

https://stackoverflow.com/questions/57165778/getting-no-such-module-error-when-importing-a-swift-package-manager-dependency

**Comment by freak4pc** [comment]
I just created a blank project and had no issues.

![image](https://user-images.githubusercontent.com/605076/64879426-f68ac600-d623-11e9-9bb3-289cd6547780.png)

![image](https://user-images.githubusercontent.com/605076/64879433-f985b680-d623-11e9-94e2-141a854b8464.png)

![image](https://user-images.githubusercontent.com/605076/64879444-fdb1d400-d623-11e9-9e71-881752b5176e.png)

**Comment by freak4pc** [comment]
@RamblinWreck77 If this is specific to SPM / Your project - we should probably close this. Let me know :)

**Comment by RamblinWreck77** [comment]
I'll go ahead and close this, the cause was having a build configuration that was custom, and not Debug/Release.

Hopefully this post helps anyone else who has this problem.

**Comment by DenTelezhkin** [comment]
/shrug https://bugs.swift.org/browse/SR-11328

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
