### ISSUE TITLE
Publish RxCocoa pod 5.0.1 to Specs

### ISSUE THREAD

**Issue by adamhowardprice** [ReactiveX/RxSwift#2065]
The latest RxCocoa version in [Cocoapods Specs](https://github.com/CocoaPods/Specs/tree/master/Specs/3/c/1/RxCocoa) is 5.0.0, but the latest version here is 5.0.1.

I need 5.0.1 for upgrading to Xcode 11 GM.

**Comment by freak4pc** [comment]
5.0.0 is the latest version. 5.0.1 is a Carthage-only release with no code changes.

**Comment by adamhowardprice** [comment]
Thanks

**Comment by adamhowardprice** [comment]
It looks like 5.0.0 was built with Swift 5.0.1. Will there be a new release built with Swift 5.1?

![image](https://user-images.githubusercontent.com/602596/64891969-4035d980-d641-11e9-9992-a1d5165150c5.png)

**Comment by freak4pc** [comment]
You said you’re using CocoaPods so there shouldn’t be any issue. Just clean and. Hold again.
