### ISSUE TITLE
CollectionView rebind problem

### ISSUE THREAD

**Issue by healmax** [ReactiveX/RxSwift#2066]
**Short description of the issue**:

Hi, I modify the last sample name "GitHub Search Repositories", i use willDisplayCell way to trigger  load next page and it's work
```
let loadNextPageTrigger: (Driver<GitHubSearchRepositoriesState>) -> Signal<GitHubCommand> =  { state in
            return state.flatMapLatest { [unowned self] state in
                guard !state.shouldLoadNextPage else {
                    return Signal.empty()
                }
                
                return self.collectionView.rx.willDisplayCell
                    .asSignal()
                    .filter({ (cell, indexPath)  in
                        indexPath.row == state.repositories.value.count - 10
                    })
                    .map { _ in return Signal.just(())}
            }
        }
```
But when i change tableView to CollectionView, trigger load next page,  the collectionView become empty. I am sure that has value when load next page. 

**Self contained code example that reproduces the issue**:
Sample, minimal project: https://github.com/healmax/RxSwiftCollectionViewLoadNextPage

**Comment by freak4pc** [comment]
I'm closing every issue older than 6 months. If this is still an issue for you, please comment and I can reopen :) Thanks !
