### ISSUE TITLE
Return Observer.create Not returning and code next to it not working.

### ISSUE THREAD

**Issue by asn111** [ReactiveX/RxSwift#2084]
**Short description of the issue**:

  Well i am pretty much new to reactive programming. problem is, I have a function(A) which returns an object , now I have another function(B) which subscribes returning object from function A and I make function B also as returning an other object in that subscribe, now this whole return this is not work. I have no idea why is happening.
Any help would be appreciated. Thanks
**Expected outcome**:

  return Object

**What actually happens**:

 code in return Observer.create not going further.

**Self contained code example that reproduces the issue**:
**Function A**
```
func getClassById(classId: Int) -> Observable<AssignedClassModel> {
        return Observable.create{[weak self] observer -> Disposable in
            //TestDebug.debugInfo(fileName: self!.TAG, message: self!.baseUrl)
            Alamofire.request("https://pickupappapi.azurewebsites.net/api/Students/GetStudentsByClass?classId=\(classId)", method:.get, parameters: nil, encoding: JSONEncoding.default, headers: self!.getRequestHeader())
                .validate()
                .responseJSON{ response in
                    switch response.result {
                    
                        do {
                            let assingnedClass = try JSONDecoder().decode(AssignedClassModel.self, from: data)
                            observer.onNext(assingnedClass)
                        } catch {
                            observer.onError(error)
                            TestDebug.debugInfo(fileName: self!.TAG, message: "Error on observer.onError - \(error)")
                        }
                    case .failure(let error):
                        observer.onError(error)
                        TestDebug.debugInfo(fileName: self!.TAG, message: "Error on observer.onError failure - \(error)")
                    }
            }
            return Disposables.create()
        }
    }
```

**Function B**

```
func getAssignedClassData(classId: Int) -> Observable<[StudentModel]>  { 
        return Observable.create{[weak self] observer -> Disposable in // from here code is not going further.
        APIService.singelton
            .getClassById(classId: classId)
            .asObservable()
            .subscribe(onNext: { [weak self] assingnedClass in
                let studentsData = Array(Database.singleton.fetchStudents(byCLassId: classId))
                print(studentsData)
                observer.onNext(studentsData)
                }, onError: { error in
                    print(error)
            }).disposed(by: self!.disposeBag)
            return Disposables.create()
            }
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  latest version as of this date

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
10.2.1
```

**Installation method**:
  - [ ] CocoaPods

**Level of RxSwift knowledge**:

  - [ ] just starting

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by asn111** [comment]
> Hi,
> 
> this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
> Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.
> 
> We are asking this because:
> 
> * we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
> * all who are interested in development of this project and watching it are being spammed by irrelevant information.
> * those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.
> 
> Thank you for understanding.

OKAY.
