### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by nhatlee** [ReactiveX/RxSwift#2086]
**Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler**:

I upgrade my project to `Swift5.1` using `Xcode11.1`. But after run `carthage update RxSwift --no-use-binaries --platform iOS` or `carthage update RxSwift --platform iOS`.  I always get the error: 
`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: ...`
Please help.

**Expected outcome**:

Can build project on `Xcode 11.1`

**What actually happens**:

Cannot build project because `import RxSwift` error 
**Platform/Environment**
  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
Xcode 11.1
```

**Installation method**:
  - [x] Carthage

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
I had switch to newest Xcode version by command `sudo xcode-select -s /Applications/Xcode11.1.app`

<img width="669" alt="Screen Shot 2019-10-09 at 16 04 01" src="https://user-images.githubusercontent.com/7148482/66467331-7df61880-eaae-11e9-92d8-e7c6780e0745.png">

**Comment by simba909** [comment]
We also faced this issue, and for us it helped to completely remove the `Carthage` directory and then rebuild all dependencies.

**Comment by LucianoPAlmeida** [comment]
If you are using the `--no-use-binaries` option it shouldn't have this error because carthage will build with the compiler in your machine. If you have more than one xcode in your machine, just make sure the `xcode-select`ed Xcode is the same you are building the app, because carthage you build using command line tools using the `xcode-selecte`ed version. If that doesn't help @simba909 option should work :))

**Comment by freak4pc** [comment]
Great answers by both here, Thanks @simba909 and @LucianoPAlmeida. This is a Carthage thing and not a RxSwift thing, please direct these kind of questions to our Community Slack (http://slack.rxswift.org) next time, as we try keeping Issues in this repo contained to bugs/issues in the project itself. 

Thanks!
