### ISSUE TITLE
Release 5.0.1 for Cocoapods

### ISSUE THREAD

**Issue by mariohahn** [ReactiveX/RxSwift#2092]
Hi,

I saw you already fixed the catalyst bug and already merged it to master, but you haven't uploaded a new version to CocoaPods.

I know I can link to the master branch but I think it would be much better to just release a new version.

Thanks (:

**Comment by freak4pc** [comment]
5.0.1 has no code changes from 5.0.0. it's a Carthage-only release.
The fix you're referring to will be released in 6.0.0 which is still not out. For now the only option would be direct-to-master/develop, until a version is released.
