### ISSUE TITLE
UITableViewAlertForLayoutOutsideViewHierarchy warning? when to fix?

### ISSUE THREAD

**Issue by nizenyang** [ReactiveX/RxSwift#2093]
https://github.com/ReactiveX/RxSwift/blob/6b2a406b928cc7970874dcaed0ab18e7265e41ef/RxCocoa/Common/DelegateProxyType.swift#L329

**Comment by benjaminths** [comment]
Any news ?

**Comment by freak4pc** [comment]
I believe this was fixed in #2090
