### ISSUE TITLE
Cannot create RxSwift project using Package.swift: error: cyclic dependency declaration found

### ISSUE THREAD

**Issue by nlykkei** [ReactiveX/RxSwift#2100]
I get the following error, when trying to setup RxSwift using the Package.swift installation file:
```
nlykkei-mbp:rxswift nlykkei$ swift build
error: cyclic dependency declaration found: RxTestProject -> RxTestProject
```

How can I fix this? Everything works using CocoaPods.

```
nlykkei-mbp:rxswift nlykkei$ cat Package.swift 
// swift-tools-version:5.0

import PackageDescription

let package = Package(
  name: "RxTestProject",
  dependencies: [
    .package(url: "https://github.com/ReactiveX/RxSwift.git", from: "5.0.0")
  ],
  targets: [
    .target(name: "RxTestProject", dependencies: ["RxSwift", "RxCocoa"])
  ]
)
```

**Comment by pomozoff** [comment]
Same here. Here is [the project](https://github.com/pomozoff/TextViewRxSwift) with this bug.
<img width="1498" alt="Screenshot 2019-11-05 at 20 32 15" src="https://user-images.githubusercontent.com/839094/68231186-9c96f300-000b-11ea-8077-cde9bdbeaf2a.png">

**Comment by fantastichut** [comment]
Same here. Happens at ReplaySubject<Int>.create(bufferSize: 1) with error:
GenericCache(0x7fff89cff138): cyclic metadata dependency detected, aborting

**Comment by fantastichut** [comment]
duplicates #2094

**Comment by freak4pc** [comment]
SPM is plagued with bugs that we simply cannot solve unfortunately. Please see the comment here and rest of the discussions: https://github.com/ReactiveX/RxSwift/issues/2127#issuecomment-643647705
