### ISSUE TITLE
Immediate / crash when installing via SwiftPM, works in Cocaopods

### ISSUE THREAD

**Issue by chrislconover** [ReactiveX/RxSwift#2101]
**Short description of the issue**:

Immediate crash in trivial usage when using RxSwift via SwiftPM

Sample project demonstrates problem.  Verified on third party machine.
https://github.com/chrislconover/RxSwiftDeallocObservableCrash

**Expected outcome**:

Should not crash

**What actually happens**:

Crashes in DeallocObservable from first call to add a tap handler (`tap`)

**Self contained code example that reproduces the issue**:

https://github.com/chrislconover/RxSwiftDeallocObservableCrash

This *trivial* sample project contains two branches.  The `master` branch uses SwiftPM and crashes on launch (you can use the simulator).  The second branch - `with_cocoapods` does not crash.

```swift

    func configure() {
        translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(tapView)
        tapView.widthAnchor.constraint(equalToConstant: 100).isActive = true
        tapView.heightAnchor.constraint(equalToConstant: 100).isActive = true
        tapView.centerXAnchor.constraint(equalTo: centerXAnchor).isActive = true
        tapView.centerYAnchor.constraint(equalTo: centerYAnchor).isActive = true

        tapView.rx.tap  // <- blows up here
            .subscribe(onNext: {
                print("weird")
            })
            //            .bind { [unowned self] in self.onNext() }
            .disposed(by: disposeBag)
    }

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
Current: 5.0.1

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro: https://github.com/chrislconover/RxSwiftDeallocObservableCrash
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  11.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ x] CocoaPods
  - [ x] SwiftPM
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ x] I have a significant code base (but trivial sample project)

**Comment by freak4pc** [comment]
See #2094
