### ISSUE TITLE
How to subscribe numberOfRows change when use RxTableViewRealmDataSource

### ISSUE THREAD

**Issue by hhl1809** [ReactiveX/RxSwift#2105]
Hi everyone, Im using RxTableViewRealmDataSource and wanna check if numberOfRows == 0 then I will do something with my tablview, like display Empty Data view or something. How can I do that ? I researched but useless. Can anyone help ?

**Comment by freak4pc** [comment]
Please open an issue in the project’s page or join the slack channel. This GitHub is for issues with RxSwift only. Thanks !
