### ISSUE TITLE
RxCocoa inhibits deploying Mac Catalyst

### ISSUE THREAD

**Issue by anonrig** [ReactiveX/RxSwift#2108]
**Short description of the issue**:

I'm getting an error with the following message on Mac Catalyst build using RxCocoa:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIWebView", referenced from:
      objc-class-ref in RxCocoa.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected outcome**:

Excepted outcome would be an acceptable build.
**Self contained code example that reproduces the issue**:

```swift
import RxCocoa
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  Latest version

**Platform/Environment**

  - [ x] iOS
  - [x ] macOS
  - [ x] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
latest
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ x] SPM

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x ] I have a significant code base

**Comment by kevinmbeaulieu** [comment]
I believe this was already fixed in https://github.com/ReactiveX/RxSwift/pull/2012, there just hasn't been a release yet since that was merged

**Comment by freak4pc** [comment]
Indeed, this was already fixed. For now, you can target `develop` directly. We plan on releasing 6.0.0-beta.1 soon which will include this fix. Thanks !
