### ISSUE TITLE
Why there is no ReplayRelay?

### ISSUE THREAD

**Issue by evgeny-sureev** [ReactiveX/RxSwift#2109]
Of course we can define `EXPANDABLE_SHARED_SEQUENCE` and create such Relay, but I think it is more convenient to have it in framework.

I can make a PR with ReplayRelay, as I am using it in my projects.

**Comment by winstondu** [comment]
Seconded. Please do

**Comment by lordzsolt** [comment]
Wondering about this also.

**Comment by freak4pc** [comment]
This is currently in progress in #2111. Closing.
