### ISSUE TITLE
How to Update specific index of Behaviour Relay  in Section Array

### ISSUE THREAD

**Issue by ProKashif** [ReactiveX/RxSwift#2115]
I was trying to update the index like this

` var arrayOfSectionModels = sections.value
        arrayOfSectionModels[section].items[row] = data
        sections.accept(arrayOfSectionModels)`

but it causes flickering (blinking) effects. I think this refreshes the whole tableView not a specific index. here is my Array

`var sections = BehaviorRelay<[SectionModel<String, FeedSections>]>(value: [])`

**Comment by freak4pc** [comment]
Hey, this doesn’t seem to be an issue with the project. Please direct these sort of questions to our Slack channel so the community can help you. 

Thanks for understanding ! ;)
