### ISSUE TITLE
failed to demangle superclass of FlatMapSink from mangled name '*'

### ISSUE THREAD

**Issue by SocialTermite** [ReactiveX/RxSwift#2118]
**Short description of the issue**:

  When I run my unit tests "failed to demangle superclass of MergeSink from mangled name" error appear with crash. It can be other than MergeSink class. 

`-all_load` tried.

**Expected outcome**:

  Work without crash

**What actually happens**:

When I start unit tests in my main project RxSwift always crash with errors:
`failed to demangle superclass of FlatMapSink from mangled name '\^AE`\^B'`, name of the class may be different
In small test project error also appears.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/16530142/72743582-9fd65f80-3bb4-11ea-9689-20d1863f29e4.png"> 
See call stack .

 
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16530142/72743916-3c006680-3bb5-11ea-9b4a-5eca30fae423.png">

**Self contained code example that reproduces the issue**:
(1)
```swift
let filledImage = try! api
            .fillImageData(in: testableImage)// Moya request with Single<ImageData>
            .toBlocking()
            .first()
```
(2) in this case not always error above appear but also crash
```swift
func testExpample() {
        let result = "1234"
        let some = Observable<String>.just(result)
        
        let another = try! rxTest().toBlocking().first()
        XCTAssertEqual(another, result)
    }
    
    func rxTest() -> Observable<String> {
        return Observable.create { (observer) -> Disposable in
            let result = "1234"
            observer.onNext("1234")
            observer.onCompleted()
            return Disposables.create()
        }
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift (5.0.1)
  RxBlocking (5.0.1)

**Platform/Environment**

  - [+] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [+ ] easy, 100% repro

**Xcode version**:

```
  Version 11.3.1 (11C504)
```
**Installation method**:
I've tried carthage also.
  - [ +] CocoaPods
  - [+ ] Carthage

**I have multiple versions of Xcode installed**:
  - [+ ] no

**Level of RxSwift knowledge**:
  - [+ ] I have a significant code base

**Comment by SocialTermite** [comment]
https://github.com/SocialTermite/Magnificent-Sun -  In this repo and commit 
Another refactoring + unit tests (4d821f8) you can reproduce this error

**Comment by rynaardb** [comment]
@SocialTermite were you able to find a solution for this or not yet? I'm having the exact same issue as you described.

**Comment by freak4pc** [comment]
Are you using a Static Library in both these scenarios? Did you attempt linking as dynamic library in CocoaPods ?

**Comment by vmzhivetyev** [comment]
I have the same issue and the same environment. Except my error message is `failed to demangle superclass of DistinctUntilChangedSink from mangled name '7RxSwift4SinkCyxG'`

**Comment by freak4pc** [comment]
Here's a working example with Carthage with both RxTest an RxBlocking. Can you attempt adding your test to it and see how it's working for you. No issues that I can see: 

[RxCarthage.zip](https://github.com/ReactiveX/RxSwift/files/4261692/RxCarthage.zip)

**Comment by twink1e** [comment]
@SocialTermite any chance your pods are statically linked while your test targets are dynamically linked?
I had similar crash, and it got fixed once I dynamically link the pods.

**Comment by mohamede1945** [comment]
My solution to this problem is to only add it to one library. If I added it to 2 libraries or 1 library and the app, I'll get the crash.

**Comment by freak4pc** [comment]
This issue is about Carthage.
For SPM specific there is a known bug with transitive dependencies, but they haven't fixed it yet: https://bugs.swift.org/browse/SR-12303

**Comment by SocialTermite** [comment]
I switched to carthage and it works now.

**Comment by shunnokw** [comment]
For my case, I have the same error because I didn't include use_frameworks! in my pod file
