### ISSUE TITLE
limitation : ObserverType and ObservableType protocol use same associatedtype name

### ISSUE THREAD

**Issue by lemoinem** [ReactiveX/RxSwift#2120]
**Short description of the issue**:

This is basically reopening #1018. It was mentioned it could be reopened for 4.0, never was (that I could find).
Three years later (and now at 5.0), this hasn't been solved on compiler level and does not seem any closer to be. (https://bugs.swift.org/browse/SR-1616)
Could we have a library-level solution yet?

Having an internal (or even public) protocol unifying both associated types:

```
protocol ObservableObserverType: ObservableType, ObserverType
{
    associatedtype Element
    typealias ObservableElement = Element
    typealias ObserverElement = Element
}
```

would make the current code easily migrated and avoid having to define `ObservableElement` and `ObserverElement` everywhere.

**Expected outcome**:

To be able to have a single type implementing `ObserverType/func on(_ event: Event<A>)` and `ObservableType/public func subscribe<Observer: ObserverType>(_ observer: Observer) -> Disposable where Observer.Element == B`

**What actually happens**:

Since the associated type name `Element` is the same for both, it's currently impossible and we have to cut the class in two.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit** 5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**: `11.3.1 (11C504)`

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

Using two separate classes for the Observer and Observable sides of the same object is really clunky and super awkward to use...
Having an internal (or even public) protocol unifying both associated types:

```
protocol ObservableObserverType: ObservableType, ObserverType
{
    associatedtype Element
    typealias ObservableElement = Element
    typealias ObserverElement = Element
}
```

would make the current code easily migrated and avoid having to define `ObservableElement` and `ObserverElement` everywhere.

**Comment by freak4pc** [comment]
Hey, this still is a compiler issue in my eyes. I don't think it's something we'd want to change. The value is quite low for unifying a single protocol for two seemingly unrelated things (there are Observers that can't be Observed, and obviously vice-versa). 

I don't think this framework should aim to "fix" things that are definitely a compiler concern, and not a Rx concern. 

Regardless, as you mentioned, there are local workarounds once could take if they need this (relatively uncommon) use-case. 

If you have more widespread use-cases and can get community support for this change, we can consider it more seriously.

Thanks for the suggestion!

**Comment by freak4pc** [comment]
I think my opinion about it is the same as it was back in that issue. We can't solve it nicely since this is a compiler limitation.

In the very rare edge-case you need a single I/O object with different in and out (it's rare because it's a tad strange to do this), it can be solved by nesting two separate private objects for each role inside the primary object, each conforming internally. 

I'll close thing for now, but if you have a creative idea how to solve this without renaming, I'm happy to discuss.

Thanks for understanding.
