### ISSUE TITLE
is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by cqhcqhcqh** [ReactiveX/RxSwift#2121]
class ProfileHeaderView: UIView {
          private var roleButton = UIButton(type: .custom) {
                willSet {
                }
                didSet {
                }
          }
}

class aViewController: UIViewController {
         let headerview = ProfileHeaderView()
         override viewDidload() {
              headerview.roleButton.rx = Reactive(self)
         }
}
`headerview.roleButton.rx = Reactive(self)` compile error with `is inaccessible due to 'private' protection level`
why `headerview.roleButton.rx = Reactive(self)` can trigger roleButton's observer `willSet` `didSet` method?

**Comment by freak4pc** [comment]
Hey. This doesn’t seem like an issue with the project, but more of a misunderstanding of the Reactive strict. you might want to direct your question to our slack channel: http://slack.rxswift.org
