### ISSUE TITLE
limitation: Make extending the library easier by making Sink and Producer open

### ISSUE THREAD

**Issue by lemoinem** [ReactiveX/RxSwift#2122]
**Short description of the issue**:

Currently, the recommended way of extending the library is to use `Observable.create()` (https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#custom-operators). However, this is only possible for the simplest cases.
More complex cases, will require us to understand the implementation details and copy `Producer` and `Sink`.

It comes with great risk, as there are multiple case that have been taken care of (multi-thread race conditions, making sure subscriptions are properly disposed, making share subscription are started the proper way with respect to the Scheduler, ensuring there are no memory leaks or reference loops, etc.).

Having these two helpers open would definitely help a lot to implement safer extensions to the library.

Currently we have two choices:

- Not only understanding how it is used (which is not necessarily the easiest part) but why and how the implementation is plugged together, in order to reproduce the behavior ourselves.
- Just copy/paste it all and use it as-is, No question asked.

My use case in particular, basically requires something akin to `Using`, but `Using` instantiate the resource first and then subscribe using it. I need to go the other way around:
First subscribe and then instantiate the resource.

This is because the resource could generate some events synchronously when it's instantiated (I don't have the control on this) and they would be lost (or I would have to buffer them in some way, which is even more complex).
Before instantiating the resource, I also need to make sure the subscription hasn't been already disposed synchronously (in which case I don't need to instantiate the resource).

All this + the behavior of the resource and the subscription would be made so much easier if I just had access to `Producer` and `Sink`.

**Expected outcome**:

Not have to duplicate the implementation of Producer and Sink

**What actually happens**:

A lot of ugly copy paste

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit** `5.0`

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**: `11.3.1 (11C504)`

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
This is an interesting thought. TBH both this and your other thread are really edge-casey things that only benefit a minuscule portion of consumers. In this case, though, I'm not sure there's a valid reason to keep these classes internal. 

The only thing I can think of is that, if you compare to Combine, you also would only get the Subscriber, Subscription, Publisher protocols, but not any of the "pieces" that help make these things (since the framework's own implementation isn't necessarily something they want others to use). 

@kzaher if you have a moment - it would be good to know your thoughts on this. 

It does seem to me by the way, that many people make extremely complex operators with absolutely no need to access these lower-level pieces.

**Comment by freak4pc** [comment]
I gave this some more thought, given Kruno didn't have the time to reply, my current instinct is that types should be succinct and serve the majority use case and majority of users. Given how much of an edge-case it is to need access to these types and how fragile they are to use without knowing them really well, I think we'll opt to keeping them internal right now.

I understand your concerns and how uncomfortable it can be to copy-paste these, but I think this might be your best best if you want the _exact_ same behavior. 

Thanks!
