### ISSUE TITLE
rx.observe does not work properly with Core Data to-many relations

### ISSUE THREAD

**Issue by rudedogdhc** [ReactiveX/RxSwift#2123]
**Short description of the issue**:

rx.observe on NSManagedObjects does not emit the correct values when using Core Data's automatically generated accessors. Consider an entity `Person` with a to-many relation to a different entity `Pet`. Core Data will generate the following accessors in the `Person` class:

```
  @NSManaged public var pets: NSSet?

  @objc(addPetsObject:)
  @NSManaged public func addToPets(_ value: Pet)

  @objc(removePetsObject:)
  @NSManaged public func removeFromPets(_ value: Pet)

  @objc(addPets:)
  @NSManaged public func addToPets(_ values: NSSet)

  @objc(removePets:)
  @NSManaged public func removeFromPets(_ values: NSSet)
```

When doing `rx.observe(NSSet.self, "pets")`, it should emit the full set every time the relation is changed, and if you set the `pets` property directly, this is what happens. 

However, if you use one of the generated methods, such as `person.addToPets(aPet)`, then the set that is emitted only contains `aPet`. The remove methods such as`removeFromPets(_:)` emit an empty set.

**Expected outcome**:

The observer should emit the entire set of objects no matter which mechanism is used to modify the relation.

**What actually happens**:

When adding, it only emits the object(s) that were added; when deleting, it emits an empty set.

**Self contained code example that reproduces the issue**:

A project demonstrating the bug is at https://github.com/rudedogdhc/RxSwiftCoreDataKVOBug

The `testObserver()` method in `AppDelegate.swift` demonstrates the issue. It sets up two observables, one using `rx.observe` directly and one using native Swift KVO. Only the native Swift observer gives the expected results.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Tested against master.

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
11.3.1
```
**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (10.1, 10.3, 11.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by rudedogdhc** [comment]
Console output when running the sample project:

```
rx.observe: ||
direct KVO: ||

person.pets = pet0
direct KVO: |pet0|
rx.observe: |pet0|

person.pets = pet0,pet1
direct KVO: |pet0,pet1|
rx.observe: |pet0,pet1|

person.addToPets(pet2)
direct KVO: |pet0,pet1,pet2|
rx.observe: |pet2|

person.addToPets(pet3)
direct KVO: |pet0,pet1,pet2,pet3|
rx.observe: |pet3|

person.removeFromPets(pet0)
direct KVO: |pet1,pet2,pet3|
rx.observe: ||

person.addToPets(pet4,pet5)
direct KVO: |pet1,pet2,pet3,pet4,pet5|
rx.observe: |pet4,pet5|

person.removeFromPets(pet2,pet3)
direct KVO: |pet1,pet4,pet5|
rx.observe: ||
```

**Comment by rudedogdhc** [comment]
Following up some more, I think that this is a result of how KVO works with to-many relations. When `addToPets(_:)` is called, `NSKeyValueObservedChange.kind` contains `.insertion`, and its `.newValue` contains only the values that were inserted. This is how it is supposed to work according to Apple's documentation, but the result is not at all expected in a Reactive framework.

I've confirmed that this is what `_RXKVOOBserver.m` is doing:

```
self.callback(change[NSKeyValueChangeNewKey]);
```

I think it should instead be doing:

```
self.callback([object valueForKeyPath:self.keyPath]);
```

**Comment by freak4pc** [comment]
Hey @rudedogdhc - we can't make such a change as it would be breaking existing behavior for other consumers. I think specific use-case observations for KVO is outside of the use cases list we support here since generally in a reactive framework, you're interested in a new value, and not necessarily other portions.
