### ISSUE TITLE
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa

### ISSUE THREAD

**Issue by josephkandi** [ReactiveX/RxSwift#2126]
I get the above error when i deploy the app to a physical device. I do not get an error in the simulator.

**Expected outcome**:

The app should launch on the physical device without crashing

**What actually happens**:

App crashes with the following error :

```
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa
  Referenced from: /private/var/containers/Bundle/Application/88FAC5D9-11D1-472B-9804-5B5BFD932C2F/Leaderboard.app/Leaderboard
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/88FAC5D9-11D1-472B-9804-5B5BFD932C2F/Leaderboard.app/Frameworks/RxCocoa.framework/RxCocoa: code signature invalid for '/private/var/containers/Bundle/Application/88FAC5D9-11D1-472B-9804-5B5BFD932C2F/Leaderboard.app/Frameworks/RxCocoa.framework/RxCocoa'
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
target 'Leaderboard' do
    use_frameworks!
    platform :ios, '13.3.1'
    pod 'NewRelicAgent', '6.6.0'
    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
  end
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  11.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by josephkandi** [comment]
It seems the issue is affecting all non iOS SDK frameworks that are using the personal developer account for running on a physical device as per this StackOverflow post, https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid

**Comment by freak4pc** [comment]
Doesn't seem to me like this is an issue with RxSwift. I suggest filing a Feedback with Apple. @josephkandi

**Comment by josephkandi** [comment]
> Doesn't seem to me like this is an issue with RxSwift. I suggest filing a Feedback with Apple. @josephkandi

Yes, you are right, closing the issue.

**Comment by EricGolovin** [comment]
> Doesn't seem to me like this is an issue with RxSwift. I suggest filing a Feedback with Apple. @josephkandi

This error occurs only on none iOS SDK

**Comment by yangguanghei** [comment]
run in the simulator is ok
