### ISSUE TITLE
Error when using package manager in Xcode 11.4 beta

### ISSUE THREAD

**Issue by nhatlee** [ReactiveX/RxSwift#2127]
**Short description of the issue**:

I create new project for test using RxSwift via `Swift package manager` . In Xcode project I chose `File -> Swift Packages -> Add Package Dependency...` to add RxSwift repo. But after Xcode fetch the RxSwift lib successful. I press build and get the error:

```
ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'
Undefined symbols for architecture x86_64:
  "XCTest.XCTAssertEqual<A where A: Swift.Equatable>(_: @autoclosure () throws -> A, _: @autoclosure () throws -> A, _: @autoclosure () -> Swift.String, file: Swift.StaticString, line: Swift.UInt) -> ()", referenced from:
      RxTest.XCTAssertEqual<A where A: Swift.Equatable>(_: [RxSwift.Event<A>], _: [RxSwift.Event<A>], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertEqual<A where A: Swift.Equatable>(_: [RxSwift.SingleEvent<A>], _: [RxSwift.SingleEvent<A>], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertEqual<A where A: Swift.Equatable>(_: [RxSwift.MaybeEvent<A>], _: [RxSwift.MaybeEvent<A>], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertEqual(_: [RxSwift.CompletableEvent], _: [RxSwift.CompletableEvent], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertEqual<A where A: Swift.Equatable>(_: [RxTest.Recorded<RxSwift.Event<A>>], _: [RxTest.Recorded<RxSwift.Event<A>>], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertEqual<A where A: Swift.Equatable>(_: [RxTest.Recorded<RxSwift.Event<A?>>], _: [RxTest.Recorded<RxSwift.Event<A?>>], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      RxTest.XCTAssertRecordedElements<A where A: Swift.Equatable>(_: [RxTest.Recorded<RxSwift.Event<A>>], _: [A], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
      ...
  "XCTest.XCTFail(_: Swift.String, file: Swift.StaticString, line: Swift.UInt) -> ()", referenced from:
      RxTest.XCTAssertRecordedElements<A where A: Swift.Equatable>(_: [RxTest.Recorded<RxSwift.Event<A>>], _: [A], file: Swift.StaticString, line: Swift.UInt) -> () in RxTest.o
  "__swift_FORCE_LOAD_$_XCTestSwiftSupport", referenced from:
      __swift_FORCE_LOAD_$_XCTestSwiftSupport_$_RxTest in RxTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Showing All Messages
Could not find or use auto-linked library 'XCTestSwiftSupport'

Could not find or use auto-linked framework 'XCTest'

Undefined symbol: XCTest.XCTAssertEqual<A where A: Swift.Equatable>(_: @autoclosure () throws -> A, _: @autoclosure () throws -> A, _: @autoclosure () -> Swift.String, file: Swift.StaticString, line: Swift.UInt) -> ()

Undefined symbol: XCTest.XCTFail(_: Swift.String, file: Swift.StaticString, line: Swift.UInt) -> ()

Undefined symbol: __swift_FORCE_LOAD_$_XCTestSwiftSupport

```

**Expected outcome**:

Expected run success.

**What actually happens**:

Got the error with above log

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 11.4 beta 1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Swift Package Manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by nhatlee** [comment]
I post full logs and attached the image:

<img width="1400" alt="Screen Shot 2020-02-09 at 11 34 18" src="https://user-images.githubusercontent.com/7148482/74096353-60a28b00-4b30-11ea-8f23-544a5551e03f.png">


[Build target LovePet_2020-02-09T11-24-15.txt](https://github.com/ReactiveX/RxSwift/files/4176483/Build.target.LovePet_2020-02-09T11-24-15.txt)

**Comment by freak4pc** [comment]
Hey there :) 
If it works on 11.4 (which is in beta) and doesn't have issues on 11.3, this is likely a bug inside SPM itself. 

We only have so much capacity so we can't spend the time fixing specific package manager bugs, at least not until 11.4 goes out of beta. 

If you have a PR that might fix this issue, I'm happy to review and merge it. 

Thanks !

**Comment by freak4pc** [comment]
@nhatlee Do you have additional feedback on this issue?

**Comment by nhatlee** [comment]
I don't have time to investigating this issue since I post it. I will try to find out when have time.

**Comment by nhatlee** [comment]
After some trying. It seem the issue related to `XCTest`. Move `RxTest` from target to `testTarget` fixed the issue.  The change for Package file like this commit: https://github.com/nhatlee/RxSwift/commit/19df574ac70e4ce3f758a807b8541097c7397398

**Comment by freak4pc** [comment]
It shouldn't be a testTarget, the reason it's working for you is that you removed all of its dependencies

There's an entire discussion around this here: https://twitter.com/freak4pc/status/1233560587176681472

**Comment by freak4pc** [comment]
From discussions in the SPM slack this seems like a bug. 
I've reported it here: https://bugs.swift.org/browse/SR-12303
And also filed a feedback: FB7608638

**Comment by truizlop** [comment]
I have the same issue after updating to Xcode 11.4 (stable version, not beta). Any way to solve/workaround this?

**Comment by freak4pc** [comment]
The workaround is to wrap all of your Rx dependencies in one product inside your own app, which would remove the duplications. I'm not sure this would work for RxTest and RxBloccking, though: 

```swift
let package = Package(
  name: "Rx Wrapper",
  products: [
    .library(name: "Rx", targets: ["Rx"]),
    .library(name: "RxTesting", targets: ["RxTesting"])
  ],
  dependencies: [
    .package(
      url: "https://github.com/ReactiveX/RxSwift.git",
      .upToNextMajor(from: "5.0.0")
    )
  ],
  targets: [
    .target(
      name: "Rx",
      dependencies: ["RxSwift" , "RxCocoa", "RxRelay"]
    ),
    .target(
      name: "RxTesting",
      dependencies: ["RxTest", "RxBlocking"]
    )
  ]
```

I'm not sure this will work for the test target, as mentioned above. 
This workaround was added in the SPM Slack by @DevAndArtist, but I hope Apple will provide an actual solution at some point:

[RxSPM_Mod.zip](https://github.com/ReactiveX/RxSwift/files/4379922/RxSPM_Mod.zip)

**Comment by antranapp** [comment]
I have a similar problem now with Xcode 11.4.1 

I can see now, if I integrate RxSwift using SPM, SPM will built RxSwift as a static library:

![Screenshot 2020-05-06 at 22 04 31](https://user-images.githubusercontent.com/478757/81223195-ea55dd80-8fe5-11ea-9b6b-ce7acb2b6da3.png)

I could workaround the issue by forcing SPM to build RxSwift as a dynamic framework in my fork: https://github.com/antranapp/RxSwift/commit/722615a926029289acd671dcf95a7494d41caf06

![Screenshot 2020-05-06 at 22 05 07](https://user-images.githubusercontent.com/478757/81223213-f0e45500-8fe5-11ea-9ae2-ee19248a94df.png)

Is there any reason that we are not building RxSwift as a dynamic library by default?

**Comment by freak4pc** [comment]
@antranapp From the tests I've ran it only solves half of the issues. Tests still don't run. 

There's a long discussion in the SPM slack around this, and generally, it's an "open bug" . What we might have to do is basically not allow installing RxTest and RxBlocking via SPM until Apple solves this, and that should mostly solve it, I believe.

**Comment by Genar** [comment]
In addition it could be useful to assign both RxBlocking and RxTest only to test targets (not your app target). For example, in the previous image, it could be useful to assign RxBlocking and RxTest not to the target XCoordinator but to a "XCoordinatorTests".

**Comment by freak4pc** [comment]
This is still an issue in Xcode 11.5. I'm not sure if there is much to be done here or if there is reason to leave this open. Apple provides us no way to make this work well. The only workable option would be to break RxSwift into a bunch of smaller repos (5-6-7 repos) which isn't something I'm interested in doing. I hope they'll find a fix for this soon. 

If anyone has any additional questions / feedback, feel free to comment and I can always reopen. Thanks!

**Comment by phoe3nix** [comment]
@nhatlee @freak4pc Hello! I have completely translated my project to SPM and have this issue. In this attachment test project with RxSwift Libraries and working tests with static linking RxTest. `Enable Testing Search Path` in this package configuration with additional wrapper local package allows you to run unit tests. 
[RxTestProj.zip](https://github.com/ReactiveX/RxSwift/files/5451015/RxTestProj.zip)

**Comment by freak4pc** [comment]
I'm not entirely sure what are the configuration changes you made. Does it work for your own project?

**Comment by phoe3nix** [comment]
@freak4pc Yes, for my project it`s work great. In build settings for main app in chapter `build options` I change  `Enable Testing Search Path` from `NO` to `YES`. I think, that is allow to find path to XCTest framework and use necessary symbol.

**Comment by freak4pc** [comment]
So, did you make a fork of this repo chasing the product type to static for everything?

**Comment by phoe3nix** [comment]
Yes, all library static. When archive or build this app, we dont see folder frameworks in .app. Also export app work good.

**Comment by freak4pc** [comment]
Do you have other dependencies that depend upon RxSwift? For example RxDataSources, RxSwiftExt, or others?

**Comment by phoe3nix** [comment]
In my project yes. RxDataSource, RxSwiftExt and RxGesture.

**Comment by freak4pc** [comment]
That helps. Thank you! I'll take a look.

**Comment by loganwright** [comment]
@phoe3nix 's suggestion worked great for me!

> In build settings for main app in chapter `build options` I change `Enable Testing Search Path` from `NO` to `YES`. I think, that is allow to find path to XCTest framework and use necessary symbol.

**Comment by kbw2204** [comment]
In my project, Excluding the RxTest and RxBlocking parts of RxSwift solved the error.

**Comment by thiagocenturion** [comment]
> In my project, Excluding the RxTest and RxBlocking parts of RxSwift solved the error.

Best answer if you wouldn't use RxTest and RxBlocking in unit tests. It works perfectly for me.

**Comment by usman-pucit** [comment]
> Testing Search Path

Works for me

**Comment by Bryan-Hwang** [comment]
> @nhatlee @freak4pc Hello! I have completely translated my project to SPM and have this issue. In this attachment test project with RxSwift Libraries and working tests with static linking RxTest. `Enable Testing Search Path` with flag `YES` in this package configuration with additional wrapper local package allows you to run unit tests.
> [RxTestProj.zip](https://github.com/ReactiveX/RxSwift/files/5451015/RxTestProj.zip)

Works for me

**Comment by freakdragon** [comment]
If someone gets error "Missing libXCTestSwiftSupport.dylib" after set `Enable Testing Search Path` than you must readd the library and set targets of `RxTest` and `RxBlocking` to your **test targets**. Look [here](https://forums.swift.org/t/missing-libxctestswiftsupport-dylib/35314/7) to see the example.
