### ISSUE TITLE
How to unit test Completable with RxTest or RxBlocking?

### ISSUE THREAD

**Issue by CharlotteErpels19931** [ReactiveX/RxSwift#2128]
Is there a way to unit test a completable with RxTest or RxBlocking? I've been trying all evening to do this but no luck :(

The function I want to test is:

func execute(email: String) -> Completable

**Comment by freak4pc** [comment]
Hey Charlotte,
You can look at some examples from the repo. Basically you can just test it like a regular Observable and only testing on `complete` events:

https://github.com/ReactiveX/RxSwift/blob/master/Tests/RxSwiftTests/CompletableTest.swift#L180

If you have more questions on "How do I do XXX?" - please join our slack at http://slack.rxswift.org

We try to keep issues for bugs :) 

Thanks!
