### ISSUE TITLE
[Xcode 11.3.1] "Could not find module 'RxSwift' for target 'arm64-apple-ios';"

### ISSUE THREAD

**Issue by entotsu** [ReactiveX/RxSwift#2135]
My iOS App Project was no ploblem with RxSwift for 2~3 month untill today's morning,
but My Project have broken since I excuted `carthage update` once...

I spent half of day, but It haven't solved.

# Process & Error

> carthage update RxSwift --platform iOS

↓

> 	:warning: "Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)."
<img width="807" alt="スクリーンショット 2020-02-24 23 14 20" src="https://user-images.githubusercontent.com/2075801/75159468-8e581880-575b-11ea-93a2-ee99ec5eb8de.png">

> Falling back to building from the source

↓

✔ Carthage Build is finished.

↓

Build Error on Xcode Project.

❌ **`Could not find module 'RxSwift' for target 'arm64-apple-ios'; found: i386, i386-apple-watchos-simulator, arm64_32-apple-watchos, armv7k, armv7k-apple-watchos, arm, arm64_32`**
<img width="1203" alt="スクリーンショット 2020-02-24 23 15 23" src="https://user-images.githubusercontent.com/2075801/75159500-9a43da80-575b-11ea-9178-8d5b4a7d5ed9.png">

---

**Expected outcome**:

No Problem of Xcode Build.

**What actually happens**:

:warning: "Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)."

❌ `Could not find module 'RxSwift' for target 'arm64-apple-ios'; found: i386, i386-apple-watchos-simulator, arm64_32-apple-watchos, armv7k, armv7k-apple-watchos, arm, arm64_32`

# Information

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
Version 11.3.1 (11C504)
```

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by entotsu** [comment]
And I confirmed 'arm64-apple-ios' module of RxSwift.
<img width="838" alt="スクリーンショット 2020-02-24 23 36 50" src="https://user-images.githubusercontent.com/2075801/75161123-98c7e180-575e-11ea-89f3-c2602d09e872.png">

**Comment by okamoto-creation** [comment]
+1

**Comment by freak4pc** [comment]
Hey - I don't know enough about Carthage and this doesn't seem to happen to me. Can you attach a project reproducing the issue? 

If you have a PR to solve this, I'd be happy to accept as well.

**Comment by entotsu** [comment]
This is sample project to reproduce the issue.
https://github.com/entotsu/Sample

**Comment by freak4pc** [comment]
Your project has a bunch of non-compiling dependency and Realm code, so I can't do much with it. Here's a test I made with Carthage based on the instructions in the Carthage project, including a test target, and everything seems fine: 

[RxCarthage.zip](https://github.com/ReactiveX/RxSwift/files/4261692/RxCarthage.zip)

Please test and let me know.

**Comment by entotsu** [comment]
@freak4pc Thank you.
I made a simple project of RxSwift with Carthage, and It's no problem too. 👌

**Comment by entotsu** [comment]
I found a reason of this problem.
I don't know why but Framework Search Path` had **WatchOS**'s path.
I removed it, and build error was solved! 👌 
<img width="641" alt="スクリーンショット 2020-02-28 2 18 29" src="https://user-images.githubusercontent.com/2075801/75468838-417d7780-59d1-11ea-92f3-92a52f03fb27.png">
