### ISSUE TITLE
Deprecated UIWebView usage - Time to take action!!!

### ISSUE THREAD

**Issue by mikepham1011** [ReactiveX/RxSwift#2139]
**Short description of the issue**:

I receive this warning from Apple just now.

```
We identified one or more issues with a recent delivery for your app, "xxxxxxx" x.x (x). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.
```

**Expected outcome**:

Remove the usage of UIWebView

**What actually happens**:

UIWebView is not removed and Apple keeps sending emails about the termination of UIWebView usage.

**Self contained code example that reproduces the issue**:

```swift
None
  
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
11.3.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Please read other threads before opening a new one. This was thoroughly discussed including information on timeline and plans.

**Comment by klmitchell2** [comment]
Not to beat a dead horse, but is this the information on timeline and plans? 
<img width="873" alt="image" src="https://user-images.githubusercontent.com/5108164/75709992-58e68a00-5c89-11ea-9429-74232e827f34.png">

**Comment by freak4pc** [comment]
We still have a month (+) before April, there will be a release before that. As I said, since this is not a hard deprecation/rejection on Apple's side we don't see a huge rush to release it. I've been trying to sort an issue with SPM distribution but it seems to be a bug with SPM itself so we'll release 5.1.0 soon without the UIWebView symbol. 

Apple's timeline is April 2020 for updates and December 2020 fo new apps.

**Comment by freak4pc** [comment]
https://github.com/ReactiveX/RxSwift/issues/2055#issuecomment-594146342
