### ISSUE TITLE
Error when using RxSwift in multiple projects in workspace

### ISSUE THREAD

**Issue by ThasianX** [ReactiveX/RxSwift#2142]
**Error when using RxSwift in multiple projects in workspace**:

The project builds fine but I get run time errors associated with overlapping dependencies.

**Expected outcome**:

Project should run fine.

**What actually happens**:

When run, I get errors much like the one below: 
`objc[51039]: Class _TtC7RxSwift22CurrentThreadScheduler is implemented in both /Users/kevinli/Library/Developer/Xcode/DerivedData/Platform-fmrljfrfcbyocvaxgjkiduxdcvln/Build/Products/Debug-iphonesimulator/Content.framework/Content (0x11096e278) and /Users/kevinli/Library/Developer/Xcode/DerivedData/Platform-fmrljfrfcbyocvaxgjkiduxdcvln/Build/Products/Debug-iphonesimulator/OnCall.framework/OnCall (0x103e2c300). One of the two will be used. Which one is undefined.`

Project Structure:

- Foo(Project which has some internal dependencies linked as frameworks)
- Bar(Project which has some internal dependencies linked as frameworks)
- Internal Dependencies(Projects) 

Dilemma: 

Foo, Bar, and the internal dependencies all use SPM to grab the RxSwift package. The part I'm confused about is that since this is all in one workspace, only 1 version of the RxSwift package may exist -- Foo, Bar, and the internal dependencies are all pointing to the same package of RxSwift in the workspace. Then why do I get a run time error?
    

**RxSwift version**

5.1.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

Not Applicable

**Xcode version**:

11.3.1

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Swift Package Manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Hey ThasianX, 
That indeed seems like there are multiple copies of the framework for some reason. 

This isn’t an issue with RxSwift but seems like a general linking / configuration error. In these cases we suggest trying on SO or our Slack (http://slack.rxswift.org) to keep GH issues for bugs only.

Thanks for understanding ! 
Shai
