### ISSUE TITLE
the UIBarButtonItem rx_tap does not call !?

### ISSUE THREAD

**Issue by zixun** [ReactiveX/RxSwift#215]
let leftItem = UIBarButtonItem(customView: UIImageView(image: UIImage(named: "nav_cancel")))
        leftItem.enabled = true
        self.navigationItem.rightBarButtonItem = leftItem
        leftItem.rx_tap
            .subscribeNext { [weak self] x in
                self?.dismissViewControllerAnimated(true, completion: nil)
            }
            .addDisposableTo(disposeBag)

this is my code  but the subscribeNext does not call while I tap the  UIBarButtonItem

I debug with UIBarButtonItem+Rx.swift,the function

    func action(sender: AnyObject) {
        callback()
    }

does not call

**Comment by zixun** [comment]
I set false of userInteractionEnabled to the customView in  UIBarButtonItem,it's also didn't call the action

**Comment by zixun** [comment]
if I replace the init of  UIBarButtonItem,such as:

    init(image: UIImage?, style: UIBarButtonItemStyle, target: AnyObject?, action: Selector)

    init(title: String?, style: UIBarButtonItemStyle, target: AnyObject?, action: Selector)

the function of action: will call !!
why~

**Comment by kzaher** [comment]
Hi @zixun ,

I believe [the problem](http://stackoverflow.com/questions/2796438/uibarbuttonitem-target-action-not-working) is that `UIImageView` isn't passing touch events properly. Don't think this is a problem with RxCocoa :)


Hope that helps :)

**Comment by zixun** [comment]
@kzaher  yes,I think so. but user does not know the implement of the RxCocoa.Can we make a UITapGestureRecognizer inside the  customView of the UIBarButtonItem by RxCocoa while the customView is not nil, and then call the action method. If you think it is feasible，I‘ll commit a PR to the repo

**Comment by zixun** [comment]
may be it's not feasible , if the custom is UIButton, my gesture will be redundant

**Comment by yury** [comment]
@zixun can't agree that we need to do UITapGestureRecognizer on customView - it can be anything custom with desired tap area.

**Comment by kzaher** [comment]
Hi guys,

I understand the confusion that when you read `rx_tap` you would expect that it works no matter what you put in that `UITabBarItem`, but that's not how touch system on iOS works.

We tried to document what is the intention of that extension
```
/**
    Reactive wrapper for target action pattern on `self`.
    */
```

Maybe we can make that description clearer to better reflect what is the purpose of that extension.

**Comment by yury** [comment]
@kzaher may be it should be called `rx_action`?

**Comment by harrylin90** [comment]
@kzaher I think your image view should set userinterface = yes , or your touch will never call. It's not how rxcocoa works, it's how cocoa touch works.

**Comment by harrylin90** [comment]
UIImageView's userinterfaceEnabled is false, so the item can't be called by touch. You can change to UIView then it will be correct.

**Comment by kzaher** [comment]
Hi guys,

Speaking generally, no matter how any interface is defined it will always create confusion in some situations.

That's simply unavoidable because you need to compress a lot bigger implementation to a few words that should correspond to it.

I think that even the name of the interface `rx_tap` corresponds nicely with implementation, if tap event gets to `UIBarButtonItem`, we will send next element :)

I think this implementation and naming are satisfying for now :)

@zixun hope this makes sense?

**Comment by zixun** [comment]
@kzaher  thx~ i m agree with you

**Comment by kzaher** [comment]
I think we all agreed current behavior is ok :), closing this one :)
