### ISSUE TITLE
Share and Take operators conflict

### ISSUE THREAD

**Issue by anton-plebanovich** [ReactiveX/RxSwift#2152]
**Short description of the issue**:
`.share(replay: 1, scope: .forever)` and `.take(1)` operators conflict causes different behavior depending on how element was received.

**Expected outcome**:
It shouldn't be different if a result was emitted at the creation of the Observable or delivered later.

**What actually happens**:
A result differs

**Self contained code example that reproduces the issue**:

**Example 1:**
```swift
let observable = Observable.just(1)
    .debug("debug")
    .share(replay: 1, scope: .forever)
    .take(1)

_ = observable.subscribe()

DispatchQueue.main.asyncAfter(deadline: .now()) {
    _ = observable.subscribe()
}
```

**Output 1:**
```
debug -> subscribed
debug -> Event next(1)
debug -> Event completed
debug -> isDisposed
```

**Example 2:**
```swift
let observable = Observable<Int>
    .create { observer in
        DispatchQueue.main.asyncAfter(deadline: .now()) {
            observer.onNext(1)
            observer.onCompleted()
        }
        
        return Disposables.create()
    }
    .debug("debug")
    .share(replay: 1, scope: .forever)
    .take(1)

_ = observable.subscribe()

DispatchQueue.main.asyncAfter(deadline: .now()) {
    _ = observable.subscribe()
}
```

**Output 2:**
```
debug -> subscribed
debug -> Event next(1)
debug -> isDisposed
debug -> subscribed
debug -> isDisposed
```

As you can see the issue is that in the second case `completed` event wasn't delivered to the `share` operator so it thinks that sequence wasn't completed and so it'll trigger `subscribed` and `isDisposed` events each time it subscribed later causing excessive operations.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
RxSwift (5.1.0)

**Platform/Environment**
  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
  - [x] easy, 100% repro

**Xcode version**:
```
Version 11.3.1 (11C504)
```

**Installation method**:
  - [x] CocoaPods
  - [x] Carthage

**I have multiple versions of Xcode installed**:
  - [x] no

**Level of RxSwift knowledge**:
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Hey, thanks for reporting this. In practice, the behavior of `.forever` is weird on the edge of undefined in some senses. Can you share what's your exact use-case here? Maybe we can figure out a nicer way around this that doesn't involve forever, specifically.

**Comment by anton-plebanovich** [comment]
Hey @freak4pc I'm using custom operator `.preventCancellation()` after `.share(replay: 1, scope: .forever)` so it can always receive its result.

**Comment by freak4pc** [comment]
So if you prevent its cancelltion why not just use whileConnected scope?

**Comment by anton-plebanovich** [comment]
You are right with that workaround it doesn't matter which `scope` will be used 😄 but I created this issue to notify RxSwift team about it. If it's something that you believe is ok to have I won't complain against closing it.

**Comment by freak4pc** [comment]
I think I'll close this for now, but appreciate the reporting. If someone will report a similar issue we can refer back to your findings. Thanks!
