### ISSUE TITLE
Xcode 11.4 and swift 5.2

### ISSUE THREAD

**Issue by bukira** [ReactiveX/RxSwift#2153]
Code doesn't compile with swift 5.2
RxCocoa

**Comment by freak4pc** [comment]
Please open a new issue with more details and fill the template.

**Comment by bukira** [comment]
Time is pressing,

It doesn’t compile and I have urgent work to do

**Comment by freak4pc** [comment]
Ok, you're free to fork it, fix it, and use your own copy.
Maintainers aren't hired by you and don't work on your schedule. Please be respectful.

**Comment by freak4pc** [comment]
See #2125

**Comment by bukira** [comment]
See 2125 ???

**Comment by freak4pc** [comment]
It's an existing issue where this is discussed.
