### ISSUE TITLE
I meet an issue while pod spec lint and pod trunk 

### ISSUE THREAD

**Issue by StoneStoneStoneWang** [ReactiveX/RxSwift#2156]
[!] The spec did not pass validation, due to 2 errors.
- ERROR | [iOS] xcodebuild:  RxCocoa/RxCocoa/iOS/Proxies/RxWKNavigationDelegateProxy.swift:35:16: error: expression resolves to an unused property

**Comment by freak4pc** [comment]
Hey, please provide more details, you didn't provide enough to help you. 

For example, you didn't mention which platforms, what did you do, how are you consuming RxSwift, and why do you even need to do `pod spec lint` and `pod trunk`. 

Just FYI for next time, we usually automatically close any issues opened without filling the full template - please don't delete that one when opening an issue :)

**Comment by StoneStoneStoneWang** [comment]
My Xcode version is 10.2.1 and my macos is 10.15.3.
The website is my pod librarie https://github.com/StoneStoneStoneWang/ZStoreKit.git.
<img width="1227" alt="WechatIMG10" src="https://user-images.githubusercontent.com/16629437/77646621-ddce7600-6f9f-11ea-816f-f4321673e671.png">
In the terminal I execute pod spec lint ZCocoa.podspec --allow-warnings or  pod trunk push  ZCocoa.podspec --allow-warnings.
It has two errors 
<img width="575" alt="WechatIMG11" src="https://user-images.githubusercontent.com/16629437/77646943-7d8c0400-6fa0-11ea-8641-a1b33f204418.png">

spec.dependency 'RxCocoa', '5.0.1' is ok!
spec.dependency 'RxCocoa' or  'RxCocoa', '~> 5.0.1' is failed!

**Comment by freak4pc** [comment]
You're using a very old version of Xcode. 

10.2.1 has been released over a year ago, we've seen 7-8 different Xcode releases since. 

I might release a patch to solve this, but please note we won't keep supporting such an old Xcode version forever. In general, we guarantee supporting specific versions of operating systems, but not specific versions of Xcode itself.

**Comment by StoneStoneStoneWang** [comment]
Which xcode version do you use?

**Comment by freak4pc** [comment]
I personally use Xcode 11.4 which is the newest, but any version of Xcode 11 will work for you.

**Comment by StoneStoneStoneWang** [comment]
Thanks!

**Comment by StoneStoneStoneWang** [comment]
I will upgrade my xcode in the future
