### ISSUE TITLE
RxSwift v5.1.1 error: Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by matheusmaus** [ReactiveX/RxSwift#2157]
**Short description of the issue**:

Can't build the project

**Expected outcome**:

Build succeeded 

**What actually happens**:

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: [...]/Carthage/Build/iOS/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Self contained code example that reproduces the issue**:

`import RxSwift`
  
**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.1.0, but in my Cartfile I declared `github "ReactiveX/RxSwift" == 5.1.1` to be able to force the new version but he keeps only fetching the 5.1.0 version. 

I already clean the Derived Data folder, did a `carthage build --platform iOS` but another error occurs, "Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)."

And did this `BUILD_LIBRARY_FOR_DISTRIBUTION = YES`

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

Version 11.4 (11E146)

**Installation method**:

  - [ ] Carthage

**I have multiple versions of Xcode installed**:

  - [ ] no

**Level of RxSwift knowledge**:

  - [ ] just starting

**Comment by freak4pc** [comment]
Hey @matheusmaus, 
I just tried and it works on my end. 

![image](https://user-images.githubusercontent.com/605076/77725961-dc389880-7007-11ea-9439-dcdb099f8caf.png)

I also added a pretbuilt binary built with the Swift 5.2 compiler. Could you try again?
If this still doesn't work, could you try clearing your Carthage cache with:

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit/
```

**Comment by matheusmaus** [comment]
After some work, now worked.

**Comment by OlyaYan** [comment]
how did it work?
