### ISSUE TITLE
[Pitch] KVO using KeyPathes

### ISSUE THREAD

**Issue by mRs-** [ReactiveX/RxSwift#2164]
Currently there is no real implementation for KVO using KeyPathes. I looked in the Implementation from RxSwift and there is an Implementation deep insight that’s written in objc as well.

So I wrote a small extension to use the new style API from Apple with KeyPath support.

```swift
public func observe<Element>(by keyPath: KeyPath<Base, Element>, options: NSKeyValueObservingOptions = [.new, .initial], retainSelf: Bool = true) -> Observable<Element?> {
    .create { observer -> Disposable in
        let keyValueObservation = self.base.observe(keyPath, options: options) { (baseElement, changed) in
            observer.onNext(baseElement[keyPath: keyPath])
        }
        return Disposables.create {
            keyValueObservation.invalidate()
        }
    }
}
```

Is this interesting for the core of RxSwift as well? Am I missing some parts thats currently missing in my Implementation? Before I'm going to create a Pull Request I would have some insights from the core team about this.

**Comment by freak4pc** [comment]
Hey Marius,
I've actually wanted to add this for a while. I'm not seeing you actually use `retainSelf`, is it there for a reason? 

I don't know about any specifics of KVO enough but the work that has been put into this repo (with the comments) seem to indicate there are some gotchas around retainment that should be worth checking.

**Comment by mRs-** [comment]
Hi,

currently this is just a Prototype and wanted to add some code to it. If this is really interesting for the core I will try to add this in the next weeks. Could be awesome to deprecate the old way and using keyPathes all over 😀

**Comment by freak4pc** [comment]
I've added this in this commit: f7479ae975b3eb501a65ab04cac5af4bce73c958

Would be great if you could test it. Let me know :)

Thanks for the pitch!
