### ISSUE TITLE
RxCocoa 5.1.1 does not build with Xcode 10.3

### ISSUE THREAD

**Issue by fen-x** [ReactiveX/RxSwift#2166]
**Short description of the issue**:

RxCocoa 5.1.1 does not build with Xcode 10.3.

**Expected outcome**:

[README](https://github.com/ReactiveX/RxSwift/blob/5.1.1/README.md#requirements) states Xcode 10.2 as minimum supported version.

**What actually happens**:

There are 2 files in RxCocoa which use [implicit returns from single-expression functions](https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md):

 - [RxWKNavigationDelegateProxy.swift](https://github.com/ReactiveX/RxSwift/blob/5.1.1/RxCocoa/iOS/Proxies/RxWKNavigationDelegateProxy.swift)
- [WKWebView+Rx.swift](https://github.com/ReactiveX/RxSwift/blob/5.1.1/RxCocoa/iOS/WKWebView+Rx.swift)

Implicit returns is Swift 5.1 feature thus available only starting from Xcode 11.

**Self contained code example that reproduces the issue**:

Having Xcode 10.3 selected it is enough to lint RxCocoa pod itself:

```
pod lib lint RxCocoa.podspec
```

**RxCocoa version**

 5.1.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.3
```

**Comment by freak4pc** [comment]
Please look over the release itself, we’ll update the README. 

> We no longer guarantee support for Xcode 10.x. Maintaining these is counter-intuitive as they're over a year old and are ridden with bugs.

**Comment by freak4pc** [comment]
https://github.com/ReactiveX/RxSwift/releases/tag/5.1.1

**Comment by fen-x** [comment]
Thanks for pointing this out.

Went through README and CHANGELOG but missed release notes. ¯\_(ツ)_/¯
