### ISSUE TITLE
Type Mismatch: Signed to Unsigned

### ISSUE THREAD

**Issue by divyaKalusulingam** [ReactiveX/RxSwift#2167]
We have used the Rxswift and Rxcocoa 5.0.0 podfile as per our need. Here we have attached the screenshots for your reference. Kindly help us asap.

**Short description of the issue**:
The function RX_reference_from_selector() in _RXObjCRuntime.m is declared to return an unsigned value, but on line 214 it returns a signed value.The function is declared to return an unsigned number but returns a signed value.

<img width="1014" alt="Screenshot 2020-04-06 at 3 56 11 PM" src="https://user-images.githubusercontent.com/63187061/78548939-3236e880-781f-11ea-9708-44a65e0eea20.png">

<img width="1046" alt="Screenshot 2020-04-06 at 3 56 19 PM" src="https://user-images.githubusercontent.com/63187061/78548942-3531d900-781f-11ea-9ca5-5fdc0a56459c.png">

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
 

**Xcode version**:   11.3.1 

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)

  - [ ] no

**Level of RxSwift knowledge**:
 
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey there @divyaKalusulingam - 
That function doesn't seem to operator on numeric values at all, but a selector (`SEL`). Where are you seen signed and unsigned numbers?

**Comment by damienb** [comment]
Hello,
I have the same problem with the Fortify (https://www.microfocus.com/en-us/solutions/application-security) tool.
Do you have an idea to solve this problem or is it a false positive?
Thank you

**Comment by freak4pc** [comment]
Both the op and you provided no answer to my question, so I have no way to help.

**Comment by damienb** [comment]
I am not at all an expert in objective c.
I'm just trying to understand a vulnerability that was brought to our attention by a static code security audit tool.
I share the result of the tool
<img width="612" alt="Capture d’écran 2020-05-18 à 15 44 02" src="https://user-images.githubusercontent.com/23341379/82220116-848b1f00-991e-11ea-9fb0-34053abd3da6.png">

**Comment by freak4pc** [comment]
There is nothing signed or unsigned in that highlighted piece of code.

I'm happy to try and help but you'll need to provide more code-specific details here. I suggest sending them a support request (the company who made the tool) nd ask for clarificaation.

Thanks!

**Comment by freak4pc** [comment]
I'm closing this given the fact there was no response to my questions for almost a month. Thanks!
