### ISSUE TITLE
Interval imitate execution

### ISSUE THREAD

**Issue by psophis** [ReactiveX/RxSwift#217]
Can Interval have an optional flag for an imitate execution in addition to execution after each interval?

**Comment by kzaher** [comment]
I think that's just `interval().startWith(-1).map { $0 + 1 }` :)

**Comment by kzaher** [comment]
You can also use 

```
@warn_unused_result(message="http://git.io/rxs.uo")
public func timer<S: SchedulerType>(dueTime: S.TimeInterval, _ period: S.TimeInterval, _ scheduler: S)
    -> Observable<Int64> {
    return Timer(
        dueTime: dueTime,
        period: period,
        scheduler: scheduler
    )
}
```

`timer(0, interval, scheduler)`

**Comment by psophis** [comment]
Thanks! So `interval` is more or less equivalent to `timer(interval, interval, scheduler)`?

**Comment by kzaher** [comment]
Yep, it should be :)

**Comment by psophis** [comment]
Great! Thanks!
