### ISSUE TITLE
Is there a way to get result without using subscribe

### ISSUE THREAD

**Issue by bitdol-pro** [ReactiveX/RxSwift#2174]
In Rxjava, there is a method blockingGet, blockingFirst
So, the result can be retrived like await of Promise
val result = maybeFunc().blockingGet()
Is there a simiar way in RxSwift?

Thank you in advance

**Comment by freak4pc** [comment]
There isn’t. You can use a BehaviorSubject or
BehaviorRelay to get that behavior but that isn’t recommended generally unless you have no other choice. The paradigm in Reactive Programming is dealing with a stream of many values as a whole and not pluck out a specific value and dealing with it imperatively.

If you have more questions, you can join our slack. http://slack.rxswift.org

**Comment by bitdol-pro** [comment]
> There isn’t. You can use a BehaviorSubject or
> BehaviorRelay to get that behavior but that isn’t recommended generally unless you have no other choice. The paradigm in Reactive Programming is dealing with a stream of many values as a whole and not pluck out a specific value and dealing with it imperatively.
> 
> If you have more questions, you can join our slack. http://slack.rxswift.org

Thank you very much!!
