### ISSUE TITLE
Add observer for tabBarController(_:,shouldSelect:) delegate method

### ISSUE THREAD

**Issue by OmarPedraza** [ReactiveX/RxSwift#2175]
**Short description of the issue**:
`UITabBarController` has observers just for its delegate methods without a return value.

In this case, I've already added [an observable](https://github.com/OmarPedraza/RxSwift/commit/b6be173c5fffa080632d476f57c40255991c7e38) just for `tabBarController(_:,shouldSelect:)`, but we can discuss if this approach is correct and if it can be applied to other delegate method of other classes.

**Expected outcome**:
The observable I've added returns both method's return value (a boolean) and the view controller which should be selected (or not).

**Platform/Environment**
  - [x] iOS
  - [ ] macOS
  - [x] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey Omar, so sorry for the delay. Just catching up on some of the issues here. 
My main issue here is that I'm not sure how popular this addition would be, and it seems rather simple to make it work by yourself by delegate forwarding.

WDYT?
