### ISSUE TITLE
By having UIWebView extension, will causing build app not appear in iTunes connect

### ISSUE THREAD

**Issue by uypanha** [ReactiveX/RxSwift#2178]
*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

  By having UIWebView extension, will causing build app not appear in iTunes connect

**Expected outcome**:

 UIWebView extension should be completely removed as it's deprecated in iOS.

**What actually happens**:

  causing build app not appear in iTunes connect

**Self contained code example that reproduces the issue**:

```swift
 UIWebView+Rx.swift
 RxWebViewDelegateProxy.swift
 Deprecated.swift
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Latest releases removed UIWebView, a long time ago. Please fill the issue template next time :)

**Comment by uypanha** [comment]
Just noticed it, thanks for your quick support.. :)
