### ISSUE TITLE
Rxswift creating problem to run unit test cases

### ISSUE THREAD

**Issue by ponnapallisurendra** [ReactiveX/RxSwift#2179]
<img width="959" alt="Screenshot 2020-05-07 at 2 07 21 PM" src="https://user-images.githubusercontent.com/14892746/81273475-8d513a80-906c-11ea-8fc9-bac00c1ff300.png">

If I run unit/uitest cases it is showing errors
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
5.1.1
**Platform/Environment**

   iOS
  

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:
11.2.1
```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey :) 
I'm not too sure why this happens but note that in the release note we mention we won't actively provide support for Xcode 10 anymore since it's over a year old and too expensive to maintain, work-wise (and Xcode 12 will probably go out soon).

**Comment by ponnapallisurendra** [comment]
@freak4pc I am not using the x code 10, I am using the x code version 11.2.1

**Comment by MobanMichael** [comment]
@freak4pc , I am also facing similar issue and my Xcode version is Version 11.4.1 (11E503a)

**Comment by freak4pc** [comment]
SPM or CocoaPods ? Can you share a repro ? 
I’m running 11.4.1 with no issues with CocoaPods.

**Comment by freak4pc** [comment]
@ponnapallisurendra @MobanMichael ?

**Comment by freak4pc** [comment]
No reply, closing.

**Comment by MobanMichael** [comment]
Sorry about late reply. We added all other frameworks in Pods file in test targets and that resolved the issue. It doesn't seems like issue with Rx Swift.
