### ISSUE TITLE
Observable: unexpected behaviour

### ISSUE THREAD

**Issue by SlavinskiySergey** [ReactiveX/RxSwift#2180]
**Code below reproduced the issue:**

```
import RxSwift
import RxCocoa

example("Test") {
    
    struct TableItemViewModel {
        let didSelectStream = PublishSubject<Void>()
        let valueStream = ReplaySubject<Bool>.create(bufferSize: 1)
        
        let selected: Observable<Bool>
        let deselected: Observable<Bool>
        
        let bag = DisposeBag()
        
        init(selectedObservable: Observable<Bool>) {
            selectedObservable
                .bind(to: valueStream)
                .disposed(by: bag)

            self.selected = didSelectStream
                .withLatestFrom(valueStream)
                .filter { !$0 }
            
            self.deselected = didSelectStream
                .withLatestFrom(valueStream)
                .filter { $0 }
        }
    }
    
    let source = BehaviorSubject(value: false)
    
    let item = TableItemViewModel(selectedObservable: source)
        
    let bag = DisposeBag()
    
    item.selected
        .map { _ in true }
        .bind(to: source)
        .disposed(by: bag)
    
    item.deselected
        .map { _ in false }
        .bind(to: source)
        .disposed(by: bag)
    
    source
        .bind { print("value: \($0)") }
        .disposed(by: bag)
    
    item.didSelectStream.onNext(())
}

```

It prints in console extra _false_ value which lead to incorrect state of _source_ variable:

```
--- Test example ---
value: false
value: true
value: false
```

Could you explain me why?

**P.S.**  In production if I add some delay then it would fix the issue: 

```
selectedObservable
   .delay(..., scheduler: ...)
   .bind(to: valueStream)
   .disposed(by: bag)
```

**Comment by dimitris-c** [comment]
Hi, this is the correct behaviour of `BehaviorSubject` as it will send the last (or initial) value when you subscribe to it.

If you have more questions, you can join the slack channel. http://slack.rxswift.org

**Comment by SlavinskiySergey** [comment]
@dimitris-c  sorry, but it looks like you misunderstood me.

I didn't mean initial _false_ value (that's true that `BehaviorSubject` send the last value when you subscribe on it). I asked about the reason why I saw last (3rd) _false_ value in console.

**Please pay attention what happens in example above**:
1. `BehaviorSubject` has initial _false_ value.
2. call of `item.didSelectStream.onNext(())` change two things:
a. `valueStream` inside `TableItemViewModel` has new inner value: _true_
b.` self.selected` inside `TableItemViewModel` sends all subscribers same _true_ value
3. **(What I mean when wrote 'Unexpected behaviour')** `self.deselected` inside `TableItemViewModel` somehow sends all subscribers value _false_ (I haven't any idea why) . Then `BehaviorSubject` occurs 3rd value which is _false_.

**Comment by dimitris-c** [comment]
Hey @SlavinskiySergey 
So `selected` and `deselected` bind to `source` and `source` is essentially the value to be used when didSelectStream emits an element, selected and deselected cycle back to source...

So you start with initial value of `false`, this will trigger the `selected` stream which in turn will bind the source to `true` (latest value) the deselected stream will go through the latest value which and will bind the `source` to `false`... If you put the `deselected` bind before the `selected` you will see the same issue reversed...

I believe this is not an issue with RxSwift but how you've constructed your streams. As with my previous comment please do use the slack channel -  http://slack.rxswift.org - for "how to/weird" behaviours.
