### ISSUE TITLE
Replacement of UIWebView for WKWebView

### ISSUE THREAD

**Issue by lazaro10** [ReactiveX/RxSwift#2183]
**Short description of the issue**:
Hello, you can include in your fix the replacement of UIWebView for WKWebView, some unit tests of yours still use UIWebView, and as we use Carthage to manage our dependencies, every project is included in our project, and apple is blocking us when we try to submit to store.

**Expected outcome**:

Able to send our app

**What actually happens**:

Apple is blocking applications that use UIWebView

**Self contained code example that reproduces the issue**:

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

5.1.1

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

11.4.1

**Installation method**:
  - [ ] CocoaPods
  - [ x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [x ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  - [ ] just starting
  - [ ] I have a small code base
  - [ x] I have a significant code base

**Comment by freak4pc** [comment]
UIWebView isn’t used in RxSwift at all since 5.1.0. This might be a different dependency you have.

**Comment by celian-m** [comment]
UIWebview References are in RxCocoa

**Comment by freak4pc** [comment]
No they’re not since 5.1.0. See other comments.
