### ISSUE TITLE
RxSwift 5.1.1 and Carthage issues

### ISSUE THREAD

**Issue by paulBuchanan** [ReactiveX/RxSwift#2185]
**Short description of the issue**:

Using RxSwift 5.1.1 with Carthage causes the debugger to crash when it hits a breakpoint in Xcode 11.4.1 if I build the libraries with:

   carthage update --platform iOS --no-use-binaries

Debugger crashes with: 

Message from debugger: The LLDB RPC server has exited unexpectedly. Please file a bug if you have reproducible steps.

If instead I use this and take the pre-compiled binaries: 

   carthage update --platform iOS

I get the following warning when the debugger hits a breakpoint:

warning: Swift error in fallback scratch context: error: virtual filesystem overlay file '/Users/freak4pc/Library/Developer/Xcode/DerivedData/Rx-hfzwoptkeprdnlcyedtxjnwyojdp/Build/Intermediates.noindex/ArchiveIntermediates/RxCocoa/IntermediateBuildFilesPath/Rx.build/Release-iphoneos/RxCocoa.build/all-product-headers.yaml' not found

However, the debugger does not crash.

**Expected outcome**:

  Debugger does not crash, and virtual filesystem overlay file warning does not display.

**Platform/Environment**

  - [X ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  11.4.1
```

**Installation method**:
  - [ ] CocoaPods
  - [ X] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X ] yes (11.4.1, 11.4, 11.3.1, 10.3)  
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ X] I have a significant code base

**Comment by freak4pc** [comment]
Hey @paulBuchanan - given this doesn't occur with SPM or CocoaPods, I think this bug fits better within Carthage or Swift's bug tracker, and doesn't seem like an RxSwift issue by itself.

**Comment by cmxconsulting** [comment]
any news  please ? It really seems due to  compilation parameters (with Carthage indeed).

**Comment by freak4pc** [comment]
Again, this seems like a Carthage-specific issue and not related to this project directly. If you have a specific idea on how to resolve it from the Carthage side, I'll try my best to help.

**Comment by cmxconsulting** [comment]
Hello @freak4pc @paulBuchanan , i think i found it. It's working fine for me.
This seems to be related to the Apple Clang Enable Modules (c objective c). 
By switching to "No" it's working.
I'm using RxSwift 5.1.0

I rebuilt it from Carthage by doing this :
carthage checkout
sed -i '' -e "s|CLANG_ENABLE_MODULES = YES;|CLANG_ENABLE_MODULES = NO;|g" Carthage/Checkouts/RxSwift/Rx.xcodeproj/project.pbxproj 
carthage build --platform ios --no-use-binaries

Here are the consequences : https://stackoverflow.com/questions/36265490/turning-off-clang-enable-module-debugging-consequences

I can do a pull request if your want.
Please let me know.

Thank you.
Chris.

**Comment by freak4pc** [comment]
Thanks for the research and glad you found a resolution to this.

Unfortunately turning off this flag just to support Carthage isn't something I feel comfortable doing. The consequences are quite large here. If you have a different solution around this I'll be happy to hear. But otherwise perhaps opening a Carthage bug would be a better idea.

Thank you!
Shai
