### ISSUE TITLE
-[_UIButtonBarLayoutMetrics modelMap]: unrecognized selector sent to instance 0x28370e380

### ISSUE THREAD

**Issue by Insfgg99x** [ReactiveX/RxSwift#2186]
[YxLoginViewController.swift.zip](https://github.com/ReactiveX/RxSwift/files/4665720/YxLoginViewController.swift.zip)

**Comment by freak4pc** [comment]
Hey @Insfgg99x. Please open a new thread filling the full issue template.
We don't answer partial issues.

Thanks!

**Comment by freak4pc** [comment]
Also, please reduce your issue to the minimal version of it, not 500-line file :)
