### ISSUE TITLE
error: dyld: Library not loaded

### ISSUE THREAD

**Issue by LLLX77** [ReactiveX/RxSwift#219]
I "import RxCocoa" in my project, build succeeded, but there is an error:

dyld: Library not loaded: @rpath/libswiftCoreLocation.dylib
  Referenced from: /Users/rmbp/Library/Developer/Xcode/DerivedData/RxSwift_sample-dlbsrmyebyjcfwakrndatysrjqir/Build/Products/Debug-iphonesimulator/RxCocoa.framework/RxCocoa
  Reason: image not found

any idea?

my Xcode version is 7.1

**Comment by yury** [comment]
Can you show your `Podfile`?

**Comment by LLLX77** [comment]
the CocoaPods version is 0.39.0, and my Podfile:

    use_frameworks!

    pod 'RxSwift', '~> 2.0.0-beta'
    pod 'RxCocoa', '~> 2.0.0-beta'
    pod 'RxBlocking', '~> 2.0.0-beta'

**Comment by yury** [comment]
Can't reproduce it... Can you help with sample project?

**Comment by kzaher** [comment]
Hi @LLLX77 ,

I think that the problem you are facing is that Xcode doesn't think your app contains Swift code and therefore doesn't deploy Swift standard library with wrappers for standard frameworks.

Is you app Objc only?

**Comment by LLLX77** [comment]
Hi @kzaher 
all my code is swift, maybe something wrong with the Xcode version or other, I solved this problem by copy all files to another new empty project, then it works well.

**Comment by zkid18** [comment]
Hi, I have the same mistake. If you are using Carthage for installing lib, don't forget to add framework to external libraries)

**Comment by serg-vinnie** [comment]
Have same problem if I create Console App

**Comment by XReyRobert** [comment]
+1

**Comment by hitendradeveloper** [comment]
My Error Was

> Library not loaded: @rpath/RxRelay.framework/RxRelay

In My case line highlighted in below screenshot was added manually in input files sections

> "$(SRCROOT)/Carthage/Build/iOS/RxRelay.framework"

I added this line and project is working as expected

![Screenshot 2019-12-12 at 12 23 41 PM](https://user-images.githubusercontent.com/9197369/70689474-66b7ef00-1cda-11ea-99fb-95b060d14c8b.png)

**Comment by freak4pc** [comment]
@hitendradeveloper this isn’t the same problem and this is a 4 year old thread :)
