### ISSUE TITLE
[Mac] No such module 'RxSwift'

### ISSUE THREAD

**Issue by MauriceArikoglu** [ReactiveX/RxSwift#2193]
**Short description of the issue**:

Building an App with Catalyst fails.
RxSwift is integrated manually as git submodule.
Works fine building for iOS platform, 
but when selecting Mac as target "No such module RxSwift" error is thrown.

**Expected outcome**:

App should build regardless of platform.

**What actually happens**:

Building an App with Catalyst fails.
RxSwift is integrated manually as git submodule.
Works fine building for iOS platform, 
but when selecting Mac as target "No such module RxSwift" error is thrown.

**Self contained code example that reproduces the issue**:

```swift
  import RxSwift
  
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  latest 5.1.1

**Platform/Environment**

  - [x ] iOS
  - [x ] macOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro

**Xcode version**:

```
  11.5
```

**Installation method**:
  - [x] Git submodules

**I have multiple versions of Xcode installed**:
  - [x] no

**Level of RxSwift knowledge**:
  - [x] I have a significant code base, although it might be related to insufficient knowledge about new Mac Catalyst

**Comment by MauriceArikoglu** [comment]
The setup described here (https://github.com/shinsuk/XCFramework-Link-Issue) fits my project setup. Could this be related? Suggested workarounds do not work though.

**Comment by freak4pc** [comment]
Hey @MauriceArikoglu - could you please provide a quick repro project here? Thanks.

**Comment by MauriceArikoglu** [comment]
@freak4pc I sent you an invite to collaborate on a private repository with a spike project. The issue is reproducible 100% of the time targeting "My Mac". iOS works fine as usual. Its probably my fault here, nevertheless would be very kind of you to look into it. Thank you in advance

**Comment by freak4pc** [comment]
Hey Maurice, something seems broken in your submodule setup:

```
Submodule 'ThirdParty/RxSwift' (https://github.com/ReactiveX/RxSwift.git) registered for path 'ThirdParty/RxSwift'
fatal: remote error: upload-pack: not our ref 76b37b19d2e4dfc8af12f317058fe1bcd0a1e659
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'ThirdParty/RxSwift', but it did not contain 76b37b19d2e4dfc8af12f317058fe1bcd0a1e659. Direct fetching of that commit failed.
```

Regardless, It would be hard for me to spend too much time looking into this since its not a bug in the code itself, but some sort of a configuration issue. 

It might be better if you join our Slack and I'll try to help out there. (http://slack.rxswift.org)

Thanks!

**Comment by MauriceArikoglu** [comment]
@freak4pc will do so! I will reach out to you via PM. Thanks a lot for the effort
