### ISSUE TITLE
RxSwift binary releases are not forward compatible as they don't declare BUILD_LIBRARY_FOR_DISTRIBUTION

### ISSUE THREAD

**Issue by borland** [ReactiveX/RxSwift#2196]
If you take an older binary framework release from github, and then use it on a version of Xcode that has a newer swift compiler (e.g. swift 5.1 vs swift 5.2) you get the compile error:

Module compiled with Swift 5.x cannot be imported by the Swift 5.y compiler

**Expected outcome**:

The code will compile

**What actually happens**:

Failure to compile with error: `Module compiled with Swift 5.x cannot be imported by the Swift 5.x compiler`

You can repro this if you download the current RxSwift.framework binary release from github, and import it into any iOS project using Xcode 12 beta - or if you download an older (5.0.1) binary release and import it into a project in Xcode 11.5

This is easy to fix; RxSwift should define BUILD_LIBRARY_FOR_DISTRIBUTION = YES; in the pbxproj, and there are a couple of non-public `init` methods that need to be made public because they are overriden in derived classes by public ones.

Pull request here:

https://github.com/ReactiveX/RxSwift/pull/2197

With the changes in the above PR, I can build a binary RxSwift.framework using Xcode11.5 (swift 5.2), and then import it into a project using Xcode12 beta (swift 5.3) and it works correctly.
Without those changes, we get the "Module cannot be imported by the new compiler" error

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

Probably all platforms but my app only runs on iOS so I do not have a good test harness available for the other platforms.

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

11.5

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

Note: People who install RxSwift via CocoaPods, Carthage (and SPM?) should be unaffected, as I believe those cause the RxSwift source code to be downloaded and built locally, thus the compiler versions of RxSwift and the host app should always match. When using a pre-built binary framework though this issue becomes important

**Comment by freak4pc** [comment]
Lets keep the discussion running in #2197
