### ISSUE TITLE
deallocate(capacity:)' is unavailable: Swift currently only supports freeing entire heap blocks, use deallocate() instead

### ISSUE THREAD

**Issue by kevinabram111** [ReactiveX/RxSwift#2200]
**Short description of the issue**:
A red error message shows up with a message of `deallocate(capacity:)' is unavailable: Swift currently only supports freeing entire heap blocks, use deallocate() instead` on the code `key.deallocate(capacity: 1)` in the file `CurrentThreadScheduler.swift`

**Expected outcome**:
The application will not produce error

**What actually happens**:
The application produces an error with a message `deallocate(capacity:)' is unavailable: Swift currently only supports freeing entire heap blocks, use deallocate() instead`

**Self contained code example that reproduces the issue**:

```swift
`key.deallocate(capacity: 1)` in line 54 in file `CurrentThreadScheduler.swift` on `RxSwift`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

'RxSwift', '5.1.0', 
'RxCocoa', '5.1.0'

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode version 11.5 (11E608c) & Swift 5
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
That code has been fixed almost a year and a half ago: https://github.com/ReactiveX/RxSwift/blame/a580d07ed002217fd91d8446c3a852486e9beefa/RxSwift/Schedulers/CurrentThreadScheduler.swift#L53

I suspect you're not on the version you think you are. Can you check your dependencies again?

**Comment by kevinabram111** [comment]
I see, there is some problem with my installation of the pod file. But I have finally found the problem, Thank You 🙇‍♂️
