### ISSUE TITLE
.rx.observeWeakly fails for KVO-compliant key path OperationQueue.operationCount on macOS 10.15+

### ISSUE THREAD

**Issue by DivineDominion** [ReactiveX/RxSwift#2204]
**Short description of the issue**:

When you use KVO to subscribe to `OperationQueue.operationCount` changes, this will fail on macOS 10.15:

    backgroundQueue.rx
            .observeWeakly(Int.self, "operationCount")
            .subscribe(onNext: {
                print("reached the subscription:", $0) // never happens
            })

It's probably related to the deprecation of the `operationCount` property. The Objective-C header points to `progress.completedUnitCount` which was introduces in 10.15.

Manual KVO and KVC work fine, though. The `class_getProperty` check fails even though there's a KVO-compliant path:

https://github.com/ReactiveX/RxSwift/blob/6b2a406b928cc7970874dcaed0ab18e7265e41ef/RxCocoa/Foundation/NSObject%2BRx.swift#L466-L468

**Expected outcome**:

A `.next` event would go through.

**What actually happens**:

The change event doesn't reach the Observer and an unhandled error is logged instead:

> 2020-07-14 17:51:55.523075+0200 RxTestApp[64237:1304657] <RxTestApp.AppDelegate: 0x6000002408c0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.

**Self contained code example that reproduces the issue**:

See attached Xcode project:  
**[Archive.zip](https://github.com/ReactiveX/RxSwift/files/4919849/Archive.zip)**

```swift
import Cocoa
import RxSwift
import RxCocoa

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    @IBOutlet var window: NSWindow!

    let disposeBag = DisposeBag()
    let backgroundQueue = OperationQueue()

    func applicationDidFinishLaunching(_ aNotification: Notification) {
        backgroundQueue.addObserver(self, forKeyPath: "operationCount", options: .new, context: nil)
        backgroundQueue.rx
            .observeWeakly(Int.self, "operationCount")
            .subscribe(onNext: {
                print("reached the subscription:", $0) // never happens
            })
            .disposed(by: disposeBag)
        backgroundQueue.addOperation { print("operation 1") }
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Version 5.1.1

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
- Version 12.0 beta 2 (12A6163b)
- Version 11.5 (11E608c)
```

**Comment by freak4pc** [comment]
If you have any idea for a fix, I'll be happy to accept it.
If it's isolated to a single property it would be quite hard getting a fix for it, but I'll take a look.

Thanks for reporting!

**Comment by DivineDominion** [comment]
@freak4pc The implementation details of Rx go a bit over my head here, so I only have an approach for discussion and cannot offer a PR out of the box.

E.g. apparently, there are KVO-able key paths that are not represented as properties in the way that `class_getProperty` recognizes them. This is one instance, but I don't know how many other key paths of the Cocoa API are implemented in such a way.

So the `class_getProperty` function returns `nil` here for some reason. But Key-Value-Coding still works. My sample app demonstrates that KVO works as well. The whole `class_getProperty` result is only used to figure out if the reference should be weak or strong, at seems:

```
        let property = class_getProperty(object_getClass(target), propertyName)
        if property == nil {
            return Observable.error(RxCocoaError.invalidPropertyName(object: target, propertyName: propertyName))
        }
        let propertyAttributes = property_getAttributes(property!)

        // should dealloc hook be in place if week property, or just create strong reference because it doesn't matter
        let isWeak = isWeakProperty(propertyAttributes.map(String.init) ?? "")
```

After that, neither `property` nor `propertyName` are used. 

My suggestion would be to flip the existing code around and instead of guarding against `nil`, introduce 2 valid cases:

```
        let isWeak: Bool
        if let property = class_getProperty(object_getClass(target), propertyName) {
            let propertyAttributes = property_getAttributes(property)
            isWeak = isWeakProperty(propertyAttributes.map(String.init) ?? "")
        } else {
            isWeak = true // false? Use a different heuristic?
        }
```

That's the furthest I can reason within the confines of RxCocoa :)

**Comment by DivineDominion** [comment]
Just a gentle follow-up request for feedback if I'm thinking about this in the wrong way @freak4pc

**Comment by freak4pc** [comment]
I don't have a strong idea around this unfortunately. There is a new `observe` which takes a KeyPath (It's on the RxSwift 6 branch). Do you mind giving that one a go?

**Comment by yourshinsuke** [comment]
iOS 12?

**Comment by loyal365** [comment]
ok then im buying it

**Comment by freak4pc** [comment]
Closing due to not activity for over two months.

**Comment by DivineDominion** [comment]
@freak4pc Since RxSwift 6.x is now public, I tried the new stuff. It's not allowing `observeWeakly`, though. A non-weak String-based KVO observation works too. The weak one still doesn't.

```swift
class AppDelegate: NSObject, NSApplicationDelegate {

    @IBOutlet var window: NSWindow!

    let disposeBag = DisposeBag()
    let backgroundQueue = OperationQueue()

    func applicationDidFinishLaunching(_ aNotification: Notification) {
        backgroundQueue.addObserver(self, forKeyPath: "operationCount", options: .new, context: nil)
        backgroundQueue.rx
            .observe(\.operationCount)
            .subscribe(onNext: {
                print("reached the KeyPath subscription:", $0)
            })
            .disposed(by: disposeBag)
        backgroundQueue.rx
            .observe(Int.self, "operationCount")
            .subscribe(onNext: {
                print("reached the strong string path subscription:", $0) // never happens
            })
            .disposed(by: disposeBag)
        backgroundQueue.rx
            .observeWeakly(Int.self, "operationCount")
            .subscribe(onNext: {
                print("reached the weak string path subscription:", $0) // never happens
            })
            .disposed(by: disposeBag)
        backgroundQueue.addOperation { print("operation 1") }
    }

    override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if keyPath == "operationCount" {
            print("manual OP", change) // this works fine
        }
    }
}
```

The output:

```
reached the KeyPath subscription: 0
reached the strong string path subscription: Optional(0)
Unhandled error happened: Object `<NSOperationQueue: 0x100f04ad0>{name = 'NSOperationQueue 0x100f04ad0'}` doesn't have a property named `operationCount`.
reached the strong string path subscription: Optional(1)
reached the KeyPath subscription: 1
2021-02-26 09:27:20.451780+0100 RxTestApp[18352:1682351] <RxTestApp.AppDelegate: 0x600000228f40>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: operationCount
Observed object: <NSOperationQueue: 0x100f04ad0>{name = 'NSOperationQueue 0x100f04ad0'}
Change: {
    kind = 1;
    new = 1;
}
Context: 0x0
```

I looked at other options, i.e. if `class_getProperty` fails because it's not a declared property, would `object_getClass(target)?.keyPathsForValuesAffectingValue(forKey: propertyName)` return something? Apparently, no.

You can verify that a key path is Key-Value _Codable_, but not observable, with `value(forKey:)` and `setValue(_:forKey:)`. Even that right out raises a runtime exception when the key path doesn't exist.

Checking for the selector via `responds(to: Selector(propertyName))` works, but again, that's useful for KVC, not KVO.

So I could make the OperationQueue case run, if needed, but this would produce a lot of false-positives for key paths that are not key-value observable and thus would never fire events.

The patch would be:

```diff
--- RxCocoa/Foundation/NSObject+Rx.swift	2021-02-13 14:06:41.000000000 +0100
+++ RxCocoa/Foundation/NSObject+Rx.swift	2021-02-26 09:55:58.000000000 +0100
@@ -488,14 +488,19 @@
         let propertyName = keyPathSections[0]
         let remainingPaths = Array(keyPathSections[1..<keyPathSections.count])

-        let property = class_getProperty(object_getClass(target), propertyName)
-        if property == nil {
+        // should dealloc hook be in place if week property, or just create strong reference because it doesn't matter
+        let propertyIsWeak: Bool
+        if let property = class_getProperty(object_getClass(target), propertyName) {
+            // Key path corresponds to a @property declaration
+            let propertyAttributes = property_getAttributes(property)
+            propertyIsWeak = isWeakProperty(propertyAttributes.map(String.init) ?? "")
+        } else if target.responds(to: Selector(propertyName)) {
+            // Key path is observable but without property declaration
+            propertyIsWeak = false
+        } else {
+            // Not found at all
             return Observable.error(RxCocoaError.invalidPropertyName(object: target, propertyName: propertyName))
         }
-        let propertyAttributes = property_getAttributes(property!)
-
-        // should dealloc hook be in place if week property, or just create strong reference because it doesn't matter
-        let isWeak = isWeakProperty(propertyAttributes.map(String.init) ?? "")
         let propertyObservable = KVOObservable(object: target, keyPath: propertyName, options: options.union(.initial), retainTarget: false) as KVOObservable<AnyObject>

         // KVO recursion for value changes
@@ -522,7 +527,7 @@
                     ? Observable.just(nextTarget)
                     : observeWeaklyKeyPathFor(nextObject!, keyPathSections: remainingPaths, options: options)

-                if isWeak {
+                if propertyIsWeak {
                     return nextElementsObservable
                         .finishWithNilWhenDealloc(nextObject!)
                 }
~
```

To be honest, I don't know if the happy path at the moment applies to only KVO'able properties.

**Comment by freak4pc** [comment]
@DivineDominion Thanks for debugging this. I suggest moving your entire comment and patch into a new PR if possible, so it's easier to parse through and share with other members. Thanks!
