### ISSUE TITLE
Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).

### ISSUE THREAD

**Issue by xiaoaifresh** [ReactiveX/RxSwift#2205]
**Short description of the issue**:
RxSwift won't build with Carthage under XCode 11.5. I'm getting this error:
![image](https://user-images.githubusercontent.com/63740082/87456318-95bd7880-c5bb-11ea-97b2-6a9959e9ebe3.png)

**Expected outcome**:

The project would build

**What actually happens**:

I'm getting build error.

**Self contained code example that reproduces the issue**:
Cartfile:
  `github "ReactiveX/RxSwift" ~> 5.1`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
Version 11.5 (11E608c)
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
It builds, it just does it from source. We only upload binaries in new releases. I imagine the upcoming release will be with 11.5.

**Comment by entotsu** [comment]
Oh, May be that's true.
