### ISSUE TITLE
Archive issue Xcode 12 beta

### ISSUE THREAD

**Issue by ElenaVielva** [ReactiveX/RxSwift#2208]
**Short description of the issue**:

I failed to archive my app on 12.0 beta 2 with RxSwift library

**Expected outcome**:

  My app has the same warnings as if I was compiling from Xcode 11 and no build errors.

**What actually happens**:

  I get this error:
 ```
Command CompileSwift failed with a nonzero exit code
 ```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  12 beta 2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes Xcode 11.4.1 , Xcode 12 beta 2
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting (but working on an app that has already RxSwift implemented on several screens)
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey. Based on your output it's related to SwiftyJSON and not RxSwift.

**Comment by ElenaVielva** [comment]
Forgot to mention that this is not the only error I get when I try to archive, other libraries also have the exact same issue:
https://github.com/SwiftyJSON/SwiftyJSON/issues/1066
https://github.com/Alamofire/Alamofire/issues/3240

**Comment by ElenaVielva** [comment]
> Hey. Based on your output it's related to SwiftyJSON and not RxSwift.

Sorry, I am having same issue in several libraries and I'm creating the issues in all of them, so I have copied the wrong output in this one. Thanks for noticing!

**Comment by freak4pc** [comment]
Given it's a beta version of Xcode and a repo-wide issue, I think this lands on Apple's desk and not ours. 

My instinct is to close this for now, and if it's not solved closer to GM we can address it. 

One of the other posts mentions manually bumping the deployment target might help, so you can also fork this project and try to do that manually, but we won't be doing that for the time being (See #2207)

**Comment by ElenaVielva** [comment]
I don't want to bump the deployment target, I'm already on iOS 10 since one of the libraries recently moved to that, and I don't want to skip more users.

Let's see what happens when a new beta is released 🤔

**Comment by freak4pc** [comment]
Did you happen to check on Beta 3?

**Comment by dingtianran** [comment]
@freak4pc Didn't get fixed at Beta 3 either

**Comment by ElenaVielva** [comment]
As @dingtianran said, same error on Beta 3

**Comment by freak4pc** [comment]
Unfortunately nothing that I see we can do here, espceially if it's approved to affect many reepos
If you havene't, can you please file a Feeedback Assistance with RxSwift and the other repos affected by this?

**Comment by freak4pc** [comment]
I just archived on Xcode 12 beta 6 with no issues. Could you confirm @ElenaVielva ?

**Comment by freak4pc** [comment]
Closing due to no reply. Feel free to comment if you found anything beyond discussed here.

**Comment by Efebyts** [comment]
> 
> 
> **Short description of the issue**:
> 
> 
> 
> I failed to archive my app on 12.0 beta 2 with RxSwift library
> 
> 
> 
> **Expected outcome**:
> 
> 
> 
>   My app has the same warnings as if I was compiling from Xcode 11 and no build errors.
> 
> 
> 
> **What actually happens**:
> 
> 
> 
>   I get this error:
> 
>  ```
> 
> Command CompileSwift failed with a nonzero exit code
> 
>  ```
> 
> 
> 
> 
> 
> **RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
> 
> 
> 
>   _version or commit here_
> 
> 
> 
> **Platform/Environment**
> 
> 
> 
>   - [x] iOS
> 
>   - [ ] macOS
> 
>   - [ ] tvOS
> 
>   - [ ] watchOS
> 
>   - [ ] playgrounds
> 
> 
> 
> **How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
> 
> 
> 
>   - [x] easy, 100% repro
> 
>   - [ ] sometimes, 10%-100%
> 
>   - [ ] hard, 2% - 10%
> 
>   - [ ] extremely hard, %0 - 2%
> 
> 
> 
> **Xcode version**:
> 
> 
> 
> ```
> 
>   12 beta 2
> 
> ```
> 
> 
> 
> :warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:
> 
> 
> 
> **Installation method**:
> 
>   - [x] CocoaPods
> 
>   - [ ] Carthage
> 
>   - [ ] Git submodules
> 
> 
> 
> **I have multiple versions of Xcode installed**:
> 
>   (so we can know if this is a potential cause of your issue)
> 
>   - [x] yes Xcode 11.4.1 , Xcode 12 beta 2
> 
>   - [ ] no
> 
> 
> 
> **Level of RxSwift knowledge**:
> 
>   (this is so we can understand your level of knowledge
> 
>     and formulate the response in an appropriate manner)
> 
>   - [x] just starting (but working on an app that has already RxSwift implemented on several screens)
> 
>   - [ ] I have a small code base
> 
>   - [ ] I have a significant code base
> 
> 

Aa
