### ISSUE TITLE
Empty Observable doesn't make CombineLatest complete

### ISSUE THREAD

**Issue by oteronavarretericardo** [ReactiveX/RxSwift#2211]
**Short description of the issue**:
When one of the Observables used in CombineLatest completes empty. CombineLatest doesn't complete. 
I couldn't find what's the expected behavior for this case on [reactive](http://reactivex.io/documentation/operators/combinelatest.html) but [RxJS](https://rxjs-dev.firebaseapp.com/api/index/function/combineLatest) reads:

> if some Observable does not emit a value but completes, resulting Observable will complete at the same moment without emitting anything, since it will be now impossible to include value from completed Observable in resulting array.

By looking at the test suite that's not how RxSwift.CombineLatest works, see the attached code.

**Expected outcome**:
Because e0 finishes empty. I expect CombineLatest to finish @210

**What actually happens**:

CombineLatest finishes @410 even though impossible to include a value from e0 in the result

**Self contained code example that reproduces the issue**:
```Swift 
func testCombineLatest_3Ary_notMatchingSpec() {
        let factories: [(TestableObservable<Int>, TestableObservable<Int>, TestableObservable<Int>) -> Observable<EquatableArray<Int>>] =
            [
                { e0, e1, e2 in
                    Observable<Int>.combineLatest([e0, e1, e2].map { $0.asObservable() }).map { EquatableArray($0) }
                },
                { e0, e1, e2 in
                    Observable.combineLatest(e0, e1, e2).map { EquatableArray([$0.0, $0.1, $0.2]) }
                },
            ]
        for factory in factories {
            let scheduler = TestScheduler(initialClock: 0)
            let e0 = scheduler.createHotObservable([
                .next(150, 1), 
                .completed(210)
                ])
            let e1 = scheduler.createHotObservable([
                .next(150, 1), 
                .next(220, 2),
                .completed(400)
                ])
            let e2 = scheduler.createHotObservable([
                .next(150, 1), 
                .next(230, 3),
                .next(410, 4),
                .completed(500)
                ])
            
            let res = scheduler.start {
                factory(e0, e1, e2)
            }
                        
            XCTAssertEqual(res.events, [
                .completed(410)
                ])
            
// i was expecting this:
//            XCTAssertEqual(res.events, [
//                .completed(210)
//                ])
//
            
            XCTAssertEqual(e0.subscriptions, [Subscription(200, 210)])
            XCTAssertEqual(e1.subscriptions, [Subscription(200, 400)])
            XCTAssertEqual(e2.subscriptions, [Subscription(200, 410)])
        }
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
Master::61dabd4

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
Version 11.3.1 (11C505)

**Installation method**:
  No installed, ran directly from workspace

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
I think it's a decent behavior to add (the specific case of immediate completion with no emitted values), even though it doesnt seem to be the case in Rx.NET, for example. This is a breaking change, though, so It'll have to wait for RxSwift 6.

**Comment by oteronavarretericardo** [comment]
@freak4pc By studying more about RxSwift i came across [post](https://github.com/ReactiveX/RxSwift/issues/1666) with a comment from @kzaher: 
` The reason why we shouldn't complete it is because even though sequence couldn't theoretically generate an element in some cases, it could always generate error.`
I believe the rational applied there also applies to this case. With that in mind, seems the current behavior although different from other Rx implementations, has a _very good reason_ to be the way it is.

**Comment by freak4pc** [comment]
That's an interesting case. Basically a1 could complete with no elements and a2 could error out, making the combineLatest as a whole error out.

I think that eventually Rx is a very fancy state machine and in this case there is an unhandled possible state (the error one), so the right thing to do might be keeping today's behavior.

**Comment by freak4pc** [comment]
After thinking of this some more, I'm going to keep the existing behavior. Thanks for the original suggestion and interesting discussion, though! 🙌
