### ISSUE TITLE
rxswift version 5.1.1 is Compatible with xcode 12.0 beta 3 version 

### ISSUE THREAD

**Issue by virkrishan** [ReactiveX/RxSwift#2213]
So can you tell me   rxswift 5.1.1 is compatible with  xcode 12.0 beta 3 version .beacuse i am getting error .i have attached a screenshot .

**Comment by virkrishan** [comment]
Please reply soon

**Comment by freak4pc** [comment]
This is a Carthage thing. You should just rebuild your dependencies. (don't remember the specifics Carthage command - probably bootstrap or update)

You're using a prebuilt binary did a different version of Swift.
