### ISSUE TITLE
Can't run UI tests on Xcode 11.6

### ISSUE THREAD

**Issue by luigitrevisi** [ReactiveX/RxSwift#2217]
Error when running UI tests on Xcode 11.6

When running UI tests on Xcode 11.6? It fails with this error:
`Multiple commands produce '/Users/myuser/Library/Developer/Xcode/DerivedData/AppName-gxzqnbqdaoihfihikudpyyvdefvs/Build/Intermediates.noindex/RxSwift.build/Debug-iphonesimulator/RxSwift.build/RxSwift.modulemap':
1) Target 'RxSwift' (project 'RxSwift') produces module 'RxSwift'
2) Target 'RxSwift' (project 'RxSwift') produces module 'RxSwift'`

I've tried changing the build system to the legacy one, as suggested in several places, but in that case it returns:
`Missing required module 'RxCocoaRuntime'`

I've also tried looking for some duplicates in the build phase, but everything looks correct.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  5.1.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
```
11.6
```

**I have multiple versions of Xcode installed**:
  - [x] 11.6 and 11.3.1
  - [ ] no

**Level of RxSwift knowledge**:
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
A month with no reply. Closing.
