### ISSUE TITLE
rxswift6 branch fails to archive because of invalid CFBundleShortVersionString 

### ISSUE THREAD

**Issue by sanojnambiar** [ReactiveX/RxSwift#2218]
**Short description of the issue**:

  Invalid CFBundleShortVersionString in rxswift6 branch

**Expected outcome**:

Should be able to achieve using Xcode 12 beta 5+

**What actually happens**:
Xcode fails to validate the build because of invalid CFBundleShortVersionString (6.0.0-beta.1). 
CFBundleShortVersionString should be period separated list of at most three non-negative integers.
Attaching screenshot.
![Screen Shot 2020-08-25 at 4 37 35 PM](https://user-images.githubusercontent.com/852567/91365405-9d7d5900-e7c6-11ea-9f91-931e94634281.png)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  Branch - rxswift6
Commit - 0ce012fe0766def474b84f3f670912b85944b7c0_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12 beta 5

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode 11.6, Xcode 12)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
I've set `CFBundleShortVersionString` to 6.0.0
