### ISSUE TITLE
Type 'RxTimeInterval' (aka 'Double') has no member 'milliseconds'

### ISSUE THREAD

**Issue by klawsachkar** [ReactiveX/RxSwift#2219]
.debounce(.milliseconds(500), scheduler: MainScheduler.instance)

This code is not working anymore, i would like to know in which version the milliseconds was removed from the RXTimeInterval.

Thank you.

**Comment by freak4pc** [comment]
We only answer to detailed bug reports. Please open a new issue outlining the version you have of RxSwift and other needed information.
