### ISSUE TITLE
Is there any way to access `RxSwift.Resources.totalCount` if RxSwift is added via Swift Package Manager?

### ISSUE THREAD

**Issue by HMWDavid** [ReactiveX/RxSwift#2223]
Is there any way to access `RxSwift.Resources.totalCount` if RxSwift is added via Swift Package Manager?

_Originally posted by @haider-kazal in https://github.com/ReactiveX/RxSwift/issues/378#issuecomment-538759530_

**Comment by freak4pc** [comment]
Hey, first of all SPM is still riddled with issues in regards to RxSwift and similar inter-module dependency related frameworks (See https://bugs.swift.org/browse/SR-12303)

About your specific question. If you use a Package.swift file, I believe you can do something like this

```swift
import PackageDescription

let package = Package(
    name: "Foo",
    targets: [
        .target(
            name: "MyApp",
            cSettings: [
                .define("TRACE_RESOURCES", configuration: .debug),
            ]
        )
    ]
    ... etc etc
)
```

I'm not sure if you can do it via Xcode, but it is regardless a SwiftPM issue and not a RxSwift issue so I suggest filing a Feedback Feature Request or Bug Report.

**Comment by realityworks** [comment]
How is this closed? You cannot change these files from xcode, they are in derived data... Can someone please re-open this.

**Comment by freak4pc** [comment]
My comment is quite clear. We support RxSwift, not SPM.

If you try the solution I suggested and it doesn't work, I suggest looking into support related to SPM, as it's not related to RxSwift at all.

**Comment by freemansion** [comment]
would appreciate if someone post a comment with the link with working solution

**Comment by cloverdaniel** [comment]
I got this to work with `swiftSettings`, thusly: 
```
...
targets: [
        .target(
            name: "<target_name>",
            dependencies: ["RxSwift"],
            swiftSettings: [.define("TRACE_RESOURCES", .when(configuration: .debug))]),
    ]
```
