### ISSUE TITLE
shouldChangeTextIn delegate and rx.text conflict

### ISSUE THREAD

**Issue by 460565420** [ReactiveX/RxSwift#2225]
i want use delegate 'shouldChangeTextIn' restrict input, but when i achieve the delegate,the subscribe only print when the textfield begin or end edit.

Do i have any way to make the delegate and subscribe both carried out? 
Thanks a lot.

textField.rx.text.orEmpty.subscribe(onNext: { (text) in
            print(text)
 }).disposed(by: rx.disposeBag)

override func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        return true
}

**Comment by freak4pc** [comment]
Hey, this doesn't seem to be like an issue with RxCocoa itself, but more like a "How do I Do X?" kind of question. To keep our GitHub focused on issues and bugs, please join our Slack and ask and ask your question there: 

http://slack.rxswift.org
