### ISSUE TITLE
Xcode 12 issue - IPHONEOS_DEPLOYMENT_TARGET >= 9.0

### ISSUE THREAD

**Issue by StefaniOSApps** [ReactiveX/RxSwift#2227]
We need to add small changes:
`Showing All Messages The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

**Comment by freak4pc** [comment]
See `rxswift6` branch.

**Comment by alouanemed** [comment]
@freak4pc your response is vague. I've checked that branch and there is no mention of the issue above.

**Comment by freak4pc** [comment]
It's not very vague :) RxSwift 5 will keep supporting iOS 8. 

RxSwift 6 will drop iOS 8 and support iOS 9 and up, so I suggested using that branch.

**Comment by alouanemed** [comment]
Ah, I see. Make sense, Thanks.

I tried that branch but the issue till persist. **Moya/Moya** uses RxSwift and I updated their cart file to use that branch here https://github.com/alouanemed/Moya/blob/master/Cartfile.

**Comment by freak4pc** [comment]
That's strange, I'm using that branch as well. Can you provide a repro?

**Comment by alouanemed** [comment]
Should I update the version to **6** like this : https://github.com/alouanemed/Moya/blob/master/Moya.podspec#L40

**Comment by alouanemed** [comment]
It didn't work, I specified the version to **6.0.0-beta.1**
```
Pre-downloading: `Moya` from `https://github.com/alouanemed/Moya.git`
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    Moya/RxSwift (from `https://github.com/alouanemed/Moya.git`) was resolved to 14.0.0, which depends on
      RxSwift (~> 6.0.0-beta.1)

None of your spec sources contain a spec satisfying the dependency: `RxSwift (~> 6.0.0-beta.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


```

**Comment by freak4pc** [comment]
You talked about Cartfile and now mentioned CocoaPods. I'm confused :)

**Comment by alouanemed** [comment]
I am using Cocoa in my project. Moya/Moya uses Cartfile

**Comment by freak4pc** [comment]
Your Podfile should link directly to the `rxswift6` branch: https://stackoverflow.com/a/39930762

**Comment by alouanemed** [comment]
I don't have RxSwift on my pod, as Moya depends on. If I link rxswift 6 directly to my pod, cocoa will show an error that there several versions.

**Comment by freak4pc** [comment]
I imagine that once the release candidate is out, they'll be able to make a new version of Moya linking to it.

I imagine Moya usage only causes a warning (For iOS 8 usage in RxSwift) and not a compilation error to my understanding.

This is a bit of a transitioning period for many library maintainers, I'm hoping we'll be able to release the B1/RC1 soon officially to allow other library maintainers to depend upon it.

**Comment by alouanemed** [comment]
I see. So I tried to link rxswift to my pod file

`  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'rxswift6'`

This error shows up:

```
Pre-downloading: `AttributedLib` from `https://github.com/Nirma/Attributed.git`
Pre-downloading: `RxSwift` from `https://github.com/ReactiveX/RxSwift`, branch `rxswift6`
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    RxSwift (from `https://github.com/ReactiveX/RxSwift`, branch `rxswift6`)

    RxViewController (~> 1) was resolved to 1.0.0, which depends on
      RxSwift (~> 5.0)


```

**Comment by alouanemed** [comment]
@freak4pc any clue?

**Comment by freak4pc** [comment]
Yup, as I mentioned, these frameworks are using RxSwift 5 as a dependency. I believe the only around this (and what these dependencies will have to do inevitably) will be to fork the repos and fix them to target the `rxswift6` branch

**Comment by alouanemed** [comment]
@freak4pc Thank you for confirming that. I forked this one and update the package file: is this correct?

https://github.com/alouanemed/RxViewController/blob/master/Package.swift#L14

**Comment by freak4pc** [comment]
I'm soo confused why we are talking about 3 different package managers :) 
You started out mentioning Cartfile for a dependency you're using, then mentioned you're using CocoaPods, and not referring to SPM.

I don't think that change looks correct. Just specifying the branch should be enough, without a version, see here: 

https://www.raywenderlich.com/1993018-an-introduction-to-swift-package-manager#toc-anchor-005

Note that the RxSwift 6 is changing a lot right now since I'm hoping to release RC1 next week.

**Comment by alouanemed** [comment]
I am using Cocoa in my project, SPM used by the pods.


That doesn't seem to work, it shows this error instead:

```
Pre-downloading: `Moya-ObjectMapper` from `https://github.com/alouanemed/Moya-ObjectMapper`
Pre-downloading: `RxSwift` from `https://github.com/ReactiveX/RxSwift`, branch `rxswift6`
Pre-downloading: `RxViewController` from `https://github.com/alouanemed/RxViewController`
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    RxSwift (from `https://github.com/ReactiveX/RxSwift`, branch `rxswift6`)

    RxViewController (from `https://github.com/alouanemed/RxViewController`) was resolved to 0.4.1, which depends on
      RxSwift (~> 5.0)


```

**Comment by freak4pc** [comment]
I'm sorry, I really can't provide this level of intimate support on GitHub issues. This repo is meant for bugs, etc. and not for dependency resolution. 

CocoaPods doesn't use Swift Package Manager directly, I'm not too sure what you're doing there but you might be able to get some more help in http://slack.rxswift.org 

It doesn't seem you change the podspec of your forked repo.

**Comment by alouanemed** [comment]
Okay, Thank you for your time.

**Comment by piv199** [comment]
In Cartfile: `github "ReactiveX/RxSwift" "rxswift6"`
After update: `Module 'RxSwift' was created for incompatible target arm64-apple-ios9.0`

What could be done, have anyone figured out how to make it work carthage+xcode12.0.1+rxswift

**Comment by freak4pc** [comment]
Hey @piv199 - I don't know Carthage well enough but understand there are some issues there. 
You might need to extend that script to exclude `arm64` from the supported architectures.
