### ISSUE TITLE
Crash during XCTAssertEqual with event of type Result<Any, NSError>

### ISSUE THREAD

**Issue by kevinabrioux** [ReactiveX/RxSwift#2232]
**Short description of the issue**:

  I have a crash in RxSwift.Event.debugDescription when using Result during an XCTAssertEqual operation

**Expected outcome**:

  I expected my test pass with sucess.

**What actually happens**:

  When i launch my test, XCTAssertEqual produce a crash in RxSwift.Event.debugDescription

**Self contained code example that reproduces the issue**:

```swift
    var testScheduler: TestScheduler!
    var disposeBag: DisposeBag!
    
    override func setUp() {
        super.setUp()
        self.testScheduler = TestScheduler(initialClock: .zero)
        self.disposeBag = DisposeBag()
    }
    
    func testCrash(){
        let observer = testScheduler
            .createObserver(Result<[Int]?, NSError>?.self)
        
        let observable = Observable.just(Result<[Int]?, NSError>.failure(NSError()))
        
        observable
            .bind(to: observer)
            .disposed(by: self.disposeBag)
        
        XCTAssertEqual(observer.events, [.next(0, .failure(NSError()))])
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 12.0 beta 6 (12A8189n)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode-12.0, Xcode-12_beta_4)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
That's interesting, I'll take a look. Generally speaking, you shouldn't be able to use XCTAssertEqual on a `Any` event, since it's not Equatable. You definitely shouldn't crash, though :)

**Comment by freak4pc** [comment]
Can you please provide a small reproducible example to save me some debugging time ? @kevinabrioux

**Comment by kevinabrioux** [comment]
Of course, i have create a test here : https://github.com/kevinabrioux/RxSwiftCrash/blob/master/RxSwiftCrashTests/RxSwiftCrashTests.swift

You can pull the sample project to reproduce it : https://github.com/kevinabrioux/RxSwiftCrash

**Comment by freak4pc** [comment]
Hey @kevinabrioux, your test works just fine if you replace `NSError()` with `NSError(domain: "com.test", code: 400, userInfo: nil)`. It is illegal to use the empty initializer of `NSError`: 

> -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.

![image](https://user-images.githubusercontent.com/605076/94188323-e140ac80-feb1-11ea-82da-b748a31ec8b7.png)

**Comment by kevinabrioux** [comment]
Many thanks for your return.

i will correctly init my NSError.

You can close this issue if you want.
