### ISSUE TITLE
Rx.Playground shows `No such module 'RxSwift'` error under Xcode 12

### ISSUE THREAD

**Issue by Scyano** [ReactiveX/RxSwift#2235]
**Short description of the issue**:

Rx.Playground shows `No such module 'RxSwift'` error under Xcode 12, but it works under Xcode 11.7

**Platform/Environment**

  - [X] iOS
  - [X] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
+ Version 11.7 (11E801a)
+ Version 12.0 (12A7209)

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Did you check the playground in the `rxswift6` branch?:

**Comment by jordizspmobile** [comment]
same for here.

**Comment by jordizspmobile** [comment]
I think that error is produced for this issue with XCode 12 -> https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

You need to exclude arm64 architectures for your target project and all your own frameworks in BuildSettings -> Excluded architectures.

And added these lines for your Podfile:

`
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
    end
end
`

**Comment by Scyano** [comment]
> Did you check the playground in the `rxswift6` branch?:

master branch

**Comment by Scyano** [comment]
@jordizspmobile it's master RxSwift repository, not my own project. I just download master branch, and start with Rx.playground following the guide, and it not work with Xcode 12

**Comment by freak4pc** [comment]
This seems to be a bug in Xcode 12, I've seen several reports of it.
Even with an empty SPM package, I can't seem to get Xcode 12 playgrounds to support _any_ third-party dependencies. 

Not sure there's anything that can be done in this case here.

**Comment by freak4pc** [comment]
Uhm I noticed checkeing 'Build active scheme' fixes it here. Can you try the latest copy in the `rxswift6` branch @Scyano ?

**Comment by Scyano** [comment]
fine, `rxswift6` works, Thanks for your patience

**Comment by fel-cesar** [comment]
Also @freak4pc solution worked for me, thanks! :)
