### ISSUE TITLE
Warnings about potential unknown cases of Event<Self.Element> on rxswift6 branch

### ISSUE THREAD

**Issue by arangato** [ReactiveX/RxSwift#2238]
**Short description of the issue**:

When archiving an iOS app with RxSwift there are following compiler warnings on seemingly exhaustive switch block:
"Switch covers known cases, but 'Event<Self.Element>' may have additional unknown values."

switch block example:
``` swift
        switch e {
            case let .next:
                break
            case let .error:
                break
            case .completed:
                break
        }
```

**Expected outcome**:

 No RxSwift related warnings during build.

**Self contained code example that reproduces the issue**:

Archiving RxExample-iOS issues several of the following warnings:

/.../RxSwift/RxRelay/Observable+Bind.swift:45:13: warning: switch covers known cases, but 'Event<Self.Element>' may have additional unknown values
            switch e {
            ^

Observation: removing `BUILD_LIBRARY_FOR_DISTRIBUTION = YES;` line added by 22f26767f6050626b480e4661737670976e6823e makes it go away.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _aa5917a1b359b7de47d6b91424d98350849d1b55_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 11.7
  Xcode 12.0 (12A7209)
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [x] Git submodules

**Comment by freak4pc** [comment]
Thanks for reporting. That flag is used to ensure forward compatibility when using xcframeworks. 

We need to annotate the Event enum with @frozen and that'll take care of it.

I'll fix it a tad later today.

**Comment by freak4pc** [comment]
@arangato can you try the latest copy of the branch?

**Comment by arangato** [comment]
> @arangato can you try the latest copy of the branch?

it works on my machine ;-) thanks for quick resolution. 
Is there a plan to release rxswift6 ?

**Comment by freak4pc** [comment]
Yup, by the weekend.
