### ISSUE TITLE
BehaviorSubject.value() crash on iOS14

### ISSUE THREAD

**Issue by chinabrant** [ReactiveX/RxSwift#2243]
**Short description of the issue**:

Firebase crash:
<img width="1138" alt="截屏2020-10-13 下午5 01 31" src="https://user-images.githubusercontent.com/3281092/95839941-2a2fa680-0d76-11eb-8467-a5a49879af67.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  - RxCocoa (5.1.1):
    - RxRelay (~> 5)
    - RxSwift (~> 5)

**Platform/Environment**

  iOS14

**Xcode version**:

```
  12.0.1
```

**Installation method**:
  - [*] CocoaPods

**Comment by freak4pc** [comment]
This isn't a valid bug report. Please provide code that causes the crash, thanks.
