### ISSUE TITLE
RXSwift memorey leaks 

### ISSUE THREAD

**Issue by AhmadDurrani579** [ReactiveX/RxSwift#2247]
I have install the RXSwift library but their is alot of memorey leaks thats xcode is showing let me upload the screen shot as well as  for showing the leaks
<img width="553" alt="sdqweqweqweqwe" src="https://user-images.githubusercontent.com/46595112/96795803-95314b00-1410-11eb-9bda-c6a9dc336174.png">

**Comment by freak4pc** [comment]
Hey Ahmad 
I'm not sure what you're showing here. Are you running in Release or Debug? Why are you sure that there is a memory leak and how are you sure it's not related to your specific usage ? 

Thanks,
Shai

**Comment by AhmadDurrani579** [comment]
@freak4pc  on screen shot i clearly show the leakage i have just installed the RXSwift 5.0 and RXcocoa so it showing these leakage even i click on it in navigate me on specific class

**Comment by freak4pc** [comment]
This is still not enough information. The fact Xcode shows it this way doesn't necessarily mean there's any leak in the code. 
The "code" in itself cannot leak if you've just installed it and never used it. 

Without more specific analysis it would be quite difficult to help you.

**Comment by AhmadDurrani579** [comment]
Make sense @freak4pc

**Comment by freak4pc** [comment]
If you find any real traces of a leak with proper instrumentation and reproducible code, please file a new issue. Thanks!
