### ISSUE TITLE
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa   Referenced from: /private/var/containers/Bundle/Application/F63B82D7-B923-434A-BE75-DA3585E3719C/RxExample-iOS.app/RxExample-iOS

### ISSUE THREAD

**Issue by Tliens** [ReactiveX/RxSwift#2252]
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa
  Referenced from: /private/var/containers/Bundle/Application/F63B82D7-B923-434A-BE75-DA3585E3719C/RxExample-iOS.app/RxExample-iOS

**Comment by Tliens** [comment]
<img width="845" alt="WX20201027-121916@2x" src="https://user-images.githubusercontent.com/31976044/97256742-d5e4f600-184e-11eb-8e1e-3ef20ddff39e.png">

like this will be ok！

**Comment by freak4pc** [comment]
If this issue was not resolved, please open a new one with more information and details. Thank you:)

**Comment by imChay** [comment]
![image](https://user-images.githubusercontent.com/11251776/116876080-7973f080-ac4e-11eb-998d-6d90e0cd9555.png)

**Comment by Dast1Woop** [comment]
> ![image](https://user-images.githubusercontent.com/11251776/116876080-7973f080-ac4e-11eb-998d-6d90e0cd9555.png)

save my day!
