### ISSUE TITLE
Can't Compile RxCocoa on Apple Watch

### ISSUE THREAD

**Issue by luigitrevisi** [ReactiveX/RxSwift#2253]
**Short description of the issue**:
I've been trying to compile an already existing iOS project containing a target for an Apple Watch extension.
The project uses RxSwift/RxCocoa which, reading at the official documentation, is compatible with watchOS.
If compiling with v5.1.1 it's ok, it fails with 6.0.0-rc.1

This issue was already fixed here: https://github.com/ReactiveX/RxSwift/issues/1737

**Expected outcome**:

The app compiles

**What actually happens**:
The app doesn't compile

**Self contained code example that reproduces the issue**:

```swift
Cannot find 'CGRectType' in scope
Cannot find 'CGPointType' in scope
Cannot find 'CGSizeType' in scope
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  6.0.0-rc.1

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [x] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12.1
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [X] Swift Package Manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base
[Mock.zip](https://github.com/ReactiveX/RxSwift/files/5451664/Mock.zip)

**Comment by freak4pc** [comment]
Thanks! Any chance you can provide a tiny isolated sample project with this issue? 
Would help getting a quick resolution over to you.

**Comment by luigitrevisi** [comment]
> Thanks! Any chance you can provide a tiny isolated sample project with this issue?
> Would help getting a quick resolution over to you.

Just added, thanks!

**Comment by freak4pc** [comment]
Hey, your project builds with no issues for me on Xcode 12.1. Anything specific to reproduce this?

**Comment by luigitrevisi** [comment]
Have you tried to compile for a real Apple Watch? For me It compiles for simulators only.

**Comment by freak4pc** [comment]
You haven't mentioned needing a real device ;-)

**Comment by freak4pc** [comment]
Can you try the `arm32_64` branch?

**Comment by luigitrevisi** [comment]
It compiled! Thank you

**Comment by freak4pc** [comment]
Fix is on `main` and will be deployed in RC2 @luigitrevisi

**Comment by bukira** [comment]
when is RC2 due? I need to point to main then in my swift package?
