### ISSUE TITLE
Add retryWhen operator

### ISSUE THREAD

**Issue by bontoJR** [ReactiveX/RxSwift#226]
`retryWhen` seems to be a very loved operator on RxJS and can be a very powerful allied to create very powerful retrial logics.

An example from RxJS is ([source](https://github.com/Reactive-Extensions/RxJS/blob/1b8709d6c198cfd1812491e49ecb02e33036d8de/doc/api/core/operators/retrywhen.md)) the incremental back-off strategy for handling errors::

```js
Rx.Observable.create(function (o) {
    console.log("subscribing");
    o.onError(new Error("always fails"));
  }).retryWhen(function (attempts) {
      return Rx.Observable.range(1, 3).zip(attempts, function (i) { return i; }).flatMap(function (i) {
        console.log("delay retry by " + i + " second(s)");
        return Rx.Observable.timer(i * 1000);
      });
  }).subscribe();
  
/*
subscribing
delay retry by 1 second(s)
subscribing
delay retry by 2 second(s)
subscribing
delay retry by 3 second(s)
subscribing
*/
```

I created a [dedicated branch for this](https://github.com/ReactiveX/RxSwift/tree/feature/retryWhen) that currently holds an attempt of port.

The problem is that, according to this test from RxJS, the source shouldn't unsubscribe if a sequence errors out ([source](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/tests/observable/retrywhen.js#L37)):

```js
test('retryWhen Observable never', function () {
    var error = new Error();

    var scheduler = new TestScheduler();

    var xs = scheduler.createHotObservable(
      onNext(150, 1),
      onNext(210, 2),
      onNext(220, 3),
      onNext(230, 4),
      onNext(240, 5),
      onError(250, error)
    );

    var results = scheduler.startScheduler(function () {
      return xs.retryWhen(function () {
        return Observable.never();
      });
    });

    results.messages.assertEqual(
      onNext(210, 2),
      onNext(220, 3),
      onNext(230, 4),
      onNext(240, 5)
    );

    xs.subscriptions.assertEqual(
      subscribe(200, 1000) //error happens at 250, but subscription is kept alive
    );
  });
```
I am currently struggling to achieve this behaviour without creating unnecessary complexity on the operator.

I would really love to have some opinions about this operator and if somebody wants to help is definitely a good thing.

**Comment by paddlefish** [comment]
I think RxJS's failure to dispose the subscription to `xs` after `onError( 250, error)` is a bug.  It looks to me that in RxJS the current implementation of `catchErrorWhen` ties all subscriptions to the source Observable together; I'd argue that it'd be more correct to dispose sooner.

**Comment by paddlefish** [comment]
I created an issue in RxJS for this (https://github.com/Reactive-Extensions/RxJS/issues/1009) and created a pull request that might fix it there (https://github.com/Reactive-Extensions/RxJS/pull/1010).

I haven't contributed much to that project, so we'll see if I'm right in my analysis or if RxJS maintainers disagree with me. :)

**Comment by kzaher** [comment]
Not that it's worth anything, but this also looks to me like a bug :)

**Comment by bontoJR** [comment]
Thanks guys for pointing to this... in a first instance I considered it to be a correct behaviour b/c of my limited knowledge of what's under the hood in RxJS, but reading how other operators are implemented and finally investing some time to read some other implementations, I definitely agree this might be an unwanted bug in RxJS, not disposing an outer subscription doesn't make sense. I will fix this operator soon.

**Comment by kzaher** [comment]
This was just released :)
