### ISSUE TITLE
M1 Mac  - Could not find module 'RxSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by jasonlagaac** [ReactiveX/RxSwift#2261]
**Short description of the issue**:

AS Mac not resolving module for  arm64 apple simulator

**Expected outcome**:

  RxSwift to compile for the arm64 simulator

**What actually happens**:

Compilation error - Could not find module 'RxSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**Self contained code example that reproduces the issue**:

NA - Happens on code compilation

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift - 5.1.1

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 12.2
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [X] Swift package manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by freak4pc** [comment]
Hey there:) won't have access to one of these M1s for a few more weeks. Happy to accept a PR / analysis if you have it.

Thanks!

**Comment by jasonlagaac** [comment]
https://github.com/ReactiveX/RxSwift/pull/2262 @freak4pc

**Comment by freak4pc** [comment]
Fixed in #2262

**Comment by tahirmt** [comment]
@jasonlagaac do you know why this is necessary? I'm getting an error in all of the frameworks with cocoapods
