### ISSUE TITLE
Use Driver Cause Memory Leaks

### ISSUE THREAD

**Issue by pilgrim1385** [ReactiveX/RxSwift#2267]
**Short description of the issue**:

  When I use Driver in my code, I got memory leaks reported by Instrument Leaks. When I change it to "bindTo", it works fine and no leaks any more. I wonder why this problem happened, and what should I do to avoid it.

**Expected outcome**:

  Driver works fine and no leaks found in Instrument Leaks.

**What actually happens**:

  Instrument Leaks report memory leak.

**Self contained code example that reproduces the issue**:

```swift
  import UIKit
import RxSwift
import RxCocoa

class ViewController: UIViewController {
    
    private let viewModel = ViewModel()
    
    private let disposeBag = DisposeBag()
    
    private lazy var nameLabel: UILabel = {
        let label = UILabel()
        label.text = "idle"
        return label
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.backgroundColor = .white
        self.view.addSubview(nameLabel)
        nameLabel.frame = CGRect(x: 100, y: 100, width: 100, height: 30)
        
        // not leak
//      viewModel.name.asObservable().bind(to: nameLabel.rx.text).disposed(by: disposeBag)
        
        // leak
//        viewModel.name.asDriver().drive(onNext: { [weak self] (name) in
//            guard let weakSelf = self else { return }
//            weakSelf.nameLabel.text = name
//        }).disposed(by: disposeBag)
        
        // leak
          viewModel.name.asDriver().drive(nameLabel.rx.text).disposed(by: disposeBag)
        
        viewModel.name.accept("act")
    }
}

class ViewModel {
    let name: BehaviorRelay<String> = BehaviorRelay(value: "")
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  5.1.1

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
  Version 12.3 (12C33)
```

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] I have a small code base

**Comment by freak4pc** [comment]
I've checked the exact same code and am not seeing a leak. 
Please enable Debug mode and make sure your resource count looks OK. If it does, it should be OK:
https://github.com/ReactiveX/RxSwift/blob/main/Documentation/GettingStarted.md#enabling-debug-mode

**Comment by pilgrim1385** [comment]
I create a "HomeViewController" as the rootViewController of the window in AppDelegate, and put a button on its view. Tap this button push this "ViewController". And keep printing Resource Count also.

`import UIKit
import RxSwift

@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        _ = Observable<Int>.interval(.seconds(1), scheduler: MainScheduler.instance)
                .subscribe(onNext: { _ in
                    print("Resource count \(RxSwift.Resources.total)")
                })
        window = UIWindow(frame: UIScreen.main.bounds)
        let homeVC = HomeViewController()
        window?.rootViewController = UINavigationController(rootViewController: homeVC)
        window?.makeKeyAndVisible()
        return true
    }
}`

`import UIKit

class HomeViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let button = UIButton()
        button.setTitle("push", for: .normal)
        button.addTarget(self, action: #selector(buttonClick), for: .touchUpInside)
        self.view.addSubview(button)
        button.frame = CGRect(x: 100, y: 100, width: 100, height: 40)
    }
    
    @objc func buttonClick() {
        let vc = ViewController()
        self.navigationController?.pushViewController(vc, animated: true)
    }
}`

When use "viewModel.name.asDriver().drive(nameLabel.rx.text).disposed(by: disposeBag)", Resource Count looks fine, 8 -> push -> 22 -> pop -> 8. But I still got leaks from Instruments Leaks. Every time when I push to this ViewController, I got a leak.
[
![截屏2020-12-17 下午7 55 09](https://user-images.githubusercontent.com/8338907/102485557-c04bba00-40a2-11eb-945d-8774091ddaa6.png)
](url)

Change To "viewModel.name.asObservable().bind(to: nameLabel.rx.text).disposed(by: disposeBag)",  Resource Count is fine, 8 -> push -> 17 -> pop -> 8. And the Instrument Leaks won't report leaks any more.
![截屏2020-12-17 下午8 06 11](https://user-images.githubusercontent.com/8338907/102486083-7adbbc80-40a3-11eb-9cc9-f933623827ac.png)

That's really strange.

**Comment by freak4pc** [comment]
Quite strange, but I'm not seeing anything in that trace that determines it's related to Driver or the library in any way.

**Comment by freak4pc** [comment]
It might be some issue with instruments (it is more common than you'd expect). If the resource count looks good it should be OK, closing this one. Thanks for the question though!
