### ISSUE TITLE
ReactiveCompatible is a class protocol in RxSwift 6

### ISSUE THREAD

**Issue by groue** [ReactiveX/RxSwift#2270]
**Short description of the issue**:

`ReactiveCompatible` is a class-only protocol in RxSwift 6, which prevents declaring handy `.rx` extensions on structs. This affects the RxGRDB repository.

**Expected outcome**:

`ReactiveCompatible` can be declared on struct extension, OR there exists another way to declare handy `.rx` extensions on structs.

**What actually happens**:

Compiler complains, and I don't know how to manage this breakage.

**Self contained code example that reproduces the issue**:

```swift
// No longer compiles
protocol P { ... }
struct S: P { ... }
extension S: ReactiveCompatible { } // Non-class type 'S' cannot conform to class protocol 'ReactiveCompatible'
extension Reactive where Base: P { /* handy extensions */ }

let s = S(...)
s.rx.yeah()
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 6.0.0

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 12.3 (12C33)
```

**Comment by freak4pc** [comment]
Hey @groue - Thanks for reporting :) 
This is a breaking change and a known downside of the new `@dynamicMemberLookup` approach we took for RxSwift 6. 

Luckily, you can make a wrapper to resolve this issue:

```swift
struct MyObject { } 

extension MyObject {
    struct Rx { 
        private let base: MyObject
        init(_ base: MyObject) { self.base = base }
    }
}

public extension MyObject.Rx { 
    /// Reactive extensions
}
```

Everything else can remain as-is. 

Does this solution accommodate that specific use-case?

**Comment by groue** [comment]
Thanks for your help and explanation 👍 !

I have too many structs to extend, so I'll basically have to restore the old `Reactive` struct-compatible wrapper. Now I'm just struggling to find a distinct name so that it does not conflict with RxSwift's ;-)

'll close this issue. Maybe, if several users report similar problems, this breaking change will turn into a regression that deserves to be addressed.

**Comment by iDevid** [comment]
I also find myself using ReactiveCompatible with many models that are structs

**Comment by bigMOTOR** [comment]
So do I.

**Comment by freak4pc** [comment]
@groue @bigMOTOR - Thanks to @iDevid's creative solution, RxSwift 6.1 (coming out today) will bring back non-Class support.

Thanks again!

**Comment by freak4pc** [comment]
RxSwift 6.1 is out with this fix. Thanks @iDevid! Let me know if this helps your cases @groue @bigMOTOR.
