### ISSUE TITLE
No such module 'RxCocoaRuntime'

### ISSUE THREAD

**Issue by Brudus** [ReactiveX/RxSwift#2277]
**Short description of the issue**:

I'm facing a strange issue and I don't know if it is a bug or I'm just missing something. I'm currently working for a big company but interestingly their build server doesn't support CocoaPods, Carthage, or Swift Package Manager. So I added all frameworks by hand. I added RxSwift, RxCocoa, etc. (version 6.0) but it won't build.

I also tried to use it in a completely fresh project. 

**Expected outcome**:

I expect that it would work without a dependency manager as .xcframework files are provided.

**What actually happens**:

The project won't build and I get the following message: 
`Failed to build module 'RxCocoa' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced`

Along with:
`No such module 'RxCocoaRuntime'`

**Self contained code example that reproduces the issue**:

I've created a GitHub project of the issue - 
https://github.com/Brudus/framework-test

The imports in the AppDelegate.swift are enough to prevent the project from building.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxCocoa 6.0.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12.3
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Manual

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by Brudus** [comment]
After adding and removing RxCocoa several times I was able to build it but still, RxCocoaRuntime seems to be missing.

```
dyld: Library not loaded: @rpath/RxCocoaRuntime.framework/RxCocoaRuntime
  Referenced from: /private/var/containers/Bundle/Application/82935471-BE2E-4D18-BE63-E95E7CFE3743/FrameworkTest.app/Frameworks/RxCocoa.framework/RxCocoa
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Comment by freak4pc** [comment]
Thanks! So when you say "by hand", you mean you took the XCFramework from the 6.0.0 release and it didn't work for you when adding it in?

**Comment by Brudus** [comment]
Exactly, I added it to the project. And put it into Frameworks, Libraries, and Embedded Content in the correct project target.

**Comment by freak4pc** [comment]
I'll try taking a look at it later in the week, thank you for reporting it :)

**Comment by freak4pc** [comment]
Hey @Brudus, apparently we need to actually import a separate RxCocoaRuntime.xcframework as well (no need to actually `import RxCocoaRuntime`, but the framework needs to be in the import phase).

I've added it to the 6.0.0 release, let me know if that works:
https://github.com/ReactiveX/RxSwift/releases/tag/6.0.0

**Comment by Brudus** [comment]
I will check it out on Saturday. It turned out that the build-server of the company I'm working for, supports SPM and I was able to add it with this. 

But thank you very much for taking the time, I will tell you if it solves the issue as soon as I've tested it but no later than Sunday morning. 

Thanks again! :)

**Comment by freak4pc** [comment]
Thanks! Looking forward to your test.

**Comment by Brudus** [comment]
Hi, I made my test and it does work now.

I just had to add the RxCocoaRuntime.xcframework to the project and also in the 'Frameworks, Libraries, and Embedded Content' section I've changed it from 'Do not embed' into 'Embed & Sign'. No RxCocoa won't throw an error anymore.

Thanks for taking the time to figure that out!

Best
Manuel

**Comment by alexfu** [comment]
This also appears to be missing from the latest 6.5.0 release.

**Comment by trilliwon** [comment]
@freak4pc RxCocoaRuntime.xcframework does not exist inside 6.5.0 release.  Could you provide it?

**Comment by freak4pc** [comment]
> @freak4pc RxCocoaRuntime.xcframework does not exist inside 6.5.0 release. Could you provide it?

Hey, are you actually getting the same build error? RxCocoaRuntime should come bundled within RxCocoa in 6.5.0. Let me know when you can, please :)

**Comment by matheusbastos-gb** [comment]
@freak4pc , I'm getting this error when I have a binary framework that depends on RxCocoa in my project. My app also depends on RxCocoa through the Swift Package Manager.

**Comment by mbastos** [comment]
@freak4pc I'm getting this error when I have a binary framework that depends on RxCocoa in my project. My app also depends on RxCocoa through the Swift Package Manager.

**Comment by lgvv** [comment]
@freak4pc  I got an error, too. However, I solved it by the method below.

```
Xcode 14.0
RxSwfit 6.5
```

project target - build phases(Unit Test) - Link Binary With Libraries

[Add] RxSwift, RxCocoa

 I hope this way will be of some help.

**Comment by sglushchenko** [comment]
Hello guys,
I have the same issue with version 6.5.0.

I have Package.swift. I have a binary target in Package.swift. My code used RXCocoa, but I replace it to RxRelay and it's enough for me. So, generally, RxRelay doesn't use RxCocoaRuntime.

When I compile main project with dependency to my binary framework that have dependencies to RxSwift and RxRelay I have the error.

I downloaded RxCocoaRuntime from version 6.0.0 and add it to my main project and compilation success, but when I launch the app I see an error that dylib RxSwift doesn't load.
I remove RxCocoaRuntime and the app started launching while I will not clean the project.

Could you help with it?

**Comment by Minny27** [comment]
I got a similar Issue like this.
<img src="https://github.com/ReactiveX/RxSwift/assets/68800789/53cffa16-fe7b-4d98-afcd-d42c562193bf" width=50%>

I resolved this issue to add `RxCocoa-Dynamic` package in `Link Binary with Libraries` of target

Path: Target > Build Phases > Link Binary with Libraries

<img src="https://github.com/ReactiveX/RxSwift/assets/68800789/f6813628-b282-45e7-8f7a-9366320b8e8d" width=50%>

**Comment by freak4pc** [comment]
We don't use the RxSwift repo for specific integration support, please use our Slack for that. We use GitHub only for bugs and issues with the library itself.
