### ISSUE TITLE
CURL debug print doesn't display body on PATCH requests.

### ISSUE THREAD

**Issue by danielt1263** [ReactiveX/RxSwift#2282]
I noticed today that the debug `curl` output doesn't show the body when I do a PATCH request. I was going to update this line:

```
if let httpBody = request.httpBody, request.httpMethod == "POST" || request.httpMethod == "PUT" {
```
to add the "PATCH" into it, but I started thinking, if the URLRequest has an httpBody, shouldn't the debug output show it, no matter what the http method is? Let me know what you think and I'll make a pull request.

**Comment by freak4pc** [comment]
@danielt1263 Yeah that's a good thought. It is "illegal" to have a body for a GET request, but if one does that for some godly-unknown reason, we should print it if it exists.

**Comment by freak4pc** [comment]
@danielt1263 Wanna take care of this before 6.1? I hope to release tomorrow

**Comment by danielt1263** [comment]
Odd, the automated test didn't pass. All tests pass locally...
