### ISSUE TITLE
Accidental deallocation of already deallocated object resulting crash when using RxSwift.

### ISSUE THREAD

**Issue by GetToSet** [ReactiveX/RxSwift#2287]
**Short description of the issue**:

I'm build an iOS app using RxSwift and found strange crashes when accessing model objects at certain certemstnces. It seems that objects got deallocated accidentally even they're strongly held.

I spent a lot of time diving deeper into this problem, and finally I got these lines of minimal code to reproduce the same issue:

```swift

import RxSwift

// MARK: - ViewModel

protocol ViewModel: class {
  associatedtype Action
}

protocol DomainAction {
  static func event(_: Event) -> Self
}

protocol DomainViewModel: ViewModel where Action: DomainAction { }

final class ConcreteViewModel: DomainViewModel {
  enum Action: DomainAction {
    case event(_: Event)
  }
}

// MARK: - Event

struct EventPayload {
  let foo: String
  let bar: String
}

protocol Event {
  var payload: EventPayload { get }
}

struct ConcreteEvent: Event {
  let payload: EventPayload
}

// MARK: - View

final class View<ViewModel: DomainViewModel> {

  var disposeBag = DisposeBag()

  init() {
    Observable.just(
      ConcreteEvent(payload: EventPayload(foo: "foo", bar: "bar"))
    )
    .subscribe(onNext: { item in
      _ = ViewModel.Action.event(item)
    })
    .disposed(by: disposeBag)
  }

}

_ = View<ConcreteViewModel>()
```

**Expected outcome**:

Code pated above runs and returns normally.

**What actually happens**:

The above code crashed with following stacktrace:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
TestAppCrash(307,0x1101e9e00) malloc: Double free of object 0x7fb216805f20
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff20392462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff203c0610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20313720 abort + 120
3   libsystem_malloc.dylib        	0x00007fff201f4430 malloc_vreport + 548
4   libsystem_malloc.dylib        	0x00007fff20208702 malloc_zone_error + 183
5   TestAppCrash                  	0x000000010f6f4f05 0x10f6f0000 + 20229
6   libswiftCore.dylib            	0x00007fff2cac7820 _swift_release_dealloc + 16
7   TestAppCrash                  	0x000000010f6f3e1d __swift_destroy_boxed_opaque_existential_1 + 77
8   TestAppCrash                  	0x000000010f6f3f41 destroy for ConcreteViewModel.Action + 17
9   TestAppCrash                  	0x000000010f6f3b84 closure #1 in View.init() + 452 (main.swift:48)
10  TestAppCrash                  	0x000000010f6f3c1c thunk for @escaping @callee_guaranteed (@guaranteed ConcreteEvent) -> () + 60
11  TestAppCrash                  	0x000000010f7c5bd3 closure #1 in ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) + 739
12  TestAppCrash                  	0x000000010f7c5f73 partial apply for closure #1 in ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) + 115
13  TestAppCrash                  	0x000000010f6fc7cf AnonymousObserver.onCore(_:) + 95
14  TestAppCrash                  	0x000000010f7cd8a1 ObserverBase.on(_:) + 273
15  TestAppCrash                  	0x000000010f7cdb67 protocol witness for ObserverType.on(_:) in conformance ObserverBase<A> + 23
16  TestAppCrash                  	0x000000010f7a35cf Just.subscribe<A>(_:) + 319
17  TestAppCrash                  	0x000000010f7c56d6 ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) + 1702
18  TestAppCrash                  	0x000000010f6f3750 View.init() + 768 (main.swift:47)
19  TestAppCrash                  	0x000000010f6f3441 View.__allocating_init() + 33
20  TestAppCrash                  	0x000000010f6f3038 main + 40 (main.swift:55)
21  libdyld.dylib                 	0x00007fff203db621 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000001101e9e00  rcx: 0x00007ffee050e6f8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee050e720  rsp: 0x00007ffee050e6f8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x00000001101e9e00  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x0000000000000043  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff20392462  rfl: 0x0000000000000246  cr2: 0x000000010fcce000
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

**Self contained code example that reproduces the issue**:

See above.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  Both 5.1.1 and 6.0.0 can produce the same issue.

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [ ] tvOS (Not tested)
  - [ ] watchOS (Not tested)
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 12.4 (12D4e)
```

**Installation method**:
  - [x] CocoaPods
  - [x] Swift Package Manager (integrated with Xcode)
  - [ ] Carthage (Not tested)
  - [ ] Git submodules (Not tested)

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
I'm not sure what made you think this is an Rx issue?

**Comment by GetToSet** [comment]
> I'm not sure what made you think this is an Rx issue?

It more seems like it's an issue regarding Swift itself, however, I can't provide a self-contained code snippet to reproduce this issue without RxSwift involved.

**Comment by GetToSet** [comment]
I got this reproduced without RxSwift involved. It's an issue on Swift itself, rather than RxSwift.

**Comment by freak4pc** [comment]
It seems to me you are not correctly holding a strong reference. CORPSE means it's been deallocated by ARC. I'd suggest turning on Zombie Objects to debug this. Good luck!

**Comment by GetToSet** [comment]
After some further investigation now I can definitely confirm it's a bug of Swift itself, where enum cases as protocol witness use incorrect ARC semantics for associated values, causing twice deallocation or memory leak. Detailed description and potential solution to this problem can be found [here](https://bugs.swift.org/projects/SR/issues/SR-14071).
