### ISSUE TITLE
Dispose issue

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#229]
There is a subject produce sequence called viewS, observed on a private thread with a long chain of operations.
In this case, disposeBag is not working as expected.
I can provide my full code to recur this issue.

    class ServiceScheduler{
    static var sharedInstance = SerialDispatchQueueScheduler(internalSerialQueueName:"ServiceScheduler")
    }

    class ViewController: UIViewController{
        var viewS = ProductSubject<ViewAction>()
        var disposeBag = DisposeBag()
        override func viewDidDisappear(){
                super.viewDidDisappear()
                diposeBag = DisposeBag()
        }
        override func viewDidAppear(){
                super.viewDidAppear()
            viewS

            //when this line removed, all things work well 
            .observeOn(ServiceScheduler.sharedInstance) 

            .map{ [unowned] self in

                    // if the observeOn is not removed,
                    // at some time, app crash here because a nil self is being called
                    if self.shouldLoad(loadType) {
                    }
                    ...
                
            }.switchLatest()
            .map { [unowned self] in return ... }
            .doOn(onNext: {[unowned self] in self.modelEventHandler($0)})
            .map { [unowned self]  in ... }
            .observeOn(MainScheduler.sharedInstance)
            .subscribeNext{ [unowned self] data in
                self.on(.Next(data))
                self.completion?(data)
            }
            .addDisposableTo(disposeBag)
        }
    }

**Comment by kzaher** [comment]
Hi @frogcjn ,

From your description, I believe this behavior is expected. We've tried to explain all about disposing [here](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#disposing).

If you have different schedulers, then canceling operations is best effort and will happen the soonest it can. It is not possible to cancel any operation execution immediately.

Consider for example that in the code you've provided the background thread is executing 
```
        .map{ [unowned] self in
<-- here somewhere
                // if the observeOn is not removed,
                // at some time, app crash here because a nil self is being called
                if self.shouldLoad(loadType) {
                }
                ...
```

We can't cancel that operation immediately. What we can do is to make sure results aren't returned on main thread and once control is transferred to our code, cancel that operation.

We can also cancel future scheduled or pending work. I think your example is just at the border where we can't stop scheduled code from starting execution but we need to let it just run and ignore the results.

I would suggest that instead of accessing resources through `self`, you access resources in scope. For example.

```
override func viewDidAppear(){
            super.viewDidAppear()
        
       let resource = self.someResource
        viewS
        //when this line removed, all things work well 
        .observeOn(ServiceScheduler.sharedInstance) 

        .map{ _ in
                if resource.shouldLoad(loadType) { // no need to reference self
                }
                ...

        }.switchLatest()
        .....
       
        .addDisposableTo(disposeBag)
    }
```

Hope that makes sense.

**Comment by frogcjn** [comment]
if I use the takeUntil to solve the problem, is this right? put it after observeOn?

      super.viewDidAppear()
        viewS
        //when this line removed, all things work well 
        .observeOn(ServiceScheduler.sharedInstance) 
        .takeUntil(disposeS)
        .map{ [unowned] self in ...

**Comment by frogcjn** [comment]
I have tested: The blocks of .map can have a retained self. This will not lead to retain cycle.
thus, in this case, all "[unowned self] in" can be safely removed from the code. 
Thus the problem solved.

**Comment by kzaher** [comment]
@frogcjn hm ... I guess that does work :)

Although that works, if you have that logic in objects outside of VC, your code could be written in more idiomatic way, so I would definitely suggest pulling it out of VC :)

**Comment by frogcjn** [comment]
@kzaher , I have a custom service class. This piece code is in the service class. VC.viewDidAppear will trigger .Next(.Load), then the service will work on this signal with this long operations. the service class has shouldLoad function and state property to record the loading process. Subclass of service can override thus other VC can use this class,

**Comment by frogcjn** [comment]
@kzaher , and I tried another method:

            dispatch_sync(ServiceScheduler.serialScheduler.underlyingQueue) { () -> Void in
                self.actionDisposeBag = DisposeBag()
                debugPrint("dispose \(self)'s viewS")
            }

main thread will wait for the disposing before self released. 
This is also work without removing [unowned self]

**Comment by kzaher** [comment]
@frogcjn hope you will have a nice time using RxSwift.

I think we've addressed all questions here :) We can open new issues if there are some new questions.

I think people need some adaptation time to figure out how to use Rx efficiently, that's perfectly natural.

I'm sure you'll find even more elegant ways in future.
