### ISSUE TITLE
Crash in RxTableViewReactiveArrayDataSource

### ISSUE THREAD

**Issue by BGLv** [ReactiveX/RxSwift#2295]
**Short description of the issue:**
Sometimes we see crashes in the Crashlytic log related to RxTableViewReactiveArrayDataSource.swift

**Expected outcome**:
 Fix crash or get info how to avoid this type of crash in future

**What actually happens**:

![image](https://user-images.githubusercontent.com/22197990/109478061-72c7d200-7a81-11eb-81b3-59a6c9f8e867.png)

![image](https://user-images.githubusercontent.com/22197990/109478276-b4587d00-7a81-11eb-8019-bd0dc7591c77.png)

<img width="588" alt="image" src="https://user-images.githubusercontent.com/22197990/109481390-575ec600-7a85-11eb-8217-33cebbdc8a79.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 5.1.1

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [X] hard, 2% - 10%
  - [] extremely hard, %0 - 2%

**Installation method**:
  - [X] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [X] I have a significant code base

**Comment by freak4pc** [comment]
Unfortunately this crash is too exotic for me to provide a "fix". Are you possibly manually mutating your data source instead of using an Observable of sections?

**Comment by BGLv** [comment]
@freak4pc no we use it like this
<img width="798" alt="image" src="https://user-images.githubusercontent.com/22197990/109485841-ce4a8d80-7a8a-11eb-8ec9-9bd2a698618d.png">
but we have cell`s with expand button so user can press on it and cell show hidden subviews, and for correctly cell sizing we call next method for tableView
<img width="462" alt="image" src="https://user-images.githubusercontent.com/22197990/109486033-0782fd80-7a8b-11eb-9fc6-be639cc41559.png">

**Comment by freak4pc** [comment]
I've had a few apps in production with thousands of rows and have never seen a crash at the area you describe, which makes me think it's related to some of the internal logic you have there. For example, that `onContentSizeChanged` seems a bit suspicious. 

Without a more solid reproducible state, there is unfortunately very little I can do to help.
