### ISSUE TITLE
Rx

### ISSUE THREAD

**Issue by Eugeneberezin** [ReactiveX/RxSwift#2299]
_version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:
12.3
```
  Xcode version goes here
```
12.3

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small codebase
  - [ ] I have a significant code base
After installing pods running arch -x86_64 pod install the project won't compile. It's complaining that it's missing RxCocoa framework

**Comment by freak4pc** [comment]
No content
Closing
