### ISSUE TITLE
Readme: Add Interstellar to Feature Comparison

### ISSUE THREAD

**Issue by fabb** [ReactiveX/RxSwift#230]
Could you add the library Interstellar to your (very helpful) feature comparison?
https://github.com/JensRavens/Interstellar

**Comment by kzaher** [comment]
Hi @fabb ,

I think that this library and Interstellar have significantly different goals, so I'm not sure adding that comparison would be helpful to either library.

I think people will blog/tweet about differences between them.

Hope that makes sense :)

**Comment by fabb** [comment]
Here is one such blog post: https://medium.com/@clozach/climbing-the-reactive-learning-curve-4a03fa8d17ae#.8sk5fco3p

**Comment by dtartaglia** [comment]
It looks like Interstellar contains the absolute bare minimum required for a system to be considered reactive. It is missing many of the operators that make working with reactive systems easier.

An Interstellar Signal is very much like an RxSwift Variable. You can do everything with a Variable that you can do with a Signal. However, a Variable has a bit more. For example, with both systems you can subscribe one Signal/Variable to another so they change in concert, but with RxSwift, you can also unsubscribe. I also didn't see any functionality in Interstellar like `distinct`, `takeWhile`, `combineLatest` or `zip`, so combining two Signals into one and most filter operations would have to be hand coded in Interstellar whereas they are included in RxSwift.

Just to be clear, I'm not saying that Interstellar is a bad. It has different goals and aims. It isn't trying to be a complete system out of the box. It's trying to be small and easily grocked. Much like the difference between the C programming language and Swift... You can do the same things with both, but some things that are easier to do in RxSwift.

**Comment by kzaher** [comment]
Hi @fabb ,

Hope it's ok with you, but I would feel much more comfortable if we would let this up to community to evaluate :)

From your response it looks like there are already resources online.

Closing this for now :)
