### ISSUE TITLE
[Pitch] New enum case for `SubjectLifetimeScope` - `.whenSuccessful`

### ISSUE THREAD

**Issue by igor-makarov** [ReactiveX/RxSwift#2301]
As a user of RxSwift and a developer of app infrastructure, I frequently need to implement a "loader task" pattern - something that should share the result, can fail, but once successful, does not need to be performed again. Examples:
* Load a config file from the server
* Initialize an SDK class

The new lifetime scope behaves just as `.forever`, but disconnects if an error occurs. In other words, it's like a `.forever` that can be retried.

I've tried to think of a way to implement this by composing existing operators, but I'm drawing a blank - which is why I think this might be an API expansion.

**Comment by freak4pc** [comment]
Thanks for the suggestion :) 
My instinct is that this doesn't make sense for a subscription scope. It's weird having a subscription scope that's tied to business logic like that. Today it's tide to actual life-cycle related events. 

I might have an idea on how to compose other operators to achieve this, I'll try to write it down here a bit later. 

Thank you!

**Comment by hello-im-szymon** [comment]
Here's a possible solution
```
        let configSubject = BehaviorSubject<Config?>(value: nil)
        let config = configSubject
            .flatMapFirst { existingProviders -> Single<Config> in
                if let config = existingConfig {
                    return .just(config)
                } else {
                    return request()
                        .do(onSuccess: { [weak configSubject] config in
                            configSubject?.onNext(config)
                        })
                        .catchError {
                            // TODO: Handle errors the way you want
                        }
                }
            }
            .share()
```
Then just call `config.subscribe(...)` whenever you need the value

**Comment by freak4pc** [comment]
Hey Igor,
Sorry I didn't have the time to further investigate this issue, but I'll be closing this for now since (like I originally commented) adding a new subscription scope for specific business logic is probably not the way to go.

I didn't check @hello-im-szymon's solution, but perhaps it can work for you.

**Comment by igor-makarov** [comment]
@hello-im-szymon I've been using this pattern as well, however in some cases it has some reentrancy problems (that cause an assert in RxSwift or in Swift runtimes). Perhaps it's a bug in my implementations.
