### ISSUE TITLE
rx_notification never callback

### ISSUE THREAD

**Issue by zixun** [ReactiveX/RxSwift#231]
the  rx_notification callback never called, and this is my code:

     NSNotificationCenter()
            .rx_notification(UMOnlineConfigDidFinishedNotification)
            .subscribeNext {[weak self] (notif:NSNotification) -> Void in
                guard let sself = self else {
                    return
                }
                sself.showADView(type: MobClick.getConfigParams("adType"))
            }.addDisposableTo(self.disposeBag)

also delete  .addDisposableTo(self.disposeBag) as TestCase,but also not work

**Comment by kzaher** [comment]
Hi @zixun ,

That is extremely weird. I've checked our unit tests, and they do pass (I've pasted them below).

Could you please tell me 
* what version are you using `2.0.0-beta.2`
* what environment (OSX, iOS, ...)
* Xcode version
* Can you try to execute `NSNotificationCenter().postNotificationName(UMOnlineConfigDidFinishedNotification, object: nil)` manually?

```
func testNotificationCenterWithoutObject() {
        let notificationCenter = NSNotificationCenter()
        
        var numberOfNotifications = 0

        notificationCenter.postNotificationName("testNotification", object: nil)
        
        XCTAssertTrue(numberOfNotifications == 0)
        
        let subscription = notificationCenter.rx_notification("testNotification", object: nil)
            .subscribeNext { n in
            numberOfNotifications++
        }

        XCTAssertTrue(numberOfNotifications == 0)
        
        notificationCenter.postNotificationName("testNotification", object: nil)
        
        XCTAssertTrue(numberOfNotifications == 1)
        
        notificationCenter.postNotificationName("testNotification", object: NSObject())
        
        XCTAssertTrue(numberOfNotifications == 2)
        
        subscription.dispose()

        XCTAssertTrue(numberOfNotifications == 2)
        
        notificationCenter.postNotificationName("testNotification", object: nil)

        XCTAssertTrue(numberOfNotifications == 2)
    }
    
    func testNotificationCenterWithObject() {
        let notificationCenter = NSNotificationCenter()
        
        var numberOfNotifications = 0
        
        let targetObject = NSObject()
        
        notificationCenter.postNotificationName("testNotification", object: targetObject)
        notificationCenter.postNotificationName("testNotification", object: nil)
        
        XCTAssertTrue(numberOfNotifications == 0)
        
        let subscription = notificationCenter.rx_notification("testNotification", object: targetObject)
            .subscribeNext { n in
                numberOfNotifications++
        }
        
        XCTAssertTrue(numberOfNotifications == 0)
        
        notificationCenter.postNotificationName("testNotification", object: targetObject)
        
        XCTAssertTrue(numberOfNotifications == 1)
        
        notificationCenter.postNotificationName("testNotification", object: nil)
        
        XCTAssertTrue(numberOfNotifications == 1)

        notificationCenter.postNotificationName("testNotification", object: NSObject())
        
        XCTAssertTrue(numberOfNotifications == 1)
        
        notificationCenter.postNotificationName("testNotification", object: targetObject)
        
        XCTAssertTrue(numberOfNotifications == 2)
        
        subscription.dispose()
        
        XCTAssertTrue(numberOfNotifications == 2)
        
        notificationCenter.postNotificationName("testNotification", object: targetObject)
        
        XCTAssertTrue(numberOfNotifications == 2)
    }
```

**Comment by zixun** [comment]
RxSwift Version is 2.0.0-beta.2
environment is iOS 
Xcode is 7.1

if I manually post Notification, It's also not work.

but

if I change the NSNotificationCenter()  to NSNotificationCenter.defaultCenter(), it works!

**Comment by zixun** [comment]
@kzaher maybe it's not the RxSwift's problem, I tried the code below:

      NSNotificationCenter().addObserverForName(UMOnlineConfigDidFinishedNotification, object: nil, queue: nil) { _ -> Void in
            println("invoke")
        }

the String of invoke also can't print, I think NSNotificationCenter() is nil will the notification is posted

**Comment by kzaher** [comment]
Oh, sry, I'm also blind :). It's early in the morning :)

`NSNotificationCenter()` just creates a new version of `NSNotificationCenter()` and then deallocates it, so nobody can send anything to it.

You should be using `NSNotificationCenter.defaultCenter()` because that returns shared `defaultCenter`.

Hope that clears things up :)
