### ISSUE TITLE
Why should my version prompt iOS 11?

### ISSUE THREAD

**Issue by soso-su** [ReactiveX/RxSwift#2310]
Showing Recent Messages
'showsBackgroundLocationIndicator' is only available in iOS 11.0 or newer

**Comment by freak4pc** [comment]
It's iOS 11 and up: 
https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator

**Comment by soso-su** [comment]
Don't you have an updated version?

**Comment by freak4pc** [comment]
I'm not too sure what you mean here.
