### ISSUE TITLE
Build failed in Xcode12.5

### ISSUE THREAD

**Issue by cacawai** [ReactiveX/RxSwift#2311]
**Short description of the issue**:

Build failed in Xcode12.5

**Expected outcome**:

Build without error in Xcode12.5

**What actually happens**:

![screenshot-20210428-143823](https://user-images.githubusercontent.com/1765479/116358704-851b7d80-a830-11eb-9b41-e6992990199a.png)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.1.0

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

Xcode12.5

```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Can you please try the main branch directly? We should have a release in the following days.

Thanks,

**Comment by hiragram** [comment]
@cacawai Use `main` branch instead. It is already fixed but not released yet.

**Comment by cacawai** [comment]
pod 'RxCocoa',  :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'main'
Tried the main branch , still got this error

**Comment by hiragram** [comment]
Are there any diff in Podfile.lock after `pod update` ?
I'm not sure but I think you should specify branch for every pods from this repository such as `pod 'RxSwift'`.

**Comment by cacawai** [comment]
RxCocoa:
    :commit: 7219024cd02502e9faa6528a655709257f28a105
    :git: https://github.com/ReactiveX/RxSwift.git
  RxSwift:
    :commit: 7219024cd02502e9faa6528a655709257f28a105
    :git: https://github.com/ReactiveX/RxSwift.git

I'm sure using the main branch, and I can see the code that your modified 3 days ago after pod update.
but still got this error, and I  also tried to clean and rebuild the whole project.

**Comment by hiragram** [comment]
I have no idea 🤷 
Try restarting Xcode or rebooting your mac.

**Comment by cacawai** [comment]
Reboot doesn't work, I'll use Xcode12.4 now, and continue to work on this issue later.

**Comment by cacawai** [comment]
I removed $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) from  LIBRARY_SEARCH_PATHS in the Build Settings fixed this issue.
It's a 9 years old project , I have no idea when and why we add this ...

**Comment by agruchala** [comment]
@cacawai What version has a fix? 6.1.0?

**Comment by cacawai** [comment]
> @cacawai What version has a fix? 6.1.0?

Yeah, I'm still using version 6.1.0
For me I just removed $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) from LIBRARY_SEARCH_PATHS in the Build Settings. And the build error just disappeared.

**Comment by agruchala** [comment]
Hmm, for Us it doesn't build on Xcode 12.5 via Carthage, so I think there is a different issue.

**Comment by kazukisugita** [comment]
@agruchala 
 +1 👍
 I'm also facing the same situation... via Carthage
