### ISSUE TITLE
Changing system time affects Throttle/Delay etc.

### ISSUE THREAD

**Issue by leonylcatwork** [ReactiveX/RxSwift#2316]
*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

If we set throttle to a control, say, a button, we could prevent button being tapped multiple times when it is processing task:
```
button.rx.tap.throttle(.milliseconds(500), latest: false, scheduler: MainScheduler.instance)
```

This works fine normally, except when you change system time backwards (by, say, one day) after first tap when `lastSentTime` was recorded.
When ThrottleSink is calculating reduceWithSpanBetween() on the second tap, its remainder time will be a great positive number making it not firing event, because `laterDate` is now in fact earlier than `earlierDate` (since we changed system time to an earlier date). I assume `delay` operator would be similar since it calls reduceWithSpanBetween() in a similar fashion.
 
line 43 Date+Dispatch.swift

```
internal func reduceWithSpanBetween(earlierDate: Date, laterDate: Date) -> DispatchTimeInterval {
    return self.map { value, factor in
        let interval = laterDate.timeIntervalSince(earlierDate)
        let remainder = Double(value) - interval * factor
        guard remainder > 0 else { return 0 }
        return Int(remainder.rounded(.toNearestOrAwayFromZero))
    }
}
```

**Expected outcome**:

I suppose when using throttle/debounce/delay operators we focus on relative time changing rather than absolute time changing.
What if we take absolute value of `interval` when calculating `remainder`? This way we only care about the magnitude and not the direction of the difference of two Dates. I know this is not perfect (a range of value in the opposite direction still prevent it from firing), but it maybe the simplest  way to deal with above problem.

BTW, is there better way to prevent a control from firing multiple times if the user tap too fast?

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.0.0

**Platform/Environment**

iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

easy, 100% repro

**Xcode version**: 

```
12.5
```

**Installation method**:
CocoaPods

**I have multiple versions of Xcode installed**:
no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
I have a significant code base

**Comment by freak4pc** [comment]
I don't find it to be a reasonable use case to support (user tapping a button, going over to change their time, coming back to tap again). 

Is this a real use case or more theoretical ? 

Did you check if Combine handles this any differently?

**Comment by leonylcatwork** [comment]
> I don't find it to be a reasonable use case to support (user tapping a button, going over to change their time, coming back to tap again).
> 
> Is this a real use case or more theoretical ?
> 
> Did you check if Combine handles this any differently?

We have an app that uses [`space repetition`](https://en.wikipedia.org/wiki/Spaced_repetition) to learn language (vocabularies). Basically, one repeatedly reviews words over time. There are users who change their time to manipulate the learning. For example, changing to an earlier time will enable them to review words they have seen/reviewed before. It is not recommended to do so but there is also no reason to stop them. We have quite a few events that are controlled by `throttle`. In such case those logics will break since events are not emitted due to time change.

"Did you check if Combine handles this any differently?" 
We have not checked Combine since our minimum deployment is still iOS 11. 

Cheers

**Comment by freak4pc** [comment]
@leonylcatwork thanks for sharing the use case.

I think you shouldn't rely on these sort of operator for business logic (especially not long-running business logic) as that is in general flakier than building something specific to that use case.
 
Also, It's a good idea to check Combine - because If it has the same issue, then it's a "non issue" as far as I'm concerned. If they don't have that issue, we can discuss ways to solve this (but again, this will require more folks from the community who think this is a reasonable use case to support).

**Comment by leonylcatwork** [comment]
@freak4pc That was fast! Will check Combine and see what it does sometime soon.

In issue #1850, quote @danielt1263 

> All timers shut down while the app is in the background. Therefore the time your app spent in the background doesn't count against the throttle time. Also, timers don't use clock time to determine their status so changing the device's clock is irrelevant.

That is what I would think `throttle` should be: irrelevant to device's clock time. I think it is quite natural to use it in buttons that we do not want multiple events firing within a short period of time, and it seems quite elegant. We can also disable the button and re-enable it after job done. But that will require quite a bit of extra work to control the state since some jobs are dispatched to multiple threads. Please enlighten me if I am in the wrong direction. Appreciated.

**Comment by freak4pc** [comment]
Sure, I understand - but that might be more around firing a Timer of your own for your business logic, and not necessarily for throttle/debounce/retry's specific use cases. 

Again, for most use cases, it's highly unlikely having such large intervals that would _also_ have business-logic value that requires validation. 

I do suggest again, that you'd check if Combine's implementation takes care of this, so we can see if there's anything further to dig here. 

Thanks!

**Comment by leonylcatwork** [comment]
Fair enough. Will check out Combine soon. Thanks

**Comment by leonylcatwork** [comment]
@freak4pc Hi again, I just tried Combine, its `throttle` operator works regardless of device time. 

Sample project: https://github.com/leonylcatwork/CombineTest

Steps:
1. run the app.
2. tap the buttons a few times to make sure subscription is working.
3. change device time to an earlier date, say, yesterday.
4. come back to tap the buttons again.
5. will see: Combine button still fires but RxSwift button does not.
6. now change time back to present and tap the buttons again: both should be working.

Really hope you guys would consider it.

Cheers

![image](https://user-images.githubusercontent.com/17819246/117066883-3767af00-ad21-11eb-941d-06a558c4fc23.png)

**Comment by freak4pc** [comment]
Hey, I'm closing this one. The rationale is outline in the accompanying PR: https://github.com/ReactiveX/RxSwift/pull/2341#issuecomment-907615975

Thanks again for the time and effort you put into this! I really appreciate it :)
