### ISSUE TITLE
Swift Compiler Warning - Deprecated protocol inheritance

### ISSUE THREAD

**Issue by osmar106** [ReactiveX/RxSwift#2318]
*If you still want to report issue, please delete above statements before submitting an issue.*

Starting with Xcode 12.5 I am getting this warning from the compiler

_Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead_
_@_functionBuilder' has been renamed to '@resultBuilder_

  _description here_

**Expected outcome**:

No warnings after build

**What actually happens**:

Starting with Xcode 12.5 I am getting this warning from the compiler

_Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead_
_@_functionBuilder' has been renamed to '@resultBuilder_

**Self contained code example that reproduces the issue**:

```swift
@_functionBuilder
    public struct DisposableBuilder {
      public static func buildBlock(_ disposables: Disposable...) -> [Disposable] {
        return disposables
      }
    }



protocol CombineLatestProtocol : class {
    func next(_ index: Int)
    func fail(_ error: Swift.Error)
    func done(_ index: Int)
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.0.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12.5
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
All of these are fixed on the main branch. Please check next time before opening an issue.
Thanks :)
