### ISSUE TITLE
Request: `do` with unretained object

### ISSUE THREAD

**Issue by 417-72KI** [ReactiveX/RxSwift#2324]
**Short description of the issue**:

A new `subscribe` function was added on RxSwift 6.1 ( #2290 )

It would be nice to do similar change with `do` operators.

**current:**

```swift
observable
    .do(onNext: { [weak self] in self?.doSomethingOnDo($0) })
    .subscribe(
        with: self,
        onNext: { $0.doSomethingOnSubscribe($1) }
    )
```

**expected:**

```swift
observable
    .do(
        with: self,
        onNext: { $0.doSomethingOnDo($1) }
    )
    .subscribe(
        with: self,
        onNext: { $0.doSomethingOnSubscribe($1) }
    )
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.2

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
12.5
```

**Comment by isaac-weisberg** [comment]
You can easily write your own extension for this functionality.

**Comment by 417-72KI** [comment]
@isaac-weisberg 
Yes, I know and I could do that.
But I hope that it will be supported by official 😊

**Comment by freak4pc** [comment]
Hey @417-72KI - I think delegating side effects to `self` might be a bit too niche to add this sort of method but I'll keep it in mind for a next release. Closing for now since it is indeed quite easy to add yourself in the time being. Thanks!
