### ISSUE TITLE
Contextual closure type '(Object, ControlEvent<Void>.Element) -> Void' (aka '(Object, ()) -> ()') expects 2 arguments, but 1 was used in closure body

### ISSUE THREAD

**Issue by 417-72KI** [ReactiveX/RxSwift#2325]
**Short description of the issue**:

When using `subscribe(with:onNext:)/bind(with:onNext:)` with `Void` event, 
Void object is set as argument and cannot be ignored.

**Self contained code example that reproduces the issue**:

```swift
// Expected
button.rx.tap
    .bind(
        with: self,
        onNext: { $0.doSomething() } // <- Contextual closure type '(Object, ControlEvent<Void>.Element) -> Void' (aka '(Object, ()) -> ()') expects 2 arguments, but 1 was used in closure body
    ) 

// Workaround (redundant)
button.rx.tap
    .bind(
        with: self,
        onNext: { obj, _ in obj.doSomething() }
    ) 
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.2.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12.5
```

**Comment by freak4pc** [comment]
Sounds like a complaint to Swift that isn't smart enough to support this automatically :) 

In general we can have an overload specializing on `Void` but I think it has very little value inside RxSwift itself. 
I'd suggest that (if it's important for your use case) you add this specialization to your own codebase.

**Comment by 417-72KI** [comment]
@freak4pc 
I created extension in my codebase.
Thank you.
