### ISSUE TITLE
Release 6.2 has no xcframework assets

### ISSUE THREAD

**Issue by janrose-gcx** [ReactiveX/RxSwift#2330]
**Short description of the issue**:

The project README states that all releases starting with 6.* will provice xcframeworks for integration in projects

**Expected outcome**:

Release 6.2 provides those frameworks in the Assets of the GH Release in the same way as 6.1 and 6.0

**What actually happens**:

Only available asset of the 6.2 is the Xcode project. No prebuilt frameworks

**Self contained code example that reproduces the issue**:

-

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

-

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

-

**Comment by freak4pc** [comment]
Hey @janrose-gcx ,
I've uploaded all xcframeworks except for RxTest - not too sure why but I can't seem to get a binary for it. 
If you need that one specifically I'd appreciate you trying to build it on your side and send the binary to me. 

Thanks!

**Comment by hyperspacemark** [comment]
FWIW, I was able to produce an RxTest XCFramework with the following incantations. These assume that RxSwift is checked out to `~/Development/RxSwift` and that the `archives` and `xcframeworks` directory exist inside the checkout. It also is only producing slices for iOS and iOS simulator.

```sh
xcodebuild archive \
	-workspace Rx.xcworkspace \
	-scheme RxTest \
	-destination "generic/platform=iOS" \
	-archivePath "archives/RxTest-iOS" \
	SKIP_INSTALL=NO \
	BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
	ENABLE_TESTING_SEARCH_PATHS=YES

xcodebuild archive \
	-workspace Rx.xcworkspace \
	-scheme RxTest \
	-destination "generic/platform=iOS Simulator" \
	-archivePath "archives/RxTest-iOS-Simulator" \
	SKIP_INSTALL=NO \
	BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
	ENABLE_TESTING_SEARCH_PATHS=YES

xcodebuild -create-xcframework \
           -framework "${HOME}/Development/RxSwift/archives/RxTest-iOS.xcarchive/Products/Library/Frameworks/RxTest.framework" \
           -debug-symbols "${HOME}/Development/RxSwift/archives/RxTest-iOS.xcarchive/dSYMs" \
           -debug-symbols "${HOME}/Development/RxSwift/archives/RxTest-iOS.xcarchive/BCSymbolMaps" \
           -framework "${HOME}/Development/RxSwift/archives/RxTest-iOS-Simulator.xcarchive/Products/Library/Frameworks/RxTest.framework" \
           -debug-symbols "${HOME}/Development/RxSwift/archives/RxTest-iOS-Simulator.xcarchive/dSYMs" \
           -output xcframeworks/RxTest.xcframework
```

We weren't able to unit test our application on Xcode 12.5 the 6.1.0 XCFrameworks but these work.

**Comment by keithcml** [comment]
@hyperspacemark @freak4pc can you folks help upload the RxTest.xcframework or send to me? super thanks.
