### ISSUE TITLE
not using scripts?

### ISSUE THREAD

**Issue by wogus3602** [ReactiveX/RxSwift#2333]
not using scripts?
An error occurred when trying to run all-test.sh.

I referred to "[CONTRIBUTING.md](https://github.com/ReactiveX/RxSwift/blob/main/CONTRIBUTING.md)".

```
The domain/default pair of (~/Git/RxSwift/RxSwift/RxSwift/Info.plist, CFBundleShortVersionString) does not exist
```

**Comment by freak4pc** [comment]
Hey @wogus3602, I need to fix the contribution guide. That script is mainly relevant for our CI. 
You should just run the test suite locally and it should work fine. Let me know if you're having any trouble.
