### ISSUE TITLE
Confuse about  `static var rx = Reactive<ReactiveBase>.Type` 

### ISSUE THREAD

**Issue by Gnoah89** [ReactiveX/RxSwift#2337]
in  Reactive.swift file，protocol ReactiveCompatible define a static variable 

```swift

/// A type that has reactive extensions.
public protocol ReactiveCompatible {
     /// ....
 
    /// Reactive extensions.
    static var rx: Reactive<ReactiveBase>.Type { get set }

   /// ....
}

```

but  `Reactive<ReactiveBase>`  only has constructor and  `public init(_ base: Base)` need a instantiate object.... 

So It looks like useless. So am i missing something? Can you tell me how to use the variable

**Comment by freak4pc** [comment]
The point is extending with static properties. 

For example
```swift
extension Reactive where Base == MyClass {
    static var thing: Observable<Bool> { ... } 
}
```

Then you can access `MyClass.rx.thing`. 

Regardless, please reserve "How do I do X?" questions to the slack channel (http://slack.rxswift.org). We use GitHub only for bugs, etc. 

Thanks!
