### ISSUE TITLE
Is there a timeout operator?

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#234]
Is there a timeout operator?
http://reactivex.io/documentation/operators/timeout.html

AVAsset has a function called loadValuesAsynchronouslyForKeys. I'm going to use RxSwift to deal with it. But if an HTTP resource cannot be got, this method will wait until 60 seconds to return. So there is a need  to limit the time for this async fun to return.

**Comment by frogcjn** [comment]
I can use

            .takeUntil(timer(2.0, MainScheduler.sharedInstance))

but there is no error will return. Just complete.

**Comment by IanKeen** [comment]
You could create a 'timeout' observable that simply errors after a set duration and merge that with your request.. possibly not ideal but you could abstract it into something nice

**Comment by frogcjn** [comment]
@IanKeen , this request is system triggered, which I cannot change the timeout property of the NSURLRequest.

**Comment by IanKeen** [comment]
right, but you can combine it with another observable which you do control the timeout of (unsure if this is even the best way... just a suggestion on how you might tackle the problem)

**Comment by frogcjn** [comment]
@IanKeen 

like

        .takeUntil(timer(2.0, MainScheduler.sharedInstance))
but there is no error will return. Just complete.

So I should have a single result ensure operator like this

                .toArray()
                .map { array -> Bool in
                    if array.count > 1{ throw CommonError.MoreThanOneResult}
                    if array.count < 1{ throw CommonError.NoResult}
                    return array.first!
                }

**Comment by IanKeen** [comment]
I was thinking perhaps something like 

```
        return create { observer in
            let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(2.0 * Double(NSEC_PER_SEC)))
            dispatch_after(delayTime, dispatch_get_main_queue()) {
                observer.onError(error)
            }
        }
```

**Comment by frogcjn** [comment]
@IanKeen

Yes, you're right.

There also needs a flag to mark whether the function was returned by system.
        return create { observer in
           var returned = false
            let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(2.0 * Double(NSEC_PER_SEC)))
            dispatch_after(delayTime, dispatch_get_main_queue()) {
                if !returned { observer.onError(error) }
            }
            someSystemAsyncFunc{
                  returned = true
                   observer.onNext(...)
                   observer.onCompleted()
            }
        }

**Comment by kzaher** [comment]
Hi,

I believe timeout should be something like

```
sequenceOf(originalObservable, failWith(testError).delaySubscription(timeoutInterval, MainScheduler.sharedInstance)).merge()
```

:)

We don't currently have `timeout` operator, but that is a good idea about optimized version of useful operator we would want to have.

**Comment by frogcjn** [comment]
Thanks! Your solution is perfect.

**Comment by frogcjn** [comment]
@kzaher
I have tested, this solution will lead to a result that there always an error.

merge will not be completed after first one completed.

**Comment by kzaher** [comment]
Ah, my bad.

What about this
```
originalObservable.amb(failWith(testError).delaySubscription(timeoutInterval, MainScheduler.sharedInstance))
```

:)

**Comment by frogcjn** [comment]
@kzaher 
Yes, that works. Thanks again!

**Comment by fpillet** [comment]
Think you can close this one now

**Comment by bontoJR** [comment]
:+1:
