### ISSUE TITLE
Rxswift provides version 0.0.0

### ISSUE THREAD

**Issue by avik-efcom** [ReactiveX/RxSwift#2354]
**Short description of the issue**:

Hi everyone,
I try to work with sdk of polar `https://github.com/polarofficial/polar-ble-sdk`
when I start run the project I got this message
```
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
 Referenced from: /private/var/containers/Bundle/Application/DCFDE6CE-2C32-48A2-BB5A-61B33552082E/XXX.test.app/Frameworks/PolarBleSdk.framework/PolarBleSdk
 Reason: Incompatible library version: PolarBleSdk requires version 1.0.0 or later, but RxSwift provides version 0.0.0
```
I run this command on the xcframework folder
`otool -L RxSwift.xcframework/ios-arm64_armv7/RxSwift.framework/RxSwift`
and got this output
```
RxSwift.xcframework/ios-arm64_armv7/RxSwift.framework/RxSwift (architecture armv7):
	@rpath/RxSwift.framework/RxSwift (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1774.101.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1200.2.41)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1.6.0, weak)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0, weak)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 4.40.2)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 20.0.0)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
RxSwift.xcframework/ios-arm64_armv7/RxSwift.framework/RxSwift (architecture arm64):
	@rpath/RxSwift.framework/RxSwift (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1774.101.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1200.2.41)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1.6.0, weak)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0, weak)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 4.40.2)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 20.0.0)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
```
I download the xcframework from here
`https://github.com/ReactiveX/RxSwift/releases/tag/6.2.0
`
**Expected outcome**:
 
app running

**What actually happens**:
app crash

**Self contained code example that reproduces the issue**:

```swift + objc
no code just run the app

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.2.0

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**: 

```
12
```
**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [X] xcframework

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Sorry but this sounds like a support question for the Polar SDK repo. Seems to me you're not linking RxSwift correctly, though.

**Comment by avik-efcom** [comment]
Why you think is Polar SDK problem?
I import(drag and drop) the RxSwift.xcframework into my project and call the command `otool -L RxSwift.xcframework/ios-arm64_armv7/RxSwift.framework/RxSwift` to get information about the framework and got the version is 0.0.0
As I understand otool -L command use to view the xcframework versions if it say 0.0.0 the problem is on RxSwift, no?

And I try old Polar SDK version and got the same error:
`Incompatible library version: PolarBleSdk requires version 1.0.0 or later, but RxSwift provides version 0.0.0`

Did I do something wrong?
Here some explain I use to import the xcframework [https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/](https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/
)

I open a new project and try import it again and got the same error..

**Comment by freak4pc** [comment]
Sorry, but as mentioned, we don't provide this kind of support. This is about integrating RxSwift into a different SDK, and not simply using RxSwift in your project. In general we don't usually support Package Managers or bundling. 

Perhaps our Slack channel could be a better choice: http://slack.rxswift.org
