### ISSUE TITLE
subclass UITextView and set delegate as self will cause DelegatePorxy works wrong and crash

### ISSUE THREAD

**Issue by Josscii** [ReactiveX/RxSwift#2358]
I got a UITextView subclass, setting its delegate to self.

```swift
class AutoReszingTextView: UITextView, UITextViewDelegate {
  ...
  delegate = self
  ...
}
```

and when I do `rx.didBeginEditing`, it will crash at:

```
-[RxCocoa.RxTextViewDelegateProxy keyboardInputChangedSelection:]: unrecognized selector sent to instance 
```

After doing some research and reading some source code, I think this behavior is somewhat a bug of RxCocoa.

The UIKit will call keyboardInputChangedSelection on textView when textView is begin editing, and as shown below, keyboardInputChangedSelection is a private method of UITextView.

https://developer.limneos.net/index.php?ios=13.1.3&framework=UIKitCore.framework&header=UITextView.h

But the wired thing is that UIKit will first ask textview's delegate if he can respond to the keyboardInputChangedSelection selector, and its delegate is a DelegatePorxy instance.

in DelegatePorxy.swift:

```swift
override open func responds(to aSelector: Selector!) -> Bool {
            return super.responds(to: aSelector)
                || (self._forwardToDelegate?.responds(to: aSelector) ?? false)
                || (self.voidDelegateMethodsContain(aSelector) && self.hasObservers(selector: aSelector))
}
```

while self._forwardToDelegate is our textView, the second condition answers true, but DelegatePorxy has no implemention of keyboardInputChangedSelection, and cause this crash.

I think this could be avoid by some way, and maybe there are other system views like UITextField works the same way.

anyone can help?

**Comment by freak4pc** [comment]
Hey @Josscii - 
Sorry but I still don't think this is a bug and it's not a use case we support right now. 
If you want to create a PR or investigate it yourself we'll be happy to add it, but it's not a priority of RxCocoa right now.

You might want to check our Slack for specific code-level support http://slack.rxswift.org
