### ISSUE TITLE
Problem shipping to App Store with XCFramework

### ISSUE THREAD

**Issue by avik-efcom** [ReactiveX/RxSwift#2361]
**Short description of the issue**:
I try to archive the app IOS after I try to distribute it to the app store I got this error
`ERROR ITMS-90056: "This bundle Payload/HeartTrends.app/Frameworks/RxSwift.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion`
this is not relate to the code just the build

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
 6.2.0

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
12
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [X] XCFramework

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hey @avik-efcom - That's interesting, we actually do ship that Info.plist with that key:
https://github.com/ReactiveX/RxSwift/blob/main/RxSwift/Info.plist#L21-L22

I'm not entirely sure if it's something specifically related to the bundling of the xcframework but I'll try to take a look at it a bit later on. We do have consumers using XCFramework(s) without an issue so it might also just be some configuration issue worth looking into.

**Comment by lexrus** [comment]
Same issue.
<img width="880" alt="Screen Shot 2021-09-24 at 3 36 45 PM" src="https://user-images.githubusercontent.com/219689/134636634-12a1cd8f-1de4-466d-928a-54048fd856ab.png">

**Comment by freak4pc** [comment]
I've shipped (and seen others ship) with these XCFrameworks several times, so I'm not sure If this is entirely an issue.
Can you see this possible solution from the Firebase repo? 

https://github.com/firebase/firebase-ios-sdk/issues/5562#issuecomment-626815650

I'll still look into fixing it but it's not a huge priority ATM.

**Comment by lexrus** [comment]
Thank you for your rapid reply. I guess it's not the same problem somehow. I just manually added CFBundleVersion to every Info.plist embedded inside these xcframeworks. And uploaded the IPA to App Store successfully.

**Comment by freak4pc** [comment]
Seems this is a non-issue, based on the firebase / Carthage issues linked above.
