### ISSUE TITLE
Xcode 13 RC: Failed to build module 'RxCocoa'; this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by osmar106** [ReactiveX/RxSwift#2363]
**Short description of the issue**:

  _Cannot build app using Xcode 13 RC, we are using Carthage._

**Expected outcome**:

  _Be able to build the app_

**What actually happens**:

  _When Xcode is building we receive the following errors:_

_"Cannot load underlying module for 'RxCocoa'"_

_"Failed to build module 'RxCocoa'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK."_

_"No such module 'RxCocoaRuntime'"_

**Self contained code example that reproduces the issue**:

```swift
import RxCocoa

import RxCocoaRuntime
  
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _6.2.0_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 13 RC
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode 13 RC and Xcode 12.5.1)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by yeyocp** [comment]
Hello.

I have the same issue. I am receiving the same error that osmar106 mentions:

_"Failed to build module 'RxCocoa'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK."_

Thank you.

**Comment by mrcperello** [comment]
Same issue here :(

**Comment by claralou** [comment]
Hi, same issue happens to me, :'(

**Comment by upeugene** [comment]
same issue

**Comment by freak4pc** [comment]
Please provide a small project reproducing the issue. 

Thanks

**Comment by upeugene** [comment]
> Please provide a small project reproducing the issue.

any project with the latest XCode 13

**Comment by freak4pc** [comment]
Again, we ask for people to share their own sample projects. 
You can't expect a maintainer to spend their free time solving your issue if you won't spend 5 minutes making a repro projects to help out, right? :)

**Comment by osmar106** [comment]
Check this repo, RxCocoa branch to test this error https://github.com/yeyocp/CarthageTestForXcode13/commits/RxCocoa

Also, if you remove "import RxCocoa" the app builds but then crash

`dyld[97462]: Library not loaded: @rpath/RxCocoaRuntime.framework/RxCocoaRuntime
  Referenced from: /Users/orodrgut/Library/Developer/Xcode/DerivedData/CarthageTestForXcode13-gpzicnensoezwphkzlzpurgzykek/Build/Products/Debug-iphonesimulator/RxCocoa.framework/RxCocoa
  Reason: tried: '/Users/orodrgut/Library/Developer/Xcode/DerivedData/CarthageTestForXcode13-gpzicnensoezwphkzlzpurgzykek/Build/Products/Debug-iphonesimulator/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Downloads/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/usr/lib/swift/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Downloads/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Library/Developer/CoreSimulator/Devices/B0580461-22FF-4AC8-91ED-68BEE713F06F/data/Containers/Bundle/Application/BA4951C1-7D85-49A7-8375-72551FF424FD/CarthageTestForXcode13.app/Frameworks/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Library/Developer/CoreSimulator/Devices/B0580461-22FF-4AC8-91ED-68BEE713F06F/data/Containers/Bundle/Application/BA4951C1-7D85-49A7-8375-72551FF424FD/CarthageTestForXcode13.app/Frameworks/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Downloads/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file)
Library not loaded: @rpath/RxCocoaRuntime.framework/RxCocoaRuntime
  Referenced from: /Users/orodrgut/Library/Developer/Xcode/DerivedData/CarthageTestForXcode13-gpzicnensoezwphkzlzpurgzykek/Build/Products/Debug-iphonesimulator/RxCocoa.framework/RxCocoa
  Reason: tried: '/Users/orodrgut/Library/Developer/Xcode/DerivedData/CarthageTestForXcode13-gpzicnensoezwphkzlzpurgzykek/Build/Products/Debug-iphonesimulator/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Downloads/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/usr/lib/swift/RxCocoaRuntime.framework/RxCocoaRuntime' (no such file), '/Users/orodrgut/Downloads/Xcode 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Applications/Xcode.app/Contents/Developer/Tool`

**Comment by freak4pc** [comment]
Hey @osmar106 and @upeugene 
I just checked your sample project and as far as I can tell this is a Carthage issue and not an RxSwift issue.

I opened your project, removed the existing frameworks, dragged the xcframeworks manually like so: 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/605076/135348896-0a7714b3-29f6-46a5-b291-d531985493ee.png">

Everything seems to work fine:
![image](https://user-images.githubusercontent.com/605076/135348957-9eabe50b-13bf-4fe0-97f9-b70b4cf5a78d.png)

I couldn't even get Carthage to pull the pre-built xcframeworks correctly from this repo. 
Unfortunately I'm not a Carthage fan myself and don't have the capacity to support Package Manager-specific issues like this (which seems like some configuration issue). 

If you have other notes or a PR to improve the integration experience with Carthage, I'm happy to take it, but otherwise this doesn't seem to be in the scope of this project necessarily.

**Comment by disbelief** [comment]
Has anyone found a solution to this problem with Carthage? I'm stuck on the same error when trying to `import RxCocoa`. Oddly none of the other Carthage frameworks I'm using have this problem.

From some digging around online it seems that maybe the `BUILD_LIBRARY_FOR_DISTRIBUTION` setting for the RxCocoa package needs to be set to `YES` instead of `NO` to enable [library evolution support](https://www.swift.org/blog/library-evolution/)?

**Comment by disbelief** [comment]
This might have something to do with XCode 13.4.1 update changing the Swift version from 5.6 to 5.6.1 (lol).

A "solution" which resolved the problem for me: wipe all of the frameworks from the `Carthage/Builds/` and `Carthage/Checkouts/` and then run `carthage update` again with the `--no-use-binaries` flag:

```
rm -rf Carthage/Builds/*
rm -rf Carthage/Checkouts/*
carthage update --no-use-binaries --use-xcframeworks --platform iOS
```

ymmv 🤷
