### ISSUE TITLE
xCode13 CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

### ISSUE THREAD

**Issue by PierreBrisorgueil** [ReactiveX/RxSwift#2371]
Hello, just ran into this with SPM : 

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-13-release-notes

> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
> 
> Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support 

`CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'RxSwift' from project 'RxSwift')
`

**Comment by freak4pc** [comment]
RxSwift doesn't depend on Combine, though. 
Can you share actual information about the issue, a reproducible project, etc.?

**Comment by paulsUsername** [comment]
Any joy fixing this?

**Comment by freak4pc** [comment]
Again, I'm not sure how this is related to RxSwift. 
Plus, Apple mentioned they fixed this issue on latest Xcode versions, please try those.

**Comment by arthursalgado** [comment]
Follow these steps

1. Clear de DerivedData folder
- rm -rf ~/Library/Developer/Xcode/DerivedData

2. Clean Xcode project
- cmd + shift + k 

3. Close Xcode project, maybe even reboot the mac (if you like)

Try again. 
The first step was the crucial step for me, but step 2 and 3 could help as well.
