### ISSUE TITLE
RxTest shows Library not loaded: /usr/lib/swift/libswiftXCTest.dylib

### ISSUE THREAD

**Issue by keithcml** [ReactiveX/RxSwift#2376]
**Short description of the issue**:

I am developing a framework using RxSwift, the framework contains a test target and I linked RxTest to the test target on Xcode 13.1. I install via dragging RxTest.xcframework to `Link Binary with Libraries`.

I got another project running Xcode 12.5.1 with no issue. (But I use RxSwift 5 in that project.)

**Expected outcome**:

Run the tests successfully.

**What actually happens**:

Tests launch failure and showing `Library not loaded: /usr/lib/swift/libswiftXCTest.dylib`.
If I remove RxTest, it runs okay.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/5032142/141235676-a7d2dfb7-15c1-4792-8291-005090ae33a8.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxTest 6.1.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 13.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] xcframeworks
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Please share a reproducible sample project.

**Comment by sarpsolakoglu** [comment]
The `RxTest.xcframework` is missing for the 6.2.0 release, so I've tried to use the one from 6.1.0 and getting the same error.

**Comment by freak4pc** [comment]
Closed with no reply from op.
