### ISSUE TITLE
Carthage build do not produces always RxSwift.xcframework but random result

### ISSUE THREAD

**Issue by BaptisteSansierra** [ReactiveX/RxSwift#2380]
**Short description of the issue**:

carthage (0.38.0) is randomly not producing the expected framework **RxSwift.xcframework**

- In an empty directory, I create a **Cartfile** containing only the following line  :
`github "ReactiveX/RxSwift" "6.2.0"`
and then execute the command
`carthage update --platform iOS --use-xcframeworks`

**Expected outcome**:

I expect the file **RxSwift.xcframework** to appears after a carthage build in **Carthage/Build/**

**What actually happens**:

A carthage build will randomly creates, in **Carthage/Build/**, one of the following :
- RxBlocking.xcframework  
- RxCocoa.xcframework        
- RxCocoaRuntime.xcframework 
- RxRelay.xcframework        
- RxSwift.xcframework

I have no way to know if RxSwift will be there.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.2.0

**Platform/Environment**

  - [ ] iOS
  - [x] macOS : 11.4
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
 13
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (11.3.1, 12.5, 13)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
If it works sometimes but not all the time, it sounds like a Carthage but and not an RxSwift bug.

**Comment by BaptisteSansierra** [comment]
indeed
https://github.com/Carthage/Carthage/issues/3243
