### ISSUE TITLE
RxSwift doesn't react to changes of Japanese keyboard

### ISSUE THREAD

**Issue by ashtiani** [ReactiveX/RxSwift#2396]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://slack.rxswift.org/) first. :warning: 

:warning: Please take you time to fill in the fields below. If we aren't provided with this basic information about your issue we probably won't be able to help you and there won't be much we can do except to close the issue :( :warning:

*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

 have a search bar that gives suggestions based on the user input on search bar, in my code it binds the search bar text to my view model. 

Everything works as expected. On Japanese keyboard however, it doesn't react to changes I have on the keyboard unless I accept the marked text. So basically it only react to unmarked text.

What is the best to make it work. I only found this, however I still cannot figure out the best way to make it work.

So when I type さ it only react to change if I select one of the words from the recommendation bar on top of the keyboard.

**Expected outcome**:

  React to all user input.

**What actually happens**:

  Only reacts to accepted/marked text.

**Self contained code example that reproduces the issue**:

```swift
  searchBar.rx
    .text
    .orEmpty
    .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
    .debounce(.milliseconds(250), scheduler: MainScheduler.instance)
    .skip(1)
    .distinctUntilChanged()
    .bind(to: viewModel.searchText)
    .disposed(by: disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  13.2.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
Hey, thanks for the issue :) 

Since this is relatively a nice issue and I don't have a huge capacity to debug in a different language, I'd appreciate your help with debugging the source code and try to scope the issue down. Let me know if this is something you could help with.

Thanks!

**Comment by freak4pc** [comment]
No reply for over 2 months. Closing.
