### ISSUE TITLE
RxSwift 6.5.0 XCFramework breaks console po command

### ISSUE THREAD

**Issue by pmanuelli** [ReactiveX/RxSwift#2397]
**Short description of the issue**:

With RxSwift and RxCocoa 6.5.0 integrated using the precompiled XCFrameworks, the object debug command (`po`) on the Xcode console stops working.

When trying to print an object with the `po` command I get an error. This happens with any object that I try to debug on the console.

This happens with the XCFrameworks integrated manually on the project or using CocoaPods.

**Expected outcome**:

The object is printed on the console normally.

**What actually happens**:

An error is printed on the console:

```
po myObject

error: virtual filesystem overlay file '/Users/shaimishali/Library/Developer/Xcode/DerivedData/Rx-dxolnknlpjuxspdqvtqlinrlckhg/Build/Intermediates.noindex/ArchiveIntermediates/RxCocoa/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxCocoa.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/shaimishali/Library/Developer/Xcode/DerivedData/Rx-dxolnknlpjuxspdqvtqlinrlckhg/Build/Intermediates.noindex/ArchiveIntermediates/RxCocoa/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxCocoa.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

The error complains about RxCocoa. But if I remove it and leave only RxSwift it now complains about RxSwift:

```
po myObject

error: virtual filesystem overlay file '/Users/shaimishali/Library/Developer/Xcode/DerivedData/Rx-dxolnknlpjuxspdqvtqlinrlckhg/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxSwift.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/shaimishali/Library/Developer/Xcode/DerivedData/Rx-dxolnknlpjuxspdqvtqlinrlckhg/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxSwift.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

I see that the file's path contains what seems to be a local path `/Users/shaimishali/Library/Developer/Xcode/DerivedData/`

**Self contained code example that reproduces the issue**:

Demo project in:

[https://github.com/pmanuelli/RxSwiftXCFrameworkCocoapodsExample](https://github.com/pmanuelli/RxSwiftXCFrameworkCocoapodsExample)

The repo contains two projects integrating RxSwift XCFrameworks using cocoapods. [One of them has the xcframeworks locally](https://github.com/pmanuelli/RxSwiftXCFrameworkCocoapodsExample/tree/main/LocalPodspecsExample). I recommend using that one.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.5.0 (with XCFramework)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
13.2.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

It's integrated using custom podspecs files but I tried also integrating the frameworks manually.

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by urbanusjam** [comment]
I ran into the same issue. Please submit a fix, please!

**Comment by ifiszer** [comment]
I'm also facing this issue.

**Comment by rfigini** [comment]
I have this same issue.

**Comment by cravacuore** [comment]
Same issue here.

**Comment by freak4pc** [comment]
Thanks for the report! I'm not entirely sure this is an RxSwift-specific issue. Are you able to use `po` with other xcframeworks?

**Comment by freak4pc** [comment]
Interesting Swift compiler bug. Could you please try these binaries?
https://wetransfer.com/downloads/3db4a4695085a80795c34c857924211c20220207194358/4fcdac8b1a544801593ece100880837620220207194410/e58ffc

**Comment by pmanuelli** [comment]
Thank you for the answer Shai.

Sadly, I get the same error.

```
error: virtual filesystem overlay file '/Users/shaimi/Library/Developer/Xcode/DerivedData/Rx-fnydthwmdxbkewbwclvzkrlxeqab/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxSwift.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/shaimi/Library/Developer/Xcode/DerivedData/Rx-fnydthwmdxbkewbwclvzkrlxeqab/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/Rx.build/Release-iphonesimulator/RxSwift.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

**Comment by freak4pc** [comment]
I'm not entirely sure there's much I can do. Seems like an issue with the compiler. 
Care to open a bug with bugs.swift.org ?

**Comment by freak4pc** [comment]
Closing this for the time being as there doesn't seem like there's anything I can do with it. If you think otherwise or find new information, feel free to comment here again. Thanks!
