### ISSUE TITLE
Deprecated warnings when targeting iOS9

### ISSUE THREAD

**Issue by zhigang1992** [ReactiveX/RxSwift#240]
Using CocoaPods to bring in RxSwift and RxCocoa.

<img width="256" alt="screen shot 2015-11-08 at 6 08 33 am" src="https://cloud.githubusercontent.com/assets/1057756/11020272/40d982ee-85df-11e5-84e6-e8aca3645c2f.png">

Tried everything to get rid of it, 

1. `inhibit_all_warnings` in podfile.
2. Build settings inhibit all warning.
3. Set deprecated usage to not generate warning.

none worked...

Quiet annoying, plz help :(

**Comment by frogcjn** [comment]
change 

platform :ios, '9.0'

to

platform :ios, '8.0'

in your pod file, this is a quick solution

**Comment by zhigang1992** [comment]
@frogcjn But I've other dependencies that are only available on iOS9.

**Comment by frogcjn** [comment]
Go to Pods project settings, choose RxCocoa Target, manually set its target to iOS 8.0

**Comment by zhigang1992** [comment]
Thx for the help,
But it seems like if I change it to anything lower than iOS9, it won't compile

```
/Pods/RxCocoa/RxCocoa/Common/CLLocationManager+Rx.swift:11:8: Module file's minimum deployment target is ios9.0 v9.0: /Users/kylefang/Library/Developer/Xcode/DerivedData/Pomotodo-ckkvmdbimwsjsebbpgblmgvitklb/Build/Products/Debug-iphonesimulator/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule
```

**Comment by kzaher** [comment]
Hi @zhigang1992 ,

I'm sorry you are having those warnings. I'm not sure I could help you better then @frogcjn has tried so far.

What I can do is to try to add preprocessor conditions or exclude those classes by some other means for ios versions >= 9 in one of the upcoming releases. Suggestions how we can do this the easiest are welcome ofc :)

I understand that this is not ideal, but not sure I have any other suggestions other then those @frogcjn already made :)

**Comment by zhigang1992** [comment]
@kzaher no worries, thx

**Comment by orta** [comment]
You can also remove warnings for a specific project: `pod 'TapkuLibrary', :inhibit_warnings => true`.
