### ISSUE TITLE
RxSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by dverma96** [ReactiveX/RxSwift#2400]
**I am using Apple M1 chip**

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
13.2.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by freak4pc** [comment]
I'm on CocoaPods & M1 with no issues. Please provide a reproducible example. Thanks :)

**Comment by HyunjoonKo** [comment]
I had the same error as you. Have you set the simulator setting in Target → Build Settings → Excluded Architecture to arm64? You have to delete this to build for the simulator.

Setting it to arm64 is a useful option on Intel Macs, but not on Apple silicon.

**Comment by indama** [comment]
@HyunjoonKo Thank you for your reply but It is not deletable arm 64 from Exclude Architecture.
