### ISSUE TITLE
Prebuilt XCFrameworks versus Carthage

### ISSUE THREAD

**Issue by gyulavoros** [ReactiveX/RxSwift#2403]
**Short description of the issue**:

Given the following `Cartfile`:
```
github "ReactiveX/RxSwift" "6.5.0"
```

By running: `carthage update --use-xcframeworks --platform iOS`, Carthage will try and download the prebuilt archives:
```
Checking out RxSwift at "6.5.0"
*** xcodebuild output can be found in /var/folders/vn/zg31l__d6hg2qry9fmn9kfqc0000gn/T/carthage-xcodebuild.jfDxcz.log
*** Downloading RxSwift binary at "Atlas"
```

In practice, only one of the frameworks gets downloaded:
```
Carthage/Build/RxBlocking.xcframework
```

If I understand this correctly, [Carthage expects one single ZIP archive to be present](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files) as an artifact next to the GitHub release.

🚫 So instead of:
```
RxBlocking.xcframework.zip
RxCocoa.xcframework.zip
RxRelay.xcframework.zip
RxSwift.xcframework.zip
RxTest.xcframework.zip
```

✅ It is supposed to be:
```
RxSwift.xcframework.zip (which contains all: RxBlocking.xcframework, RxCocoa.xcframework, RxRelay.xcframework, RxSwift.xcframework, RxTest.xcframework)
```

**Expected outcome**:

Given that I'm **not using** the `--no-use-binaries` flag with Carthage, all XCFrameworks should be downloaded from the GitHub release.

**What actually happens**:

Only RxBlocking is present after Carthage update/bootstrap.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.5.0 release

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is it to reproduce? (chances of successful reproduction after running the self-contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 13.2.1 (13C100)
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small codebase
  - [x] I have a significant codebase

**Comment by olejnjak** [comment]
Well anyone? This is quite significant issue when using Carthage...

**Comment by freak4pc** [comment]
Hey there, 
As always, Carthage creates definition that cause a headache for the rest of us :) 

Forcing developers to download 5 frameworks when they only need RxSwift, for example. (Or downloading the entirety of Firebase dependencies for a single dependency) is just bananas. Sometimes I just don't get what Carthage folks have in mind. 

Regardless, this seems like a required fix. I'll try to take care of it soon. Thanks!

**Comment by gyulavoros** [comment]
@freak4pc Is there anything I can support you with? Shall I take a stab at making the changes in [make-xcframeworks.sh](https://github.com/ReactiveX/RxSwift/blob/main/scripts/make-xcframeworks.sh) (I assume)?

**Comment by freak4pc** [comment]
@gyulavoros Can you please try 6.5.0 and see if it works correctly now? You might need to clear your Carthage cache for this to work.

**Comment by gyulavoros** [comment]
@freak4pc Carthage tries to compile `6.5.0` from source:

```
carthage update --cache-builds --use-xcframeworks --platform iOS
*** Cloning RxSwift
*** Checking out RxSwift at "6.5.0"
*** No cache found for RxSwift, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/vn/zg31l__d6hg2qry9fmn9kfqc0000gn/T/carthage-xcodebuild.TlVfZT.log
*** Downloading RxSwift binary at "Atlas"
*** Building scheme "RxBlocking" in Rx.xcworkspace
*** Building scheme "RxRelay" in Rx.xcworkspace
```

I think this is due to the strict naming convention, now the release contains `RxSwift.zip` and Carthage is looking for `RxSwift.xcframework.zip`.
