### ISSUE TITLE
Can't run RxSwift on M1 computer on simulator

### ISSUE THREAD

**Issue by johannwerner** [ReactiveX/RxSwift#2409]
**Short description of the issue**:

import swift package manager using main branch. 
write import code
import RxSwift
run app on any simulator

**Expected outcome**:

able to import RxSwift

**What actually happens**:

could not find module 'RxSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator,

**Self contained code example that reproduces the issue**:

```swift
import RxSwift
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

[  _version or commit here_](https://github.com/ReactiveX/RxSwift/commit/7741a11cb4252c379c8e034508cb1b92b8b40427)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
 Version 13.2.1
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] swift package manager 

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

 

The solution would be to change excluded architectures for any ios simulator for debug at least maybe release as well. 
"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
Related to this issue https://github.com/ReactiveX/RxSwift/issues/2261

**Comment by freak4pc** [comment]
Firstly, Doesn't seem like an RxSwift issue, to be honest.
Second, I just created an empty project with RxSwift on my M1 Pro and it works just fine. Please attach a repro.

**Comment by johannwerner** [comment]
Thanks I was able to run it now. Actually the problem was I set the project to 
"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64; and this caused the issue. I remember adding this in the beginning because the app wasn't running and even though it didn't fix this I never removed it.
