### ISSUE TITLE
Is there a nicer way of observing object changes?

### ISSUE THREAD

**Issue by lyptt** [ReactiveX/RxSwift#241]
I've got a very basic example going with the latest RxSwift 2 version, admittedly I'm fairly new to the rx way of doing things:

```swift
combineLatest(firstNameField.rx_text, lastNameField.rx_text) { UserModel(firstName: $0, lastName: $1) }
	.subscribeNext { [unowned self] in
		self.user = $0
	}
	.addDisposableTo(disposeBag)

(self.rx_observe("user") as Observable<UserModel?>)
	.map { user in
		return user?.isValid() as Bool!
	}
	.bindTo(signInButton.rx_enabled)
	.addDisposableTo(disposeBag)
```

What I'm attempting to do is generate a new `UserModel` from two observables, and bind the result of that new model's isValid() function to a button's enabled state.

I've found that KVO works for this use case, but it requires using classes and dynamic variables to do so. Is there a better way of achieving this without KVO?

**Comment by dtartaglia** [comment]
I'm pretty new as well, but I think if you make your user variable a `Variable` then you will be able to observe it without using KVO.

i.e.: `let user = Variable<UserModel?>()`

Then in your `subscribeNext` do `self.user.value = $0`

And observe changes to `user` by doing `user.subscribeNext { self.user.value.isValid() as Bool! }`

Something like that at least.

**Comment by lyptt** [comment]
Oh cool! That looks like exactly what I need. I'll give that a go. Thanks!

**Comment by kzaher** [comment]
Thnx @dtartaglia for answering.

Hi @lyptt, I would just like to add that you are trying to solve this problem imperatively :) Our example app is lacking good MVVM examples for now, but we'll improve it in future :)

**Comment by lyptt** [comment]
@kzaher yes it's probably a bit more imperative than you should be with rx, I'm trying to slowly easy my way into it bit by bit! The examples you've currently got are a bit beyond my comprehension at the moment :)

**Comment by kzaher** [comment]
Yeah, we have two problems.
* how to educate new users
* how to demonstrate advanced usages

Those two things don't mix well together :) We'll need to find some better ways to satisfy all of those cases :)

**Comment by kzaher** [comment]
We've released some KVO changes that should help with this issue, but using KVO for non ObjC is discouraged.

We'll still need to work on examples, but closing this for now.
