### ISSUE TITLE
Please add @propertyWrapper attribute for BehaviourRelay

### ISSUE THREAD

**Issue by Cy-4AH** [ReactiveX/RxSwift#2410]
It would be nice feature for BehaviourRelay to have `@propertyWrapper` attribute.
It will be easy to make existing properties Observable, will not needed to rewrite existing code.

**Comment by freak4pc** [comment]
Hey, thanks for the feature request ;) 
It's something I've considered but decided to steer away from, for now:

1. It's quite easy making this yourself (Example: https://twitter.com/freak4pc/status/1215375493819764743), and one can just choose to add it

2. It promotes usage of imperative practices in reactive code

3. As opposed to `@Published`, it doesn't perform any "magic" in UIKit, or SwiftUI. The huge value of `@Published` is in the fact it interacts with `ObservableObject`/`StateObject`.

Thanks for the suggestion and request, though.
