### ISSUE TITLE
Carthage as a Static Library will crash

### ISSUE THREAD

**Issue by lcghh** [ReactiveX/RxSwift#2417]
create static framework
carthage update RxSwift --platform iOS --no-build
sed -i -e 's/MACH_O_TYPE = mh_dylib/MACH_O_TYPE = staticlib/g' Carthage/Checkouts/RxSwift/Rx.xcodeproj/project.pbxproj
carthage build RxSwift --platform iOS

and  the following code
let ordersSubject:BehaviorRelay<[String ]> = BehaviorRelay(value: [])
func bindData() -> Void {
        ordersSubject.bind(to: tableView.rx.items(cellIdentifier: "OrdersManagerTableViewCell", cellType: OrdersManagerTableViewCell.self)) {[weak self] (row, element, cell) in
                
                
         }
         .disposed(by: disposeBag)
        
    }

then crash
2022-04-15 16:30:33.281475+0800 FinalTest_Example[87095:3454539] Writing analzed variants.
failed to demangle superclass of DelegateProxy from mangled name 'So16_RXDelegateProxyC': unknown error
2022-04-15 16:30:35.457451+0800 FinalTest_Example[87095:3454539] failed to demangle superclass of DelegateProxy from mangled name 'So16_RXDelegateProxyC': unknown error
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/YSB-lc/Library/Developer/Xcode/DerivedData/FinalTest-cjokbrgdpbotbbhccsaqvnqwpwmu/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/YSB-lc/Library/Developer/Xcode/DerivedData/FinalTest-cjokbrgdpbotbbhccsaqvnqwpwmu/Build/Products/Debug-iphonesimulator
failed to demangle superclass of DelegateProxy from mangled name 'So16_RXDelegateProxyC': unknown error
CoreSimulator 783.5 - Device: iPhone 13 Pro (D355BE94-8F8E-443C-9152-651037A31302) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 13 Pro

**Comment by lcghh** [comment]
fix it

**Comment by erneestoc** [comment]
@lcghh how? 🙏🏻
