### ISSUE TITLE
`drive` for PublishRelays

### ISSUE THREAD

**Issue by ktan17** [ReactiveX/RxSwift#2435]
Hi, hopefully this is the right place to mention this - I noticed that in [Driver+Subscription](https://github.com/ReactiveX/RxSwift/blob/main/RxCocoa/Traits/Driver/Driver%2BSubscription.swift) while there are methods to drive BehaviorRelays and ReplayRelays, you cannot drive a PublishRelay. I was wondering if there was a reason for this or if it would be something useful and quick to add (if so, I'd love to make a first contribution 😄).

**Comment by danielt1263** [comment]
Hmm... Well a PublishRelay is more like a Signal than it is a Driver since it doesn't emit a value on subscription like the other two do.

**Comment by freak4pc** [comment]
Hey @ktan17 :) 
Daniel is absolutely right. This is a design decision.

Drive has a replay 1, meaning it should be fed into something that represents state / has an initial value - like a Behavior Subject / Relay.

Signal has no replay, so it can be fed to something that represents events / has no initial value - like a Publish Subject / Relay.

Feeding a Driver into a Publish* would cause the loss of that initial event, and feeding a Signal into a Behavior* would have no "last value" to replay for that initial value - so they don't make sense.

Hope this help!

**Comment by ktan17** [comment]
Makes sense! Thank you for the clarification 😄
