### ISSUE TITLE
DelegateProxy cause undefined symbol compile error

### ISSUE THREAD

**Issue by alekkania** [ReactiveX/RxSwift#2442]
**Short description of the issue**:

I using the `RxCLLocationManagerDelegateProxy` from examples from this repo to manage CoreLocation.
I receive
` error build: Undefined symbol: _$s7RxCocoa13DelegateProxyC12parentObject08delegateD0ACyxq_Gx_qd__mtcAFRbd__AA0cD4TypeRd__lufCTq`
compiler error in Xcode 14. 

**Expected outcome**:

Compilation will pass.

**What actually happens**:

` error build: Undefined symbol: _$s7RxCocoa13DelegateProxyC12parentObject08delegateD0ACyxq_Gx_qd__mtcAFRbd__AA0cD4TypeRd__lufCTq`
compiler error in Xcode 14. 

**Self contained code example that reproduces the issue**:

https://github.com/ReactiveX/RxSwift/blob/main/RxExample/Extensions/RxCLLocationManagerDelegateProxy.swift

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.5

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
 14
```

**Comment by danielt1263** [comment]
The class is working fine in the sample app. If you are having a problem using it in your app. Please provide a complete, self-contained, example.

**Comment by alekkania** [comment]
> The class is working fine in the sample app. If you are having a problem using it in your app. Please provide a complete, self-contained, example.

@danielt1263 
[RxIssue.zip](https://github.com/ReactiveX/RxSwift/files/9461279/RxIssue.zip)
Attached zip with example app. 
Rx is added by XCFramework. 
Xcode 14 beta 6
Swift 5.7
iOS 16 build

**Comment by dasmihir20** [comment]
I am getting same issue with Xcode Beta 6

**Comment by suprie** [comment]
Same here

**Comment by kimtungit** [comment]
I also have the same situation

**Comment by freak4pc** [comment]
Hey all,
This seems like an issue with the xcframework itself.
I suggest trying to build your own xcframeworks using Xcode 14, since the xcframeworks bundled with this repo have been built with Xcode 13. 

Running this script locally should do the work:
https://github.com/ReactiveX/RxSwift/blob/main/scripts/make-xcframeworks.sh

**Comment by suprie** [comment]
@freak4pc I still have the same issue after rebuild the xcframeworks

**Comment by freak4pc** [comment]
> @freak4pc I still have the same issue after rebuild the xcframeworks

And does it build with just SPM?

**Comment by dasmihir20** [comment]
Using SPM works for me!! Thanks you!!

**Comment by freak4pc** [comment]
> Using SPM works for me!! Thanks you!!

Thanks for letting me know! 
That unfortunately probably means there's a bug in Xcode 14 somehow. Since we don't really control the output of the xcframework build process. 

Let me know if you find a way around this 💪😇

**Comment by freak4pc** [comment]
Closing this ATM, there's nothing actionable we can do since the fact SPM "solves" this means there's some issue with xcframework(s) for this area
