### ISSUE TITLE
Xcode Cloud: Unable to verify project that links RxSwift and more using SPM

### ISSUE THREAD

**Issue by kimxwan0319** [ReactiveX/RxSwift#2446]
**Short description of the issue**:

I'm trying to CI/CD jobs to Xcode Cloud, but i receive failures during the step Prepare Build for App Store Connect.
(My code works very well in local.)

```
ITMS-90334: Invalid Code Signature Identifier. The identifier "RxSwift-<long identifier>" in your code signature for "RxSwift" must match its Bundle Identifier "RxSwift"
```

**Expected outcome**:

* success and upload to testflight.

**What actually happens**:

* receive failures during the step Prepare Build for App Store Connect like
```
ITMS-90334: Invalid Code Signature Identifier. The identifier "RxSwift-<long identifier>" in your code signature for "RxSwift" must match its Bundle Identifier "RxSwift"
```
<img width="1166" alt="Screen Shot 2022-09-20 at 1 54 58 PM" src="https://user-images.githubusercontent.com/67373938/191170694-f712ac72-89b5-461f-8d20-05d58fa1b10d.png">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 release Atlas(6.5.0)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Xcode version**:

```
 14.0.1
```
But `14.0.0` and `13.4.1` also return failures.

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  * SPM

**Comment by freak4pc** [comment]
Hey @kimxwan0319 - I'm sorry but this doesn't seem in the scope of what we support in this repo, since it seems specific to Xcode Cloud. I'd suggest asking on the Apple forums, or possibly in the RxSwift slack.
