### ISSUE TITLE
install RxSwift as static library on SPM

### ISSUE THREAD

**Issue by kimxwan0319** [ReactiveX/RxSwift#2454]
May I know how to install RxSwift as a static library on SPM?
I just added 'RxSwift' instead of 'RxSwift-Dynamic'. But it was added as a dynamic library.

<img width="1089" alt="Screen Shot 2022-10-02 at 1 20 34 AM" src="https://user-images.githubusercontent.com/67373938/193418684-4c404451-4765-4a32-b156-610f15f8bde3.png">

(I posted this question on Slack, but no one answered me. Sorry...)

**Comment by freak4pc** [comment]
Hey @kimxwan0319 - I'm sorry but we don't support configuration-specific things here, only code-level bugs with RxSwift itself. The slack would still be the best place to go. 

Thanks for understanding 🙏
