### ISSUE TITLE
Compiling for iOS 10.0, but module 'RxSwift' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by lhpkxywm** [ReactiveX/RxSwift#2458]
RxSwift 6.2.0,Xcode14

**Comment by freak4pc** [comment]
This issue has no information, no repro project, no nothing. 
Our deployment target is iOS 9, I guess it's something in your configuration and I can't help without you filling all the details of the issue template.

Please open a new issue with all the missing info.
