### ISSUE TITLE
Crash. Debug.swift line 46 logEvent(_:dateFormat:content:) 

### ISSUE THREAD

**Issue by pandaleecn** [ReactiveX/RxSwift#2463]
Crashed: rxswift.queue.DispatchQoS(qosClass: Dispatch.DispatchQoS.QoSClass.background, relativePriority: 0)
0  libicucore.A.dylib             0xddff4 icu::Calendar::getTimeZone() const + 506
1  libicucore.A.dylib             0x1f05a4 ucal_setTimeZone + 160
2  CoreFoundation                 0x8c968 __cficu_ucal_setTimeZone + 64
3  CoreFoundation                 0x817a4 __ResetUDateFormat + 1784
4  CoreFoundation                 0xae1d0 __CreateCFDateFormatter + 320
5  Foundation                     0x64d90 -[NSDateFormatter _regenerateFormatter] + 272
6  Foundation                     0x26288 -[NSDateFormatter stringForObjectValue:] + 140
7  XXXXXX_Binary               0x41badf0 logEvent(_:dateFormat:content:) + 32 (Debug.swift:32)
8  XXXXXX_Binary               0x41bb930 specialized DebugSink.init(parent:observer:cancel:) + 46 (Debug.swift:46)
9  XXXXXX_Binary               0x41bb530 Debug.run<A>(_:cancel:) + 99 (Debug.swift:99)
10 XXXXXX_Binary               0x41e1080 closure #1 in Producer.subscribe<A>(_:) + 2684512
11 XXXXXX_Binary               0x41b7994 specialized CurrentThreadScheduler.schedule<A>(_:action:) + 25 (CurrentThreadScheduler.swift:25)
12 XXXXXX_Binary               0x41e0cec Producer.subscribe<A>(_:) + 2683596 (<compiler-generated>:2683596)
13 XXXXXX_Binary               0x41d9254 ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) + 80 (ObservableType+Extensions.swift:80)
![image](https://user-images.githubusercontent.com/17469549/199924174-71130ada-1b88-47fe-81fe-ebfd8b3643cf.png)

**Comment by make1a** [comment]
we have the same issue.   
version: 5.1.1

**Comment by freak4pc** [comment]
Hey both,
RxSwift 5 is almost 3 years old and we don't really provide active support for it.

Could you upgrade to RxSwift 6 and see if the problem persists ?
