### ISSUE TITLE
Where are 6.5.0 -> RXCocoa.Frameworks and RxRelay.Frameworks ?

### ISSUE THREAD

**Issue by vassily-fr** [ReactiveX/RxSwift#2467]
**Short description of the issue**:

Sorry for the dummy question, but I can't find link to download version 6.5.0 of : 
RxCocoa.xcFramework
RxRelay.xcFramework

**Expected outcome**:

A link 😅

**What actually happens**:

No Link 😅

**Self contained code example that reproduces the issue**:
for 6.5.0 version : 
https://github.com/ReactiveX/RxSwift/releases/download/6.5.0/RxSwift.xcframework.zip. <- 🎉
https://github.com/ReactiveX/RxSwift/releases/download/6.5.0/RxCocoa.xcframework.zip. <- 😢
https://github.com/ReactiveX/RxSwift/releases/download/6.5.0/RxRelay.xcframework.zip. <- 😢
  
on 6.2.0 versino :
https://github.com/ReactiveX/RxSwift/releases/download/6.2.0/RxSwift.xcframework.zip. <- 🎉
https://github.com/ReactiveX/RxSwift/releases/download/6.2.0/RxCocoa.xcframework.zip. <- 🎉
https://github.com/ReactiveX/RxSwift/releases/download/6.2.0/RxRelay.xcframework.zip. <- 🎉

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.5.0

**Platform/Environment**

  - [ x] iOS
  - [ x] macOS
  - [ x] tvOS
  - [ x] watchOS
  - [ x] playgrounds

**Comment by hupengfei-hinterstellar** [comment]
When the [RxSwift.xcframework.zip] downloaded, you will see they all in the [RxSwift] folder.
