### ISSUE TITLE
  CollectionViewWaterfallLayout crash at check delegate while using rx.contentOffset observe or other scrollView observe

### ISSUE THREAD

**Issue by zkfpk6** [ReactiveX/RxSwift#2468]
**Short description of the issue**:

  CollectionViewWaterfallLayout crash at check delegate while using rx.contentOffset observer or other observer，when i remove these observer, it will never crash, please help!
  https://github.com/ecerney/CollectionViewWaterfallLayout

**Expected outcome**:

  the flowlayout's delegate is not nil

**What actually happens**:

  the flowlayout's delegate is nil

**Self contained code example that reproduces the issue**:

```swift
  scrollView.rx.contentOffset.bind(onNext: { _ in

        }).disposed(by: disposeBag)
```
will crash at CollectionViewWaterfallLayout.swift, line 114
```swift
private weak var delegate: CollectionViewWaterfallLayoutDelegate?  {
        get {
            return collectionView?.delegate as? CollectionViewWaterfallLayoutDelegate
        }
    }
...
       guard let delegate = delegate else {
            assertionFailure("UICollectionView's delegate should conform to WaterfallLayoutDelegate protocol")
            return
        }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 6.5.0

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
  14.1
```

**Comment by danielt1263** [comment]
Please include a complete code sample. For example, a GitHub repo of a project that shows the problem.

**Comment by zkfpk6** [comment]
> Please include a complete code sample. For example, a GitHub repo of a project that shows the problem.

please check this：
https://github.com/zkfpk6/TestRepo

**Comment by danielt1263** [comment]
Your test repo did not crash for me...

**Comment by zkfpk6** [comment]
> Your test repo did not crash for me...

yes,  just uncomment below "// MARK: - crash",  it will crash.
sorry for my english..

**Comment by danielt1263** [comment]
I submitted a PR to your TestRepo with the fix.

**Comment by freak4pc** [comment]
Thanks for taking care of this @danielt1263 🙏 
Based on the repo seems like this isn't an issue with RxSwift itself but sum misuse of the API. 

Closing, let me know if there are further issues (Even though it's better directing those to our slack)
