### ISSUE TITLE
There is wrong print log in GettingStarted.md document

### ISSUE THREAD

**Issue by Neph3779** [ReactiveX/RxSwift#2470]
**Short description of the issue**:

in [Getting Started document's creating-an-observable-that-performs-work](https://github.com/Neph3779/RxSwift/blob/main/Documentation/GettingStarted.md#creating-an-observable-that-performs-work)

448 line and 455 line is calling print("Subscribed")
so print log should print "Subscribed" 4 times
(2 times for calling MyInterval, 2 time for 448 line and 455 line)

I think you forgot to remove 448, 455 line when wrote this document

It might be confusing for beginners like me, so can you remove 448, 455 line or fix print log?

**Expected outcome**:

print log (started from line 475 in GettingStarted.md) should be like 
```
Started ----
Subscribed
Subscribed
Subscribed
Subscribed
First 0
Second 0
First 1
Second 1
First 2
Second 2
First 3
Second 3
First 4
Second 4
Disposed
Second 5
Second 6
Second 7
Second 8
Second 9
Disposed
Ended ----
```

when run code in this document

**Comment by freak4pc** [comment]
Feel free to submit a PR 🙏

**Comment by Neph3779** [comment]
#2471 
I made a Pull Request, so I'll close this issue.
Thank you
