### ISSUE TITLE
The invite link for the slack channel is broken

### ISSUE THREAD

**Issue by danielt1263** [ReactiveX/RxSwift#2472]
**Short description of the issue**:

The invite link for the slack channel is broken: http://slack.rxswift.org/

**Expected outcome**:

It should allow you to connect to the slack channel

**What actually happens**:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Comment by freak4pc** [comment]
Yup, since heroku closed down OSS there's no where to host the self-invite page.

If you have any new suggestions I'm happy to try but not super available to dig into this myself ATM

**Comment by cristiankocza-viacom** [comment]
@freak4pc I can host it if helps, I have a DigitalOcean subscription for hosting services.

**Comment by cristik** [comment]
@freak4pc I can host it if helps, I have a DigitalOcean subscription for hosting services.
