### ISSUE TITLE
rx_tap on table view cell button

### ISSUE THREAD

**Issue by xdgimf** [ReactiveX/RxSwift#248]
I'm trying to use rx_tap on a table view cell button, how can i prevent adding new rx_tap every time i reload the tableview?

    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    //...
    cell.addButton.rx_tap
                .subscribeNext {
                    log.info("\(indexPath.row)")
                }
                .addDisposableTo(disposeBag)
    //...
    }

**Comment by frogcjn** [comment]
I think it needs a custom cell class, and in the cell class, there is a dispose bag, so this solution needs more work.

I'd like to use traditional way of storyboard segue to implement this.

**Comment by frogcjn** [comment]
There is a better way from RxExample:

        tableView.rx_itemSelected
            .subscribeNext { [unowned self] indexPath in
                self.showDetailsForUserAtIndexPath(indexPath)
            }
            .addDisposableTo(disposeBag)

**Comment by xdgimf** [comment]
if i'm not mistaken tableView.rx_itemSelected is for the whole table view cell, I only want to add it to a  button in a tableview cell. I did what you said last time, I added a disposeBag to the  cell(CustomTableViewCell) and it works fine. I also tried creating an array of disposeBag but got a problem disposing them when reloading only 1 row, so I stick with the disposeBag on a tableview cell

**Comment by frogcjn** [comment]
You should create a custom cell class, and add a disposeBag property for each cell.
