### ISSUE TITLE
`UIImageView.rx_image` takes a `UIImage!`... That seems wrong

### ISSUE THREAD

**Issue by dtartaglia** [ReactiveX/RxSwift#250]
Is there a particular reason why `UIImageView.rx_image` takes an implicitly unwrapped optional?

I want to send it a `UIImage?`, rather than a `UIImage!` and the underlying value `UIImageView.image` is a `UIImage?`

**Comment by kzaher** [comment]
Hi @dtartaglia ,

the reason why that was the case was because Swift say that property as `UIImage!`. I think situation has changed some version of Swift, so we can use `UIImage?`.

**Comment by gregpardo** [comment]
I noticed this while using it too. Sometimes you want to map a nil value to UIImage to make it empty.

**Comment by dtartaglia** [comment]
My push notification already got merged. Should be in soon.

**Comment by kzaher** [comment]
This was released.
