### ISSUE TITLE
Too large binary size after upgrading to Xcode 14.2 

### ISSUE THREAD

**Issue by arturdev** [ReactiveX/RxSwift#2503]
**Short description of the issue**:

  Our app has an AppClips component, which also depends on Rx. Before upgrading to Xcode 14.2, the unzipped version of the AppClips was weighing about 9MB (10 is the maximum allowed). 
  After upgrading to Xcode 14.2, the app weighs more than 13MB! From where the total size of RxSwift + RxCocoa frameworks is more than 5 MB!!!  And because of this, I can't release any new version of the AppClips! The only temporary solution is increasing the minimum deployment target to iOS 16 (apple increased the limit to 15MB for 16.0+), but this is not a long term solution, coz there are still a lot of devices running lower OS versions.

**Expected outcome**:
  How to reduce the size of the frameworks?

**Xcode version**: 

```
14.2
```

**RxSwift Version**: 

```
5.1.3
```

**Comment by arturdev** [comment]
@freak4pc Why RxSwift's size is so big in the first place?
And, is there a way (by modifying Rx.xcodeproj's build settings) to make it smaller somehow? 
RxSwift is a widely used library that is used in almost all apps nowadays.. and as there is no more a bitcode support, I think RxSwift should think a way to reduce the app size..

**Comment by freak4pc** [comment]
I don't really have an answer for you @arturdev. This project is OSS, feel free to pick the source files you want and drop the ones you don't :) 

We don't perform optimizations on a per-consumer basis as this is a free, open project and not a commercial product. 

This will have to be something you solve on your side and not something we can solve from the RxSwift side for your specific use-case. For example, you could include only RxSwift, RxRelay, and not use RxCocoa if you don't need it, etc. Or perform your own investigation of the bundle size and provide an appropriate PR.

**Comment by arturdev** [comment]
@freak4pc  Your response sounded like:..
![image](https://user-images.githubusercontent.com/6263856/225233606-9a8279e5-5aa5-4455-b390-f2dfc992ceb5.png)

**Comment by freak4pc** [comment]
Not with that tone, but in essence we support a wide community and not specific issues of specific consumers.

**Comment by arturdev** [comment]
Well, that's not a specific customer issue, but I believe quite a common issue for all the AppClips customers... I bet every AppClip that uses Rx has this issue.

**Comment by arturdev** [comment]
So the question here is more like are there any build settings that could potentially reduce the app size?

**Comment by danielt1263** [comment]
@arturdev Do you see how the question, "are there any build settings that could potentially reduce the app size?" really has nothing to do with RxSwift specifically? 

There are a lot of things you can do to reduce app size and a bunch of articles about it. [Here's an article about it.](https://charlieinden.github.io/ios-interviews/2020-10-21_iOS---Reducing-Your-App-s-Size-51827bbb92b8.html) There are others.

Good luck!
