### ISSUE TITLE
Context propagation

### ISSUE THREAD

**Issue by SebastianThiebaud** [ReactiveX/RxSwift#2517]
_If this isn't the right place to open a feature request, let me know, and I'll repost it in the right forum._

This is related to Apple's distributed tracing guidelines for Swift (and more specifically, Swift 5.5) 
[https://github.com/apple/swift-distributed-tracing-baggage](apple/swift-distributed-tracing-baggage)
[https://github.com/apple/swift-distributed-tracing](apple/swift-distributed-tracing)

According to OpenTelemetry and Apple: in a distributed system (or a mobile application composed of several frameworks), a context is passed from senders to receivers. The context refers to metadata collected, stored, and carried across API and framework boundaries by components within a distributed system and between logically associated execution units. These execution-scoped values include information such as IDs, request methods, and versions. A context must be immutable, and its write operations must result in the creation of a new context containing the original and updated values.

When RxSwift's observables and operators are used within an application, new execution units are created and do not carry over the current context (task local values). In this case, the current context should be copied so the new detached task can pass along the baggage and all its data. 

I'd love to hear if there is any plan to support context propagation within RxSwift.

Thank you.

**Comment by freak4pc** [comment]
Hey, @SebastianThiebaud

RxSwift is mainly in maintenance and minor enhancements mode to provide solid support for the existing project API surface. We don't plan on making any large feature additions and can't imagine we'll have anyone working on supporting Distributed Tracing with RxSwift itself.

I don't oppose any PRs on the topic but as mentioned, it's not on the roadmap.
