### ISSUE TITLE
Missing spec for 6.6.0 in Cocoapods

### ISSUE THREAD

**Issue by marciogranzotto** [ReactiveX/RxSwift#2522]
**Short description of the issue**:

`v6.6.0` was released 3 days ago, but there's still only `v6.5.0` in cocoapods:

<img width="864" alt="image" src="https://github.com/ReactiveX/RxSwift/assets/11080704/fc8a0768-9b07-41e7-98e8-c04954b22206">

**Expected outcome**:

Expected to be able to use v6.6.0 with cocoapods

**What actually happens**:

```
[!] CocoaPods could not find compatible versions for pod "RxBlocking":
  In Podfile:
    RxBlocking (~> 6.6.0)

None of your spec sources contain a spec satisfying the dependency: `RxBlocking (~> 6.6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 ```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 v6.6.0

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  14.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by loganmoseley** [comment]
Thank you @freak4pc for guiding this and the 6.5.0 Swift Concurrency update. It’s a big deal.

I’ve modified the 6.5.0 podspec JSON for 6.6.0. Hope it makes this request easier for you.

1. Updated `version` and `source.tag` to `6.6.0`.
2. Updated `swift_version[s]` to `5.5` because that’s when it was implemented. [SE-0296](https://github.com/apple/swift-evolution/blob/main/proposals/0296-async-await.md)
3. Updated `swift_versions` to an array because of [Podspec Syntax Reference#swift_versions](https://guides.cocoapods.org/syntax/podspec.html#swift_versions).

```json
{
  "name": "RxSwift",
  "version": "6.6.0",
  "summary": "RxSwift is a Swift implementation of Reactive Extensions",
  "description": "This is a Swift port of [ReactiveX.io](https://github.com/ReactiveX)\n\nLike the original [Rx](https://github.com/Reactive-extensions/Rx.Net), its intention is to enable easy composition of asynchronous operations and event streams.\n\nIt tries to port as many concepts from the original Rx as possible, but some concepts were adapted for more pleasant and performant integration with iOS/macOS/Linux environment.\n\nProbably the best analogy for those who have never heard of Rx would be:\n\n```\ngit diff | grep bug | less          #  linux pipes - programs communicate by sending\n\t\t\t\t    #  sequences of bytes, words, lines, '\u0000' terminated strings...\n```\nwould become if written in RxSwift\n```\ngitDiff().grep(\"bug\").less          // sequences of swift objects\n```",
  "homepage": "https://github.com/ReactiveX/RxSwift",
  "license": "MIT",
  "authors": {
    "Krunoslav Zaher": "krunoslav.zaher@gmail.com"
  },
  "source": {
    "git": "https://github.com/ReactiveX/RxSwift.git",
    "tag": "6.6.0"
  },
  "requires_arc": true,
  "platforms": {
    "ios": "9.0",
    "osx": "10.9",
    "watchos": "3.0",
    "tvos": "9.0"
  },
  "source_files": [
    "RxSwift/**/*.swift",
    "Platform/**/*.swift"
  ],
  "exclude_files": "RxSwift/Platform/**/*.swift",
  "swift_versions": ["5.5"],
  "swift_version": "5.5"
}
```

**Comment by dnkoutso** [comment]
FYI the JSON output includes both `swift_versions` and `swift_version` for backwards compatibility. An initial version of CocoaPods only dealt with a single version of Swift but then support for supporting multiple Swift versions was added.

Specifying a string or array for `swift_version` is handled properly by the later versions of CocoaPods like 1.7.x and on if I recall correctly.

**Comment by basalphenaar** [comment]
Is there any update on this? It seems like the most recent version available through CocoaPods is still v6.5.0.

**Comment by goranbrl** [comment]
Hey @freak4pc, any chance of v6.6.0 getting a proper Cocoapods release soon? Would be greatly appreciated, thanks 🙂

**Comment by jules-moorhouse-deltatre** [comment]
Just encountered this today, so we cannot use Xcode beta 15 (at least v2 and above) without this :( 

Any update please ?

**Comment by studiogaram** [comment]
@freak4pc Hello, did you forget to update the pod spec? 
Since the owners of rxswift in pod trunk are freak4pc and zher, it's hard for me or others to contribute.

```
You are not allowed to push new versions for this pod. The owners of this pod are freak4pc@gmail.com and krunoslav.zaher@gmail.com.
```

I would appreciate it if you could check it and update it.

**Comment by ayushmahajan** [comment]
Just spent the past 15 minutes trying to download the unavailable pod version. Can we please release the pod version 6.6.0?

**Comment by bluerainxty** [comment]
Any updates?

**Comment by foxware00** [comment]
@freak4pc Could we please get this sorted/merged. It would be good to be able to update various dependencies that rely on RxSwift

**Comment by ecunha-ta** [comment]
Hey, @freak4pc @kzaher could you please update the references in cocoapods for all the rx pods updated? With the final release of XCode 15 it would be nice mainly because of: https://github.com/ReactiveX/RxSwift/issues/2532 . 

Thanks!

**Comment by SuperMarioBean** [comment]
same here

**Comment by freak4pc** [comment]
Hey all,
Sorry for the delay. to be honest the main reason I'm not updating the spec is because it's insanely difficult to use CocoaPods to upload specs. It's ridden with a lot of cryptic error messages, and Xcode 15 isn't supported at all because of an [https://github.com/CocoaPods/CocoaPods/issues/12012](open issue from their side).

I had to spin up an entire CI machine just so I'll be able to push the spec, but seems to be working now.

I just pushed the 6.6.0 specs to CocoaPods.

**Comment by basalphenaar** [comment]
> Hey all, Sorry for the delay. to be honest the main reason I'm not updating the spec is because it's insanely difficult to use CocoaPods to upload specs. It's ridden with a lot of cryptic error messages, and Xcode 15 isn't supported at all because of an [open issue from their side](https://github.com/CocoaPods/CocoaPods/issues/12012).
> 
> I had to spin up an entire CI machine just so I'll be able to push the spec, but seems to be working now.
> 
> I just pushed the 6.6.0 specs to CocoaPods.

That sounds pretty annoying! Thanks for all your efforts 👍

**Comment by ecunha-ta** [comment]
Thank you for this.

**Comment by gsbernstein** [comment]
Seems like at least that one xcode 15 issue has been fixed with their latest update https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0

**Comment by loganmoseley** [comment]
Oh dang, that’s aggravating. Then even more so: Thank you very much, Shai!
