### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by Gargo** [ReactiveX/RxSwift#2524]
**Short description of the issue**:

According to your Podfile:
```
pod 'ReactorKit'
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
```

`pod install` doesn't work 
```
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In snapshot (Podfile.lock):
    RxSwift (= 6.5.0, ~> 6.0)

  In Podfile:
    RxSwift (= 6.6.0)

Specs satisfying the `RxSwift (= 6.6.0), RxSwift (= 6.5.0, ~> 6.0)` dependency were found, but they required a higher minimum deployment target.
```

works with 6.5.0 versions only (or when I don't specify concrete versions in the podfile)

**Expected outcome**:

`pod install` works

**What actually happens**:

`pod install` is finished with errors

**Self contained code example that reproduces the issue**:

no swift code required

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.6.0/6.5.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
14.2 (but it seems to be independent from Xcode)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  - [x] yes (14.2, 14.3)
  - [ ] no

**Level of RxSwift knowledge**:
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by TTOzzi** [comment]
This is the same issue as #2522. It seems to be missing a `pod trunk push` run.
