### ISSUE TITLE
visionOS Compiling Error

### ISSUE THREAD

**Issue by ilkerulusoy** [ReactiveX/RxSwift#2530]
**Short description of the issue**:

There is compiling error in RxCocoa/UIApplication+Rx.swift for visionOS SDK. There is a macro in the top of the code but not working. 

**Expected outcome**:

Compile without error. 

**What actually happens**:

in RxCocoa/UIApplication+Rx.swift
Application.isNetworkActivityIndicatorVisible is available in xrOS

<img width="1928" alt="CleanShot 2023-06-22 at 01 00 35@2x" src="https://github.com/ReactiveX/RxSwift/assets/1990736/377e3c6f-6ab6-4ff0-839d-84798cb8ec0b">

in RxCocoa/UITabBar+Rx.swift
'tabBar(_:willBeginCustomizing:)' is unavailable in xrOS
'tabBar(_:willEndCustomizing:changed:)' is unavailable in xrOS,

<img width="1933" alt="CleanShot 2023-06-22 at 01 43 24@2x" src="https://github.com/ReactiveX/RxSwift/assets/1990736/a45ec74a-3dfb-4c84-a909-25baf6e487f8">

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxCocoa/7d93271874a742595980a876f7328d958853d5c1

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds
  - [x] visionOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 15 Beta 2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [x] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by RobertDresler** [comment]
I think this PR is no longer valid since directive `os(iOS)` was incorrectly true for `visionOS` (e.g. in Beta 8 it is false). So I think the only changes needed for fixing compiling errors are in my https://github.com/ReactiveX/RxSwift/issues/2542.

**Comment by ilkerulusoy** [comment]
I will re-check
