### ISSUE TITLE
We need 'Action' similar to RAC's 'Action' or how to solve this with RxSwift?

### ISSUE THREAD

**Issue by Fab1n** [ReactiveX/RxSwift#254]
Imagine, we have a function like `func openAlert() -> Observable<AlertResponse>` where `AlertResponse` contains `.OK` and `.Cancel` for an alertView which has an OK and Cancel button.
Now I want to know if the observable is currently active and bind this information to a - let's say - button's `rx_enabled` state to make clear that while the action is ongoing, the button can't be pressed. 
Doesn't make so much sense for Alerts, but here is another example:

On button tap, a server request is sent. How can I easily bind the button's `rx_enabled` subject to the actions ongoing state?

It is quite common that I want to know if some action is currently active or not. 

How to solve this in a nice way with RxSwift?

**Comment by kzaher** [comment]
@Fab1n Take a look at RxExample app. We use ActivityIndicator class in Wikipedia image search and Github repository search example.

ActivityIndicator is pretty generic.

The trick is to use `using` operator and treat `ActivityToken` as resources. 

That's how I would do it, not sure if there is some nicer way :)

Note:
`Driver` class is there to guarantee and express that we want to receive those "is it running" elements on main thread, that observable can't error out and is sharing subscription.

We could have exposed `_variable.asObservable()`, but this was kind of nicer way of communicating properties of that observable sequence.

**Comment by Fab1n** [comment]
Ok thank you 😀

I will have a look at it tomorrow

**Comment by ashfurrow** [comment]
Looking forward to this!

**Comment by ashfurrow** [comment]
I've begun working on something like this here: https://github.com/ashfurrow/Action Still very early, and it's very scaled down from ReactiveCocoa's version, but I think it's a good start.

**Comment by kzaher** [comment]
Hey @ashfurrow ,
If you are looking for a way how to track activity, we've got something in `RxExample` app. We didn't export it to a separate project, but it's pretty simple :)

https://github.com/ReactiveX/RxSwift/blob/642b84e946792cb22ca72613b0410132d6edf5f2/RxExample/RxExample/Services/ActivityIndicator.swift

It will aggregate activity from multiple observables.

Let me know what you think ...

**Comment by ashfurrow** [comment]
Neat! I'll have to take a closer look once I've had my coffee ☕️

**Comment by kzaher** [comment]
It looks to me that `Action` = `ActivityIndicator` + `flatMapLatest` + some small additional juice :)

**Comment by ashfurrow** [comment]
Opened an issue to do it, I can't spare _too_ much time on it right now but I'll see what I can do. Thanks so much for the suggestion!

**Comment by fpillet** [comment]
Action is awesome, thanks!

**Comment by Fab1n** [comment]
`ActivityIndicator` is really great! Thank you! Maybe we should make it an official API. Should we keep this issue open until we have it?

**Comment by kzaher** [comment]
We have some related projects grouped under [RxSwiftCommunity](https://github.com/RxSwiftCommunity/) organization.

I'm thinking maybe it would be good idea to add `ActivityIndicator` to some of them. Maybe RxViewModel. That is kind of @esttorhe's baby, so it depends what is his vision for that project :)

I'll probably create a new project under [RxSwiftCommunity](https://github.com/RxSwiftCommunity/) for reactive data sources for table and collection views. What is currently in `RxDataSourceStarterKit` and polish that code.

If people like @ashfurrow `Action` that much, maybe it would also make sense to move it under [RxSwiftCommunity](https://github.com/RxSwiftCommunity/) to better promote it.

**Comment by ashfurrow** [comment]
Yup! I've been [discussing moving it over](https://github.com/RxSwiftCommunity/contributors/issues/4), but it needs to be "production ready" first. I have [one remaining issue](https://github.com/ashfurrow/Action/issues/3) to get it there, but it needs `replayAll`, which will be in RxSwift's next release.

**Comment by esttorhe** [comment]
@kzaher hahaha. It **was** my baby now is part of the community. 

I think ActivityIndicator would work great on RxViewModel

**Comment by kzaher** [comment]
We can probably close this issue for now.
