### ISSUE TITLE
Can't compile RxSwift for visionOS

### ISSUE THREAD

**Issue by RobertDresler** [ReactiveX/RxSwift#2542]
On Xcode 15 beta 8, compiler directive `os(iOS)` is no longer true for `visionOS`. Therefore, RxSwift can't be compiled for `visionOS` platform.

E.g. these errors:

![Screenshot 2023-09-06 at 18 05 07](https://github.com/ReactiveX/RxSwift/assets/40290767/1ca45ac2-95a7-4d8e-93b6-eb1e1257b4ac)

It can be fixed by replacing `#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS)` with `#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS) || os(visionOS)` or even better with `#if canImport(...)`.

**Comment by freak4pc** [comment]
Happy to accept a PR around this! 

i think it would be preferable to use `|| os(visionOS)` where needed because there are APIs that are only available to iOS, which would also apply to visionOS itself.

**Comment by RobertDresler** [comment]
@freak4pc I opened PR
