### ISSUE TITLE
RXCocoa on contextMenuConfigurationForRowAt method

### ISSUE THREAD

**Issue by confusionhill** [ReactiveX/RxSwift#2547]
Hello, I wanted to use RxSwift and RxCocoa ona simple tableview app. It's currently using apple newest Tableview delegate API ` func tableView(_ tableView: UITableView, contextMenuConfigurationForRowAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration?` and I wanted to use RxCocoa. Are there any available API that I can use to integrate RxSwift to that new method? Thank you

**Expected outcome**:

  _what you expect to happen goes here_

**What actually happens**:

  _what actually happens goes here_

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version goes here
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [v ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [v ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [v] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by danielt1263** [comment]
This is very much a question that should be asked on the RxSwift slack channel.

**Comment by freak4pc** [comment]
Agree with Daniel.
