### ISSUE TITLE
Cannot call value of non-function type '[Observable<Event>.Type]'

### ISSUE THREAD

**Issue by dd9913762113** [ReactiveX/RxSwift#2548]
Xcode 15.0
Mac Book Pro M1

Feedbacks.swift
```
private func bindingsStrongify<Event, O, WeakOwner>(_ owner: WeakOwner, _ bindings: @escaping (WeakOwner, O) -> (Bindings<Event>))
    -> (O) -> (Bindings<Event>) where WeakOwner: AnyObject {
    return { [weak owner] state -> Bindings<Event> in
        guard let strongOwner = owner else {
            return Bindings(subscriptions: [], events: [Observable<Event>]())
        }
        return bindings(strongOwner, state)
    }
}
```
- Moya/RxSwift (15.0.0):
    - Moya/Core
    - RxSwift (~> 6.0)
  
<img width="781" alt="截屏2023-10-16 下午5 20 00" src="https://github.com/ReactiveX/RxSwift/assets/85228967/ce0404d3-bd3d-4ec6-86ff-5d3ff22cde18">

**Comment by danielt1263** [comment]
The compiler is confusing the Swift.Observable type with the RxSwift.Observable type. Use: `return Bindings(subscriptions: [], events: [RxSwift.Observable<Event>]())` instead.

**Comment by freak4pc** [comment]
Feedbacks.swift is part of the example project and not the library itself so I don't think it's very relevant. Worth fixing but not a blocker for consumers. Closing for now, thanks
