### ISSUE TITLE
docs.rxswift.org (RxSwift Reference) - all links to Documentation/[FILENAME].md are broken

### ISSUE THREAD

**Issue by ben-p-commits** [ReactiveX/RxSwift#2558]
**Short description of the issue**:

When navigating around on https://docs.rxswift.org/, links to any markdown resource are broken.

**Expected outcome**:

Because `ReadMe.md` is successfully rendered in this fashion on the [landing page](https://docs.rxswift.org/), I would expect links to markdown resources to link to a static html page with the rendered markdown, or at least link back to the file in the repository instead.

**What actually happens**:
<img width="300" alt="image" src="https://github.com/ReactiveX/RxSwift/assets/5067237/c085b13c-01bd-4b44-9257-608cc2650400">

** Reproduction **
1. Navigate to https://docs.rxswift.org/
2. Click a link on the readme to anything under the **I came here because I want to...** header.

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

I assume there is static site generation code somewhere that just needs tweaking.

If I get some time later I'll take a look myself.

**Comment by freak4pc** [comment]
Thanks, I've made all URLs on the README absolute. All those pages aren't part of the docs, they're part of the repo.
Would be call doing this in DocC at some point but not in my plans so far :)
