### ISSUE TITLE
Can I build RxSwift on Xcode 7.1 and swift2.1?

### ISSUE THREAD

**Issue by shiratsu** [ReactiveX/RxSwift#256]
I want to use RxSwift on Xcode 7.1 and swift2.1 by Carthage.
But i couldn't.
My cartfile is the following code.
```
git "git@github.com:ReactiveX/RxSwift.git" "2.0.0-beta.2"
github "TransitApp/SVProgressHUD"
github "realm/realm-cocoa"
github "oarrabi/OAStackView"
```

When i build my project,I got the following error.
```
Module file was created by an older version of the compiler; rebuild 'RxSwift' and try again: /Users/hiratsukashu/20151114_shot_xcode71/shot_for_ph2_by_swift/Carthage/Build/iOS/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64.swiftmodule
```

are there any solution?

**Comment by nanoxd** [comment]
Use `carthage update --no-use-binaries` or `carthage bootstrap --no-use-binaries` to ignore the archived framework for this release and compile from scratch.

**Comment by ikesyo** [comment]
It seems that RxSwift does not have prebuilt binaries. And he is using `git` source, not `github` source. Since prebuilt binaries are attached to GitHub Releases, prebuilt ones are not used in the case.

`rm -rf ~/Library/Developer/Xcode/DerivedData/RxSwift-*` might be the help.

**Comment by nanoxd** [comment]
:blush: Good catch, I overlooked that :eyes:.

**Comment by shiratsu** [comment]
Oh,thank you.I will try it.

**Comment by shiratsu** [comment]
I could build! Thank you!

**Comment by shiratsu** [comment]
I could build the following code.
```
carthage build
```
Thank you!
