### ISSUE TITLE
Deprecated code warnings in playground Filtering_and_Conditional_Operators.xcplaygroundpage

### ISSUE THREAD

**Issue by ThomasAWRaku** [ReactiveX/RxSwift#2569]
**Short description of the issue**:

  Deprecated code warnings in playground `Filtering_and_Conditional_Operators.xcplaygroundpage`

  RxSwift/Rx.playground/Pages/Filtering_and_Conditional_Operators.xcplaygroundpage:198:10 'skipWhile' is deprecated: renamed to 'skip(while:)'

  RxSwift/Rx.playground/Pages/Filtering_and_Conditional_Operators.xcplaygroundpage:216:10 'skipUntil' is deprecated: renamed to 'skip(until:)'

**Expected outcome**:

  No deprecation warnings in playground sample code.

**What actually happens**:

  Deprecation warnings in playground sample code.

**Self contained code example that reproduces the issue**:

  See `RxSwift/Rx.playground/Pages/Filtering_and_Conditional_Operators.xcplaygroundpage`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  551639293147e54fddced6f967a60d115818e18e

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 14.2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by annie-gupta** [comment]
@ThomasAWRaku Have raised a PR for the same
