### ISSUE TITLE
asSingle -> Sequence contains more than one element.

### ISSUE THREAD

**Issue by EE-Yat-Ho** [ReactiveX/RxSwift#2579]
**Short description of the issue**:

**asSingle** does not **forwardOn** the value entered as **next**.
When **Subject** or **Observable** is changed to **asSingle**, it does not work properly.

**Expected outcome**:

It works normally when you change **Subject** or **Observable** to **asSingle**.

**Self contained code example that reproduces the issue**:

```swift
let ps = PublishSubject()
let disposeBag = DisposeBag()

ps.asSingle()
    .subscribe(onSuccess: { string in
        print("❔ onSuccess \(string)")
    }, onFailure: { error in
        print("❔ onFailure \(error)")
    }, onDisposed: {
        print("❔ onDisposed")
    })
    .disposed(by: disposeBag)

ps.onNext("a")
// not thing print
ps.onNext("b")
// print "❔ onFailure Sequence contains more than one element."
// print "❔ onDisposed"
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
15.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [x] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by EE-Yat-Ho** [comment]
I would like to add the code below to **.next** of **AsSingleSink**.

```
self.forwardOn(element)
self.forwardOn(.completed)
```

**Comment by danielt1263** [comment]
That is as designed. In your case, use `ps.take(1).asSingle()`

**Comment by EE-Yat-Ho** [comment]
“completed” is issued when “take” receives the specified number of events. 
Great.

**Comment by Efebyts** [comment]
> 
> 
> **Short description of the issue**:
> 
> 
> 
> **asSingle** does not **forwardOn** the value entered as **next**.
> 
> When **Subject** or **Observable** is changed to **asSingle**, it does not work properly.
> 
> 
> 
> 
> 
> **Expected outcome**:
> 
> 
> 
> It works normally when you change **Subject** or **Observable** to **asSingle**.
> 
> 
> 
> 
> 
> **Self contained code example that reproduces the issue**:
> 
> 
> 
> ```swift
> 
> let ps = PublishSubject()
> 
> let disposeBag = DisposeBag()
> 
> 
> 
> ps.asSingle()
> 
>     .subscribe(onSuccess: { string in
> 
>         print("❔ onSuccess \(string)")
> 
>     }, onFailure: { error in
> 
>         print("❔ onFailure \(error)")
> 
>     }, onDisposed: {
> 
>         print("❔ onDisposed")
> 
>     })
> 
>     .disposed(by: disposeBag)
> 
> 
> 
> ps.onNext("a")
> 
> // not thing print
> 
> ps.onNext("b")
> 
> // print "❔ onFailure Sequence contains more than one element."
> 
> // print "❔ onDisposed"
> 
> ```
> 
> 
> 
> **Platform/Environment**
> 
> 
> 
>   - [x] iOS
> 
>   - [ ] macOS
> 
>   - [ ] tvOS
> 
>   - [ ] watchOS
> 
>   - [ ] playgrounds
> 
> 
> 
> **How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
> 
> 
> 
>   - [x] easy, 100% repro
> 
>   - [ ] sometimes, 10%-100%
> 
>   - [ ] hard, 2% - 10%
> 
>   - [ ] extremely hard, %0 - 2%
> 
> 
> 
> **Xcode version**:
> 
> 
> 
> ```
> 
> 15.1
> 
> ```
> 
> 
> 
> :warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:
> 
> 
> 
> **Installation method**:
> 
>   - [ ] CocoaPods
> 
>   - [ ] Carthage
> 
>   - [x] Git submodules
> 
> 
> 
> **I have multiple versions of Xcode installed**:
> 
>   (so we can know if this is a potential cause of your issue)
> 
>   - [x] yes (which ones)
> 
>   - [ ] no
> 
> 
> 
> **Level of RxSwift knowledge**:
> 
>   (this is so we can understand your level of knowledge
> 
>     and formulate the response in an appropriate manner)
> 
>   - [ ] just starting
> 
>   - [x] I have a small code base
> 
>   - [ ] I have a significant code base
> 
>

**Comment by danielt1263** [comment]
The `asSingle()` operator works exactly as designed. If you attempt to emit more than one next event, then it's supposed to emit an error and that's exactly what happens in your sample code.

If you want the observer to receive the first value emitted and then shut down, then use `.first()` (which returns a Single) instead of `asSingle()`.

**Comment by danielt1263** [comment]
@Efebyts I'm not sure why you quoted the original message to this closed topic... Care to elaborate?
