### ISSUE TITLE
Cocoapods trunk push verification fails on pods dependent on RxSwift using Xcode 15+

### ISSUE THREAD

**Issue by mjohnson12** [ReactiveX/RxSwift#2582]
**Short description of the issue**:

While attempting to push out a new pod version for [WorkflowRxSwift](https://cocoapods.org/pods/WorkflowRxSwift) cocoapods gets an error doing the verification build when using Xcode 15.x.  This pod depends on RxSwift and the error is as follows:

`- ERROR | xcodebuild:  RxSwift/RxSwift/Schedulers/ConcurrentDispatchQueueScheduler.swift:17:29: error: 'Date' is only available in application extensions for macOS 10.10 or newer`

It is failing because the minimum deployment target in the podspec for Mac OS for RxSwift is 10.9.  The package file for RxSwift currently has the minimum deployment target set to 10.10 [here](https://github.com/ReactiveX/RxSwift/blob/main/Package.swift#L45C34-L45C40).

Can you update the minimum deployment target to 10.10 on your podspec please to fix this issue?

The only workaround we have at the moment is using Xcode 14.x to do the push but because Sonoma does not support Xcode 14.x this won't work much longer for us.

**Expected outcome**:

Expected to be able to `pod trunk push` a pod that depends on RxSwift without compilation failure.

**What actually happens**:

The push fails with 25 errors.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.6

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 15.1
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by Shannon-Yang** [comment]
I'm having the same problem, any updates?

**Comment by freak4pc** [comment]
Seems there was a discrepancy with the podspec, I fixed it [here](https://github.com/ReactiveX/RxSwift/commit/b0811e8d70bdf7bab26fd3ce5c5c98f707dc3495) but it might need a new release being cut if we're referring specifically to a podspec.

**Comment by freak4pc** [comment]
@mjohnson12 @Shannon-Yang Please try RxSwift 6.7.0
