### ISSUE TITLE
No available version for github "ReactiveX/RxSwift" satisfies the requirement: == 6.6.0

### ISSUE THREAD

**Issue by er-tuanlk** [ReactiveX/RxSwift#2590]
**Short description of the issue**:

Cannot get ReactiveX/RxSwift with version is 6.6.0

I setup my Cartfile:

`github "ReactiveX/RxSwift" "6.6.0"`

**Expected outcome**:

Can down load rxswift normally

**What actually happens**:

Got the error: No available version for github "ReactiveX/RxSwift" satisfies the requirement: == 6.6.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [x] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

Xcode15.0.1

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
I'm not too sure what's the issue there, that version does exist. https://github.com/ReactiveX/RxSwift/tree/6.6.0
I'm unsure how that is an RxSwift issue 🤔 Doesn't it just work off the GitHub releases?

**Comment by freak4pc** [comment]
Any thoughts on this @er-tuanlk ?

**Comment by er-tuanlk** [comment]
@freak4pc, I do not know the root cause, but until I try to use `carthage bootstrap` instead of `carthage update`, I do not face this issue anymore.

**Comment by freak4pc** [comment]
Alright, will close for now :) Thanks.
