### ISSUE TITLE
`bind` function may cause ambiguity

### ISSUE THREAD

**Issue by harryzjm** [ReactiveX/RxSwift#2599]
RxCocoa  6.7.1
RxSwift  6.7.1
Xcode  15.3

```swift
extension ObservableType {
    public func bind<Result>(to binder: (Self) -> Result) -> Result {
        binder(self)
    }

    public func bind(onNext: @escaping (Element) -> Void) -> Disposable {
        self.subscribe(onNext: onNext,
                       onError: { error in
                        rxFatalErrorInDebug("Binding error: \(error)")
                       })
    }
}
```

This two function may cause ambiguity in some cases, such as:
```swift
let ry = BehaviorRelay<Bool>(value: false)
override func viewDidLoad() {
    super.viewDidLoad()
    
    _ = ry.bind { [weak self] bl in
        self?.test()
    }
}

func test() {}
```

In this case, the `test` method will be executed synchronously, don\`t as I expect bind to `test` function if `ry` changed
So I suggest change the name of the `func bind<Result>(to binder: (Self) -> Result) -> Result` method

**Comment by danielt1263** [comment]
Interesting... As a side note though, ignoring the return value in this case is a guaranteed memory leak, and assigning it to a dispose bag will resolve the issue regarding which method will be used.

So, I agree with you in theory, but in practice, this isn't an issue.

**Comment by harryzjm** [comment]
yeah, In our project, there have `.take(1)` in the operators, so we often ignore the result, don\`t assigning it to dispose bag.

**Comment by danielt1263** [comment]
I personally have always used `.bind(onNext: { })` so I've never noticed the issue...

**Comment by harryzjm** [comment]
You are right, But I just like less code, May be I should write more clearly.

**Comment by freak4pc** [comment]
Hey there, I don't really see how this is an issue with RxSwift :) 

It's not ambiguity if you choose to use a possibly wrong overload. We also can't (and won't) rename methods that are part of the library for a very long time. 

My main suggestion would be that if you have a very specific use case where you use take(1) a lot, etc, perhaps write your own extension on Observable for your own project. I'm not entirely sure this fits in the scope of fixing anything inside the project.

Thanks for the suggestion though!
