### ISSUE TITLE
ITMS-91061:丢失的隐私清单- 您的应用包含"Frameworks/RxSwift.framework/RxSwift"

### ISSUE THREAD

**Issue by KingSering** [ReactiveX/RxSwift#2628]
ITMS-91061:丢失的隐私清单- 您的应用包含"Frameworks/RxSwift.framework/RxSwift"，其中包括 OneSignalOutcomes，该SDK在文档中被标识为影响隐私的第三方SDK。从2024年11月12日起，如果新应用包含影响隐私的SDK，或应用更新添加新的影响隐私的新SDK，该SDK必须包含隐私清单文件。请与包含此文件的SDK提供商联系，以获得附有隐私清单的SDK更新版本。有关此策略（包括需要包含签名和清单的SDK列表）的更多详细信息，请访问:https://developer.apple.com/support/third-party-SDK-requirements.

https://developer.apple.com/support/third-party-SDK-requirements
![image](https://github.com/user-attachments/assets/a3abe333-435e-4abb-87d3-86c5ce041142)

**Comment by KingSering** [comment]
只要项目中使用到了rxswift 提交app审核时就会被指出缺少隐私清单，苹果的官网也特意指出rxswift框架缺少隐私清单

**Comment by freak4pc** [comment]
This is a duplicate of #2625 
Please follow there
