### ISSUE TITLE
Build fails because of missing PrivacyInfo.xcprivacy after Upgrading to 6.8.0

### ISSUE THREAD

**Issue by Lutzifer** [ReactiveX/RxSwift#2631]
**Short description of the issue**:

Build fails because of missing PrivacyInfo.xcprivacy after upgrading to 6.8.0.
We use xcodegen to include the dependencies via SPM.

**Expected outcome**:

I can build the app with 6.8.0 the same way as before 6.8.0

**What actually happens**:

<img width="636" alt="Screenshot 2024-10-10 at 12 55 07" src="https://github.com/user-attachments/assets/3530b91d-47e3-405e-9fff-beb4eccdb328">

We get PrivacyInfo.xcprivacy errors

**Self contained code example that reproduces the issue**:

As the error happens on a project level, a code example is hard to provide but can try to whip up a standalone smaller project if needed.

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.8.0, release version

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 16.0 (16A242d)
```

**Installation method**:
  - [X] SPM

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [X] yes (which ones)

  15.4.0, 16.0.0

**Level of RxSwift knowledge**:

  - [X] I have a significant code base

**Comment by freak4pc** [comment]
I couldn't reproduce this in a fresh SPM project:
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/fa91ef19-9b91-4b17-a503-5798cd665649">

Also, we (monday.com) use Tuist (which works over XcodeGen) and we had no issues with upgrading/building. 

Can you provide some reproduction I could debug further?

**Comment by Lutzifer** [comment]
I'll see if I can extract something tomorrow, thx for having a look.

**Comment by freak4pc** [comment]
Device looks fine, too. LMK if you can reproduce something - I won't be available until next week but will take a look as soon as I can :) 

<img width="807" alt="image" src="https://github.com/user-attachments/assets/38fc0ca1-084c-4196-82d7-31ca23cb2262">

**Comment by Lutzifer** [comment]
Issue has somehow disappeared over night, seems to be some weird caching issue somewhere.

Thx for having a look again.
