### ISSUE TITLE
Cannot find 'Resources' in scope

### ISSUE THREAD

**Issue by hrvoje0099** [ReactiveX/RxSwift#2637]
Hello everyone, I have injected RxSwift into my project via SPM. I have a problem that for some reason it does not see the Resources object. RxSwift is important. The version is 6.8.0. It's strange that when I press CMD and click on Resource, Xcode sees it in the RxSwift package, but regardless it throws the error 'Cannot find 'Resources' in scope'. What am I doing wrong? Do I need anything else? Thanks
![image](https://github.com/user-attachments/assets/4aec36e9-1d52-4642-982d-435654cb7fcc)

**Comment by freak4pc** [comment]
Hey there, 
I'm sorry but we don't use GitHub to support issues with specific project setups, but only issues with the framework itself that applies to all users.

I suggest consulting the community slack channel on the matter, perhaps they can assist.

Closing

**Comment by freak4pc** [comment]
Resources is hidden behind a compile time flag. See here: https://github.com/ReactiveX/RxSwift/blob/main/Documentation/GettingStarted.md#enabling-debug-mode

**Comment by freak4pc** [comment]
This is more of an SPM question than an RxSwift question, perhaps asking in the slack channel or checking official SPM docs will be beneficial

To be honest though, I'm not 100% sure how it's possible to change build settings for dependencies in SPM. I haven't tried that directly
