### ISSUE TITLE
Create an org, for repos that are not RxSwift but are strongly related

### ISSUE THREAD

**Issue by orta** [ReactiveX/RxSwift#265]
### Proposal

Create an org, like RxSwiftCommunity. This hosts:

- guides.rxswift.org
- rxswift.org
- Other related projects

The production of this could make it easier to have a project like RxSugar, which could obviate things like [NSObject+Rx](https://cocoapods.org/pods/NSObject+Rx/) and centralize some of the things that might be questionable in core, e.g. https://github.com/ReactiveX/RxSwift/pull/262 https://github.com/ReactiveX/RxSwift/issues/254 and https://github.com/ReactiveX/RxSwift/issues/181 into their own thing.

**Comment by ashfurrow** [comment]
Neat.

**Comment by angerman** [comment]
Yep, sounds like a good idea.

**Comment by bontoJR** [comment]
I agree, so I moved forward and created it with all the necessary permissions. :tada:

**Comment by kzaher** [comment]
Awesome :)
@bontoJR love the graphics

Now I know where we'll put all of those extension projects. This repository is getting too crowded :)

:tada:

**Comment by bontoJR** [comment]
Yup, I do agree and we can keep under control all the "related" projects.

I will move RxBluetooth as soon as I am able to create a nice example how to use it with the Apple TV. I have something very nice in my mind. :smile: 

Let's keep RxSwift, RxBlocking and RxCocoa here, all the other extensions with a certain value, are going to be under the RxSwift Community organization :)

**Comment by orta** [comment]
Great, this is all looking awesome :+1:

**Comment by ashfurrow** [comment]
This is so cool! I have a few projects (see below) – what would the process be for considering moving them to the org? 

https://github.com/ashfurrow/NSObject-Rx
https://github.com/ashfurrow/Action

**Comment by bontoJR** [comment]
I am still unsure about the guideline, I took some inspiration from [here](https://github.com/finagle).

So I guess the code should be strongly connected to RxSwift or RxCocoa, of course, it should be "production ready" plus it should be available/working with CP or Carthage.

I moved RxAlamofire, for example, on the other hand I am waiting to improve RxBluetooth before moving it under RxSwiftCommunity. I think NSObject+Rx should definitely fit all 3 requirements and can be moved right away. :smile:

**Comment by ashfurrow** [comment]
Cool, I've created a "contributors" repo and opened an issue to discuss initial guidelines: https://github.com/RxSwiftCommunity/contributors/issues/1

And also an issue to move NSObject+Rx over: https://github.com/ashfurrow/NSObject-Rx/issues/3

Help on any of these is welcome!

**Comment by ashfurrow** [comment]
I've moved over NSObject+Rx, working fine now :cactus:
