### ISSUE TITLE
My Application is open source which used RxSwift for Reactive Programming

### ISSUE THREAD

**Issue by zixun** [ReactiveX/RxSwift#273]
My Application( [CocoaChina+](https://github.com/zixun/CocoaChinaPlus) ) is open source. It used RxSwift for Reactive Programming.
and some of other swift opensource library,such as : [Neon](https://github.com/mamaral/Neon), [Ji](https://github.com/honghaoz/Ji)

Thanks for RxSwift 😄

**Comment by kzaher** [comment]
Hi @zixun ,
You're welcome :)

Did see some some traffic coming from your blog to this project. Thnx for that. Hope we'll send some traffic back :)

Looks like your app is gaining some popularity, good luck with it :)

I guess this is not an issue per se, so closing this one :)
