### ISSUE TITLE
Make bindingErrorToInterface Public

### ISSUE THREAD

**Issue by ashfurrow** [ReactiveX/RxSwift#274]
Hey there! Any reason why we can't make [`bindingErrorToInterface`](https://github.com/ReactiveX/RxSwift/blob/c909f0f572d84f7b7578c55b7b16d853ebad5f8a/RxCocoa/Common/RxCocoa.swift#L65-L72) a public function? It'd save me duplicating the function in my own codebase.

**Comment by kzaher** [comment]
Hey :)

I think that's internal convenience method prisoner dilemma :)

I don't think it has clear enough definition and clear place in public interface to be there. I think all libraries have them :)

I think that's one of those things that doesn't have any real meaningful logic, it's more of a configuration written in code, policy that you would possibly want to change on project level for various reasons, etc ...

I would love if this was public
https://github.com/Alamofire/Alamofire/blob/master/Source/Alamofire.swift#L86

... but I kind of understand why it would be ugly for them to make it public :)

That was kind of my best attempt to explain why it's not public.

¯\\\_(ツ)\_/¯

**Comment by ashfurrow** [comment]
Makes sense! Thanks! :balloon:
