### ISSUE TITLE
How to cancel a subscription to an observable in Rxswift ?

### ISSUE THREAD

**Issue by zixun** [ReactiveX/RxSwift#277]
How to cancel a subscription to an observable in Rxswift ?

**Comment by fpillet** [comment]
Subscriptions return disposables. Keep the reference to the `Disposable` and when you want to cancel the subscription, simply `disposable.dispose()`

You can also use `DisposableBag` when you need to keep multiple disposables and dispose them all at once.

See https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#disposing

**Comment by zixun** [comment]
thx,I got it
