### ISSUE TITLE
what's `flatMap`'s behaviour?

### ISSUE THREAD

**Issue by Fab1n** [ReactiveX/RxSwift#281]
is `flatMap` like `map.switchLatest()`? Does it dispose inner ongoing observables when the outer signal fires a new event?
What are common pitfalls using `flatMap`?

**Comment by yury** [comment]
`flatMap` merges all events from all inner observables
`switchLatest` take events from latest observable

**Comment by carlosypunto** [comment]
They aren't the same. 
http://reactivex.io/documentation/operators/flatmap.html
http://reactivex.io/documentation/operators/switch.html

i.e. a common pitfalls using flatMap is: when map's closure will go to return an observable the result of map will be a `Observable<Observable<YourType>>`. But, if you want an `Observable<YourType>`, you must to use flatMap

**Comment by Fab1n** [comment]
Ok, one thing I wanted to know is its behavior in cancelation... In RxJS there is a `flatMapLatest`. The Rx site makes clear that only `flatMapLatest` disposes its inner observables

**Comment by carlosypunto** [comment]
both ways are correct
