### ISSUE TITLE
How to use rx_tap on UIButton of UITableViewCell 

### ISSUE THREAD

**Issue by shiratsu** [ReactiveX/RxSwift#288]
I have a similar question with https://github.com/ReactiveX/RxSwift/issues/248.
But I couldn't find answer above issue.

I'm trying to use rx_tap on a table view cell button.
after tapping button,then tableview reload,then rx_tap event happen without tapping.
Maybe i think subscribe is still cotinueing.

how can i prevent adding new rx_tap every time i reload the tableview?

```
import UIKit
#if !RX_NO_MODULE
import RxSwift
import RxCocoa
#endif

public protocol ConditionCellDelegate : class {
    
    func updateCell(atIndexPath: NSIndexPath,dic_pushcondition:NSDictionary)
    
}


@IBDesignable
class ConditionCell: ABMenuTableViewCell {
    
    
    ...
    @IBOutlet weak var cond_switch: OnOffBtn!
    weak var delegate:ConditionCellDelegate!
    
    
    var disposeBagCell:DisposeBag = DisposeBag()
    
    ....
    
    func setUpdateAction(atIndexPath:NSIndexPath,dic_pushcondition:NSDictionary){
        self.cond_switch.rx_tap
            .map{ [unowned self] _ in
                
                
               ....
                
                return send_param
            }
            .catchError{ error -> Observable<NSDictionary> in
                
                
                AppDelegate.sharedAppDelegate().showRxSwiftCommonMessage("更新できませんでした", message_type: TWMessageBarMessageType.Error, error: error)
                
                return empty()
                
            }
            .subscribeNext { [unowned self] send_param  in
                
                
                ....
                
            }.addDisposableTo(self.disposeBagCell)
        
    }
    
    
    
    
}
```

**Comment by carlosypunto** [comment]
Hello @shiratsu, I think you must to create a new DisposeBag on each cell reuse 

```
class TableViewCell: UITableViewCell {

    var disposeBagCell:DisposeBag = DisposeBag()

    ...
    
    override func prepareForReuse() {
        disposeBagCell = DisposeBag()
    }

}
```

**Comment by shiratsu** [comment]
Oh!That's simple.I will try it.Thank you!

**Comment by carlosypunto** [comment]
😉

**Comment by charlag** [comment]
May I ask why you're assigning to `disposeBagCell` two times?

**Comment by sergdort** [comment]
Hi, @charlag  

Because life cycle of `UITableViewCell` ends on `prepareForReuse` so next time it will display another data, and you probably want to dispose previous subscriptions

**Comment by scotteg** [comment]
I usually new up a cell's disposeBag in `didEndDisplayingCell` 🙂

**Comment by aventurella** [comment]
I assume then, that if you add some listening thing on the cell from the outside, you add the disposable back to it's disposeBag:

```swift
class TableViewCell: UITableViewCell {
    var disposeBag = DisposeBag()
    let subject = PublishSubject<Void>()

    override func prepareForReuse() {
        disposeBag = DisposeBag()
    }

   @IBAction onSomeTableViewCellViewAction(_ sender: AnyObject){
        subject.onNext(())
    }
}

// then when you dequeue for reuse from the UITableViewDataSource
let item = tableView.dequeue...
item.subject
    .asObservable()
    .subscribe(onNext: {...})
    // put it in the items disposeBag so when it's reused it will be cleared
    .disposed(by: item.disposeBag) cleared.
```

**Comment by anirudhamahale** [comment]
I send ID in the subject but it gives some other ID only.

**Comment by ShenYj** [comment]
> Hello @shiratsu, I think you simply must to create a new DisposeBag on each cell reuse
> 
> ```
> class TableViewCell: UITableViewCell {
> 
>     var disposeBagCell:DisposeBag = DisposeBag()
> 
>     ...
> 
>     override func prepareForReuse() {
>         disposeBagCell = DisposeBag()
>     }
> 
> }
> ```

The disposeBag var in Cell can resolve this problem, but I have another question
The Observable in the Cell will unused when cell is reused, How can I resolve both of them?
