### ISSUE TITLE
Can I translate this to chinese and pull request to you :)

### ISSUE THREAD

**Issue by lixin147741** [ReactiveX/RxSwift#289]

**Comment by bontoJR** [comment]
What about translating `guides.rxswift.org` so we can add `cn.rxswift.org` after `es.rxswift.org`?

**Comment by lixin147741** [comment]
It's a wanderful idea. I'm translating now

**Comment by bontoJR** [comment]
Great!!! :+1: 

Can you reopen this issue in the dedicated repository, so we can give you push access after the first PR?

Thanks!
