### ISSUE TITLE
Can I forward two original delegates with RxCocoa?

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#293]
For example, there are two original UIScrollViewDelegate object want to listen to the same scrollView.

**Comment by frogcjn** [comment]
`scrollView.rx_setDelegate`, this method only allowed one delegate per scrollView.

I have tried:
```swift
        scrollView.rx_delegate.setForwardToDelegate(delegateA, retainDelegate: false)
        scrollView.rx_delegate.setForwardToDelegate(delegateB, retainDelegate: false)
```
It is not working very well, only the `scrollViewDidScroll` pass to delegateA. other method will be ignored.

**Comment by kzaher** [comment]
Hi @frogcjn ,

the idea is that if you want to have multiple observers, you would use Rx mechanism of observable sequences.

In this case that could maybe work, but in general case, if you have value being returned from a delegate method, you can't reconcile the changes :)

**Comment by kzaher** [comment]
I guess this could be considered closed. Let me know if there are some further questions regarding this :)
