### ISSUE TITLE
Requesting a more simple testable MVVM example

### ISSUE THREAD

**Issue by rubenfonseca** [ReactiveX/RxSwift#297]
Hello :-) Thank you for this beautiful project.
I would like to request a simple example of how to properly use RxSwift to build a simple testable MVVM screen.

Here's what I have in mind:
- username text field
- password text field
- login button
- activity indicator to show that a network request is in place
- BONUS: show alert if the network request fails?

Of course the logic that drives the screen would reside in the ViewModel so it could be easily tested. For instance:
- username and password need to be both present for the login button to be enabled
- while the network request is in flight, the login button should be disabled, and the activity indicator should be animating

I'm volunteering to write the tests, as long as you write a good ViewModel :-)

**Comment by dtartaglia** [comment]
Check this out and see what you think... And suggestions are welcome! https://github.com/dtartaglia/MVVMSwiftSample/blob/feature/make_reactive/MVVM/DetailViewController.swift

**Comment by kzaher** [comment]
We'll also try to add that example to our example project, since it looks common :)

**Comment by carlosypunto** [comment]
@rubenfonseca I have, after consultation, an example that I think meets your needs. And suggestions are welcome! https://github.com/carlosypunto/ReallySimpleMVVMExampleWithRxSwift

**Comment by kzaher** [comment]
An example how to do MVVM has been just released with beta.4. 

I've polished GitHub login example a little and refactored it in MVVM paradigm. I think this should be solved now :)

ViewModel logic is totally isolated from the rest of the world with protocols :)

I'm going to close this for now so it's easier to track issues. Please let me know if we need to reopen this.

**Comment by dtartaglia** [comment]
I realize this is "closed" but I would like to discuss it. Is that possible? 

I see that the MVVM sample you created makes extensive used of the `Variable` class, but Variable is just another name for `BehaviorSubject` and the tutorials I've read so far about Rx are pretty explicit that Subjects are only for simple examples and not appropriate for actual production code. (For example: http://www.introtorx.com) While I accept that what you have is a "simple example" I would really like to see what MVVM would look like as a production example...

**Comment by bontoJR** [comment]
I can write a book about subjects, but here's what I learned using RxScala and RxJava: considering the nature of the projects and the fact that they were mostly server side (if not all of them), I consider the usage of subjects a bad thing. I know they are necessary, not all libraries have shining interfaces to be easily bridged to Rx, but I found the server side development somewhat _simpler_ if compared to what we have in a UI-driven system.

Considering how big is the Cocoa space and the huge number of libraries that are fully imperative, the usage of subjects is mandatory, it's the only way to bridge the imperative nature of Cocoa, to the declarative style of Rx. In Java, server side, I learned that, when this happen, a good habit is to mask the `Variable` behind a getter that returns an observable, for example a step counter variable can be expressed `private var _stepCounter = Variable(val: 0)` and then we can make the `stepCounter` public:
 
```
var stepCounter: Observable<Int> = {
   get {
      return self._stepCounter.asObservable()
   }
}
```

This is how I was used to work with RxJava. In this way the view model is read-only. Please be aware that sometimes a read-write relationship is required and for this reason we need to expose the variable. :)

I would really like to go ahead on the discussion with this, I wrote a small fitness app based on this assumptions, I can later publish this on Github and we can eventually discuss the best way to MVVM with Rx on iOS/Mac. :)

**Comment by rubenfonseca** [comment]
I knew it wasn't that simple! This is the problem I'm experiencing with the Rx world in general: no one can agree what's "the right way to do it". Is it variables? subjects? units?

**Comment by kzaher** [comment]
@rubenfonseca I don't think there is any disagreement, only misinterpretation :) I think that was what @bontoJR was trying to explain.

There are also language (Swift) and environment specific things, but those are tiny details IMHO.

The gist is, you should use subjects/Variables in as few places as possible, but you will need them or some other isomorphic mechanism when dealing with UI.

In this particular scenario we could have got away with init injected observable sequences, but that is not a scalable solution.
E.g. When you have a table/collectionview and cell reusing, you need to break the observable sequence going from UITable/CollectionViewCell to view model on `prepareForReuse` and resume it afterwards.

**Comment by rubenfonseca** [comment]
@kzaher reading back my comment, I totally forgot to say the most important thing: **thank you** for writing this nice example. Already learned a lot :-) Please don't misinterpret my sad comment!

**Comment by kzaher** [comment]
We've added parallel MVVM example of github signup using vanilla observables and Driver.

We've also added table view editing example of using immutable view model.

There are also marble unit tests attached in example app.

I'll silently close this for now. We can reopen this if needed :)

**Comment by rubenfonseca** [comment]
Thank you so much for this fine example :D
