### ISSUE TITLE
Duplicated call for Observable

### ISSUE THREAD

**Issue by tomaszbak** [ReactiveX/RxSwift#298]
I have simple code like this:

    let export = PublishSubject<Void>()
    let url: Observable<NSURL> = export.flatMapLatest {
        return createAsyncOpeation()
    }

When I subscribe twice to url, my async operation, unexpectedly for me, will be called twice. How should I create observable to subscribe many times and always get the same url from previous operation?

**Comment by phamquochoan** [comment]
I think you should take a look at Connectable Observable:
https://github.com/ReactiveX/RxSwift/blob/master/Documentation/API.md#connectable-observable-operators

I'm new to Rx too, can't help you further with sample code.

**Comment by tomaszbak** [comment]
Thanks for reply, connectables are answer that I was looking for, code below seems to work as I expected.

    let export = PublishSubject<Void>()
    let url = export.flatMapLatest {
        return createAsyncOpeation()
    }.publish()
    
    url.connect()
    
    for _ in 0...10 {
        url.subscribeNext { _ in }
    }

Is this a valid way of using connectables?

**Comment by kzaher** [comment]
@tomaszbak you probably want 

```
let export = PublishSubject<Void>()
let url = export.flatMapLatest {
    return createAsyncOpeation()
}.shareReplay(1)
```

**Comment by tomaszbak** [comment]
Thanks for sharing, this worked for me too. Taking it even further, if I don't need to buffer elements this two snippets do the same thing, yes?
1:

    let export = PublishSubject<Void>()
    let url = export.flatMapLatest {
        return createAsyncOpeation()
    }.shareReplay(0)
2:

    let export = PublishSubject<Void>()
    let url = export.flatMapLatest {
        return createAsyncOpeation()
    }.share()

**Comment by kzaher** [comment]
@tomaszbak yes, you are correct

**Comment by tomaszbak** [comment]
I have answers to all my questions so I'm closing the issue. Thank you.
