### ISSUE TITLE
UIBarButtonItem rx_tap resource leak

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#302]
I have created empty viewcontroller with only one barbutton.
And in deinit I see that rs -> 23 but according to balance has to be 22
May be I do something wrong?

```swift

   #if TRACE_RESOURCES
   private let startResourceCount = RxSwift.resourceCount
   #endif


   let disposableBag = DisposeBag()

   override func viewDidLoad() {
      super.viewDidLoad()
      
      #if TRACE_RESOURCES
         print("Number of start resources = \(resourceCount)")
      #endif
      
      self.rightBarButton.rx_tap
         .subscribeNext { [unowned self] _ -> Void in
            self.dismissViewControllerAnimated(true, completion: nil)
         }.addDisposableTo(disposableBag)
}

   deinit {
      print("\(self)")
      #if TRACE_RESOURCES
         print("View controller disposed with \(resourceCount) resources")
         
         let numberOfResourcesThatShouldRemain = startResourceCount
         let time = dispatch_time(DISPATCH_TIME_NOW, Int64(0.1 * Double(NSEC_PER_SEC)))
         dispatch_after(time, dispatch_get_main_queue(), { () -> Void in
            let rs = resourceCount
            assert(resourceCount <= numberOfResourcesThatShouldRemain, "Resources weren't cleaned properly")
         })
      #endif
   }

```

**Comment by tailec** [comment]
`Deinitializers are called automatically, just before instance deallocation takes place`
from 
https://developer.apple.com/library/prerelease/mac/documentation/Swift/Conceptual/Swift_Programming_Language/Deinitialization.html#//apple_ref/doc/uid/TP40014097-CH19

**Comment by sergdort** [comment]
I'm not sure how its related to the resources count =)

**Comment by frogcjn** [comment]
deinit will be called before disposableBag deinit.
So if you want to test this, you can call disposableBag = DisposeBag() at first.

**Comment by frogcjn** [comment]
pseudocode of Swift deinit:

```swift
realDeinit{
     self.deinit()
     propertyOne.realDeinit()
      propertyTwo.realDeinit()
     ...
}
```

**Comment by kzaher** [comment]
@sergdort I don't think this is resource leak.

We have that same test in API wrappers example. I think that probably some global resource is lazy loaded for some reason, and that's what causing that difference.

You can test that theory by removing the assert and push/pop VC for a couple of times.
If the resource count doesn't increase, in that case everything is ok, and there is no leak.

Please let me know is it increases after several push/pops or not.

Our example app is designed so that code works always ideally since we additionally test for leaks in automated way before releases and we force load lazy resources at startup 

```
public class RootViewController : UITableViewController {
    public override func viewDidLoad() {
        super.viewDidLoad()
        // force load
        GitHubSearchRepositoriesAPI.sharedAPI.activityIndicator
        DefaultWikipediaAPI.sharedAPI
        DefaultImageService.sharedImageService
    }
}
```

Your app might not be designed the same way.

**Comment by sergdort** [comment]
Hi @kzaher ,
Yep you are right, the number of resources remains the same after several present/dismiss .
So I guess I should just look on number of resources rather then putting assertion

**Comment by kzaher** [comment]
Yeah, I think this makes it really easy to just print out resources to terminal or use some other visual mechanism.

It's not fully automatic like we have in our example app, but close enough :) 

If you'll have some leaks, it probably won't be one or two object ;), it will reaaaally stick out.

**Comment by sergdort** [comment]
Thanks :+1: , I guess we can close it now =)
