### ISSUE TITLE
concat().take(1) runs all observables, instead of subscribing when needed.

### ISSUE THREAD

**Issue by bclymer** [ReactiveX/RxSwift#303]
I'm new to the Rx scene, however after reading [this blog post](http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/#comment-2093768735) I tried to implement the same thing for an `in memory cache` -> `core data store` -> `network fetch` system. I was noticing however that even if the cache hit, the core data request and network fetch still kicked off. Here's some example code (this was run in the provided playground)

```
let obs1: Observable<Int> = create { ob in
    print("Running obs 1")
    ob.onNext(1)
    ob.onCompleted()
    return AnonymousDisposable {
        print("Disposing obs 1")
    }
}

let obs2 = obs1.concat(create { ob in
    print("Running obs 2")
    ob.onNext(2)
    ob.onCompleted()
    return AnonymousDisposable {
        print("Disposing obs 2")
    }
})

let obs3 = obs2.concat(create { ob in
    print("Running obs 3")
    ob.onNext(3)
    ob.onCompleted()
    return AnonymousDisposable {
        print("Disposing obs 3")
    }
}).take(1)

obs3.subscribeNext({
    print($0)
})
```

Actual Output
```
Running obs 1
1
Disposing obs 1
Running obs 2
Disposing obs 2
Running obs 3
Disposing obs 3
```

Expected Output
```
Running obs 1
1
Disposing obs 1
```
So although the observable doesn't publish the 2 and 3 due to the `Take(1)`, the 2 latter observables are fired off taking up unnecessary resources.

This very well may be a lack of understanding, and if so I apologize. If so, is there a way to accomplish the multi-layered fetch?

**Comment by kzaher** [comment]
Hi @bclymer ,

I believe RxJava internally works on a slightly different engine. They first request certain number of elements from system, and then system waits until new elements are produced.

Default `subscribe` interface just requests `Int64.max` elements :)

For other Rx implementations, I believe that the correct way to produce elements in a way that can be interrupted is to use schedulers.

The reasoning is, if you don't schedule some work on specific scheduler and in that way set "interrupt" points, system won't be able to cancel upcoming work for you (although only one element will be returned, filtering results is not a problem).

If you don't have some specific scheduler to run you work at, but want to run it "immediately", you can use `CurrentThreadScheduler.instance`.

This is how you would write that logic in RxSwift 

```
let scheduler = CurrentThreadScheduler.instance

let obs1: Observable<Int> = create { ob in
    print("Running obs 1")
    let d = scheduler.schedule(()) {
        ob.onNext(1)
        ob.onCompleted()
        return NopDisposable.instance
    }
    return AnonymousDisposable {
        print("Disposing obs 1")
        d.dispose()
    }
}

let obs2 = obs1.concat(create { ob in
    print("Running obs 2")
    let d = scheduler.schedule(()) {
        ob.onNext(2)
        ob.onCompleted()
        return NopDisposable.instance
    }
    return AnonymousDisposable {
        print("Disposing obs 2")
        d.dispose()
    }
    })

let obs3 = obs2.concat(create { ob in
    print("Running obs 3")
    let d = scheduler.schedule(()) {
        ob.onNext(3)
        ob.onCompleted()
        return NopDisposable.instance
    }
    return AnonymousDisposable {
        print("Disposing obs 3")
        d.dispose()
    }
    }).take(1)

obs3.subscribeNext({
    print($0)
})
```

... or the most proper way if you want that each particular event is cancellable.

```
let obs1: Observable<Int> = create { ob in
    print("Running obs 1")
    let d = scheduler.schedule(()) {
        ob.onNext(1)
        return scheduler.schedule(()) {
            ob.onCompleted()
            return NopDisposable.instance
        }
    }
    return AnonymousDisposable {
        print("Disposing obs 1")
        d.dispose()
    }
}

let obs2 = obs1.concat(create { ob in
    print("Running obs 2")
    let d = scheduler.schedule(()) {
        ob.onNext(2)
        return scheduler.schedule(()) {
            ob.onCompleted()
            return NopDisposable.instance
        }
    }
    return AnonymousDisposable {
        print("Disposing obs 2")
        d.dispose()
    }
    })

let obs3 = obs2.concat(create { ob in
    print("Running obs 3")
    let d = scheduler.schedule(()) {
        ob.onNext(3)
        return scheduler.schedule(()) {
            ob.onCompleted()
            return NopDisposable.instance
        }
    }
    return AnonymousDisposable {
        print("Disposing obs 3")
        d.dispose()
    }
    }).take(1)

obs3.subscribeNext({
    print($0)
})
```

You can take a look at how `generate` operator is implemented for further reference :)

**Comment by bclymer** [comment]
@kzaher thank you so much! Your explanation made sense to the point where I feel like I understand the changes I made now. (also your code worked perfectly). I'll close out this issue. :tophat:
