### ISSUE TITLE
catchError after a flatMap() or map.switchLatest() not being called

### ISSUE THREAD

**Issue by Fab1n** [ReactiveX/RxSwift#304]
isn't it possible to catch any error after a sequence of maps and thus convert the error signal to a normal observable with which I can handle the error in the UI accordingly?

Check this out: How to do something like this?
``` swift
let imageSignal = button.rx_tap 
    .flatMap(API.loadImages)
    .flatMap(animateImage)

let successErrorState = imageSignal
    .map { _ in false }

let errorErrorState = imageSignal
    .catch { error in
        print("\(error)")
        return just(true)
    }

sequenceOf(successErrorState,errorErrorState)
    .merge()
    .subscribeNext { isError in
         if isError {
             // show error UI
         } else {
             // show success UI
         }
    }
```

**Comment by Fab1n** [comment]
why does `catchError` seem to only work directly on the failing observable, like `API.loadImages` i.e.?

**Comment by Fab1n** [comment]
is `.publish()` and then `imageSignal.connect()` the solution? 
I want to handle errors just like any other event... Many times we have to react on errors in the same way than on regular events

**Comment by frogcjn** [comment]
Is this helpful?
`catchErrorJustReturn()`

**Comment by kzaher** [comment]
@Fab1n ,

That is a direct consequence of sequence grammar and the reason why Rx is so powerful :)

You need to do something like this :) Not a big difference IMHO.

```
let imageSeque = button.rx_tap 
    .flatMapLatestMap { _ in
            return API.loadImages
                 .flatMap(doSomething1)
                 .flatMap(doSomething2)
                 .flatMap(doSomething3)
                 .catchErrorJustReturn(somethingToPresentWhenErrorHappens)
     }
    .flatMap(animateImage)
```

Error handler is reserved for failures that destroy the underlying rx mechanism.

For next values you can use, explicitly unwrapped optionals, your enum type, Result ...

**Comment by Fab1n** [comment]
thank you very much @kzaher and @frogcjn. I got my head around this! But I have another problem with .catchError. I opened another issue for that: #316
