### ISSUE TITLE
move TestScheduler from test target to RxSwift framework target

### ISSUE THREAD

**Issue by aler** [ReactiveX/RxSwift#305]
TestScheduler and it's dependencies are very useful for testing reactive code. It would be nice to have them public in RxSwift framework.

**Comment by kzaher** [comment]
Hi @aler ,

yes, the plan is to publicly expose TestScheduler, and I would like to expose a bunch of other test mock classes. We'll maybe create a new project for that.

**Comment by kzaher** [comment]
There is a new project called `RxTests` that has virtual time test scheduler and mock observable sequences.

That should close this one. Please let me know if we need to reopen it.
