### ISSUE TITLE
_Simple_ Sectioned UITableView example

### ISSUE THREAD

**Issue by IanKeen** [ReactiveX/RxSwift#306]
I would love to see a simple sectioned tableview example without the noise of MVVM or api calls. Just a simple observable bound to a table to show a couple of sections with a couple of rows.

This has been a major pain point for me lately, I have been through the sample code which appears out of date... as does every other example I have come across

**Comment by frogcjn** [comment]
Is this helpful?
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/PartialUpdates/PartialUpdatesViewController.swift

**Comment by IanKeen** [comment]
There are 3 _different_ rx views going on in that example... I was able to eventually brute force some code into working but the provided examples were not _immediately_ helpful - Rx is a new paradigm to a lot of people and I think some bare bones examples are _much_ more valuable than anything else to ease the learning curve

**Comment by kzaher** [comment]
@IanKeen We'll try to do something about it :)

**Comment by IanKeen** [comment]
Thank you! I did eventually get it up and running to a point.. still playing a little but just wanted to create this issue to add it to your radar :) thanks guys!!

**Comment by mikefinney** [comment]
@IanKeen Glad you got it up and running. :+1:  Do you have or can you make a public example that shows the simpler tableview use case example? Who knows how many people it could help?

**Comment by kzaher** [comment]
I've added simple examples for RxExample app :)
I'll close this for now. Let me know if you need more simple examples in RxExample project.

We can reopen this if needed.
