### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by bontoJR** [ReactiveX/RxSwift#310]
Swift is now open source and it comes with a package manager. We need to add the `Package.swift` file ti support it.

**Comment by kzaher** [comment]
Yeah, reading the docs :)

Ugh, yeah, this will be painful ...

I think that we should probably wait a while until we investigate what it takes to run this on Linux, or until Swift package manager releases won't look like this -> swift-2.2-SNAPSHOT-2015-12-01-b :)

If you (or someone else) have time to try to set this up on Linux maybe, that would be sweet, or at least investigate what do we need to figure out to support it :)

It looks like GCD is going on a road trip https://github.com/apple/swift-corelibs-libdispatch, NSRecursiveLock is just a simple wrapper for pthread_mutex_lock, and there has to be some kind of spin lock in Linux :)

I think this is everything we need.

I'm little torn between trying to make next release, working on `rx_sentMessage` and trying to polish `Drivers` and RxCocoa delegate interface :)

Don't think my brain can joggle with one more thing :) I guess if nobody else has time to try this, then I'll try after a week or two.

**Comment by orta** [comment]
SPM won't be "out" for ~9 months or so, not worth thinking about too soon FWIW

**Comment by bontoJR** [comment]
@orta I am aware of that, the current build is barely sable and future development will break changes.

I opened this to discuss and keep tracking of the evolution.

**Comment by kzaher** [comment]
We have supported it in latest RC.

It's still not perfect because spm has problems with parsing RC version, and unsure how to compile RxCocoa using it, but it does work :)

We've done everything possible for now.

Closing this one :)
