### ISSUE TITLE
Cannot load module 'RXSwift' as 'RxSwift'

### ISSUE THREAD

**Issue by remirobert** [ReactiveX/RxSwift#319]
Hello,

I am having an issue to install and use RXSwift.
I tried every solutions available, carthage, cocoapod, and even with the git submodule.

I always have the same issue : 

Cannot load module 'RXSwift' as 'RxSwift'

**Comment by carlosypunto** [comment]
Hi @remirobert,

Is RxSwift, and not RXSwift
