### ISSUE TITLE
Observe current and previous value

### ISSUE THREAD

**Issue by tyregor** [ReactiveX/RxSwift#320]
Hi everyone,

I was wondering if it is somehow possible to access a Variables current and previous value without saving intermediate state in some other variable?

What I like to do is to observe a `Variable<[Int: Bool]>` , construct a diff upon change and work with that.

Hints or complete solutions are much appreciated :smile:

**Comment by kzaher** [comment]
Hi @tyregor ,

I guess there are number of ways to do it :)

You can do something like

```
let a = Variable([1:true])

let diff = zip(a, a.skip(1)) { ($0, $1) }
```

**Comment by tyregor** [comment]
Hi @kzaher ,

this is truly elegant and shows me just how much I still have to learn.

Thx
