### ISSUE TITLE
dispose is called on subscribe

### ISSUE THREAD

**Issue by NebulaFox** [ReactiveX/RxSwift#321]
For some reason my Disposable is being disposed on subscribe and thus cancelling my request prematurely.

In the example below I use the stack trace to pin point that the subscription is being disposed immediately.
   
    let obs = RxSwift.deferred{
            RxSwift.create { observer in
                let request = Alamofire.request(.GET, "http://google.com")
                observer.on(.Next(request))
                observer.on(.Completed)
                
                return AnonymousDisposable {
                    let v: Int? = nil 
                    v! // should never be called
                    request.cancel()
                }
            }
        }

    let subscription = obs.subcribe { event in
        print("event \(event)")
    } // crashes on subscribe

Is this correct behaviour?

**Comment by carlosypunto** [comment]
Hi @NebulaFox,

I believe what you find is this:



```
RxSwift.create { observer in
            let request = Alamofire.request(.GET, "http://google.com").response { response in
            
            	// here check error if exist sen an error event
            
                observer.on(.Next(response))
                observer.on(.Completed)
            }

            return AnonymousDisposable {}
        }
```

**Comment by fpillet** [comment]
First off, you don't need to use `deferred` since your subscription method will be called at subscription time. Second, you're starting a request but never expecting any result, thus completing immediately. So yes, disposable being called is normal.

Finally, rather than crashing, you could make efficient use of debugger breakpoints :)

**Comment by fpillet** [comment]
@carlosypunto one should also make sure to cancel the request on `dispose`, in case subscriber didn't wait for it to complete and moved on to something else:

```
RxSwift.create { observer in
            let request = Alamofire.request(.GET, "http://google.com").response { response in

                // here check error if exist sen an error event

                observer.on(.Next(response))
                observer.on(.Completed)
            }

            return AnonymousDisposable {
                request.cancel()

            }
        }
```

**Comment by carlosypunto** [comment]
ohh, yeah, thanks @fpillet 👍

**Comment by NebulaFox** [comment]
I see. That makes sense.

I think I might need to expand the example then to see if my reasoning is correct.

    let obs = RxSwift.deferred{
        RxSwift.create { observer in
            let request = Alamofire.request(.GET, "http://google.com")
            observer.on(.Next(request))
            observer.on(.Completed)

            return AnonymousDisposable {
                let v: Int? = nil 
                v! // should never be called
                request.cancel()
            }
        }
    }.flatMap {
        return RxSwift.create { observer in
            req.responseJSON { response in
                if let json = response.result.value as? [String: AnyObject] where response.result.isSuccess {
                    observer.on(.Next(json))
                    observer.on(.Completed)
                } else if let error = response.result.error {
                    observer.on(.Error(error))
                }
            }

            req.resume()

            return NopDisposable.instance
        }

I separated the request from the result because I have a few different ways I may want to handle the request. The above will still crashes on subscription. What would be the best to do this then?

**Comment by NebulaFox** [comment]
Just did a quick test with your advice and it works.

I did not realise that Completed ended the observable. I thought it got propagated through with the next behind it.

Thanks again.
