### ISSUE TITLE
RxSwift Setup

### ISSUE THREAD

**Issue by kbala** [ReactiveX/RxSwift#325]
I am iOS Developer, beginner for the great Swift Lang :). I just read the doc about reactive programming and RxSwift. Would be great for my projects.

I just tried to setup the RxSwift using Carthage (github "ReactiveX/RxSwift" "2.0.0-beta.4"), I am using Xcode 7.1.1. Everything looks good, but I cannot access any methods from RxSwift.

For example, I write this line of code, let email = Variable("") and it says "User unresolved identifier 'Variable' ".

May I know where I did the mistake, Please help.

Thanks

**Comment by carlosypunto** [comment]
Hello @kbala,
You must import the library/es in each file where you use them
```
import RxSwift
import RxCocoa // if is necesary
```

**Comment by kbala** [comment]
Hi @carlosypunto,

Thanks for your reply.

But I am not sure where to find the library/es, actually saying i didn't get you exactly.

**Comment by carlosypunto** [comment]
I mean the import declaration: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Declarations.html#//apple_ref/doc/uid/TP40014097-CH34-ID354

**Comment by kbala** [comment]
ok, could you please my screenshot, http://screencast.com/t/APCtBLL8qp
Also, When I type "import Rx" the intelligence doesn't show the rest. http://screencast.com/t/MdAA333IQj

**Comment by kbala** [comment]
Hi guys,
I am still struggle with RxSwift setup into my project. I just upgraded my Xcode to 7.2, I use Carthage. not sure whats the best way to include rxswift into my project.

**Comment by tailec** [comment]
1. Add this to Cartfile

**Comment by tailec** [comment]
1. Add this to Cartfile `github "ReactiveX/RxSwift" "2.0.0-beta.4"`
2. Run `carthage update`
3. Go to your target in XCode, select `General` tab, add RxSwift and RxCocoa to `Linked Frameworks and Libraries` from `../Carthage/Build/iOS/`
4. Go to your target in XCode, select `Build Phases` tab, click plus button on the top and select `New Run Script Phase`
5. Put this to your newly created runscript:
![screen shot 2015-12-16 at 08 10 40](https://cloud.githubusercontent.com/assets/10499966/11835602/c3299dc8-a3cc-11e5-9797-5ebd46d08865.png)

**Comment by kbala** [comment]
Hi, Was busy.

I did as you suggested above, but still same issue for me. Also I got following warning:
ld: warning: ld: warning: ignoring file /Users/kbala/XcodeProjects/Test/RXTest/RxCocoa.framework/RxCocoa, missing required architecture arm64 in file /Users/kbala/XcodeProjects/Test/RXTest/RxCocoa.framework/RxCocoa (2 slices)ignoring file /Users/kbala/XcodeProjects/Test/RXTest/RxSwift.framework/RxSwift, missing required architecture arm64 in file /Users/kbala/XcodeProjects/Test/RXTest/RxSwift.framework/RxSwift (2 slices)

Please advise.

**Comment by kzaher** [comment]
Hm..., maybe try updating Carthage? ¯\_(ツ)_/¯

**Comment by orta** [comment]
Or switching to use CocoaPods.

**Comment by kbala** [comment]
Yes, Updating Carthage solved my issue, Thanks a lot @kzaher. I started learning/implementing RxSwift. :)
