### ISSUE TITLE
How to tie an Observables disposable to the lifetime of another Observable?

### ISSUE THREAD

**Issue by Fab1n** [ReactiveX/RxSwift#326]
Say in a function of a class I want to listen to an `Observable` but not to create a `DisposeBag` and add the `Disposable` to it. That can be because this class is a *singleton* and so `Disposables` keep growing.

How can I dispose my subscription when the incoming `Observable` is deallocated or better **completed**?

**Comment by fpillet** [comment]
The subscription is automatically disposed of when the observable completes.

**Comment by Fab1n** [comment]
Ok, yeah, that makes sense! But the warning then does not go away... This should be ok then

**Comment by fpillet** [comment]
Ah yes the warning -- people tend to do this:

```swift
_ = someObservable.subscribeNext { .... }
```
