### ISSUE TITLE
Dead Code In PartialUpdatesViewController RxExample code

### ISSUE THREAD

**Issue by mikefinney** [ReactiveX/RxSwift#329]
There are a few lines of dead code in the  [PartialUpdatesViewController](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/PartialUpdates/PartialUpdatesViewController.swift) RxExample code:

* import CoreData
* var moc: NSManagedObjectContext!
* var child: NSManagedObjectContext!

**Comment by kzaher** [comment]
Merged this :)
