### ISSUE TITLE
UITextView.rx_text doesn't catch iOS autocorrect text changes

### ISSUE THREAD

**Issue by timojaask** [ReactiveX/RxSwift#333]
`UITextView.rx_text` observes text changes via `textViewDidChange`. Unfortunately, when text changes due to iOS autocorrect, the `textViewDidChange` is not called, therefore `rx_text` never receives that new text.

You can test it by creating a text view, make sure autocorrection is enabled, observe `rx_text`, type a misspelled word and move focus away from the text view. The text will be automatically corrected, but the last change will never be observed via `rx_text`, because `textViewDidChange` doesn't fire when autocorrect happens.

**Comment by kzaher** [comment]
Hi @timojaask ,

I've confirmed the problem. This is the only way I know how to solve this, but I don't like it.

https://github.com/ReactiveX/RxSwift/commit/e14ca2e94d4e995c552c2d7c417f52ad9c3b75d7

Any ideas how to solve this more elegantly?

**Comment by sergdort** [comment]
Hi, guys
@kzaher  how about ```rx_observeWeakly``` of ```text``` keypath

**Comment by kzaher** [comment]
Hi @sergdort ,

that's an interesting idea :) I've just tried it, and unfortunately it doesn't seem to work either :/

Also `NSNotificationCenter.defaultCenter().rx_notification(UITextViewTextDidChangeNotification, object:self)` doesn't fire in that case.

Is there some obvious API I'm missing?

**Comment by sergdort** [comment]
Just looked at how ReactiveCocoa did this, looks like they did the same and probable they also have bug =)

**Comment by kzaher** [comment]
Haha, yeah, I've also checked other reactive/binding frameworks :)

This hack is the best thing I could conjure so far. ¯\\\_(ツ)\_/¯ 
This does look like a bug in `UITextView`, but this is a pretty ugly one and would like to find some workaround.

**Comment by sergdort** [comment]
How about observe ``textViewDidEndEditing`` instead of ``func textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool``

Looks like this bug appears only when you moving focus away from the text view

**Comment by kzaher** [comment]
Yeah, that also appears to be working ...

I'm wondering is there any other edge case like this one what `textViewDidEndEditing:` can't catch ...

Maybe we can use `textViewDidEndEditing:` and I can just implement `@objc public func textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool { return true }` so that if we need this uglier hack in future, we don't touch public interface ...

**Comment by sergdort** [comment]
Looks like this bug could also appears on `UITextField` rx_text

**Comment by sergdort** [comment]
There is also `NSTextStorageDelegate` in `textStorage` of `UITextView`
and probably method:

` - (void)textStorage:(NSTextStorage *)textStorage didProcessEditing(NSTextStorageEditActions)editedMask range:(NSRange)editedRange  changeInLength:(NSInteger)delta `

could work too

**Comment by kzaher** [comment]
I have noticed that same behavior on UITextField also. I've also been able to repro this without ending editing :(

I think it's worth a shot to try 
```
- (void)textStorage:(NSTextStorage *)textStorage didProcessEditing(NSTextStorageEditActions)editedMask range:(NSRange)editedRange changeInLength:(NSInteger)delta
```
... for `NSTextView`.

I'm still unsure how to solve `NSTextField` without equivalent ugly hack :/

**Comment by sergdort** [comment]
Hi @kzaher
Have you tried to add proxy target for `UIControlEvents` `UIControlEvents.AllEditingEvents` ?

With this setup 
`
      self.textField.addTarget(self, action: "textFieldDidChange:", forControlEvents: .AllEditingEvents)`

I was able to get all changes of text

**Comment by sergdort** [comment]
So ended up with this:

```swift
extension UITextField {
    
    /**
    Reactive wrapper for `text` property.
    */
    public var rx_text: Observable<String> {
        return rx_controlEvent(.AllEditingEvents)
            .map({[weak self] _ in self?.text ?? ""})
    }
    
}

```

**Comment by sergdort** [comment]
And it does not work =)

**Comment by sergdort** [comment]
Hi @kzaher looks like NSTextStorageDelegate works great, please take a look, may be I did something wrong :)

**Comment by kzaher** [comment]
This is done :)
