### ISSUE TITLE
Change CLLocationManager extensions to be not forced unwrapped optionals

### ISSUE THREAD

**Issue by psophis** [ReactiveX/RxSwift#334]
In CLLocationManager extensions most Observables have return types that are force unwrapped optional. Does this need to be the case?

**Comment by kzaher** [comment]
I believe there was a time when because of objc/Swift interoperability we had those implicitly unwrapped optionals in `CLLocationManagerDelegate`.

I think we can improve this now.

**Comment by kzaher** [comment]
Changes for removing implicitly unwrapped optionals have been pushed to `develop` branch, so you can take a peek there.

c337e642dcadfeb9d85bb049138dae8ebe26cf1b

**Comment by psophis** [comment]
That looks great!
