### ISSUE TITLE
Add reactivex.io documentation to doc strings

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#342]
As previously discussed in #335.

I would like to see links to [reactive.io](https://reactivex.io)'s documentation in the doc strings for methods.

Example:

```swift
/**
Projects each element of an observable sequence into a new form.

- seealso: [map operator on reactivex.io](http://reactivex.io/documentation/operators/map.html)

- parameter selector: A transform function to apply to each source
- returns: An observable sequence whose elements are the result of invoking the transform function on each element of source.

*/
@warn_unused_result(message="http://git.io/rxs.uo")
public func map<R>(selector: E throws -> R) -> Observable<R> {
    return self.asObservable().composeMap(selector)
}
```

**Comment by kzaher** [comment]
Yeah, I think that's a great suggestion. We can do that :)

**Comment by psophis** [comment]
I there a preferred way to link to these?

I think the `- seealso:` is the correct field but what should the link text be? Is the example above sufficient?

**Comment by kzaher** [comment]
Thnx for suggestion. Added those links in develop branch :)

Should be better now.
