### ISSUE TITLE
No such module when compiling release version

### ISSUE THREAD

**Issue by tirrorex** [ReactiveX/RxSwift#345]
Hello, when i compile in command line to get a release with "codebuild -configuration Release"
i get a .swift:10:8: error: no such module 'RxSwift' 
I use cocopoads to manage frameworks.
Could someone point me to the right direction please?

**Comment by kzaher** [comment]
Hi @tirrorex ,

I'm suspecting that probably xcodebuild selects a scheme from project file and not from xcworkspace.

I would suggest using explicit scheme, something like:

```
xcodebuild -workspace [workspace] -scheme [scheme] -configuration [configuration] ...
```

If that is not the issue, I'm not sure I understand what is happening here.
What command do you use to build debug version?

**Comment by tirrorex** [comment]
It seems indeed to be the problem, command used was "xcodebuild -configuration Release"
Could build using xcode directly though

**Comment by kzaher** [comment]
You mean why the xcode is choosing wrong workspace and scheme?

**Comment by kzaher** [comment]
Not sure what to do with this one. Closing this for now.
