### ISSUE TITLE
addDisposableTo to accept protocol type

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#352]
Do you think it could be possible to create protocol

```swift
protocol SomeName {
  public func addDisposable(disposable: Disposable);
}
```

In this case it will be possible to use ```addDisposableTo``` operator with for example ```CompositeDisposable```

Or it will break some logic ?

**Comment by kzaher** [comment]
Hi @sergdort ,

please take a look at my answer on https://github.com/ReactiveX/RxSwift/issues/353

**Comment by sergdort** [comment]
Thanks @kzaher
