### ISSUE TITLE
Getting Started states `gg` function that doesn't exist

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#355]
This section 
https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#creating-your-own-observable-aka-observable-sequence

Has the sentence 

`"So what is the gg function?" `
But there is no such method demo'd / implemented. Also, it says it is a replacement for `RxBox` which is never explained.

Could this be rooted in some old version of RxSwift ?

**Comment by kzaher** [comment]
Hi @freak4pc ,

Unfortunately that is a typo :( We've corrected it in `develop` branch.
https://github.com/ReactiveX/RxSwift/blob/develop/Documentation/GettingStarted.md

¯\_(ツ)_/¯

**Comment by freak4pc** [comment]
Thanks ! :)
