### ISSUE TITLE
ControlTarget is internal class

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#356]
I have a problem where I need to show popover after tapping the button 
but `rx_tap` is `ControlEvent<Void>`

So I wanted to write my own `tap` which would sent `UIButton`  but `ControlTarget` is internal class

Is there any other approach? 
To be more clear I have no access to the button because it is in table view's cell

**Comment by kzaher** [comment]
Hi @sergdort ,

I'm little confused here. 

```
let button: UIButton = ...
button.rx_tap
      .map { [weak button] in button }
```
?

**Comment by sergdort** [comment]
Lol yeah! Sorry for this stupid question (:
