### ISSUE TITLE
rx_tap should pass through UIControl

### ISSUE THREAD

**Issue by singno** [ReactiveX/RxSwift#357]
```
let btn = UIButton()
        
btn.rx_tap.subscribeNext { (_) -> Void in
    print(btn)
}
```

But it will be better to pass through UIControl as parameter.

```
let btn = UIButton()
        
btn.rx_tap.subscribeNext { (_, btn) -> Void in
    print(btn)
}
```

**Comment by kzaher** [comment]
Hi @singno ,

I did initially have some doubts how to wrap that interface.

The reason why we've picked `Observable<()>` was because button is usually used as a trigger for some operation, and you want to abstract away trigger mechanism.

In the end, those two approaches should be equivalent

```
let button: UIButton = ...
button.rx_tap
      .map { [weak button] in button }
```

**Comment by kzaher** [comment]
This looks stale.

¯\\\_(ツ)\_/¯
