### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#36]
Hi guys,

I'm currently working on RxCocoa refactorings, and currently don't have time to play with Swift 2.0 :(
The earliest that will be on my plate is in a week or two, don't think I'll manage to do it before that time.

Since there is some community interest in using RxSwift with Swift 2.0, I've created a [branch](https://github.com/kzaher/RxSwift/tree/feature/swift2.0) where you can share your changes if somebody has managed to make it to work with new version of Swift, so others don't have to redo that work.

That's best I can do so far.

Kruno

**Comment by seivan** [comment]
I should be done tomorrow afternoon.

**Comment by kzaher** [comment]
Hi @seivan I'm continuing work on you RxSwift 2.0 branch.

Just wanted to let everyone know in case somebody is working on porting.

**Comment by kzaher** [comment]
I've made a PR so people can see changes.
https://github.com/kzaher/RxSwift/pull/50

**Comment by garethknowles** [comment]
Hi @kzaher thanks for the work on getting RxSwift ready for Swift 2, really excited to start using it in my new project.

I have managed to get RxSwift and RxCocoa working with the new Xcode 7.0 beta 3 and Swift 2 with a small fix on my fork:  https://github.com/kzaher/RxSwift/pull/54  All Unit Tests seem to be passing.

Thanks,
Gareth
