### ISSUE TITLE
How about to add rx_textColor for UITextField and UILabel

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#361]
Now have a project where I need to change color of the text based on whether there any changes
Just wondering if community need this ?
I've did this like this :

```swift
extension UILabel {

   public var rx_textColor: AnyObserver<UIColor> {
      return AnyObserver { [weak self] event in
         MainScheduler.ensureExecutingOnScheduler()
         
         switch event {
         case .Next(let value):
            self?.textColor = value
         default:
            break
         }
      }
   }
}
```

**Comment by kzaher** [comment]
Hi @sergdort ,

I think that we would ideally like to keep our API surface as small as possible, otherwise we'll have serious hoarding issues :)

There are ofc multiple reasons why we would want to keep API surface as small, and I think we all understand them :)

I would like to actually like to motivate people to do extensions in this way
```
extension UINavigationController {
    var rx_serviceState: AnyObserver<ServiceState?> { // <- this is some custom enum value 
        return AnyObserver { [weak self] event in
            switch event {
            case .Next(let maybeServiceState):
                // if nil is being bound, then don't change color, it's not perfect, but :)
                if let serviceState = maybeServiceState {
                    let isOffline = serviceState ?? .Online == .Offline

                    self?.navigationBar.backgroundColor = isOffline
                        ? Colors.OfflineColor
                        : Colors.OnlineColor
                }
            case .Error(let error):
                bindingErrorToInterface(error)
            case .Completed:
                break
            }
        }
    }
}
```

I'm thinking more in the direction how can we support people using RxCocoa with this pattern.

I'm thinking of adding `BindingObserver` maybe (still thinking about it), that could be nice and expressive, and help people write this kind of code:

```
extension UINavigationController {
    var rx_serviceState: AnyObserver<ServiceState?> { // <- this is some custom enum value 
        return BindingObserver { maybeServiceState, self in
                // if nil is being bound, then don't change color, it's not perfect, but :)
                if let serviceState = maybeServiceState {
                    let isOffline = serviceState ?? .Online == .Offline

                    self.navigationBar.backgroundColor = isOffline
                        ? Colors.OfflineColor
                        : Colors.OnlineColor
                }
        }
    }
}
```

In that way we've reduced some noise in VM/VC and moved code to view where it belongs.  `Observable<ServiceState?>` is also more natural to test.

This is kind of direction where I think we should be going :)

The reason why we've supported some primitive properties/observers on controls because it kind of makes sense for those data types to be produced in business layer code.

Hoping we didn't make some accidental mistake, but that's kind of the general thought process :)

It seems to be that usually `rx_textColor` would be associated with some kind of validation enum, and it would probaby make more sense to use `BindingObserver` or something :)

**Comment by sergdort** [comment]
Hi @kzaher
I see your point :) make sense;)
By the way did not see that BindingObserver type

**Comment by kzaher** [comment]
I'm planning to add that :)

Have lots of ideas how to improve things, but first I give it some time. If after enough time I still think it's a good idea, then I add it :)

¯\\\_(ツ)\_/¯

**Comment by sergdort** [comment]
Sorry for reopening issue, may be its will be related to another one.

What do you think about spreading files in the RxSwift POD just like it done in RxSwift project?
May be it will help others too. 

Because personally I use RxSwift pod to look up what implementation does (or why it does not do what I want =) ) while developing my apps

**Comment by kzaher** [comment]
I'm not entirely sure what project changes are you suggesting and how to accomplish that :)

**Comment by sergdort** [comment]
I guess its more related to RxSwift.podspec file, unfortunately, I'm not familiar with podspec customization.
In my opinion it would be better to look like this 
<img width="372" alt="screen shot 2015-12-30 at 3 32 57 pm" src="https://cloud.githubusercontent.com/assets/4622322/12051326/a6d7d0d8-af0a-11e5-9500-972f869af795.png">

Then how it look in POD project when you use it with cocoapods

![screen shot 2015-12-30 at 3 34 34 pm](https://cloud.githubusercontent.com/assets/4622322/12051335/e1144e16-af0a-11e5-91b7-e3415dda7927.png)

**Comment by sergdort** [comment]
I guess some thing similar as [AFNetworking.podspec](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec) does

**Comment by esetnik** [comment]
Actually to support the format you're proposing you don't need to use submodules as is done with `AFNetworking.podspec`. You can just break your source files into folders on the filesystem and the paths will be preserved when installing with Cocoapods. The subspecs are for including optional functionality which is not the use case here.

**Comment by kzaher** [comment]
I've asked @orta about this, and there is a simple way how to do something that could be considered as solving this. 

Podfile
```
use_frameworks!
pod 'RxSwift', :branch => '${BRANCH}', :path => '~/Projects/RxCI'
pod 'RxCocoa', :branch => '${BRANCH}', :path => '~/Projects/RxCI'
pod 'RxBlocking', :branch => '${BRANCH}', :path => '~/Projects/RxCI'
```

**He does say that this is not preferred way to work with CocoaPods**, but I really love it :)
Files will be linked with git repo, so you can make changes directly to RxSwift and make a PR in case you see any issue, and test the changes in your project immediately while doing that :)

IMHO, this is perfect for contributor workflow. 

¯\\\_(ツ)\_/¯ 

<img width="446" alt="screen shot 2015-12-31 at 12 22 45" src="https://cloud.githubusercontent.com/assets/1641148/12064053/927f8e6e-afb9-11e5-9857-1959ac370716.png">

**Comment by sergdort** [comment]
@esetnik  I looked on RxSwift project and it looks like it has been spread into folders. Or I missing something?

**Comment by kzaher** [comment]
@sergdort I think that when you use :path =>, you'll use project in development mode and you'll have folders.

Otherwise I believe it will have flat structure if imported normally using name + ~>.

**Comment by sergdort** [comment]
I see thanks :)
