### ISSUE TITLE
Simple Question: How to print the incoming stream of UITextField?

### ISSUE THREAD

**Issue by kbala** [ReactiveX/RxSwift#363]
let username = Variable("")
        
        usernameTF.rx_text.bindTo(username).addDisposableTo(disposeBag)
        
        _ = username.map{ username in
            
            print(username)
            
        }
        
I am a beginner, learning Rx :) 

Please help,

**Comment by kbala** [comment]
_ = usernameTF.rx_text.subscribe { user in
            print(user)
        }

Seems this works.

**Comment by kbala** [comment]
_ = usernameTF.rx_text.subscribe(onNext: doit)

func doit(username:String)
    {
        print(username)
    }

this works!

anything short?

**Comment by lonkly** [comment]
_ = unTF.rx_text.subscribe(onNext: {u in print(u)}) ths s shrtr thn urs  :-1:

**Comment by kbala** [comment]
Yes :+1: 

Thanks
