### ISSUE TITLE
`timeout` does not emit Timeout error

### ISSUE THREAD

**Issue by longlongjump** [ReactiveX/RxSwift#367]
Hello, `timeout` method does not emit `RxError.Timeout`. Actually nothing happens at all. I don't found any code that possibly can emit RxError.Timeout, but docs says that

> Applies a timeout policy for each element in the observable sequence. If the next element isn't received within the specified timeout duration starting from its predecessor, a TimeoutError is propagated to the observer.

Here is sample code:
```
let scheduler = MainScheduler.sharedInstance
let sampleTimer = timer(10.0, 10.0, scheduler)
 _ = sampleTimer.take(1).timeout(5,  scheduler).subscribe(onNext: { val in
    debugPrint(val)
    }, onError: { e in
        debugPrint(e)
    }, onCompleted: {
        debugPrint("completed")
    }, onDisposed: {
        debugPrint("disposed")
    });
```

**Comment by kzaher** [comment]
Hi @longlongjump ,

Thnx for reporting this.

The bug is actually here:

```
public func timeout(dueTime: RxTimeInterval, scheduler: SchedulerType)
        -> Observable<E> {
            return Timeout(source: self.asObservable(), dueTime: dueTime, other: nil, scheduler: scheduler)
    }
```

it should be

```
public func timeout(dueTime: RxTimeInterval, scheduler: SchedulerType)
        -> Observable<E> {
            return Timeout(source: self.asObservable(), dueTime: dueTime, other: failWith(RxError.Timeout), scheduler: scheduler)
    }
```

That's why our unit tests didn't catch it. They've only tested overload with explicit sequence

```
 public func timeout<O: ObservableConvertibleType where E == O.E>(dueTime: RxTimeInterval, other: O, _ scheduler: SchedulerType)
        -> Observable<E>
```

This will be fixed soon :(

**Comment by kzaher** [comment]
This should be released right now. Closing this one.

Please let me know if we need to reopen this.
