### ISSUE TITLE
Make RxTableViewSectionedAnimatedDataSource part of RxSwift 

### ISSUE THREAD

**Issue by coryoso** [ReactiveX/RxSwift#368]
RxTableViewSectionedAnimatedDataSource is part of an RxSwift example project, but would be very helpful as part of the framework itself

**Comment by kzaher** [comment]
Hi @coryoso ,

we will package those data sources in a repository somewhere under here [https://github.com/RxSwiftCommunity](https://github.com/RxSwiftCommunity)

We'll just need some time to do it :)

**Comment by kzaher** [comment]
This has been packed here.

https://github.com/RxSwiftCommunity/RxDataSources

This should work now.

Podfile
```
pod 'RxDataSources', '~> 0'
```

I'll close this for now, please let me know if there are some issues and we need to reopen this.
