### ISSUE TITLE
bindNext works fine , but bindTo not.

### ISSUE THREAD

**Issue by kaich** [ReactiveX/RxSwift#369]
I use RxSwift do something as blow :

        rx_observeWeakly([AnyObject].self, "categoryArray")
            .map({ (category)  in
                let convertArray :[String]? = category?.map({ (emDic) -> String in
                    if let emDic = emDic as? [String :AnyObject] {
                        if let name = emDic["speciesName"] as? String {
                           return name
                        }
                    }
                    return ""
                })
                return convertArray
            }).bindNext { result in
               categoryDescriptor.selectorOptions = result
            }
            .addDisposableTo(disposeBag)

I get the `result` contains 10 items. But if I change bindNext to bindTo  , it doesn't work fine 

        rx_observeWeakly([AnyObject].self, "categoryArray")
            .map({ (category)  in
                let convertArray :[String]? = category?.map({ (emDic) -> String in
                    if let emDic = emDic as? [String :AnyObject] {
                        if let name = emDic["speciesName"] as? String {
                           return name
                        }
                    }
                    return ""
                })
                return convertArray
            })
          .bindTo(Variable(colorDescriptor.selectorOptions))
          .addDisposableTo(disposeBag)                          

when I use the bottom code ,`colorDescriptor.selectorOptions ` is 0 item. I make sure `convertArray` contains 10 items. What's the reason about it. Hope your answer!

**Comment by kzaher** [comment]
Hi @kaich ,

I believe this code will bind values to temporary variable allocated on stack that has initial value `colorDescriptor.selectorOptions`, and not bind to `colorDescriptor.selectorOptions` itself.

```
.bindTo(Variable(colorDescriptor.selectorOptions))
```

**Comment by kaich** [comment]
thanks @kzaher. I review the sourcecode by your answer. In swift Array and Dictionary is struct. It's value passed.
