### ISSUE TITLE
How to think over streams (observables), LOL

### ISSUE THREAD

**Issue by kbala** [ReactiveX/RxSwift#374]
@kzaher I Love RxSwift. I've gone thru the example projects and I could understand well, and also I have completed a login page for my project, its awesome!. I can only able to do this based on your GitHubSignup Example. But the next module in my project is, capturing photos and send server to save and have to list out the captured photos in a TableViewController. To achieve this what the basic ground work I have to do before start, I know i have to consider everything as stream, but not sure how/where to start that. Please guide

**Comment by kzaher** [comment]
Hi @kbala ,

I would first suggest trying to think of them as sequences and not streams :) Streams have wrong associations attached to them, like being stateful, computation sharing, etc... which doesn't describe Rx very well IMHO ¯\\\_(ツ)\_/¯  Rx can behave like streams in some cases for sure, but that's not default behavior.

You could investigate some of the links from here http://reactivex.io/tutorials.html

I've gone through this course https://courses.edx.org/courses/DelftX/FP101x/3T2014/info and it's so awesome. Not sure what's happening with it now :/
Especially exercises and labs (this is Haskell, but it should purge your mind from imperative way of thinking)

Maybe this one https://www.coursera.org/course/reactive, still didn't have a chance to go through it though.

Hard to tell really. The problem isn't learning library but more of a mindshifting ¯\\\_(ツ)\_/¯ 

Different things work for different people, what worked for me might work horribly for you :)

**Comment by kbala** [comment]
Oh wow! thanks for your reply, Let me go through now :)

**Comment by kbala** [comment]
Hi @kzaher I could understand the stuff more than before, thanks.

Could you please give me an example for best way to capture photos using the UIImagePickerController using with RxSwift? Kick me to start, LOL :)
