### ISSUE TITLE
"Playgrounds" link is broken in Examples.md

### ISSUE THREAD

**Issue by finneycanhelp** [ReactiveX/RxSwift#375]
Item number 5 "Playgrounds" link is broken at
https://github.com/ReactiveX/RxSwift/blob/develop/Documentation/Examples.md

Not sure why "more examples" works but "Playgrounds" does not when the raw source in Examples.md looks quite similar between the two. 

Perhaps send the user to https://github.com/ReactiveX/RxSwift#playgrounds for "Playgrounds"? It's more descriptive. Your choice. :)

**Comment by kzaher** [comment]
Should be fixed now :) Good catch.

**Comment by finneycanhelp** [comment]
confirmed. My pleasure. :)
