### ISSUE TITLE
RxSwift.resourceCount not accessable

### ISSUE THREAD

**Issue by kbala** [ReactiveX/RxSwift#378]
# if TRACE_RESOURCES

```
private let startResourceCount = RxSwift.resourceCount
```
# endif

Says, 
Module 'RxSwift' has no member named 'resourceCount'

**Comment by sergdort** [comment]
Please take a look on [#301](https://github.com/ReactiveX/RxSwift/issues/301)

**Comment by kbala** [comment]
Hi @sergdort I set the OtherSwift Compiler Flags same as you did, still I have same issue, Please see the below SS

![2016-01-03_1318](https://cloud.githubusercontent.com/assets/3509745/12077828/01d782fc-b21d-11e5-9496-f78b2e7207bc.png)

**Comment by sergdort** [comment]
Hi @kbala  did you make a post POD install hook ?


```ruby
use_frameworks!

pod 'RxSwift'

post_install do |installer|
   installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
         target.build_configurations.each do |config|
            if config.name == 'Debug'
               config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
            end
         end
      end
   end
end
```

**Comment by singno** [comment]
I use Carthage build version:  github "ReactiveX/RxSwift" ~> 2.0 . And I cann't access   RxSwift. resourceCount too. 

![image](https://cloud.githubusercontent.com/assets/5654690/12086982/d62b4d58-b309-11e5-9935-c07331288b2e.png)

![image](https://cloud.githubusercontent.com/assets/5654690/12086994/f0981dba-b309-11e5-87f9-1d6a2062621c.png)

**Comment by sergdort** [comment]
Here is screen shot from RxSwiftExample, looks like it should be -D TRACE_RESOURCES

<img width="1042" alt="screen shot 2016-01-04 at 11 40 43 am" src="https://cloud.githubusercontent.com/assets/4622322/12087030/1dd4aeba-b2d8-11e5-8a97-44c4d040ab52.png">

**Comment by singno** [comment]
It seems not working for me.

**Comment by sergdort** [comment]
And it should be off course in the framework build settings. I'm not sure is it possible to do some configurations with Carthage

<img width="1010" alt="screen shot 2016-01-04 at 12 38 12 pm" src="https://cloud.githubusercontent.com/assets/4622322/12087988/29e17c4e-b2e0-11e5-8e76-a14980822acc.png">

**Comment by kzaher** [comment]
You can't access `resourceCount` with Carthage because, as far as I'm aware of, Carthage only uses release version of the binaries, and you can't specify addition compilation flags.

Once any version of RxSwift libraries is compiled without `TRACE_RESOURCES` Swift flag, the code that traces resources is simply not compiled inside the library.

If Carthage supported specifying additional Swift flags during compilation, that would be possible, but I'm not sure it currently supports that or is there some other way to solve that using Carthage.

**Comment by singno** [comment]
@kzaher Yes, Carthage seems can not change build setting.
@sergdort I can not set the build setting of RxSwift framework.

**Comment by ikesyo** [comment]
You can use `carthage build --configuration Debug`.

**Comment by kbala** [comment]
yes, I run >carthage build --configuration Debug

I can access the resourceCount now, and works

**Comment by kzaher** [comment]
Thnx @ikesyo  :)

**Comment by kzaher** [comment]
And thnx @sergdort , helping with issues helps a lot :+1:

**Comment by sunflash** [comment]
`carthage build --platform iOS --configuration Release-Tests `
work too

**Comment by scotteg** [comment]
You can also quickly enable `RxSwift.resourceCount` by adding the `TRACE_RESOURCES` flag to the **RxSwift** target, e.g., in the Pods project, **Build settings > Other Swift flags > Debug**:

![screenshot 2016-06-05 17 11 08](https://cloud.githubusercontent.com/assets/1337867/15808602/c14a4d30-2b40-11e6-9366-746e141dd561.png)

You'll just need to remember to re-enable it every time you do a `pod update`--which, maybe, isn't such a bad thing 😉

**Comment by RafaelPlantard** [comment]
Just remembering that right now, the resource count is getted from:
`RxSwift.Resources.total`.

**Comment by sergdort** [comment]
Hey guys you can also add post install to pod file 

```ruby
post_install do |installer|
   installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
         target.build_configurations.each do |config|
            if config.name == 'Debug'
               config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
            end
         end
      end
   end
end
```

**Comment by kzaher** [comment]
Let's add this to next release :)

**Comment by kzaher** [comment]
Oh,

@sergdort I've thought we can add this to podspec also and not podfile. My bad.

**Comment by nahung89** [comment]
follow to @kzaher in #1277, i can enable debugging with Carthage by using script:
```
carthage update --no-use-binaries --configuration Debug RxSwift
```

**Comment by majid701** [comment]
I'm having this issue as well even though I am not using Carthage. I added RxSwift to the project with Cocoapods and tried to access `RxSwift.Resources.totalCount` but after adding the post install script to the podfile I get a `dyld: Symbol not found` exception on the line `RxSwift.Resources.totalCount`
What is the correct way to access the total count?

**Comment by haider-kazal** [comment]
Is there any way to access `RxSwift.Resources.totalCount` if RxSwift is added via Swift Package Manager?

**Comment by uuttff8** [comment]
> Is there any way to access `RxSwift.Resources.totalCount` if RxSwift is added via Swift Package Manager?

@kzaher

**Comment by Pyxisq** [comment]
@kzaher Sorry) Any updates about Swift package?

**Comment by realityworks** [comment]
Still no clear way to debug if using SwiftPackageManager.

**Comment by freak4pc** [comment]
> Still no clear way to debug if using SwiftPackageManager.

There is absolutely no need to go through every issue related to this and comment there.
