### ISSUE TITLE
How to access RxSwift.resourceCount by Carthage build framework

### ISSUE THREAD

**Issue by singno** [ReactiveX/RxSwift#381]
![image](https://cloud.githubusercontent.com/assets/5654690/12086529/134d3420-b306-11e5-96fd-97e3a708f1a8.png)

**Comment by sergdort** [comment]
Hi @singno  looks like it duplicates #378

**Comment by sergdort** [comment]
But I'm not sure ;)

**Comment by singno** [comment]
Yes, it looks like #378. Maybe I should reply  #378 directly.
