### ISSUE TITLE
Use of unresolved identifier 'castOrFatalError'

### ISSUE THREAD

**Issue by sger** [ReactiveX/RxSwift#382]
Hello,

I'm trying to create a DelegateProxy but can't access castOrFatalError or castOptionalOrFatalError

Xcode 7.2
github "ReactiveX/RxSwift" "2.0.0-beta.4"

Any ideas?

**Comment by sergdort** [comment]
Hi @sger I guess you can just force cast it 

```swift
object as! MyObject
```

**Comment by sger** [comment]
@sergdort thats true but any ideas why can't access the helper method?

**Comment by sergdort** [comment]
@sger because it's `internal` not `public` ;)

**Comment by sger** [comment]
@sergdort ok just saw the implementation on the RxExample thanks man
