### ISSUE TITLE
ResourceCount increasing in a PageViewController

### ISSUE THREAD

**Issue by kbala** [ReactiveX/RxSwift#390]
Guys, In my project i need to list out the items based on date, So I did a pageviewcontroller and put the dataviewcontroller for each date. For testing I just put the GitHubRespositoriesSearch in the dataviewcontroller. it works as expected, but when I swipe next and next the resource count got increased and reached this line

`assert(resourceCount <= numberOfResourcesThatShouldRemain, "Resources weren't cleaned properly")`

@kzaher given some direction in the ViewController class of example project, but i am still not sure how to dispose resources when in case of pageviewcontroller, please guide me

**Comment by sergdort** [comment]
Hi @kbala looks like this is kind of the same as I had #302, @kzaher gave a good answer there

**Comment by kbala** [comment]
So its not increasing resource count? whats the trick to fix this?

**Comment by sergdort** [comment]
In my app its increasing when I push some screens and then decreasing back to some value.
Sounds like you have some root view controller which holds some resources. As far as I understand you should not add resources to the `disposeBag` which will never be deallocated (on dealloc it despose all disposables which are in the bag).

**Comment by kbala** [comment]
I see, let me try

**Comment by kbala** [comment]
anyone tested the resourceCount with UIPageViewController? For me the count get increasing, and i am not sure whether it should be cleared with a suitable workaround or maybe nothing harm?

**Comment by sergdort** [comment]
Hi, @kbala In my app I use page controller, and it works fine, as I said, resource count gets increasing, and then when one of page deallocates, it decrease to some value, because there are lots of bindings on the page, I guess you should look whether your views get deallocated, I my app I had some retain cycle, which cause resource leak in my case. I'm guessing you have the same problem =)

**Comment by kbala** [comment]
its get deallocated as soon as it reaches the max resourceCount. Can I send my code to you?

**Comment by sergdort** [comment]
If it's Ok for you :)

**Comment by kbala** [comment]
No I think. do we have example for pageviewcontroller with RxSwift?

**Comment by kzaher** [comment]
I think @sergdort tried to help here. We don't have page view controller example anywhere now.

This looks stale. Closing this. Assuming this wasn't an issue with library itself.
