### ISSUE TITLE
`.observeOn(MainScheduler.sharedInstance)` events delivered out of order

### ISSUE THREAD

**Issue by dpassage** [ReactiveX/RxSwift#393]
This may not be a bug, but I'd welcome suggestions on how to deal with it. (I'm still on 2.0.0 beta 3; working on updating to the release version in parallel.)

I have a Variable in class A. There's a method in class B which observes it on the main thread:

```
        updateService.currentVersion
            .observeOn(MainScheduler.sharedInstance)
            .subscribe { event in
...
```

In the other object, I first set the value to `1` on the background thread, and then to `2` on the main thread.

At the subscriber, however, I'm seeing them out of order: first `2` and then `1`.

I'm guessing that's because `observeOn` turns into a no-op if the current thread is the same as the scheduler's thread, and thus the `2` is delivered immediately while the `1` goes to GCD jail for a beat.

Can anyone recommend a good way to deal with this? Should I do all updates to the `Variable` on the main thread?

Thanks!

**Comment by kzaher** [comment]
@dpassage I believe this might be a bug in beta.3

Could you please try to do the same in released 2.0.0 version?

**Comment by dpassage** [comment]
Will do, thx!

**Comment by dpassage** [comment]
Just upgraded to 2.0.0, exact same issue.

**Comment by dpassage** [comment]
I also wrapped `dispatch_async(dispatch_get_main_queue()...` around the setting the value to `1`, same issue as well.

**Comment by dpassage** [comment]
Well. I ended up wrapping more of the first class in `dispatch_async` and got the behavior I wanted. I still suspect my base problem is "not enough Rx".

**Comment by kzaher** [comment]
@dpassage could you paste something I can execute and see the desired anomaly?

If this is some bug in the library, we would definitely like to fix it.

**Comment by dpassage** [comment]
Yeah, let me see if I can make a test case for you, may take me a couple days to get to it.

**Comment by DouglasHeriot** [comment]
Can you explain more about how you set the value to `1` _"first"_?
Are you sure it actually happens first? Try adding log messages.

I’m guessing your code is like this:
```
dispatch_async(backgroundQueue) {
    dispatch_async(dispatch_get_main_queue()) {
        NSLog("Setting to 1")
        variable.value = 1
    }
}

NSLog("Setting to 2")
variable.value = 2
```

I bet you’ll find that it sets it to 2 first, even without anything RxSwift related.

**Comment by kzaher** [comment]
This looks stale. Closing for now.
