### ISSUE TITLE
Feature request: repeatWhen operator

### ISSUE THREAD

**Issue by smaspe** [ReactiveX/RxSwift#396]
Other implementations of Rx have the `repeatWhen` operator, which allows the repetition to be controlled by another `Observable`. Very convenient.

It is quite different from `repeat` in that a/ you can control the flow of repetitions and b/ you can interrupt it.

The implementation would probably take from `repeat` but not entirely, as it requires to delay the `scheduleRecursive` call until a new event was received from the control `Observable`, and also to resubscribe to the original source instead of re-emitting the same event.

**Comment by thanegill** [comment]
Does [`retryWhen`](https://github.com/ReactiveX/RxSwift/blob/83bac6db0cd4f7dd3e706afc6747bd5797ea16ff/RxSwift/Observables/Observable%2BSingle.swift#L172-L184) not do the same thing?

**Comment by kzaher** [comment]
@smaspe could you maybe explain more about the context for which you need `repeatWhen`. I would first like to understand how common your need is :)

**Comment by smaspe** [comment]
@thanegill no, because retryWhen requires the source to error. (but similar)

@kzaher sure! It is used in a polling system. The control Observable is able to trigger a single repeat from the source Observable.

The control Observable can then be bound to either a timed interval, a user action, ...

**Comment by smaspe** [comment]
@thanegill Actually transforming the Completed event into a specific Error event on the source Observable allows to use retryWhen. A bit of a hack, though.

**Comment by kzaher** [comment]
Hi @smaspe,

I think we would need to refactor `retryWhen` to accommodate that new functionality. I'll try to find time to investigate RxJava to see how they've organized their code, find proper unit tests and see what can we learn from them.

That will probably take some time since I'll need to find time for investigations and those refactorings, but I'll see what we can do here in the long run.

**Comment by smaspe** [comment]
@kzaher thanks for taking that into consideration! much appreciated!

**Comment by AquaGeek** [comment]
+1 to this feature request — I'm doing something very similar (polling system).

**Comment by kzaher** [comment]
I think that right now you can just do something like:

```
struct InfiniteSequence<E> : SequenceType {
    typealias Element = E
    typealias Generator = AnyGenerator<E>
    
    private let _repeatedValue: E
    
    init(repeatedValue: E) {
        _repeatedValue = repeatedValue
    }
    
    func generate() -> Generator {
        let repeatedValue = _repeatedValue
        return anyGenerator {
            return repeatedValue
        }
    }
}
```

and then 

```
InfiniteSequence(sourceSequence.takeWhile { x in x is correct }).concat()
```

**Comment by DanielAsher** [comment]
I believe this is worthy of inclusion in the core library.

**Comment by RamblinWreck77** [comment]
I would like this as well! Would be super useful

**Comment by JeromeCHA** [comment]
Me too! It would be awesome, but this is from 2016 so I don't think it will be done soon... :/

**Comment by freak4pc** [comment]
I'm closing this for now due to inactivity - If you have any more comments on this subject, feel free to comment or ping me directly and I'll re-open it :) Thanks !
