### ISSUE TITLE
Noisy debug logging in _RXObjCRuntime.m

### ISSUE THREAD

**Issue by tomburns** [ReactiveX/RxSwift#397]
Opening an issue at @kzaher's request to quiet the logging that occurs when optimized observers are registered.

https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Common/_RXObjCRuntime.m#L589

**Comment by kzaher** [comment]
Thnx :+1:

**Comment by kzaher** [comment]
This release solves this one.
