### ISSUE TITLE
Request: Add doOnDisposed operator

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#398]
As seen here: http://www.introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html#Finally

**Comment by DanielAsher** [comment]
I recently needed this operator. I was advised to make use of the new `using` operator, but `finally` seems like a much more elegant solution.

+1

**Comment by kzaher** [comment]
We currently have `using` operator. It looks like a boring solution, but I believe people really do need it more then `finally` :)

It looks to me that `finally` is one of those side effect operators, and could be maybe added to `do` operator.

http://reactivex.io/documentation/operators/do.html

I'm not sure that naming makes much sense in the context of Swift. 

In C# you have `try`,`catch`,`finally`.
I believe the same is valid for Java.

I think the closest thing in Swift would be `defer`, but that is a keyword, so not sure how would I add it as an operator.

It seems to me that simplest and most consistent way to implement finally would be to add `onDisposed` to `do` operator.

Disposed is executed in all cases finally is.

**Comment by DanielAsher** [comment]
@kzaher a `doOn(onDisposed:` would work nicely.

I feel a convenience function named `finally` conveys well its purpose.

**Comment by DanielAsher** [comment]
I would add that I believe a `finally` combinator is lighter-weight than the `using` factory function.

**Comment by thanegill** [comment]
An `doOn(Disposed: )` operator would work for me. And while we're at it an `doOn(Subscribed: )` would also be nice. 

Is there an example of `using` with the equivalent functionality of `doOn(Disposed: )` and `doOn(Subscribed: )`?

**Comment by thanegill** [comment]
Below is what I figured out for a `doOn(Disposed: )` operator, is this the right way to do this?

```swift
extension Observable {
    public func doOnDisposed(onDisposed: () -> ()) -> Observable<Element> {
        return Observable<Element>.using({
                return AnonymousDisposable(onDisposed)
        }, observableFactory: { _ -> Observable<Element> in
            return self
        })
    }
}
```

**Comment by kzaher** [comment]
@thanegill I believe the code you've written should work.

```
extension Observable {
    public func doOnMyExtensions(onSubscribed: () ->(), onDisposed: () -> ()) -> Observable<Element> {
        return Observable<Element>.using({
                onSubscribed()
                return AnonymousDisposable(onDisposed)
        }, observableFactory: { _ -> Observable<Element> in
            return self
        })
    }
}
```

I would suggest that you might want to just use `using` operator. You are maybe missing a hidden "resource" that is used during subscription lifetime.

**Comment by sergdort** [comment]
@kzaher Just wondering, is it lead to retain cycle, because of referencing `self` in `observableFactory ` ?

**Comment by kzaher** [comment]
Looks like we can close this one :)

**Comment by DanielAsher** [comment]
Would love to see a commit attached!
I'm so `lazy`. I'll do a search :)

**Comment by kzaher** [comment]
We didn't add a special operator for that because it seems to me that you can accomplish the required behavior and more with `using` operator ;)
