### ISSUE TITLE
distinctUntilChanged where the element that is compared is the last emitted element

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#399]
Is there an easy way the use `distinctUntilChanged` where the comparer compares current element to the last emitted element instead of the previous element?

My use case is for filtering location updates. I only need updates if the the traveled distance is greater than 50 meters. When using the current `distinctUntilChanged` operator if the rate of elements is greater than one per the 50 meters then all elements are filtered even if the location has changed more 50 meters.

**Comment by sergdort** [comment]
Hi, @thanegill, how about `filter` [operator](https://github.com/ReactiveX/RxSwift/blob/master/Rx.playground/Pages/Filtering_Observables.xcplaygroundpage/Contents.swift#L23)

**Comment by kzaher** [comment]
@thanegill I think you can use `scan` operator to remember last element you've emitted, and after then use that `distinctUntilChanged(comparer: (lhs: E, rhs: E) throws -> Bool)` to clean it up.

If distance is greater then 50m, emit latest, otherwise, emit original.

**Comment by thanegill** [comment]
This seems to work:

```swift

extension CLLocationCoordinate2D: Equatable { }

public func == (lhs: CLLocationCoordinate2D, rhs: CLLocationCoordinate2D) -> Bool {
    return lhs.latitude == rhs.latitude && lhs.longitude == rhs.longitude
}

extension ObservableType where E == CLLocation {
    func distinctUntilChangeGreaterThan(meters meters: CLLocationDistance) -> Observable<CLLocation> {
        return self.scan(CLLocation(), accumulator: { lastLocation, location in
            if lastLocation.distanceFromLocation(location) > meters {
                return location
            } else {
                return lastLocation
            }
        }).distinctUntilChanged { lhs, rhs in
            return lhs.coordinate == rhs.coordinate
        }
    }
}
```
Thank's @kzaher, @sergdort

**Comment by jondwillis** [comment]
This may be solvable in a coming Swift version:

https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md

The reason I arrived here, is that I have a lot of subscriptions to arrays  in global state (ReSwift), and as a result, I have a lot of `distinctUntilChanged { $0 == $1 }`. Aside from the runtime cost, there is a high compile time cost -- sometimes more than a second per each.
