### ISSUE TITLE
How to write canEditRowAtIndexPath for tableview with rx_dataSource?

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#404]
```Swift            
            ...
            .bindTo(tableView.rx_itemsWithDataSource(dataSource))
            .addDisposableTo(controlsDisposeBag)
```
I have a tableView with an rx_datasource

but How can I implement tableView:canEditRowAtIndexPath function with this tableView?

**Comment by sergdort** [comment]
Hi, @frogcjn  I guess (if you are using RxDataSources) you need just override your `RxTableView...DataSource` and implement method based on your logic.

**Comment by thomasschuster** [comment]
I can confirm that. I just extended the `RxTableView...DataSource` and implemented the methods of the `UITableViewDataSource` protocol there.

**Comment by kzaher** [comment]
Yeah, we'll probably turn those delegate methods into lambdas in data sources inside RxDataSources project.

**Comment by sergdort** [comment]
Hi @kzaher bit later I can also implement some examples, to show usage, if you want.

**Comment by kzaher** [comment]
@sergdort I think it might be useful to transform RxDataSources project example app to use navigation view controller and add customization example.

**Comment by kzaher** [comment]
Looks like we can close this one also.
