### ISSUE TITLE
Lacking flatMapIterable from RxJava

### ISSUE THREAD

**Issue by robertofrontado** [ReactiveX/RxSwift#406]
Hello guys, I want to know it there is an equivalent of that function?

Or if u know how to do this in RxSwft, the following code is in RxJava

```javascript
@Override public Observable<Boolean> builtObservable() {
    assert dealer != null || market != null;

    return repository.getPacksFish(GetPacksFishUseCase.Order.BY_FISH)
            .flatMapIterable(packs -> packs)
            .flatMap(pack -> {
                if (dealer != null) pack.setDealerAssigned(dealer);
                if (market != null) pack.setMarketAssigned(market);

                setCurrentSelectedPackFishUseCase.setPackFish(pack);
                return setCurrentSelectedPackFishUseCase.builtObservable()
                        .flatMap(success -> {
                            assert success;
                            return addOrUpdatePackFishToPacksUseCase.builtObservable();
                        });
            })
            .toList()
            .map(results -> true);
}
```
So I have an Observable<[Pack]> and I want to split it in many Observable<Pack> so I can apply a FlatMap to each of them, do something and return an Observable<Bool> (This comes from another method) and then joint them and work as a Observable<[Bool]>

Greetings!

**Comment by tottakai** [comment]
would something like .flatMapIterable(packs -> packs) -> .flatMap { packs -> packs.toObservable() } work?

**Comment by robertofrontado** [comment]
How could I miss that?

Yeah @tottakai thanks!

**Comment by raytso** [comment]
there are no `toObseravble()` in RxSwift

**Comment by sergdort** [comment]
There is `asObservable()`
