### ISSUE TITLE
include of non-modular header inside framwork module 'RxCocoa.Swift'

### ISSUE THREAD

**Issue by hilen** [ReactiveX/RxSwift#411]
I run it ok yesterday, but failed today. Why ?
The error message is :
![image](https://cloud.githubusercontent.com/assets/2245840/12391392/78ac8fc4-be22-11e5-95f5-fccb8e2cc691.png)

My pod version is 1.0.0.beta.2
pod file is
```
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'
    pod 'RxBlocking', '~> 2.0'
```

How to fix it ?

**Comment by kzaher** [comment]
Hi @hilen,

This is a dupe of problem that for some reason sometimes appear. I think I've managed to repro it once, but can't remember what did I exactly do ...

I think I've removed CocoaPods integration from project entirely, and readded it (including workspace, configurations ...)

You might want to also clean derived data, cocoapods cache, etc ...

If you add this to new project, it works, right?

**Comment by hilen** [comment]
@kzaher Hi, thanks for your response.
As you say if I add it to the new project, it works.  And If I replace `#import <RxSwift/RxSwift.h>  to #import "RxSwift.h"` in `RxCocoa-Swift.h` file. It works too.
So this problem is weird. I just run it by replace the `#import` string.

**Comment by hilen** [comment]
@kzaher Hi, I fix this error by remove the `${SRCROOT}  in Build Settings -> Header Search Paths` , take a look at here : https://github.com/CocoaPods/CocoaPods/issues/4835 . Maybe there is something wrong with `CocoaPods` and `${SRCROOT}  with recursive`  ：）

**Comment by zhaoyunyi** [comment]
I got this errror too , it is very sucks, how to solve it?:(

**Comment by pertau** [comment]
I'm using Carthage and changing the Header Search Paths from recursive to non-recursive fixed this problem.
