### ISSUE TITLE
Cannot load RxTests framwork

### ISSUE THREAD

**Issue by nopctoday** [ReactiveX/RxSwift#415]
I installed the RxSwift, RxCocoa, RxBlocking, RxTests via Cocoapods according to the instructions. However, all of sudden my app starts crashing and reports that it couldn't find RxTests framework. No matter how I try to reference it, it would just crash. I am not even using RxSwift yet:

```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/Me/Library/Developer/Xcode/DerivedData/ZZ-bqgnogyvvghkeweubgasikolmbsl/Build/Products/Debug-iphonesimulator/RxTests.framework/RxTests
  Reason: image not found
```

**Comment by carlosypunto** [comment]
RxTests requires an target with XCText support, for use it you must do this in the Podfile:

```
platform :ios, '8.0'

use_frameworks!

pod 'RxSwift',    '~> 2.0'
pod 'RxCocoa',    '~> 2.0'
pod 'RxBlocking', '~> 2.0'

target "the_name_of_a_XCTest_compatible_target" do
	pod 'RxTests',    '~> 2.0'
end
```

If you are beginning maybe you do not need to use [`RxBlocking`](https://github.com/ReactiveX/RxSwift/blob/master/RxBlocking/README.md)

So, I recommend you use `RxSwift` and `RxCocoa` only.

```
platform :ios, '8.0'

use_frameworks!

pod 'RxSwift',    '~> 2.0'
pod 'RxCocoa',    '~> 2.0'
```

**Comment by nopctoday** [comment]
Oh excellent! It works now! Kudos @carlosypunto
