### ISSUE TITLE
Move KVO code from RxCocoa to RxSwift

### ISSUE THREAD

**Issue by kykim** [ReactiveX/RxSwift#424]
I'm using RxSwift and don't need most of the features in RxCocoa.
One feature I would like is the KVO observables.
I'm wondering if that code could be moved down into RxSwift from RxCocoa.
My reasoning is this:
    * `Foundation` based code => RxSwift
    * `UIKit` or `Cocoa` based code  => RxCocoa

Thoughts?

**Comment by fpillet** [comment]
KVO observables depend on features of the Obj-C runtime, not available on Linux. RxSwift core aims to be portable, so I don't think this will happen.

**Comment by kykim** [comment]
Ah. Okay.
