### ISSUE TITLE
flatMap error

### ISSUE THREAD

**Issue by jcampbell05** [ReactiveX/RxSwift#426]
I get this error when trying to use flatMap.

<img width="1089" alt="screen shot 2016-01-21 at 19 52 06" src="https://cloud.githubusercontent.com/assets/1484989/12492527/8b6845d8-c078-11e5-875f-008e42793ae4.png">

The function I am trying to wrap comes from the Facebook SDK.

```swift
extension FBSDKLoginManager {
    
    func rx_logIn(readPermissions: [String]) -> Observable<FBSDKLoginManagerLoginResult> {
        
        return Observable.create({
            
            let subject = $0
        
            self.logInWithReadPermissions(readPermissions) {
        
                result, error in
                
                if error != nil {
                    subject.onError(error)
                } else {
                    subject.onNext(result)
                    subject.onCompleted()
                }
            }
            
            return NopDisposable.instance
        })
        
    }
}
```

**Comment by sergdort** [comment]
Hi, @jcampbell05  when I have compiler errors like this I try to write return type explicitly,

kind of :

```swift
    flatMap { obj -> Observable<MyObj>
          return self.rx_myObservable(obj)
    }
```

**Comment by jcampbell05** [comment]
Really helped, thank you! How come the compiler complains so much ?

**Comment by bontoJR** [comment]
Inference, unfortunately sometimes with closures the compiler isn't able to insert the type and you get back strange errors. :)

**Comment by jcampbell05** [comment]
Yeah your solution worked :)
