### ISSUE TITLE
why  did you delete UIActionSheet+Rx and UIAlertView+Rx from source code ? 

### ISSUE THREAD

**Issue by kaich** [ReactiveX/RxSwift#427]
I find the newest source code not contain UIAlertView+Rx and UIActionSheet+Rx. Why did you delete these ?  Whether  the Way of  delegate observe changed ?

**Comment by sergdort** [comment]
Hi, @kaich , I guess because these classes are deprecated

**Comment by kaich** [comment]
@sergdort Yeah , I agree. Thank you!
