### ISSUE TITLE
Helpers for map+filter operations (AKA collect)

### ISSUE THREAD

**Issue by laurilehmijoki** [ReactiveX/RxSwift#428]
Hello and thanks for RxSwift, I enjoy using it!

I created the following helper functions into my project. They provide a succinct way for expressing `map` and then `filter`.

I wonder if RxSwift already has something like these helpers. If not, would you like to see a pull request that adds these functions into RxSwift?

```swift
struct ObservableHelper {
    static func collectSome<E>(value: E?) -> Observable<E> {
        return ObservableHelper.collect { $0 ?? nil } (value)
    }

    static func collectAs<ExpectedType>(t: ExpectedType.Type)(_ value: Any ) -> Observable<ExpectedType> {
        return ObservableHelper.collect {
            switch $0 {
                case let v as ExpectedType: return v
                default: return nil
            }
        } (value)

    }

    static func collect<OldValue, NewValue>(f: OldValue -> NewValue?)(_ value: OldValue) -> Observable<NewValue> {
        if let someValue = f(value) {
            return Observable.just(someValue)
        } else {
            return Observable.never()
        }
    }
}
```

One can use the above functions like so:

```swift
protocol MyType {}
protocol MyTypeExtension : MyType {}

let observable: Observable<MyType?> = // definition comes here
observable
    .flatMap(ObservableHelper.collectSome)
    .flatMap(ObservableHelper.collectAs(MyTypeExtension.self)
```

I've borrowed the concept "collect" from the Scala [API](http://www.scala-lang.org/api/2.11.4/index.html#scala.collection.TraversableLike@collect[B](pf:PartialFunction[A,B]):Traversable[B]).

**Comment by kzaher** [comment]
Hi @laurilehmijoki ,

thnx for opening this issue. Those are really nice extension methods, but we would really like to keep this library as minimalistic and essential as possible.

I'm sure there will be other extensions libraries with "sugar" operators, so it might make more sense to add these operators there.

**Comment by laurilehmijoki** [comment]
Ok, thanks for the reply! Closing the issue...
