### ISSUE TITLE
Help in sequence of Observables

### ISSUE THREAD

**Issue by ed-mejia** [ReactiveX/RxSwift#434]
Hi, Im kind of lost trying to do this sequence and maybe someone could help me.

Lets say I have the following func that returns Observables

func rx_fetchSchools() -> Observable<[Schools]>
\ -func rx_fetchStudents(schoolID: Int) -> Observable<[Students]>
  \ -func rx_fetchScores(studentID: Int) -> Observable<[Scores]>

I would like to chain in a single process:

1) Fetch all the schools,
2) for each school fetch all the students
3) for each student fetch all the scores

Any hint to the right path would be appreciated :+1:

**Comment by kaich** [comment]
I write fake request as below : 

```swift
func rx_fetchSchools() -> Observable<[String]>
{
    return just(createEntity("school"))
}


func rx_fetchStudents(school: String?) -> Observable<[String]> {
    return just(createEntity("\(school)student"))
}

func rx_fetchScores(student: String?) -> Observable<[String]> {
    return just(createEntity("\(student)scores"))
}

func createEntity(entity :String) -> [String] {
   return (1...20).map { (index)  in
     return "\(entity)_\(index)"
    }
}
```

If you want fetch a request denpend on another request. I do it like this : 

```swift 
rx_fetchSchools()
            .map({$0.toObservable()})
            .flatMap({ (school)  in
                return school.flatMap({ (school)  in
                      return  rx_fetchStudents(school)
                                .map({$0.toObservable()})
                                .flatMap({ (student) in
                                    student.flatMap({ (student) in
                                        return rx_fetchScores(student)
                                    })
                             })
                })
            })
            .subscribeNext({ (scores) -> Void in
                print(scores)
            })
            .addDisposableTo(disposeBag)
```
I can get all scores. this code seems to  be redundant. I don't have any idea to optimize it. If you have any idea, please tell me. part of log as below : 

["Optional(\"Optional(\\\"school_1\\\")student_1\")scores_1", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_2", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_3", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_4", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_5", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_6", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_7", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_8", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_9", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_10", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_11", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_12", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_13", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_14", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_15", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_16", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_17", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_18", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_19", "Optional(\"Optional(\\\"school_1\\\")student_1\")scores_20"]
["Optional(\"Optional(\\\"school_1\\\")student_2\")scores_1", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_2", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_3", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_4", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_5", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_6", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_7", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_8", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_9", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_10", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_11", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_12", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_13", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_14", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_15", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_16", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_17", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_18", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_19", "Optional(\"Optional(\\\"school_1\\\")student_2\")scores_20"]

**Comment by ed-mejia** [comment]
Hey @kaich thank you very much, your sample really help me to understand a little bit more this flow thing...

It works as expected but because I needed to do some stuff in the middle of the flow, catch any error, etc so I start testing and ended with this:

```
rx_fetchSchools().map { schools in
            return schools.toObservable()
            }.concat().map { school -> Observable<[String]> in
                print("Saving to Database school: \(school)")
                return self.rx_fetchStudents(school)
            }.concat().map { students in
                return students.toObservable()
            }.concat().map { student -> Observable<[String]> in
                print("Saving to Database  Student: \(student)")
                return self.rx_fetchScores(student)
            }.concat().map { scores in
                return scores.toObservable()
            }.concat().subscribe(onNext: { (score) -> Void in
                print("Saving to Database Score: \(score)")
                }, onError: { (error) -> Void in
                    print("ERROR: \(error)")
                }, onCompleted: { () -> Void in
                    print("COMPLETED!")
            }).addDisposableTo(disposeBag)

```

I'm not sure if this is optimal, furthermore Im not sure about the use of concat() for example if I use merge() works the same way :worried:

If I don't any of concat() or merge() operators I'm unable to get the full sequence but just one school

**Comment by ed-mejia** [comment]
On the other hand what should be the right way to deal with the func in this example

```
    func rx_fetchSchools() -> Observable<[Schools]> {
        return Observable.create({ (observer) -> Disposable in
            let request = network.requestSchools() { (response: SchoolList?, error: APIError?) -> Void in
                if let error = error {
                    observer.onError("ERROR!")
                }
                if let response = response  where response.list.count > 0 {
                    observer.onNext(response.list)
                }
                // mark as completed this event
                observer.onCompleted()
            }
            return AnonymousDisposable{
                request.cancel()
            }
        })
    }
```
should I return the full array or update the func to return  Observable<School>  and:

```
if let response = response  where response.list.count > 0 {
  for school in response.list {
      observer.onNext(school)                        
  }
}
```

:anguished:

**Comment by thanegill** [comment]
Use `merge()`, `concat()` will only subscribe to the next observable when the previous completes. `merge()` will run all synchronously. Read up on [reactivex.io documentation](http://reactivex.io/documentation/operators/merge.html)

I would return the full array and use `.flatMap` to split it up later. Ex: 

```swift
AnObservableOfSchools
    .flatMap { schools in
        return schools.toObservable()
    }
```

**Comment by kaich** [comment]
hey @ed-mejia 
concat() is similar to merge(). concat() send value is in order. The first complete then start  second observable. But merge() not in order.  eg:
[a,b].concat().
 a send 1,2,3 , b send 4,5,6.  
the result must be 1,2,3,4,5,6

[a,b].merge()
a send 1,2,3 , b send 4,5,6.
the result may be 1,4 ,2,3 ,5,6.  (the result may be cross)

But in the your example they are same funcation.

**Comment by ed-mejia** [comment]
Hey guys @thanegill @kaich thanks for your examples I have it more clear now ... Yay!!! :+1:
