### ISSUE TITLE
How can I get the current value of the Observable<T> type without subscribe func

### ISSUE THREAD

**Issue by DuckDeck** [ReactiveX/RxSwift#435]
As the title. So how can I fetch the current value(T) of the Observable<T> type without subscribe func

**Comment by sergdort** [comment]
Hi, @DuckDeck  as far as I know current value u can get only within `Variable<T>`

To clarify the concept of observable I would sagest you to take a look on [this](https://www.youtube.com/watch?v=sTSQlYX5DU0) video

**Comment by thanegill** [comment]
There is no value to an Observable until you subscribe. What's your use case?

**Comment by DuckDeck** [comment]
Here is the instance: I can get a Observable<String> from UITextView txt: 
let observableTxt = txt.rx_text
so how can I convert observableTxt to txt.text with out subscribe func? I mean to fetch the current value from Observable<String> .

**Comment by thanegill** [comment]
The observable `.rx_text` is just a sequence of changes to the `.text` field so the "current" value is the same as `.text`

**Comment by AleksandarSavic95** [comment]
I know the issue is closed, but for anyone still wondering, here it is:
```
...
let currentValue;
myObservableFunction().subscribe(v => currentValue = v);
// use currentValue as You wish
```
**Note** This will work if the `myObservableFunction` returns the observable **immediately**.
If the called function (the one You are subscribing to) is a longer-lasting operation, You should pass the retrieved value to a callback function:
```
myObservableFunction().subscribe(v => myCallback(v));
```

**Comment by freak4pc** [comment]
Your code seems to be RxJS, not RxSwift.
