### ISSUE TITLE
sectionIndexTitlesForTableView for RxTableViewSectionedDataSource 

### ISSUE THREAD

**Issue by avdwerff** [ReactiveX/RxSwift#439]
Is there an easy way to support sectionForSectionIndexTitle and sectionIndexTitlesForTableView for the RxTableViewSectionedDataSource?

**Comment by sergdort** [comment]
Hi, @avdwerff I've recently added some lambdas to [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources) you can submit your pull request to =) 

Or subclass from RxTableViewSectionedDataSource and implement

**Comment by avdwerff** [comment]
ah thanks, I will check yours first.

**Comment by kzaher** [comment]
This looks like we can close it.
