### ISSUE TITLE
Feature Request: delay operator

### ISSUE THREAD

**Issue by gekitz** [ReactiveX/RxSwift#441]
I was looking at the list of supported operators and I couldn't find `delay`, I saw `delaySubscription` which, from my understanding, delays the subscription whereas `delay` would delay the forwarding of the signal every time the signal is emitted. 

Are there any plans to support that operator or clues on how to implement it?

Thanks for the great work! :+1:

**Comment by thanegill** [comment]
A workaround for now:

```swift
extension ObservableType {
    public func delay(time: NSTimeInterval, scheduler: SchedulerType = MainScheduler.instance) -> Observable<E> {
        return self.flatMap { element in
            Observable<Int>.timer(time, scheduler: scheduler)
                .map { _ in
                    return element
                }
        }
    }
}
```

**Comment by gekitz** [comment]
@thanegill thanks a lot, works perfectly fine. You said you wouldn't use that in production, what are the reasons for that?

**Comment by kzaher** [comment]
@gekitz I think that one of the problems might be that this won't preserve ordering or elements since concurrent scheduler could reverse the order (flatMap is map + merge operator).

Can you please explain to me context in which you need delay?

**Comment by gekitz** [comment]
I understand. The context I'm using this in, is to delay the signal of `rx_didEnterRegion` by 30 seconds. The idea is that a user could enter a geofence, but it could be that they don't stay there long enough. After the delay I check if the user is still in the region and only then the signal would get propagated. 

Does that make sense to you?

**Comment by thanegill** [comment]
@gekitz As @kzaher said elements might not stay in the same order.

As for `rx_didEnterRegion` maybe something like this:

```swift
    public func isStillInRegionAfter(time: NSTimeInterval) -> Observable<Bool> {
        return CLLocationManager().rx_didEnterRegion
            .doOn(onNext: { region in
                CLLocationManager().requestStateForRegion(region)
            })
            .buffer(timeSpan: time, count: 4, scheduler: MainScheduler.instance)
            .map { regions in
                return regions.reduce(true, combine: { (bool, region) -> Bool in
                    return region.identifier == regions.first?.identifier
                })
        }
    }
```

**Comment by kzaher** [comment]
Would something like this conceptually work for you?
```
let stayedInRegionForMoreThen30Minutes = CLLocationManager().rx_didEnterRegion
            .flatMapLatest { region in
                     Observable.just(region).delaySubscription(30 * 60, scheduler)
            }
```

**Comment by gekitz** [comment]
actually both solutions solved the problem for me, thanks. 

Should we close the issue or is it still a valid feature request?

**Comment by kzaher** [comment]
I think that until we find some compelling use cases where `delay` operator is absolutely necessary, we should dodge it :)

**Comment by gekitz** [comment]
Sounds good.
