### ISSUE TITLE
rx_observe need dynamic keyword before property to work when value change

### ISSUE THREAD

**Issue by huynguyencong** [ReactiveX/RxSwift#451]
Assume I have a class `Person` with property `yearOld`. And I want to observe `yearOld` property. I found that it doesn't send next when `yearOld` property value change.

```
person.rx_observe(Int.self, "yearOld").subscribeNext { (number) -> Void in
      print("\(number)")
}
```

I search and found that KVO also not working properly until I add dynamic keyword before the yearOld property

```
class Person: NSObject {
    dynamic var yearOld: Int = 1
}
```

Reference: http://stackoverflow.com/questions/24092285/is-key-value-observation-kvo-available-in-swift

Should you note it in KVO example in Readme file?

**Comment by kzaher** [comment]
I think KVO is a mechanism that shouldn't be encouraged in new code.

If want to do something like that, probably.

```
class Person: NSObject {
    let yearOld = Variable(1)
}
```
... is a much cleaner solution, and preferred solution.

Having said that, I would suggest that you don't use classes and such a fine granularity for observing changes :)

How could we document that best in README.md, I'm open to suggestions :)

**Comment by huynguyencong** [comment]
But yearOld is a variable I need to change. And I want subscribe next to that variable, every time it change value. How can I do that without KVO? And so how rx_observe can work properly?

**Comment by kzaher** [comment]
Hi @huynguyencong ,

I've written an example how to do this without KVO in my last reply. KVO is a really awkward mechanism that has huge amount of issues associated with it.

We have wrapped it because is some cases you have no choice, but if you do, then my advice is to stay away from KVO. 

Having said that, if you insist on using KVO with swift classes, then yes, dynamic is required.

**Comment by huynguyencong** [comment]
But you use "let" keyword, that mean it is a constant. But I want it is a variable, because yearOld is a property that I need to change it every year.
I guess rx_observe base on KVO, so it also need "dynamic" keyword, because I want to use that property as "var"

**Comment by kzaher** [comment]
let only means that reference to variable is immutable.

```
class Person: NSObject {
    let yearOld = Variable(1)
}

let p = Person()
p.yearOld.value = 23
p.yearOld.map { } ...
```

**Comment by huynguyencong** [comment]
And when I change yearOld value to 24, how I can get a signal?

If I do below:
person yearOld.rx_observe(Int.self, "value").subscribeNext { (number) -> Void in
      print("\(number)")
}

I also have to use dynamic in value property in Variable class?
