### ISSUE TITLE
Module file was created by an older version of the compiler, rebuild `RxSwift` and try again.

### ISSUE THREAD

**Issue by manojmahapatra** [ReactiveX/RxSwift#452]
Hi there,

I was trying to integrate `RxSwift` via carthage in one of my projects when I encountered the error (as mentioned in title) while trying to import `RxSwift and(or) RxCocoa`. Though I tried to build both the frameworks to update swift modules(`Carthage/build/iOS/RxSwift.Framework/Modules`) but it's not working and I'm still seeing the same error. 

This is happening in `XCode 7.2`. Is there anything am missing?

**Comment by kzaher** [comment]
Hi,

maybe you just need to clean carthage cache and derived data?

**Comment by manojmahapatra** [comment]
@kzaher I'd tried both the options earlier, nothing that worked. Any other pointers?

**Comment by kzaher** [comment]
@manojmahapatra maybe you have more then one Xcode maybe and Command line tools (Preferences > Command Line Tools) are set to older version.

**Comment by manojmahapatra** [comment]
@kzaher yeah you were right, it was due to an older Xcode version sitting in my system and CLI was pointing to that version. Thanks mate!
