### ISSUE TITLE
Add timer and interval to Driver

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#455]
As they never fail to begin with.

**Comment by kzaher** [comment]
I think we could do that.

**Comment by thanegill** [comment]
I can start working on it. Should they default to a certain scheduler?

**Comment by kzaher** [comment]
Driver wouldn't be able to have scheduler parameter but use `driverObserveOnScheduler` (MainScheduler) because that's one of the requirements for `Driver` unit (deliver on main scheduler).

**Comment by kzaher** [comment]
Added them.
