### ISSUE TITLE
change implementation of rx_didFinishDeferredUpdatesWithError

### ISSUE THREAD

**Issue by gekitz** [ReactiveX/RxSwift#462]
I discovered that `rx_didFinishDeferredUpdatesWithError` is implemented in a slightly weird way and I suggest to update it.

The delegate method `optional public func locationManager(manager: CLLocationManager, didFinishDeferredUpdatesWithError error: NSError?)` states that the error is optional. From the documentation we can extract that the method is called whenever deferred updates are finished, this could be based on an error or just after the user travelled the expected distance or the timeout fires. Both are success cases.

The current implementations puts a new event on the stream only if an error occurs, I suggest to change that in favor of the success case. Whenever the delegate is called without an error, it would trigger a next event and in case of an error we would end up in onError.

Suggested implementation, which I could put in a pull request:

```swift
    public var rx_didFinishDeferredUpdatesWithError: Observable<Void> {
        return rx_delegate.observe("locationManager:didFinishDeferredUpdatesWithError:")
            .map { a in
                
                if let error = a[1] as? NSError {
                    throw error
                }
                
                return ()
        }
    }
```

Does that make sense for you?

**Comment by kzaher** [comment]
Hi @gekitz ,

I would agree with you, it is messed up the way we have it implemented now. Thnx for reporting this. We need to do something about this.

**Comment by gekitz** [comment]
I can contribute the change for that, no problem.

**Comment by kzaher** [comment]
Hm. It looks like maybe the code in your branch is stale?

This is what I see in `develop`.

```
public var rx_didFinishDeferredUpdatesWithError: Observable<NSError> {
        return rx_delegate.observe("locationManager:didFinishDeferredUpdatesWithError:")
            .map { a in
                return try castOrThrow(NSError.self, a[1])
            }
    }
```

I think this one is also wrong, it should probably be

```
public var rx_didFinishDeferredUpdatesWithError: Observable<NSError?> {
        return rx_delegate.observe("locationManager:didFinishDeferredUpdatesWithError:")
            .map { a in
                return try castOptionalOrThrow(NSError.self, a[1])
            }
    }
```

**Comment by gekitz** [comment]
I created a PR from my reference implementation and updated the unit tests.

**Comment by kzaher** [comment]
Hi @gekitz,

I think that behavior that you are trying to accomplish is reasonable, but I don't think this is the correct layer in which we would want to implement this behavior.

`rx_didFinishDeferredUpdatesWithError` is just meant as a simple delegate wrapper, and not trying to do anything smart.

That's why it looks to me that this is the correct implementation.

```
public var rx_didFinishDeferredUpdatesWithError: Observable<NSError?> {
        return rx_delegate.observe("locationManager:didFinishDeferredUpdatesWithError:")
            .map { a in
                return try castOptionalOrThrow(NSError.self, a[1])
            }
    }
```

I think that then you could use that method to implement something that you are asking for. Something like:

```
public func rx_deferredLocationUpdates() -> Observable<[CLLocation]> { }
```

I think we'll probably `rx_deferredLocationUpdates` in future when I investigate this in more detail.

**Comment by gekitz** [comment]
I think you're right, otherwise you would have to subscribe again once you get an error and since it's supposed to be a wrapper, your suggestion is actually the right one.

Thanks for clarifying. Should we keep this issue open for the updated implementation you suggested?

**Comment by kzaher** [comment]
Let's keep it open.

I need to fix this first :) 

Hoping I'll have some time next weekend to clean up these small issues and publish a new release :)

**Comment by kzaher** [comment]
We've added optional `NSError`. I think we can close this now.
