### ISSUE TITLE
Recommended type for Observable that never sends value?

### ISSUE THREAD

**Issue by JSchaenzle** [ReactiveX/RxSwift#468]
For a signal that just does some work upon subscription, and then completes, what would you recommend using for the type? AnyObject? In ReactiveCocoa, there was a RACUnit class that you could use to send a `defaultUnit` if you just needed to trigger something but you didn't care what the data being sent was. Does RxSwift have something similar?

**Comment by thanegill** [comment]
`Void`

**Comment by kzaher** [comment]
This looks like we can close it.
