### ISSUE TITLE
RxTest fails to build in Xcode 7.3-beta2

### ISSUE THREAD

**Issue by koke** [ReactiveX/RxSwift#472]
Running the test suite (or using the RxTest pod) throws a couple build errors when using Xcode 7.3 beta 2

> XCTest+Rx.swift:67:7: Cannot invoke 'XCTAssertEqual' with an argument list of type '([AnyEquatable<Event<T>>], [AnyEquatable<Event<T>>], file: String, line: Uint)'
> XCTest+Rx.swift:95:7: Cannot invoke 'XCTAssertEqual' with an argument list of type '([AnyEquatable<Recorded<Event<T>>>], [AnyEquatable<Recorded<Event<T>>>], file: String, line: Uint)'

It seems the `file` parameter on `XCTAssertEqual` changed from `String` to `StaticString` in https://github.com/apple/swift/pull/888

**Comment by koke** [comment]
I got a fix in https://github.com/ReactiveX/RxSwift/commit/60b4b965092c372edce7b18ed67f863d3a7a3e8b, but that breaks the builds on Xcode 7.2. I'm not sure if there's a workaround or this will have to be a new release that supports Swift 2.2 only.

**Comment by kzaher** [comment]
Hi @koke ,

Thnx for reporting this. I'm hoping this is just an Apple but and they will fix this soon :(. 

I'm not sure it would be a good idea to pull this in immediately since it you are telling me this will break on Xcode 7.2, and this is the released version. Let's monitor this and see what will Apple do here. 

If they release a version that requires `StaticString`, then we'll make the same breaking change.

**Comment by Bogidon** [comment]
Hi @koke and @kzaher,

How can I use 60b4b96 with Carthage? Is it in a branch? If not, could we create a branch called, for example, `Xcode7.3`?

**Comment by kzaher** [comment]
Hi @Bogidon ,

I've created new branch xcode/7.3 If @koke makes PR to that branch, I would be happy to merge it.

**Comment by tomburns** [comment]
@kzaher the xcode/7.3 branch gets further into the build process, but still fails:

```
/Users/.../RxSwift/RxSwift/DataStructures/Queue.swift:165:16: warning: 'anyGenerator' is deprecated: renamed to 'AnyGenerator'
/Users/.../RxSwift/RxSwift/DataStructures/InfiniteSequence.swift:26:16: warning: 'anyGenerator' is deprecated: renamed to 'AnyGenerator'
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **
```

**Comment by kzaher** [comment]
¯\\\_(ツ)\_/¯ 

I've tried to support Xcode 7.3, but since even released 7.2.1 version still has horribly buggy compiler, it's pointless at this stage.

I'm waiting until they make transition from catastrophically unstable compiler to just the usually horrible one (when they release it) :)

Try building just Debug configuration. I believe Xcode compiler just fails when it tries to optimize the code.

**Comment by Bogidon** [comment]
Interesting @kzaher. I was getting the same error as @tomburns.

Let's 🙏 they fix it before release. Should we file a rdar?

**Comment by kzaher** [comment]
@Bogidon if you guys can file a radar, that would be :+1:

**Comment by stephenvisser** [comment]
Seems like this is still an issue after today's release

**Comment by ibadcool** [comment]
XCTAssertEqual(leftEquatable, rightEquatable, file: file, line: line)

Cannot invoke 'XCTAssertEqual' with an argument list of type '([AnyEquatable<Event<T>>], [AnyEquatable<Event<T>>], file: String, line: UInt)'

**Comment by alexpopov** [comment]
It still fails to build for me, but for a different reason:
Reason: Project /Carthage/Checkouts/RxSwift/RxTests/RxTests.xcodeproj cannot be opened because it is missing its project.pbxproj file.

If I try to open the project by hand, and it complains about the same issue. 

If it matters, I run `carthage update --platform iOS`

**Comment by kzaher** [comment]
Hi guys,

I'm little confused here. I've ran the integration tests on my machine and both CocoaPods and Carthage integrations were ok.

Are you sure you've got the correct version of Xcode selected for `Command Line Tools`? 
<img width="750" alt="screen shot 2016-03-23 at 22 51 21" src="https://cloud.githubusercontent.com/assets/1641148/14002074/cd960d6c-f149-11e5-8a95-875147885355.png">

**Comment by alexpopov** [comment]
I do. I tried clearing the Carthage cache as well. If I run `xcodebuild -version` from the command line I also get 
  `Xcode 7.3`
  `Build version 7D175`
So I'm at a loss as to what to do.

**Comment by kzaher** [comment]
... and just to be clear, you've removed both `~/Library/Caches/org.carthage.CarthageKit/` and `Carthage` directories?

**Comment by alexpopov** [comment]
Just to be clear... no. I removed the latter first and the build failed. Then I removed the former, and the build failed. Removing both at once did the trick! Thanks a bunch! I guess this is the solution, at least for my particular issue.

**Comment by kzaher** [comment]
Ok, glad this was a simple solution :) Weird, but simple :)

**Comment by idanhaviv** [comment]
I still get the same error:
> Cannot invoke 'XCTAssertEqual' with an argument list of type '([AnyEquatable<Event<T>>], 
> [AnyEquatable<Event<T>>], file: String, line: UInt)'
with XCode 7.3 
this is my pod file:

> pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
> pod 'RxSwift',    '~> 2.2'
> pod 'RxCocoa',    '~> 2.0'
> pod 'RxBlocking', '~> 2.0'
> pod 'CocoaLumberjack/Swift'
> pod 'SWXMLHash', '~> 2.1.0'
> pod 'Moya'
> pod 'Moya/RxSwift'
> pod 'Moya-ObjectMapper/RxSwift', '~> 1.1.6'
> pod 'VBFPopFlatButton'

> target 'TrollTests', :exclusive => true do
>    pod 'RxTests',    '~> 2.0'
>    pod 'Quick', '~> 0.9.0'
>    pod 'Nimble', '~> 3.2.0'
>    pod 'Dip'
> end

i tried updating to RxSwift latest version 2.3.1 but got this error upon pod install:
[!] Unable to satisfy the following requirements:

> - `RxSwift (~> 2.3.1)` required by `Podfile`
> - `RxSwift (~> 2.2)` required by `RxCocoa (2.2.0)`
> - `RxSwift (~> 2.2)` required by `RxBlocking (2.2.0)`
> - `RxSwift (~> 2.0)` required by `Moya/RxSwift (6.2.0)`
> - `RxSwift (~> 2.2.0)` required by `Moya-ObjectMapper/RxSwift (1.1.7)`
> - `RxSwift (~> 2.2)` required by `RxTests (2.2.0)`

i also tried not specifying version numbers in PodFile with no success

**Comment by fpillet** [comment]
Your Podfile lists RxSwift at 2.2 but RxCocoa at 2.0. You need all versions to be the same (for RxTests as well).

**Comment by idanhaviv** [comment]
i changed all to 2.0 but still get the same error

**Comment by fpillet** [comment]
You need to use 2.3.1 with Xcode 7.3 and Swift 2.2. Previous versions of RxSwift won't compile correctly.

**Comment by kzaher** [comment]
Hi @idanhaviv ,

problems seems to be in `Moya-ObjectMapper/RxSwift` requesting `2.2.0` instead of `2.2`.

```
ss.dependency "RxSwift", "~> 2.2.0"
```

when it should be

```
ss.dependency "RxSwift", "~> 2.2"
```

**Comment by idanhaviv** [comment]
if it was 2.2 while i have 2.3.1 should it work fine? anything i can do besides open an issue on Moya-ObjectMapper?
