### ISSUE TITLE
Add UISplitViewController to RxCocoa

### ISSUE THREAD

**Issue by gregpardo** [ReactiveX/RxSwift#473]
Could include things like rx_preferredDisplayMode and such. Might consider trying to tackle this if I can find the time. 

EDIT: On second thought looks like there are no controllers in RxCocoa only UIView/UIControls etc. I'm just going to manually handle this with a driver for now.

**Comment by kzaher** [comment]
Hey, yeah, trying to keep as much code as possible out of this library :)

We can only wrap most common and useful interfaces and rely on other libraries to help us wrap specialized APIs otherwise line count would explode :)

**Comment by kzaher** [comment]
Hi @gregpardo ,

I'm assuming we can close this :)
