### ISSUE TITLE
Is it possible to have a subject push values to itself without creating an infinite loop?

### ISSUE THREAD

**Issue by JaidevSoin** [ReactiveX/RxSwift#482]
I have a UITableView, which I want to put into an editing state if certain conditions are met. The primary way to toggling edit is through an edit button.

So the view elements I have are

    let tableView = UITableView()
    let editButton = UIButton()

And whether the tableView should be in editing mode is fed from:

    let editing = BehaviorSubject(value: false)

Which will be hooked up to the tableView using something like:

    editing.subscribeNext { isEditing in
      tableView.setEditing(isEditing, animated: true)
    }

When the edit button is tapped, I want that to push a new value to ``editing``, that is the negation of the most recent value sent to ``editing``. The most recently value may have been set by a tap on ``editButton``, or it may have come from somewhere else.

I don't understand how to combine the stream for the button press with the stream for ``editing`` in such a way that allows this without an infinite loop e.g.

    Obervable.combineLatest(editButton.rx_tap.asObservable(), editing) { _, isEditing in
      editing.onNext(!isEditing)
    }

I'm aware that the tableView has an ``editing`` property, but I don't want to rely on that as I am looking for a more general solution that I can re-use elsewhere. I'm also not looking to track the value of isEditing in an instance var, or even as a Variable(), as I am looking for a stateless, stream based solution (if this is at all possible).

Thank you!

P.S. I have also asked this question on StackOverflow in case you would like to answer there: http://stackoverflow.com/q/35329892/270836

P.P.S. Only been playing with RxSwift a week or two, but I'm really digging it. Thanks guys!

**Comment by kzaher** [comment]
I think you can do something like 
```
let editButton = UIButton()

editButton.rx_tap
     .scan(false) { !$0 }
     .startWith(false)
     .subscribeNext { isEditing in
            tableView.setEditing(isEditing, animated: true)
     }
```

... you can probably create a convenience for `scan` and `startWith` so you can write something like 

```
let editButton = UIButton()

editButton.rx_tap
     .scanAndStartWith(false) { !$0 }
     .subscribeNext { isEditing in
            tableView.setEditing(isEditing, animated: true)
     }
```

**Comment by JaidevSoin** [comment]
Cheers for the response.

Correct me if I'm wrong, but using scan here in this way will emit a stream of alternating booleans, so for 3 taps it would emit: false true false true?

This would be perfect if I wanted to toggle editing using only editButton, however editing can also be toggled via other inputs - For example, if the table is currently being edited, and a user selects a row, that will both push a related ViewController for that row, as well as disable editing (done using tableView.rx_itemSelected). 

In this case, if I then tap the editButton again, it's going to send a ``false``, which is inappropriate as the table is already no longer editing.

Any suggestions?

Cheers

**Comment by kzaher** [comment]
Hi @JaidevSoin ,

You can combine multiple inputs that toggle that.

```swift
let toggleEditingState = Observable.of(
      editButton.rx_tap, 
      tableView.rx_itemSelected.map { _ in () }
).merge()

toggleEditingState
     .scanAndStartWith(false) { !$0 }
     .subscribeNext { isEditing in
            tableView.setEditing(isEditing, animated: true)
     }
```

**Comment by JaidevSoin** [comment]
Hey @kzaher, cheers for the continued help.

So I only want ``rx_itemSelected`` on ``tableView`` to disable editing if editing is currently enabled. If editing isn't currently enabled, then selecting an item should not toggle editing mode.

The two ways I see of maybe doing this relate to either:

1) Any time ``rx_itemSelected`` fires, map it to a ``false`` and push it to a ``editing<Bool>`` stream, which is also pushed to by tapping ``editButton`` - The problem is this once again runs in to is that the value that comes out of the ``editButton`` ignores the input from ``rx_itemSelected``, so I'm running in to the problem of ``editButton`` sending a false again after editing is already disabled.

2) Somehow filter ``rx_itemSelected`` to only toggle editing state if the editing state is currently true. I am not sure how to do this though, as this requires combining some sort of ``editing<Bool>`` stream with ``rx_itemSelected`` to push to the ``editing<Bool>`` stream again, however this of course puts me in an infinite loop again.

Once again, any help is much appreciated!

Thanks

**Comment by JaidevSoin** [comment]
Cheers for helping me thinking through this @kzaher. I've now worked it out :). The key was ``withLatestFrom``. I've included an example of this below in case this can help anyone else. ``editButton`` is the primary way to trigger editing mode on or off, and I've included an event sent via ``tableView.rx_itemSelected`` as an additional input example (in this case, I want editing to end any time an item is selected).

    let isEditing = BehaviorSubject(value: false)
    let tableView = UITableView()
    let editButton = UIButton()

    tableView.rx_itemSelected
      .map { _ in false }
      .bindTo(isEditing)

    editButton.rx_tap.withLatestFrom(isEditing)
      .map { !$0 }
      .bindTo(isEditing)

    isEditing.subscribeNext { editing in
      tableView.setEditing(editing, animated: true)
    }

Note: This solution sends ``.Next(false)`` to ``isEditing`` every time an item is selected, even if the table isn't currently in editing mode. If you feel this is a bad thing, and want to filter ``rx_itemSelected`` to only send ``.Next(false)`` if the table is actually in editing mode, you could probably do this using a combination of ``withLatestFrom`` and ``flatMap``.
