### ISSUE TITLE
Linkage failure after adding rx test

### ISSUE THREAD

**Issue by omerlh** [ReactiveX/RxSwift#485]
Hey
I've just added rx test using pod file to my project, and the linkage start to fail:
````
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/Developer/Library/Frameworks'
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
Now I've checked and bit code is not enabled for our project in all the targets.
I am using xcode 7.2.1, cocoapods 0.39

Could you help? Look like other libraries have similar problems...

Thanks!

**Comment by kzaher** [comment]
Hi @omerlh ,

I believe you should only add RxTests to your test target, and not application target.

**Comment by omerlh** [comment]
That's exactly what I did...

**Comment by kzaher** [comment]
Maybe you could disable bitcode for test target?

**Comment by omerlh** [comment]
bitcode is disabled for all targets...

**Comment by omerlh** [comment]
Hey
I think I've managed to solve it. Rxtest are configured with enablebitcode true, and our project doesn't. I found in stack over flow a [post](http://stackoverflow.com/a/32685434/4792970) that recommend adding the following code to the pod file:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
It simply disable bit code for all the pod projects. I checked, and it is working.

**Comment by kzaher** [comment]
Hi @omerlh ,

glad you were able to solve it. I think that maybe we had some similar question in the past, but couldn't remember.

I guess we can then close this one.

**Comment by omerlh** [comment]
Yeah sure. Might be a good idea to write it down somewhere...
