### ISSUE TITLE
Interview for InfoQ about RxSwift?

### ISSUE THREAD

**Issue by sdesimone** [ReactiveX/RxSwift#486]
First off, apologies for creating an issue about this, but I haven't found a way to get in touch with this project's maintainers.

My name is Sergio De Simone and I use to contribute to InfoQ.com
I would like to cover RxSwift in a short post and it would be great if you could answer a few questions about the project.

Here you have the questions:

**Could you explain what change of perspective Rx programming
  requires? What are its advantages? Any cost?**

**How would you describe RxSwift's level of maturity Do you know of
  any projects using it?**

**What's on RxSwift roadmap?**

**What was you experience implementing Rx in Swift? How did the
  language perform?** (Also, any comparison to other languages that
  you have implemented Rx for?)

Thank you a lot.

Please, if you are willing to do it, get in touch with me at zergyo at gmail dot com

**Comment by kzaher** [comment]
Hi @sdesimone ,

Hope it's ok if we answer to your github email address so we don't spam everybody.
