### ISSUE TITLE
Mock Timer for Unit Tests

### ISSUE THREAD

**Issue by fabb** [ReactiveX/RxSwift#490]
After having tried for quite a time to mock the `Timer` for unit tests, I'd like to ask for some advice on this.

I have the following requirements:
* The type should be `Observable<Int>` (or a subclass)
* Right after allocation, it should not have emitted any events yet (therefore I cannot use `Variable`)
* The mock Timer should have a way to emit the next value to observers at specific lines in unit tests (e.g. a function `mockExecuteOnTick`)

Any suggestions?

**Comment by kzaher** [comment]
Hi @fabb ,

did you take a look at out operator unit tests? They do exactly that. You have `TestScheduler`, `HotObservable`, `ColdObservable`, ....

There is also test example project in RxExample app (`RxExample-iOSTests` directory).

You also have `PublishSubject` .....

**Comment by pangers** [comment]
@fabb 
I wrote a blog post on how to do this.

http://www.pangers.com/blog/2016/3/1/unit-testing-with-rxswift

**Comment by fabb** [comment]
Thank you, I'll check it out!

**Comment by kzaher** [comment]
I think we should be able to close this one.
