### ISSUE TITLE
Connectable observable playground is not working

### ISSUE THREAD

**Issue by omerlh** [ReactiveX/RxSwift#493]
Hey,
I've noticed that this playground is not working - all the methods call are commented, and there is run forever that make the playground hang.
I've started to fix it (remove the run for ever, move method calls to use the example method), but it seem like it will need deeper refactor - especially adding threading synchronization. I've started to play with it a bit to do something like that:
````swift
 example("sampleWithoutConnectableOperators") {
    let int1 = Observable<Int>.interval(RxTimeInterval(1), scheduler: MainScheduler.instance).take(20)
    let secondObservableDispatchGroup = dispatch_group_create()
    
    _ = int1
        .subscribe {
            print("first subscription \($0)")
        }

    delay(5) {
        _ = int1
            .subscribe {
                print("second subscription \($0)")
                
                if $0.isStopEvent {
                    dispatch_group_leave(secondObservableDispatchGroup)
                }
            }
    }

    try! int1.toBlocking().toArray()
    
    dispatch_group_enter(secondObservableDispatchGroup)
    dispatch_group_wait(secondObservableDispatchGroup, DISPATCH_TIME_FOREVER)

}
````
But I am not happy with this approach, and it might be better to implement this using TestScheduler.
So, I would like to know:

- Does this playground is intend not to work? if so, it might be better to remove it or mention it. At least, remove the ```playgroundShouldContinueIndefinitely()``` as the end of file so the playground will not hang. I can send a PR with this if you'd like

- What do you think should be the best approach to fix this playground? There is probably something I've missed as I am very new to RX and swift...

BTW the playground is AWESOME, helped me a lot to understand the concept of RX in swift.

Thank you very much!
Omer

**Comment by kzaher** [comment]
Hi @omerlh ,

below every example there is a commented method call that runs that example. Just uncomment it to run the example.

We can't uncomment all of them at once since all of the outputs would be combined into something that's hard to read.

Maybe I can add additional instructions at the top.

**Comment by omerlh** [comment]
Hi @kzaher 
This really did the trick, but it is really not trivial. I think that adding some instruction would really help with that.
Thanks!

**Comment by kzaher** [comment]
Hi @omerlh ,

I've added instructions to playgrounds in `develop` branch. This will end up in master `branch` soon. Thnx for reporting this inconvenience.

I'm supposing we can probably close this now.

**Comment by omerlh** [comment]
Great, thank you!
