### ISSUE TITLE
UITableView.rx_contentOffset causing EXC_BAD_ACCESS when selecting cells.

### ISSUE THREAD

**Issue by fjcaetano** [ReactiveX/RxSwift#499]
Hi guys, we're using RxSwift 2.2.0, and this issue is causing some weird crashes. The exception always happens when a cell is selected in the tableview.

We have this code that, when removed, stops the crash:

``` swift
    let voidContentOffsetStream = tableView.rx_contentOffset.map { _ in () }
    let search = searchBar.rx_searchTapped.map { _ in () }
    Observable.of(voidContentOffsetStream, search)
      .merge()
      .subscribeNext { [weak self] _ in
        self?.searchBar.resignFirstResponder()
      }.addDisposableTo(disposeBag)
```

I was able to assess that it is the `rx_contentOffset` that is causing the issue, however, removing it from the merge doesn't solve it. The map itself must be removed in order for the crash to stop happening:

``` swift
//    let voidContentOffsetStream = tableView.rx_contentOffset.map { _ in () }
    let search = searchBar.rx_searchTapped.map { _ in () }
    Observable.of(search)
      .merge()
      .subscribeNext { [weak self] _ in
        self?.searchBar.resignFirstResponder()
      }.addDisposableTo(disposeBag)
```

We need to set a delegate for the tableview because our cells have varying sizes. To try and solve this, I've already tried assigning the delegate using the xib, by code and with `rx_setDelegate` with no success.

I have checked our previous code, and this seems to be happening since the version 2.0.0 of the Rx framework.

P.S. We had this same snippet of code in others UIViewControllers and they had to be removed because we checked that they were causing the same issue.

**Comment by kzaher** [comment]
Hi @fjcaetano ,

we have a really similar example in RxExample app called `GitHubSearchRepositoriesViewController.swift`

It has `rx_contentOffset` and uses `rx_setDelegate` and it doesn't cause a crash in our case so there has to be something other at play here.

What is the callstack and message for crash?

**Comment by fjcaetano** [comment]
Hi @kzaher, I'm aware that isn't just the `rx_contentOffset` that is causing the issue. I also have a similar code on other parts of my app and they run without problems. I meant that I was able to drill down on the issue and this was the root cause.

I'll try to find out what, exactly, I'm doing to the tableView that breaks when I use `rx_contentOffset`

**Comment by fjcaetano** [comment]
@kzaher, I tried replicating the error in a new, clean project and it was successful. Next, I tried copying my Podfile to this new project and I found out that it was actually a conflict between two Pods.

If I removed the Taplytics pod, this error does not occur, but when I install their pod, this happens. I'll get in touch with them to try and fix this.

Should I leave this issue open until it's solved?

**Comment by kzaher** [comment]
Thnx @fjcaetano for investigating this,

it saved me bunch of time for sure, and I realistically wouldn't be able to solve anything on my side.

They are doing some swizzling magic :)

```
#1	0x000000010bb201d2 in __34-[TLTableViewDelegate tl_swizzle:]_block_invoke_2 ()
```

I guess if you don't think this is a problem with RxCocoa, it would be great to close it.

If their investigation reveals it's something we are doing wrong on our end, we can reopen this.

**Comment by fjcaetano** [comment]
Yeah, I figured that they ought to do a lot of swizzling to be able to do everything related to A/B testing only by integrating their framework.

I'm closing the issue, but I can keep you updated if you want.

Thank you for your help.

**Comment by kzaher** [comment]
Yeah, sure, keep me updated how this resolves and what were they doing to cause this :)
