### ISSUE TITLE
doOnSubscribe and doOnUnsubscribe?

### ISSUE THREAD

**Issue by JSchaenzle** [ReactiveX/RxSwift#501]
Is there an equivalent of doOnSubscribe and doOnUnsubscribe that can be tacked on to a signal?

**Comment by kzaher** [comment]
Hi @JSchaenzle ,

This is similar to https://github.com/ReactiveX/RxSwift/issues/398

I'm just curios of the context you need `doOnSubscribe` and `doOnUnsubscribe`?

People usually need it to tie lifetime of some external hidden resource with observable sequence lifetime, or debugging.

In case you need it for external resource lifetime, maybe `using` operator is better.
In case you need it for debugging, we do have `debug` operator.

Trying to figure out do we really need to add this convenience functionality.

**Comment by JSchaenzle** [comment]
@kzaher,
Thanks for the response. I am used to ReactiveCocoa and RxJava where I use operators like `doOnSubscribe` and `doOnUnsubscribe` for debugging complex signals. I'm just getting started with RxSwift (and really liking it!) and I didn't realize that the debug operator was a thing. I think that will be exactly what I need. Thanks again for pointing that out to me.

**Comment by lbatteau** [comment]
I like to use `doOnSubscribe` for indicating network activity. When creating an Observable that performs a network request, the subscribe event is the actual start of the request. Hope that makes sense.

**Comment by sergdort** [comment]
Hi, @lbatteau I guess you can use `using` operator or [ActivityIndicator](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Services/ActivityIndicator.swift)
