### ISSUE TITLE
RxDataSources is outdated in the RxExample project

### ISSUE THREAD

**Issue by icanzilb** [ReactiveX/RxSwift#503]
The RxExample code still uses the now deprecated property `cellFactory` (for example: https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/SimpleTableViewExampleSectioned/SimpleTableViewExampleSectionedViewController.swift#L46)

One solution would be to update the files to the latest version from here: https://github.com/RxSwiftCommunity/RxDataSources

But the question is rather - since this is a separate pod why is included as source files in the main repo? This way RxExample will always get out of sync with the pod.

**Comment by kzaher** [comment]
Hi,

These are the reasons. 
* example app is just an example, we aren't shipping it, so there is no reason why we need to be perfectly synchronized with it
* this is a really small amount of code, and it's mostly convenience wrappers. The only real code is difference algorithm. 
* the main purpose of example app is for somebody to be just able to click run and have something running in no time so he can play with the library operators and integrations, I feel that not being able to do that would create too much friction.

So yes, well need to sync it manually from time to time, but don't see that as a big issue IMHO.

**Comment by kzaher** [comment]
Hi,

These are the reasons. 
* example app is just an example, we aren't shipping it, so there is no reason why we need to be perfectly synchronized with it
* this is a really small amount of code, and it's mostly convenience wrappers. The only real code is difference algorithm. 
* the main purpose of example app is for somebody to be just able to click run and have something running in no time so he can play with the library operators and integrations, I feel that not being able to do that would create too much friction.

So yes, well need to sync it manually from time to time, but don't see that as a big issue IMHO.

**Comment by kzaher** [comment]
Hi,

These are the reasons. 
* example app is just an example, we aren't shipping it, so there is no reason why we need to be perfectly synchronized with it
* this is a really small amount of code, and it's mostly convenience wrappers. The only real code is difference algorithm. 
* the main purpose of example app is for somebody to be just able to click run and have something running in no time so he can play with the library operators and integrations, I feel that not being able to do that would create too much friction.

So yes, well need to sync it manually from time to time, but don't see that as a big issue IMHO.

**Comment by kzaher** [comment]
Synchronized with latest version :)
