### ISSUE TITLE
Shouldn't 'rx_enabled' and 'rx_selected' be ControlProperty?

### ISSUE THREAD

**Issue by fjcaetano** [ReactiveX/RxSwift#505]
Both these properties have been declared as `AnyObserver<Bool>` on UIControl+Rx, which means that they are bindable to Observable sequences, but they aren't Observable themselves.

Considering that they could be observed and bindable, shouldn't they be ControlProperty?

**Comment by kzaher** [comment]
Hi @fjcaetano ,

I think that `ControlProperty` only makes sense in situation user can change those values directly using UI interaction without need for programatic plumbing.

`rx_text`
`rx_value`
...

The usual way that I've seen people using that selected/enabled is to use target/action pattern to register for button taps, and then toggle that state.

I don't see `rx_enabled` and `rx_selected` as control values, but rather something equivalent of button title, or background color.

If there is built-in way of using `UIButton` as a checkbox without additional plumbing?

**Comment by fjcaetano** [comment]
@kzaher, your example was perfect. That is exactly how I'm using the `selected` property in the code I'd like it to be of a different type.

I think that what you said about the `ControlProperty` and UI changes makes sense if you're only listening to changes, in which case, it could be a `ControlEvent` as well, instead of `Observable`.

The way I understood the `ControlProperty` type, I thought of it as properties of the UI that you could listen to changes but also change its value (the same as the `text`, and `value` properties you mentioned), mostly because of it it is documented:

> Unit for `Observable`/`ObservableType` that represents property of UI element.

So, considering that my question came to me because not only I'd like to listen to it, but also change it's value maybe by binding it to an Observable, and considering that `enabled` and `selected` are properties of an UI element, I think it only makes sense that they should be `ControlProperty`

**Comment by fjcaetano** [comment]
Btw, I'm also on the slack channel, if you'd like to talk with me through there, my username is **flavo_caetano**

**Comment by kzaher** [comment]
Hi @fjcaetano ,

you don't need `ControlProperty` to use bindings. The reason why "binding" works is because `ControlProperty` is observer, and not vise versa.

Not sure I have much time :), but don't think we are limiting anything with using just `AnyObserver`.

you can still do:

```
mySpecialValue
    .map { ... }
   .bindTo(button.rx_selected)
```

I think we can probably close this one, let me know if you feel there is something else that we need to discuss.

¯\\\_(ツ)\_/¯

**Comment by fjcaetano** [comment]
The way it is limited and the whole point of this issue is that with `AnyObserver` you cannot read value changes. If one would like to listen to state changes of a button, one would have to observe the KVO change, which is more costly and, overall, uglier than using `ControlProperty`, which, btw, is the way we're having do it:

``` swift
someButton.rx_observeWeakly("enabled")
    .flatMap { $0.map { Observable.just($0) } ?? Observable.empty() }
```
