### ISSUE TITLE
Can't use UIBindingObserver

### ISSUE THREAD

**Issue by svyatoslav-reshetnikov** [ReactiveX/RxSwift#510]
Hello,

I try to create sectioned table view and i use your example. I updated RxSwift on 5.3.1. But XCode can't see UIBindingObserver. I use CocoaPods. What could be the problem? Attach screenshot. Thank you.
![2016-02-25 9 52 23](https://cloud.githubusercontent.com/assets/6576845/13312232/f38a9fe2-dba5-11e5-8ff1-c2578c6bf5dc.png)

**Comment by kzaher** [comment]
Hi @svyatoslav-reshetnikov ,

I'm confused, can you paste Podfile maybe? Latest version of RxSwift is 2.2.0

**Comment by svyatoslav-reshetnikov** [comment]
Krunoslav, i use latest version of RxSwift - 2.2.0. This is part of my Podfile:
pod 'RxSwift',    '~> 2.2'
pod 'RxCocoa',    '~> 2.2'
pod 'RxBlocking', '~> 2.2'

I don't understand why my project can't see UIBindingObserver from Pods.

**Comment by sergdort** [comment]
Hi, @svyatoslav-reshetnikov  

I think your Podfile.lock will help more, because it displays the real version of `RxSwift` installed 

Have you tried to look on it?

**Comment by svyatoslav-reshetnikov** [comment]
Hi, @sergdort 
I check my Podfile.lock and it display me that `RxSwift` version is 2.2.0.
  - RxBlocking (2.2.0):
    - RxSwift (~> 2.2)
  - RxCocoa (2.2.0):
    - RxSwift (~> 2.2)
  - RxSwift (2.2.0)

**Comment by sergdort** [comment]
@svyatoslav-reshetnikov 
Does `UIBindingObserver` exist in your `RxCocoa` pod ?

**Comment by svyatoslav-reshetnikov** [comment]
@sergdort 
Yes. Very strange situation for me.

**Comment by sergdort** [comment]
@svyatoslav-reshetnikov 
Does `RxTableViewSectionedReloadDataSource` class comes from [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources) or you just copy-pasted it to your project?

**Comment by kzaher** [comment]
Looks stale ¯\\\_(ツ)\_/¯

**Comment by svyatoslav-reshetnikov** [comment]
@sergdort 
You're right, i just copy-pasted it into my project. I add [https://github.com/RxSwiftCommunity/RxDataSources](RxDataSources) into my podfile and it solved my problem.

Thank you!
