### ISSUE TITLE
Memory leaks in RxExample app

### ISSUE THREAD

**Issue by Shelin69** [ReactiveX/RxSwift#511]
Hello, 
I've been thinking of using RxSwift in my future apps, and so I was testing the performance of it on different iphones and while creating a test app based on your example app I encountered some memory leaks. 
At first I thought that maybe I was doing something wrong, and so I decided to check for memory leaks in your example app, and it happend that it was not only my app that was leaking.

As you can see, this is a check for your example app - specifically your TableView with editing example.
<img width="1279" alt="rxexample_memoryleak" src="https://cloud.githubusercontent.com/assets/6329153/13351089/90d5e82c-dc84-11e5-8a0e-3e292b30b004.png">

Could you maybe tell me what is causing this memory leak and if so, can it be prevented somehow?

**Comment by kzaher** [comment]
Hi @Shelin69 ,

This is not a memory leak, this is lazy loading protocol metadata.

**Comment by Shelin69** [comment]
Oh, ok that explains a lot.
Thank you!

**Comment by Shelin69** [comment]
@kzaher 
Hi,
So I have one more question as I got more into checking of the messages from the intruments. The memory leak happens because there is no free() call for the 
`Protocol * __unsafe_unretained * pSubprotocols = protocol_copyProtocolList(protocol, &numberOfBaseProtocols);`
When I added the free call there was no more warning about memory leak. So I wanted to ask is the missing of the free call intended because if there was a free call later I could encounter some errors? Or is there another explanation for the missing of that operation?

**Comment by kzaher** [comment]
Hi @Shelin69 ,

I think it's fine to free that array since `protocol_copyProtocolList` creates a copy of that array.

That memory is only allocated once per lazy loaded protocol, but I think it would probably make the code behave a little more polite if we added free there.

If you want to make a PR that has that `free` I would be happy to merge it.
