### ISSUE TITLE
string literal for Objective-C selectors is deprecated

### ISSUE THREAD

**Issue by harrylin90** [ReactiveX/RxSwift#517]
It seems that string literal for selectors is deprecated.I found there are two issues that can't be fixed.
In NSOjbect+Rx.swift:
let deallocSelector = "dealloc" as Selector
let rxDeallocatingSelector = RX_selector("dealloc")

**Comment by kzaher** [comment]
Hi @harrylin90 ,

I think that in the worst case we could create some objc method that does that, but I'm assuming there is some easier way to do this.

**Comment by harrylin90** [comment]
@kzaher 
Thanks. Waiting for the solution.

**Comment by harrylin90** [comment]
Hi @kzaher ,
I think I probablely found an easy way. When I looked up Objective-C routine, I found a method:
public func sel_getUid(str: UnsafePointer<Int8>) -> Selector
let deallocSelector = sel_getUid("dealloc")
let rxDeallocatingSelector = RX_selector(sel_getUid("dealloc")).
What do you think?

**Comment by kzaher** [comment]
I think that we should probably wait until new Xcode is published, maybe they'll also deprecate that one :)

Does `NSSelectorFromString` works? Seems to me that it could be the simplest solution if it does.

**Comment by harrylin90** [comment]
It works. Thanks.
