### ISSUE TITLE
Set queuePriority of a NSOperation for a Scheduler.

### ISSUE THREAD

**Issue by jcampbell05** [ReactiveX/RxSwift#518]
Is it possible to set priority of a stream for a scheduler like you would for operations ?

**Comment by kzaher** [comment]
Hi @jcampbell05 ,

there is `OperationQueueScheduler`, just do `observeOn(someOperationQueueScheduler)` and that's it.

You can set priority to `operationQueue` you pass to `OperationQueueScheduler` initializer.

**Comment by kzaher** [comment]
This one should also be resolved.
