### ISSUE TITLE
warning when using rxswift with Carthage

### ISSUE THREAD

**Issue by kkdevenda** [ReactiveX/RxSwift#520]
While running `carthage update` I get the following warning- 
**ld: warning: linking against dylib not safe for use in application extensions**

**ld: warning: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.**

I'm using Xcode 7.2

**Comment by kzaher** [comment]
Hi @kkdevenda ,

that's normal warning because carthage is building RxTests which are dependent on `XCTest`.

**Comment by kzaher** [comment]
I think we can also close this. If this will cause you any problems, please let me know and we can reopen this.
