### ISSUE TITLE
How to use rx_tap to alter Observable<Bool>

### ISSUE THREAD

**Issue by coryoso** [ReactiveX/RxSwift#521]
I'm trying to toggle a Observable<Bool> by a rx_tap signal.

I tried to use flatMap, but that either doesn't work or i'm using it incorrectly. 
```
boolValue.flatMap { value -> value in
    return !value
}
```

Any idea?

**Comment by sergdort** [comment]
Hi @coryoso 
Well, I think your `rx_tap` should be reflection of your `viewModel` behavior

Kind of

```swift 
let flag: Variable<Bool>

button.rx_tap.map{ !flag.value }.bindTo(flag).addDisposable(disposeBag)

```

**Comment by kzaher** [comment]
Hi guys,

there is also a `scan` operator, so something like:

```
button.rx_tap
     .scan(false) { state, _ in 
          !state
     }
     .startWith(false)
```

... should work.

You can also take a look at calculator example in `RxExample` app for further details.
