### ISSUE TITLE
Multiple rowData models in cellFactory

### ISSUE THREAD

**Issue by pavankataria** [ReactiveX/RxSwift#522]
Hi, I'm trying to use the cellFactory property to try and cater for two kinds of models to populate two cells that have been registered. 
Currently cellFactory supports only one model to populate only one registered class.

How can I have a tableview that supports **two tableviewcells in a Reactive setup?**

I understand that I may need to subclass the datasource and do something there, could you perhaps let me know the minimal changes required to get this working?

Thank you
Pavan

**Comment by kzaher** [comment]
Hi @pavankataria ,

probably you are looking for 
```
public func rx_itemsWithCellFactory
```

The most general form is using your custom data source or [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources/) and `public func rx_itemsWithDataSource`.
