### ISSUE TITLE
Official way to perform unit tests with RxSwift

### ISSUE THREAD

**Issue by VictorAlbertos** [ReactiveX/RxSwift#525]
Hi, first of all, thanks for this amazing Rx version of Swift :)

I'm having troubles to find an official way to perform unit tests using RxSwift. RxJava provides [TestSubscriber](http://reactivex.io/RxJava/javadoc/rx/observers/TestSubscriber.html) class to be able to block the thread until onCompleted is called, and some other handy features like built-in assertions. 

The [installation guide](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Installation.md) reflects a dependency called RxTests, which I guess it is meant to be used as a toolkit for unit testing. But I can’t find any documentation about how to use it.

So, which approach should I need to take to perform unit testing with RxSwift?

Thanks!

P.S. Maybe it could be documented a little more?

**Comment by kzaher** [comment]
Hi @VictorAlbertos ,

If you are looking for blocking operators like RxJava has (`toBlocking`), there is RxBlocking project inside of this repo that contains basic blocking operators so you can also use `toBlocking` with RxSwift.

We are using `RxTests` for all of `RxSwift` operator tests so you can take a look at `AllTests-*` target inside the project.

Unit testing can mean really a lot of different things to a lot of different people:
* If you are testing your custom operators -> take a look a built in operator tests in `AllTests-*` target
* If you are testing pure functions that modify the operators -> I guess all the same here
* If you want to test compositions of operators and functions, e.g. entire view models -> you can also test that nicely and in a really visual way by using `RxTests` with small convenience operators (example is located inside `RxExample_iOSTests.swift` and loads with `Rx.xcworkspace` > `RxExample-iOSTests` target)
```
        // expected events and test data
        let (
            usernameEvents,
            passwordEvents,
            repeatedPasswordEvents,
            loginTapEvents,

            expectedValidatedUsernameEvents,
            expectedSignupEnabledEvents
        ) = (
            scheduler.parseEventsAndTimes("e---u1----u2-----u3-----------------", values: stringValues).first!,
            scheduler.parseEventsAndTimes("e----------------------p1-----------", values: stringValues).first!,
            scheduler.parseEventsAndTimes("e---------------------------p2---p1-", values: stringValues).first!,
            scheduler.parseEventsAndTimes("------------------------------------", values: events).first!,

            scheduler.parseEventsAndTimes("e---v--f--v--f---v--o----------------", values: validations).first!,
            scheduler.parseEventsAndTimes("f--------------------------------t---", values: booleans).first!
        )
```

I guess maybe it would make sense to add those links to `README.md`. I can add them for next release if that helps.

**Comment by VictorAlbertos** [comment]
Thanks a lot @kzaher, I will take a look at the resources you have just pointed :)

And maybe it would be a good idea to add those links to the README file, eventually.

**Comment by kzaher** [comment]
Added this to `README.md`

**Comment by tailec** [comment]
Hi @kzaher,

Recently, I've been looking at `RxTests` and your example in `RxExample_iOSTests.swift`.
I noticed that your tests cover enabling user interface elements only.

I've tried to test  `let signedIn: Driver<Bool>` output but I couldn't get any values. Is it even possible?
Probably, I'm doing something wrong :)
