### ISSUE TITLE
Issue with SubscribeOn and ObserveOn

### ISSUE THREAD

**Issue by robertofrontado** [ReactiveX/RxSwift#528]
Hello guys, I'm facing a problem with the threads, I'm subscribing my Observable to a background thread and trying to observes it in the mainThread, but the items emitted by it never reach the subscribeNext

This is my code 

```swift
Observable<Int>.create { subscriber in
            while(true) {
                subscriber.onNext(0)
            }
            return NopDisposable.instance
            }
            .subscribeOn(ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: DispatchQueueSchedulerQOS.Default))
            .observeOn(MainScheduler.instance)
            .subscribeNext { (value) -> Void in
                // Never reached
            }
            .addDisposableTo(DisposeBag())
```

If I removed the subscribeOn, the items reaches the subscribeNext but in the mainThread, so it blocks the UI

```swift
Observable<Int>.create { subscriber in
            while(true) {
                subscriber.onNext(0)
            }
            return NopDisposable.instance
            }
            .observeOn(MainScheduler.instance)
            .subscribeNext { (value) -> Void in
                // Now they do
            }
            .addDisposableTo(DisposeBag())
```

So I want to know how I can subscribeOn in other thread and observerOn in the mainThread and be able to consume the items emitted by the Observable

Thanks

**Comment by kzaher** [comment]
Hi @robertofrontado ,

I had a little wtf moment when I've seen your code and that it doesn't work.

You've made a mistake in the way you are using `DisposeBag`. I suggest finding out more how Rx works in [GettingStarted](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md).

The problem in you code is that you are adding disposable to a dispose bag that has a temporary strong reference on stack and that dispose bag automatically gets released and disposes all of the subscriptions with them.

```
.addDisposableTo(DisposeBag())
```

If you don't want to dispose that subscription and run this **forever**, then do:
```
_ = Observable<Int>.create { subscriber in
            while(true) {
                subscriber.onNext(0)
            }
            return NopDisposable.instance
            }
            .subscribeOn(ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: DispatchQueueSchedulerQOS.Default))
            .observeOn(MainScheduler.instance)
            .subscribeNext { (value) -> Void in
                // Never reached
            }
```

Take a look at RxExample app how dispose bags are used properly.

If you want to generate elements, I would suggest using `generate` operator.

**Comment by robertofrontado** [comment]
@kzaher Thanks,

But my question is, how can I perform some background work, and subscribe in the mainThread with the subscribeOn & observeOn ?

In the examples in [GettingStarted](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Schedulers.md) it says that the observeOn is used to perform work on a different scheduler ?

What should I use in SubscribeOn and ObserveOn ?

I'm using 

```swift
subscribeOn(ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: DispatchQueueSchedulerQOS.Background))

observeOn(MainScheduler.instance)
```

But its not working well, it performs all the work in the mainThread

**Comment by kzaher** [comment]
Hi @robertofrontado ,

Could you please read my last answer again :)

If you need to generate elements use `generate` operator because Rx doesn't know anything about your while loop.

If you want to properly generate some sequence, you should use recursive scheduling on some scheduler (`generate` operator already does that for you) because otherwise when you dispose subscription, you will only block computation results from being observed, and not the real computation.

**Comment by robertofrontado** [comment]
Hi @kzaher 

Thanks for your help :+1:
