### ISSUE TITLE
"import RxSwift" - no such module when opening playground

### ISSUE THREAD

**Issue by mingyeow** [ReactiveX/RxSwift#531]
i am using xcode 7.2.1, and when i open up rx.playground, it says "no such module"

**Comment by mingyeow** [comment]
Playground execution failed: Introduction.xcplaygroundpage:2:8: error: module file was created for incompatible target x86_64-apple-ios9.0: /Users/mingyeowng/Library/Developer/Xcode/DerivedData/RxSwift-hezizvedfdgddggyvrxeuzczkgtl/Build/Products/Debug-iphonesimulator/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule

**Comment by fpillet** [comment]
You need to build the RxSwift-OSX target at least once as the playground is targeting OS X

**Comment by kzaher** [comment]
Hi guys,
I've improved playground documentation, should be better now.

**Comment by mingyeow** [comment]
@kzaher  works now. thanks a lot!
