### ISSUE TITLE
Retry sequence after requesting user input

### ISSUE THREAD

**Issue by Eruhenon** [ReactiveX/RxSwift#538]
Hey, 

I'm quite new to RX and I'm trying to understand how I can continue a task, after an error which requires user input.
A concrete example would be two factor authentication.. We have an auth-service and a protected resource. Logging in, we receive from the auth-service a LOA-2 (username&password used) token. trying to fetch data from the protected resource we receive an error stating we need LOA-3 (two-factor). So we have to get the input from the user, send it to the auth-service, get a new token (LOA-3) und retry our fetch call with the new token.
There are a lot of examples for logins, but I can't wrap my head around continuing a chain, which requires user input.
Any ideas? Thanks

**Comment by kzaher** [comment]
Hi @Eruhenon ,

There is an example in RxExample app regarding how you can transform UIAlertView to observable sequence of chosen results.

```
func promptFor<Action : CustomStringConvertible>(message: String, cancelAction: Action, actions: [Action]) -> Observable<Action>
```

You can create different wrappers for your custom interface where you enter username and password.

I think code should be something like (it's just a sketch):

```
func getResourceFromURL(url: String, token: String) -> Observable<Resource> {
          return networkService.resourceFromURL(url, token: token)
                      .catchError { e in
                             if !e.isAuthenticationError {
                                  return Observable.error(e)
                             } 
                             
                             return promptFor("Enter username and password")
                                   .flatMap(networkService.requestToken)
                                   .flatMap { token in
                                           return getResourceFromURL(url, token)
                                   }
                      }
}
```

**Comment by Eruhenon** [comment]
This looks precisely like what I'm looking for.

Thanks a lot!
