### ISSUE TITLE
puzzled by create method

### ISSUE THREAD

**Issue by kkdevenda** [ReactiveX/RxSwift#542]
The implementation of create method says, "- parameter subscribe: Implementation of the resulting observable sequence's `subscribe` method."

As per my understanding when calling create method I pass the subscribe method (with signature "(AnyObserver<E>) -> Disposable") for my observable as an argument to the create method. I believe I will use this subscribe method for subscribing to the observable. But when I call subscribe method to subscribe to my observable, I am calling a method with different signature. The subscribe method now takes the method "on" as an argument "subscribe(on: (event: Event<Self.E>) -> Void). I was expecting to call the subscribe method that I provided when creating the observable with create method but it's different.

I have looked through different classes and protocols to understand the concept but I'm still unable to get my head around. Can you please help me with this.

**Comment by thanegill** [comment]
Have you read through the [getting started Doc](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#creating-your-own-observable-aka-observable-sequence)?

**Comment by kkdevenda** [comment]
Yes, I have read "Getting started doc". I don't know what I am missing. I have read a lot about RxSwift and Rx, even the documentation available on reactive.io, it will be great if you can help me.

**Comment by kzaher** [comment]
Hi @kkdevenda ,

`(event: Event) -> Void` is the `AnyObserver` that receives events. Hope that helps.

**Comment by thanegill** [comment]
@kkdevenda Can you show what code you do have?
