### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by sebasbad** [ReactiveX/RxSwift#546]
Broken doc link: Serial vs Concurrent Schedulers section refers to an "implicit guarantees" section URL http://guides.rxswift.org/intro/schedulers/GettingStarted.md#implicit-observable-guarantees that doesn't exist

**Comment by bontoJR** [comment]
Hello @sebasbad, [guides.rxswift.org](https://github.com/RxSwiftCommunity/guides.rxswift.org/issues) has its own repository, can you reopen the issue there or eventually a PR fixing the problem? Thanks!

**Comment by sebasbad** [comment]
Done: https://github.com/RxSwiftCommunity/guides.rxswift.org/issues/25. Thnx :)
