### ISSUE TITLE
Code syntax error in Documentation/Examples.md

### ISSUE THREAD

**Issue by dakeshi** [ReactiveX/RxSwift#553]
Hi.

I got a few questions about the sample code in addition to #529.
 
- Simple UI bindings Section

`.map { WolframAlphaIsPrime($0.toInt() ?? 0) }`
`.concat()`
`.map { "number \($0.n) is prime? \($0.isPrime)" }`
 
For Swift2.0 later, `Int($0)` would be correct in the context.
And I was wondering about what is the meaning of `n` and `isPrime`.
Is a kind of property, extensions or one of response value from API?
It is not important part to understand the concept of RxSwift, 
but I think that we need to give more clear example for beginners.
(Assume that WolframAlphaIsPrime is async API name to find out prime number)

- Autocomplete Section
```swift
if username.isEmpty {
    return just((valid: false, message: "Username can't be empty."))
}
```
I think that `just` should be `Observable.just`

`let loadingValue = (valid: nil, message: "Checking availability ...")`

To set `nil` in tuple, we need an additional work.

```swift
typealias LoadingInfo = (valid : String?, message: String?)
let loadingValue : LoadingInfo = (valid: nil, message: "Checking availability ...")
```

**Comment by kzaher** [comment]
Hi @dakeshi ,

we are open for PRs :) Maybe it's easier to solve these issues that way  :)

**Comment by dakeshi** [comment]
Thanks @kzaher. I'll do that.

I'd like to check one more time before sending PRs and it is more natural for me to create issue then make PRs. :smile:
