### ISSUE TITLE
Question: catchErrorJustReturn behavior differences.

### ISSUE THREAD

**Issue by orkenstein** [ReactiveX/RxSwift#562]
Hi there!
I have the following code:
```
Observable<Int>.interval(5.0, scheduler: MainScheduler.instance).filter {
        // Some filtering
      }.flatMapLatest { _ -> Observable<Value> in
        return SomeRxStuff().catchErrorJustReturn(KindaDefaultValue())
      }.map {
        return $0.map
      }.subscribeNext { 
       // do the stuff
      }
```

Which actually... works. Yep, we catch the error produced by `SomeRxStuff()` and the flow continues.
But when `catchErrorJustReturn()` called after `flatMap`:
```
Observable<Int>.interval(5.0, scheduler: MainScheduler.instance).filter {
        // Some filtering
      }.flatMapLatest { _ -> Observable<Value> in
        return SomeRxStuff()
      }.map {
        return $0.map
      }.catchErrorJustReturn(KindaDefaultValue())
      .subscribeNext { 
       // do the stuff
      }
```
... the value get into `subscribeNext` and then the sequence terminates after the first error.
I expect `Observable` not to be terminated in both scenarios. What's the difference?

**Comment by kzaher** [comment]
Hi @orkenstein ,

The behavior is correct. I would suggest reading through [GettingStarted](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md) to understand how RxSwift is working.

**Comment by orkenstein** [comment]
@kzaher thanks for the feedback.

>If you don't know if Observable can fail, you can ensure it can't fail using catchErrorJustReturn(valueThatIsReturnedWhenErrorHappens), but after an error happens the underlying sequence will still complete.

Does it mean, that after error get caught by `catchErrorJustReturn` the sequence will be terminated with `onComplete`?
How can I implement a sequence that will be never terminated by error?

**Comment by kzaher** [comment]
Hi @orkenstein ,

you can use one of the `retry` operators. You've looked for them.

**Comment by kzaher** [comment]
Assuming this is closed.
