### ISSUE TITLE
Typo Bug in release 2.3.1 -  associatedtype Value 

### ISSUE THREAD

**Issue by georgepoenaru** [ReactiveX/RxSwift#571]
Hi, 

I just ruined pod install and after updating to 2.3.1 from 2.3.0 I found a typo that cause build error. The typo can be found in "InvocableType" protocol

There is no "associatedtype" definition in swift. It is "typealias"

Please change from associatedtype to typealias 

![screenshot 2016-03-23 12 37 28](https://cloud.githubusercontent.com/assets/4004883/13984199/014ad2dc-f0f5-11e5-808f-073eaf1f6305.png)

**Comment by sergdort** [comment]
Hi @georgepoenaru what version of swift or Xcode do you have?

**Comment by georgepoenaru** [comment]
Version 7.2.1 (7C1002)

**Comment by georgepoenaru** [comment]
Ok, now I see that is supported in 7.3
