### ISSUE TITLE
rx_tap

### ISSUE THREAD

**Issue by zdenektopic** [ReactiveX/RxSwift#576]
Hello,

I have issue with making `rx_tap` work for network requests repeatedly.
Lets assume we have `UIButton` that is supposed to initiate network request each it is tapped. How would I achieve this? I wasnt able to do it with `map` neither `subscribe` operator :(

**Comment by kzaher** [comment]
Hi @zdenektopic ,

take a look at RxExample app inside this repo.

You can do `pod try RxSwift`, or just clone the repro and run it. It is full of examples like the one you are requesting.
