### ISSUE TITLE
SPM in Ubuntu

### ISSUE THREAD

**Issue by popaaaandrei** [ReactiveX/RxSwift#580]
Dear All, 

I am referencing RxSwift as `.Package(url: "https://github.com/ReactiveX/RxSwift.git", majorVersion: 2)` which resolves in `2.3.1`

Environment is `Ubuntu 15.10, Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75).`

If you know how to fix this please tell me, I want to have a small setup to play with: `Kitura+RxSwift` :)

Thank you,
Andrei

**Comment by kzaher** [comment]
Hi @popaaaandrei ,

we are trying to make make RxSwift at lest exprimentally operational on Linux again. 

Last time it worked was with `February 8, 2016 Snapshot (Swift 2.2)`.

Right now Swift 3.0-dev compiler is shipped to Linux, and it crashes on `ObservableType` definition :)

We've done what we could in `swift-3.0` branch, so if somebody has time to fix the compilation on Linux with `Swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a-ubuntu15.10` or later, we are open to PRs :)

**Comment by kzaher** [comment]
This is being tracked under #846
