### ISSUE TITLE
suggestion for completing a generic map method 

### ISSUE THREAD

**Issue by popaaaandrei** [ReactiveX/RxSwift#586]
Dear All, 

Please help me understand where I'm doing wrong. I have this result datatype called 🍒 which wraps a type and a progress

```
public enum 🍒<T> {
        case Success(T)
        case Progress(CGFloat)
}

class func rx_request(router: Router) -> Observable<🍒<AnyObject>>
```

This `AnyObject` needs to be transformed into a `Mappable` structure (ObjectMapper), so because I have several of these Mappable structs, I wanted to achieve something like this, a generic map that I can use:

```
class func rx_convert<T : Mappable>(value: 🍒<AnyObject>) -> Observable<🍒<T>> {
        
        return Observable.create { observer in
            
            switch value {
            case .Success(let object):
                guard let convertedObject = Mapper<T>().map(object) else {
                    observer.onError(NetworkError.IncorrectDataReturned)
                    return NopDisposable.instance
                }
                
                observer.on(.Next(🍒<T>.Success(convertedObject)))
                observer.on(.Completed)
                
            case .Progress(let progress):
                observer.on(.Next(🍒<T>.Progress(progress)))
                break
            }
            
            return NopDisposable.instance
        }
}
```

It seems the above definition is wrong because this cannot be compiled: `Cannot explicitly specialize a generic function`

```
.flatMapLatest({ _ in
    🐯.rx_request(Router.Pipeline)
})
.flatMapLatest({ result -> Observable<🍒<ResponsePipeline>> in
    🐯.rx_convert<ResponsePipeline>(result)
})
```

What am I doing wrong here?

Andrei

**Comment by kzaher** [comment]
Hi @popaaaandrei ,

1rst: .... omg, my eyes, it burns :)
2nd: This is where your error is ` 🐯.rx_convert<ResponsePipeline>(result)`. Compiler is saying you can't write `rx_convert<ResponsePipeline>`
3rd: why don't you just use `map`?

:beers:

**Comment by popaaaandrei** [comment]
1rst: I know, sorry, it burns my eyes too :(
2nd: This is what happens when one wants to circumvent the learning process of generics :(
3rd: I got to `flatMap` because I wanted to return a specific error if the Mapping could not be done. Conversion can fail, what do you suggest?

1) I can add a conversion error `case` in `enum 🍒`, create a generic map method
2) return `nil` if the conversion fails and further filter `nil` values, which ultimately prohibits me from notifying the user that the backend data is 💩
3) go with `flatMap`

Thank you!
Andrei

**Comment by kzaher** [comment]
You can do things like
```swift
Observable.just(json)
.map(MyOwnObject.parse)
...
```

```swift
struct MyOwnObject {
    static func parse(json: JSON) throws -> MyOwnObject { 
       do {
             // .... bla bla bla parsing
       }
       catch let e {
              throw NetworkError.IncorrectDataReturned(e)
       }
    }
}
```

**Comment by popaaaandrei** [comment]
And if parse function throws error, `map` will pass it along and will be caught in `subscribeError`?

**Comment by kzaher** [comment]
yes
