### ISSUE TITLE
RxCocoa Fail Build with XCode 7.2 and Cocoapod 1.0.0.beta.2

### ISSUE THREAD

**Issue by azizcode** [ReactiveX/RxSwift#592]
Hi everyone i have problem when add RxCocoa in my project with cocoapods. I have configure my podfile like this:

platform :ios, '8.0'
use_frameworks!

target 'CityScan' do

pod 'Cartography', '~> 0.6'
pod 'RxCocoa', '~> 2.0'
pod 'RxSwift', '~> 2.0'
pod 'RxBlocking', '~> 2.0'
pod 'RxTests', '~> 2.0'

end

target 'CityScanTests' do

end

target 'CityScanUITests' do

end

when i am clean and build my project i have some issue which i have no idea how to fix it. My issue seen like this:

<img width="1280" alt="screen shot 2016-04-02 at 1 03 59 am" src="https://cloud.githubusercontent.com/assets/5786359/14215961/6b6c076c-f870-11e5-9ed2-048be86f8e9f.png">

Anyone know how to fix this issue?

**Comment by kzaher** [comment]
Hi @azizcode ,

Version 2.3.1 requires Xcode 7.3 and it would be great to have latest CocoaPods.

**Comment by azizcode** [comment]
thanks @kzaher . I Will try update my xcode and cocoapods on monday.

**Comment by azizcode** [comment]
thanks @kzaher my xcode work great when i am update it and get RXSwift
