### ISSUE TITLE
how to make  bidirectional binding between view and viewmodel use RxSwift

### ISSUE THREAD

**Issue by pengxianhe** [ReactiveX/RxSwift#606]
I know use bindto to bind viewmodel.property and view ，but i did not find 
bidirectional binding method

**Comment by kzaher** [comment]
Hi @pengxianhe ,

please take a look at example app. You can find example of how to do two way binding there.

```swift
infix operator <-> {
}

func <-> <T>(property: ControlProperty<T>, variable: Variable<T>) -> Disposable {
    let bindToUIDisposable = variable.asObservable()
        .bindTo(property)
    let bindToVariable = property
        .subscribe(onNext: { n in
            variable.value = n
        }, onCompleted:  {
            bindToUIDisposable.dispose()
        })

    return StableCompositeDisposable.create(bindToUIDisposable, bindToVariable)
}
```

```
         let sliderValue = Variable<Float>(1.0)
        slider.rx_value <-> sliderValue

        sliderValue.asObservable()
            .subscribeNext { [weak self] x in
                self?.debug("UISlider value \(x)")
            }
            .addDisposableTo(disposeBag)
```

**Comment by pengxianhe** [comment]
OK， I got it

**Comment by riccardo-tesio** [comment]
IMHO this is not a perfect solution. It is elegant and it works, but each event is returned to the sender.
I mean:
property -> updates the variable -> updates the property
and
variable -> updates the property -> updates the variable

I am trying with this implementation: in my app it works, but I am new to Rx and there could be other anomalies:

`func <-> <T>(property: ControlProperty<T>, variable: Variable<T>) -> Disposable {

    var updating = false
    
    let bindToUIDisposable = variable.asObservable().filter({ _ in
        updating = !updating
        return updating
    }).bindTo(property)
    let bindToVariable = property.filter({ _ in
        updating = !updating
        return updating
    }).subscribe(onNext: { n in
        variable.value = n
        }, onCompleted:  {
            bindToUIDisposable.dispose()
    })
    
    return StableCompositeDisposable.create(bindToUIDisposable, bindToVariable)
}
`

Any comment will be appreciated :)

**Comment by anirudhamahale** [comment]
Very nicely demonstrated
https://stackoverflow.com/a/54494020/5744323
