### ISSUE TITLE
How to use Rx_Swift for Local and Push Notifications

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [ReactiveX/RxSwift#610]
How can I implement observable for Local notification and Push notifications when they are received.
In app delegate, We are notify on 

> didReceiveLocalNotification

 and 

> didReceiveRemoteNotification

 How can I listen these notification on other screen? I've used NotificationCenter for notify but now I want to use RX-Swift. I've tried with this way but not working.

```
  extension UILocalNotification {
   var notificationSignal : Observable<UILocalNotification> {
        return Observable.create { observer in
            observer.on(.Next(self))
            observer.on(.Completed)
            return NopDisposable.instance
        }
    }
}
```

**Comment by kzaher** [comment]
Hi @Dhvl-Golakiya ,

We still haven't officially wrapped app delegate. I've seen a repo that wraps app delegate partially `https://github.com/pixeldock/RxAppState/blob/master/Pod/Classes/UIApplication%2BRx.swift`.

You would need to add properties that wrap something like `rx_delegate.observe("application:didReceiveLocalNotification:")` and `rx_delegate.observe("application:didReceiveRemoteNotification:")` to be able to observe remote and local notifications.

**Comment by Dhvl-Golakiya** [comment]
HI, Thanks for reply. I found a solution for that using `PublishSubject`. Thanks once again.
