### ISSUE TITLE
takeUntil canceling before next event

### ISSUE THREAD

**Issue by rodrigoruiz** [ReactiveX/RxSwift#611]
Following a similar example to question 39 here: http://reactivex.io/learnrx/

I'm trying to transforma a method call "search(query: String)" into a sequence of those calls.
They way I'm achieving this is by creating a "Variable" which I update with the "query" value every time 
the "search(query: String)" method is called.

Then I have this in my "init()":
`_ = queryVariable.asObservable().flatMap({ query -> Observable<[JSON]> in
    return self.facebookSearch(query).takeUntil(self.queryVariable.asObservable())
}).subscribeNext({ result in
    if let name = result[0]["name"].string {
        print(name)
    } else {
        print("problem")
    }
})`

If I type "ABC", my "search(query: String)" method will be called 3 times with "A", "AB", "ABC".
That would be mapped to seq(["A", "AB", "ABC"]) with "queryVariable.asObservable()".
Then I'm mapping it to facebook searches (searching people by their names on Facebook).
And with "subscribeNext" I print the name.
If I don't use the "takeUntil", it works as I'd expect, I get 3 sets of results, one for each of my queries("A", "AB", "ABC").

But if I type fast (before Facebook has time to responde to the request), I'd want only one result, for the query "ABC". That's why I added the "takeUntil". With it I'd expect the "facebookSearch(query: String)" call to be ignored when the next "query" comes in, but it is being canceled for the current query, so with this "takeUntil" I end up printing nothing.

Is this a known issue or am I doing something wrong?

**Comment by kkdevenda** [comment]
I think a more useful operator for your use case is `buffer`. You can define a time limit and a number of events limit on the base observable to emit an event. Resulting observer will emit an event whenever either of the two conditions is met first.

https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

In the above mentioned post staltz makes a nice use of buffer to imitate double clicks. I think your case is also similar.

**Comment by kzaher** [comment]
Hi @rodrigoruiz ,

take a look at `flatMapLatest` operator. That operator is designed for that kind of scenarios. There is a lot of places in RxExample app that use it.

```
func search(query: String) -> Observable<[SomethingYouHaveParsed]> {
}

textField.rx_text
    .flatMapLatest(search)
    .subscribeNext { results in
    }
```

As a general rule of thumb is:
* using variables a lot -> probably doing something wrong
* using subscribeNext a lot -> probably doing something wrong

:)

**Comment by kzaher** [comment]
Oh, so I've forgot to answer the original question. There is no issue with takeUntil, variable will emit the initial value immediatelly, and that will cancel your request :)

Yeah, please take a look at flatMapLatest. I guess we should be able to close this one. We can reopen it if you have any followup questions.
