### ISSUE TITLE
Strange TableView delegate behavior

### ISSUE THREAD

**Issue by danieljvdm** [ReactiveX/RxSwift#613]
I'm trying to use `rx_itemsWithCellIdentifier`(which I use successfully in other projects), but for some reason I get an error 
> Value of type `UITableView` has no member `Generator`

Here is my full code:

    import Foundation
    import UIKit 
    import RxSwift
    import RxCocoa

    class ASCTableViewController: UIViewController {

        @IBOutlet weak var tableView: UITableView!
        let viewModel = ASCTableViewViewModel()
        let disposeBag = DisposeBag()
    
        override func viewDidLoad() {
            super.viewDidLoad()
            bindViewModel()
        }
    
        func bindViewModel(){
            viewModel.objects
                .bindTo(tableView.rx_itemsWithCellIdentifier("cell")) { (a,b,c) in
        
                }
        }
    }

When I actually have the block for the method in I get a different error: 
> Extra argument in call

I see the Generator error when I remove the block.

Thanks

**Comment by kzaher** [comment]
Hi @danieljvdm ,

I think that error usually means that you are binding something that is not a collection of elements to items.

Unfortunately Swift compiler doesn't always report a readable error. 

In these scenarios I always annotate types until compiler tells me where is a problem.

Make sure you have something like:

```swift
let items: Observable<[SomeElement]> = .... // notice the Array or some other collection
items.bindTo(tableView.rx_itemsWithCellIdentifier("someCellIdentifier")) { (index: Int, item: Int, cell) in
}
```

**Comment by danieljvdm** [comment]
Thanks, I have got the code compiling now. However, I now get a crash 
>Could not cast value of type 'UITableViewCell' (0x1060d3540) to 'App.MyTableViewCell' (0x104b02e08).

In Line 57 of `UITableView+Rx.swift`

My code is now

    viewModel.models
            .observeOn(MainScheduler.instance)
            .bindTo(tableView.rx_itemsWithCellIdentifier("cell", cellType: MyTableViewCell.self)) { (index, element, cell) in
                print(element)
                cell.model = element
            }
            .addDisposableTo(disposeBag)

**Comment by danieljvdm** [comment]
I've also tried annotating the types of the index, element, and cell and it makes no difference. The block even recognizes `cell` as `MyTableViewCell`

**Comment by danieljvdm** [comment]
Ok that was a stupid bug - switched projects and forgot to update the class in IB. My bad! When working with Rx I just start assuming all my bugs are because I don't understand it haha. You can close this :)

**Comment by lowki93** [comment]
Hello,
i can't understand, this are good, but rx_itemsWithCellIdentifier is deprecated on swift3.0

    var cars: Variable<[CarViewModel]> = Variable((UIApplication.shared.delegate as! AppDelegate).cars)
    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.estimatedRowHeight = 80

        self.cars.asObservable()
            .bindTo(tableView.rx_itemsWithCellIdentifier("CarCell", cellType: CarTableViewCell.self)) { (a,b,c) in

        }
    }

After changes, 
    var cars: Variable<[CarViewModel]> = Variable((UIApplication.shared.delegate as! AppDelegate).cars)
    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.estimatedRowHeight = 80

        self.cars.asObservable().bindTo(self.tableView.rx.items("CarCell", cellType: CarTableViewCell.self)) { (index, carViewModel: CarViewModel, cell) in
            cell.carViewModel = carViewModel
            }.addDisposableTo(disposeBag)
    }

i had ```extra argument in call```with ```tableView.rx.items("CarCell", cellType: CarTableViewCell.self)````
Can you help me please

**Comment by dejanjevtic87** [comment]
Try with:

`tableView.rx.items(cellIdentifier: "CarCell", cellType: CarTableViewCell.self)`
