### ISSUE TITLE
Carthage framework.zip in releases

### ISSUE THREAD

**Issue by rskuja** [ReactiveX/RxSwift#627]
Can you please add RxSwift.framework.zip to new releases so when we update we don't have to compile it but carthage can download the framework. Thanks!

**Comment by DenHeadless** [comment]
I believe Apple recommends against using prebuilt binaries until Swift 3.0 is released. From Xcode 7.2 release notes:

> The Swift debugger can crash when stopping in code that depends on a Swift library or framework that has been distributed in binary form.
Frameworks written in Swift should be compiled from source as part of the same project that depends on them to guarantee a single, consistent compilation environment. (22492040)

https://developer.apple.com/library/mac/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc7_release_notes.html#//apple_ref/doc/uid/TP40001051-CH5-SW1

**Comment by rskuja** [comment]
This crash was fixed on Xcode 7.3 , there is still some issues going on, but at least its not crashing.

**Comment by kzaher** [comment]
Hi @rskuja ,

I'm unsure how safe is this. Do we have some official information from Apple regarding should we do this.

I mean, I don't have a problem in doing this, but I'm not sure can this break someone's system in production.

May I ask that problem are you experiencing?

I understand that when Carthage builds for all platforms that is extremely slow, but you usually need to use only one platform (--platform iOS).

And updating your dependencies isn't often, right?

**Comment by rskuja** [comment]
Thats all correct. We have a lot of dependencies and iOS/Mac project in the same xcode project so its quite a lot of compiling/updating for us. Your concerns are okey, lets wait for 3.0 release.
