### ISSUE TITLE
subscribeNext getting called on completed?

### ISSUE THREAD

**Issue by dtartaglia** [ReactiveX/RxSwift#642]
let stream = PublishSubject<Int>()
    let trigger = PublishSubject<Void>()
    stream.sample(trigger).subscribeNext { value in print("value \(value)") }
    stream.onNext(5)
    trigger.onCompleted()

The above prints "value 5" to the console. I find that surprising since I never called `onNext()` on the trigger. Is this a bug or expected behavior?

**Comment by dtartaglia** [comment]
Okay, I see from the [marble diagram](http://reactivex.io/documentation/operators/sample.html) that this is expected behavior.

Is there a way I can avoid printing "value 5" in the above?

**Comment by kzaher** [comment]
Hi @dtartaglia ,

I think this was part of operator description.

You can always do

```
stream.sample(trigger.concat(Observable.never())).subscribeNext { value in print("value \(value)") }
```

I'm assuming that original decision was made because it's easy to change behavior if that isn't wanted, and in case it didn't emit that element on completed, it would be harder to change termination behavior without creating a new operator.

We've just made it compliant with other implementations.

**Comment by dtartaglia** [comment]
@kzaher Thanks for the idea, but it didn't work. `concat`ing the `Observable.never()` to the call did stop the `completed` event, but the `onNext` still got called.

IE:

	func add(proposedTodo: RxSwift.Observable<Todo>, saveTrigger: RxSwift.Observable<Void>) {
		let todoToSave = proposedTodo.sample(saveTrigger)
		let test = todoToSave.debug("Todo \(unsafeAddressOf(todoToSave))")
		test.subscribeNext { todo -> Void in
			print("subscribeNext called")
		}.addDisposableTo(disposeBag)
	}

The above produces this output:
Todo 0x7ae69460 -> subscribed
Todo 0x7ae69460 -> Event Next(Todo(id: <__NSC...-28 11:57:27 +0000))
subscribeNext called
Todo 0x7ae69460 -> Event Completed


	func add(proposedTodo: RxSwift.Observable<Todo>, saveTrigger: RxSwift.Observable<Void>) {
		let todoToSave = proposedTodo.sample(saveTrigger).concat(Observable.never())
		let test = todoToSave.debug("Todo \(unsafeAddressOf(todoToSave))")
		test.subscribeNext { todo -> Void in
			print("subscribeNext called")
		}.addDisposableTo(disposeBag)
	}

the same code with concat(Observable.never()) produces this output:
2016-04-28 07:58:59.591: Todo 0x7af89690 -> subscribed
2016-04-28 07:59:06.576: Todo 0x7af89690 -> Event Next(Todo(id: <__NSC...-28 11:58:59 +0000))
subscribeNext called

This might be a bug?

**Comment by kzaher** [comment]
Hi @dtartaglia,

take a look at my example, the `concat` is on trigger itself, not on `sample` result :)

**Comment by kzaher** [comment]
¯\\\_(ツ)\_/¯

**Comment by dtartaglia** [comment]
Thanks for the help @kzaher. That fixed my problem just in time for presenting a cycle.js sort of solution in iOS
