### ISSUE TITLE
Make function 'installDelegate' in DelegateProxyType.swift public

### ISSUE THREAD

**Issue by smumryak** [ReactiveX/RxSwift#645]
It should be great to have possibility to implement forwarding delegates for users custom classes if they are using proxy delegates.

**Comment by sergdort** [comment]
Hi, @smumryak , 
For the most of extensions there is `rx_setDelegate` so you probably could use it.

**Comment by smumryak** [comment]
Hey, @sergdort!
I guess I didn't explained my concern well enough. I need to implement `rx_setDelegate` for my custom class or for some system class (in my case - WKWebView) and I just cant because `installDelegate`, which is used to implement `rx_setDelegate` for UIScrollView, UITableView, etc. extensions, is private

**Comment by kzaher** [comment]
Hi guys,

I'll try to revise polish that interface a bit before making it public. It is little ugly right now. But yeah, we could make this public.

**Comment by kzaher** [comment]
This should be solved.
