### ISSUE TITLE
How to bind rx_tap with viewmodels ? 

### ISSUE THREAD

**Issue by vishal91** [ReactiveX/RxSwift#653]
Hi 

 Have functions in viewmodel which return Observable<Void> . How to subsribe these functions to rx_tap event.

**Comment by kzaher** [comment]
Hi @vishal91 ,

please take a look at [examples](https://github.com/ReactiveX/RxSwift/tree/master/RxExample/RxExample/Examples) inside [RxExample](https://github.com/ReactiveX/RxSwift/tree/master/RxExample) app. There are a lot of simple real world examples how to use this library, including the ones you are asking for.
To run them, just open [Rx.xcworspace](https://github.com/ReactiveX/RxSwift/tree/master/Rx.xcworkspace), chose `RxExample-iOS` target and hit run.
If you are using `CocoaPods` you can also just write `$ pod try RxSwift`, chose `RxExample-iOS` target and hit run.

It is important to note that to use this library efficiently, you need to understand the underlying Rx abstraction of observable sequences. If you are having issues understanding the Rx abstraction of observable sequences, please take a look at [GettingStarted.md](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md).

If you are having troubles understanding how particular operators work, we've tried to demonstrate them in [Rx.playground](https://github.com/ReactiveX/RxSwift/tree/master/Rx.playground) and there are also [operator unit tests](https://github.com/ReactiveX/RxSwift/tree/master/Tests/RxSwiftTests/Tests).

It would be great to ask questions like this on http://stackoverflow.com/ tagged with `rx-swift`. We have recently hooked up http://stackoverflow.com/questions/tagged/rx-swift rss feed to our slack channel to increase chances of your stackoverflow questions getting answered. We are hoping this would make the process of asking these kinds of questions and getting an answer more streamlined.
To increase the chances of getting your question answered, please try to sketch your question as short code snippet and explain the context:
* what are you trying to accomplish
* what is the broader context why are you trying to do this
* what is the problem you are currently having that's preventing you from solving it
* what potential solutions have you tried

We also have an awesome slack channel [![Slack channel](http://slack.rxswift.org/badge.svg)](http://slack.rxswift.org) [Join Slack Channel](http://slack.rxswift.org/), so maybe you can also find help there.

**Comment by kzaher** [comment]
¯\\\_(ツ)\_/¯
