### ISSUE TITLE
Value of type 'UITextField' has no member 'rx_text'

### ISSUE THREAD

**Issue by denis631** [ReactiveX/RxSwift#655]
Hello everybody!
I've decided to start learning Rx and I've downloaded the RxCocoa and RxSwift using CocoaPods.
Unfortunately it doesn't work ;( It can not find the `rx_text` extension of the `UITextField`, even though the file `UITextField+Rx.swift` is the there. What am I doing wrong ?

<img width="1512" alt="screen shot 2016-04-29 at 23 49 05" src="https://cloud.githubusercontent.com/assets/6100421/14930545/12a463d0-0e65-11e6-9fa4-044947f37159.png">

**Comment by Succete** [comment]
import RxSwift
import RxCocoa

**Comment by denis631** [comment]
I swear it didn't work yesterday. I've tried that before, but now it works ... Well, I feel very silly, but this works, so thank you :)

**Comment by Succete** [comment]
@denis631 You're welcome. It sometimes happens, don't mind.

**Comment by shengyang998** [comment]
Already changed to UITextField().rx.text
