### ISSUE TITLE
How to stop observable if subscriber is disposed ?

### ISSUE THREAD

**Issue by Oyashirox** [ReactiveX/RxSwift#667]
First, thanks for your work, it's incredibly useful !

I want to create a simple reactive method to unzip a file, and be notified of the progress. I'd also like that if the caller is disposed, the task that is executed on the background thread stops. 

I'm using SSZipArchive which has a simple blocking call. Here's my code so far :

```swift
var unzipProgressSubject : PublishSubject<Progress>?
    
    func unzipFile(filePath: String) -> Observable<Progress> {
        if let subject = unzipProgressSubject where !subject.disposed {
            subject.dispose()
        }
        
        unzipProgressSubject = PublishSubject()
        
        let unzipObservable = Observable<Progress>.create { observer in
            let unzipPath = Helper.getCacheDir()
            
            SSZipArchive.unzipFileAtPath(filePath, toDestination: unzipPath, delegate: self)

            observer.onCompleted()
            return NopDisposable.instance
        }
        
        let mergeObservable = Observable.of(unzipProgressSubject!, unzipObservable).merge(maxConcurrent: 2)
        
        return mergeObservable
    }
    
    //MARK: - Zip Delegate
    @objc func zipArchiveProgressEvent(loaded: UInt64, total: UInt64) {
        let done = loaded == total
        unzipProgressSubject?.on(.Next(Progress(bytesRead: loaded, contentLength: total, done: done)))
        
        if done {
            unzipProgressSubject?.on(.Completed)
        }
    }
```

Question 1 : In order to send progress, I use a subject that is called in the delegate callback. To emit all progress values (from the delegate) and the completed call (from the end of the observable), I use the merge operator. First problem here : if I use `Observable.of(unzipProgressSubject!, unzipObservable)` it seems to work (I receive progress values), but with `Observable.of(unzipObservable, unzipProgressSubject!)` the subscriber never receives .Next event, even if the delegate method is really called. I am using it wrong ? I also feel like using the subject is not the best practice in this case, but it's the only thing I can think of.

Question 2 : As the title says : How to stop observable if subscriber is disposed ? In RxJava, the observer has a `isUnsubscribed` property, si if it's true, there's no use continuing the work. Is there an equivalent with RxSwift ? 

I'm a completely new user of Reactivex and non native english speaker, so I may not use the correct terms, sorry.

**Comment by kzaher** [comment]
Hi @Oyashirox ,

If you want to get information is subscription disposed, you can get it this way:

```swift
Observable.create { (observer: AnyObserver<Something) in
       let disposable = AnonymousDisposable {
       }

       // ....
       print("Is disposed: \(disposable.disposed)")
       // ...

       return disposable
}
```

I'm unsure how to use this information to cancel `SSZipArchive.unzipFileAtPath`.

You can use RxSwift to cancel operations that have cancellable interface or use scheduling to perform work.

**Comment by Oyashirox** [comment]
Thanks for your reply, I'll try as soon as possible.

There is a `zipArchiveShouldUnzipFileAtIndex` callback, So I think I'll keep a reference to the AnonymousDisposable in my class, and check its disposed property in the callback.

Do you have any idea why the order in `Observable.of` matters ?

**Comment by kzaher** [comment]
The order matters because everything is executing synchronous and in first case:

* you are first unzipping, and after that finishes you start observing
*and in the other case you first setup the observer, and then start unzipping.

**Comment by kzaher** [comment]
We should be able to close this one probably.

¯\\\_(ツ)\_/¯
