### ISSUE TITLE
UIControl.rx_value should be public

### ISSUE THREAD

**Issue by amarcadet** [ReactiveX/RxSwift#681]
Hi,

I am developing a custom UIControl and wanted to add some nice RX touch on it.
Unfortunately I can't do something like this (code below) because `UIControl.rx_value` is not declared as `public`.

```swift
class PickerButton: UIControl {}

extension PickerButton {
    /**
     Reactive wrapper for `TouchUpInside` control event.
     */
    var rx_tap: ControlEvent<Void> {
        return rx_controlEvent(.TouchUpInside)
    }
    
    /**
     Reactive wrapper for `value` property.
     */
    public var rx_value: ControlProperty<PickerButtonValue> {
        return UIControl.rx_value( // error here: "Type 'UIControl' has no member 'rx_value'"
            self,
            getter: { slider in
                slider.value
            }, setter: { slider, value in
                slider.value = value
            }
        )
    }
}
```

What do you think about allowing external access to `UIControl.rx_value`?

By the way, thanks for all your hard work and contributions to the Swift community :)

**Comment by sergdort** [comment]
Hi, @amarcadet 

I guess you can use `ControlProperty` or `ControlEvent`

**Comment by kzaher** [comment]
Hi @amarcadet ,

Yes, the method you wanted to use was private because it's internal convenience method.

You can create your own more pretty version like this:

```swift
extension UIControl {
    static func valuePublic<T, ControlType: UIControl>(control: ControlType, getter:  ControlType -> T, setter: (ControlType, T) -> ()) -> ControlProperty<T> {
        let values: Observable<T> = Observable.deferred { [weak control] in
            guard let existingSelf = control else {
                return Observable.empty()
            }
            
            return existingSelf.rx_controlEvent([.AllEditingEvents, .ValueChanged])
                .flatMap { _ in
                    return control.map { Observable.just(getter($0)) } ?? Observable.empty()
                }
                .startWith(getter(existingSelf))
        }
        return ControlProperty(values: values, valueSink: UIBindingObserver(UIElement: control) { control, value in
            setter(control, value)
        })
    }
}
```

The reason why we have this internal version is because of performance optimizations, but you shouldn't notice any significant difference if using the proposed solution.

**Comment by amarcadet** [comment]
Thanks @kzaher for the snippet, works like a charm!
I close the issue since my problem is solved.

However, why don't you offer something like that as part of RxCocoa for subclassing purposes?

**Comment by kzaher** [comment]
Because shipping convenience methods is usually a bad idea :) If for no other reason, then because of backwards compatibility.

**Comment by amarcadet** [comment]
Thanks for your answer, you made a good point and I understand the motivation behind it.
