### ISSUE TITLE
Is it possible to only using RxSwift and RxCocoa with Carthage?

### ISSUE THREAD

**Issue by zhigang1992** [ReactiveX/RxSwift#682]
Compiling all is a bit slow.
Also, user can want to put the `RxBlocking` and `RxTest` in `Cartfile.private`.
But keep `RxSwift` and maybe `RxCocoa` in the actual `Cartfile`.

Thoughts?

**Comment by kzaher** [comment]
Hi @zhigang1992 ,

I'm not sure why this is a problem, we create new releases once a month. 

I think that you probably can't specify using Carthage which targets to build, but I could be wrong about this. As far as I can tell the way you do this in Carthage is to not integrate `RxTests` and `RxBlocking`.

Is there something we can set in `Cartfile` to help you?

**Comment by zhigang1992** [comment]
Is mostly because of the build time for Carthage update.
Not just when the project is integrating with rxswift, also if we are integrating say RxDataSource, which is dependent on RxSwift, is also needs to build all the targets in Rx.xcworkspace.
Even with --platform iOS, it's still quiet slow. :sad:
Thoughts?

**Comment by zhigang1992** [comment]
It's mostly because of the build time for Carthage update.
Not just when my project integrate with rxswift, also when it integrates with say RxDataSource.
It will build all the targets in Rx.xcodeproject twice with in one Carthage update 
It's pretty slow even with --platform iOS
To be honest, I don't actually have a solution to it. I was hoping maybe you guys knows a bit more about it.
:(

**Comment by zhigang1992** [comment]
https://github.com/Carthage/Carthage/issues/1227
Guess it's a no.
:(

**Comment by kzaher** [comment]
¯\\\_(ツ)\_/¯

**Comment by caoer** [comment]
With the newer version, it might be possible: 
⚠️ Carthage will only consider targets that support the archive action. (#2507 & #2515) ⚠️

https://github.com/Carthage/Carthage/pull/2507
https://github.com/Carthage/Carthage/issues/2515

@zhigang1992 @kzaher

**Comment by freak4pc** [comment]
That’s not “a possibility” since it means choosing one which isn’t relevant :)
