### ISSUE TITLE
UISwitch.on does not produce element

### ISSUE THREAD

**Issue by NicolasRiviere** [ReactiveX/RxSwift#690]
Hello !

When i click on my switch, the next element (bool) is produced and visible in my debugger output.
But if i set programmatically the state of my switch, no element is produced and nothing is logged.

```
mySwitch.rx_value.subscribeNext { (next) in
            print(next)
        }.addDisposableTo(disposeBag)

mySwitch.on = true //Nothing visible in my debugger
```

The next element "true" should be emitted, no ? Am i missing something ?

Thank you for your help !
Nicolas

**Comment by tarunon** [comment]
Hi @NicolasRiviere ,
`ControlProperty` would not observe programatic changes.
You could bind with `Variable` and change value using `Variable`.

```swift
let switchValue = Variable(false)
(mySwitch.rx_value <-> switchValue)
  .addDisposableTo(disposeBag)
switchValue.asObservable()
  .subscribeNext { (next) in
    print(next)
  }
  .addDisposableTo(disposeBag)

switchValue.value = true 
```

Please refer to these discussions, I think these would useful for you. (#551, #471)

**Comment by NicolasRiviere** [comment]
Thank you very much for your help @tarunon !
