### ISSUE TITLE
collection zip not work fine 

### ISSUE THREAD

**Issue by kaich** [ReactiveX/RxSwift#694]
I write code like as below In my view model.

```
  Observable.create({ (observer) -> Disposable in
            fileUploadArray.map({ UIImageJPEGRepresentation($0 , 0) })
                .map ({ (data) -> Observable<String>  in
                   return Observable.create({ (o) -> Disposable in
                        dispatch_after(3, dispatch_get_main_queue(), {
                            NSLog(self.description)
                            o.onNext("100")
                        })

                        return NopDisposable.instance
                   })
                })
                .zip({ $0 })
                .subscribe({ (event) in
                    NSLog("get result")
                })
                .addDisposableTo(self.disposeBag)

            return NopDisposable.instance
        })
```

Everytime `o.onNext("100")` excuted. It works fine and outputs `get result` when i add `NSLog(self.description)` . But It doesn't work when I remove code 'NSLog(self.description)'. I don't understand it. Something released ? Who can help me.

**Comment by FengDeng** [comment]
please try this
          
          fileUploadArray.map({ UIImageJPEGRepresentation($0 , 0) })
                .map ({ (data) -> Observable<String>  in
                   return Observable.create({ (o) -> Disposable in
                        dispatch_after(dispatch_time(DISPATCH_TIME_NOW,3 * Int64(NSEC_PER_SEC)), dispatch_get_main_queue(), {
                            o.onNext("100")
                        })
                        return NopDisposable.instance
                   })
                })
                .zip({ $0 })
                .subscribe({ (event) in
                    NSLog("get result")
                })
                .addDisposableTo(self.disposeBag)

**Comment by kaich** [comment]
@FengDeng  thanks , I know yours code works fine. But I want create a obsevable that publish a whole message when upload images of message complete. I change my code style. It works fine. For my code , I want to know the reason of it not  work fine.

**Comment by FengDeng** [comment]
@kaich I think it is not Rx error.,and not NSLog(self.description).  maybe  because 3 != dispatch_time(DISPATCH_TIME_NOW,3 * Int64(NSEC_PER_SEC))

**Comment by kzaher** [comment]
This works as far as I can tell.

```swift
[Observable.just(1), Observable.just(2), Observable.just(3)].zip { $0 }
    .subscribe { e in
        print(e)
    }
```

This isn't a good pattern in general:

```swift
 Observable.create({ (observer) -> Disposable in
                 .....
                .subscribe({ (event) in
                    NSLog("get result")
                })
                .addDisposableTo(self.disposeBag)

            return NopDisposable.instance
        })
```

https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md

Maybe you've meant?

```swift
Observable.deferred {
            return fileUploadArray.map({ UIImageJPEGRepresentation($0 , 0) })
                .map ({ (data) -> Observable<String>  in
                   return Observable.create({ (o) -> Disposable in
                        dispatch_after(3, dispatch_get_main_queue(), {
                            NSLog(self.description)
                            o.onNext("100")
                        })

                        return NopDisposable.instance
                   })
                })
                .zip { $0 }
}
```

**Comment by kaich** [comment]
@kzaher thank you. Yes, you are right. my code pattern is not good. The `deferred` method  is that I want. I have a better understanding of rx.
