### ISSUE TITLE
I want to make a observer and observable. and them don't dispose when Next(error).Do you think is it necessary?

### ISSUE THREAD

**Issue by FengDeng** [ReactiveX/RxSwift#695]
All in title.

**Comment by kzaher** [comment]
Hi @FengDeng ,

I'm not sure I understand the question.

¯\\\_(ツ)\_/¯

**Comment by FengDeng** [comment]
Hi @kzaher ,
I am sorry,my english is very poor.
I want i can receive nextValue after error.

**Comment by DianQK** [comment]
Hi @FengDeng ,
As we know, after call `onError`... , they will be disposed.

But I think you can try this:

```swift
enum MyResult<T> {
  case Success(T)
  case Failure(ErrorType)
}
```

then.. call `onNext(MyResult.Success(value))`  or `onNext(MyResult.Failure(error))`.

**Comment by FengDeng** [comment]
Hi @DianQK ,
It's a good idea!
But i don't want to switch...and catch errors in another way.
I create my observer and my observable,
I want to know RxSwift will complete this?or it is extra?

**Comment by kzaher** [comment]
When you are sending error, that means that you want to complete sequence with error. 
At that moment the disposable that you have returned from Observable.create lambda will be disposed automatically.

**Comment by FengDeng** [comment]
@kzaher,
perhaps i don't want to complete sequence with error^_^
Sometime I just want to complete my sequence when i give it completed command.and i could  receive any errors.
Perhaps it's a not especially good design that errors also call func dispose .

**Comment by guitarkitten** [comment]
just wrap the value and the error your observable will send into a Result enum, then you can just handle the enum, think the normal value and the error your observable sends as a whole.
