### ISSUE TITLE
Trying to open Playground freezes Xcode

### ISSUE THREAD

**Issue by plm75** [ReactiveX/RxSwift#704]
Steps to reproduce:

1. clone repo
2. open workspace in Xcode 
3. wait for Xcode to finish indexing
4. build target "RxSwift - OSX"
5. select Rx playground in the file navigator: TOC appears in the main screen but so does to colour spinner -> Xcode freezes

As a "bonus", after a force quit, Xcode reopens to playground on restart and freezes again.  Only solution is to delete the repo ...

Xcode 7.3.1
OSX 10.11.5

**Comment by HaloWang** [comment]
Same problem😷

**Comment by kzaher** [comment]
Hi guys,

Any idea what's causing this? Can't repro this.

Can you maybe try ...

```
rm -rf Rx.xcworkspace
rm -rf Rx.xcodeproj
rm -rf Rx.playground
git checkout .
```

**Comment by scotteg** [comment]
Also, did you try deleting derived data? If neither of these suggestions help, could each of you provide details about your Mac configuration (** > About This Mac > Overview > System Report**, and copy the **Hardware Overview** section)?

**Comment by plm75** [comment]
@kzaher , @scotteg  
I tried @kzaher 's instructions, but same result.
@scotteg : yes, I tried several times after deleting derived data but no luck.

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,2
  Processor Name:	Intel Core i5
  Processor Speed:	2,5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP102.0106.B0A
  SMC Version (system):	2.6f59
  Serial Number (system):	xxxxx
  Hardware UUID:	xxxxxxxxxxx
  Sudden Motion Sensor:
  State:	Enabled

**Comment by plm75** [comment]
@kzaher , @scotteg , @HaloWang 

OK, I just retried after disabling all my Xcode plugins and it works ... I'll close the issue and will put another comment when I have time to pinpoint which plugin is causing that in case someone else has the same problem in the future.

 Sorry for the trouble.

@HaloWang : please feel free to re-open if this does not work for you

**Comment by plm75** [comment]
So in my case, Playground is working again after I removed the Xvim plugin
