### ISSUE TITLE
Version numbers in info.plist are not consistent with current tag

### ISSUE THREAD

**Issue by amarcadet** [ReactiveX/RxSwift#707]
Current tag is `2.5.0` and current [info.plist](https://github.com/ReactiveX/RxSwift/blob/5293690a61b14785aa8407ea9bbd1864499d73df/RxSwift/Info.plist#L17-L18) files are `2.0.0`.

**Comment by kzaher** [comment]
Hi @amarcadet ,

good point. I think we would want to add check for that to `./scripts/pre-release-tests.sh`.

**Comment by kzaher** [comment]
Pushed fix for this yesterday. 

This should be fixed in `develop` branch, and we'll update those versions with next release.

**Comment by amarcadet** [comment]
Thanks
