### ISSUE TITLE
CloudKit??

### ISSUE THREAD

**Issue by kristofer** [ReactiveX/RxSwift#709]
I am beginning to work with RxSwift and was wondering if there is an "RxCloudKit"? I see RxRealm, which I suspect will be handy, but obviously when one fetches the cloudkit records one needs, they come back in an async manner...

any pointers?

**Comment by kzaher** [comment]
.... as far as I can tell, not .... yet. ¯\\\_(ツ)\_/¯

**Comment by kzaher** [comment]
I think we can close this one.
