### ISSUE TITLE
Why two way binding operator does not lead to endless loop?

### ISSUE THREAD

**Issue by leizh007** [ReactiveX/RxSwift#716]
I read the two way binding operator in sample code of RxSwift.
```
func <-> <T>(property: ControlProperty<T>, variable: Variable<T>) -> Disposable {
    let bindToUIDisposable = variable.asObservable()
        .bindTo(property)
    let bindToVariable = property
        .subscribe(onNext: { n in
            variable.value = n
        }, onCompleted:  {
            bindToUIDisposable.dispose()
        })

    return StableCompositeDisposable.create(bindToUIDisposable, bindToVariable)
}
```
When property changed, it will notify variable, and set the variable's value, while the variable's value is set, it will notify the property. I think it will lead to endless loop... So why endless loop didn't happen?

**Comment by kzaher** [comment]
Hi @leizh007 ,

Because `ControlProperty` doesn't fire in case of programmatic updates.

**Comment by leizh007** [comment]
@kzaher  Thanks for your answer. Is that mean: when I changed the variable's value, then it changes the property's value through bindTo method. That change won't emit signals to the property's subscriber?  Only the user changed the property's value through UI interface can fire the `ControlProperty` to emit signals?
