### ISSUE TITLE
why convert type error?

### ISSUE THREAD

**Issue by JxbSir** [ReactiveX/RxSwift#719]
I copy it from your demo project.  But I can not build it successfully.  please see the picture below.  Please help.

![1 pic](https://cloud.githubusercontent.com/assets/9983806/15627710/f5e4b094-251e-11e6-940a-1f73bda805f7.jpg)

**Comment by JxbSir** [comment]
I already import this three library

import RxSwift
import RxCocoa
import RxBlocking

**Comment by sergdort** [comment]
Hi, @JxbSir  try to manually specify types in the closures

sometimes Swift compiler don't understand them 😀

kinda :

```Swift

Observable.combineLatest(userValid, passwordValid) { userName, password -> Bool in
     return userName && password
}

```

**Comment by JxbSir** [comment]
![2 pic](https://cloud.githubusercontent.com/assets/9983806/15627831/15eda96e-2523-11e6-8bff-d3e27abf62e9.jpg)

**Comment by JxbSir** [comment]
Still not work

**Comment by sergdort** [comment]
Hm.. why does it complain on `&&` operator ?

**Comment by JxbSir** [comment]
I don't know, I can not understand why it cannot convert from Bool to Bool?

**Comment by nero-tang** [comment]
@JxbSir It's because ```user_rx``` and ```pass_rx``` are optional. If you can make sure those textfields are not optional then simply change the code into:
```swift
let user_rx = txtUser!.rx_text.map{ $0.characters.count >= 6 }.shareReplay(1)
let pass_rx = txtPwd!.rx_text.map{ $0.characters.count >= 6 }.shareReplay(1)
```
Otherwise,
```swift
let user_rx = txtUser?.rx_text.map{ $0.characters.count >= 6 }.shareReplay(1) ?? Observable.just(false)
let pass_rx = txtPwd?.rx_text.map{ $0.characters.count >= 6 }.shareReplay(1) ?? Observable.just(false)
```

**Comment by Jameson-zxm** [comment]
because of txtUser? and txtPwd? is Option i think。

**Comment by sergdort** [comment]
Yes, guys you right 👍 

`user_rx` is `Observable<Bool>?`

**Comment by JxbSir** [comment]
OK, I just started using Rx..., thank you guys for helping
