### ISSUE TITLE
Could not build Objective-C module 'RxCocoa'

### ISSUE THREAD

**Issue by phuna** [ReactiveX/RxSwift#728]
*Short description*:

 - Can't build with error `'RxCocoa/RxCocoa.h' file not found` & `could not build Objective-C module 'RxCocoa'`

*Code that reproduces the issue*:

 - Minimum project which I've just created which imports RxSwift & RxCocoa: 

https://github.com/phuna/test-build-rxcocoa-error
 - Pod file content:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestBuildError' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'

  # Pods for TestBuildError

end
```

*Xcode version*:

  7.3.1 (7D1014)

*Expected outcome*:

  - Can build project successfully
  - Code completion should show suggestions

*What actually happens*:

 - Build turns to error as soon as I import `RxCocoa` in `ViewController.swift`, import only `RxSwift` makes build success
 - Code completion doesn't work. I must type this manually from start to end and no suggestion appears
```
Observable<Int>.interval(0.5, scheduler: MainScheduler.instance).subscribeNext { _ in
        }
```

*Installation method*:
  (so we don't waste time investigating an incorrect integration)
  * CocoaPods (I'm using v1.0.1)

*I have multiple versions of Xcode installed*:
  (so we can know if this is a potential cause of your issue)
  * no

*Level of RxSwift knowledge*:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  * I have a small code base

**Comment by phuna** [comment]
Bump. Anyone?
I've search around and can see that some people are having the same problem, but most of the answers/solutions are to:
- Set flag `use_frameworks!` which I already set
- Clear Derived data
- Change scheme to library, build it then change scheme back to project then build it

I tried them all but still got the same error. Sample project above is a minimum Single View IOS App, I just created it and add `RxSwift` & `RxCocoa`, nothing else.
Sorry if this is not the place for this question, if so please let me know. I'm stuck at this.
Thank you

**Comment by kzaher** [comment]
Hi @phuna ,

I'm unsure what is causing this. I've experienced this once, and the only way to solve it was.

* Remove Pods directory and *.xcworkspace (`mv Pods ~/.Trash; mv *.xcworkspace ~/.Trash`)
* Remove all derived data
* `pod install`

**Comment by kzaher** [comment]
If you can repro this, maybe sending CocoaPods team a snapshot of the repo could them troubleshoot this issue.

**Comment by phuna** [comment]
Thanks @kzaher,  I don't have access to computer now so I'll try your suggestion later.

**Comment by phuna** [comment]
@kzaher : It's strange, I tried the minimum project again on another machine and it works. It seems that my Pod env has something wrong.
Thank you for your support, I think this can be closed.

**Comment by kzaher** [comment]
@phuna please send this repro to CocoaPods team so they can fix this :)

**Comment by kzaher** [comment]
It looks like this is not a CocoaPods issue, but Xcode issue.

Just happened to me. To resolve it I've had to:
* close Xcode 
* manually remove entire derived data dir **while Xcode is turned off** */Users/{User}/Library/Developer/Xcode/DerivedData*

**Cleaning the project from Xcode doesn't help**

**Comment by phuna** [comment]
Thanks @kzaher , I can't reproduce problem now but noted for next time :)

**Comment by jibeex** [comment]
@kzaher Kzaher's solution is great. It almost solved my problem. Buuildt I need also 

- remove the **Build** folder manually

before rebuild the project. Then it works like a charm.

**Comment by appsonite** [comment]
Thanks @kzaher your solution worked :)

**Comment by acevif** [comment]
Thanks @kzaher your solution worked for me too :)
