### ISSUE TITLE
Why 3 frameworks?

### ISSUE THREAD

**Issue by tcurdt** [ReactiveX/RxSwift#732]
Did I miss the docs or why are there 3 frameworks? RxBlocking, RxCocoa and RxSwift?

**Comment by tcurdt** [comment]
To clarify: I understand that RxBlocking is for testing and RxCocoa is the Cocoa specific part - but unless I missed this that's not to be found and should be part of the install instructions.

**Comment by fpillet** [comment]
Because RxCocoa can't work on Linux atm.

**Comment by tcurdt** [comment]
@fpillet that's all good and nice - but it's not explained or even mentioned in the install docs.

**Comment by fpillet** [comment]
That's correct, guess we could add more information about this. Only mention is in the installation instructions here https://github.com/ReactiveX/RxSwift#manual but not really explained.

The UI specific portion of RxSwift will remain separated from the core.

**Comment by tcurdt** [comment]
Yes, I guess I would add it to the carthage section which frameworks need to be added to the project.
The cocoapods instructions kind of suggest that - but it's really not clear.
