### ISSUE TITLE
DistinctUntilChanged vs Distinct - better docs

### ISSUE THREAD

**Issue by tcurdt** [ReactiveX/RxSwift#733]
Linking to http://reactivex.io/documentation/operators/distinct.html for docs is not so great. The details on `distinctUntilChanged` are "TBD". Only once you dig deeper you find that it only looks at the previous key.

**Comment by kzaher** [comment]
Hi @tcurdt ,

any suggestions how to improve this?

**Comment by tcurdt** [comment]
If you can it I would be a bit clearer [here](http://reactivex.io/documentation/operators/distinct.html):

> In some implementations there are variants that allow you to adjust the criteria by which two items are considered “distinct.” In some, there is a variant of the operator **"distinctUntilChanged"** that only compares an item against its immediate predecessor for distinctness , thereby filtering only consecutive duplicate items from the sequence.

and I would fix the "TBD" in the language specific information.

**Comment by kzaher** [comment]
Oh, I think this is an issue for https://github.com/ReactiveX/reactivex.github.io/issues

**Comment by kzaher** [comment]
Don't think this is issue in this repo, so closing this out, maybe somebody will have time to update the docs on `reactivex.github.io`
