### ISSUE TITLE
TextField Two Way Binding Issue: when keyboard is dismissed, values change to empty.

### ISSUE THREAD

**Issue by ShaneQi** [ReactiveX/RxSwift#737]
I wanted to bind a UITextField and a Variable\<String\>, when I try to use the '<->' operator, a issue came up: when I dismiss the keyboard (with `self.view.endEditing(true)`), the textField text and the binded variable change to "". I don't think this is a normal behavior.

'<->' operator is from here, the issue also comes from here:
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift

Then I added a dismiss keyboard tap gesture into the RxSwift example, it has the same issue:

![2016-06-09 16_00_44](https://cloud.githubusercontent.com/assets/7324708/15946200/5b4b3f30-2e5b-11e6-8967-c208ff3d6a33.gif)

I looked into it: when the keyboard is dismissed, the `beginningOfDocument` of textInput is kind of a `nil`, so that the `guard` statement let the function return nil: 

```swift
func nonMarkedText(textInput: UITextInput) -> String? {
    let start = textInput.beginningOfDocument
    let end = textInput.endOfDocument

    guard let rangeAll = textInput.textRangeFromPosition(start, toPosition: end),
        text = textInput.textInRange(rangeAll) else {
            return nil
    }
...
}
```
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift#L23-L26

**Comment by kzaher** [comment]
Hi @ShaneQi ,

:(

I have no idea why that is `nil` sometimes.

The patch for this is simple, just adding `if nonMarkedTextValue != nil && nonMarkedTextValue != variable.value {`, **but this is not a proper solution ofc**.

```swift
func <-> (textInput: RxTextInput, variable: Variable<String>) -> Disposable {
    let bindToUIDisposable = variable.asObservable()
        .bindTo(textInput.rx_text)
    let bindToVariable = textInput.rx_text
        .subscribe(onNext: { [weak textInput] n in
            guard let textInput = textInput else {
                return
            }

            let nonMarkedTextValue = nonMarkedText(textInput)

            if nonMarkedTextValue != nil && nonMarkedTextValue != variable.value {
                variable.value = nonMarkedTextValue ?? ""
            }
        }, onCompleted:  {
            bindToUIDisposable.dispose()
        })

    return StableCompositeDisposable.create(bindToUIDisposable, bindToVariable)
}
```



does anybody have an idea why this is `nil`, is this an Apple bug?

**Comment by kzaher** [comment]
Hi @ShaneQi ,

changes that work are pushed to `master` branch. Could you verify the fix maybe?

Unsure, can we improve this.

**Comment by ShaneQi** [comment]
Hello @kzaher ,

I tried and it works well now. Thanks for the fixing! 

I will close this issue.
