### ISSUE TITLE
Documentation on iBeacon

### ISSUE THREAD

**Issue by DenisLaboureyras** [ReactiveX/RxSwift#744]
Hi guys,

I've submitted my app this week and received a request from Apple on how I use beacons and stuff. I searched a reference in my code for methods (startMonitoringForRegion, ...) they were looking for and find out that RxCocoa is referring to these methods.

The last question of Apple is this one : "If this app uses 3rd party SDKs for iBeacons, please provide links to their documentation showing that background location is required for it to function."

Is there a link in your documentation that answering Apple's question ? If not can you create one for me please :) ?

And by the way, your framework rocks ! I use it in Java, Swift and JS, it's a key component in my project.

Kind regards,
Denis

**Comment by kzaher** [comment]
Hi @DenisLaboureyras ,

I don't think we have any special documentation except inline one. We've just created simple extensions for `CLLocationManager`.

**Comment by DenisLaboureyras** [comment]
OK thanks for your answer.
That's what I told the Apple review team, and my app passed the submission review :)

I'm closing the issue!
