### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by mgetzbw** [ReactiveX/RxSwift#746]
Currently there is no support for Swift 3 and XCode 8, this prevents downstream projects from upgrading when XCode 8 goes GA

**Comment by kzaher** [comment]
Hi,

we've played with Swift 3 branch, but yes, it's probably still not working with Xcode 8.

https://github.com/ReactiveX/RxSwift/tree/swift-3.0

**Comment by kzaher** [comment]
Ups, opened #753, forgot about this one.
