### ISSUE TITLE
Custom NSControl and how to make rx_ property

### ISSUE THREAD

**Issue by uros-gardasevic** [ReactiveX/RxSwift#748]
On my way to making custom NSControl i realised i wouldn't be able to use NSControl.rx_value class function, and even if i opt for moving that code into accessible scope, still the ControlTarget would be unreachable.

Considering the situation where you have NSControl subclass which has property of type T, how would you go around it and make two way bindable rx_property?

Thanks.

**Comment by kzaher** [comment]
Hi @uros-gardasevic ,

I think this is a dupe of #681.

**Comment by uros-gardasevic** [comment]
You're right, exactly what i was looking for.
#681 looks quite similar to what i initially intended to ask, but i refrained because i'm sure public interface is the way it is for a good reason.

Thanks for your answer, and keep on with the good RX work.
