### ISSUE TITLE
rx_response and error: memory read failed for

### ISSUE THREAD

**Issue by croccio** [ReactiveX/RxSwift#749]
*Short description*:

  When i use rx_response i get "error: memory read failed for" if son i big. see example in answer below

*Xcode version*:

  7.3.1

with 1.9.0 version of rxLibrary and Xcode 7.0 is all ok, no problem. i don't know if the cause is Xcode or newer version of library.

*Expected outcome*:

  nonsuccess should be called

*What actually happens*:

  crash "error: memory read failed for"

*Installation method*:
  (so we don't waste time investigating an incorrect integration)
  * CocoaPods

*I have multiple versions of Xcode installed*:
  (so we can know if this is a potential cause of your issue)
  * no

*Level of RxSwift knowledge*:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  * I have a significant code base
```
```
    func getBpeShops(latitude: Double, longitude: Double, radius: Int, category: WindroseShopCategory?, var chainCode: String?) -> Observable<WindroseShop> {
        
        
        if nil == chainCode {
            chainCode = "CC"
        }
        
        var request = getRequest(GetBPEShops(latitude: latitude, longitude: longitude, radius: radius, chainCode: chainCode!))
        
        if nil != category && category != WindroseShopCategory.TUTTE {
            request = getRequest(GetBPEShops(latitude: latitude, longitude: longitude, radius: radius, category: category!, chainCode: chainCode!))
        }
        
        return urlSession.rx_response(request)
            . debug("getBpeShops")
            . observeOn(doOnBackgroundThread())
            . map { (data, response) in
                let httpResponse = response as! NSHTTPURLResponse
                switch httpResponse.statusCode {
                case 200:
                    return try WindroseShop(data: data)
                case 401:
                    throw NoBaseAuth(serviceResponse: response)
                default :
                    throw RequestError(responseCode: httpResponse.statusCode, url: (httpResponse.URL?.absoluteString)!)
                }
        }
    }
```

**Comment by croccio** [comment]
i think the problem is big json

**Comment by croccio** [comment]
here you are a json that fails and a json that success. there is a service that give me them, so they're same response, one bigger one smaller. with version 1.9.0 i don't have any problem. i did update to last and i get that error. i've Xcode 7.3.1 

[json.zip](https://github.com/ReactiveX/RxSwift/files/318654/json.zip)

**Comment by croccio** [comment]
anyone can help me?

**Comment by kzaher** [comment]
Hi @croccio ,

could you please fill out this template, so somebody will have a better chance of helping you.

https://raw.githubusercontent.com/ReactiveX/RxSwift/64e40ef604ff7c42747b0bbf82bd18942feba33b/Documentation/IssueTemplate.md

**Comment by croccio** [comment]
@kzaher done

**Comment by croccio** [comment]
it's a problem of last version. with 1.9 i don't have any problem

**Comment by kzaher** [comment]
Hi @croccio ,

I think you are missing the most important part, self contained code that reproduces the issues.
Unless we have that, I'm not sure there is a way we can help you on this.

**Comment by croccio** [comment]
@kzaher i've updated it.

it doesn't enter in map.

i've tried with last version of rx swift and Xcode 7.0.1 and no crash. it could be Xcode 7.3.1 problem?

here a summary of combination:
xcode 7.0.1 + rxswift 1.9 = no crash
xcode 7.3.1 + rxswift 1.9 = crash
xcode 7.0.1 + rxswift 2.5 = crash
xcode 7.3.1 + rxswift 2.5 = crash

**Comment by kzaher** [comment]
Hi @croccio ,

I think we would need some kind of small code sample that is self contained (so we can run it and reproduce the issue), otherwise I'm not sure there is much we can do here.

**Comment by kzaher** [comment]
If we don't have a good repro case, we can't do much, sorry.

**Comment by croccio** [comment]
here example. is on all ViewController.swift

please help me

[Test.zip](https://github.com/ReactiveX/RxSwift/files/376049/Test.zip)

**Comment by kzaher** [comment]
Hi @croccio ,

I don't think this is problem with Rx.

If you change code in your view controller to this

```
return urlSession.rx_response(request)
            //. debug("getBpeShops")
            . observeOn(backgroundScheduler)
            . map { (data, response) in
                let httpResponse = response as! NSHTTPURLResponse
                switch httpResponse.statusCode {
                case 200:
                    return try WindroseShop(data: data)
                case 401:
                    throw NoBaseAuth(serviceResponse: response)
                default :
                    throw RequestError(responseCode: httpResponse.statusCode, url: (httpResponse.URL?.absoluteString)!)
                }
        }
```

... it will work.

I've tried to dig in why `debug` operator was failing, and it seems that the problem is converting element to string.

If you add this code to NSURLSession+Rx.swift

```
                 guard let httpResponse = response as? NSHTTPURLResponse else {
                    observer.on(.Error(RxCocoaURLError.NonHTTPResponse(response: response)))
                    return
                }
                // insert this code
                let element: (NSData, NSHTTPURLResponse) = (data, httpResponse)
                let value1 = "\(data)" // this doesn't crash
                let value2 = "\(httpResponse)" // this doesn't  crash
                let debugDescription = "\(element)" // this crashes the program, have no idea why
                print(debugDescription)
```

**Comment by croccio** [comment]
it fail only when json is large. with small json not crash.

thank you :)
