### ISSUE TITLE
UITableView .bindTo.rx_itemsWithCellIdentifier "Extra argument in call"

### ISSUE THREAD

**Issue by pluckq** [ReactiveX/RxSwift#752]
Hello, so im new in RX, and trying bind data, that i map from API, my code looks like: 
`let disposeBag = DisposeBag()
        Network.request(.getMyTrainings())
        .mapObject(GroupTrainings)
            .bindTo(tableView.rx_itemsWithCellIdentifier("cell", cellType: UITableViewCell.self)) { (index, element, cell) in
                print(element)
            }
            .addDisposableTo(disposeBag)`

And there a error "Extra argument in call".

Please help me, how i can do things right, with easy style like that?

**Comment by kzaher** [comment]
Hi @pluckq ,

seen the issue, I was thought of adding some examples to inline documentation to improve this. Let's leave this open until I add those.
