### ISSUE TITLE
How to cache using concat

### ISSUE THREAD

**Issue by indiche** [ReactiveX/RxSwift#754]
Hello

I'm trying to implement caching method described [here](http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/) in RxSwift, but I'm failing to do so. I already read https://github.com/ReactiveX/RxSwift/issues/303, but I still don't understand how can I implement behaviour described in that post.

Let's say I have something like this:

```swift

import RxSwift
import RxAlamofire

protocol Cache<T> {
   let data: T
   var isValid: Bool
}

class FavoritesRespository {
    private let disposeBag = DisposeBag()
    private let favoritesSubject = BehaviourSubject<[Favorite]>(value: [])
    private let favoritesCache: Cache<[Favorite]>

   func observeFavorites() -> Observable<[Favorite]> {
        updateFavoritesIfNeeded()
        return favoritesSubject
   }

   private func updateFavoritesIfNeeded() {
         Observable.of(memory, network)
            .single { $0.isValid }
            .map { $0.data }
            .subscribeNext(self.favoritesSubject.onNext)
            .addDisposableTo(disposeBag)
   }

   private var memory: Observable<Cache<[Favorite]>> {
       return Observable.just(favoritesCache)
   }

   private var network: Observable<Cache<[Favorite]>> {
        return request(getFavorites)
            .map { responseToCache($0) }
            .doOnNext { newCache in
                self.favoritesCache = newCache
            }
   }
}
```

I would like to avoid triggering of network request if memory data is valid. As I understood from https://github.com/ReactiveX/RxSwift/issues/303 I would have to create new observable, and wrap RxAlamofire method in it. Can it be done without creating new observables?

Also, is there a cleaner way to do what I'm doing with BehaviourSubject? Idea is to have one method that will return shared stream to all subscribers, but for every new subscriber it will try to fetch new data and send new value if needed.

**Comment by kzaher** [comment]
Hi @indiche ,

we have some image caching examples in RxExample app, so maybe you can check those out.

If you want to do it with `concat`, I think you can conceptually do something like:

```swift
Observable.of(
     memory, 
     network.subscribeOn(CurrentThreadScheduler.instance) // `subscribeOn(CurrentThreadScheduler.instance)` is here so you can cancel scheduling of network operation in case something is returned from memory
)
            .concat()
            .take(1)
```
