### ISSUE TITLE
Catch up a little bit with macOS bindings and RxCocoa in general.

### ISSUE THREAD

**Issue by bontoJR** [ReactiveX/RxSwift#759]
The current version of RxCocoa is highly focusing on iOS, so macOS seems totally ignored, it would be good to catch up a little bit with some more bindings. :)

P.S. I can happily do that on the free time :)

**Comment by kzaher** [comment]
Hey,

yeah, seen the PR, let's maybe keep these improvements on hold until we fully transition to Swift 3.0 :).

If you have time it would be great if you could help with Swift 3.0 first, and then we can think about macOS maybe :)

**Comment by dseehof** [comment]
Hi,

is this still on the agenda of enhancements. Especially an addition for NSTableView would be quite useful - similar to what exists for UITableView. Is anyone maybe already working on that?

**Comment by kzaher** [comment]
Hi @dseehof ,

I have a fairly limited knowledge of OSX. I've tried to take a look once, but it looks like OSX is completely different beast then iOS family.

I'm also curios has anyone attempted to wrap them.

**Comment by kzaher** [comment]
I think we can improve OSX support, but let's open issue per specific extension. Otherwise it's too chaotic.
