### ISSUE TITLE
viewmodel not disposed of with the following operation

### ISSUE THREAD

**Issue by grangej** [ReactiveX/RxSwift#762]
I have observable that appears to be preventing the release of the viewModel / causing a crash. I also use this pattern elsewhere so i'm wondering if there is something I am doing wrong here. If I comment out this code the viewModel is properly disposed of and everything is fine. I am using local scope so as far as I can tell no use of self was harmed in the making of this function ;)

`    private func setupModalObservables() {
        
        let storage = self.storage
        
        let didBecomeActive = self.didBecomeActive.distinctUntilChanged()
        
        let notifications = self.notifications.distinctUntilChanged { (lhs, rhs) -> Bool in
            
            return lhs == rhs
        }
        
        RxSwift.Observable.combineLatest(didBecomeActive, notifications) { (activeViewModel, notifications) -> RxSwift.Observable<[NotificationEntity]> in
            
            
            return storage.rx_backgroundCreateOperation({ (context, save) -> [NotificationEntity] in
                
                var updatedNotifications: [NotificationEntity] = [NotificationEntity]()
                
                for notificationEntity in notifications {
                    
                    if let notification: Notification = try context.fetch(Request<Notification>().filteredWith("id", equalTo: notificationEntity.id)).first {
                        
                        
                        notification.notificationState = NotificationState.Read

                        updatedNotifications.append(notification.mapEntity())
                    }
                    
                }
                
                save()
                
                return updatedNotifications
            })
            
        }.switchLatest().debug().subscribeNext { (notifications) in
            
            Logger.logLevelVerbose.log("Marked read for (\(notifications.count)) notifications", logPrefix: "NotificationsViewModel")
            
        }.addDisposableTo(self.disposeBag)
    }`

**Comment by kzaher** [comment]
Hi @grangej ,

I don't see anything obvious in this code example that would cause a leak. Maybe the real leak is somewhere else.

If there is some small **self contained code sample** that we can run that demonstrates the leak in the library, we can ofc investigate it, otherwise I'm not sure there is much we an do here.

**Comment by kzaher** [comment]
@grangej try to use the `debug` operator, maybe it will help you figure things out.

**Comment by kzaher** [comment]
Not much we can do here.
