### ISSUE TITLE
takeUntil does not stop on .Completed

### ISSUE THREAD

**Issue by macdrevx** [ReactiveX/RxSwift#763]
According to http://reactivex.io/documentation/operators/takeuntil.html,

> The TakeUntil subscribes and begins mirroring the source Observable. It also monitors a second Observable that you provide. If this second Observable emits an item **or sends a termination notification**, the Observable returned by TakeUntil stops mirroring the source Observable and terminates.

(emphasis mine)

The following test attempts to verify that `takeUntil(_:)` stops mirroring the source when the second observable emits `.Completed`, however the test fails:

    func testTakeUntilCompleted() {
        let testScheduler = TestScheduler(initialClock: 0)
        let events: [Recorded<Event<Int>>] = [completed(65)]
        let testObservable = testScheduler.createColdObservable(events).asObservable().debug("test observable")

        let res = testScheduler.start { Observable<Int>
            .interval(10, scheduler: testScheduler).debug("interval")
            .takeUntil(testObservable).debug("takeUntil")
        }

        let correctEvents = [
            next(210, 0),
            next(220, 1),
            next(230, 2),
            next(240, 3),
            next(250, 4),
            next(260, 5),
            completed(265)
        ]

        XCTAssertEqual(res.events, correctEvents)
    }

Here's an abbreviated log output:

```
takeUntil -> subscribed
test observable -> subscribed
interval -> subscribed
interval -> Event Next(0)
takeUntil -> Event Next(0)
interval -> Event Next(1)
takeUntil -> Event Next(1)
interval -> Event Next(2)
takeUntil -> Event Next(2)
interval -> Event Next(3)
takeUntil -> Event Next(3)
interval -> Event Next(4)
takeUntil -> Event Next(4)
interval -> Event Next(5)
takeUntil -> Event Next(5)
test observable -> Event Completed
test observable -> disposed
interval -> Event Next(6)
takeUntil -> Event Next(6)
interval -> Event Next(7)
takeUntil -> Event Next(7)
…
interval -> Event Next(77)
takeUntil -> Event Next(77)
interval -> Event Next(78)
takeUntil -> Event Next(78)
takeUntil -> disposed
interval -> disposed

error: -testTakeUntilCompleted : XCTAssertEqual failed: ("[Next(0) @ 210, Next(1) @ 220, Next(2) @ 230, Next(3) @ 240, Next(4) @ 250, Next(5) @ 260, Next(6) @ 270, Next(7) @ 280, Next(8) @ 290, Next(9) @ 300, Next(10) @ 310, Next(11) @ 320, Next(12) @ 330, Next(13) @ 340, Next(14) @ 350, Next(15) @ 360, Next(16) @ 370, Next(17) @ 380, Next(18) @ 390, Next(19) @ 400, Next(20) @ 410, Next(21) @ 420, Next(22) @ 430, Next(23) @ 440, Next(24) @ 450, Next(25) @ 460, Next(26) @ 470, Next(27) @ 480, Next(28) @ 490, Next(29) @ 500, Next(30) @ 510, Next(31) @ 520, Next(32) @ 530, Next(33) @ 540, Next(34) @ 550, Next(35) @ 560, Next(36) @ 570, Next(37) @ 580, Next(38) @ 590, Next(39) @ 600, Next(40) @ 610, Next(41) @ 620, Next(42) @ 630, Next(43) @ 640, Next(44) @ 650, Next(45) @ 660, Next(46) @ 670, Next(47) @ 680, Next(48) @ 690, Next(49) @ 700, Next(50) @ 710, Next(51) @ 720, Next(52) @ 730, Next(53) @ 740, Next(54) @ 750, Next(55) @ 760, Next(56) @ 770, Next(57) @ 780, Next(58) @ 790, Next(59) @ 800, Next(60) @ 810, Next(61) @ 820, Next(62) @ 830, Next(63) @ 840, Next(64) @ 850, Next(65) @ 860, Next(66) @ 870, Next(67) @ 880, Next(68) @ 890, Next(69) @ 900, Next(70) @ 910, Next(71) @ 920, Next(72) @ 930, Next(73) @ 940, Next(74) @ 950, Next(75) @ 960, Next(76) @ 970, Next(77) @ 980, Next(78) @ 990]") is not equal to ("[Next(0) @ 210, Next(1) @ 220, Next(2) @ 230, Next(3) @ 240, Next(4) @ 250, Next(5) @ 260, Completed @ 265]") - 
```

Is this a bug or expected behavior?

**Comment by macdrevx** [comment]
Looking at `TakeUntilSinkOther._synchronized_on(_:)`, the `.Completed` case is handled differently than `.Next` and `.Error`. In particular, nothing is forwarded to the parent other than setting its `_open` flag, which doesn’t seem to ever be read: https://github.com/ReactiveX/RxSwift/blob/6df77da4745338fa13986d044f6b764af4c3d99f/RxSwift/Observables/Implementations/TakeUntil.swift#L37

Could this be the source of the problem?

**Comment by kzaher** [comment]
Hi @macdrevx ,

As far as I can tell `completed` event shouldn't do anything, and the current behavior is correct.

`takeUntil` means, take until `other` sequence produces an element. If `other` sequence completes, it won't ever produce an element or event, so no synchronization is needed.
If `other` sequence errors out, composition should error out.

If `other` sequence completes, that means it won't ever produce any element, so we don't need to synchronize `other` and source sequence anymore.

There is a slight optimization that is not being performed, and it can for sure.

```
class TakeUntilSink<ElementType, Other, O: ObserverType where O.E == ElementType>
    : Sink<O>
    , LockOwnerType
    , ObserverType
    , SynchronizedOnType {

....
    func on(event: Event<E>) {
         if _open {
              _synchronized_on(event: event) 
         }
         else {
          synchronizedOn(event)
         }
    }
....
```

**Comment by macdrevx** [comment]
@kzaher thanks for the quick reply. I'm a bit confused though, because that behavior seems to contradict what's prescribed by http://reactivex.io/documentation/operators/takeuntil.html:

> If this second Observable emits an item or sends a termination notification, the Observable returned by TakeUntil stops mirroring the source Observable and terminates.

**Comment by macdrevx** [comment]
Doesn't `.Completed` constitute sending a termination notification?

**Comment by macdrevx** [comment]
@kzaher for comparison, the RxJava implementation terminates mirroring when `other` emits `completed`: https://github.com/ReactiveX/RxJava/blob/fef520ee5570e3af48fab0fd55f255a39a1ffd70/src/main/java/rx/internal/operators/OperatorTakeUntil.java

**Comment by kzaher** [comment]
@macdrevx Thnx for finding that out from RxJava code. I've checked RxJS and it has our behavior.

I think all libraries are trying to converge, but it's a process :)

¯\\\_(ツ)\_/¯

**Comment by macdrevx** [comment]
Thanks @kzaher. I was also looking at this with @tomburns who pointed out that the C# implementation works like RxSwift too according to their [docs](https://msdn.microsoft.com/en-us/library/hh229530(v=vs.103).aspx), so maybe it's the documentation on http://reactivex.io/documentation/operators/takeuntil.html and the RxJava implementation that is unexpected.

**Comment by c0diq** [comment]
FYI ReactiveSwift is following RxJava implementation. What would be the operator that would terminate a new subscription immediately if another observable completed?
