### ISSUE TITLE
Provide prebuilt binaries

### ISSUE THREAD

**Issue by alejandro-isaza-hs** [ReactiveX/RxSwift#764]
RxSwift takes a long time to build and this slows down the development process. It would be great if it provided prebuilt binaries. See https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by kzaher** [comment]
Hi @alejandro-isaza-hs ,

we will start bundling prebuilt binaries when there is at least some hint of ABI stability. I think we'll probably start to do that with releases of RxSwift 3.0.

**Comment by kzaher** [comment]
I think we can close this for now since we can't fulfill this in near time frame. We can reopen this if there will be some hints of ABI stability.
