### ISSUE TITLE
cannot insert integers in flatMapLatest {}

### ISSUE THREAD

**Issue by rcholic** [ReactiveX/RxSwift#765]
I have a variable named `triggerRefresh` that is a `PublishSubject` type, which triggers an API call for fetching list of questions by pagination/pagesize. Below is the relevant part of my code:
```
var pageSize = 20
var curPage = 1
var results: Driver<[Question]>

init(provider: MyAPI) {
  results = triggerRefresh.startWith(())
            .flatMapLatest {
                provider.request(.GetQuestionByPagination(self.pageSize, self.curPage))
                    .retry(3)
                    .observeOn(MainScheduler.instance)
                    .trackActivity(activityIndicator)
        }
}
```
The weird errors I got in XCode 7.2 is: `Variable 'self.results' used before being initialized`, however, if I replace the variables `self.pageSize, self.curPage` with their numerical values, the error is gone. Does anyone know what might be wrong?

**Comment by jsslai** [comment]
Instance properties must be initialised before you can access them in Swift. So results property must be initialised before you access pageSize or curPage properties. You can use lazy var for this purpose:

```
class Foo {
    var pageSize = 20
    var curPage = 1
    lazy var results: [Int] = {
        let start = self.curPage * self.pageSize
        let end = start + self.pageSize
        
        return (start..<end).map { $0 }
    }()
}
```
