### ISSUE TITLE
"TableView with Editing" example is not able to move items

### ISSUE THREAD

**Issue by rivertea** [ReactiveX/RxSwift#768]
"TableView with Editing" example is not able to move items.

Firstly, I added

```
dataSource.canMoveRowAtIndexPath = { _ in
    return true
}
```
in `configureDataSource()` so that the items are able to be moved.

When trying to moving the cells in one section, the cells are moved without refreshing the label.
When moving the cells from section 0 to section 1, `fatal error: Index out of range` will be raised.

BTW, randomuser.me may have modified the API, the `parseJSON()` in `RandomUserAPI.swift`
```
let users = results.map { $0["user"] as? [String: AnyObject] }.filter { $0 != nil }
```
should modify as
```
let users = results.filter { $0 != nil }
```
Then it can fetch the users. 

My Xcode version is 7.3.1, I run the example on the iOS 9.3 simulator.
Cheers

**Comment by kzaher** [comment]
Hey, this should be fixed now. Thxn for reporting. 👍
