### ISSUE TITLE
Can synchronous binding be supported ?

### ISSUE THREAD

**Issue by jibeex** [ReactiveX/RxSwift#781]
Hello, currently, all the bindings & subscription closures are run asynchronously, is it possible to have an option to run bindings & subscription closures synchronously ?

Thank you.

**Comment by kzaher** [comment]
Hi @jibeex ,

Rx is synchronous by default. I'm not sure what is your understanding.

**Comment by jibeex** [comment]
Correct me if I am wrong. Subscription closures are run inside dispatch_async(....){ ....  } , so that is always asynchronous, right ?

**Comment by jibeex** [comment]
Ah, I think I have better understanding right now. If I don't specify any scheduler, no "subscribeOn" or "observeOn", subscription closures are going to run synchronously. But if some schedule is specified, subscription closures run asynchronously. Is it right ?

**Comment by kzaher** [comment]
> Ah, I think I have better understanding right now. If I don't specify any scheduler, no "subscribeOn" or "observeOn", subscription closures are going to run synchronously. But if some schedule is specified, subscription closures run asynchronously. Is it right ?

yep

**Comment by kzaher** [comment]
No hidden dependencies.

**Comment by jibeex** [comment]
Thank you. That is good for me.
