### ISSUE TITLE
How to observe orientation change with RxSwift

### ISSUE THREAD

**Issue by jibeex** [ReactiveX/RxSwift#783]
Hi,

Is there an Rx property on which we can subscribe for orientation change device ?

**Comment by sergdort** [comment]
Hm, I'm not sure whether there are any `NSNotification`
But you can observe `viewWillTransitionToSize` kinda like this:

```swift
rx_sentMessage(#selector(UIViewController.viewWillTransitionToSize(_:withTransitionCoordinator:)))
         .subscribeNext { (params) in
            //Do something here on size class change
         }
         .addDisposableTo(disposeBag)
```

**Comment by jibeex** [comment]
Looks a little bit complex. It seems better to use view.rx_observe(CGRect.self, "frame")

**Comment by Succete** [comment]
maybe observe UIDeviceOrientationDidChange notification.

**Comment by acecilia** [comment]
NSNotificationCenter.defaultCenter().rx_notification(UIDeviceOrientationDidChangeNotification).subscribeNext {
}

**Comment by kzaher** [comment]
Assuming this is resolved :)

**Comment by lexuanquynh** [comment]
The solution is to find a better alternative.
` NotificationCenter.default.rx.notification(UIDevice.orientationDidChangeNotification)
            .observeOn(MainScheduler.instance)

            .subscribe(onNext: { data in
                print("data \(data)")
            })
        .disposed(by: disposeBag)`
