### ISSUE TITLE
Need to change the cocoapod podspecs to OSX10.10?

### ISSUE THREAD

**Issue by acecilia** [ReactiveX/RxSwift#791]
The podspec says:

` s.osx.deployment_target = '10.9'`

But in the project:
![captura de pantalla 2016-07-11 a las 22 33 24](https://cloud.githubusercontent.com/assets/7938671/16745756/a135c554-47b7-11e6-953b-9fb9330ff40f.png)

**Comment by kzaher** [comment]
Hi @acecilia ,

I think we've used 10.10 because it crashed the linker while comparing with carthage otherwise. I haven't encountered problem with CocoaPods for some reason. Is there one?

**Comment by acecilia** [comment]
I thought the deployment version in cocoapods should be the same of the deployment version in the project.

**Comment by kzaher** [comment]
Hi @acecilia ,

Yeah, I think we should probably ramp up Podspec version to 10.10.

**Comment by kzaher** [comment]
I've increased the version. This will be published with next release.
