### ISSUE TITLE
Why 'toArray' is invalid

### ISSUE THREAD

**Issue by zhaomingbo** [ReactiveX/RxSwift#792]
like this:
searchBar.rx_text.flatMap { searchString -> Observable<String> in
        self.viewModel.searchDataSource.toObservable().filter{
            $0.rangeOfString(searchString) != nil
        }
        }.toArray()
it can't normal 'next' 

but
“Observable.of("xasd","zx").toArray()”
 is effective

I'm deeply sorry for my English

**Comment by Succete** [comment]
It's OK, maybe I can help you.
你把searchDataSource的类型先贴出来看看。
let observable = searchBar.rx_text.flatMap { searchString -> Observable in
            self.viewModel.searchDataSource.toObservable().filter{
                $0.rangeOfString(searchString) != nil
            }
        }
写成这样，flatMap里Observable类型不清。然后看一下observable的类型。应该是类型不正确，所以不能用toArray()

**Comment by zhaomingbo** [comment]
Thank you very much for your reply
     
let observable = searchBar.rx_text.flatMap { searchString -> Observable<String> in
            self.viewModel.searchDataSource.toObservable().filter{
                $0.rangeOfString(searchString) != nil
            }
   }
可以正常next 的可以打印出正常的string类型,可是toArray就不能合成数组了 我上面发的漏写了<String>

**Comment by zhaomingbo** [comment]
我知道了没哟
