### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by mbuchetics** [ReactiveX/RxSwift#793]
Currently, RxSwift does not build due to 

> A shell task failed with exit code 66:
> xcodebuild: error: Scheme RxExample-iOS-no-module is not currently configured for the build action.

Once we delete the scheme, everything works fine. We are building RxSwift as a dependency of Moya.

**Comment by kzaher** [comment]
Hi @mbuchetics ,

I think this might be a problem with Carthage. We've deleted that scheme from the RxSwift repo as far as I can tell. Have you tried deleting Carthage dir and `~/Library/Caches/org.carthage.CarthageKit`? I've had similar issues with Carthage while performing integration tests.

**Comment by ikesyo** [comment]
I've checked the repo, the scheme is removed in [this commit](https://github.com/ReactiveX/RxSwift/commit/c0939e1b4e06bc372ee6f9d63c180d6b158f0d96) and the change is included in the latest 2.6.0 release. So if you are using 2.5.0 and before releases, the scheme still exists in the checked out directory. I believe updating to 2.6.0 should resolve the issue.

**Comment by mbuchetics** [comment]
Seems to be working fine with Moya 7.0 and RxSwift 2.6. Thanks!
