### ISSUE TITLE
Observable.timer crashing and not working in swift-3.0 branch

### ISSUE THREAD

**Issue by alexiosdev** [ReactiveX/RxSwift#799]
Dear @kzaher , I have been using RxSwift in several projects and this is really awesome.

I have swift3.0 project and using RxSwift as submodule with swift-3.0 branch.
I am not sure what I did wrong but this Observable.timer seems not working.
They are not working on both `XCode 8.0 beta 2` and `XCode 8.0 beta 3`.

-  Timer with interval not working.
```swift
Observable<Int64>.timer(0, period: 5, scheduler: MainScheduler.instance)
            .subscribeNext{value in
                print(value)
            }.addDisposableTo(disposeBag)
```
This code should print `0` first and print time value every 5 seconds, but I only see `0` in console.  So timer is not working

- Crash with some big interval

If I increase interval to 600 (about 10 mins), the app directly crashes.

```swift
Observable<Int64>.timer(0, period: 600, scheduler: MainScheduler.instance)
            .subscribeNext{value in
                print(value)
            }.addDisposableTo(disposeBag)
```

This issue is so confident that I don't need to provide sample project.
I think you can put that code in `viewDidLoad()` method of `ViewController.swift` file which is created by Single View Based iOS app template.

Thank you.

**Comment by alexiosdev** [comment]
I think `schedulePeriodic` and `scheduleRelative` has some error in calculating intervals for DispatchSource.
```swift
public func schedulePeriodic<StateType>(_ state: StateType, startAfter: TimeInterval, period: TimeInterval, action: (StateType) -> StateType) -> Disposable {
        
        
        let initial = MainScheduler.convertTimeIntervalToDispatchTime(startAfter)
        let dispatchInterval = MainScheduler.convertTimeIntervalToDispatchInterval(period)
        
        var timerState = state
        
        let validDispatchInterval = dispatchInterval < 0 ? 0 : UInt64(dispatchInterval)
        
        let timer = DispatchSource.timer(flags: DispatchSource.TimerFlags(rawValue: UInt(0)), queue: _serialQueue)
        timer.scheduleRepeating(deadline: initial, interval: DispatchTimeInterval.seconds(Int(validDispatchInterval)), leeway: DispatchTimeInterval.microseconds(0))
        
        let cancel = AnonymousDisposable {
            timer.cancel()
        }
        timer.setEventHandler(handler: {
            if cancel.disposed {
                return
            }
            timerState = action(timerState)
        })
        timer.resume()
        
        return cancel
    }
```

When calling `timer.scheduleRepeating` function, you use `DispatchTimeInterval.seconds(Int(validDispatchInterval))`  but I think `validDispatchInterval` is a nanosecond value and you are getting dispatch time interval with .seconds enum.

I suggest the function calling should look like this
```Swift
timer.scheduleRepeating(deadline: .now() + .milliseconds(Int(startAfter * 1000)), interval: .milliseconds(Int(period * 1000)), leeway: .microseconds(0))
```

@kzaher what do you think about this?

Thanks.

**Comment by kzaher** [comment]
Hi @alexiosdev ,

Unfortunately the fix wasn't so simple, Apple has somewhat changed semantics of `DispatchSource.timer`.

I've added new scheduler unit tests and pushed fix to `swift-3.0` branch.

**Comment by alexiosdev** [comment]
Hi, @kzaher, Thank you for your support.
Timer seems working well and also no crashes any more.
👍

**Comment by vipinsaini0** [comment]
{
        guard let time = time else { return }
        guard time > 0 else { return }
        var timeout = time
        timer = DispatchSource.makeTimerSource(flags: DispatchSource.TimerFlags(rawValue: 0),
                                               queue: DispatchQueue.main)// as! DispatchSource
        timer?.schedule(wallDeadline: .now(), repeating: .seconds(1))

        timer.setEventHandler { _ in  // Error show: " Ambiguous reference to member 'setEventHandler(qos:flags:handler:)' "
            if timeout <= 0 {
                DispatchQueue.main.async {
                    dismiss()
                    completion?()
                }
            } else {
                timeout -= 1
            }
        }

        timer!.resume()
    }
