### ISSUE TITLE
Use a real CHANGELOG?

### ISSUE THREAD

**Issue by orta** [ReactiveX/RxSwift#80]
It's nice that you're using GitHub's releases feature, but nothing beats actually including a CHANGLOG so that you can easily look over the changes from the terminal.

**Comment by kzaher** [comment]
Do you feel that the level of detail noted in release notes is sufficient, or do you think that it should be more granular or in different format?

**Comment by orta** [comment]
I think the level of detail in the release notes is totally cool :+1: 
Once RxSwift is big enough it might warrant something more like [CocoaPods](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md)/[AFNetworkings](https://cocoapods.org/pods/AFNetworking#changelog)

**Comment by kzaher** [comment]
I've added changelog as of 1.9.1
I'm going to close this issue. Let me know if you feel that we need to modify it :)

**Comment by orta** [comment]
[I'm happy](http://cocoapods.org/pods/RxSwift#changelog)
