### ISSUE TITLE
[Swift 3.0] Observable.interval not working?

### ISSUE THREAD

**Issue by aputinski** [ReactiveX/RxSwift#805]
Based on the Getting Started, should the below code snippet print an integer each second?

```swift
Observable<Int>
  .interval(1, scheduler: MainScheduler.instance)
  .takeUntil(rx_deallocated)
  .subscribe { event in
     print(event)
   }
```
  
*Xcode version*:

  Xcoode 8 Beta 3

*Expected outcome*:

  ```swift
Next(0)
Next(1)
Next(2)
...
```

*What actually happens*:

  ```swift
Next(0)
```

*Installation method*:
  * Carthage

*I have multiple versions of Xcode installed*:
  * yes (7, 8 Beta 2, 8 Beta 3)

*Level of RxSwift knowledge*:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  * I have a small code base
```

**Comment by kzaher** [comment]
Hi @aputinski ,

if self is not deallocated yes. Can you please check you are using latest commit from swift-3.0 branch?

**Comment by aputinski** [comment]
Ahh... looks like I was a few comments behind. Sorry about that.
