### ISSUE TITLE
Rx.xcodeproj does NOT have Rx.playground as advertised in the docs, which is confusing

### ISSUE THREAD

**Issue by PelamReaktor** [ReactiveX/RxSwift#806]
```
*Short description*:

Rx.xcodeproj does not have Rx.playground as advertised in the docs, which is confusing for a novice.

Suggested fix:
1. Add Rx.playground to Rx.xcodeproj
2. Add a line about first opening Rx.xcodeproj instead of Rx.playground to Rx.playground.

*Self contained code example that reproduces the issue*:

  * As an RxSwift novice read https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#playgrounds
  * Follow link to https://github.com/ReactiveX/RxSwift/tree/master/Rx.playground
  * Clone RxSwift from github
  * Open Rx.playground directly in XCode, it errors at import RxSwit
  * Notice the nice instructions at the top of playground :)
  * Deduce that you must open Rx.xcodeproj instead of Rx.playground directly <---- this step could be mentioned in the Rx.playground
  * Open Rx.xcodeproj and build as instructed
  * Be confused about how to get to working playground
  * Add Rx.playground file to Rx.xcodeproj  <---- this step can be easily removed
  * click on Rx.playground
  * Working playground ---> learn RxSwift

*Xcode version*:

Version 7.3.1 (7D1014)

*Expected outcome*:

After building the Rx.xcodeproj RxSwift OSX scheme, I expect to have a working playground.

*What actually happens*:

Getting to working Rx.playground from the tutorial is unnecessarily difficult and could lose some novices on the way.

*Installation method*:
clone of RxSwift from GitHub

*I have multiple versions of Xcode installed*:
  * no

*Level of RxSwift knowledge*:
  * I have a small code base
```

**Comment by PelamReaktor** [comment]
For reference: here is what it says on the top of the playground:

IMPORTANT: To use Rx.playground:

	1.	Open Rx.xcworkspace.
	2.	Build the RxSwift-OSX scheme (Product → Build).
	3.	Open Rx playground in the Project navigator.
	4.	Show the Debug Area (View → Debug Area → Show Debug Area).

Btw. Great documentation and the playground is cool too :)

**Comment by kzaher** [comment]
Hi @PelamReaktor ,

can you maybe explain which documentation are you referring to?

**Comment by PelamReaktor** [comment]
Hi @kzaher 

Specifically this line:

https://github.com/ReactiveX/RxSwift/blob/master/Rx.playground/Pages/Introduction.xcplaygroundpage/Contents.swift#L5

And this

https://github.com/ReactiveX/RxSwift/blame/master/Documentation/Playgrounds.md#L7-Lundefined

They seem to say that Rx.playground is included in Rx.xcodeproj and easy to find in there.

If I understand this correctly, adding Rx.playground to Rx.xcodeproj would smooth out the path for novices and make those 2 documentation lines be correct.

Best Regards,
Peter Lamberg

**Comment by kzaher** [comment]
This should be improved now. Closing this.
