### ISSUE TITLE
Request: Proxy for MKMapViewDelegate

### ISSUE THREAD

**Issue by mkko** [ReactiveX/RxSwift#807]
There's a plenty of proxies for various delegates in [/RxCocoa/iOS/Proxies](/ReactiveX/RxSwift/tree/master/RxCocoa/iOS/Proxies) but a proxy for the MKMapViewDelegate is missing. RxSwiftCommunity has made one ([RxMKMapView](https://github.com/RxSwiftCommunity/RxMKMapView)) and it'd be neat if it could be added as part of the main project.

Is there any reason why not include this proxy? I'd be happy to help and make a pull request.

**Comment by sergdort** [comment]
I think becaus its in `MapKit` rather then `UIKit` , `Cocoa`

**Comment by mkko** [comment]
Oh right, that's a good point. Totally forgot that MapKit is its own framework. Then this makes no sense.
