### ISSUE TITLE
rx_itemsWithCellIdentifier problem

### ISSUE THREAD

**Issue by krasnodar95** [ReactiveX/RxSwift#810]
Hello, I have this problem XCode 7.3.1

![2016-07-30 17 40 07](https://cloud.githubusercontent.com/assets/1948526/17271137/dddee728-567c-11e6-8aee-03e075a6bdd7.png)

**Comment by sergdort** [comment]
Hi, @krasnodar95 

It's generic method`rx_itemsWithCellIdentifier<S: SequenceType, Cell: UITableViewCell, O : ObservableType where O.E == S>(cellIdentifier: String, cellType: Cell.Type = Cell.self)`

so it's needs to know the types, please take a look how this works in the [example app](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/SimpleTableViewExample/SimpleTableViewExampleViewController.swift#L28)
