### ISSUE TITLE
combineLatest + merge

### ISSUE THREAD

**Issue by RamwiseMatt** [ReactiveX/RxSwift#811]
I am trying to use combineLatest and merge together. My understanding of merge is that it emits items even if one of the observables involved is completely empty (in other words, they are not dependent on each other). However, I am running into a situation where the result of a merge is an observable that never emits items, *even when one of the original observables IS emitting*.

```
let fbTokenChangeNotification = NSNotificationCenter.defaultCenter().rx_notification(FBSDKAccessTokenDidChangeNotification)

// This will print "A wild notification appeared." upon receiving a notification via rx_notification()
Observable
	.of(Observable.empty(), fbTokenChangeNotification)
	.merge()
	.subscribeNext { _ in
		print("A wild notification appeared.")
	}
	.addDisposableTo(disposeBag)


// This will not print anything, no matter how many notifications are sent via rx_notification()
Observable
	.of(Observable.combineLatest(
			fbTokenChangeNotification.single(),
			someOtherObservable) { nf1, _ in
				return nf1
		},
		fbTokenChangeNotification.skip(1))
	.merge()
	.subscribeNext { _ in
		print("A wild notification appeared.")
	}
	.addDisposableTo(disposeBag)

```

(for the sake of completeness, the idea behind this construction would be that the first item emitted by fbTokenChangeNotification is only observed if the second observable emits an item. Any future notifications by fbTokenChangeNotification should always be observed).

*Xcode version*:
  
  Xcode version 7.3.1

*Expected outcome*:

Both merges should be emitting items when the "fbTokenChangeNotification" emits more than one item.

*What actually happens*:

Only the first merge (with an empty observable) performs as expected. Strange, because the merge result in the second example should always emit something if more than one notification was sent, regardless of whatever observable it is merged with. At least, such is my understanding.

*Installation method*:
 CocoaPods

*I have multiple versions of Xcode installed*:
no

*Level of RxSwift knowledge*:
 I have a small code base

**Comment by kzaher** [comment]
Hi @RamwiseMatt,

I'm assuming one of the observable sequences sent error and disposed everything. Probably `someOtherObservable`.

You can trace all events for sequence by using `debug` operator.

```swift
Observable
    .of(Observable.combineLatest(
            fbTokenChangeNotification.single().debug("fb"),
            someOtherObservable.debug("some other")) { nf1, _ in
                return nf1
        },
        fbTokenChangeNotification.skip(1).debug("token change"))
    .merge()
     .debug("all")
    .subscribeNext { _ in
        print("A wild notification appeared.")
    }
    .addDisposableTo(disposeBag)
```

**Comment by RamwiseMatt** [comment]
Thanks for the reply, it's much appreciated!

Your suggestion seems to have gotten me a little closer. The console tells me...

```
2016-08-01 13:23:54.722: fb -> Event Error(Sequence conta...e than one element.)
2016-08-01 13:23:54.722: fb -> disposed
2016-08-01 13:23:54.722: all -> Event Error(Sequence conta...e than one element.)
2016-08-01 13:23:54.722: all -> disposed
```

Which indicates that the `fbTokenChangeNotification.single()` observable is somehow malfunctioning, I suppose? As stated before, the idea is to grab only the first element of the fbTokenChangeNotification observable and apply combineLatest with someOtherObservable. I am not sure what to make of this!

**Comment by RamwiseMatt** [comment]
Replacing single() with take(1) seems to have fixed this error for me, though frankly I am uncertain as to why, as I understand them to be the same thing. Other than that, the issue has been resolved.

**Comment by fpillet** [comment]
`single` errors out if the observable emits more than one item. `take(1)` takes the first item emitted by an observable then completes.
