### ISSUE TITLE
`Driver` and `ShareReplay1WhileConnected`

### ISSUE THREAD

**Issue by MadsBogeskov** [ReactiveX/RxSwift#813]
I am currently using RxSwift in conjunction with a MVVM pattern in an app, and I am having some problems with the way the `Driver` works. 

I have code like this: 
`let titleObservable: Observable<String> = Observable.just("My Awesome Title").concat(SomeNetworkBasedObservable.single())`

which Completes after the network request completes, as expected. However I then have a ViewModel object that takes this observable as input like this:

```
class MyViewModel {
    let titleDriver: Driver<String>

    init (titleObs: Observable<String>) {
         titleDriver = titleObs.asDriver(onErrorJustReturn: "")
    }
}
```

This `titleDriver` is then subscribed to in the view that has the ViewModel, which is all fine and good. The value gets set as expected in the view. However just after the titleObservable completes it also disposes the entire observable, probably because there will never come any newer values from the `titleObservable`, aka this code in `ShareReplay1WhileConnected`:
```
case .Error, .Completed:
    _element = nil
    _connection?.dispose()
```
This code also deletes the underlying saved element of the `Driver`. But I use this value later on, where I expected to still be able to get it since it is a `ShareReplay` and I keep a strong reference to the original `Driver`. But since the observable has completed then there is no longer any value associated with the `Driver`. 

This might be a case where I bind the value to a `Subject` in the viewmodel and save the value. However then I would need to have something like: 
```
class MyViewModel {
    let titleDriver: Driver<String>
    let savedTitle = BehaviorSubject<String>(value: "")

    init (titleObs: Observable<String>) {
         titleDriver = titleObs.asDriver(onErrorJustReturn: "")
         titleDriver.drive(savedTitle).addDisposableTo(disposeBag)
    }
}
```

Is this the right approach? Or is there some way I can make the driver not dispose and remove the element?

**Comment by kzaher** [comment]
Hi @MadsBogeskov ,

**Comment by kzaher** [comment]
unfortunately `Driver` wasn't intended to model finite sequences like in your case :)

I guess you could do something like
```swift
Observable.just("My Awesome Title")
.concat(SomeNetworkBasedObservable.single().catchError(... you need to handle error ...))
.concat(Observable.never())
```

**Comment by MadsBogeskov** [comment]
Yeah I thought as much :) That solution would work, and I like it more than just exposing a normal shareReplay, observeOn Observable.
Thanks!
