### ISSUE TITLE
What is a `Sink`

### ISSUE THREAD

**Issue by jibeex** [ReactiveX/RxSwift#817]
Hello, is there a nice explanation of what a `Sink` is in this library ?

**Comment by fpillet** [comment]
It's an internal class used to implement the operators, that receives events and processes them. Beyond that, I think you'll have to go through the code to figure out how it works.

**Comment by jibeex** [comment]
Thank you. So it is a processor to transform streams of events into another stream, right?

**Comment by tqtifnypmb** [comment]
It provides `dispose` function to observer when it's being feeding to by operator or by the implementation of operator.
