### ISSUE TITLE
'bindTo(aNSButton.rx_enabled)' failed

### ISSUE THREAD

**Issue by a83988029** [ReactiveX/RxSwift#819]
here is my code:
    
        let aDisposeBag = DisposeBag()
        class LoginController: NSViewController {
        @IBOutlet weak var accountField: NSTextField!
        @IBOutlet weak var passwdField: NSSecureTextField!
        @IBOutlet weak var loginBtn: NSButton!
        override func viewDidLoad() {
            super.viewDidLoad()
            let accAvailable = accountField.rx_text.map({(aa)-> Bool in
                print("aa")
                return aa.characters.count > 0
            })
    
            let passAvailable = passwdField.rx_text.map({(aa)-> Bool in
                print("bb")
                return aa.characters.count > 0
            })
    
            let allAvailable = Observable.combineLatest(accAvailable, passAvailable){$0 && $1}
            allAvailable.bindTo(loginBtn.rx_enabled).addDisposableTo(aDisposeBag)
    
        }
    }

When I input contents into accountField,nothing prints in the console.

But if I replace `allAvailable.bindTo(loginBtn.rx_enabled).addDisposableTo(aDisposeBag)` into 

    allAvailable.subscribeNext { (available) in
                print(available)
            }.addDisposableTo(aDisposeBag)

Then I can see `aa` or `bb` is printed in the console.
Anyone can tell what's wrong with my code,thanks a lot!

**Comment by kzaher** [comment]
Hi @a83988029 ,

I've tried your exact case in RxExample app and it worked. Maybe you have wrong connected some ib outlet or something. You also have `debug` operator, so you can try to debug and see what's happening.

**Comment by a83988029** [comment]
It works as expected today.
I have no idea what happened last week.
