### ISSUE TITLE
[Swift 3.0] Update for Xcode 8 beta 6

### ISSUE THREAD

**Issue by mohsenr** [ReactiveX/RxSwift#833]
Xcode 8 beta 6 introduces a number of breaking changes to the Swift language. We need to update the code to match.

**Comment by mohsenr** [comment]
I just started working on this.

**Comment by mohsenr** [comment]
Created a WIP pull request for this (#834), however I'm not able to do any more work on this today. Please feel free to pick it up and continue the implementation . Leave a comment here so we know you’re working on it.

**Comment by kzaher** [comment]
I've merged it. Unit tests still don't pass :( I think this might be compiler bug.

**Comment by mohsenr** [comment]
Fixed it :-)
