### ISSUE TITLE
DeallocObservable triggers an event as part of deinit. Is that expected?

### ISSUE THREAD

**Issue by hernangonzalez** [ReactiveX/RxSwift#836]
Hi, 

I have subscribed to the tap of a bar item, and I am getting an event when the item is deallocated. 

```
	override var navigationItem: UINavigationItem {
		let navItem = super.navigationItem

		if navItem.leftBarButtonItem == nil {
			let barItem = UIBarButtonItem(image: UIImage(named: "shape3"), style: .Done, target: nil, action: nil)
			barItem.tintColor = UIColor.blackColor()
			barItem.rx_tap
				.subscribe({ (event) in
					logger.debug(event)
				})
				.addDisposableTo(rx_disposeBag)
			navItem.leftBarButtonItem = barItem
		}
}
```

Looks like this is pretty intencional, as I found the trigger for this on `DeallocObservable`
```
class DeallocObservable {
    let _subject = ReplaySubject<Void>.create(bufferSize: 1)

    init() {
    }

    deinit {
        _subject.on(.Next(()))
        _subject.on(.Completed)
    }
}
```

I was not expecting that to happen, am I using it wrong here?

Thank you!
H.

**Comment by kzaher** [comment]
Hi @hernangonzalez ,
 
It seems to me that is expected behavior.

Upon deallocation of UI element all sequences that are derived from that element should complete. 

I think you were looking for a different subscribe form that registers a callback for sequence elements only:
```swift
                .subscribe(onNext: { (_) in
                    logger.debug("Tap")
                })
```

**Comment by hernangonzalez** [comment]
@kzaher I was expecting it to complete, no to send a Next. That's where i found it unexpected.

**Comment by hernangonzalez** [comment]
Anyway, if this is expected. I'll just learn to use it as is. Thank you!

**Comment by kzaher** [comment]
As far as I can repro in RxExample app, it completes on dealloc, and doesn't send element event. Dealloc sequence should send next, not rx_tap.
