### ISSUE TITLE
Add UIWebView delegate proxy to RxCocoa

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#838]
I think adding [this](https://gist.github.com/cliss/91dbceb77f39e092f062) to RxCocoa would be awesome.

I'd be happy to create a PR, just wanted to make sure there were no objections before I started 😄

**Comment by kzaher** [comment]
Hi @AndrewSB ,

yeah, I think adding this would be ok.

**Comment by AndrewSB** [comment]
Cool! I'll update here when I have the PR.
I should add tests as well?

**Comment by kzaher** [comment]
@AndrewSB yep, ofc, take a look at CLLocationManager+Rx

**Comment by AndrewSB** [comment]
@kzaher submitted #855
