### ISSUE TITLE
Variable used before being initialized   

### ISSUE THREAD

**Issue by viacheslavgusev** [ReactiveX/RxSwift#840]
![2016-08-19 5 16 01 pm](https://cloud.githubusercontent.com/assets/15193264/17812916/3f4f0c32-663a-11e6-845c-39174a74a2ae.png)
![2016-08-19 5 16 34 pm](https://cloud.githubusercontent.com/assets/15193264/17812918/3f7d6618-663a-11e6-842a-8eea874abbf3.png)

I have a such interesting problem. 
If I place the initialization of _self.eventCoordinateVariable_ at the begging of _init()_ after the initializations of _self.eventTitleVariable_ and _self.eventDescritionVariable_  - all works fine.

I don't have any ideas why it works in such way.

And I have such questions: 
We can't use Variables before initializing all of them? 
Are they connected with each other somehow? 
Or is this problem connected with swift initialization process?

Thanks for your time.

*Xcode version*:

 Version 7.3.1 (7D1014)

*What actually happens*:

I try to bind ViewModel and Model.

*Installation method*:
  * CocoaPods

*I have multiple versions of Xcode installed*:
  * no

*Level of RxSwift knowledge*:

  * just starting

```

**Comment by kzaher** [comment]
Hi @viacheslavgusev ,

Swift compiler is telling you that you are using `self` before initializing all member properties/fields (specifically `eventCoordinateVariable`). This is not an Rx issue.
