### ISSUE TITLE
Reporting UIKit iOS 10 issue: Why isn't UISwitch being deallocated ... ever, help wanted.

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#842]
I'm asking for help on this. I have no idea why is this happening, but it looks like every instance of UISwitch isn't being deallocated ... ever

Simplest way to experience it:

``` swift
class Switchy : UISwitch {
    deinit {
        print("bye, just smile and :wave: boys") // This will never be printed
    }
}

....

Switchy(frame: .zero) // never being deallocated
UISwitch(frame: .zero).rx.deallocating.subscribe(onNext: { _ in print("This will never be called") })
UISwitch(frame: .zero).rx.deallocated.subscribe(onNext: { _ in print("This will never be called") })
```

**Comment by JegnuX** [comment]
Basic retain cycle. 
`UISwitch` seems to retain an instance of a `UISwitchModernVisualElement` object through the `_visualElement` property, with retain itself the `UISwitch` element through the `_switchControl` property. 
=> bugreport.apple.com ?

![switchtest_xcodeproj 2](https://cloud.githubusercontent.com/assets/63070/17834158/07ef484c-6734-11e6-93db-71c8f893b913.jpg)
![switchtest_xcodeproj](https://cloud.githubusercontent.com/assets/63070/17834159/09fd465c-6734-11e6-8919-1f0a3b650c7a.jpg)

**Comment by bontoJR** [comment]
Oh yeah, good catch! It's happening on the beta as well, UISwitch is never deallocated.
As @JegnuX said, it seems an rdar is necessary.

**Comment by kzaher** [comment]
I've just reported it on bugreport.apple.com ¯\\\_(ツ)\_/¯
