### ISSUE TITLE
Can't build RxSwift

### ISSUE THREAD

**Issue by zbangsatz** [ReactiveX/RxSwift#850]
I can't build RxSwift "3.0.0.alpha.1" in a new demo project with both cocoapods & carthage

Installation method: CocoaPods (1.0.1)

I have multiple versions of Xcode installed: No - Just Xcode version 7.3 (7D175)

Level of RxSwift knowledge: 0

<img width="695" alt="screen shot 2016-08-26 at 3 47 38 pm" src="https://cloud.githubusercontent.com/assets/14541049/17999706/98e34596-6ba4-11e6-83e9-97a18c03a781.png">

**Comment by dangthaison91** [comment]
Have you try this? And i guess RxSwift 3 require Xcode 8.
<img width="960" alt="screen shot 2016-08-26 at 5 22 06 pm" src="https://cloud.githubusercontent.com/assets/6436310/18002440/f2c5efca-6bb1-11e6-8088-f49510bad249.png">

**Comment by zbangsatz** [comment]
I'm using Xcode 7.3 and also Swift 2.2. But I will try. Thanks!

**Comment by kzaher** [comment]
Hi @zbangsatz ,

RxSwift 3.0.0 is for Swift 3.0 only, sorry.

**Comment by annphan** [comment]
Thank you!

**Comment by zbangsatz** [comment]
Thank you!
