### ISSUE TITLE
Initial value for the observable

### ISSUE THREAD

**Issue by nonameplum** [ReactiveX/RxSwift#852]
Hi,

I there a way to post an event when new subscriber subscribe to the observable?
Ideally for me would be to use e.g. `PublishSubject` that will post first initial value for every new subscriber. This initial value for every new subscriber may change over time.

Thanks in advance :)

**Comment by Chlup** [comment]
I think that you are looking for `BehaviorSubject`.

**Comment by nonameplum** [comment]
Not exactly, because `BehaviorSubject` will send for every new subscriber last event from the stream. I don't need this. I want to send for every new subscriber my own first event that may, but shall not be the last event from the stream. I think that something like `doOnSubscribe` that I could use to make `.onNext(initialEvent)` inside.

**Comment by kzaher** [comment]
Hi @nonameplum ,

maybe something like:

```swift
let resultSequence = Observable.deferred {
    return originalSequence.startWith(yourInitialValue)
}
```

**Comment by nonameplum** [comment]
Look quite good. One problem only that I have. I need to pass `yourInitialValue` as an array because I don't know how many events I should send (it depends during runtime). But start with can't be filled using an array :/. `StartWith` class is private so I have no idea how to get around this problem -> http://stackoverflow.com/questions/24024376/passing-an-array-to-a-function-with-variable-number-of-args-in-swift

**Comment by kzaher** [comment]
This should be solved.
