### ISSUE TITLE
Carthage build warnings related to .playground

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#856]
I'm getting these warnings on a clean `carthage update` of RxSwift:

```
*** Checking out RxSwift at "3.0.0.alpha.1"
*** xcodebuild output can be found in /var/folders/5_/bcyz_kd134dgtzcnwl02mywr0000gn/T/carthage-xcodebuild.xxqZ7y.log
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
*** Building scheme "RxTests-iOS" in Rx.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
--- xcodebuild: WARNING: Unable to open project file '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/asb/Developer/wrytr/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
```

**Comment by kzaher** [comment]
Hi @AndrewSB ,

yeah, I'm unsure how to solve this besides removing Rx.playground from Rx.xcodeproj.

**Comment by AndrewSB** [comment]
Thats what I thought too @kzaher. Do you think removing it from the targets that are built will lead anywhere?

**Comment by kzaher** [comment]
If it's not an error, I wouldn't want to remove it from project since it's useful to have it there. If we find some simple way to resolve this, we can implement it. 

If at some point in future this turns into an error, we can then remove it.

Since nobody made any suggestions how to resolve this warning without removing plagrounds, let's close this for now since it doesn't cause any real issues IMHO.

**Comment by shubh10** [comment]
@kzaher These [guys](https://github.com/Moya/Moya/issues/629) had similar issue and they have fixed it. See if it helps

**Comment by AndrewSB** [comment]
@shubh10 I think you're mistaken, that looks like an issue that ended with a `CLEAN FAILED`. So it wasn't the warnings, but the error that the issue and solution addresses
