### ISSUE TITLE
Value of type 'UISearchBar' has no member 'rx_text'

### ISSUE THREAD

**Issue by zh-wowtv** [ReactiveX/RxSwift#858]
My code:

```
self.searchBar
      .rx_text // Observable property thanks to RxCocoa
      .subscribeNext { [unowned self] (query) in // Here we will be notified of every new value
        self.shownCities = self.allCities.filter { $0.hasPrefix(query) } // We now do our "API Request" to find cities.
        self.tableView.reloadData() // And reload table view data.
      }
      .addDisposableTo(disposeBag)
```

I'm using RxSwift 3.0-alpha, is RxSwift changed in new version? Thanks

**Comment by Chlup** [comment]
I thinks that's now .rx.text because of this change: https://github.com/ReactiveX/RxSwift/pull/832

**Comment by zh-wowtv** [comment]
@Chlup Thanks. You're right.

**Comment by zh-wowtv** [comment]
But here comes a new problem:

**Comment by zh-wowtv** [comment]
I changed the source code:

```
    self.searchBar.rx.text
      .subscribe(onNext: { element in
        self.shownCities = self.allCities.filter { $0.hasPrefix(element) } // We now do our "API Request" to find cities.
          self.tableView.reloadData() // And reload table view data.
         print(self.shownCities)
      })
      .addDisposableTo(disposeBag)

```

Still doesn't work although the content printed out is correct.

**Comment by kzaher** [comment]
Hi @zh-wowtv ,

could you please fill out our issue template. I'm not sure what exactly isn't working for you. You can also use `debug` operator in your code samples and send us difference between real and expected printout.

**Comment by kzaher** [comment]
Not sure I can help with this one without more info.

**Comment by Isuru-Nanayakkara** [comment]
@zh-wowtv Were you able to get this resolved? I'm stuck at this same issue.

@kzaher This code snippet is from [this](http://www.thedroidsonroids.com/blog/ios/rxswift-by-examples-1-the-basics/) tutorial. 
```
searchBar
    .rx_text 
    .subscribeNext { [unowned self] (query) in
        self.shownCities = self.allCities.filter { $0.hasPrefix(query) }
        self.tableView.reloadData()
    }
    .addDisposableTo(disposeBag)
```

The code is in an older version of RxSwift. I'm trying to rewrite it in the latest RxSwift syntax. Here's what I have so far.

```
searchBar.rx.text.subscribe { query in
    self.shownCities = self.allCities.filter { $0.hasPrefix(query) } // error here
    self.tableView.reloadData()
}
.addDisposableTo(disposeBag)
```

I'm getting the following error at the second line.

> Cannot convert value of type 'Event<String?>' (aka 'Event<Optional<String>>') to expected argument type 'String'
