### ISSUE TITLE
Variable's asDriver() sync first call

### ISSUE THREAD

**Issue by VladimirBorodko** [ReactiveX/RxSwift#860]
Driver's main advantage for UI is sync first call, so I would expect asDriver() implementation looks more like this:
`extension Variable {`
`  ``func asDriver() -> Driver<E> {`
`  ``  ``return Driver.deferred{`
`  ``  ``  ``let source = self.asObservable().skip(1).observeOn(driverObserveOnScheduler)`
`  ``  ``  ``return Driver(source).startWith(self.value)`
`  ``  ``}`
`  ``}`
`}`

**Comment by kzaher** [comment]
Hi @VladimirBorodko ,

would you please be kind enough to fill that issue template. I'm not sure how to answer your question and what is the exact problem you are reporting.

**Comment by kzaher** [comment]
Until I understand the real issue, can't do anything with this.
