### ISSUE TITLE
Problem for Subject

### ISSUE THREAD

**Issue by zh-wowtv** [ReactiveX/RxSwift#862]
My playground project crash when I subscribe to subject. For example, here is my code:

```
example("Subject") {
  let subject = BehaviorSubject<String>(value:"Hi")
  
  subject.onNext("1")
  subject.onNext("2")
  
  subject.subscribe { event in
    print(event)
  }
}
```

The error message is:

<img width="529" alt="2016-09-03 4 35 52" src="https://cloud.githubusercontent.com/assets/18462946/18223784/8e0a0d48-71f4-11e6-81df-eabc378310e5.png">

My Xcode is version 8 beta 6, the swift is 3.0.0 alpha 1.

**Comment by kzaher** [comment]
Hi @zh-wowtv ,

I'm assuming this is some kind of Swift bug because of playgrounds.

./scripts/validate-playgrounds.sh is passing though.

¯\\\_(ツ)\_/¯

**Comment by kzaher** [comment]
It looks like this works again in Xcode 8 GM. Closing this issue.
