### ISSUE TITLE
Request: Observable creation from Optional

### ISSUE THREAD

**Issue by tarunon** [ReactiveX/RxSwift#866]
I request extension of Optional like `Array.toObservable`.
https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Observables/Observable%2BCreation.swift#L200-L213
Optional is same of Array that has 1 element or empty. (It would be similar in `Array.flatMap`) 
So, I think we can create `Optional.toObservable` also.

I think this feature is useful, and has many profit.

The most simple example is:

``` swift
var a: Observable<Int?>
a.flatMap { $0.toObservable() } // -> Observable<Int>
```

**Comment by kzaher** [comment]
Hi @tarunon ,

I believe there is already https://github.com/RxSwiftCommunity/RxOptional .

**Comment by tarunon** [comment]
Hi @kzaher san,

Yes, I believed it also, but I could not find `Optional.toObservable` in RxOptional.
I opened this issue, because I think this feature would be needed standard support more than adding in RxOptional.

**Comment by sergdort** [comment]
Hi guys, Isn't it `filterNil` in RxOptional?

**Comment by tarunon** [comment]
@sergdort 
Thank you for help.
Yes, I think `.filterNil()` is equal to `.flatMap { $0.toObservable() }`, and `Observable.just(optional).filterNil()` is equal to `optional.toObservable()` also.
This feature is like of monad transform.

**Comment by kzaher** [comment]
Hi @tarunon ,

I'm ~50:50 on this. I understand reasons for pro and con. For the interface to be consistent with 3.0.0 version we would need to have it as `Observable.from(optional)`.

If somebody needs this please tumb up this issue, or thumb down it. For this one, I'm fine with either outcome.

**Comment by Busta117** [comment]
this is my solution, i made a set of method to write the bindings with that sintaxis but you can see here how i fixed it: 
``` swift
infix operator ~>
@discardableResult
public func ~> <T>(variable: Variable<T>, property: AnyObserver<T?>) -> Disposable {
    let bindDisposable = variable.asObservable()
        .map { $0 }
        .bindTo(property)
    return bindDisposable
}
```

and just use it like 
``` swift
var a: Observable<String?>
var label = UILabel()
(a ~> label).addDisposableTo(disposableBag) // this is the Disposable
```

**Comment by tarunon** [comment]
Hi @Busta117 ,
I think your solution is near that convert `Observable<T>` to `Observable<T?>`.
This request is about transform `Optional<T>` to `Observable<T>`.

**Comment by kzaher** [comment]
Hi @tarunon ,

I would be fine adding `Observable.from` with optional overload. I think we could include this for 3.2. 

Would you like try to give it a try yourself?

**Comment by tarunon** [comment]
@kzaher 
Of course! I try to make PR 😁
Thank you notification.
