### ISSUE TITLE
Tableviewcell reuse 

### ISSUE THREAD

**Issue by aofeng2009** [ReactiveX/RxSwift#879]
When i use RXSwift update a model from response for the tableViewcell, I have met some trouble,
1.Where i should add observe on cell's property? 'awakeFromNib' or 'updateModel'?
and how to?
2.How to fixed bindTo many times cause by tableviewcell reuse?
CustomTableviewcell.swift
```
override func awakeFromNib()  {

}
func udpateModel(model:CutomModel) {
    model.selected.asObservable().bindTo(self.selectButton.rx_selected)
}
```

**Comment by sergdort** [comment]
Hi, @aofeng2009 please take a look on #821 or #437

**Comment by aofeng2009** [comment]
You saved my day.
