### ISSUE TITLE
3.0.0.alpha.1 will not compile in xcode 8

### ISSUE THREAD

**Issue by RoryKelly** [ReactiveX/RxSwift#883]
**Short description of the issue**:

Just checked out 3.0.0.alpha.1 using cocoapods, and it won't compile.

**Self contained code example that reproduces the issue**:

This is my pod file, I'm using a single view controller XCode project. 
```
 target 'demo' do
    pod 'RxSwift',   :git=> 'git@github.com:ReactiveX/RxSwift.git', :branch => 'master'
    pod 'RxCocoa',    '~> 3.0.0-alpha.1'
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo

  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 3.0.0-alpha.1'
    pod 'RxTests',    '~> 3.0.0-alpha.1'
  end

  target 'demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
```

**Xcode version**:

```
Version 8.0 (8A218a)
```

**Expected outcome**:

The project builds.
**What actually happens**:

XCode complains about missing @escaped closures everywhere.

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ x] yes (which ones) (latest beta. and latest release)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base (I have significant RXJava experience)
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @RoryKelly ,

we've released new beta.1 version that compiles with Xcode Version 8.0 (8A218a).

**Comment by RoryKelly** [comment]
Coo,l I tried using beta.1 yesterday but pods couldn't find it I'll try again this morning. Thanks.
