### ISSUE TITLE
Is there a way to flatMap every element of array in Observable<[Type]> and return Observable<[Type]> with all intermediate results?

### ISSUE THREAD

**Issue by rehsals** [ReactiveX/RxSwift#888]
Hi!
Another problem I've stumbled on recently.
Let's say I have a
```
func getDataList() -> Observable<[DataType]>
```
Now I want to perform expensive operation on each `DataType` object from array (`fetchAdditionalDataFor(data: DataType) -> Observable<DataType>` ). And I want `.Next` for `getDataList()` to be generated on every completed expensive operation. So I could get an array, with objects where some of them have the operation performed on and some haven't yet.

**Comment by pgherveou** [comment]
not sure this answer ur question but i created a gist here https://gist.github.com/pgherveou/e1bf42339b1df598275690cb5432992c  that define an operator that sync an array with projected values

**Comment by rehsals** [comment]
Thanks, I think it's exactly what I needed.

**Comment by kalyanmuddapu** [comment]
Hello PG Herveou, 
Thanks for the code .
But how to get [DataType] from the array using flatMap ,filter
