### ISSUE TITLE
Release beta.1 to be Carthage installable

### ISSUE THREAD

**Issue by buffstop** [ReactiveX/RxSwift#893]
Building RXSwift using Carthage for Xcode8/Swift3 fails, as it checks out alpha.1.

Please make beta.1 a release (is currently pre-release).
 
Cartfile:
```
github "ReactiveX/RxSwift" ~>3.0.0
```

**Xcode version**:

```
  Xcode version:  8.0 (8A218a)
```

**Expected outcome**:
- should checkout 3.0.0.beta.1
- Build succeeds 

**What actually happens**:
- checks out 3.0.0.alpha.1
- Build fails

One line of log (repeated many times for many files):
```
*** Fetching RxSwift
*** Checking out RxSwift at "3.0.0.alpha.1"
*** xcodebuild output can be found in /var/folders/s0/h6_m1hdj3176rs93vmddjx8c0000gn/T/carthage-xcodebuild.tMjSCH.log
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Volumes/.../Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Volumes/.../Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
** BUILD FAILED **
/Volumes/ ... /Carthage/Checkouts/RxSwift/RxSwift/Schedulers/SchedulerServices+Emulation.swift:32:19: error: assigning non-escaping parameter 'action' to an @escaping closure
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones) Xcode 7.3.1 & Xcode 8
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @buffstop , 

I'm not sure how does carthage support pre-releases. This worked for me.

```
github "ReactiveX/RxSwift" "3.0.0-beta.1"
```

Unfortunately, it's not a release, so we can't make it a release.

**Comment by buffstop** [comment]
That works here too. Thank you.

**Comment by mihailsalari** [comment]
Not works...

**Comment by buffstop** [comment]
Thx!

**Comment by tonyarnold** [comment]
Yeah, this won't work because of the tag `3.0.0.alpha.1` (which according to SemVer needs to be `3.0.0-alpha.1`). The 3.0 betas are not installable with Carthage due to this errant tag name.
