### ISSUE TITLE
Errors still remained on Swift 3.0 / Xcode8 with installation of CocoaPods

### ISSUE THREAD

**Issue by SpiciedCrab** [ReactiveX/RxSwift#894]
How can we support Swift 3.0 with RxSwift's new version?
We add
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end`

in our podfiles , but it doesn't work.
So any other solutions?
We have cocoapods v1.0 with Xcode 8 on MacOS 10.11.6

**Comment by kzaher** [comment]
Hi @SpiciedCrab ,

RxSwift 3.x is compatible with Swift 3.x
RxSwift 2.x is compatible with Swift 2.x

**Comment by kzaher** [comment]
To be able to help with this issue, we would need to understand what exact part isn't working.

**Comment by anafinotti** [comment]
I'm getting this error...anyone? 
![screen shot 2016-09-19 at 8 10 43 pm](https://cloud.githubusercontent.com/assets/5528817/18654257/373375aa-7ea5-11e6-9f1b-28fab78bb88b.png)

**Comment by SpiciedCrab** [comment]
![image](https://cloud.githubusercontent.com/assets/13127567/18656879/ab85591e-7f27-11e6-88f4-bb1bd315d74d.png)
I also got this error while pod updating...

**Comment by tleavy86** [comment]
@SpiciedCrab  @anafinotti I had the same problem, Updating to Cocoapods 1.1.0.rc.2 fixed my problem

**Comment by bonro001** [comment]
I am using cocoa pods 1.1.0 rc2 and still seeing the issue under Xcode 8:

- `RxSwift (~> 3.0.0-beta.1)` required by `Podfile`
- `RxSwift (~> 3.0.0-beta.1)` required by `Podfile`

using this:

pod 'RxSwift',    '~> 3.0.0-beta.1'
pod 'RxCocoa',    '~> 3.0.0-beta.1'
pod 'RxDataSources', '~> 1.0.0-beta.2'

**Comment by bonro001** [comment]
Was able to fix this with pod repo update

**Comment by SpiciedCrab** [comment]
@tleavy86 thanks and it works!
