### ISSUE TITLE
Why RxSwift.framework and RxCocoa.framework binary size is so big?

### ISSUE THREAD

**Issue by foobra** [ReactiveX/RxSwift#895]
RxCocoa 1.6M
RxSwift 3.3M

Can I decrease them?

**Comment by foobra** [comment]
Will these whole framework will be included in the final ipa?

**Comment by foobra** [comment]
In static library way, all .a will merge into libPods.a(via cocoapods), and unused symbols will not link, so the actual size which include in the final ipa will much less than (1.6M+3.3M). But in dynamic framework way, these tow frameworks will entirely included in the final ipa, that will increase the size of app binary.

Am I misunderstood something? How can we decrease the binary size of RxSwift , I've tried git submodule but it is still output a dynamic framework. If I include all RxSwift files into my own project, will it decrease the binary size?

**Comment by kzaher** [comment]
Hi @foobra, 

I think this all depends on compiler optimizations. I guess it might work. We are also outputing bitcode, so I'm not sure what is the actual download size. 

Try uploading binary with and without Rx to test flight, I think there is actual download size there.
