### ISSUE TITLE
Question: "Splitting" a stream of values

### ISSUE THREAD

**Issue by keepingitneil** [ReactiveX/RxSwift#897]
I have a stream coming from a network and I want to do two different things with the data. Upon receiving data I want to:
1) map the values to a model that can be saved and doNext to save them.
2) map the values to a model that can be used by the UI and return this observable (shareReplay(1)) to be subscribed to in another part of the code.

I landed on something like this:
```           
 let observable = worker.performRequest(request).map { ($0, storeMapper($0)) }.do(onNext: {
                Store.sharedStore.saveEvents($0.1)
            }).map { homeMapper($0.0) }
            return observable.shareReplay(1)
```

Which works, but I'm not quite happy with it because I don't think it communicates what I'm doing. I would much prefer to so something like:

```
let observable = worker.performRequest(request)
observable.map(storeMapper).doNext { /*save the events*/ }
return observable.map(homeMapper).shareReplay(1)
```

But when I did that, the save events portion never ran. Can someone give me the play-by-play on why something like this wouldn't work. Nothing magical happening in performRequest by the way, just a vanilla observer.create {}

**Comment by kzaher** [comment]
Hi @keepingitneil ,

unless we have some self contained code that repros this, I'm not sure can we do something about this.

You can try to use `debug` operator and try to debug you issue that way.

**Comment by nero-tang** [comment]
I think what you could do is:
```swift
let response = worker.performRequest(request).shareReplay(1)

// Save the events
response.map(storeMapper).subscribeNext { /* Save the events */ }

// Update the UI
response.map(homeMapper).subscribeNext { /* Update UI */ }
```

**Comment by kzaher** [comment]
Hi @nero-tang ,

yes, probably :)

**Comment by keepingitneil** [comment]
Hey sorry, got caught up with a heavy work week. @nero-tang I don't quite want to do that because subscribeNext would trigger an HTTP request in my specific situation, right?

What I want is to return the observable so some other part of my app can trigger the HTTP call. But when it does, I would like the storeMapper to do its deal.

Hopefully you can infer what I'm intending to do with the following:
`let response = worker.performRequest(request)

// Save the events
response.map(storeMapper).doNext{ /* Save the events */ }

// Update the UI
response.map(homeMapper).subscribeNext { /* Update UI */ }.shareReplay(1)`

The goal is to inject some private doNext behavior in a stream that'll get called when I call subscribe later on. Does that make sense? I'll see if I can work up a better example when I get home.

**Comment by kzaher** [comment]
Hi @keepingitneil ,

I'm not sure what is wrong with your original solution:

```swift
let observable = worker.performRequest(request)
             .map(storeMapperSomething)
             .do(onNext: saveSomething)
             .map(homeMapper)
             .shareReplay(1)
```

It seems to me that it does exactly what you are describing.

> Which works, but I'm not quite happy with it because I don't think it communicates what I'm doing.

As far as I can tell it communicates exactly what you want

> I would much prefer to so something like

```
let observable = worker.performRequest(request)

// This line doesn't do anything, as far as I can tell it just creates definition and then discards it
observable.map(storeMapper).doNext { /*save the events*/ } 

return observable.map(homeMapper).shareReplay(1)
```

**Comment by nero-tang** [comment]
Hi @keepingitneil ,

Like @kzaher mentioned above:
```swift
observable.map(storeMapper).doNext { /*save the events*/ } 
```
This line is useless as the observable returned is not subscribed to, and the block in ```doNext``` won't even fire at all.

If you want the HTTP call gets trigger by other code, you can simply do something like this:
```swift
let response = triggerObservable
    .flatMap { worker.performRequest(request) }
    .shareReplay(1)

// Save the events
response.map(storeMapper).subscribeNext { /* Save the events */ }

// Update the UI
response.map(homeMapper).subscribeNext { /* Update UI */ }
```

**Comment by keepingitneil** [comment]
@kzaher the part of the original solution that I didn't like is having to map to a tuple the first time so as to keep the original data stream in tact.

@nero-tang hrmm yeah seems like the drawback of needing to subscribe on both separately is still there. I was wanting the /*save events*/ to happen when I subscribeNext on the /*update UI*/ portion. That's why I've been trying to steer my solutions towards doNext for that one.

Super appreciate the help guys. This isn't something that happens a lot in my codebase so I'll keep my original solution involving the tuple. Was really just wondering why the other wasn't working (which you guys answered) and if there was a better way to do it.
