### ISSUE TITLE
Unable to Install RxSwift on xcode 8 and swift 3.0

### ISSUE THREAD

**Issue by techmehra** [ReactiveX/RxSwift#898]
Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `RxCocoa`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'RxCocoa', '= 3.0.0-beta.1'`) or revert to a stable version by running `pod update RxCocoa`.

**Comment by dasoga** [comment]
Same for me.

**Comment by dasoga** [comment]
Hey @techmehra I complied my project:

I just add this to my Podfile

    pod 'RxSwift',    '~> 3.0.0-beta.1'
    pod 'RxCocoa',    '~> 3.0.0-beta.1'
    pod 'RxDataSources', '~> 1.0.0-beta.2'

I hope can help u.

**Comment by techmehra** [comment]
@dasoga I have already done this

**Comment by jondwillis** [comment]
Use Cocoapods 1.1.x

**Comment by kzaher** [comment]
`sudo gem install cocoapods --pre`

**Comment by techmehra** [comment]
done all thing
I am using cocoapods version 1.1.0 rc 2

**Comment by kzaher** [comment]
Hi @techmehra ,

then I would suggest cleaning all caches and trying on some other computer. It seems that this could be some local cache issue;

**Comment by kzaher** [comment]
I guess the gist would be:

* make sure you have CocoaPods 1.1.0.rc.2 `sudo gem install cocoapods --pre`
* make sure you've clean all of your caches (DerivedData, .cocoapods)

If that doesn't work, maybe some other pod is causing issues by specifying exact version, I would suggest:

* using fixed version 

```swift
pod 'RxSwift',    '3.0.0-beta.1'
pod 'RxCocoa',    '3.0.0-beta.1'
pod 'RxDataSources', '1.0.0-beta.2'
```

if that doesn't work, try using master branch directly

```swift
pod 'RxSwift',  :git => 'git@github.com:ReactiveX/RxSwift.git', :branch => 'master'
pod 'RxCocoa',   :git => 'git@github.com:ReactiveX/RxSwift.git', :branch => 'master'
pod 'RxDataSources', :git => 'git@github.com:ReactiveX/RxSwift.git', :branch => 'master'
```

Other then that, have no idea what could be wrong.

**Comment by kzaher** [comment]
Not sure what to do with this one. We've pushed some fix to `master` branch that could have fixed this.

#949

**Comment by SaraBasemAwad** [comment]
I am trying to configure RXSwift  using pods
- pods version : 1.1.1
- xcode version: 8.1
I used the below to do so:
# Uncomment the next line to define a global platform for your project
 # platform :ios, '9.0'
use_frameworks!

target 'YOUR_TARGET_NAME' do
	 pod 'RxSwift',    '~> 3.0'
	 pod 'RxCocoa',    '~> 3.0'
 

  # Pods for YOUR_TARGET_NAME

  target 'YOUR_TARGET_NAME' do
    inherit! :search_paths
    # Pods for testing
  end

end

 The following error has occurred: 
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
