### ISSUE TITLE
Swift 3.0 XCode 8 GM Error - Reactive<CLLocationManager> has no member

### ISSUE THREAD

**Issue by dcosson** [ReactiveX/RxSwift#900]
**Short description of the issue**:

I was able to build RxSwift 3.0.0-beta.1 with Carthage and Swift 3.0, and I'm going through my project updating the breaking changes (mostly just changing `rx_` to `rx.`).

With CLLocationManager this isn't working however, I get an error that the Reactive-wrapped location manager has no methods `didEnterRegion`, `didUpdateLocations`, etc. Looking at the CLLocationManagerDelegate docs, it doesn't look like these methods have changed.

I'm not getting these errors for any other uses of RxSwift (UITextField, UIButton, etc).

**Self contained code example that reproduces the issue**:

```swift
class LocationController: NSObject, CLLocationManagerDelegate {
    let locationManager = CLLocationManager()

    override init() {
        super.init()
        let status = CLLocationManager.authorizationStatus()
        locationManager.delegate = self
        if status != .authorizedAlways {
            locationManager.requestAlwaysAuthorization()
        }
        locationManager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
        locationManager.pausesLocationUpdatesAutomatically = true

        locationManager.startUpdatingLocation()
        locationManager.allowsBackgroundLocationUpdates = true
        locationManager.rx.didUpdateLocations.subscribeNext { locations in 
            for loc in locations {
                // .... do stuff with location
            }
       }
    }
````

**Xcode version**:

```
8.0
```

**Expected outcome**:

This should build correctly (and then trigger updates when I update locations).

**What actually happens**:

 Build error: `Value of type 'Reactive<CLLocationManager>' has no member 'didUpdateLocations'`

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (XCode 7.3.1 & XCode 8.0)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by azbuky** [comment]
I think CLLocationManager extension was moved to RXExample - #874

**Comment by dcosson** [comment]
@azbuky ah looks like you're correct, thanks.
