### ISSUE TITLE
pod lib lint with v3

### ISSUE THREAD

**Issue by pgherveou** [ReactiveX/RxSwift#903]
I am trying to publish and updated version of my [lib](https://github.com/pgherveou/rxpager) using 
RxSwift 3.0.0-beta.1 as a dependency 
but ``pod lib lint using `` fails with  xcodebuild errrors (I think its trying to build Rxswift…)

Does anyone know how to successfully lint a lib using RxSwift 3?

**Comment by sergdort** [comment]
Hi, @pgherveou, same here :) 
the problem with Cocoapods rather than with RxSwift. 
Seams like they don`t have for xcode8

**Comment by kzaher** [comment]
Hi @pgherveou,

I've had to use modified version of CocoaPods for Swift 3.0. You can find that version [here](https://github.com/kzaher/CocoaPods/tree/xcode8b6) .

1. Clone the repo
2. Build the binaries (I think you'll need to do something like `bundler install`, etc...)
3. Just use `$ [pathToClonedRepo]/bin/pod trunk push MyPod.podspec`

**Comment by pgherveou** [comment]
great thks for the tips @kzaher I will give it a try
By the way Are you interested in having this kind of handy operator under https://github.com/RxSwiftCommunity ?
