### ISSUE TITLE
invalid version string

### ISSUE THREAD

**Issue by tcurdt** [ReactiveX/RxSwift#904]
Cannot submit IPA with RxSwift to iTunes Connect

**Short description of the issue**:

When I am trying to submit an IPA to Apple that includes the framework (build with Carthage) I get:

```
ERROR ITMS-90060: "This bundle is invalid.

The value for key CFBundleShortVersionString '3.0.0-beta.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."
```

**Self contained code example that reproduces the issue**:

NA

**Xcode version**:

```
Xcode 8.0
Build version 8A218a
```

**Expected outcome**:

NA

**What actually happens**:

NA

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:

  - [ ] yes
  - [x] no

**Level of RxSwift knowledge**:

  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
https://github.com/ReactiveX/RxSwift/issues/878

**Comment by tcurdt** [comment]
I guess that's a duplicate of https://github.com/ReactiveX/RxSwift/issues/878
