### ISSUE TITLE
GitHub search example in Swift 3/RxSwift 3 not working correctly?

### ISSUE THREAD

**Issue by spilja** [ReactiveX/RxSwift#908]
**Is the GitHub search example working as it should in Swift 3/RxSwift 3?**:

  _I'm trying to work out how to autoload content when table has reached the bottom of the screen, but the example doesn't seem to be working. Whatever I type in to GItHub search example, I always get 30 repositories as a result. I would expect more to autoload as I get to the bottom of the view. _

**Xcode version**:

```
  8.0
```

**Expected outcome**:

_More than 30 repositories matching the search to appear, with more results loading as the bottom of the table is reached._ 

**What actually happens**:

_Whatever the search is, 30 results are returned and nothing happens once the bottom of the screen is reached. 30 results is also what's stated in the braces on top._

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @spilja ,

I'm having issues reproing this. Can you maybe tell me what are you searching for when it fails for you?

I've tried to search for `rx`, and it did load additional 30 results, so little confused.

¯\\\_(ツ)\_/¯

**Comment by spilja** [comment]
Ugh, I'm sorry, that was my fault, I added an Observable.never() in the concat, doh. 

Just so I'm not a total waste of time, it seems like there's a redundant isNearTheBottomEdge function in GitHubSearchRepositoriesViewController. There's also a UIScrollView extension in the same class that does the same thing.
