### ISSUE TITLE
Compile 'RxCocoa' still get error

### ISSUE THREAD

**Issue by HotWordland** [ReactiveX/RxSwift#909]
Xcode8 formal (not GM version) compile RxCocoa still get error like #899 

![image](https://cloud.githubusercontent.com/assets/6984865/18820072/caeda82a-83cc-11e6-8e0d-c30727a98bce.png)

and Does anyone know how to fix it ?

**Comment by kzaher** [comment]
Hi @HotWordland ,

could you maybe provide us with:
* xcode version
* cocoapods version
* podfile or cartfile

**Comment by HotWordland** [comment]
I check my cocoapods version is 1.0.1 , maybe old version lead to this error. Next I try to update the cocoapods version in 1.1.0.

**Comment by HotWordland** [comment]
@kzaher I check my cocoapods version is 1.0.1 , maybe old version lead to this error. Next I try to update the cocoapods version in 1.1.0.

**Comment by HotWordland** [comment]
@kzaher it's my problem i update my cocoapods version to 1.1.0 and fix it thanks 👍

**Comment by gurjitdhiman** [comment]
i have xcode 8
cocoapods 1.1.0.rc.2

still not working !!!
