### ISSUE TITLE
rx_ to new rx syntax for subjects

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#913]
I currently have a class which has an instance variable `let rx_scanning = PublishSubject<Bool>()`.

I was wondering if it was possible to update it to use the new Reactive syntax introduced in `3.0.0.alpha.1`? To make it `.rx.scanning`? 

I gave it an initial shot, with:

```
extension Reactive where Base: MyClass {
    var scanning: PublishSubject<Bool> {

    }
}
```

but I had absolutely no idea how to handle the memory with a subject instead of an observable in the extension.

**Comment by kzaher** [comment]
Hi @AndrewSB ,

If you want to go that road, you can Google for `get_associatedObject`. Example from RxSwift code base.

```swift
public var deallocated: Observable<Void> {
        return synchronized {
            if let deallocObservable = objc_getAssociatedObject(base, &deallocatedSubjectContext) as? DeallocObservable {
                return deallocObservable._subject
            }

            let deallocObservable = DeallocObservable()

            objc_setAssociatedObject(base, &deallocatedSubjectContext, deallocObservable, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
            return deallocObservable._subject
        }
    }
```

The simplest way is to just create a private property in MyClass and return it.

**Comment by JegnuX** [comment]
IMHO it doesn't make much sens to use `rx.` (or even `rx_`) prefix on custom types. This prefix is mostly necessary when extending third party types to avoid name collisions. (`textField.text` => `textField.rx.text`)

**Comment by AndrewSB** [comment]
hmm, interesting. @JegnuX that makes sense, I picked up on the convention after seeing it used so liberally in RxSwift & RxCocoa, but you're totally right.
