### ISSUE TITLE
Does Variable<> property support KVC mode?

### ISSUE THREAD

**Issue by SpiciedCrab** [ReactiveX/RxSwift#914]
We have our app programming in MVVM, so all the models from our services should be generated into their corresponding VMs.
Then we have a sample model:

```
public class Citys: MappableBaseModel {
    public var cityId : Int = 0
    public var cityName : String?
}
```

And VM with some properties in Variable<>
```
public class CityVM: BaseViewModel {
    public var cityId : Variable<Int>
    public var cityName : Variable<String>
}
```

And while converting, we need some common methods to do it for us since we may have a huge amount of conversions from Models to VMs.
The best way we can find is KVC, but the Variable<> properties seems not to be supported by KVC.
So any solutions for it ?

**Xcode version**:

```
Xcode 8.0

```

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] No

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] I have a small code base

**Comment by kzaher** [comment]
Hi @SpiciedCrab ,

> The best way we can find is KVC,

KVC is an old legacy mechanism that relies on dynamic properties of ObjC runtime. My advice is to avoid it where ever possible.

> but the Variable<> properties seems not to be supported by KVC.

Yes, variable already enables subscribing to changes, so KVC is redundant.

**Comment by SpiciedCrab** [comment]
Then if we want to convert all the properties in Citys model to Varaible<> properties in CityVM, we have to code like this？
```
cityVm.cityId = Variable<Int>(cityModel.cityId)
cityVm.cityName = Variable<String>(cityModel.cityName)
......

```

which seems to be not a simple way for all the models and the whole team....

**Comment by kzaher** [comment]
Hi @SpiciedCrab ,

that won't work, I you have old models written in objc and want to observe them, then you'll need to use KVO since there is no other way, but if you have new models in Swift, then you won't use KVO for them.
