### ISSUE TITLE
opt in to rx. syntax for non-NSObject classes?

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#916]
Currently, it seems as though classes that subclass NSObject are automatically opted in to the new `rx.` Reactive extension.

Can I extend a class that doesn't conform to NSObject - just a plain swift class - to the new Reactive syntax?

**Comment by kzaher** [comment]
Hi @AndrewSB ,
```
extension WhatEverYouWant: ReactiveCompatible { }
```

**Comment by AndrewSB** [comment]
perfect. 

I'm sorry about creating 3 separate issues for basically the same problem 😁

**Comment by eroth** [comment]
@kzaher 

A little late to this, but in regards to 

> Hi @AndrewSB ,
> 
> ```
> extension WhatEverYouWant: ReactiveCompatible { }
> ```

Can existing protocols be extended this way? I'm trying to do something like:
`MyProtocol: ReactiveCompatible {}` but am getting `Extension of protocol 'MyProtocol' cannot have an inheritance clause`.  Thanks!

**Comment by freak4pc** [comment]
Extending protocols is much trickier for the most part.
