### ISSUE TITLE
Build fails with No such file or directory message

### ISSUE THREAD

**Issue by serluca** [ReactiveX/RxSwift#918]
**Short description of the issue**:
I have a xcode run script phase that converts the xcode tags `TODO:` and `FIXME:` in xcode warnings that fails 

**Self contained code example that reproduces the issue**:
To reproduce add a new xcode `Run Script Phase` on the app target (as explained [here](https://bendodson.com/weblog/2014/10/02/showing-todo-as-warning-in-swift-xcode-project/)), then try to build
```sh
TAGS="TODO:|FIXME:"
echo "searching ${SRCROOT} for ${TAGS}"
find "${SRCROOT}" \( -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
```

**Xcode version**:

```
8.0
```

**Expected outcome**:

I expect the project to build

**What actually happens**:

The build fails with the following message:
```
egrep: /Users/.../Carthage/Checkouts/RxSwift/Sources/RxSwift/NAryDisposable.swift: No such file or directory
egrep: /Users/.../Carthage/Checkouts/RxSwift/Sources/RxSwift/Observable+Extensions.swift: No such file or directory
```
**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Comment by serluca** [comment]
Here a temporary solution in case someone is having the same issue I have,

Replace the script with the following one: 
```
TAGS="TODO:|FIXME:"
echo "searching ${SRCROOT} for ${TAGS}"
find "${SRCROOT}" ! -path "*/Carthage/*" \( -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
```

**Comment by kzaher** [comment]
Hi @serluca ,

We've currently released beta build, so yes, there are some TODOs inside of the repo.

I think your checks are definitely cool, and love them, but I wouldn't suggest performing them on code you don't control since they could be there for multiple reasons.

Thnx for reporting this and reminding us of this, but it doesn't look like a bug in framework to me. 

¯\\\_(ツ)\_/¯

**Comment by scottrhoyt** [comment]
I add my Carthage/Checkouts directory my repo, and I've noticed similar problems. When I go to stage those files, git complains that the files cannot be found. Navigating to the files in Finder, they appear to be there but attempting to open them results in a similar error.

FWIW, this is on `3.0.0-beta.1` and the framework still seems to build without errors.

**Comment by scottrhoyt** [comment]
Looks like it's possibly a problem with some broken (or obsolete) symbolic links?

**Comment by serluca** [comment]
HI @kzaher 

Thanks for getting back to me, I know it's a beta and I shouldn't search on code out of my control. 
The issue I was mentioning was not about the warning script (that it is easy to fix) but as @scottrhoyt said about broken links.

It seems that those files where I receive the error:
```
NAryDisposable.swift
Observable+Extensions.swift
```
are broken symbolic links.

Thanks for the great job you are doing here :)

**Comment by kzaher** [comment]
Oh, I think I now understand what you are saying.

This is part of issues with Swift Package Manager https://github.com/ReactiveX/RxSwift/issues/846

We'll fix it.

**Comment by kzaher** [comment]
This should be fixed now.

**Comment by scottrhoyt** [comment]
Thanks!
