### ISSUE TITLE
CompositeDisposable should not dispose a disposable when removing it by its key.

### ISSUE THREAD

**Issue by c0diq** [ReactiveX/RxSwift#919]
**Short description of the issue**:

`CompositeDisposable` is disposing of the disposable automatically when removing it by its key.

**Self contained code example that reproduces the issue**:

```swift
return Observable<Session>.create { observer in
    let disposable = CompositeDisposable()

    // Disconnect immediately if disposal occurs before sending the session.
    let disconnectDisposableKey = disposable.insert {
        // BUG: This gets invoked when `disposable.remove(for: disconnectDisposableKey)` is called below
        connection.disconnect()
    }

    let sessionDisposable = connection.establishSession()
        .do(onNext: { _ in
            // Now that a session is successfully established, it becomes the
            // caller's responsibility to disconnect its underlying connection.
            // BUG: Removing will invoke the AnonymousDisposable above and 
            // disconnect the connection.
            disposable.remove(for: disconnectDisposableKey)
        })
        .subscribe(observer)

    disposable.insert(sessionDisposable)
    return disposable
}
```

**Xcode version**:

```
Xcode 8
```

**Expected outcome**:

Calling `remove(for:)` should not dispose the underlying disposable but only return it. It should be the caller responsibility to decide if the disposable should be disposed.

**What actually happens**:

The disposable removed is disposed.

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [X] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [X] I have a small code base
  - [ ] I have a significant code base

**Comment by fpillet** [comment]
Comment in the code is clear about it: when removing a disposable, it gets disposed. The behavior you want calls for a separate API that removes the disposable without immediately disposing it. Current behavior matches those in other Rx implementations (RAC diverges on many fronts).

**Comment by c0diq** [comment]
I found a workaround
```
return Observable<Session>.create { observer in
    let disposable = CompositeDisposable()

    var connectionDisposable: Disposable? = Disposables.create {
        connection.disconnect()
    }

    // Disconnect immediately if disposal occurs before sending the session.
    disposable.insert {
        connectionDisposable?.dispose()
    }

    let sessionDisposable = connection.establishSession()
        .do(onNext: { _ in
            connectionDisposable = nil
        })
        .subscribe(observer)

    disposable.insert(sessionDisposable)
    return disposable
}
```
