### ISSUE TITLE
Is possible to avoid [weak self] in strong references?

### ISSUE THREAD

**Issue by zbangsatz** [ReactiveX/RxSwift#920]
RxSwift is awesome. I really really like to use it in all my projects. But I have a question:

**- Is possible to avoid [weak self] in strong references and no leak memories?**

Ex:
self.textField.rx_text
.subscribeNext({ 
// do something without [weak self]
})
.addDisposable(disposeBag)

**Comment by sergdort** [comment]
There is weakify extension [here](https://github.com/RxSwiftCommunity/RxSwiftExt/blob/master/Source/ObservableType%2BWeak.swift)

**Comment by zbangsatz** [comment]
Thank you. Very useful. Do you have any suggestions or libraries?

**Comment by sergdort** [comment]
Not sure what do you mean 🙂?

**Comment by zbangsatz** [comment]
Suggestion about useful libraries like RxSwiftExt. I'm newbie

**Comment by sergdort** [comment]
I would suggest you to take a look on libraries ander RxSwiftComunity and pick what you like and need
