### ISSUE TITLE
Observable.using

### ISSUE THREAD

**Issue by pgherveou** [ReactiveX/RxSwift#921]
Hi there,
Is there a simpler way to use  **Observable.using**?

I want to create a Resource Factory using the disposable created by a subscription.

I came up with the following solution where I had to create a custom AnyDisposable.

Is there some simpler solution I could use here?
or would it make sense to add a AnyDisposable class to the framework? 

```swift
import PlaygroundSupport
import RxSwift

PlaygroundPage.current.needsIndefiniteExecution = true

class AnyDisposable: Disposable {
  let _dispose: () -> Void

  init(_ disposable: Disposable) {
    _dispose = disposable.dispose
  }

  func dispose() {
    _dispose()
  }
}

let infiniteInterval$ = Observable<Int>
  .interval(0.1, scheduler: MainScheduler.instance)
  .do(
    onNext: { print("infinite$: \($0)") },
    onSubscribe: { print("subscribe to infinite$")},
    onDispose: { print("dispose infinite$")}
)

let limited$ = Observable<Int>
  .interval(0.5, scheduler: MainScheduler.instance)
  .take(2)
  .do(
    onNext: { print("limited$: \($0)") },
    onSubscribe: { print("subscribe to limited$")},
    onDispose: { print("dispose limited$")}
)

let o: Observable<Int> = Observable.using({ () -> AnyDisposable in
  return AnyDisposable(infiniteInterval$.subscribe())
  }, observableFactory: { _ in return limited$ }
)
o.subscribe()

// print 
// subscribe to infinite$
// subscribe to limited$
// infinite$: 0
// infinite$: 1
// infinite$: 2
// infinite$: 3
// infinite$: 4
// limited$: 0
// infinite$: 5
// infinite$: 6
// infinite$: 7
// infinite$: 8
// infinite$: 9
// limited$: 1
// dispose limited$
// dispose infinite$
```

**Xcode version**:

```
  Xcode 8
```
**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
> Is there some simpler solution I could use here?

I'm not sure what are you trying to accomplish.

Could you please explain your original problem?

**Comment by pgherveou** [comment]
I was trying to subscribe to a stream that retrieves newsfeed updates and store them in a cache while I am scrolling a stream of existing newsfeed

Initially I thought I could do something like this: 
```swift
Observable.using({ storeFeedUpdates$.subscribe() }, observableFactory: { $readNewsFeed })
```

**Comment by kzaher** [comment]
@pgherveou Hm, there are probably other ways how one could model this more elegantly but would probably require a lot of other changes in your system and a lot more time from my side that I unfortunately don't have :) 

Maybe somebody else on slack channel can brainstorm on this, or provide some other solutions here. ¯\\\_(ツ)\_/¯  

I'm sure that with time you'll find some nicer solutions, and since this is not an issue with library, closing this one.
