### ISSUE TITLE
Convert a Subject to a Driver

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#922]
Is there a subject that behaves similarly to a driver? As in it can't take an error?

Currently I have some `PublishSubject`s that I only pass `.next` events to, and I pass them to views as `Driver`s by:

```
let scanning = PublishSubject<Bool>()
let scanningDriver = scanning.asDriver { _ in assertionFailure(); return .never() }
```

Is there anyway for me to compose the same logic without an assertionFailure?
IMHO it makes sense to leverage the compiler here, to make it impossible for me to `on(.error)` to my scanning `PublishSubject`, instead of me remembering that that shouldn't be allowed

**Comment by kzaher** [comment]
Hi @AndrewSB ,

you can easily create your own concept based on `PublishSubject` that does that. Please take a look at how we've wrapped `BehaviorSubject` inside `Variable`.

I guess we can maybe add an `Event` to `RxCocoa`.

**Comment by AndrewSB** [comment]
Hey @kzaher, yeah. I understand it would be just like `Variable`, another wrapper for a subject. I'd love to take a shot at implementing, I'll start a Pull Request soon!

**Comment by AndrewSB** [comment]
Yeah, I just tried to create the `Event` subject, Xcode complained:
<img width="727" alt="screen shot 2016-10-06 at 6 20 14 pm" src="https://cloud.githubusercontent.com/assets/3814772/19176112/a2f5b93e-8bf1-11e6-9fa3-3f42cbbdbf8f.png">

**Comment by patrickbdev** [comment]
@AndrewSB is there any update on this feature? This would be incredibly useful.

**Comment by AndrewSB** [comment]
Yup @patrickbdev! This was superseded by #928. It looks like @DenHeadless is pretty interested in helping out too. Maybe we can take a shot at implementing it together 😄
