### ISSUE TITLE
Timeframe for RxSwift 3.0?

### ISSUE THREAD

**Issue by lizixroy** [ReactiveX/RxSwift#924]
It seems that the latest version is RxSwift 3.0 beta. When will a stable version of RxSwift 3.0 be released? 

Thanks!

**Comment by kzaher** [comment]
Hi @lizixroy ,

What a perfect moment to retweet 😀 
https://twitter.com/RxSwiftLang/status/783365438180818944

The tweet says "soon". If electric eel says so, we have to trust it. I don't think eels know how to lie.

I'm also curious when will it be released 😀

**Comment by rlam3** [comment]
Would love to see this release soon. Or is there a workaround to use moya and rxswift when using xcode 8 and swift 3.0? Thanks!

**Comment by kzaher** [comment]
Just released.
