### ISSUE TITLE
Observable.using does not accept resourceFactory of type () -> Disposable

### ISSUE THREAD

**Issue by DrBreen** [ReactiveX/RxSwift#925]
When using operator `Observable.using` compile time error is reported when `resourceFactory` type is `() -> Disposable`. If, however, the closure type is of concrete type - for example, `() -> AnonymousObservable` or `() -> Resource`, where `Resource` conforms to `Disposable` protocol - then no compile error is reported.

**Self contained code example that reproduces the issue**:

```
let observable = Observable<Int>.never()

        let anonymousDisposableAsDisposableResourceFactory = { () -> Disposable in
            return AnonymousDisposable {
                print("AnonymousDisposable disposed")
            }
        }

        let disposablesCreateAsDisposableResourceFactory = { () -> Disposable in
            return Disposables.create {
                print("Disposable from Disposable.create disposed")
            }
        }

        let anonymousDisposableAsAnonymousDisposableResourceFactory = { () -> AnonymousDisposable in
            return AnonymousDisposable {
                print("AnonymousDisposable disposed")
            }
        }

        let anonymousDisposableAsCancelableDisposableResourceFactory = { () -> Cancelable in
            return AnonymousDisposable {
                print("AnonymousDisposable disposed")
            }
        }


        let usingResourceObservable0 = Observable<Int>.using(anonymousDisposableAsAnonymousDisposableResourceFactory, observableFactory: { disposable in observable }) //ok
        let usingResourceObservable1 = Observable<Int>.using(anonymousDisposableAsDisposableResourceFactory, observableFactory: { disposable in observable }) //compilation error
        let usingResourceObservable2 = Observable<Int>.using(disposablesCreateAsDisposableResourceFactory, observableFactory: { disposable in observable }) //compilation error
        let usingResourceObservable3 = Observable<Int>.using(anonymousDisposableAsCancelableDisposableResourceFactory, observableFactory: { disposable in observable }) //compilation error
```

**Xcode version**:

```
Xcode 8.0
```

**Expected outcome**:

`usingResourceObservable1`, `usingResourceObservable2` and `usingResourceObservable3` should not cause compilation errors.

**What actually happens**:

`usingResourceObservable1`, `usingResourceObservable2` and `usingResourceObservable3` cause compilation errors.

**Installation method**:
- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**I have multiple versions of Xcode installed**:
- [ ] yes (which ones)
- [x] no

**Level of RxSwift knowledge**:
- [ ] just starting
- [ ] I have a small code base
- [x] I have a significant code base

**RxSwift version**:
3.0.0-beta.2

**Comment by kzaher** [comment]
Hi @DrBreen ,

yes, this is a consequence of `using` extension method description.

I think people are requesting this one a lot recently. I can't think of a reason why not to do this...., so we'll try to make this to work.

**Comment by DrBreen** [comment]
Great, glad to hear that. By the way, Swift 2.0 version of `Observable.using` works fine.

**Comment by kzaher** [comment]
Hi @DrBreen ,

I've tried to investigate this, but I couldn't find any trivial workarounds for this. It looks like this has changed with language.

I don't understand why this wouldn't work. Maybe this is just a temporary compiler bug.

**Comment by mono0926** [comment]
Same here: https://gist.github.com/mono0926/78bf126d9bd887276793410890c44e38

**Comment by kzaher** [comment]
This is also frustrating to me, but I don't see any elegant solutions for this. I've tried some workarounds but none of them quite worked out.

If somebody sees any way how to solve this in a simple way, feel free to make a PR.

The situation is somewhat similar to `retryWhen` operator, but it seems that `Swift.Error` treatment is special.
