### ISSUE TITLE
Project "Preprocessor.xcodeproj" has no shared schemes

### ISSUE THREAD

**Issue by lfaoro** [ReactiveX/RxSwift#93]
Cartfile statement: `github "ReactiveX/RxSwift" "rxswift-2.0"`
Performing a `carthage update --platform mac` this error appears: `Project "Preprocessor.xcodeproj" has no shared schemes`

Opening the .xcworkspace and adding the Shared flag to Preprocessor in the schemes, fixes this issue.

**Comment by kzaher** [comment]
Hi @lfaoro,

Carthage is having issues resolving multiple targets inside the same repository. Even if we've added that, it still wouldn't know how to build targets properly as far as I'm aware of.

We've had to create separate branches for RxSwift 1.* to be able to somehow integrate with Carthage.

We'll probably also do the same for RxSwift 2.0 version, but it's still in kind of preview mode, so fixing carthage build hasn't been our focus for the time being :)
