### ISSUE TITLE
ConcurrentDispatchQueueScheduler behavior

### ISSUE THREAD

**Issue by pgherveou** [ReactiveX/RxSwift#936]
**Short description of the issue**:
On the latest beta, When using a Concurrent Dispatch Queue, the sequence emit a few times but never complete.

**Self contained code example that reproduces the issue**:

```swift
import Foundation
import PlaygroundSupport
import RxSwift

PlaygroundPage.current.needsIndefiniteExecution = true

let queue = DispatchQueue(
  label: "Test",
  attributes: .concurrent // commenting this to use a serial queue remove the issue
)

let scheduler: SchedulerType = ConcurrentDispatchQueueScheduler(queue: queue)

func makeSequence(label: String, period: RxTimeInterval) -> Observable<Int> {
  return Observable<Int>
    .interval(period, scheduler: scheduler)

    // note in this simplifed snippet, share is useless
    .shareReplay(1) // commenting this remove the issue,
}

let _ = makeSequence(label: "main", period: 1.0)
  .flatMapLatest { (index: Int) -> Observable<(Int, Int)> in
    return makeSequence(label: "nested", period: 0.2).map { (index, $0) }
  }
  .take(10)
  .mapWithIndex { ($1, $0.0, $0.1) }
  .subscribe(
    onNext: { print("\($0.0) emit (main: v\($0.1), nested: v\($0.2))") },
    onCompleted: { print("completed") }
)
```

**Xcode version**: 

```
8.0
```

**Expected outcome**:

it should print
```
0 emit (main: v0, nested: v0)
1 emit (main: v0, nested: v1)
2 emit (main: v0, nested: v2)
3 emit (main: v0, nested: v3)
4 emit (main: v1, nested: v0)
5 emit (main: v1, nested: v1)
6 emit (main: v1, nested: v2)
7 emit (main: v1, nested: v3)
8 emit (main: v2, nested: v0)
9 emit (main: v2, nested: v1)
completed
```
**What actually happens**:
It prints 
```
0 emit (main: v0, nested: v0)
1 emit (main: v0, nested: v1)
2 emit (main: v0, nested: v2)
3 emit (main: v0, nested: v3)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @pgherveou ,

I'll investigate this. I have some ideas what could be happening.

**Comment by kzaher** [comment]
Hi @pgherveou,

I've pushed my attempt to repro this, but I was unable to. The code and unit tests look good too. It seems that maybe you have disposed dispose bag prematurely.

**Comment by kzaher** [comment]
Anybody else can repro this?

**Comment by pgherveou** [comment]
Sorry about the slow response.
I just ran the code in a playground again a few times
it works most of the time but I also got the same unexpected results a few time
Could it be an issue with Playground?

Here is the project I created 
https://www.dropbox.com/sh/hjzkeffr5jplm04/AAA_PnciCTpR0zGopUg2VK4oa?dl=0

**Comment by kzaher** [comment]
Hi @pgherveou ,

thnx for awesome repro steps. I've finally managed to repro it and fix it. 

Pushed fix to master branch. Feel free to reopen the issue if you can still repo this.

**Comment by pgherveou** [comment]
Hi @kzaher just updated the sample project to 3.0 and it fixed the issue! 
Thanks again for the great work. 

Do you have any tips to debug this kind of issues, hopefully next time I can send you a PR instead of a simple sample project!
