### ISSUE TITLE
Retry failed observables in a chain

### ISSUE THREAD

**Issue by ngocluu** [ReactiveX/RxSwift#943]
I have the following observable create functions:

```
func createO1() -> Observable<Void> { ... }
func createO2() -> Observable<Void> { ... }
func createO3() -> Observable<Void> { ... }
func createO4() -> Observable<Void> { ... }
func createO5() -> Observable<Void> { ... }
```

```
let output = createO1().flatMap { createO2() }.flatMap { createO3() }.flatMap { createO4() }.flatMap { createO5() }
output.subscribe(...)
```

`output` is a chain of o1...o5.

I need this behavior: if one of the observables in the chain failed (o1...o5), that observable should be retried, only that failed observable, not retry whole chain.

I don't want to apply `retry` operator to each function `createON`, because if they are used in another context, they should not retry.
I know I can apply `retry` to each createON() in the above chain, but there are any ways/operators to apply that retry behavior to the `output` observable instead?

**Comment by kzaher** [comment]
Hi @ngocluu ,

I'm assuming you maybe want to do something like

```swift
Observable.concat([createO1(), createO2(), createO3()].map { $0.retry() }])
```

**Comment by ngocluu** [comment]
Thanks @kzaher!
