### ISSUE TITLE
Type 'inout UITextField' does not conform to protocol 'ReactiveCompatible'

### ISSUE THREAD

**Issue by Dharin-shah** [ReactiveX/RxSwift#944]
:warning: If you don't have something to report in the following format, it will probably be easier and faster to ask in the [slack channel](http://http://slack.rxswift.org/) first. :warning: 

**Short description of the issue**:
Previously in swift 2.x I was using
`someTextField.rx_text`

Then it Changed to (in swift 3.0 update)
`someTextField.rx.textInput.text`

But now it is giving me this error

when I updated (from pods)
RxCocoa 3.0.0-rc.1 (was 3.0.0-beta.2)
RxSwift 3.0.0-rc.1 (was 3.0.0-beta.2)
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
// `Self contained code example` means:
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**Xcode version**:

```
  Xcode version goes here
```

**Expected outcome**:

  _what you expect to happen goes here_

**What actually happens**:

  _what actually happens goes here_

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [*] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [*] I have a significant code base

**Comment by Dharin-shah** [comment]
RxCocoa now provides optional string. Which is why i was getting this error.

**Comment by wangbourne** [comment]
so what's the solution?

**Comment by Dharin-shah** [comment]
My **function** wasn't expecting a Driver of Optional String, which is why it game me this error. 
`someTextfield.rx.text.asDriver()` returns Driver<String?>
`someTextfield.rx.text()` returns Observable<String?>

**Comment by wangbourne** [comment]
SomeTextfield.rx.text() is not recognized. Appreicate if you could  let me know how I can achieve it. 

![image](https://cloud.githubusercontent.com/assets/2090084/20048500/c5d8248e-a508-11e6-80a3-f57b8dff3e58.png)

**Comment by Dharin-shah** [comment]
Whhoopsie, My Bad
its just `firstName.rx.text` and **not** `firstName.rx.text()`

**Comment by xnxin** [comment]
I have the same issue, I cpoy the code from demo, I don`t understand why. how do you solve this problem

**Comment by xnxin** [comment]
Well, the demo`s parameter is Observable<String>, but when textField.rx.text.asObservable() is  Observable<String?>, so i modify the parameter to Observable<String?> , it working.

**Comment by Dharin-shah** [comment]
You can use the ControlProperty<String> as an observable since it wraps an observable for that property. Therefore you can subscribe to it just as you subscribe to an Observable.

Here's a gist (commented in the code where ControlProperty is defined)
> 
> Initializes control property with a observable sequence that represents property values and observer that enables
>      binding values to property.
> 
>      - parameter values: Observable sequence that represents property values.
>      - parameter valueSink: Observer that enables binding values to control property.
>      - returns: Control property created with a observable sequence of values and an observer that enables binding values
>      to property.

**Comment by xnxin** [comment]
@Dharin-shah ,thanks, I`ll try this later, and there is any document to introduce how to extend Reactive for struct type?

**Comment by aksswami** [comment]
I am trying to get observable string from searchBar but I am constantly getting this error. Any help will be appreciated. 
```
 var latestRepositoryName: Observable<String> {
        return searchBar.rx
            .text.asObservable()
            .throttle(0.5, scheduler: MainScheduler.instance)
            .distinctUntilChanged
    }
```

I am getting error `Type 'inout UISearchBar' does not conform to protocol 'ReactiveCompatible'`.

**Comment by sergdort** [comment]
Damn Swift compiler!! 😄
This is because `rx.text` is `ControlProperty<String?>` you need to apply `map`
@kzaher I see a lot of confusion lately, because we decided to be consistent with UIKit, 
I remember we had a discussion with you about it in slack but I don't remember how it's ended 🙂

**Comment by aksswami** [comment]
Thanks @sergdort 

Resolved it using RxOptional `filterNil()` transformer.

**Comment by Dharin-shah** [comment]
latestRepositoryName must be of type 
`Observable<String?>` or you must explicitely handle it here by using map function and passing you handler to handle optional string
For eg:
`var latestRepositoryName : Observable<String>{
        return searchBar.rx.text.throttle(0.5, scheduler : MainScheduler.instance).map(){text -> String in
           if(text == nil){
             return ""
          }else{
       return text!
   }

}
}`

**Comment by rlam3** [comment]
I'm having a similar issue with searchBar...

Was wondering if anybody could give me some pointers on this issue. I need to get the term from search bar and then launch a backend request to server then reload my data. 

But I keep getting the following error on rx.text

```
'inout UISearchBar' does not conform to protocol 'ReactiveCompatible'
```

```swift
 // Rx 
    var latestSearchTerm: Observable<String?>{
        return searchBar.rx.text
            .throttle(0.5, scheduler: MainScheduler.instance)
            .distinctUntilChanged()
            .filterNil()
            .flatMap{ text in
                return text
            }
    }
```

I'm on XCode 8 and Swift 3

Thanks!

**Comment by Dharin-shah** [comment]
Filternil might be an issue
Try removing it

**Comment by rlam3** [comment]
@Dharin-shah Thanks for quick reply. I tried this but is giving me the same issue. 

```swift
        return searchBar.rx.text.orEmpty
            .throttle(0.5, scheduler: MainScheduler.instance)
            .distinctUntilChanged()
            .flatMapLatest{ text -> Observable<String> in
                
                if text.isEmpty{
                    return .just("")
                }
                
                return text
            }
```

**Comment by Dharin-shah** [comment]
Are you still returning observable<string?>

**Comment by Dharin-shah** [comment]
Oops my mistake

**Comment by rlam3** [comment]
@Dharin-shah I'd like it to be Observable<String?> but if It is ... the error still persists...

**Comment by Dharin-shah** [comment]
Why are you flat maping .. if you want string? Observable just return without the flat map and change the return type to string? Observable

**Comment by rlam3** [comment]
@Dharin-shah Not sure what you are referring to. Do you mind showing me in  a code comparison? Thanks!

**Comment by Dharin-shah** [comment]
Forgive me if i seem ignorant , its just that i am on my phone and cant really test . Once i get back to my laptop will surely check your code.

**Comment by amirpervaiz086** [comment]
@xnxin  meaning asObservable requires optional observable as input? as you said you changed it to <String?> I was facing same issue and had to convert my input observable to <String?> from <String>. Just want to clear concept why it is required. Thanks in advance
