### ISSUE TITLE
Argument labels '(onNext:)' do not match any available overloads

### ISSUE THREAD

**Issue by JunDang** [ReactiveX/RxSwift#946]
**Short description of the issue**:

  Can not compile with RxCocoa

![screen shot 2016-10-19 at 10 15 12 pm](https://cloud.githubusercontent.com/assets/8404682/19544071/3f49a57c-964a-11e6-81b3-631b4a949aa2.png)

**Xcode version**:
Xcode 8.0 and Swift 3.0
```
**Installation method**:
  - CocoaPods 1.1.0
  

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
    - no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - just starting

**Comment by kzaher** [comment]
Hi @JunDang ,

did you add 
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
```
to your Podfile?

**Comment by JunDang** [comment]
@kzaher
I have added the codes you provided above and here is my Podfile looks like:
---------------------------------------
use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end

target ‘HuaLongTianShiUserVersion’ do
    #pod 'Cartography', :git => "https://github.com/robb/Cartography.git", :tag => '0.6.0'
    pod 'Cartography', :git => 'https://github.com/mluisbrown/Cartography.git', :branch => 'swift3'
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', '~> 3.1.1’
    pod 'WeatherIconsKit', :git => 'git@github.com:gscalzo/WeatherIconsKit.git'
    pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
    pod 'RxSwift',    '~> 3.0.0-rc.1’
    pod 'RxCocoa',    '~> 3.0.0-rc.1’
   # pod 'Charts'
    #pod 'Auk', '~> 2.1'
    pod 'AMap2DMap' 
    pod 'AMapSearch' 
end
------------------------------------------
However the same problem exist. Please help. Thank you very much!

**Comment by kzaher** [comment]
Hi @JunDang ,

can you please try to use `master` branch. We've pushed some fix there that could have fixed this. There were issues with casing in includes.

#949

**Comment by JunDang** [comment]
@kzaher
Hello,
   Can you let me know the command for master branch? 
   I have tried to use:
   pod ‘RxCocoa’, :git => ‘git@github.com:ReactiveX/RxSwift/RxCocoa.git’
  but it did not work.

    Thank you very much!

**Comment by kzaher** [comment]
You can reference master branch with 
```
pod ‘RxCocoa’, :git => ‘git@github.com:ReactiveX/RxSwift/RxCocoa.git’, :branch => 'master'
```

... but you can might as well just try 3.0.0 version.

**Comment by JunDang** [comment]
@kzaher 
Thank you for your help! So I have installed 3.0.0 with pod and the issues did not show up anymore.
However, I have another issue, it says that "use of unresolved identifier NopDisposable"
I have imported RxSwift and RxCocoa. Please help!

![screen shot 2016-10-28 at 2 14 38 pm](https://cloud.githubusercontent.com/assets/8404682/19817361/4644789a-9d19-11e6-8870-383b4a04e1eb.png)

**Comment by kzaher** [comment]
`Disposables.create()`

**Comment by 1cookspe** [comment]
It says that 

`pod ‘RxCocoa’, :git => ‘git@github.com:ReactiveX/RxSwift/RxCocoa.git’, :branch => 'master'` 

does not exist. Has RxCocoa been moved?
