### ISSUE TITLE
 Documentation in UITableView+Rx.swift is incorrect.

### ISSUE THREAD

**Issue by RoryKelly** [ReactiveX/RxSwift#947]
**Short description of the issue**:

 Documentation in UITableView+Rx.swift is incorrect. i.e tableView.dequeueReusableCell(withIdentifier:.. vs tableView.dequeueReusableCellWithIdentifier(..

**Comment by kzaher** [comment]
Hi @RoryKelly ,

Pushed a fix for this, should be ok now.
