### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by XXboy** [ReactiveX/RxSwift#948]
**Short description of the issue**:

  _crash anywhere_
<img width="863" alt="2016-10-20 23 20 39" src="https://cloud.githubusercontent.com/assets/22525292/19566627/99f4f746-971d-11e6-87f6-b5680aa0bd9b.png">

**Self contained code example that reproduces the issue**:

```swift
  forgotButton.rx.tap
            .subscribe(onNext: { self.fogotPassword() })
            .addDisposableTo(DisposeBag())
```
 

**Xcode version**:

```
  Xcode8.0
```

**Expected outcome**:

  _don't crash_

**Installation method**:
  - [x] Carthage

**I have multiple versions of Xcode installed**:
  - [x] no

**Level of RxSwift knowledge**:
  - [x] I have a small code base

**Comment by kzaher** [comment]
Hi @XXboy,

I think this might be something on your end or Swift compiler. RxExample app inside this repo is full of code that looks like that and doesn't crash.

I've noticed that you are using `DisposeBag` in a wrong way, but that shouldn't cause this.

Have you tried clearing Carthage cache?

**Comment by XXboy** [comment]
Hi @kzaher ,
   I try on my friend's Mac, and doesn't crash. But test() method never called.
<img width="681" alt="rxswift_error" src="https://cloud.githubusercontent.com/assets/22525292/19585112/5a1504cc-977c-11e6-8464-29446d3a5b7d.png">

**Comment by XXboy** [comment]
Hi @kzaher ,
Thank you!
I try on my friend's Mac, it's okay. My mac is macOS Sierra 10.12.1 Beta, and my firend is macOS Sierra 10.12

**Comment by kzaher** [comment]
@XXboy ¯\\\_(ツ)\_/¯ 

I would assume this is because of `10.12.1 Beta`. Have no idea why, but it would be weird if this was repo step :) Lot of apps would crash :)

I think we can close this for now. If we'll have some new data, we can reopen this.
