### ISSUE TITLE
"include/_RXObjcRuntime.h" not found

### ISSUE THREAD

**Issue by bitkill** [ReactiveX/RxSwift#949]
**Short description of the issue**:

  Cannot compile via carthage, 

**Expected outcome**:

  Generate a RxCocoa.framework

**What actually happens**:
```

--- xcodebuild: WARNING: Unable to open project file '/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/duh/Library/Developer/Xcode/DerivedData/Rx-hawhizdyzypcbzejdlhpvmtjimuk/Build/Intermediates/Rx.build/Release-iphoneos/RxCocoa-iOS.build/Objects-normal/armv7/_RXObjCRuntime.o RxCocoa/Runtime/_RXObjCRuntime.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/RxCocoa/Runtime/_RXObjCRuntime.m:16:9: fatal error: 'include/_RXObjcRuntime.h' file not found
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxCocoa-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/duh/Desktop/guide/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/duh/Library/Developer/Xcode/DerivedData/Rx-hawhizdyzypcbzejdlhpvmtjimuk/Build/Intermediates/Rx.build/Release-iphoneos/RxCocoa-iOS.build/Objects-normal/armv7/_RXObjCRuntime.o RxCocoa/Runtime/_RXObjCRuntime.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Self contained code example that reproduces the issue**:

```cartfile
github "Alamofire/Alamofire" "4.0.1"
github "hkellaway/Gloss" "1.0.0"
github "CosmicMind/Material" "2.2.2"
github "ReactiveX/RxSwift" "3.0.0-rc.1"
github "RxSwiftCommunity/RxDataSources" "1.0.0-rc.2"
github "RxSwiftCommunity/RxAlamofire" "3.0.0-rc.2"
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

3.0.0-rc.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 8.0 (8A128a)
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by bitkill** [comment]
just found out that the error is because I have a case-sensitive filesystem.
There is a typo in https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Runtime/_RXObjCRuntime.m#L16

changed from
`#import "include/_RXObjcRuntime.h"`
to
`#import "include/_RXObjCRuntime.h"`

It's working for me now

**Comment by kzaher** [comment]
Hi @bitkill ,

This should be fixed now. I've pushed a patch to master. Feel free to reopen this issue if it's not fixed.
