### ISSUE TITLE
Clarify the difference between Functional Reactive Programming and RxSwift

### ISSUE THREAD

**Issue by bontoJR** [ReactiveX/RxSwift#95]
This topic has been something hot for me in the last week, the generale feeling around RxSwift is that this framework is *Functional Reactive Programming*, which, by definition is not.

I think a clarification somewhere in the documentation would help to wipe the general initial confusion that some newcomers are facing. The big issue I am reading on twitter and some articles about Rx is that the FRP (and the association with RAC) is causing a lot of confusion about terminology: Observable and Observer for RX and Behaviour/Signal and Event for FRP.

I created a [PR for this](https://github.com/ReactiveX/RxSwift/pull/94), feedbacks are welcomed.

**Comment by kzaher** [comment]
Yeah, I think we should clarify the difference. I think it would be fair to Conal. I'll not by comments in PR.

**Comment by innocarpe** [comment]
Please check this link 😃 
https://github.com/ReactiveX/reactivex.github.io/issues/130
