### ISSUE TITLE
Binding UITextFieldText

### ISSUE THREAD

**Issue by victoraugustolls** [ReactiveX/RxSwift#951]
**Short description of the issue**:

Before updating to the newest RxSwift version, I used to do something like:

```
searchTextField.rx.text
            .bindTo(viewModel.searchText)
            .addDisposableTo(disposeBag)
```

where the viewModel.searchText is a `Variable<String>("")`.

Now, it won't let me do this anymore, it stops in `searchTextField.rx.text` and I don't get anymore options.

**Expected outcome**:

Bind text field text to view model variable.

**What actually happens**:

Nothing, won't let me use previous code

**Self contained code example that reproduces the issue**:

```swift
searchTextField.rx.text
            .bindTo(viewModel.searchText)
            .addDisposableTo(disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Commit: 01e4906f389914ea9c5119955f915d2ee6a859b9

**Platform/Environment**

  - [X] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [X] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  8.0 build 8A218a
```

**Installation method**:
  - [ ] CocoaPods
  - [X] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [X] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [X] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @victoraugustolls ,

you probably want `searchTextField.rx.text.orEmpty`.

**Comment by victoraugustolls** [comment]
Yep, that was it. I knew I was missing something, but when I typed `searchTextField.rx.text.` autocomplete failed to suggest me anything. Thanks!
