### ISSUE TITLE
Retain cycle is occurring when passing in a named transform function

### ISSUE THREAD

**Issue by meacreatio** [ReactiveX/RxSwift#953]
**Short description of the issue**:

There's currently no way to declare `[weak self]` (that I know of) when passing in a named transform function to `ObservableType.map`.  As a result, the disposeBag object holds on to my ViewController and prevents `deinit` from being called.  Is there a way to overcome this from within the RxSwift framework?

**Expected outcome**:

  The disposeBag does not hold onto my ViewController and `deinit` is called when the ViewController is dismissed.

**What actually happens**:

  The disposeBag holds on to my ViewController making it impossible for `deinit `to be called when the ViewController is dismissed.

**Self contained code example that reproduces the issue**:

```
    // contrived example:

    // from within viewDidLoad()
    // causes a retain cycle
    self.buttonYes.rx.tap
            .map(self.doStuff) // I prefer this syntax but I can't use [weak self] here
            .subscribe(onNext: { (_) in
                print("done")
            })
            .addDisposableTo(self.disposeBag)

    // does not cause a retain cycle
    self.buttonYes.rx.tap
            .map { [weak self] (_) in
                self!.doStuff()
            }
            .subscribe(onNext: { (_) in
                print("done")
            })
            .addDisposableTo(self.disposeBag)

//outside viewDidLoad() in the same class
func doStuff() {
        print("doing stuff")
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  3.0.0-rc.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 8.0 (8A218a)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @meacreatio ,

this is not a bug. You shouldn't do `.map(self.doStuff)`. It looks cleaner, but it creates a retain cycle like you've noticed.

This is not a problem with Rx but with the way you are architecting your dependency chain.

**Comment by meacreatio** [comment]
@kzaher Understood.  Thanks.
