### ISSUE TITLE
Add zipped binaries to Aenea release

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveX/RxSwift#955]
It would be awesome if we could bundle built binaries with the Aenea release for Carthage https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by kzaher** [comment]
@AndrewSB 

https://github.com/Carthage/Carthage#known-issues :)

**Comment by AndrewSB** [comment]
@kzaher I thought the problem had been fixed, waiting on a response to https://github.com/Carthage/Carthage/issues/924#issuecomment-256187029

**Comment by kzaher** [comment]
I think this is not a Carthage issue but an issue with Swift itself.

Swift doesn't have stable ABI.

https://github.com/ReactiveX/RxSwift/issues/963

**Comment by kzaher** [comment]
Sorry, this will have to wait Swift 4 unfortunately.

It's not because we don't want to, it's just that platform doesn't allow it to work properly.

**Comment by AndrewSB** [comment]
Yup, you're totally right.

I'll follow up w/ Carthage to see if they have any ideas on how to mitigate using binaries compiled with  different swift versions, but yes, we'll probably have to wait until Swift 4
