### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by XXboy** [ReactiveX/RxSwift#963]
**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _3.0_

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
  Xcode8.1
```
**Installation method**:

  - [ ] Carthage

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] I have a small code base

**Comment by DenHeadless** [comment]
And this is why, until Swift 4.0 you should not use prebuilt frameworks, and build Swift frameworks from code, unfortunately.

**Comment by kzaher** [comment]
Hi @XXboy ,

as far as I can tell, you need to compile the dependencies again on Xcode 8.1.

Swift ABI isn't stable.

This is a Swift limitation.

**Comment by c0diq** [comment]
I have the same problem. Only Xcode 8.1 installed on my machine. Run carthage to rebuild from scratch and getting the same problem.
