### ISSUE TITLE
Does somebody know why travis CI often returns error 65 after

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/RxSwift#966]
```
▸ Touching AllTests-tvOS.xctest
▸ Signing build/Build/Products/Release-Tests-appletvsimulator/AllTests-tvOS.xctest
** TEST FAILED **
+++exitIfLastStatusWasUnsuccessful
+++STATUS=65
+++'[' 65 -ne 0 ']'
+++echo 65
65
+++exit 65
```

and how to make this more robust?

**Comment by moogle19** [comment]
See: https://github.com/travis-ci/travis-ci/issues/4725

A workaround to get rid of the issue is to add `sleep 5` in `after_success`

**Comment by kzaher** [comment]
I've implemented this and tried to reuse built in simulator instance. Hoping it will work in future.
