### ISSUE TITLE
value of type '[observable<UIImage)>]'has no member 'combineLatest'

### ISSUE THREAD

**Issue by JunDang** [ReactiveX/RxSwift#967]
_If you still want to report issue, please delete above statements before submitting an issue._

**Short description of the issue**:

  value of type '[observable<UIImage)>]'has no member 'combineLatest'

![screen shot 2016-10-29 at 3 34 01 pm](https://cloud.githubusercontent.com/assets/8404682/19832269/62ad58c4-9ded-11e6-8280-d483b997a7c6.png)

// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// \* that we should be able to just run the provided code without changing it.
// \* that it will reproduce the issue upon running

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 3.0.0

**Platform/Environment**

  - [* ] iOS

**Xcode version**:

8.0

**Installation method**:
  - [*] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [* ] just starting

```

**Comment by kzaher** [comment]
Hi @JunDang ,

It's now `Observable.combineLatest(array)`.

**Comment by nhatlee** [comment]
@kzaher I faced the same error, but `Observable.combineLatest(array)` not fixed the error. Image of the error: [https://ibb.co/hKSkbk](url)

**Comment by freak4pc** [comment]
It's not array for a while now. It needs to be `Observable.combineLatest(usernameValid, paswordValid)`

**Comment by sergdort** [comment]
Hi @nhatlee 
Here is signature of this version of the `combineLatest` operator
```
public static func combineLatest<C: Collection>(_ collection: C, _ resultSelector: @escaping ([C.Iterator.Element.E]) throws -> Element) -> Observable<Element>
```
In the result selector you get array of the elements emitted by source observables

**Comment by nhatlee** [comment]
@freak4pc It still have the same error :(
@sergdort : I know have this static function, but my problem is that I cannot call this function.

**Comment by freak4pc** [comment]
@nhatlee We can't help without code samples

**Comment by sergdort** [comment]
Works fine for me, make sure you are using latest version of Rx

<img width="583" alt="screen shot 2017-08-20 at 13 41 08" src="https://user-images.githubusercontent.com/4622322/29494957-fbe90d4c-85ac-11e7-85d9-050c87408216.png">

**Comment by rajkumar17** [comment]
@freak4pc 
 I getting error on filter, value not found. Let me know
   
<img width="1252" alt="Screenshot 2021-01-29 at 11 12 19 AM" src="https://user-images.githubusercontent.com/1968356/106236435-dbbdef00-6222-11eb-8fbc-a02b584cd326.png">

**Comment by freak4pc** [comment]
This is a 3 year old thread. Please use slack for help that isn't a bug with RxSwift.
