### ISSUE TITLE
Sync Reachability with main repo.

### ISSUE THREAD

**Issue by fe9lix** [ReactiveX/RxSwift#971]
Hi! I was about update to update Reachability for the example projects to match the version of the  [main repo](https://github.com/ashleymills/Reachability.swift) and noticed that the RxSwift version contains a number of changes (some Swift 3 syntax changes as well as a couple of other things – to me, it's not entirely clear from the diff what the reasoning behind certain changes was).

Wouldn't it make sense to stay in sync with the main Reachability repo, i.e. either by contributing the changes back if they contain bug fixes/improvements or simply syncing with master? (The latest version seems to work fine with Xcode 8.1 and Swift 3.0). 

@kzaher: If the modifications aren't necessary any more, I would submit a PR that uses the latest version from the main Reachability repo. As far as I can see, there are only two API changes that should be quick to update.

**Comment by kzaher** [comment]
Hi @fe9lix ,

As far as I can tell, we've only wanted to make it work with Swift 3.0. I wasn't aware of any other bugs.

I think it's ok to update it to latest version.

**Comment by fe9lix** [comment]
Ok, cheers. Created PR #972.
