### ISSUE TITLE
Migrating rxswift 2.3 to rxswift 3.0.

### ISSUE THREAD

**Issue by hoanghaKolabs** [ReactiveX/RxSwift#978]
How to migrating rxswift 2.3 to rxswift 3.0

**Comment by sergdort** [comment]
Hi, @hoanghaKolabs !

I would recommend you to take a look on [release notes](https://github.com/ReactiveX/RxSwift/releases)

**Comment by hoanghaKolabs** [comment]
Thanks, I found it.
