### ISSUE TITLE
UIRefreshControl

### ISSUE THREAD

**Issue by hrachyahakobyan** [ReactiveX/RxSwift#983]
I am writing a view controller which has a tableview, which has a UIRefreshControl. I want to fetch data from the network when the user triggers the refresh control. I pass the Driver of the refresh control to the model which calls the API and returns some data. However, I cannot seem to make the refresh control work reactively. I use it the following way just to see if it works

```

refreshControl.rx.controlEvent(.allEvents).subscribe(onNext: { _ in
            print("It worked!")
            }, onError: nil, onCompleted: nil, onDisposed: nil)
            .addDisposableTo(disposeBag)

```

and then make a Driver() out of it and pass it to the init() of my view model

```

refreshControl.rx.controlEvent(.valueChanged).asDriver()

```

but no matter how I trigger the refresh control, onNext is never called, neither my model receives any actions so no API calls are being made.
 
Am I doing something wrong? 

Thanks for the awesome work by the way.

**Comment by kzaher** [comment]
Hi @hrachyahakobyan ,

this might provide some insight

https://github.com/ReactiveX/RxSwift/pull/906
