### ISSUE TITLE
UICollectionView rx_contentOffset and UICollectionViewDelegateFlowLayout

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#99]
When I use rx_contentOffset and have implementation of UICollectionViewDelegateFlowLayout its crashs on :

[RxCocoa.RxCollectionViewDelegateProxy collectionView:layout:sizeForItemAtIndexPath:]: unrecognized selector sent to instance 

Should I use also collectionView.rx_setDelegate(self) ?

**Comment by kzaher** [comment]
Hi @sergdort ,

if you are using any of the methods with rx_*, then you should use `view.rx_setDelegate`. 

We install our custom proxy for delegate so we can intercept observed events.

That proxy forwards all implemented selectors so this should work.

Have you used that `rx_setDelegate` and still doesn't work?

This is actually a good suggestion for us to document. I understand why people would be confused with this.

Hope this helps.

**Comment by sergdort** [comment]
Hi @kzaher yep, still getting crash.

So this is how I setup my collection view

self.models
         >- self.collectionView.rx_subscribeItemsTo(cellFactory)
         >- disposeBag.addDisposable
      self.collectionView.rx_setDelegate(self)
      self.collectionView.rx_contentOffset
         >- subscribeNext(handelOffset)
         >- disposeBag.addDisposable

Where self is viewcontroller which implements UICollectionViewDelegateFlowLayout protocol

**Comment by kzaher** [comment]
I think there is an issue with our proxy not confirming to `UICollectionViewDelegateFlowLayout` and thus not forwarding the events.

I'm assuming this is the case.

I'll need to investigate it :(

**Comment by sergdort** [comment]
Hey, @kzaher  I was able to fix this on my side just by conforming also RxCollectionViewDelegateProxy to UICollectionViewDelegateFlowLayout, please find it in pull request https://github.com/ReactiveX/RxSwift/pull/103

**Comment by kzaher** [comment]
Well release this in a patch release next week, so we can close it then. Thnx for your help.

**Comment by sergdort** [comment]
NP man, cool library by the way, love it! :)

**Comment by kzaher** [comment]
This should be out in RxSwift-2.0-alpha.1 :)
