### ISSUE TITLE
combineLatest(array) did not work

### ISSUE THREAD

**Issue by JunDang** [ReactiveX/RxSwift#990]
**Short description of the issue**:
use Observable.combineLatest(array), however, it did not work. Please see below codes:

![screen shot 2016-11-08 at 1 06 08 pm](https://cloud.githubusercontent.com/assets/8404682/20111882/fd4cc168-a5b7-11e6-975c-16d584bbc113.png)

Previously, with Swift 2.0 and older version of RxSwift, I used 

.flatMap{$0.count == 0 ? Observable<[Field]>.just([]) : $0.map{self.webService.retrieveField(token, field_id: $0)}.combineLatest{$0} }

NOW, I am using Swift 3.0 and RxSwift 3.0, I changed it to Observable.combineLatest(array): 

 .flatMap{$0.count == 0 ? Observable<[Field]>.just([]) : Observable.combineLatest($0.map{self.webService.retrieveField(token, field_id: $0)}){return $0}}

 However, the following never get called:

.subscribe(onNext: {[unowned self] (fields) -> Void in
                    let ids = self.fieldList.map{$0.id}
                    print(ids)
                    CoreData.deleteMultipleObjects("Fields", ids: ids)
                    for field in fields {
                        CoreData.insertObject(field)
                    }
                    self.fieldList = fields
                    self.tableView.reloadData()
                    CoreData.setRereshtime("Fields", refresh_time: Date())
                    progressHUD.removeFromSuperview()

Please help!

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
    3.0

**Platform/Environment**

  - [x] iOS
  

**Xcode version**:
  8.0
```

**Installation method**:
  - [x] CocoaPods


**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [*] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [*] just starting

**Comment by kzaher** [comment]
Hi @JunDang ,

I would assume your we service failed with error.
