### ISSUE TITLE
Why is the NSControl.rx.value static func non-public?

### ISSUE THREAD

**Issue by angerman** [ReactiveX/RxSwift#991]
**Short description of the issue**:

When creating a custom ControlProperty

**Expected outcome**:

Can use `NSControl.rx.value(base, getter, setter)`

**What actually happens**:

Can **not** use `NSControl.rx.value(base, getter, setter)`

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

--- 
See `RxCocoa/macOS/NSControl+Rx.swift`

Why can't `value` be public?

**Comment by pblondin** [comment]
I'm currently facing the exact same issue. Please let us know if there is a way around this. Thanks!

**Comment by pblondin** [comment]
Finally I've found the solution as explained here [681](https://github.com/ReactiveX/RxSwift/issues/681)

In case your project is in Swift3, here is the snippet for valuePublic

```swift
extension UIControl {
    static func valuePublic<T, ControlType: UIControl>(control: ControlType, getter:  @escaping (ControlType) -> T, setter: @escaping (ControlType, T) -> ()) -> ControlProperty<T> {
        let values: Observable<T> = Observable.deferred { [weak control] in
            guard let existingSelf = control else {
                return Observable.empty()
            }
            
            return (existingSelf as UIControl).rx.controlEvent([.allEditingEvents, .valueChanged])
                .flatMap { _ in
                    return control.map { Observable.just(getter($0)) } ?? Observable.empty()
                }
                .startWith(getter(existingSelf))
        }
        return ControlProperty(values: values, valueSink: UIBindingObserver(UIElement: control) { control, value in
            setter(control, value)
        })
    }
}

```

**Comment by AppsTitude** [comment]
Merci Philippe !
