### ISSUE TITLE
Module compiled with Swift 3.0.1 cannot be imported in Swift 2.3

### ISSUE THREAD

**Issue by Joe2Code** [ReactiveX/RxSwift#993]
**Short description of the issue**: 
Been updating a project to Swift 3.0 (and now 3.0.1) and running into an error for RxSwift "Module complied with Swift 3.0.1 cannot be imported in Swift 2.3"

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
3.0.0

**Platform/Environment**
  - [x] iOS
  
  Xcode version goes here
   8.1 GM
**Installation method**:
  - [x] Carthage

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (8.0 and 8.1GM, which I'm currently using -- have switched between both with no changes)

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting

**Comment by kzaher** [comment]
Hi @Joe2Code ,

I think this is just how Swift compiler/environment works. There is no ABI compatibility.

**Comment by Joe2Code** [comment]
I'm not 100% sure this solved the issue, but I switched "Generate Legacy Test Coverage Files" and "Use Legacy Swift Language Version" both to "NO" and the error went away.

Thanks for the info about the lack of Swift ABI compatibility.
