### ISSUE TITLE
Memory Leaks with the latest Demo

### ISSUE THREAD

**Issue by foxsin10** [ReactiveX/RxSwift#994]
**Short description of the issue**:

 Memory leaks found

**Expected outcome**:

  fix leaks

**What actually happens**:

    Just found some leaks.
    I run my code with Instruments to check if there were memory leaks. 
    The code below were written in an UIViewController. When I run my code with Simulator, the method of "deinit" worked well. But when I run it with Instruments, the console printed some leaks.
    I also found leaks when I run the latest Demo.

**Self contained code example that reproduces the issue**:

``` 
        var dataSource = Variable([String]())

        for i in 0 ..< 100 {
              dataSource.value.append("\(i)")
        }

        dataSource
            .asObservable()
            .bindTo(listTableView.rx.items(cellIdentifier: "YZActiveUserTableViewCell", cellType: YZActiveUserTableViewCell.self)) {
            [unowned self](row, element, cell) in
            cell.index = row
            let longtap = UILongPressGestureRecognizer.init(target: self, action: #selector(self.needTopresentPopView(with:)))
            longtap.minimumPressDuration = 1
            cell.addGestureRecognizer(longtap)
        }
        .addDisposableTo(bag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  RxSwift 3.0.1
  RxCocoa 3.0.1

**Platform/Environment**

   iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**
   
  easy, 100% repro

**Xcode version**:

```
  Xcode 8.1
```

**Installation method**:
  CocoaPods

**I have multiple versions of Xcode installed**:

   no

**Level of RxSwift knowledge**:
 

    I have a small code base

**Comment by kzaher** [comment]
Hi @foxsin10 ,

I've just checked with memory profiler on `SimpleTableViewExampleViewController` inside RxExample app and as far as I can tell there are no memory leaks.

The only thing that happens is that `let tableViewDataSourceNotSet = TableViewDataSourceNotSet()` gets lazy loaded on first use, but that's not a leak.

What do you think we have leaks? Can you be more specific?

**Comment by foxsin10** [comment]
Hi @kzaher ,

Thanks for answering.
When I run RxExample app, I set `SimpleTableViewExampleViewController ` to the `Initial View Controller`, and I implemented it as `UIViewController`. 
Here is the screenshot.
see: 
<img width="1258" alt="simple 2x" src="https://cloud.githubusercontent.com/assets/11630650/20201490/692c15cc-a7f3-11e6-97d3-bcf84c680e18.png">

And then I set `SimpleTableViewExampleSectionedViewController` to the `Initial View Controller`, which also was implemented as `UIViewController`.
The results is here:
<img width="1160" alt="sectioned 2x" src="https://cloud.githubusercontent.com/assets/11630650/20201561/05001e62-a7f4-11e6-9e93-20a6741f2333.png">
<img width="947" alt="sectioned2 2x" src="https://cloud.githubusercontent.com/assets/11630650/20201571/1bd136e4-a7f4-11e6-88e7-5eb3dd8d13d1.png">

But, the `deinit` method worked well after I clicked the navigationbackbutton when the `Initial View Controller` was set to the navigationcontroller, which confused me. Normally, if there exists a leak in `UIViewController`, the `deinit` method won't work.

**Comment by kzaher** [comment]
Hi @foxsin10 ,

Leaks tool in unreliable IMHO and I wouldn't recommend using it.

Most optimal way to test for memory leaks is:
        * navigate to your screen and use it
        * navigate back
        * create memory snapshot (Mark Generation)
        * navigate second time to your screen and use it
        * navigate back
        * create memory snapshot (Mark Generation)
        * observe difference in allocated objects

<img width="977" alt="screen shot 2016-11-12 at 00 26 13" src="https://cloud.githubusercontent.com/assets/1641148/20233299/a635535e-a86e-11e6-919c-15a2c217cbda.png">

`CFBasicHash` and `<non-object>` are part of the way UIKit handles events and they disappear over time, or at least they should :)

If there was some leak here caused by our code, that list would contain instances of .... for example `UITableViewCell`, `UITableView` or `Rx*` classes.

**Comment by foxsin10** [comment]
Ok, get it .
