### ISSUE TITLE
Probably,RecursiveImmediateScheduler has bug.

### ISSUE THREAD

**Issue by shiratsu** [ReactiveX/RxSwift#995]
**Short description of the issue**:

I'm sorry if my issue is not bug.

I got receive crash report from crashlytics on my application.
I suspect that RecursiveImmediateScheduler brings crash.
```
// immediate scheduling
    
    /// Schedules an action to be executed recursively.
    ///
    /// - parameter state: State passed to the action to be executed.
    func schedule(_ state: State) {

        var isAdded = false
        var isDone = false
        
        var removeKey: CompositeDisposable.DisposeKey? = nil
        let d = _scheduler.schedule(state) { (state) -> Disposable in
            // best effort
            if self._group.isDisposed {
                return Disposables.create()
            }
            
            let action = self._lock.calculateLocked { () -> Action? in
                if isAdded {
                    self._group.remove(for: removeKey!)
                }
                else {
                    isDone = true
                }
                
                return self._action
            }
            
            if let action = action {
                action(state, self.schedule)
            }
            
            return Disposables.create()
        }
        
        _lock.performLocked {
            if !isDone {
                removeKey = _group.insert(d)
                isAdded = true
            }
        }
    }
```
I suspect that this Forced Unwrapping brings crash rarely.
```
self._group.remove(for: removeKey!)
```

**Expected outcome**:

I think if nsurlsession is called,this crash would happen rarely.

**What actually happens**:

I attached bug capture.
<img width="1153" alt="2016-11-11 18 26 16" src="https://cloud.githubusercontent.com/assets/918490/20211979/374a32cc-a844-11e6-825a-120f7f3997b5.png">

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
// If we can't get a self contained code example that reproduces the issue, there is a big chance we won't be able
// to help you because there is not much we can do.
//
// `Self contained code example` means:
//
// * that we should be able to just run the provided code without changing it.
// * that it will reproduce the issue upon running
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift version is 2.6.0.
However i think currenct version has same bug.

**Platform/Environment**

  - [○ ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ○] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version is 8.0.
```

**Comment by kzaher** [comment]
Hi @shiratsu ,

Interesting report. 

I guess it's possible that there is a bug in our codebase, but if it is, I don't think it's in the place where you suspect it to be.

If this was the case
```
self._group.remove(for: removeKey!)
```

then it would crash with unwrapping implicitly unwrapped optional error instead of `swift_release_dealloc`.

`isAdded` is only set to true when removeKey set. I'll try to improve readability of that code so people aren't confused when reading the code.

If you could provide me with some self contained code that causes a crash, that would be great, I'll also try to investigate this.

**Comment by kzaher** [comment]
I've ran this code

```
let scheduler = ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: .UserInitiated)
        let xs = Observable<Int>.create { o in
            o.on(.Next(1))
            o.on(.Completed)
            return NopDisposable.instance
            }
        .observeOn(scheduler)

        for i in 0 ..< 8 {
            scheduler.schedule(0) { _ in
                for i in 0 ..< 1000000 {
                    xs.subscribe { e in
                        print(e)
                    }
                }
                return NopDisposable.instance
            }
        }
```

from 2.6.0 release on iPhone6S with latest iOS 10.1 in Release mode and can't get a crash. I've left the test running for a couple of minutes.

I've also ran the same test on iOS Simulator and on master branch.

In all cases I couldn't repro this.

If somebody has some stress test that can repro this, please let me know.

**Comment by kzaher** [comment]
I've found a possible race condition so I think you might be right after all.

I can't repro it in any way but I've pushed a fix that I think should solve it.

¯\\\_(ツ)\_/¯

**Comment by shiratsu** [comment]
Oh,I'm sorry.I just realized your reply.
Thank you for your understanding and updating.

I will use it.
