### ISSUE TITLE
Ambiguous reference to member 'text' for UITextField.rx.text

### ISSUE THREAD

**Issue by lizixroy** [ReactiveX/RxSwift#996]
After upgraded to XCode 8.1(8B62), I get this error "Ambiguous reference to member 'text'" everywhere I use rx.text. 

For example:
```
        passwordTextField.rx.text.subscribe(onNext: {
        // do something here ...
        }).addDisposableTo(disposeBag)
```

This is an error and the project cannot be compiled. Any idea on how to fix this?

**Comment by rcoppolo** [comment]
Hi @lizixroy! What was the solution here? (Running into the same thing…)

**Comment by lizixroy** [comment]
Hi,

It turned out that this error was caused by us having a "text" property in one of our own classes that conform to Rx's protocols. 

It's not a RxSwift problem. 

Make sure to check for the same problem in your codebase.

Roy

iPhone$B$+$iAw?.(B

2016/11/15 20:46$B!"(BRyan Coppolo <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by bertadevant** [comment]
Hi, 

I am having a similar problem but when trying to bind a collectionView 

`.bindTo(lectureViewList.rx.items)`

It says ambiguous reference to member items. The thing is that I used this binding method before on the same project and it works there so I do not know why it does not work here. Any ideas?

**Comment by kzaher** [comment]
The problem is probably cause by the fact we've changed `rx.text` to be `ControlProperty<String?>`.

For that purpose we've added `orEmpty` extension.

Just use:

```
passwordTextField.rx.text.orEmpty.subscribe(onNext: {
})
```

**Comment by nim23** [comment]
@bertadevant did you manage to solve your issue. I am running into the same issue.

**Comment by Yogesh-Bhatt** [comment]
Hi,
I am also facing  similar problem  when trying to bind a UITableView : 
.bindTo(tableView.rx.items)

**Comment by nim23** [comment]
@Yogesh-Bhatt If this is of any help, I got around the issue here, https://github.com/nim23/pokedex-reactivex/blob/master/Pokedox/MainViewController.swift#L33. The closure made the compiler error go away. I basically took it from here https://github.com/ReactiveX/RxSwift/blob/44cee5305013247a1e83d1adb8630de68e0a8ac5/RxCocoa/iOS/UITableView%2BRx.swift#L37.

**Comment by Yogesh-Bhatt** [comment]
**@nim23** Thanks for quick reply but I am also using closure and its showing me same compile error. I am not sure what wrong is happening here.

![screen shot 2017-01-22 at 8 05 13 pm](https://cloud.githubusercontent.com/assets/1204372/22183207/5e788164-e0de-11e6-90bf-481e61cd0d6d.png)

**Comment by billionssg** [comment]
temporary solution from me: put text into a variable first, then call the subscribe

example:

`var text = textField.rx.text

text.subscribe(onNext:{ (typedText) in
            //do something here
        }).addDisposableTo(disposeBag)`

**Comment by aventurella** [comment]
I get the same thing under Xcode 8.3 (Swift 3.1) with `NSButton.rx.tap`.  The temp variable solution doesn't seem to work for me.

![error](https://cloud.githubusercontent.com/assets/75315/24572818/31792b2c-1631-11e7-8c49-4d2719f41a57.png)

**Comment by petrovRV** [comment]
import UIKit
import RxSwift
import RxCocoa

class ViewController: UIViewController {
    
    @IBOutlet weak var txtField: UITextField!
    @IBOutlet weak var btn: UIButton!
    
    let disposeBag = DisposeBag()
    let txtFieldText = Variable("")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        txtField.rx.text.bindTo(txtFieldText).addDisposableTo(disposeBag)
    }
}

Hello, guys. I've got the code but it doesn't work. How can I it fix?

**Comment by bertadevant** [comment]
Hi @petrovRV you are binding a variable to a text field? as in the textfield is the driving force? it should change the variable? 

Because if yes, it should change the variable then you have to bind it to the txtFieldText.value not the variable itself. 

If your textField is not mean to change the variable but the variable has to change the textField you need to `txtFieldText.asObservable().bind(to: txtField.rx.text)`

Most of the times you have this ambiguous reference issue is because the result you are trying to bind is not in the right format. If value still gives you issues try adding a `.map { $0 } ` before bidding and make sure you are getting a string not a Reactive<String> 

Hope it helps!

**Comment by petrovRV** [comment]
bertadevant, sorry but I don't very understand about you said. I want repeat example with video [https://www.youtube.com/watch?v=P0nNsmFe81k&t=749s](url) (11:17 to 12:30)

**Comment by petrovRV** [comment]
I use that code

import UIKit
import RxSwift
import RxCocoa

class ViewController: UIViewController {
    
    @IBOutlet weak var txtField: UITextField!
    @IBOutlet weak var btn: UIButton!
    
    let disposeBag = DisposeBag()
    let txtFieldText = Variable("")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        txtFieldText.asObservable().map { $0 }.bind(to: txtField.rx.text).addDisposableTo(disposeBag)
        
        txtFieldText.asObservable().subscribe(onNext: {
            print($0)
        }).addDisposableTo(disposeBag)
    }
}

but I get an error [photo](https://drive.google.com/open?id=0B2uKHFTccFnWekFvX0dVbDlNVFk)

**Comment by Guacaswole** [comment]
FYI, future people reading this.  The reason for getting @bertadevant 's issue is that basically the swift compiler can figure out the inputs / return types of the closure so you have to be explicit and the error message should go away

**Comment by JaapWeijland** [comment]
billionssg fix worked for me. Xcode wouldn't autocomplete textField.rx.text, so I couldn't .bind(to:) it.

**Comment by pedro-alonsod** [comment]
Same error with RxCocoa 4.1.2: 
`demoTextField.rx.text.orEmpty
            .bind(to: demoTextLabel.rx.text)
            .disposed(by: disposeBag)`
gives:

` Ambiguous reference to member 'text'

 Found this candidate (RxCocoa.Reactive<Base>)

 Found this candidate (RxCocoa.Reactive<Base>)

Found this candidate (RxCocoa.Reactive<Base>)

 Found this candidate (RxCocoa.Reactive<Base>)`
